### ISSUE TITLE
Is the homepage of the site also editable?

### ISSUE THREAD

**Issue by konklone** [usnistgov/800-63-3#1]
I found a grammar typo on https://pages.nist.gov/800-63-3/ that I wanted to submit a pull request for, but I can't find that text in this repository.

**Comment by jimfenton** [comment]
Which branch are you looking at? What's on pages.nist.gov comes from the nist-pages branch, but hopefully master isn't far behind. Or just tell us where it is...

**Comment by konklone** [comment]
Ooooh, I missed the `nist-pages` branch. It's there - thank you.
