### ISSUE TITLE
Adding city-provided social workers with biometric devices 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1000]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.3.4, 1
 
**Comment (Include rationale for comment)**:  Adding city-provided social workers with biometric devices
 
"The CSP MAY use trusted referees, such as notaries, legal guardians, medical professionals, conservators, persons with power of attorney, or some other form of trained and approved or certified individuals that can vouch for or act on behalf of the applicant in accordance with applicable laws, regulations, or agency policy. The CSP MAY use a trusted referee for both remote and in-person processes." Maybe after power of attornery, put city provided social workers with biometric devices for registering people who have no other means of registration.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
It looks like the suggested change is at the end of the issue.  However, this is just a list of examples. Agency can determine who qualifies as a trusted ref.
