### ISSUE TITLE
maybe add - The records shall be encrypted using approved cryptographic means. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1001]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.2.5, 1
 
**Comment (Include rationale for comment)**:  maybe add -  The records shall be encrypted using approved cryptographic means.

 
"CSPs shall comply with their respective records retention policies in accordance with whatever laws and regulations apply to those entities. If the CSP opts to retain records in the absence of any legal requirements, the CSP SHALL conduct a privacy risk assessment to determine how long records should be retained." maybe add -  The records shall be encrypted using approved cryptographic means.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The need for encryption is both a security and privacy concern, and is addressed by 4.2.4, which references the 800-53 moderate baseline.
