### ISSUE TITLE
Appreciate this section highlighting the privacy risks, mitigations, AND enhancements from federation 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1002]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 9, 
 
**Comment (Include rationale for comment)**:  Appreciate this section highlighting the privacy risks, mitigations, AND enhancements from federation
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Thank you!
