### ISSUE TITLE
Suggest emphasizing that only federation enables this privacy enhancement -- in other words, federation can enhance privacy 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1003]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 9.3, 
 
**Comment (Include rationale for comment)**:  Suggest emphasizing that only federation enables this privacy enhancement -- in other words, federation can enhance privacy
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Will add a sentence making this point.
