### ISSUE TITLE
Similar to 9.3, only federation enables this privacy enhancement 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1004]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 9.5, 
 
**Comment (Include rationale for comment)**:  Similar to 9.3, only federation enables this privacy enhancement
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
We think that the section title "Blinding in Proxied Federation" already makes this point.
