### ISSUE TITLE
General concerns 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1005]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: General, 
 
**Comment (Include rationale for comment)**:  General concerns
 
The new guidance does not address the needs of fraud detection mechanisms 
Our primary concern is that privacy requirements state“…collect only the minimum information required to verify the individuals identity…”
Depending on how we interpret “the minimum amount of information needed to verify an identity” there could significant impacts in our ability to detect and monitor fraud activities

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We actually do.  There is a requirement in -A:

`The CSP SHOULD obtain additional confidence in identity proofing using fraud mitigation measures, for example inspecting geolocation, examining the device characteristics of the applicant, evaluating behavioral characteristics, or checking vital statistic repositories such as the Death Master File, so long as any additional mitigations do not substitute for the mandatory requirements contained herein and the CSP SHALL conduct a privacy risk assessment of these mitigation measures. Such assessments SHOULD include any privacy risk mitigations (e.g., limited retention, use limitations, notice, etc.) or other technological mitigations (e.g. cryptography).`
