### ISSUE TITLE
Remove bullet 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1006]
**Organization Name (N/A, if individual)**: DCMA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 6.2., 
 
**Comment (Include rationale for comment)**:  Remove bullet
 
Follow standard document formatting. See Section 5.4

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE with changes to Ch.6. See #597
