### ISSUE TITLE
Delete "as" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1011]
**Organization Name (N/A, if individual)**: DCMA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 8.6., 1
 
**Comment (Include rationale for comment)**:  Delete "as"
 

**Suggested Change**: To read, "and advise"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Fixed by dacaa26
