### ISSUE TITLE
Replace "5" with "(5)" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1012]
**Organization Name (N/A, if individual)**: DCMA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 9.3., 2
 
**Comment (Include rationale for comment)**:  Replace "5" with "(5)"
 
Consistency

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
