### ISSUE TITLE
Replace asterisks with bullets and make each bullet start on its own line 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1013]
**Organization Name (N/A, if individual)**: DCMA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 9.4., 2
 
**Comment (Include rationale for comment)**:  Replace asterisks with bullets and make each bullet start on its own line
 
Consistency

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Bullets are rendering properly.
