### ISSUE TITLE
DoD mandates changing memorized secrets periodically. This is in violation of DoD regulations. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1016]
**Organization Name (N/A, if individual)**: DCMA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.1.2., 8
 
**Comment (Include rationale for comment)**:  DoD mandates changing memorized secrets periodically. This is in violation of DoD regulations.
 

**Suggested Change**: Recommend changing to state that it must be in compliance with government/organization regulations.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The referenced guideline is a SHOULD NOT, meaning that agencies may continue this practice even though it is discouraged. Based on current research, requiring periodic changes to memorized secrets has at best a negligible positive effect, and may actually be detrimental to security. The guideline will remain; it is a given that agencies must be in compliance with other government/organization regulations.
