### ISSUE TITLE
Rephrase "limit online attackers to no more than 100 consecutive failed attempts" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1018]
**Organization Name (N/A, if individual)**: DCMA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.2., 1
 
**Comment (Include rationale for comment)**:  Rephrase "limit online attackers to no more than 100 consecutive failed attempts"
 

**Suggested Change**: Recommend changing to state that it must be in compliance with government/organization regulations.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The limit of 100 consecutive failed attempts is determined by limiting the likelihood of an online guessing attack based on the estimated complexity of the secret being entered. As with other guidelines in the document, agencies may impose more stringent requirements.
