### ISSUE TITLE
DoD does not permit the option to display text during entry. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1020]
**Organization Name (N/A, if individual)**: DCMA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 10.1., 5
 
**Comment (Include rationale for comment)**:  DoD does not permit the option to display text during entry.
 

**Suggested Change**: Recommend changing to state that it must be in compliance with government/organization regulations.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by ychoong** [comment]
As with other guidelines in this document, agencies may impose more stringent requirements in order to further reduce authentication risk.
