### ISSUE TITLE
Recommend deletion of this bullet: "Support of copy and paste in fields for entering memorized secrets" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1022]
**Organization Name (N/A, if individual)**: DCMA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 10.2.1., 4
 
**Comment (Include rationale for comment)**:  Recommend deletion of this bullet: "Support of copy and paste in fields for entering memorized secrets" 
 

**Suggested Change**: This encourages users to write down/store passwords thus increasing the likelihood of compromise.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by ychoong** [comment]
Having copy and paste feature is clarified in section 5.
