### ISSUE TITLE
Rephrase: "Provide clear, meaningful and actionable feedback when chosen passwords are rejected (e.g., when it appears on a “black list” of unacceptable passwords or has 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1026]
**Organization Name (N/A, if individual)**: DCMA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 10.2.1., 5
 
**Comment (Include rationale for comment)**:  Rephrase: "Provide clear, meaningful and actionable feedback when chosen passwords are rejected (e.g., when it appears on a “black list” of unacceptable passwords or has been used previously)."
 

**Suggested Change**: Recommend changing to state that it must be in compliance with government/organization regulations.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by ychoong** [comment]
This is informative, not normative.
