### ISSUE TITLE
Fix spacing on sub-bullet 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1027]
**Organization Name (N/A, if individual)**: DCMA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 10.2.9., 2
 
**Comment (Include rationale for comment)**:  Fix spacing on sub-bullet
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
