### ISSUE TITLE
Rephrase items listed above where recommended changing to government regulation compliance. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1028]
**Organization Name (N/A, if individual)**: DCMA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Table 10-1, 
 
**Comment (Include rationale for comment)**:  Rephrase items listed above where recommended changing to government regulation compliance.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by ychoong** [comment]
This section is informative, not normative.
