### ISSUE TITLE
Complexity 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1029]
**Organization Name (N/A, if individual)**: DCMA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Appendix A, A.3.
 
**Comment (Include rationale for comment)**:  Complexity
 

**Suggested Change**: Delete heading or add supporting verbiage
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
There are three paragraphs of content discussing complexity of memorized secrets in Appendix A.3. We don't understand this comment.
