### ISSUE TITLE
Delete "and" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1031]
**Organization Name (N/A, if individual)**: DCMA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 4.2., 5
 
**Comment (Include rationale for comment)**:  Delete "and"
 

**Suggested Change**: To read, "conduct analysis" or "conduct an analysis" to follow sentence structure of item #3.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Fixed by #600.
