### ISSUE TITLE
Insert "by" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1033]
**Organization Name (N/A, if individual)**: DCMA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 10.1.1., 2
 
**Comment (Include rationale for comment)**:  Insert "by"
 

**Suggested Change**: To read, "...owned by the patient..."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
