### ISSUE TITLE
Since these measures and controls are not mandatory requirements, NIST should allow flexibility in the identity proofing and authentication processes when these controls are put 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1036]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: General, 
 
**Comment (Include rationale for comment)**:  Since these measures and controls are not mandatory requirements, NIST should allow flexibility in the identity proofing and authentication processes when these controls are put in place. 
 
In addition to having strong authentication protocols, SSA has dynamic fraud detection process and a robust infrastructure in place. All of these areas together help SSA to avoid impersonation during identity proofing or compromise of an existing account. 

The threat mitigation measures and compensating controls provide additional confidence in the user's identity and per NIST, are recommended but only optional. Use of these measures and controls should be reflected in the requirements.  

**Suggested Change**: Since these measures and controls are not mandatory requirements, NIST should allow flexibility in the identity proofing and authentication processes when these controls are put in place. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE with April 1 update to -3
