### ISSUE TITLE
Recommend that OMB provide additional guidelines extending the timeframe to become compliant with these guidelines. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1037]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: General, 
 
**Comment (Include rationale for comment)**:  Recommend that OMB provide additional guidelines extending the timeframe to become compliant with these guidelines.
 
These guidelines are well above-and-beyond the existing guidelines in place today. Implementing these guidelines will take much longer than the timeframe provided in OMB M-14-04.

This will become onerous to any agency to develop processes that are both practical and economical in the one year timeframe.

**Suggested Change**: Recommend that OMB provide additional guidelines extending the timeframe to become compliant with these guidelines.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We cannot accept this on behalf of OMB, but we will share this issue with them.
