### ISSUE TITLE
Definition of "Remote" indicates the note: "Any information exchange across the Internet is considered remote". 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1038]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 3, 
 
**Comment (Include rationale for comment)**:  Definition of "Remote" indicates the note: "Any information exchange across the Internet is considered remote". 
 
It is unclear if this includes tunneled connections (e.g., virtual private networks) where the information is reliably protected end-to-end by a single organization's security controls.

Security implications

**Suggested Change**: Clarify the meaning of the note
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will remove the note
