### ISSUE TITLE
Document states, "In the event a CSP ceases to conduct identity proofing and enrollment processes, the CSP SHALL be responsible for fully disposing of or 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1039]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.2, 
 
**Comment (Include rationale for comment)**:  Document states, "In the event a CSP ceases to conduct identity proofing and enrollment processes, the CSP SHALL be responsible for fully disposing of or destroying any sensitive date including PII, or its protection…" 
 
This sentence is suggesting a difference between sensitive data and PII. 

**Suggested Change**: Provide additional clarification on what NIST defines as 'sensitive data'
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
We will remove the term 'sensitive data', because the primary concern from the standpoint of this document is privacy.
