### ISSUE TITLE
Issuing source vs. Authoritative source. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1040]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.2.2.1, Table 5-2
 
**Comment (Include rationale for comment)**:  Issuing source vs. Authoritative source. 
 
Where able, allow CSPs to validate identity evidence with information held or published by the authoritative source as opposed to the issuing source for all strengths of evidence. Validating evidence with the issuing source is far more restrictive and may even be impossible. Allowing CSPs to validate with authoritative sources provides the same level of confidence with added flexibility. 

**Suggested Change**: "Details have been confirmed as valid by comparison with information held or published by the authoritative source."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #582
