### ISSUE TITLE
Document states, "the CSP SHALL NOT use attributes collected and maintained in the identity proofing process for any purpose other than identity proofing, authentication or 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1042]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.2, Item 5, 
 
**Comment (Include rationale for comment)**:  Document states, "the CSP SHALL NOT use attributes collected and maintained in the identity proofing process for any purpose other than identity proofing, authentication or attribute assertions; or to comply with law or legal process unless [consent provided]."
 
We recommend this section explicitly allow the use of attributes collected and maintained to maintain the integrity of the system (e.g., to identify fraud and abuse). This recommendation is consistent with the Fraud Reduction and Data Analytics Act of 2015.

**Suggested Change**: Replace with (inserted text in bold) "The CSP SHALL NOT use attributes collected and maintained in the identity proofing process for any purpose other than identity proofing, authentication, authorization or attribute assertions; for operating security and integrity controls; or to comply..."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Analogous to #1058
