### ISSUE TITLE
We recommend updating Item 8 in the list of requirements to be informed by security and fraud risks, rather than exclusively based on privacy considerations. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1043]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.2, Item 8, 
 
**Comment (Include rationale for comment)**:  We recommend updating Item 8 in the list of requirements to be informed by security and fraud risks, rather than exclusively based on privacy considerations. 
 
Conducting a security risk assessment is integral to determining the specified requirements.

**Suggested Change**: Replace with "The CSP SHALL conduct privacy, fraud and security risk assessments to determine…"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Analogous to part of #1057.
