### ISSUE TITLE
SSA has a substantial population of users enrolled in our online services. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1044]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: General, 
 
**Comment (Include rationale for comment)**:  SSA has a substantial population of users enrolled in our online services. 
 
These users have been identity proofed following previous NIST SP 800-63 requirements, often taking additional steps to verify the identity beyond the mandatory requirements. 800-63-3 does not provide any guidance on how to handle these subscribers.

In addition to routine fraud analytics, the mere passage of time since the account was created indicates a legitimate account.

**Suggested Change**: Add guidance that states users identity proofed and enrolled under former guidance do not need to meet the mandatory requirements under 63-3.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
A section in -3 about risk based assessment before migrating users.

**Comment by paul-grassi** [comment]
Resolved via April 1 update to -3
