### ISSUE TITLE
"At a minimum, the applicant must be verified by a process that is able to achieve a strength of STRONG." 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1045]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.7, 
 
**Comment (Include rationale for comment)**:  "At a minimum, the applicant must be verified by a process that is able to achieve a strength of STRONG."
 
Unlike validation requirements for IAL 2, which state, "Each piece of evidence must be validated with a process that is able to achieve the same strength as the evidence provided," the verification requirements state, "At a minimum, the applicant must be verified by a process that is able to achieve a strength of STRONG." These are two separate things.

Per 800-63-3, we validate evidence, but we verify the applicant. According to Table 5.3, we verify "identity evidence", not the "applicant". In order to achieve a strength of strong, we will have to confirm the applicant's ownership of the claimed identity through a physical or biometric comparison. As written, no one will ever use KBV since it will not/cannot achieve a strength of STRONG (required for LOA2, LOA1 does not identity proof), since it can only be used to verify adequate/fair evidence. 

**Suggested Change**: Clarify this section. If we collect multiple pieces of evidence, we should only have to verify/bind the evidence to the user for one piece. Anything more is too burdensome for our users. Allow the CSP to verify any one of the collected pieces of evidence at the strength of that evidence. If an adequate/fair piece of evidence is provided, allow CSP to verify with KBV. In this scenario, if fair/adequate evidence is provided, then there was also a STRONG piece of evidence provided.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We agree that the language is not clear and should be adjusted, especially that verification talks about evidence and not binding to the identity.  However, we don't agree with the suggested change.  We will clarify this section.
