### ISSUE TITLE
"The CSP MAY perform remote identity proofing. The CSP SHOULD offer both in-person and remote proofing." 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1046]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.4.1.5, 
 
**Comment (Include rationale for comment)**:  "The CSP MAY perform remote identity proofing.  The CSP SHOULD offer both in-person and remote proofing."
 
This is internally inconsistent -- if the CSP SHOULD offer both in-person and remote IdP, it follows that it SHOULD perform remote IdP.

**Suggested Change**: Clarify if CSPs SHOULD or MAY provide remote identity proofing.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #667
