### ISSUE TITLE
Document is conflicting when addressing address confirmation: it states that the address must be "found on any supplied, valid piece of identity evidence" vs. "found 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1047]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.4.1.6, 
 
**Comment (Include rationale for comment)**:  Document is conflicting when addressing address confirmation: it states that the address must be "found on any supplied, valid piece of identity evidence" vs. "found in records". 

 
Need to ensure address is verified via records or found on identity evidence. 

**Suggested Change**: •The CSP SHALL confirm address of record through validation of the address contained on any supplied, valid piece of identity evidence or found in records.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #642
