### ISSUE TITLE
Document states, "If the CSP performed remote proofing: The applicant SHALL present a valid enrollment code to complete the identity proofing process." 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1048]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.4.1.6, 
 
**Comment (Include rationale for comment)**:  Document states, "If the CSP performed remote proofing: The applicant SHALL present a valid enrollment code to complete the identity proofing process."  
 
We recommend removing the "enrollment code" requirement for remote proofing. If the address of record is digital, this can be done with a link to the address of record of the applicant, which would increase usability without decreasing security. 

**Suggested Change**: Instead of specifically stating the CSP must send an "enrollment code", refer to it as "verification" since that means "binding". This could be a link or a code.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
The comment, as described, is a valid implementation of an enrollment code (provided it meets the entropy requirements). The suggested change does not address the comment.
