### ISSUE TITLE
Document states, "Validation against a third party data service shall only be used for one piece of presented identity evidence." 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1049]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.4.1.3, 
 
**Comment (Include rationale for comment)**:  Document states, "Validation against a third party data service shall only be used for one piece of presented identity evidence." 
 
This would become cumbersome and not economical for an agency to have contracts with multiple issuing sources for validation of each piece of evidence. 

**Suggested Change**: Allow all pieces of fair/adequate evidence validated against a single third party data service.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #770 and #582
