### ISSUE TITLE
Enrollment codes valid for a maximum of 7 days seems unrealistic for a customer to receive a code in the mail. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1050]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.5.6, 
 
**Comment (Include rationale for comment)**:  Enrollment codes valid for a maximum of 7 days seems unrealistic for a customer to receive a code in the mail.
 
We currently allow 5-7 days just for the code to arrive in the mail, this timeline does not allow time for the user to go online and finish registration. 

**Suggested Change**: At a minimum, allow up to 30 days.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
The document specifies that in certain circumstance 21 days is ok. We will make this clearer and remove 'unreachable by USPS'.
