### ISSUE TITLE
Document states "The CSP shall allow a resolved, validated, or verified identity to opt out of KBV." 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1051]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.3.2, 
 
**Comment (Include rationale for comment)**:  Document states "The CSP shall allow a resolved, validated, or verified identity to opt out of KBV."
 
If the user's identity is already resolved, validated, and verified, why would any CSP want to require KBV at that point?

**Suggested Change**: Change to "The CSP shall not require KBV for a resolved, validated, or verified identity."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #1354
