### ISSUE TITLE
requires one piece of Strong evidences plus 2 "Adequate" pieces, but adequate is never mentioned again, is that the same as "fair"? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1052]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: throughout, 
 
**Comment (Include rationale for comment)**:  requires one piece of Strong evidences plus 2 "Adequate" pieces, but adequate is never mentioned again, is that the same as "fair"?
 
Use "Fair" or "Adequate" consistently

**Suggested Change**: Grammar issue
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Resolved via #518
