### ISSUE TITLE
Differentiate between in-person and remote identity proofing. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1053]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.5.5, 
 
**Comment (Include rationale for comment)**:  Differentiate between in-person and remote identity proofing.
 
In-person identity proofing requires the same stringent evidence as is required when identity proofing remotely. SSA already has a robust, well-established in-person process in place to assist users. We have a long history of identity proofing our customers.

**Suggested Change**: Differentiate between in-person and remote identity proofing. Reduce the in-person evidence requirements. In turn, this will more accurately represent the additional confidence in the user's identity just because the interaction has been done face-to-face.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is primarily an IAL2 issue.  And related to #643

**Comment by paul-grassi** [comment]
As online options evolve, innovate, and improve, in-person proofing is actually becoming less secure. Consider a remote method that validates physical security features vice an in-person experience that does not.  Even a trained human (perhaps with the exception of forensic experts) can't detect the presence, or lack thereof, of security measures.  Therefor we will not lessen the requirements for in-person proofing. 

However, all agencies, per the updated 800-63-3, have options in what requirements they implement provided the document compensating controls and comparability.  See <https://pages.nist.gov/800-63-3/sp800-63-3.html#sec5>.
