### ISSUE TITLE
We recommend removal of KBV for in-person identity. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1054]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.3.2, 
 
**Comment (Include rationale for comment)**:  We recommend removal of KBV for in-person identity.
 
Regarding Knowledge Based Verification (KBV), we do not want our in-person employees asking questions to demonstrate the applicant is the owner of the claimed information. (i.e., Out of Wallet Questions). Conducting face-to-face identity verification puts the in-person employees performing identity proofing in the "line of fire".   

**Suggested Change**: We recommend removal of KBV for in-person identity.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
It should have been clear, but need to make sure KBV not allowed for in-person.
