### ISSUE TITLE
Allow the Social Security number to be used as at least "fair/adequate" evidence or add language that the issuing source of evidence can use that 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1055]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 8.1.1, 
 
**Comment (Include rationale for comment)**:  Allow the Social Security number to be used as at least "fair/adequate" evidence or add language that the issuing source of evidence can use that evidence as fair/adequate evidence.
 
Document states the "Evidence requirements at the higher IALs preclude the usage of the SSN or the Social Security Card as acceptable identity evidence." However, we feel that the SSN meets the scoring requirements for "adequate/fair" as described in Table 5-1.

We claim the identity through an identity proofing process.
The issuing process for the evidence can reasonably be assumed to have been delivered into the possession of the subject to whom it relates
The evidence contains at least one reference number (The SSN). If you continue to require 2 additional pieces of evidence (1 STRONG and 1 other adequate/fair) this would be more than enough information to establish the appropriate level of confidence in the user's identity.

**Suggested Change**: Allow the Social Security number to be used as at least "fair/adequate" evidence or add language that the issuing source of evidence can use that evidence as fair/adequate evidence.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Additional attributes can be collected to support identity validation and verification, but we will not change the definitions of identity evidence characteristics.
