### ISSUE TITLE
Document states, "AAL 1 requires single-factor authentication" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1056]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.1, 
 
**Comment (Include rationale for comment)**:  Document states, "AAL 1 requires single-factor authentication" 
 
A multifactor credential that does not satisfy the AAL2 requirements should still be allowed for AAL1.

**Suggested Change**: Change the word "requires" to "allow"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
"requires" is preferred because it emphasizes that there is a requirement. Changing to "either single-factor or multi-factor" to show that multi-factor authentication is also acceptable at AAL1.
