### ISSUE TITLE
We recommend rewording the requirement as ‘The CSP SHALL comply with their respective records retention policies in accordance with whatever laws and regulations apply to 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1057]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.2.5 and 4.3.5, 
 
**Comment (Include rationale for comment)**:  We recommend rewording the requirement as ‘The CSP SHALL comply with their respective records retention policies in accordance with whatever laws and regulations apply to those entities.
 
Document states "The CSP SHALL comply with their respective records retention policies..."  Note that section 6.1 indicates that "CSPs SHALL maintain a record of all authenticators" (is required, not something the SP opts to do), but this section does not maintain a credential length." ---- This section removes the requirement in existing NIST language to retain records for 7 years past the expiration of the credential.

This section, as written, would effectively allow a CSP to operate without keeping registration records; and makes privacy risk the sole consideration in determining retention schedules.  Fraud and security risks should also be considered in such determinations.  The minimum retention time indicated in the current version is appropriate to ensure RPs can rely on CSP retention periods. 

**Suggested Change**: We recommend rewording the requirement as ‘The CSP SHALL comply with their respective records retention policies in accordance with whatever laws and regulations apply to those entities.  The CSP shall conduct privacy, security, and fraud risk assessments to determine how long records should be retained.  The CSP SHOULD retain records for 7 years, 6 months past the revocation and expiration of the credential.’
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The 7 years 6 months requirement in previous editions of this document has been removed because it was not clear what its source as a mandatory requirement was. A general records schedule (GRS) exists, GRS-24, which many agencies make use of as a guideline; we will add a reference to it.

We will also change the privacy risk assessment to include security and fraud considerations.
