### ISSUE TITLE
We recommend 4.4 explicitly allow the use of attributes collected and maintained to maintain the integrity of the system. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1058]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.4, 
 
**Comment (Include rationale for comment)**:  We recommend 4.4 explicitly allow the use of attributes collected and maintained to maintain the integrity of the system.
 
The text states "CSPs SHALL NOT use or disclose information about authentication for any purpose other than conducting authentication or to comply with law or legal process, unless [consent clause]."

We recommend this section explicitly allow the use of attributes collected and maintained to maintain the integrity of the system (e.g., to identify potential fraud and abuse.).  This recommendation is consistent with the Fraud Reduction and Data Analytics Act of 2015.

**Suggested Change**: Replace with "CSPs SHALL NOT use or disclose information about authentication for any purpose other than conducting authentication; for operating security and integrity controls; or to comply with law or legal process unless [consent clause]."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
We will add language permitting the use of information relating to authentication for managing fraud and abuse. We will add a privacy consideration to consult with the agency SAOP regarding the implementation of these capabilities.
