### ISSUE TITLE
Document states that the authentication SHALL be considered invalid if not completed with 5 minutes. If the authentication is completed with an OTP, users may 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1059]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.3.2, 4
 
**Comment (Include rationale for comment)**:  Document states that the authentication SHALL be considered invalid if not completed with 5 minutes. If the authentication is completed with an OTP, users may need more time. 
 
Since enrollment code delivered digitally is available for 10 minutes, change the authentication window to match.

**Suggested Change**: "… authentication SHALL be considered invalid if not completed within 10 minutes."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The referenced section refers to out-of-band authenticators, and there is not a significant security risk associated with a 10-minute vs. 5-minute limit.
