### ISSUE TITLE
Consider rewording, "At IAL2, the CSP SHALL bind at least one, and SHOULD bind at least two, authenticators to the subscriber's online identity." 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1060]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 6.1.1, 2
 
**Comment (Include rationale for comment)**:  Consider rewording, "At IAL2, the CSP SHALL bind at least one, and SHOULD bind at least two, authenticators to the subscriber's online identity."
 
This makes it sound like IAL 2 only requires single factor authentication, that multifactor authentication is option.

**Suggested Change**: …"The CSP SHALL bind at least one, and should bind at least two authenticators of a factor to the subscriber's online identity."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This is true particularly for physical authenticators, but it might not be helpful to bind two different memorized secrets since they are also likely to be lost (forgotten).
