### ISSUE TITLE
Add the text "The CSP SHALL suspend, revoke, or destroy a credential within 24 hours of being notified of or identifying a compromise. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1061]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 6.2, 
 
**Comment (Include rationale for comment)**:  Add the text "The CSP SHALL suspend, revoke, or destroy a credential within 24 hours of being notified of or identifying a compromise.
 
The guidance makes suspension of a credential optional when compromise is reported; this differs from the current guidance (§7.3.1.2,3) which requires CSPs to revoke or destroy credentials reported as compromised within 24 hours (LOA3) or 72 hours (LOA2).

If a credential is compromised, it should be quickly revoked to prevent its fraudulent use in authenticating to relying parties.

**Suggested Change**: Add the text "The CSP SHALL suspend, revoke, or destroy a credential within 24 hours of being notified of or identifying a compromise.  In determining whether a credential has been compromised, the CSP MAY verify an address of record.  [A suspended credential SHALL be reversible if the subscriber successfully authenticates to the CSP and requests reactivation of an authenticator suspended in this manner.]" (existing text in brackets)
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
We removed the specific time limits because we could not find any basis for the specific requirement. Agencies are of course encouraged to establish and document their own time limits.

It should be obvious that the suspense, revocation, or destruction occur as soon as possible, but the document doesn't actually say that, so it will be added.
