### ISSUE TITLE
The text clarifies Section 4.3 and indicates "Section 4.4 does not permit the CSP to use information about authenticators…" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1062]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 9.3, 
 
**Comment (Include rationale for comment)**:  The text clarifies Section 4.3 and indicates "Section 4.4 does not permit the CSP to use information about authenticators…"
 
The text clarifies Section 4.3 and indicates "Section 4.4 does not permit the CSP to use information about authenticators that is collected and maintained in the authentication process for any purpose other than authentication or to comply with law or legal process..."

See comment on Section 4.4 above.

**Suggested Change**: Section 4.4 does not permit the CSP to use information about authenticators that is collected and maintained in the authentication process for any purpose other than authentication; to operate security and integrity controls; or to comply with law or legal process...
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
See #1058
