### ISSUE TITLE
‘"Out-of-band authentication using the PSTN (SMS or voice) is discouraged and is being considered for removal in future editions of this guideline." 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1063]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.3.2, 
 
**Comment (Include rationale for comment)**:  ‘"Out-of-band authentication using the PSTN (SMS or voice) is discouraged and is being considered for removal in future editions of this guideline." 
 
We disagree with the proposal to remove the SMS option since we have several large-scale public facing services that utilize SMS, including mySSA. If this change is implemented in a future revision, it would require a large-scale effort to implement.

**Suggested Change**: Remove the language about discouraging OOB using PSTN and it being considered for removal in future editions of this guideline. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
See also #980.

We note that deployment of alternative forms of 2-factor authentication will take time, which is why the note was included but PSTN is still acceptable for out-of-band authentication in this revision.
