### ISSUE TITLE
Text does not convey whether the CSP may release security information to the RP to identify fraud. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1066]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 6.3, 
 
**Comment (Include rationale for comment)**:  Text does not convey whether the CSP may release security information to the RP to identify fraud.
 
The text states: "Note that the IdP may have access to information that may be useful to the RP in enforcing security policies, such as device identity, location, system health checks, and configuration management.  If so, it may be a good idea to pass this information along to the RP within the bounds of the subscriber's privacy preferences."

The text in bold does not convey whether the CSP may release security information to the RP to identify fraud.

**Suggested Change**: Replace bold text with: "The CSP SHOULD convey security information to the RP consistent with the subscriber's privacy preferences.  The RP MAY require the subscriber consent to provide such information as a condition for using the service."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Section 4.2 includes the statement: An IdP MAY disclose information on subscriber activities to other RPs within the federation for security purposes such as communication of compromised subscriber accounts. 

This conveys the requested change.

**Comment by jimfenton** [comment]
Similar to #1058

**Comment by jimfenton** [comment]
Will remove the sentence about it being a "good idea" to pass this information along.
