### ISSUE TITLE
CSPs main concerns regarding cost and impacts of the changes 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#1067]
### All Fields Are Required
**Organization Name (N/A, if individual):** Kantara Initiative Inc. 

**Organization Type (see below for codes)**: 3
 
**Document (63-3, 63A, 63B, or 63C)**:General Comments of 800-63-3

**Reference (Include section and paragraph number)**: General Comments 
 
**Comment (Include rationale for comment)**:

Substantial Impact:
a) Reducing the number of assurance levels from 4 to 3 will increase the cost as well as user friction. It will also reduce the performance of existing solutions. 
b) Existing credentials will need to be re-proofed because of both the changes of applicable assurance levels and the changes in the proofing requirements. This will have high economic and time investment.
c) There are technical challenges of document verification requirement for every remote identity proofing transaction (lower success rate of Identity Proofing and user friction).
d) Because of a, b and c getting service implementations to be compliant with the revised standards will take time. As such, there needs to be consideration of the timeframe and roadmap for implementation. 
e) There are technical challenges with requiring validation using the “issuing source”. 
f) Due to the high level of significant comments that Kantara has submitted, we believe that this document should not go to publication without additional industry review. 

**Suggested Change**: see comment above 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #582 and #643

**Comment by paul-grassi** [comment]
My apologies for earlier brevity. In regards to B, that is a great point and something we could consider in our companion implementation guides. That said, this can be based on agency risk assessment and is out of scope for this document.  Mission and risk is the best approach to determine whether to re-proof, not an arbitrary process defined in these documents.  This is a great opportunity for trust frameworks to assist agencies in the best migration approach (if necessary).

d) agencies have 1 year from finalization to implement SP's, if they are applicable to them.
