### ISSUE TITLE
Document Verification for all remote proofing (validation of driver´s license and passport) 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#1068]
### All Fields Are Required
**Organization Name (N/A, if individual):** Kantara Initiative Inc. 

**Organization Type (see below for codes)**:3
 
**Document (63-3, 63A, 63B, or 63C)**:SP 800-63A

**Reference (Include section and paragraph number)**: 4.4.1.4 and 5.2. 
 
**Comment (Include rationale for comment)**:

•	Kantara is currently unaware of any real time automated mechanisms for validating driver’s license. As such, the only viable implementations are PKI or self-assertion.
•	Financial institutions will also have difficulty verifying these sources.  Negotiating individual contracts with different states for driver’s license validation would expand costs considerably, if it were even possible. 

Technical challenges to document verification: 
a) While current technology does exist to allow the digital capture of a document and then compare that image to a ‘selfie’ image of an individual, it is a very cumbersome and much more costly procedure. In addition, it can be inaccurate depending on quality of document as well as the capability of person trying to capture image. As such, this will result in a much lower success rate of Identity Proofing and which will increase user friction. It is Kantara’s position that many agencies and organizations are not looking to provide more friction for their clients. 
b) Kantara also believes that this approach requires clients to provide documentation that they may not feel comfortable in providing (e.g., Driver’s License or Passport). Many document verification solutions also are limited to the types of documents that can be scanned or captured and these are typically Driver’s Licenses and Passports. Kantara also believes that there is a limited population that has access to these types of documents. Many younger as well as the older demographic may not have a driver’s license and less than 50%  of the U.S. population has a passport*. If services are restricted to only these two forms of identification then the population able to use services may be significantly restricted. 

*The Expeditioner, “How Many Americans Have a Passport” December 2016, http://www.theexpeditioner.com/2010/02/17/how-many-americans-have-a-passport-2/

**Suggested Change**:
Recommendation: Document verification should not be a requirement for every remote identity proofing transaction. Kantara suggests that there is a need for intermediate verification options that don't require the full rigor of IAL2 (remote + document verification). 
Kantara believes that document verification can and should play a role in the identity proofing process. Document verification would be a viable solution in situations where it would be necessary to provide an extra layer of verification (i.e., there might be limited data available). 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #582 and #643
