### ISSUE TITLE
VIRTUAL IN-PERSON IDENTITY PROOFING vs. REMOTE IDENTITY PROOFING

### ISSUE THREAD

**Issue by jandrewh** [usnistgov/800-63-3#107]
**Organization**: 2

**Type**: 

**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: 3. Definitions and Abbreviations, 4.3. Virtual Inperson Proofing Requirements, 4.5. Identity Assurance Level 2, and 4.5.1. Presence Requirements

**Comment (Include rationale for comment)**: In reference to the usage of the words “Virtual” and “Remote”. As defined, 

“Remote
(As in remote authentication or remote transaction) An information exchange between network connected devices where the information cannot be reliably protected end to end by a single organization’s security controls.
Note: Any information exchange across the Internet is considered remote.”

This reference definition appears to suggest these two words are one in the same. Remote is defined as either an “authentication” or “transaction”. The IAM community is accustom to Remote Identity Proofing as being defined or associated with KBA/KBV based. Remote Electronic Identity Proofing or Virtual In-Person Identity Proofing is relatively a new concept and methodology.

Currently there is no reference definition for the “Virtual In-Person Identity Proofing“. Due to the expansion and functionality for identity proofing to include “Virtual In-Person Identity Proofing” e.g. audio video transmission as provisioned in Sec. 4.3 "Virtual In-person Identity Proofing Requirements" as being applicable for IAL3, it would seem to justify a definition for Virtual In Person Identity Proofing.

**Suggested Change**: Add a definition for “Virtual Identity Proofing”,

A. Virtual In-person identity proofing requires a video audio link that enables appearance of the Applicant to be identity proof and a Trusted Referee examination of Government issued Photo and Non-Photo Identification Documents and collection of the personal identifiable information

B. Virtual In-person Identity Proofing applies to an Applicant who is distal (not in the physical presence) of a Registration Authority and has an antecedent relationship with a Sponsor to acquire a trusted token/credential.

C. Virtual In-person Identity Proofing applies to a Public Applicant who is not in the physical presence of a Registration Authority, does not have an antecedent relationship with a Sponsor, and needs to acquire a trusted token/credential.

Currently  IAL2 provisions for Remote Identity Proofing which seems to imply inclusion for Virtual In-Person Identity Proofing, however, recommend adding Virtual In-person Identity Proofing to IAL2 as well. Which would allow for both Remote Proofing KBA/KBV and Virtual In-Person Identity Proofing to mitigate convolution. 
## Thank you for your consideration and outstanding work on 800-63.3 A,B,C.

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by dkelts** [comment]
I agree that there's a stain on the term Remote Proofing.  All of us with proofing/registration technologies face that stain.  However...

The concept of a video/audio stream over the Internet means that " the information cannot be reliably protected end to end by a single organization’s security controls ".   This makes the concept described in the suggested change actually Remote Proofing.  Unless you control every electron from the Subject to the Referee.

Nobody wants the stain, so let's remove it:

Identity Proof = Resolution + Validation + Verification

But if you score the Verification part of an Identity Proof as a straight up Authentication, whether in-person or remote, then you _could_ have a Remote Proof that performs Identity Verification (Authentication) more accurately than an In-Person Proof that uses a human without additional contextual or technological support (e.g. biometrics, employee-membership, quizzing, intuition).  That human's eyes will make a mistake 1:1000 (or 2.47 out of 1000 times depending on your stats).

I would argue the only additional category is Derived Proof = Authenticating to a prior In-Person Proof.  However, you might score it just like an Identity Proof, thereby making it Remote Proof according to these definitions.
