### ISSUE TITLE
Reduced Assurance Levels from 4 to 3

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#1070]
### All Fields Are Required
**Organization Name (N/A, if individual):** Kantara Initiative Inc. 

**Organization Type (see below for codes)**: 3
 
**Document (63-3, 63A, 63B, or 63C)**: SP 800-63A

**Reference (Include section and paragraph number)**: Section 7 
 
**Comment (Include rationale for comment)**:

•	The simplification of the levels from four to three may have made it more difficult to obtain the levels. Kantara believes that it removes the lower cost category and increases the cost to comply.
•	In order to achieve IAL level 2 would require that at least one piece of STRONG evidence be used. By definition, a STRONG level of evidence must contain a photo/image/biometric of the individual. NIST has confirmed this to mean that some form of remote document verification technology would be required in order to verify the photo/image/biometric. Kantara feels that this is too restrictive and does not provide agencies and organizations enough flexibility to determine the level of Identity Proofing needed for given situations. Kantara further believes that having only one level of remote identity proofing (IAL2) which, as it currently is written, requires document verification, creates an undue burden on agencies and organization to have to provide this level of proofing for every remote transaction. Kantara believes that this would significantly increase the cost and user friction as well as reducing the performance (pass rate) of existing solutions – particularly those that currently leverage LOA2.
 
**Suggested Change**:
Recommendation:
NIST to return to 4 levels of IALs to provide more flexibility with the following structure:
•	IAL1 – No Identity Proofing required (Self-Asserted)  
•	IAL2 – Remote Identity Proofing using verification of government ID and financial/utility account (this utilizes current LOA3 Identity Proofing capabilities)  
•	IAL3 – Remote Identity Proofing at IAL2 level plus the addition of document verification  
•	IAL4 – In-person Identity Proofing
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #643
