### ISSUE TITLE
Use of "digital service" term 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#1071]
### All Fields Are Required
**Organization Name (N/A, if individual):** Kantara Initiative Inc. 

**Organization Type (see below for codes)**: 3
 
**Document (63-3, 63A, 63B, or 63C)**: SP 800-63B

**Reference (Include section and paragraph number)**: Sections 2 and 4
 
**Comment (Include rationale for comment)**:

Kantara believes that there is inconsistency in the use of the term "digital service" in the introduction to SP-800-63-B. Section 4 uses the term as if it refers to the Credential Service Provider, whereas the introductory text uses the term as if means the Relying Party.

**Suggested Change**: Clarify the term 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Section 4 actually refers to the retention of data by the relying party, which might then make the data available subsequently. Changing the wording to 'relying party' to make this clear.
