### ISSUE TITLE
Subscriber vs subject, lack of clarity of the concepts

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#1072]
### All Fields Are Required
**Organization Name (N/A, if individual):** Kantara Initiative Inc. 

**Organization Type (see below for codes)**: 3 
 
**Document (63-3, 63A, 63B, or 63C)**: SP 800-63B

**Reference (Include section and paragraph number)**: 800-63B
 
**Comment (Include rationale for comment)**:
•	Part of the model inconsistency is differences in how the verb "authenticate" is applied. For example, does the subscriber authenticate or does the CSP do the authentication?
•	There is extensive reference to the "subscriber" whereas other schemes include "subscriber" and a "subject". While the “subject” and the "subscriber" may be the same individual, there are many use cases where the subscriber is the individual or organization that wants credentials issued for one or more subjects (e.g., power of attorney, tax preparation firms, old age homes).  
•	There are inconsistencies in the overall lifecycle model in different sections of the text. You become a subscriber because you have enrolled, the definition of enrollment doesn't include the definition of a service account.  Since they are unclear on the enrollment process it is not clear what the subscriber is.

**Suggested Change**: 
Recommendation: Define subscriber and subject and ensure those terms are used consistently in the text in alignment with recognized international sources (e.g., ETCI, Kantara Initiative Inc., international standards). 

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Same issue as #897
