### ISSUE TITLE
State model for transitions between non-authenticated and authenticated states 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#1073]
### All Fields Are Required
**Organization Name (N/A, if individual):**Kantara Initiative Inc. 

**Organization Type (see below for codes)**: 3
 
**Document (63-3, 63A, 63B, or 63C)**: SP 800-63B 

**Reference (Include section and paragraph number)**: 800-63B
 
**Comment (Include rationale for comment)**:
The state model for transitions between non-authenticated and authenticated states is not clear - a diagram would be helpful.

**Suggested Change**:
 Create a state model to show how entities go from non-authenticated to authenticated state, verifiers in pre-authenticated to post-authenticated state.  
 

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
We have included a diagram along those lines in the top-level document, SP 800-63-3, as Table 4-1.
