### ISSUE TITLE
Equivalent standard 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#1074]
### All Fields Are Required
**Organization Name (N/A, if individual):** Kantara Initiative Inc. 

**Organization Type (see below for codes)**: 3
 
**Document (63-3, 63A, 63B, or 63C)**: SP 800-63B

**Reference (Include section and paragraph number)**: 4.1.4, 4.2.4, 4.3.4
 
**Comment (Include rationale for comment)**:
In items 4.1.4, 4.2.4, 4.3.4 there are references to 800-53 "or an equivalent industry standard”. However, no method of judging what an equivalent standard is identified.

**Suggested Change**:
Recommendation: Provide the criteria to determine an equivalent standard in all relevant places in the document. 
 

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Should we just remove the "or an equivalent industry standard" because this can be tailored by agencies anyway?

**Comment by jimfenton** [comment]
As part of their risk analysis, agencies are free to determine what industry standards they consider acceptable.
