### ISSUE TITLE
Summary of Requirements 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#1075]
### All Fields Are Required
**Organization Name (N/A, if individual):** Kantara Initiative Inc. 

**Organization Type (see below for codes)**: 3
 
**Document (63-3, 63A, 63B, or 63C)**: SP 800-63B

**Reference (Include section and paragraph number)**: 4.5. 
 
**Comment (Include rationale for comment)**:
Section 4.5. summary of requirements: there are not rows for records retention or privacy requirements. 
 
**Suggested Change**: Recommendation: Add to the summary records retention and privacy requirements. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
We will add privacy controls and records retention rows to the table, and also to corresponding tables in -63A.

**Comment by nbl-nist** [comment]
Jim, in 63A there is no subsection for privacy controls equivalent to the security controls and records retention is part of the general requirements in 4.2, so I'm not sure how we would incorporate these concepts into the summary tables per your comment above.
