### ISSUE TITLE
Requirements on federal agencies 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#1076]
### All Fields Are Required
**Organization Name (N/A, if individual):** Kantara Initiative Inc. 

**Organization Type (see below for codes)**: 3
 
**Document (63-3, 63A, 63B, or 63C)**: SP 800-63C 

**Reference (Include section and paragraph number)**: 4.2. 
 
**Comment (Include rationale for comment)**:
Item 4.2 of SP 800-63C - requirements on federal agencies
 
**Suggested Change**: Include it in an annex instead of including in the rest of the flow of the document.  The agency guidance at the end of the privacy section is a non sequitur with respect to the rest of the document.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The text is germane to the primary audience for the document and needs to be retained.
