### ISSUE TITLE
Title 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#1079]
### All Fields Are Required
**Organization Name (N/A, if individual):** Kantara Initiative Inc. 

**Organization Type (see below for codes)**: 3
 
**Document (63-3, 63A, 63B, or 63C)**: 63-3, 63A and 63B

**Reference (Include section and paragraph number)**: 63-3, 63A and 63B 

**Comment (Include rationale for comment)**:
The documents are called "guidance" but they contain requirements.  The documents are a mixture of explanatory material, guidance material and requirements material. 
 
**Suggested Change**: Change of title and adopt a normative style
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
NIST needs to maintain the current language.
