### ISSUE TITLE
SSN Collection for Resolution/Validation versus Verification 

### ISSUE THREAD

**Issue by bhall6** [usnistgov/800-63-3#108]
**Organization**: ID.me

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: Section 5, 5.2, 1

**Comment (Include rationale for comment)**: The requirement to not collect SSN is prescriptive and process oriented versus outcome and results based. The reality is that SSN is the only ubiquitous identifier for Americans and there are no viable alternatives to resolve a unique identity in a way that Relying Parties and Identity Providers could use to release sensitive PII and/or records related to a specific person. For example, if the identity provider uses a drivers license number instead of an SSN as a unique identifier for the individual, the Relying Party, let's say any federal agency, will be unable to use the drivers license number as they are highly unlikely to have a drivers license associated with unique identities and related records in their database. They have SSN as the unique identifier. 

**Suggested Change**: At a high level, NIST should avoid prescriptive guidance and should instead focus on results based guidance, particularly if there are no viable alternatives at the moment as, a priori, we can expect that future interpretation of an ambiguous clause related to process will be decided by an auditor's subjective opinion and thus will vary according to the luck of the draw for the CSP. For this specific issue, the scope should be more narrowly construed. SSN should be fine and acceptable for attribute validation and for identity resolution. As a static identifier that has been compromised in numerous breaches (Anthem, OPM, etc), it should not be used for identity verification. This comment, if retained, should be moved to Section 5.4, Identity Verification, and should not inhibit or impact CSPs with respect to validation and resolution. 

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
Issue #93 required a fix to the document to include guidance on resolution.  It is possible to add additional language here regarding SSN but we feel that the guidance to limit the use of SSN applies to all processes associated with proofing.  We also understand the SSN's potential utility in resolution and to link to records that could be used for validation or verification.  Therefore we maintain the position that it SHALL NOT be collected, but make allowances for its collection to support not only results oriented guidance, but also to achieve resolution for RPs, such as federal agencies, that use SSN to correlate a CSP identity to an RP account.  In addition, General Requirement 13 in section 4 allows for additional data collection to help counter fraud. The SSN is an identifier and we recognize that and have made appropriate allowances for its use.  We have also added evidence requirements which are strict enough at the higher IALs to preclude the usage of SSN or the Social Security Card as acceptable identity evidence.
