### ISSUE TITLE
Usability requirements 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#1081]
### All Fields Are Required
**Organization Name (N/A, if individual):** Kantara Initiative Inc. 

**Organization Type (see below for codes)**: 3
 
**Document (63-3, 63A, 63B, or 63C)**:  63A, 63B and 63C

**Reference (Include section and paragraph number)**: 10 
 
**Comment (Include rationale for comment)**:

There are currently no normative usability requirements, is this intentional?
 
**Suggested Change**:
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by ychoong** [comment]
Noted for future consideration
