### ISSUE TITLE
Use of the term "trained personnel" is potentially open to varied interpretations. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1086]
**Organization Name (N/A, if individual)**: CDC

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Table 5.3, 
 
**Comment (Include rationale for comment)**:  Use of the term "trained personnel" is potentially open to varied interpretations.
 

**Suggested Change**: Recommend this document present general criteria or parameters for the required training; alternatively--or in addtion--reference potential sources of documentation (NIST, ISO or other standards) or traininng curriculums.
Rationale: Supports conistency across agencies; promotes effective and efficient use resources in identifying and utilizing appropriate training; and supports more effective implementation of this special publication.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We will include language, similar to -53, that discusses an organizational policy around training.  In addition, the implementation guide will have additional details on effective training in this domain, without pointing to specific programs.
