### ISSUE TITLE
Language in the requirements

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#1087]
### All Fields Are Required
**Organization Name (N/A, if individual):** Kantara Initiative Inc. 

**Organization Type (see below for codes)**: 3 
 
**Document (63-3, 63A, 63B, or 63C)**: 63A, 63B and 63C

**Reference (Include section and paragraph number)**: 63A, 63B and 63C 

**Comment (Include rationale for comment)**:
The shift towards normative language in the requirements is appreciated. However, the phrasing of some requirements makes it difficult to have certainty that an implementation meets those requirements. As assessors there is also uncertainty about how to evaluate conformity.  Uncertainty then leads to inconsistency. 
 
**Suggested Change**:
Recommendation: Clean up the text to separate (i.e., have in separate paragraphs) normative requirements and non-normative suggestions.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We appreciate the "pure" approach recommended by KI, but we believe the examples and supporting text helps, and will therefore leave structure the same.
