### ISSUE TITLE
There is a danger that continuing with a digital only focus will result in incorrect principles being established… 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1088]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: All, 
 
**Comment (Include rationale for comment)**:  There is a danger that continuing with a digital only focus will result in incorrect principles being established…
 
There is a danger that continuing with a digital only focus will result in incorrect principles being established and insufficient a distinction will be made between identity and security. 

If policies, rules etc do not apply in any channel then there is the probability that the issue is not an identity issue but a technology or channel issue and should potentially be dealt with in an alternative document.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
No suggested change.
