### ISSUE TITLE
Use of terms is inconsistent see comments on section 3. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1089]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: All, 
 
**Comment (Include rationale for comment)**:  Use of terms is inconsistent see comments on section 3.
 

**Suggested Change**: Review all terms across the suite for consistent use
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Unknown what terms are inconsistent.
