### ISSUE TITLE
‘Digital identity’ is a frequently used term in this suite but is undefined. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1090]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Executive summary, 1
 
**Comment (Include rationale for comment)**:  ‘Digital identity’ is a frequently used term in this suite but is undefined.
 
It is used inconsistently from sentence to sentence. It leverages a defined term ‘identity’ but then derails that term.
Suggest that clarity will be much improved if the term ‘digital identity’ was not used anywhere.

An 'identity' is one of more attributes, they are inevitably stored digitally in a system. When you are wrting 'digital identity' you do not mean this but some more or in some cases something else entirely.

**Suggested Change**: Suggest use of the term 'Digital identification' when discussing the process or act of identifying oneself in an online channel.
Suggest using 'authenticator'  or 'credential' or identifier' without the word digital, when meaning these things.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
It's defined in the first sentence of the executive summary.
