### ISSUE TITLE
In many instances the use of “digital identity” would seem to be better served by “identifier” – probably without the digital prefix. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1091]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Executive summary, 1
 
**Comment (Include rationale for comment)**:  In many instances the use of “digital identity” would seem to be better served by “identifier” – probably without the digital prefix.
 
 The identifier used to access a digital service (para.2) may be usable in other channels.

**Suggested Change**: Use "identifer" where applicable without "digital".
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This entire suite is about the concept of digital identity, and all of the functions to support it, whereas an identifier is just one piece.
