### ISSUE TITLE
‘Digital identity is hard’ (ignoring issues with the term at this point) this statement needs clarification. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1092]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Executive summary, 1
 
**Comment (Include rationale for comment)**:  ‘Digital identity is hard’ (ignoring issues with the term at this point) this statement needs clarification. 
 
Digital identity is poorly understood, once this is solved it becomes remarkably easy albeit with some technical intricacies when it come doing it remotely. 

**Suggested Change**: Change to 'Digital identification is complex…'
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
#1714
