### ISSUE TITLE
The definition of subject refers to both person and non-person entities. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1094]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Executive summary, 2
 
**Comment (Include rationale for comment)**:  The definition of subject refers to both person and non-person entities.
 
This version of 800-63 focuses on the authentication of individuals.

**Suggested Change**: Use “person”, when a more specific term like subscriber is not being used.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This was on purpose, as this suite will be extended to non-person entities.
