### ISSUE TITLE
The point of the phrase “but does not necessarily need to uniquely identify the subject [person]” is unclear. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1095]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Executive summary, 2
 
**Comment (Include rationale for comment)**:  The point of the phrase “but does not necessarily need to uniquely identify the subject [person]” is unclear. 
 
Unique identification will always practically require a context, whether that’s a single RP or a jurisdiction. Whatever might be considered as a set of core identity attributes in a particular context won’t work globally in every context to determine uniqueness.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
No suggested change.  In addition, the following sentence further defines what we mean.
