### ISSUE TITLE
The term “authentication error” seems to be oddly used. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1096]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Executive Summary, 3
 
**Comment (Include rationale for comment)**:  The term “authentication error” seems to be oddly used. 
 
Authentication is more or less binary depending on the successful use of the authenticator at the CSP. It is assumed that the need to link possession of the authenticators by the subscriber at the appropriate level has been made, and also that the identity assurance is at the correct level. The “error”, from the RP’s perspective is that an incorrect access control or authorization decision is made. 

**Suggested Change**: Replace "authentication error" with a clearer description.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is M-04-04 language that we will retain.  In addition we further define what this means in context of the entire suite.
