### ISSUE TITLE
IAL in the bullet list – the description here is inconsistent with what is said for IAL in other places 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1097]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Executive summary, 6
 
**Comment (Include rationale for comment)**:  IAL in the bullet list – the description here is inconsistent with what is said for IAL in other places
 
e.g. over the page when the binding of authenticators is not mentioned.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
No suggested change offered.
