### ISSUE TITLE
IAL 1 it refers to a real-life identity. This term is not defined and the implication is that this is an official government identity. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1098]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Executive summary, ?
 
**Comment (Include rationale for comment)**:  IAL 1 it refers to a real-life identity. This term is not defined and the implication is that this is an official government identity. 
 
Given that an identity is just a set of one or more attributes, there is no requirement at any level for a link to an official government identity or ‘real-world identity as used in latter IALs (also not defined)

**Suggested Change**: Remove all references to 'real-life' and similar phrases from the documents.
Add a general comment somwhere appropriate that generally at IAL3 the identity is likely to contain attributes that represent the initial identifying attributes established by government
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
I don't know the issue number, but in -A we will be clarifying IAL1 further.  But to make the point about what identity proofing is, we intend to keep the current language.
