### ISSUE TITLE
Applicant is not widely used. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1099]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Executive Summary, IAL2 bullet
 
**Comment (Include rationale for comment)**:  Applicant is not widely used.
 

**Suggested Change**: Better to be subject (or ideally person).
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Applicant is the term selected for someone enrolling to be identity proofed. Chapter 4 provides additional detail on the entire identity model and state transition of an individual moving throughout the process.
