### ISSUE TITLE
Recording identity evidence

### ISSUE THREAD

**Issue by jaspenc** [usnistgov/800-63-3#11]
**Organization**:2

**Type**:Procedure

**Reference (Include section and paragraph number)**:SP 800-63A Section 4.2 (7)

**Comment (Include rationale for comment)**:
 "The CSP SHALL NOT record an image, scan, or other copy of the evidence."  So, a drivers license can't be copied?  This goes against current practice for PIV/PIV-I identity proofing, and in industry.    Can you provide a rationale for this prohibition?  
**Suggested Change**:

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by TerryMcBride** [comment]
+1

At a higher level, the introduction of many of the privacy requirements throughout the suite is problematic. They are more suitable to a Trust Framework than technical guidelines for implementing authentication over an open network.  For example, in many cases (e.g., SSA, IRS), Federal Agencies have much more data on a person than is needed to establish an identity record. The CSP and RP aren't always different entities.  According to the Executive Summary this doc provides guidelines for step 3 of the process from M-04-04: "Select technology based on digital authentication technical guidance." The privacy requirements are business practice guidance, not technical guidance. I would recommend moving them to another document. It would make it simpler to follow the authentication standard.

**Comment by paul-grassi** [comment]
FIP 201 does not specify that documents need to be scanned and saved.  In addition, as NIST moves into privacy risk engineering for system engineers, privacy is no longer considered just a policy control, but can also be a technical control. As of now, we will not be removing privacy requirements from this document.
