### ISSUE TITLE
Requirement for at least single factor needs to be clarified and consistent through documents. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1100]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Executive Summary, AAL1
 
**Comment (Include rationale for comment)**:  Requirement for at least single factor needs to be clarified and consistent through documents.
 
Unclear here (and in other document parts) if this is single factor only (or perhaps also at least a combination of two types of weaker factor). Also, that a single factor can only be a memorized secret type, as neither something you have or something you are as a single factor can be effectively bound to the subscriber.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
No suggested change provided.  However, Chapter 4 of -B details authenticator requirements for all AALs.  In the case of AAL1, it is single factor but all authenticators, to include HW multifactor crypto are allowed (and preferred).
