### ISSUE TITLE
Requirement for cryptographic technology seems overstated. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1101]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Executive Summary, AAL3
 
**Comment (Include rationale for comment)**:  Requirement for cryptographic technology seems overstated.
 
Unclear here (and in other document parts) whether the use of three different factor types effectively provides the appropriate proof of possession by the subscriber, and whether two-factor with cryptographic technology is the only option.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
No suggested change provided.  However, the document states that 3-factor is more than needed for government digital services.  In addition, Chapter 4 and 5 of -B provide requirements (and options) for each AAL.
