### ISSUE TITLE
‘These guideline are agnostic…’ this needs qualification as it only applies to online/digital. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1102]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Executive summary, last
 
**Comment (Include rationale for comment)**:  ‘These guideline are agnostic…’ this needs qualification as it only applies to online/digital.
 
Refer to initial comment about the focus on digital.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This statement is quite clear. We aren't mandating an architecture, just minimum requirements to deliver proofing, authentication, and federation services.
