### ISSUE TITLE
Replace "subject". 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1103]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 2, 1
 
**Comment (Include rationale for comment)**:  Replace "subject".
 
More accurate to say “a unique representation of a person” rather than subject, as there is no consideration of non-person entities.

**Suggested Change**: Use "person" (or perhaps "individual" is better).
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Section 2.3 describes the intent to include non-person identities in this guideline, hence the selection of subject.
