### ISSUE TITLE
Need to uniquely identify the subject is unclear. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1104]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 2, 1
 
**Comment (Include rationale for comment)**:  Need to uniquely identify the subject is unclear.
 
The idea of uniquely identifying is unclear. This would seem to be about an identifier and this does not need to be globally unique, just unique in context.

**Suggested Change**: Replace with  “not necessary for the subject to be recognized by globally unique identifiers”.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This introduction is not about identifiers, but about proving you physical self.
