### ISSUE TITLE
Replace subject. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1105]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 2, 1
 
**Comment (Include rationale for comment)**:  Replace subject.
 
The text “…assurances that the subject…” should use subscriber as used elsewhere and defined as the returning user.

**Suggested Change**: Use subscriber.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Subject remains most appropriate as we expand this beyond humans.
