### ISSUE TITLE
Replace "authenticate identity". 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1106]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 2, 2
 
**Comment (Include rationale for comment)**:  Replace "authenticate identity".
 
A user doesn’t “authenticate their identity” – they authenticate at the required level of strength, and this exchange can include assertions of pseudonymous identity or other attributes that identify the subscriber.

**Suggested Change**: The clause should probably be something like "allow a subscriber to remotely access an online service on a Federal System."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE with the April 1 update of -3.
