### ISSUE TITLE
As this standard does not address channels other than online/digital it should be noted in this section that some principles may not translate very well… 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1107]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 2.2, All
 
**Comment (Include rationale for comment)**:  As this standard does not address channels other than online/digital it should be noted in this section that some principles may not translate very well…
 
 and matters other than identity may be included.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
No suggested change provided.
