### ISSUE TITLE
Constraints for biometrics is overstated relative to other factor types. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1108]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 2.2, 2
 
**Comment (Include rationale for comment)**:  Constraints for biometrics is overstated relative to other factor types.
 
Similar weaknesses to biometrics apply to something you have authenticators, but this is not strongly identified here or in 63B. With the use of a memorized secret or biometric, there is always a risk that the authenticator is not in the subscriber’s possession for a specific authentication transaction.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Resolved via #904
