### ISSUE TITLE
Define RA. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1111]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 2.5.1, 3
 
**Comment (Include rationale for comment)**:  Define RA.
 
RA is not included in the abbreviation and definitions section.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will remove RA from definition.
