### ISSUE TITLE
Inconsistent use of the term ‘authentication’. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1112]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 3, 1
 
**Comment (Include rationale for comment)**:  Inconsistent use of the term ‘authentication’. 
 
While we agree that there are no universally agree terms, the terms should at the very least be used consistently, as defined, in the entire 800-63-3 suite.

**Suggested Change**: See subsequent comment on 'authentication'
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
See #1217
