### ISSUE TITLE
There are terms for ‘subject’, ‘subscriber’, ‘claimant’, ‘party’ (not defined) and ‘person’ (not defined) all used at various times for the same entity. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1113]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 3, Applicant
 
**Comment (Include rationale for comment)**:  There are terms for ‘subject’, ‘subscriber’, ‘claimant’, ‘party’ (not defined) and ‘person’ (not defined) all used at various times for the same entity. 
 

**Suggested Change**: Provide an additional note here as to which relationship in the model that this relates to.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Chapter 4 discusses the model in detail.
