### ISSUE TITLE
Replace "identity information". 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1114]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 3, Assertion
 
**Comment (Include rationale for comment)**:  Replace "identity information".
 
The part of the definition that refers to “identity information” seems to imply that this is a particular set of data. At a minimum, the assertion may only contain a pseudonymous identifier. It may also include other “identifying” values or claims. Other attributes don't necessarily need to be "[independently] verified" - the individual can be the authoritative source of attributes such as ethnicity which might be held by the CSP.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
@jricher I think there is value to remove `identity` from this definition.  What do you think?
