### ISSUE TITLE
This term needs to always be qualified with a pre-fix as the definition already states three meanings and is missing a fourth (FAL). 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1115]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 3, Assurance
 
**Comment (Include rationale for comment)**:  This term needs to always be qualified with a pre-fix as the definition already states three meanings and is missing a fourth (FAL). 
 
To avoid misinterpretation is should indicate which context it is being used in.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Either remove or update the definition.
