### ISSUE TITLE
Reword assurance for part 2). 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1116]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 3, Assurance
 
**Comment (Include rationale for comment)**:  Reword assurance for part 2).
 
This doesn’t work too well for authentication. Credential is not widely used in 63B – this should be replaced with authenticator, and should probably mention possession by the subscriber.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
See #1115
