### ISSUE TITLE
This term is used inconsistently throughout this and the other documents. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1117]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 3, Authentication
 
**Comment (Include rationale for comment)**:  This term is used inconsistently throughout this and the other documents. 

 
It is use in the context of 'use of an authenticator' in some places but in others it is something else.  Authentication is proving possession by the subscriber. It’s not directly used to claim digital identity (which is not well defined and used). Arguably the “identity” is the same whether it’s part of a digital transaction or the use of some other channel.

**Suggested Change**: Suggest that this be restricted to ‘An instance of the use of an Authenticator’ it may be extended to include the concepts of presentation and validation.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We believe the usage of authentication is used correctly throughout the document.
