### ISSUE TITLE
Refine this definition to include all three types including biometric. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1119]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 3, Authenticator
 
**Comment (Include rationale for comment)**:  Refine this definition to include all three types including biometric.
 
The definition completely overlooks the something you are authenticators – i.e. biometrics. The use of “cryptographic” technologies is over-emphasised. It doesn’t apply to something you have form factors such as a grid card.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Definition holds up in this version.  The parens is just an example, and we still only allow biometrics to unlock the true authenticator.
