### ISSUE TITLE
Given that there are also terms for ‘subject’, ‘subscriber’, ‘applicant’, ‘party’ (not defined) and ‘person’ (not defined)… 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1121]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 3, Claimant
 
**Comment (Include rationale for comment)**:  Given that there are also terms for ‘subject’, ‘subscriber’, ‘applicant’, ‘party’ (not defined) and ‘person’ (not defined)…
 
 are all used at various times for the same entity it would be good to provide an additional note here as to which relationship in the model that this relates to.

**Suggested Change**: See comment for Applicant
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Chapter 4 defines the lifecycle and state transition of a subject moving through all identity processes.
