### ISSUE TITLE
More clarity may be needed for readers to understand the difference between an identity bound in the context of an IAMS 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1122]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 3, Credential
 
**Comment (Include rationale for comment)**:  More clarity may be needed for readers to understand the difference between an identity bound in the context of an IAMS
 
 and the identity bound for use in a federated attribute assertion system

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
No suggested change provided.
