### ISSUE TITLE
Include use of authentication credential. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1123]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 3, Credential
 
**Comment (Include rationale for comment)**:  Include use of authentication credential.
 
The definition is problematic since the term credential is often also used to describe an authenticator element – for example a password or an OTP code. Credential is also used to describe an identity attribute. The CSP binding between one or more authenticators and one or more identifiers (minimally a single pseudonymous identifier) isn’t necessarily itself a credential. Is a credential simply a data element held by a CSP for the purposes of authentication or identifying attributes?

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
No suggested change provided.  However, the credential is the record bound to an authenticator.  In the sense of PKI, the certificate may be the credential, but the private key is the authenticator.
