### ISSUE TITLE
"Real-life identities" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1125]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 2, 2
 
**Comment (Include rationale for comment)**:  "Real-life identities"
 
And throughout the document. As all identities are ‘real-life identities’, what do you mean by this term.

**Suggested Change**: Remove reference to 'real-life'
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
this document will expand beyond humans and include devices.
