### ISSUE TITLE
Bullets 2-4 are not the outcome of identity proofing for IAL1 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1126]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 2.1, 1
 
**Comment (Include rationale for comment)**:  Bullets 2-4 are not the outcome of identity proofing for IAL1
 

**Suggested Change**: Remove and break up outcomes by IAL
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will clean up language since IAL1 really is no-proofing.
