### ISSUE TITLE
All the following terms are inconsistent with overview document. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1128]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 3, 
 
**Comment (Include rationale for comment)**:  All the following terms are inconsistent with overview document.
 
Attack, Attacker, Attribute, Authentication, Authenticator, Claimant, Credential, CSP, Identity, Subscriber and Valid

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #898
