### ISSUE TITLE
Does the US have a definition of ‘legal name’? If not then suggest new definition. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1132]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 3, Pseudonym
 
**Comment (Include rationale for comment)**:  Does the US have a definition of ‘legal name’? If not then suggest new definition.
 
Unless there is such a definition then this is either incorrect or more complex. In UK and NZ it is allowed to anything you want provided it is not for the purposes of deceit, if US is the same then rephrasing is required.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
In the US, action by a court is required to change one's legal name, so it does have particular standing.
