### ISSUE TITLE
Given the very restrictive definition of ‘remote’ would this ever be possible in reality. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1133]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 3, Virtual In-person Proofing
 
**Comment (Include rationale for comment)**:  Given the very restrictive definition of ‘remote’ would this ever be possible in reality. 
 

**Suggested Change**: Consider rethingkin the remote limitation but keep this concept.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Already possible with innovation in the market today.
