### ISSUE TITLE
First sentence in not valid for IAL1 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1134]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4, 2
 
**Comment (Include rationale for comment)**:  First sentence in not valid for IAL1
 
No verification occurs at level 1

**Suggested Change**: Change to ' The outcome of identity proofing determines the degree to which a person may be who they claim to be' 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #1126
