### ISSUE TITLE
List of attributes is a poor example of ‘identity’. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1136]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4, 2
 
**Comment (Include rationale for comment)**:  List of attributes is a poor example of ‘identity’. 
 
Identity' allows for any attributes, this list starts an assumption of a particular set which is further reinforced later in the document when ‘Name’ and ‘physical address’ become required. That in turn means that these listed as 'could include' is also misleading.

**Suggested Change**: Either support the defintion of 'identity' as being non-specified attributes or set identity as a specific set.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Related to #1135. There is some rationale here to consider even if we retain the existing example list.
