### ISSUE TITLE
The 3 vertical boxes under 'Verificatin' don’t apply to all IAL and may not be necessary. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1137]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.1, Figure 4-1
 
**Comment (Include rationale for comment)**:  The 3 vertical boxes under 'Verificatin' don’t apply to all IAL and may not be necessary.
 

**Suggested Change**: Remove or make a note.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
There is a similar issue to this, I just can't find it.  We will be editing the graphic or note to be specific about applicability to IAL2/3.

**Comment by paul-grassi** [comment]
@kboeckl lets close this when we do a PR for the proofing graphic.

**Comment by paul-grassi** [comment]
Related to #615
