### ISSUE TITLE
This appears to contradict the table 5-2 in the overview document. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1138]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.2, Table 4.2
 
**Comment (Include rationale for comment)**:  This appears to contradict the table 5-2 in the overview document. 
 

**Suggested Change**: It should read 1, 2 or 3 then 2 or 3 then 2 or 3 then 3
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE due to updates to -3.
