### ISSUE TITLE
Needs rewording. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1139]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.2, Bullet 1
 
**Comment (Include rationale for comment)**:  Needs rewording. 
 
Failure to complete an identity proofing process may impact the decision to deliver a service.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
See comment #677
