### ISSUE TITLE
This assumes a particular explicit purpose, contradicts bullet 5 and a section of the overview which talks about the assertion of other associated attributes. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1140]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.2, Bullet 3
 
**Comment (Include rationale for comment)**:  This assumes a particular explicit purpose, contradicts bullet 5 and a section of the overview which talks about the assertion of other associated attributes.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
We do not believe that the bullets contradict each other. Bullet 3 deals with collection, and bullet 5 with use.
