### ISSUE TITLE
Bullet 5 appears to contradict 3. ‘CSPs SHALL NOT make consent a condition of the service’. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1141]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.2, Bullet 5
 
**Comment (Include rationale for comment)**:  Bullet 5 appears to contradict 3. ‘CSPs SHALL NOT make consent a condition of the service’. 
 
This contradicts the privacy approach in the overview document section 4.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Bullet 5 refers to consent for use; bullet 3 refers to collection.
