### ISSUE TITLE
Redress requirement appears to be privacy rather than identity proofing. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1142]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.2, Bullet 6
 
**Comment (Include rationale for comment)**:  Redress requirement appears to be privacy rather than identity proofing.
 
The requirement for a CSP to provide the means to address problems is important, but this would seem to be a generic privacy requirement for the provision of personal information to an online service under any circumstances.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The redress requirement addresses issues beyond than those that are only privacy-related.
