### ISSUE TITLE
Why should fraud mitigation measures only apply to remote applications? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1143]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.2, Bullet 11
 
**Comment (Include rationale for comment)**:  Why should fraud mitigation measures only apply to remote applications?
 

**Suggested Change**: Apply fraud mitigation based on IAL not remote
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Fraud mitigation applies in-person as well as remote. We will remove "remote" and cite applicable measures since all measures don't apply equally to in-person and remote proofing.

**Comment by paul-grassi** [comment]
Addressed in a previous fix.
