### ISSUE TITLE
If the CSP does not proof then no attributes are collected and IAL is nil not 1. The same applies to an applicant providing no 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1144]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.3, 1
 
**Comment (Include rationale for comment)**:  If the CSP does not proof then no attributes are collected and IAL is nil not 1. The same applies to an applicant providing no attributes.
 
If they self-assert nothing then no record is created ergo IAL0. The only way to have IAL1 would be for the CSP to store something not consciously provided by the applicant e.g. IP address, in which case this should be made clear.

**Suggested Change**: Should read ‘The CSP SHALL NOT verify attributes. Applicants MAY self-assert one or more…’ 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We aren't getting into IAL0 vice 1, but this is a good edit.
