### ISSUE TITLE
Without having a purpose for the collection of evidence this section is completely overcooked and undercooked at the same time. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1145]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.4.1.2, 1
 
**Comment (Include rationale for comment)**:  Without having a purpose for the collection of evidence this section is completely overcooked and undercooked at the same time. 
 
There is no such category of document as ‘Adequate’.
There is no concept of correctness or ownership.

**Suggested Change**: Remove reference to 'Adequate'.
Suggest thinking about what is to be achieved by the presentation of evidence, what value does multiple form bring and will it be possible for the general population.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
See #518 for adequate comment.  However, evidence collection is just one step. We also have validation (correctness in comment) and verification (ownership in comment), therefore the rest of this comment is declined.
