### ISSUE TITLE
Define and explain third party data service. Clarify the requirement. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1146]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.4.1.3, 
 
**Comment (Include rationale for comment)**:  Define and explain third party data service. Clarify the requirement.
 
This requirement introduces a new entity – the third party data service. Presumably this is a role that is distinct from either CSP or Verifier. 

**Suggested Change**: If the third party is an authoritative source for the identity attribute then surely this strengthens the evidence, and the restriction should not apply. If the third party is only corroborative then this could apply.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Resolved via #770
