### ISSUE TITLE
Presupposes a solution that either has address as an identity attribute of requires it as part of the binding process. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1147]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.4.16, 
 
**Comment (Include rationale for comment)**:  Presupposes a solution that either has address as an identity attribute of requires it as part of the binding process. 
 
Breaks the agnostic claim in the overview document.
Enrollment code also presupposes a solution. It is always an authentication factor, and it only needs to be reset if it is to be part of a persistent authenticator.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Resolved via #642
