### ISSUE TITLE
Security controls should be kept separately from IAL. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1148]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.4.1.8, 
 
**Comment (Include rationale for comment)**:  Security controls should be kept separately from IAL.
 
Helps clarify identity components as destinct from channel components

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is a requirement from past versions that we will retain in this version.
