### ISSUE TITLE
Introduces a new term enrollee. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1149]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.4.2, 
 
**Comment (Include rationale for comment)**:  Introduces a new term enrollee. 
 

**Suggested Change**: Suggest use Applicant or Claimant
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Good catch.
