### ISSUE TITLE
Clarify how biometrics increases identity assurance. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1150]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.5, 
 
**Comment (Include rationale for comment)**:  Clarify how biometrics increases identity assurance.
 
It’s not particularly clear how biometrics increases the strength of the identity assurance. If this is in-person capture of facial, fingerprint or other biometric data for comparison against an authoritative source, then this is an effective means of providing evidence. If this is a visual comparison of the subject with a photo ID document, this isn’t really a biometric comparison.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is a good comment for the explanatory text in 4.5
