### ISSUE TITLE
One or two items for SUPERIOR? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1151]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.5.2, 
 
**Comment (Include rationale for comment)**:  One or two items for SUPERIOR?
 
This requirement states that two (2) items of SUPERIOR evidence are required for IAL3, but the summary Table 4-3 states one (1) SUPERIOR piece. In any case, if the piece of evidence is “SUPERIOR”, it’s not obvious why one piece would not suffice.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We may remove table, but will keep comment open until we decide.

**Comment by paul-grassi** [comment]
Will be resolved via #669
