### ISSUE TITLE
Table 4-3 needs rework - see previous comments 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1152]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.7, Table 4-3
 
**Comment (Include rationale for comment)**:  Table 4-3 needs rework - see previous comments
 

**Suggested Change**: Presence for IAL1 and IAL2 should be the same only IAL3 has a requirement and that is that it shall not be remote – though this is questionable.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
See #1151
