### ISSUE TITLE
Makes statements that do not apply to IAL1 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1153]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5, 
 
**Comment (Include rationale for comment)**:  Makes statements that do not apply to IAL1
 

**Suggested Change**: Separate statements by IAL
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Chapter 5 is only in play as directed in Section 4, which is just for IAl 2 and 3.
