### ISSUE TITLE
Explain "contains a biometric". 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1154]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.2.1.1, Table 5-1
 
**Comment (Include rationale for comment)**:  Explain "contains a biometric".
 
The “Superior” strength describes whether the evidence contains a biometric. The sentence above relates to photo. Therefore, it seems that this should be described as digital biometric information to make this distinction clear.

**Suggested Change**: To make this distinction clear, should this be digital biometric information if it is intended to encompass examples such as facial biometric on an embedded chip.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
There is a similar comment elsewhere, can't find it, but we will clarify this.
