### ISSUE TITLE
Properties do not appear to relate to a solid purpose or objective 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1155]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.2.1.1, Table 5-1
 
**Comment (Include rationale for comment)**:  Properties do not appear to relate to a solid purpose or objective
 
Contains three levels of strength (unacceptable, weak and fair) that are not used.
Strong assumes the identity attributes include ‘name’.
Requires a photograph or image but there is no requirement to use it in the process.
Disallows expired evidence without consideration as to the aspect of the evidence that has expired, which usually relate to an entitlement not identity. This is somewhat ironic given 4.2 bullet 1.
Ditto for Superior

**Suggested Change**: Needs to be align with the Requirements for each IAL
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We understand the comment about strengths not being used, but we will retain them.  In addition, table 5-1 is just one part of the proofing process, resolution, which combined with validation and verification makes use of the characteristics we have defined.
