### ISSUE TITLE
Table does not align with the requirements for IAL, especially IAL1 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1156]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.2.2.1, Table 5-2
 
**Comment (Include rationale for comment)**:  Table does not align with the requirements for IAL, especially IAL1
 
At IAL1 where there is no requirement to validate, it is odd to deem this as unacceptable in this table.
Has strengths that are not used.
The jump from IAL1 to IAL2 is too great and there is insufficient difference between IAL2 and IAL3.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
#1153 describes the approach to chapter 5 and IAL1.  #643 will resolve the IAL2 jump comment.
