### ISSUE TITLE
Table 5-3 has strengths that are not used. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1157]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.3.1, Table 5-3
 
**Comment (Include rationale for comment)**:  Table 5-3 has strengths that are not used.
 

**Suggested Change**: Remove or rethink
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We appreciate and understand this comment, but will retain this strengths for now.
