### ISSUE TITLE
Clarify physical comparison and use of equipment. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1158]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.3.1, Table 5-3
 
**Comment (Include rationale for comment)**:  Clarify physical comparison and use of equipment.
 
The requirement for strong states that there should be a “physical comparison” using “appropriate equipment”. There is an alternative requirement that allows for biometric comparison. For in person, it’s not obvious what equipment would be used for checking the subject against the photo evidence. For remote, perhaps this could be comparison by an operator for a live video stream, but much anything else using equipment would seem to be biometric.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #243
