### ISSUE TITLE
Is entropy actually a useful requirement for KBV. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1159]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.3.2, 
 
**Comment (Include rationale for comment)**:  Is entropy actually a useful requirement for KBV.
 
The third bullet suggests that the CSP should use transaction information of a certain entropy. In theory, this addresses the risk of discovery by guessing, but does not address the extent to which the information is published or available in the public domain. The net effect may be that the complexity requirement means that it’s simply harder for the subject to provide a correct response.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This relates specifically to micro-deposits, where the entropy of a transaction between 0 and 1.00 USD is not sufficient, hence the entropy requirement.
