### ISSUE TITLE
Online-guessing: a note needs to be added either here or 5.1.1 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1160]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 8.2 Threat Mitigation Strategies, Table 8-2
 
**Comment (Include rationale for comment)**:  Online-guessing: a note needs to be added either here or 5.1.1
 
Online-guessing: a note needs to be added either here or 5.1.1 that adding to entropy creates a converse risk where it increased the likelihood that authenticators will be written down, reused or stored in unsafe mechanisms.

**Suggested Change**: A note needs to be added either here or 5.1.1 that adding to entropy creates a converse risk where it increased the likelihood that authenticators will be written down, reused or stored in unsafe mechanisms.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The online guessing entry in 8.2 applies more generally to authenticator outputs (including things like OTP devices) and not just to memorized secrets.

This seems like an appropriate topic for the discussion of memorized secret complexity in Section A.3.
