### ISSUE TITLE
The strategy for "Multiple factors" isn't sufficiently specific. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1161]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 8.2 Threat Mitigation Strategies, 3
 
**Comment (Include rationale for comment)**:  The strategy for "Multiple factors" isn't sufficiently specific.
 
The “Multiple factors” makes a general statement that multiple (both?) factors increases authentication strength.

**Suggested Change**: It’s potentially more useful to highlight that each factor type addresses particular risks, and when two types (or better still three types) are used together, then the specific mitigations address the risks inherent in the other factor type – which we believe can be grouped as discovery risks and transfer risks.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The threat analysis section does not try to characterize every aspect of the threats and mitigations. It does correctly describe the fact that the use of multi-factor authentication requires additional capabilities on the part of the attacker, which is generally considered to be additional strength.
