### ISSUE TITLE
System and network security controls is a generic cyber security measure and not specific to authentication. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1162]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 8.2 Threat Mitigation Strategies, 3
 
**Comment (Include rationale for comment)**:  System and network security controls is a generic cyber security measure and not specific to authentication.
 

**Suggested Change**: Put in context
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This section does not specify system and network requirements, which indeed would be more appropriate in a generic cyber security context such as SP 800-53. However, the discussion of threat mitigations would be incomplete without including this.
