### ISSUE TITLE
Appendix A and creating similar advice 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1164]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Appendix A, 
 
**Comment (Include rationale for comment)**:  Appendix A and creating similar advice
 
All particularly useful advice. Ultimately it would be good to see similar advice for other form factors, particularly with regard to catering for real world use by online service users.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Similar advice for authenticators other than memorized secrets would be more implementation-dependent, and better suited for an implementation guide.
