### ISSUE TITLE
Assertion – definition indicates that the verifier provides “identity information” but this is potentially misleading. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1168]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 3. Definitions, 
 
**Comment (Include rationale for comment)**:  Assertion – definition indicates that the verifier provides “identity information”  but this is potentially misleading. 
 
The term “identity information” does not explicitly include the case where the identity is a pseudonymous identifier. The term “identity information” is ambiguous and depends on context, jurisdiction, etc.

**Suggested Change**: Reword definition to the assertion includes a subject identifier that may be pseudonymous and other attributes (which may or may not be independently verified).
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Definitions are moving into 63-3, so see #1114.
