### ISSUE TITLE
The distinction between “Attribute Claim” and “Attribute Value” is not entirely apparent. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1169]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 3. Definitions, 
 
**Comment (Include rationale for comment)**:  The distinction between “Attribute Claim” and “Attribute Value” is not entirely apparent. 
 
If Claim is meant to describe a derived value, then why not indicate that this is the case.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
We need another term here, because Claim is used in so many places. Perhaps privacy-enhancing attribute or something like that?

@nbl-nist how do you feel about that term?

**Comment by jricher** [comment]
I dislike "privacy enhancing attribute" as it ascribes value to the mechanism instead of describing it.

I had proposed "attribute reference" and "attribute value" previously and would suggest we use that.

**Comment by nbl-nist** [comment]
I could go with attribute reference in place of attribute claim.

**Comment by paul-grassi** [comment]
reference infers a pointer, which if you squint really hard could apply: 'older than 21' is a pointer to '1/4/1997'. With no context, it doesn't mean a whole lot.  I seek a term that can stand alone.

**Comment by jricher** [comment]
It's exactly the pointer notion that leads me to suggesting "reference" here. It's a reference to an attribute, not the value itself.

**Comment by jricher** [comment]
Closed by 2439d827e0aa379a5bee7e632ee899cf9ba3cac2
