### ISSUE TITLE
Authentication – definition refers to identity rather than possession. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1170]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 3. Definitions, 
 
**Comment (Include rationale for comment)**:  Authentication – definition refers to identity rather than possession.
 
The authentication process provides confidence in the subscriber’s possession of one or more authenticators at the corresponding AAL. The level of confidence about the identity depends on the strength of the registration business process that established the link to the person. Also, this document only addresses users and does not (fortunately) attempt to authenticate information systems.

**Suggested Change**: Reword definition to include confidence in possession of the authenticator. Remove reference to information systems.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will use FIPS200 definition which is used by many NIST documents.
