### ISSUE TITLE
Registration Authorities (RAs) are not covered in this abbreviation and definitions section. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1174]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 3, CSP
 
**Comment (Include rationale for comment)**:  Registration Authorities (RAs) are not covered in this abbreviation and definitions section.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Duplicate.  RA will be removed.
