### ISSUE TITLE
Identity proofing does not have to result in the issuance of a credential. E.g. IAL1 and a non-returning event 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1176]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 3, Identity proofing
 
**Comment (Include rationale for comment)**:  Identity proofing does not have to result in the issuance of a credential. E.g. IAL1 and a non-returning event
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Good catch.

**Comment by paul-grassi** [comment]
Resolved via issue #1111
