### ISSUE TITLE
Should register apply to CSP or RP? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1177]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 3, Register
 
**Comment (Include rationale for comment)**:  Should register apply to CSP or RP?
 
Does an applicant register with a RP for the service or register with the CSP for authenticators and optionally identifiers? If register is used for the CSP process, what is the verb for the RP application process? Enrolment, perhaps?

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
register should be removed in favor of enroll
