### ISSUE TITLE
Replace or redefine subject. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1178]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 3, Subject
 
**Comment (Include rationale for comment)**:  Replace or redefine subject.
 
The scope of 800-63 is restricted to requirements for person rather than including non-person entities. If this definition stands, then the documents should use person rather than subject. Alternatively, if subject is used as more or less meaning person, then this definition should be applied to entity, and a different definition used for subject.

**Suggested Change**: See comment for Applicant
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
we are leaving scope broad on purpose, as 63-3 will include NPEs.
