### ISSUE TITLE
Should subscriber relate to RP or CSP? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1179]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 3, Subscriber
 
**Comment (Include rationale for comment)**:  Should subscriber relate to RP or CSP?
 
This definition which emphasizes the CSP setup process, doesn’t cover the general use in the documents for describing the RP’s returning user. Does a person subscribe to a service, but bind to the CSP credentials?

**Suggested Change**: See comment for Applicant
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
In context of this document and the digital identity model, the subscriber definition is appropriate.
