### ISSUE TITLE
63C section 5.2.1 is hard to understand..

### ISSUE THREAD

**Issue by nov** [usnistgov/800-63-3#118]
**Organization**: 2

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63C

**Reference (Include section and paragraph number)**: 5.2.1. Shared Secret

**Comment (Include rationale for comment)**:

This section mentions about 128bit strength shared & assynmetric keys, but it doesn't talk about signing nor encryption.
Since following sections speaks about signing and encryption, I read this section is assuming not using signing nor encryption.
So now I'm confusing how the keys should be used.
What this section actually intend to say??

**Suggested Change**:

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
This section doesn't assume protection of the secret with signing or encryption, the secret is included in the assertion itself. This would map, for example, to the `jti` field in an ID token in OIDC -- an unguessable value recognizable by the IdP.

I think the term "shared secret" might be misleading, perhaps a better title: Assertion identifier?

**Comment by nov** [comment]
Thanks Justin,

+1 for section title change :)
