### ISSUE TITLE
Should valid be used to mean active? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1180]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 3, Valid
 
**Comment (Include rationale for comment)**:  Should valid be used to mean active?
 
This is an unusual definition for valid. Rather than being the opposite of invalid, it’s more like the opposite of inactive.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Definition should either go or be replaced by dictionary definition.
