### ISSUE TITLE
Introduces a further undefined term ‘digital authentication’, while not disagreeing with the statement it misuses the term ‘authentication’ as currently defined 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1181]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 1
 
**Comment (Include rationale for comment)**:  Introduces a further undefined term ‘digital authentication’, while not disagreeing with the statement it misuses the term ‘authentication’ as currently defined
 
 and as recommended.
More so when ‘authenticated identity’ appears.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
The document is scoped to online, remote, internet-based, aka digital authentication. The term is appropriate.
