### ISSUE TITLE
Need to watch the confusion between applying the suite to building an enrolment system and applying the suite to integrating with an existing enrolment system. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1182]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 3
 
**Comment (Include rationale for comment)**:  Need to watch the confusion between applying the suite to building an enrolment system and applying the suite to integrating with an existing enrolment system.
 
Introduces the term ‘identifier’ which has not been defined.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
No suggested change offered.
