### ISSUE TITLE
Does CSP bind to a credential, an account, or… 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1183]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 3
 
**Comment (Include rationale for comment)**:  Does CSP bind to a credential, an account, or…
 
The statement that “the CSP creates a credential and binds it to one or more authenticators” implies that credential only means a unique identifier (or perhaps more amorphous identity). The authenticator elements are typically also understood as CSP credentials.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
In this document an authenticator may convey nothing about an identity.  The credential is the record that is bound to an identity.  We remain agnostic to whether an authenticator and credential can be the same thing.
