### ISSUE TITLE
Not subscriber. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1184]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 3
 
**Comment (Include rationale for comment)**:  Not subscriber.
 
The “subscriber” is still an applicant at this point – aren’t they?

**Suggested Change**: Use individual?
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
paragraph should be re-worked to align to new model.
