### ISSUE TITLE
Replace "with their real world identity". 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1185]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 4
 
**Comment (Include rationale for comment)**:  Replace "with their real world identity".
 

**Suggested Change**: Use “with the person”. Or “individual” if that’s clearer.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We are happy with the clarity and easy-to-read aspect of this phrase.
