### ISSUE TITLE
Introduces the term ‘real world’ which is not defined and is incongruent when considering IAL1. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1186]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 4
 
**Comment (Include rationale for comment)**:  Introduces the term ‘real world’ which is not defined and is incongruent when considering IAL1. 
 
It can also be taken to mean official government identity which is not a concept contained in the definition of ‘identity’.

**Suggested Change**: See earlier comment
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
handled in other issues.  identity proofing requirements, writ large, start with no proofing to a lot of proofing.  To proof is to prove your real life identity. IAL1 is no proofing. Therefore, we are content with this phrase.
