### ISSUE TITLE
‘At IAL1, identity proofing is not required…’ is a false statement, as IAL1 is an identity proofing level. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1187]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 4
 
**Comment (Include rationale for comment)**:  ‘At IAL1, identity proofing is not required…’ is a false statement, as IAL1 is an identity proofing level. 
 

**Suggested Change**: Suggest change to …’identity verification is not required…’
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We define proofing in 2.1. Expected Outcomes of Identity Proofing, which states all functions are required, not just verification.
