### ISSUE TITLE
Replace “self-asserted and not verified” . 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1188]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 4
 
**Comment (Include rationale for comment)**:  Replace “self-asserted and not verified” .
 
For some identity attributes such as ethnicity the person is the authoritative source, and there is no possibility of further verification.

**Suggested Change**: Use "independently verified". 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We appreciate this perspective, but at IAL1, there is little confidence in the information being asserted by the user, hence treat it as self-asserted.  Yes, I am the auth source that I am Italian, but online I could be Irish.
