### ISSUE TITLE
This paragraph hits upon the idea that it is about attributes and not identity. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1190]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 6
 
**Comment (Include rationale for comment)**:  This paragraph hits upon the idea that it is about attributes and not identity. 
 
If this could be promulgated throughout the suite a number of terminology and understanding problems would be resolved. Experts in NZ would fully support this approach.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We appreciate the notion that identity is really just attributes, but we prefer to keep using this term as it works with our stakeholders.
