### ISSUE TITLE
Device identity and geo-location are something you have. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1192]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 8
 
**Comment (Include rationale for comment)**:  Device identity and geo-location are something you have.
 
While device identity or geo-location can be an effective method of reducing the risks of discovery and transfer, these are not additional factors, but just another form of something you have. Although these potentially offer more precision, as with biometrics these are able to be spoofed by a skilled attacker.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
No suggest change offered.
