### ISSUE TITLE
Separate authentication CSP and identity CSP in diagram. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1193]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, Fig 4-1
 
**Comment (Include rationale for comment)**:  Separate authentication CSP and identity CSP in diagram.
 
As noted elsewhere, the CSP for authentication (and a pseudonymous identifier) can be separate from one or more CSPs  providing identity attributes. If the diagram were modified to show this case, it becomes clearer that identity proofing and enrolment at the RP is a one-time process, and subscriber authentication is the repeated returning user process. Arguably the person’s involvement as Applicant, Subscriber and Claimant would be clearer if split into two diagrams that show first time and returning to the RP.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is a good comment, in addition, we use term IDP not CSP, so we should fix.  Some notion that the CSP for proof need not be the same as authN further explains our new approach of IAL and AAL.

**Comment by paul-grassi** [comment]
We contemplated, but as an overall graphic, adding 2 CSPs would make it too busy.
