### ISSUE TITLE
MFA should be expanded first time. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1194]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.3.1, 2
 
**Comment (Include rationale for comment)**:  MFA should be expanded first time.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
2nd instance need not spell out MFA.

**Comment by paul-grassi** [comment]
Turns out the document is correct.  MFA is spelled out in Exec Summ and then again in intro of document.  The unexpanded version in Section 4 is correct.
