### ISSUE TITLE
Two versus three factors. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1195]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.3.1, 2
 
**Comment (Include rationale for comment)**:  Two versus three factors.
 
While it’s correct that two factors (of different types) are typically stronger than one factor (something you know), it’s worth stating that three factors of different types is typically even stronger.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Old version said that 3 factors was overkill so we removed.  But we can make a logical statement that the more factors the better
