### ISSUE TITLE
Is there too much here? Should it be left to 3B 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1197]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.3.1, All
 
**Comment (Include rationale for comment)**:  Is there too much here? Should it be left to 3B
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We are content with the amount of informational material in this chapter.
