### ISSUE TITLE
Use "individual" more widely. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1198]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5, 1
 
**Comment (Include rationale for comment)**:  Use "individual" more widely.
 
The two points effectively use “individual” demonstrating that this is at least as good as “person” and definitely better than “subject”. Reconsider the use of individual as key term?

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
In its current form individual is a good term, but we are leaving the scope open to NPE, so subject is appropriate.
