### ISSUE TITLE
Authentication error is misleading. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1199]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5, 3
 
**Comment (Include rationale for comment)**:  Authentication error is misleading.
 
As commented elsewhere, an authentication is binary (success or fail) therefore an error isn’t really possible. Condition (1) is a discovery or transfer attack where the claimant is not the subscriber. Condition (2) is an identity fraud attack (or perhaps admin failure) during identity proofing. In both cases, the attacker can access an online service that they are not authorized to do. Using authentication error, however, isn’t a useful description, as the issue isn’t addressed by “fixing” the authentication per se.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Authentication error is an m0404 term that will retain in this version, which is a transition from LOA to individual xAL.  In addition, the document describes that authentication error is misleading, and breaks it down in the context of proofing and authentication.
