### ISSUE TITLE
2nd bullet point, this is a privacy risk not identity risk. The second identity risk is that someone receives or takes over the authenticator that 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1200]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5, 3
 
**Comment (Include rationale for comment)**:  2nd bullet point, this is a privacy risk not identity risk. The second identity risk is that someone receives or takes over the authenticator that has been bound to the identity.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
No suggested change provided.  However, this risk is described in the authenticator portion, so we are covered properly.
