### ISSUE TITLE
IAL3 – rules out the ability to have a high strength identity bound to a high strength authenticator for the digital channel. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1201]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.1, 2
 
**Comment (Include rationale for comment)**:  IAL3 – rules out the ability to have a high strength identity bound to a high strength authenticator for the digital channel.
 
 This comes from a failure to understand at a principle level what is required to do identity proofing.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
no suggested change offered.
