### ISSUE TITLE
This is trying to put a square peg in a round whole but better than nothing 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1202]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.2, All
 
**Comment (Include rationale for comment)**:  This is trying to put a square peg in a round whole but better than nothing
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
thanks
