### ISSUE TITLE
The categories for risk are flawed – Inconvenience, distress and personal harm are impacts of the other things occurring. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1203]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.3.1, Fig 5-1
 
**Comment (Include rationale for comment)**:  The categories for risk are flawed –  Inconvenience, distress and personal harm are impacts of the other things occurring.
 

**Suggested Change**: They should be Financial loss or liability, Unauthorised release of sensitive information, Loss of reputation, qualification or brand and other (which would include Civil or criminal violations).
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE with April 1 update to -3.
