### ISSUE TITLE
The first ‘No’ should actually go to IAL0. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1205]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.3.3, Fig 5-2
 
**Comment (Include rationale for comment)**:  The first ‘No’ should actually go to IAL0.

 
Unsure of the value of additional steps in diagram after the IAL has been determined as it changes nothing. Use of Federation is not determined by the need to resolve uniqueness.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
we appreciate the approach to IAL0, but we will remain with IAL1 as the starting point, where 0 to n attributes are provided, yet self-asserted and not verified.
