### ISSUE TITLE
There appears to be an assumption that the stronger the IAL the more Govt official the identity must be. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1206]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: All, 
 
**Comment (Include rationale for comment)**:  There appears to be an assumption that the stronger the IAL the more Govt official the identity must be. 

 
If you are to apply the definition that you have chosen then IAL strength relates to degree to which the attributes are correct and owned by the claimant, whatever they are.

**Suggested Change**: If you want this suite of documents to be the rules for specific attribute set then say so up front. 
As currently written a large amount of the content of this document is inconsistent and contrary.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This comment is difficult to parse.  Nowhere do we state that the higher the IAL the more government official the identity is, nor do we state the required set of attributes that need to be verified (there are comments about the definition of core attributes that we have accepted). The inconsistent comment is related to the issue regarding core attributes, which we have accepted, therefore we will achieve the consistency desired herein.
