### ISSUE TITLE
There is some greying of the boundary between what is an identity proofing activity (which IAL is about) and what is the process for binding 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1207]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: All, 
 
**Comment (Include rationale for comment)**:  There is some greying of the boundary between what is an identity proofing activity (which IAL is about) and what is the process for binding to an authenticator – 
 

**Suggested Change**: Make these more clearly separated.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We're pretty clear in the sense that binding is a section in -A and points to common requirements defined in -B
