### ISSUE TITLE
A number of comments, especially those regarding the use of terms, contained in the overview also apply to this document. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1208]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: All, 
 
**Comment (Include rationale for comment)**:  A number of comments, especially those regarding the use of terms, contained in the overview also apply to this document.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Terms will be resolved via #898
