### ISSUE TITLE
Consider relevance of binding in 800-63A. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1209]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.4, 
 
**Comment (Include rationale for comment)**:  Consider relevance of binding in 800-63A.
 
In the overview document it states that this document covers the binding to an authenticator, however this section just refers to another document.

**Suggested Change**: Either put initial binding to an authenticator here or remove mention of this document and or IAL, as covering this aspect, from the overview. NB This was already noted as an inconsistency within the overview document.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We are comfortable with binding being in -B, and the requirements therein, and also think the link to binding in -A is helpful
