### ISSUE TITLE
This section is about the linking of authenticators to identity be fact of 5.4 this is dealt with elsewhere. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1210]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 6, 
 
**Comment (Include rationale for comment)**:  This section is about the linking of authenticators to identity be fact of 5.4 this is dealt with elsewhere. 
 

**Suggested Change**: This section should also be in the elsewhere (63B).
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
6 is more about proofing identity based on authenticator possession, but if we do treat binding in a new way based on comments, this comment may be applicable, so keeping open.

**Comment by paul-grassi** [comment]
Will be resolved via #628
