### ISSUE TITLE
Reconsider requirement for primary and secondary. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1211]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 6, 7
 
**Comment (Include rationale for comment)**:  Reconsider requirement for primary and secondary.
 
This paragraph introduces the concept of primary authenticators and secondary authenticators. This does not appear to have been defined anywhere and the distinction is unclear.

**Suggested Change**: [Include in 800-63B if valid.]
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Good comment to get these defined.

**Comment by paul-grassi** [comment]
OBE via changes to Ch6.  See #597
