### ISSUE TITLE
RP authorization decisions are independent from CSP authenticator management. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1212]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 6.1, Item 4
 
**Comment (Include rationale for comment)**:  RP authorization decisions are independent from CSP authenticator management.
 
This point mixes the RP’s responsibility for authorization to access the online service with the CSP’s operational support of the authenticator. Except when the subscriber deregisters from the CSP, or perhaps a very long period of inactivity, there is no reason to make an authenticator invalid (whatever that might mean).  Even if the IdP issues a successful authentication, it’s the RP’s responsibility to determine if any resources should be accessed.

**Suggested Change**: Remove this requirement [which should have been in 800-63B]. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This section is all about getting a new authenticator based on possession of a primary.  This use case, as specified in Section 6, Item 1, is not about authorization to an RP, but about the privilege or authorization to even hold a primary authenticator.  The example, a PIV, is given to someone based on their status as an active federal employee.  If they are not authorized to have the PIV, they shouldn't have the secondary.
