### ISSUE TITLE
New authenticator requirement is insufficient. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1213]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 6.1, Item 7
 
**Comment (Include rationale for comment)**:  New authenticator requirement is insufficient.
 
While in practice it may be easiest to have an initial authenticator – typically a password as a something you know factor that can be used by itself, in principle there does not seem to be any reason to correlate the same or different types. That said, the AAL of the subscriber’s account is important. The user should not be able to add or modify a credential at a lower level of authentication than the highest AAL combination for the CSP account to prevent takeover of a stronger set by a weaker credential.

**Suggested Change**: Requirements for a new authenticator should be matched to the highest AAL on the subscriber's CSP account. [Cover this in 800-63B]
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
CSP can issue any AAL they want (or based on the use case of the user).  It is expected that the RP will enforce what authenticator AAL is valid.  For example, I have an AAL3 PIV card that can get me anywhere, but if a mobile authenticator stored in software is issued to me, that is a valid authenticator and at a lower AAL (likely 2).  Any RP I access with the mobile AAL2 authenticator needs to enforce whether I can access service with this lower AAL authenticator.
