### ISSUE TITLE
The stated AAL3 requirements seem to be too tough, and indeed in some cases unnecessary. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1214]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 6.3, 
 
**Comment (Include rationale for comment)**:  The stated AAL3 requirements seem to be too tough, and indeed in some cases unnecessary. 
 
 If a subscriber can authenticate at AAL2 – if that is the highest combination on their CSP account, they don’t need to have an in-person verification, particularly if the IdP operates with pseudonymous identity. For example, if the person has a password and an OTP token, they only need to authenticate at AAL2 to add another something you have like SMS token or Google Authenticator OTP. It’s only when the person requires a higher IAL that it becomes necessary to ensure that the binding between the identity and authenticators takes place at the corresponding strength.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
As I reread the requirements, perhaps when we get to biometrics we are making this too difficult.  Need to compare with 800-157.

**Comment by paul-grassi** [comment]
will be resolved via #628
