### ISSUE TITLE
Risk of becoming outdated rapidly whan legislation changes 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1216]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 8, 
 
**Comment (Include rationale for comment)**:  Risk of becoming outdated rapidly whan legislation changes
 
There is a risk that this section could be in conflict if changes to legislation are made.

**Suggested Change**: It may be better to refer to the relevant legislation or policies in general
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
We will revise as needed.
