### ISSUE TITLE
Inconsistent use of terms. Refer comments in previous two documents 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1217]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 2. Introduction, All
 
**Comment (Include rationale for comment)**:  Inconsistent use of terms. Refer comments in previous two documents
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
See #1167, #1117, #1112, #1089

**Comment by dig-comments** [comment]
@jimfenton #1089 is a noted and closed IMO.

**Comment by jimfenton** [comment]
The definitions are being moved to the -3 volume.

Noted that this comment cites Section 2; we are making some terminology adjustments in response to other comments but need more specific examples to respond to this issue.
