### ISSUE TITLE
A progression of 1 then 2 then 3 factors for strength may be too simplistic. Certain combinations are weaker than others. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1220]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 2.Introduction, 6,7,8
 
**Comment (Include rationale for comment)**:  A progression of 1 then 2 then 3 factors for strength may be too simplistic. Certain combinations are weaker than others. 
 

**Suggested Change**: A principle based approach based on the threats may need to be considered.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The requirements for AAL1, AAL2, and AAL3 are considerably more nuanced; normative requirements are in Section 4. Section 2 is only a non-normative introduction.

Note that AAL3 is not 3-factor authentication.
