### ISSUE TITLE
What does high confidence mean? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1222]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 2. Introduction, 7,8
 
**Comment (Include rationale for comment)**:  What does high confidence mean?
 
While AAL2 and AAL3 are respectively more robust authentication, the terms “high confidence” and “very high confidence” does not seem to clearly describe that additional risks are mitigated.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
These are only relative terms: "some assurance" at AAL1, "high confidence" at AAL2, and "very high confidence" at AAL3. Section 2 is a non-normative introduction section; detailed information on each AAL is given in Section 4. Threat comparison is discussed (again non-normatively) in section 8.
