### ISSUE TITLE
See comments to previous two documents for detailed issues with terms 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1223]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 3. Definitions, ALL
 
**Comment (Include rationale for comment)**:  See comments to previous two documents for detailed issues with terms
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Previous comments have been responded to; not sure there is a new comment here.
