### ISSUE TITLE
This is a very good replacement for token. Further clarity will occur if ‘authentication’ is restricted to the context of using an authenticator. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1224]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 3. Definitions, Authenticator
 
**Comment (Include rationale for comment)**:  This is a very good replacement for token.  Further clarity will occur if ‘authentication’ is restricted to the context of using an authenticator. 
 
This is so when it is an extension (e.g. authentication secret) but not when it is used on its own.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Thank you for the comment on the use of _authenticator_. While the term _authentication_ has a fairly broad definition in Section 3, the fact that SP 800-63B deals with authentication using one or more authenticators is made clear in Section 2, paragraph 2. As noted in the definition of _authentication secret_, not all authentication secrets, particularly short-term ones, are associated with authenticators.
