### ISSUE TITLE
Authenticator Assurance Level (AAL). Is this a “metric”? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1225]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 3. Definitions, 
 
**Comment (Include rationale for comment)**:  Authenticator Assurance Level (AAL). Is this a “metric”? 
 
Authenticator Assurance Level (AAL). Is this a “metric”? While AAL is defined as 3 levels, it does not use scoring or some other method of measurement. Scoring may be a better approach than the current single factor, two factor, multi-factor recommendations which are not consistently recommended.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The term _category_ is probably more appropriate than _metric_ because it does not denote a measurement. As with previous editions of SP 800-63, we are not adopting a scoring system.

Recategorizing as 63-3 because the definitions are moving there.

**Comment by jimfenton** [comment]
Previously fixed by 16af10079890a9ad4e57995e2bbcac501a623311
