### ISSUE TITLE
The use of “a given level of strength” seems better than the use of “confidence” in the introduction. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1226]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4. Authenticat-ion Assurance Levels, 1
 
**Comment (Include rationale for comment)**:  The use of “a given level of strength” seems better than the use of “confidence” in the introduction. 
 
This paragraph clearly describes that a subscriber (i.e. returning user) is being authenticated and the identifier can be pseudonymous, and other identity attributes are optional.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The introduction uses both _confidence_ and _strength_ in various places. Confidence is what results from the use of an authentication method that has sufficient strength. We believe the use of the terms to be correct.
