### ISSUE TITLE
Single factor requirement restricts potential authenticator solutions. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1227]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.1 Authentica-tor Assurance Level 1, 1
 
**Comment (Include rationale for comment)**:  Single factor requirement restricts potential authenticator solutions.
 
Should it always be the case that AAL1 “requires single-factor authentication”? For example, is a relatively weak memorized secret like a 4-digit PIN plus a relatively weak something you have like a browser cookie effectively a two-factor authentication approximately equivalent to a typical password?

**Suggested Change**: Remove "requirement" for single-factor authenticator for AAL1. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
_Requires_ is the wrong word to use here, particularly since multi-factor authenticators may be used at AAL1.

**Comment by jimfenton** [comment]
We do not recognize combinations of weaker authentication factors to satisfy single-factor authentication. The "requires" term was already fixed in #1056
