### ISSUE TITLE
Single factor constraint for AAL1 restricts authenticator solution options (and listed examples). 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1228]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.1 1 Permitted authenticator types, 
 
**Comment (Include rationale for comment)**:  Single factor constraint for AAL1 restricts authenticator solution options (and listed examples).
 
If there is a requirement to restrict AAL1 to single factor, then the list of authenticator types includes non-single factor authenticators such as multi-factor cryptographic device. We believe that the only type of single factor authenticator that can be used by itself is something you know. Something you have may not be in the possession of the owner at the time of authentication, and something you are has the constraints as outlined in 800-63B. While it’s important that a single factor authenticator is something you know, should this be synonymous with AAL1 (which is arguably a simple constraint) or should there be both single and two-factor mixes for AAL1 or an expansion of the three authenticator assurance levels?

**Suggested Change**: Remove "requirement" for single-factor authenticator for AAL1. Restrict single factor to something you know authenticators.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The word _requirement_, and the implication that AAL1 is restricted to single-factor, is being addressed by #1227.

Physical authenticators will continue to be acceptable for single-factor authentication at AAL1. They have different threat characteristics from memorized secrets, but overall provide comparable strength.
