### ISSUE TITLE
Something you have authenticators are ineffective as single factor authenticators. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1229]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.1 1 Permitted authenticator types, 
 
**Comment (Include rationale for comment)**:  Something you have authenticators are ineffective as single factor authenticators.
 
A look up secret is a something you have (i.e. the grid card) and therefore it cannot be used by itself as there is no assurance that the current holder is the registered subscriber.
An out of band device is something your have. Arguably the registration of the additional channel may provide some benefit, but there is no assurance that the user is the subscriber, if not used in combination with another factor type.

**Suggested Change**: Remove the something you have authenticators (as single factors). Review conflict between single factor assumption and multi-factor device examples.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
While it is true that a physical authenticator alone has the weakness that it can be used by other than the subscriber, memorized secrets also can be appropriated by impostors. For that reason, multi-factor authentication needs to be used whenever there is any significant risk associated with mis-authentication.
