### ISSUE TITLE
AAL2 does not need to be restricted to something you know and something you have only. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1231]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.2.1 Permitted Authenticator Types, 3
 
**Comment (Include rationale for comment)**:  AAL2 does not need to be restricted to something you know and something you have only.
 
While false match rates might limit the usability of a something you are authenticator, the combination with something you have would seem to offset both the probabilistic matching and transferred biometric. Section 5.2.3 seems to acknowledge this two-factor combination. Arguably the combination of a memorized secret and biometric are limited by pragmatic considerations rather than risk.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by enewt** [comment]
See the note at the bottom of 4.2.1 in 63-B.
