### ISSUE TITLE
Clarify the AAL3 12 hour requirement. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1235]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.3.3 Reauthen-tication, 
 
**Comment (Include rationale for comment)**:  Clarify the AAL3 12 hour requirement.
 
Presumably the subscriber can’t normally sustain an active session for 12 hours, particularly with a 15 minute inactivity timeout. It’s not clear how a session will extend over this prolonged period.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The intent is to not interrupt the user who is actively using an authenticated service during a (long) working shift. See also #1230; we will clarify the meaning of "session".
