### ISSUE TITLE
Requirements in this table are not based on principles and may therefore be subject to dating as new technology and methods evolve. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1236]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.5 Summary of Requirements, Table 4-3
 
**Comment (Include rationale for comment)**:  Requirements in this table are not based on principles and may therefore be subject to dating as new technology and methods evolve. 
 

**Suggested Change**: Suggest that a focus on the threats may bring an alternative approach. See also comment on AAL levels in the Introduction.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Table 4-3 is only a non-normative summary of requirements discussed earlier in Section 4. Further discussion of threats can be found in Section 8.
