### ISSUE TITLE
Some of the authenticators for AAL1 are not sufficient for something you know as a single factor. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1237]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.5 Summary of Requirements, Table 4-3
 
**Comment (Include rationale for comment)**:  Some of the authenticators for AAL1 are not sufficient for something you know as a single factor.
 
For example, a single factor OTP is a something you have with no certainty of possession by the subscriber for a particular authentication.

**Suggested Change**: Allow two-factor authenticator combinations for AAL1 but restrict single factor to memorized secret only.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
See response to #1221.
