### ISSUE TITLE
This table contains items relating to the strength of the authenticator (and its use by the user) which are identity items. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1238]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.5 Summary of Requirements, Table 4-3
 
**Comment (Include rationale for comment)**:  This table contains items relating to the strength of the authenticator (and its use by the user) which are identity items. 
 
It also contains items relating to the strength of the message and the environment (as this is only looking at online this means cyber security). 

**Suggested Change**: While both aspects are important to capture,  they should be separated.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
It is unclear what is meant by "identity items", but in any case Table 4-3 is non-normative and intended to summarize requirements at each AAL. Separating it into two tables would be counter to that goal.
