### ISSUE TITLE
This contains a thorough reference for authenticator types and is of great value. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1239]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5. Authenticator and Verifier Requirements, ALL
 
**Comment (Include rationale for comment)**:  This contains a thorough reference for authenticator types and is of great value.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Thank you.
