### ISSUE TITLE
Setting a requirement that contradicts one of the most common use cases is an example that the simplistic 1+2+3 approach to authentication strength may be 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1241]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.1.1 Memor-ized Secret Authenticators, 
 
**Comment (Include rationale for comment)**:  Setting a requirement that contradicts one of the most common use cases is an example that the simplistic 1+2+3 approach to authentication strength may be flawed.
 

**Suggested Change**: It would be valid to say that ‘…when used as the only factor, memorized secrets SHALL be at least 8 characters in length…’
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
See response to #1240.
