### ISSUE TITLE
This is a matter of context. SMS has its place when used in conjunction with other factors such as password as mitigation against a number 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1243]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.3.2 Out-of-band Verifiers, Note
 
**Comment (Include rationale for comment)**:  This is a matter of context. SMS has its place when used in conjunction with other factors such as password as mitigation against a number of threats.
 

**Suggested Change**: Rather than rule it out, put it in context.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
It already is in context as a valid factor at AAL2.  In fact, we specified additional requirements to shore up many SMS vulnerabilities.
