### ISSUE TITLE
The 100 consecutive attempts control is not required in all circumstances. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1244]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.2 Rate LImiting, 1
 
**Comment (Include rationale for comment)**:  The 100 consecutive attempts control is not required in all circumstances.
 
If there are other controls in place (for example; 3 attempts, 15 minute lockout, IP address monitoring), then the count limit of 100 consecutive failed attempts may not add any effective additional deterrence, if the memorized secret isn’t easily guessable.

**Suggested Change**: Change SHALL to CAN.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
100 consecutive failed attempts is a high enough limit that it is very unlikely that the subscriber will encounter the limit, and provides protection against long-duration slow guessing attacks.
