### ISSUE TITLE
The recommendation for limited use of biometrics seems to be overstated. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1245]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.3 Use of Biometrics, 1
 
**Comment (Include rationale for comment)**:  The recommendation for limited use of biometrics seems to be overstated.
 
While the listed constraints for biometrics are relevant, the recommendation for limited use does not seem to recognise that there are comparable issues for other factor types such as the fact that passwords are written down and OTP devices are not always in the subscriber’s possession. Used as a second or third factor, something you are adds additional mitigation to the discover or transfer risks for something you know or something you have.

**Suggested Change**: Like something you have, something you are cannot be used as a single factor, but biometric authenticators should be recommended as the second (or third) factor to overcome the intrinsic risks with memorized secrets or possession authenticators.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by enewt** [comment]
The suggested change is already what draft 63-b allows.
