### ISSUE TITLE
PAD should be added to Definitions and Abbreviations. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1248]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.3 Use of Biometrics, 1
 
**Comment (Include rationale for comment)**:  PAD should be added to Definitions and Abbreviations.
 

**Suggested Change**: PAD should be added to Definitions and Abbreviations.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Tagging as 63-3 because the definitions and abbreviations are moving there.
