### ISSUE TITLE
As well as being used in conjunction with something you have, a biometric could be used with something you know 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1249]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.3 Use of Biometrics, 2
 
**Comment (Include rationale for comment)**:  As well as being used in conjunction with something you have, a biometric could be used with something you know 
 
– for example, voice could be captured by phone without needing a specialized device.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by enewt** [comment]
The reason for this is explained in a Note in 4.2.1. To implement biometrics the device needs to be authenticated - that is something the user has. Therefore adding something you know when using biometrics is always a third factor.
