### ISSUE TITLE
The requirement for binding authenticators may not be sufficient to protect the AAL level of the CSP account. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1251]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 6.1.2.1 Binding of an additional authenticator, 2
 
**Comment (Include rationale for comment)**:  The requirement for binding authenticators may not be sufficient to protect the AAL level of the CSP account. 
 
The authenticator itself does not have an AAL. Depending on the implementation, it may be necessary for the subscriber to add a new authenticator at the highest level for any authenticator on the account. If a subscriber adds a new authenticator at AAL1 or AAL2, then there needs to be a constraint that prevents any modification to a higher level authenticator or the contact channels that might be used to send a notification to a subscriber.

**Suggested Change**: An additional authenticator should be bound at the highest AAL for the CSP account.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Will be addressed by resolution to #1163.
