### ISSUE TITLE
A CSP doesn’t necessarily need to revoke an authenticator in circumstances such as death, particularly if the authenticator is only bound to pseudonymous identity. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1252]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 6.4 Revocation and Termination, 1
 
**Comment (Include rationale for comment)**:  A CSP doesn’t necessarily need to revoke an authenticator in circumstances such as death, particularly if the authenticator is only bound to pseudonymous identity. 
 
The service provider (the RP) needs to revoke access for online identity, so that subscriber’s services and entitlements are no longer available regardless of any subsequent authentication attempts. Enitlement fraud at one RP may not be sufficient for disentitlement at all RPs. CPS authentication should be separate from RP authorisation.

**Suggested Change**: Remove this revocation requirement for the authenticator at the CSP.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Fraudulent activity involved deceased persons is a significant problem. Revocation of authenticators provides an extra level of protection against such fraud, especially in federated identity situations.
