### ISSUE TITLE
The table should include authenticator specific threats. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1254]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 8.1 Authentic-ator Threats, Table 8-1
 
**Comment (Include rationale for comment)**:  The table should include authenticator specific threats.
 
Some of the listed threats and attacks are not directly related to the user and CSP’s use of an authenticator, but more general cyber security considerations – in particular, the Endpoint compromise threats such as malicious code.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Same response as #1162.
