### ISSUE TITLE
The threat of eavesdropping is a general cyber security concern rather than being specific to authentication. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1256]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 8.2 Threat Mitigation Strategies, Table 8-2
 
**Comment (Include rationale for comment)**:  The threat of eavesdropping is a general cyber security concern rather than being specific to authentication. 
 
Malware can be used not only to capture a memorized secret, but also other personal information such as credit card details, images, etc.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
As noted in #1162, for completeness we are including relevant general cyber security threats/mitigations and not just those specific to authentication.
