### ISSUE TITLE
Use of multi-factor authenticators is missing as a mitigation for a number of threats – e.g. Phishing, Social engineering, Eavesdropping, on-line guessing etc 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1258]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 8.2 Threat Mitigation Strategies, Table 8-2
 
**Comment (Include rationale for comment)**:  Use of multi-factor authenticators is missing as a mitigation for a number of threats – e.g. Phishing, Social engineering, Eavesdropping, on-line guessing etc
 

**Suggested Change**: Add in to other areas
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Multi-factor authenticators do not, by themselves, mitigate threats such as phishing and social engineering. If the user can be tricked into revealing their authenticator output to an impostor, they can be tricked into multi factor authentication as well. Use of authenticators that provide verifier impersonation resistance is helpful in these cases.

Eavesdropping and on-line guessing are also not particularly addressed by multi-factor authentication, although perhaps there is more that has to be eavesdropped or guessed.
