### ISSUE TITLE
Omit/Change Entitlement Determination

### ISSUE THREAD

**Issue by BSI-github** [usnistgov/800-63-3#1259]
Organization Name (N/A, if individual): Biometric Signature ID, NASPO IDP-V Member

Organization Type (see below for codes): 2
 
Document (63-3, 63A, 63B, or 63C): 63A

Reference (Include section and paragraph number): 4.2 [1] (Page unknown via HTML)
 
Comment (Include rationale for comment): "Identity proofing SHALL NOT be performed to determine suitability/entitlement to gain access to services or benefits." would appear to contradict the very purpose of not only the document, but the reasons for the identity proofing itself, at least with it's current wording. For example, for some AARP benefits one must prove they are 65 or older, this can only be achieved by proofing his identity as LAST, FIRST and AGE.
 
Suggested Change: Omit the text, or change the wording if need be.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Resolved via #677
