### ISSUE TITLE
Multiple Devices Should Be Allowed For Certain Forms Of Biometrics

### ISSUE THREAD

**Issue by BSI-github** [usnistgov/800-63-3#1260]
Organization Name (N/A, if individual): Biometric Signature ID, NASPO IDP-V Member

Organization Type (see below for codes): 2
 
Document (63-3, 63A, 63B, or 63C): 63B

Reference (Include section and paragraph number): 5.2.3 (Page unknown via HTML)
 
Comment (Include rationale for comment): "Use of the biometric SHALL be limited to one or more specific devices that are identified using approved cryptography." only applies to certain biometrics, and does not confirm to usage for gesture biometrics that, for example, can be achieved on any desktop, laptop or mobile devices. This would be true for almost all software based biometric systems.

 
Suggested Change: Omit the text, or reword as to include software biometrics from multiple devices
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by enewt** [comment]
Trust in the biometric sensor is important for any modality.
