### ISSUE TITLE
Level of identity assurance (IAL2) is too restrictive 

### ISSUE THREAD

**Issue by CMSComments** [usnistgov/800-63-3#1261]
**Organization Name (CMS):**

**Organization Type (1)**:
 
**Document (63A)**:

**Reference (Section 4.2)**:
 
**Comment (Level of identity assurance (IAL2) is too restrictive and is unable to scale or be automated.
IAL2 requires validation of some form of photo/image/biometric, this would require the Agency to provide document verification as part of the remote identity proofing process for all use cases. This solution does not scale for solutions which support millions of users nationwide. )**:
 
**Suggested Change* Strongly consider providing at least 2 levels that support remote identity verification. It is our recommendation that NIST allow one of these levels to use some combination of “Fair” levels of evidence to be used to support those use cases where a combination of “Strong” and “Fair” levels are not appropriate nor justified.   These two levels would allow agencies such as  the ability to make a risk based determination of the appropriate level of remote proofing to be used to support specific agency use cases.*:
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Resolved via #643
