### ISSUE TITLE
iconectiv joins many in the industry in expressing concern about NIST's proposed discouragement of SMS as a two-factor authentication method. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1262]
**Organization Name (N/A, if individual)**: iconectiv

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.3.2, 2
 
**Comment (Include rationale for comment)**:  iconectiv joins many in the industry in expressing concern about NIST's proposed discouragement of SMS as a two-factor authentication method.
 
Moreover, the phrase "removal in future editions" reflects a time-locked vision of SMS.  

1. ignores huge security improvements in various emerging technologies and the networks of the future               
2. should preserve the option of conducting a risk management approach to authentication which includes the use of SMS text as an out-of-band authentic tool for appropriate industry use scenarios, just as would be done for any authentication mechanism

**Suggested Change**: amend to "Out-of-band authentication using the PSTN (SMS or voice) will be discouraged and considered for
 removal in future editions of this guideline if the above and other risk mitigation techniques
 prove ineffective or too difficult for federal agencies to implement"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
New edits available via #1827
