### ISSUE TITLE
LOA Levels 2 & 3 are now combined into Identity Assurance Level IAL 2 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1263]
**Organization Name (N/A, if individual)**: Boeing

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.7. Summary of Requirements , Table 4-3
 
**Comment (Include rationale for comment)**:  LOA Levels 2 & 3 are now combined into Identity Assurance Level IAL 2
 
Mid-level IAL (2) assurance is much more stringent than previous LOA2 and may not be achievable in all use cases.  For instance, non-US, remote users.  This will  force those use cases to the lower level of assurance,  IAL 1,  which does not require evidence or validation.  Thus nulifying any requirement for evidence or verification leaving "Zero" level of assurance.

**Suggested Change**: Offer four IAL levels to enable something stronger than IAL 1 which is basically no assurance but less than  IAL2. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #643
