### ISSUE TITLE
IAL 2 requires 2 STRONG OR 1 STRONG and 2 ADEQUATE 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1264]
**Organization Name (N/A, if individual)**: Boeing

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**:  Properties of Identity Evidence, Table 5-1
 
**Comment (Include rationale for comment)**:  IAL 2 requires 2 STRONG OR 1 STRONG and 2 ADEQUATE
 
 ADEQUATE is not defined

**Suggested Change**: Define ADEQUATE evidence and verification method.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #518
