### ISSUE TITLE
In previous releases the NIST 800-63 version combined the scores of both the credentials and the surrounding processes into a single value. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1266]
**Organization Name (N/A, if individual)**: Boeing

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: , 
 
**Comment (Include rationale for comment)**:  In previous releases the NIST 800-63 version combined the scores of both the credentials and the surrounding processes into a single value.  
 
Under the third release it is clear that a single value now is broken into individual attributes.  This change expands the scope of evaluation process to accommodate for each attribute instead of a single score.  Additionally, new internal processes and technical controls will need to be developed to define internal acceptance criteria.  It is recommended that the LoA score consolidate the three assurance score to a single value as previously defined in the 800-63-2 guideline. 

All processes and authenticator evaluators were weighed evenly to arrive at a single score.  This score was clearly defined and left little room for subjectivity and personal interpretation.  The new model introduces segregation of the controls and could call into question the value of one assurance level over another.  

**Suggested Change**: It is recommended that the LoA score consolidate the three assurance score to a single value as previously defined in the 800-63-2 guideline. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We remain committed to this separation, and the benefits it brings to RPs and providers in the market.
