### ISSUE TITLE
There isn't any Identity Proofing or vetting requirements for this control. Therefore, the value of this assurance level when establishing identity is minimal. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1267]
**Organization Name (N/A, if individual)**: Boeing

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: IAL 1  -  No Identity Proofing , 
 
**Comment (Include rationale for comment)**:  There isn't any Identity Proofing or vetting requirements for this control.  Therefore, the value of this assurance level when establishing identity is minimal.  
 

**Suggested Change**: It is recommended that if no effort to establish a baseline identity is performed then no score should be assigned.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #1126.  That said, we will not likely introduce an IAL0 and certainly won't add proofing requirements to IAL1.
