### ISSUE TITLE
Recommend breaking out the Identity Proofing qualifying criteria into a general and intermediate level proofing qualifing values. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1268]
**Organization Name (N/A, if individual)**: Boeing

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: IAL2 -  In Person or Remote Proofing, 
 
**Comment (Include rationale for comment)**:  Recommend breaking out the Identity Proofing qualifying criteria into a general and intermediate level proofing qualifing values.   
 
This value accepts a very wide range of identity proofing techniques with the intent of increasing adoption of the guideline.  The lack of tangible requirements for collecting information that provides a reasonable level of identity assurance can offer incentives to perform the minimum proofing required for this level. 

Identity and Authentication are used when considering access to varying levels of data sensitivity.  Given the scope of the assurance level this value may not be a practical guideline when stronger Identity validation is required.

**Suggested Change**: Recommend breaking out the Identity Proofing qualifying criteria into a general and intermediate level proofing qualifing values.   
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
The intent of this document is to not be prescriptive and allow the market to innovate remote proofing solutions.  Given the strength requirements of evidence, validation, and verification, we believe the requirements do not create a race to the bottom condition that lessens the assurance requirements of IAL2.
