### ISSUE TITLE
The requirements to be considered for IAL 3 are too restrictive for domestic users who are remote and international users. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1269]
**Organization Name (N/A, if individual)**: Boeing

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: IAL 3 - In-Person Only Vetting, 
 
**Comment (Include rationale for comment)**:  The requirements to be considered for IAL 3 are too restrictive for domestic users who are remote and international users. 
 
Requiring mandatory in-person vetting and biometric sample collection not only places increased burden on the proofing entity it also raises the qualifications to a level where this identity verification may be inpractical. Requiring mandatory in-person vetting and biometric sample collection not only places increased burden on the proofing entity it also raises the qualifications to a level where this identity verification may be unpractical.  

**Suggested Change**: Recommend introducing an intermediate identity proofing assurance level that allows for virtual in-person (webcam or other) vetting that confirms the identity within existing proposed standards. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
IAL2 allows for many remote options for identity proofing.  IAL3 allows for in-person and stricter remote proofing.  Given the risk associated with applications that assess at IAL3, we believe the requirements mitigate the threat of proofing errors.
