### ISSUE TITLE
Overlap of credential types 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1270]
**Organization Name (N/A, if individual)**: Boeing

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.3, 
 
**Comment (Include rationale for comment)**:  Overlap of credential types 
 
The overlap of credential types between AAL1 and AAL2 draws cause for initial confusion when interpreting the guideline during credential evaluation.  The defining controls within the 80--63-3 document itself creates questions when differentiating between the levels.  Other than reauthentication requirements it is difficult to distinguish a significant difference between the authenticator values until the auditor looks to the other security control documents referenced within the controls

Draws cause for initial confusion when interpreting qualifying assurnace level guidelines during credential evaluation

**Suggested Change**: Consider altering the presentation format to distinguish how a credential could be considered one assurnace level over another as the table in 4.3 lacks in presenting that differentiation.  
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
AAL is determined by the risk associated with the application, not by the authenticator. The overlap between authenticator types results from the fact that a higher AAL authenticator may be used at a lower AAL. For example, a multi-factor cryptographic device having verifier impersonation resistance can be used at AAL3, but can also be used to authenticate to an application at AAL1.
