### ISSUE TITLE
Consistent Definitions

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#1273]
### All Fields Are Required

**Organization Name (N/A, if individual):**
DoD-CIO-ID2

**Organization Type (see below for codes)**:
1

**Document (63-3, 63A, 63B, or 63C)**:
All - 63-3, 63A, 63B, and 63C

**Reference (Include section and paragraph number)**:
 All

**Comment (Include rationale for comment)**:
 Definitions of terms and abbreviations are scattered across the four 800-63-3 documents.

**Suggested Change**:
 Include definitions and abbreviations in one document and reference from the others instead of repeating the same material in every document.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #898 and PR #688
