### ISSUE TITLE
Why not OTP?

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#1276]
### All Fields Are Required

**Organization Name (N/A, if individual):**
DoD-CIO-ID2

**Organization Type (see below for codes)**:
1

**Document (63-3, 63A, 63B, or 63C)**:
63B

**Reference (Include section and paragraph number)**:
 4.3.1

**Comment (Include rationale for comment)**:
 In 4.3.1, why not OTP in addition to single factor crypto? An OTP from a multi-factor OTP device in addition to a single factor crypto device seems like a clear upgrade over single factor crypto device plus password.

**Suggested Change**:

 Add "Single factor Cryptographic Device used in conjunction with a OTP from a single or multi-factor OTP device" to the list of permitted authenticator types for AAL-3.  
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
If the OTP and single-factor crypto device authentication occurs in the same session, this would meet AAL3 if the other requirements (verifier impersonation resistance in particular) are net. We had considered including authenticator combinations like this in the document but had considered it unlikely that subscribers would use two physical authenticators to separately meet the multi-factor and verifier impersonation resistance requirements.
