### ISSUE TITLE
Theft during enrollment of cryptographic authenticators

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#1278]
### All Fields Are Required

**Organization Name (N/A, if individual):**
DoD-CIO-ID2

**Organization Type (see below for codes)**:
1

**Document (63-3, 63A, 63B, or 63C)**:
63B

**Reference (Include section and paragraph number)**:
 Sections 5,9

**Comment (Include rationale for comment)**:
 Each sub-section in section 5 that addresses cryptographic authenticators should address theft during enrollment (e.g., man-in-the-middle attack on the protocol used to provision the keys). At present, a software key loaded onto a smart card may count as a multi-factor cryptographic device, when in reality it's more like single-factor cryptographic software. Requirements on key provisioning protocols should be addressed (in addition to requirements on key storage end point). Likewise, section 9 should include attacks on key provisioning protocols.

**Suggested Change**:

 The sub-sections in section 5 that addresses cryptographic authenticators should address theft during enrollment and requirements on key provisioning protocols.   
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Adding a new subsection of 5.2 that addresses key provisioning for all authenticator types.

**Comment by jimfenton** [comment]
New text is instead being added to Section 6.1, Authenticator Binding.
