### ISSUE TITLE
AAL-3 physical protection requirements

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#1279]
### All Fields Are Required

**Organization Name (N/A, if individual):**
DoD-CIO-ID2

**Organization Type (see below for codes)**:
1

**Document (63-3, 63A, 63B, or 63C)**:
63B

**Reference (Include section and paragraph number)**:
 Section 4.5, Table 4-3

**Comment (Include rationale for comment)**:
 Table 4-3 requires FIPS 140-2 Level 3 physical security for all AAL-3 authenticators. This does not seem to fit with the list of acceptable AAL-3 authenticators in 63B, section 4.3.1 (i.e. a 'memorized secret' is an authenticator that does not use FIPS 140-2 Level 3 physical security).  

**Suggested Change**:
 Suggest adding "Single factor Cryptographic Device used in conjunction with a OTP from a single or multi-factor OTP device" as a permitted authenticator (as noted in comment on 63B, 4.3.1 above) and adding level 3 physical security requirement for verifiers of this variety.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Table 4-3 is a non-normative summary of the requirements. It isn't possible to fit all of the detail into the table and maintain its usefulness.

Section 4.3.1 contains the detailed requirements and correctly specifies that only cryptographic device authenticators are subject to the FIPS 140 requirements.
