### ISSUE TITLE
Definition of "Address of Record"

### ISSUE THREAD

**Issue by tarbrix** [usnistgov/800-63-3#128]
2:

Technology Provider:

63-3:

Section 3, Page 21, Address of Record :

We have a couple of issues with this definition.  First, in 63-3A: Sections 4.5.5 and 4.6.5 imply that a phone number or email address may be "an address of record" which conflicts with the definition provided in Section 3 of 63-3.  Secondly, within industry, saying "street address" implies just that - a street name and number and does not necessarily include a full physical address of a property: city, state, zip, country.   Finally, when the "address of record" is used to notify or verify something during the enrollment processes (as in 4.5.5 and 4.5.6) many millions of American's cannot receive mail at their physical place of residence.  

Suggested Change:  Our recommendation depends on NIST's intention.  If phone number, email address, etc. are to be allowed for use as an "address of record" then the definition of address of record needs to change.  If they are not, then, at a minimum, sections 4.5.5 and 4.6.5 in 63-3A need to be updated accordingly.  If left to us, we would recommend:
1.  In definition of Address of Record, change the words "residential street address" to "complete physical address of the applicant's place of residence".
2.  Add a definition for "Uniquely Assigned Identifier"  which would include things such as: SSN, Email addresses, Phone Numbers, Member Numbers, and other codes that are unique across the population of subscribers. 
3.  In 63-3A, 4.5.5/4.6.5 change to allow "sending to the Address of Record or other uniquely assigned 
   identifier such as email address or phone number.

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
@burr44 it is my understanding that earlier versions of 800-63 expanded the definition of "Address of Record" beyond just physical mailing address, but it doesn't look like that change made it into the definitions section.  True?  I just want to check historical context before I accept this comment and make the change.

**Comment by paul-grassi** [comment]
Thanks for finding this.  Address of record includes logical addresses (cell/email) so we updated definition.
