### ISSUE TITLE
Time-based One-Time Passwords

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#1280]
### All Fields Are Required

**Organization Name (N/A, if individual):**
DoD-CIO-ID2

**Organization Type (see below for codes)**:
 1

**Document (63-3, 63A, 63B, or 63C)**:
63B

**Reference (Include section and paragraph number)**:
 5.1.5.2, 10.2.5

**Comment (Include rationale for comment)**:
 In the sentence that begins with "Time-based OTPs SHALL have a lifetime of less than 2 minutes," is this two minutes from time of generation or two minutes total?  Typically, a window is +/- some value to account for clock drift.  Is this +/- 60 or +/- 120? Two minutes seems likely to draw complaints from users. 

Section 10.2.5 suggests +/- 60, which is really a very narrow window if these guidelines are to cover all use of TOTP values for authentication.

**Suggested Change**:
 Clarify lifetime of Time-based OTPs.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by mingpeiwk** [comment]
Agreed on the need of clarification.

If the clock of the OTP generating device is perfect, then the forward 2 mins to limit when the OTP must be consumed by a verifier is reasonable. The main usage of OTP validity time was to handle clock drift. A software OTP generator in a mobile device tends to have a good clock accuracy with network sync assistance. 

A device, in particularly, hardware tokens can have an accrued clock drift of a few minutes in some extreme temperature condition and later life cycle. So the precise detection of clock drift and therefore the OTP valid time window needs to be flexible, and left for the verifier to define according to its policy. 

I tend to think that this shouldn't be defined in this specification for those use cases in combination of clock drift handling.

Suggest to consider change of the language to reflect that the OTP valid time to mean from the OTP generating time with synchronized clock between the generator and the verifier.
