### ISSUE TITLE
Rate Limiting

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#1281]
### All Fields Are Required
**Organization Name (N/A, if individual):**
DoD-CIO-ID2

**Organization Type (see below for codes)**:
 1

**Document (63-3, 63A, 63B, or 63C)**:
63B

**Reference (Include section and paragraph number)**:
 5.2.2

**Comment (Include rationale for comment)**:
 Section 5.2.2, seems overly prescriptive w.r.t. requiring rate limiting. For example, suppose the result of a successful brute force attack was obtaining an encrypted payload. Why should rate limiting be required? It is not clear if a countermeasure like encryption would satisfy the 'unless otherwise specified in the description of a given authenticator' clause. In environments where interfaces are unauthenticated, rate limiting may provide means of mounting a DOS attack. Environments that only release encrypted data and do not rate limit would not be subject to a DOS attack, and would not be at any risk of data loss.

 Also regarding rate limiting, if a failed mutual authentication TLS attempt is attempted (using a revoked certificate or certificate with a bad signature), the attempt may be rejected before the RP application could record the failed attempt or impose rate limiting.

**Suggested Change**:

 Clarify "rate-limiting" requirements and scope in line with the comment.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The rate limiting requirements of section 5.2.2 are imposed only for certain authenticator types for which the authenticator output has lower entropy and therefore more vulnerability to brute-force attacks.

The nature of the information (i.e., whether it is encrypted) that might be released is not considered in the authentication requirements for a given AAL. Instead, the selection of AAL depends on the risk of a false authentication, and a lower AAL might be selected where the risk of disclosure is negligible.
