### ISSUE TITLE
Rate Limiting #2

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#1282]
### All Fields Are Required
**Organization Name (N/A, if individual):**
DoD-CIO-ID2

**Organization Type (see below for codes)**:
 1

**Document (63-3, 63A, 63B, or 63C)**:
63B

**Reference (Include section and paragraph number)**:
 6.1, Paragraph 2

**Comment (Include rationale for comment)**:
 In 6.1 paragraph two, what role would a CSP play in retaining rate limiting information? 

**Suggested Change**:
 Suggest this SHALL should be a SHOULD or MAY.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The rate limiting requirements (Section 5.2.2) require that the CSP or verifier keep some state information. How many recent unsuccessful authentications have there been? The CSP and verifier have a close relationship (they are often the same entity) so it is possible for that state information to be kept in either place.
