### ISSUE TITLE
Derived Credentials

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#1283]
### All Fields Are Required
**Organization Name (N/A, if individual):**
DoD-CIO-ID2

**Organization Type (see below for codes)**:
 1

**Document (63-3, 63A, 63B, or 63C)**:
63B

**Reference (Include section and paragraph number)**:
6.1.2.1
 
**Comment (Include rationale for comment)**:
Section 6.1.2.1 seems to touch on some derived credential issues. 

**Suggested Change**:

Clarify what relationship, if any, this section has with derived credentials.  Reference SP 800-157 as necessary.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE via changes to Ch6. See #597
