### ISSUE TITLE
Path Validation

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#1284]
### All Fields Are Required
**Organization Name (N/A, if individual):**
DoD-CIO-ID2

**Organization Type (see below for codes)**:
 1

**Document (63-3, 63A, 63B, or 63C)**:
63B

**Reference (Include section and paragraph number)**:
 5.2.5

**Comment (Include rationale for comment)**:
 None of the verifiers that use asymmetric keys address certification path validation, and generally intimate that the verifier "has" a key for each authenticator. The key may arrive as part of a protocol that exercises the authenticator and requires trust establishment. 

**Suggested Change**:

Clarify and address the role certificate path validation in the context of protecting verifiers that use asymmetric keys.  
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
We will address this in the relevant definitions.
