### ISSUE TITLE
Biometrics

### ISSUE THREAD

**Issue by DoD-CIO-ID** [usnistgov/800-63-3#1286]
### All Fields Are Required
**DoD-CIO-ID**

**Organization Type (see below for codes)**:
1

**Document (63-3, 63A, 63B, or 63C)**:
63A 

**Reference (Include section and paragraph number)**:
6.3

**Comment (Include rationale for comment)**:
It's unclear what additional security an additional biometric would add for a derived credential, particularly if it's being issued remotely.  

**Suggested Change**:
If biometrics are a requirement, mitigations for biometric replay resistance should also be required.  

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #628

**Comment by DoD-CIO-ID** [comment]
**Clarification of Original Comment:**
Per comment #1287, "Remote Issuance to Mobile Credentials," we request that NIST re-examine the biometric requirement more closely.  If NIST does decide to keep the biometric requirement, we request that NIST include mitigations for biometric replay resistance as part of the biometric requirement.  Our reasoning is that if biometrics are going to be required for remote issuance of derived credentials, they should at least be combined with mitigations of known biometric vulnerabilities.  That way, the biometric will genuinely add  additional assurance to the credential-proofing process.
