### ISSUE TITLE
Remote Issuance to Mobile Credentials

### ISSUE THREAD

**Issue by DoD-CIO-ID** [usnistgov/800-63-3#1287]
### All Fields Are Required
**Organization Name (N/A, if individual):**
DoD-CIO-ID

**Organization Type (see below for codes)**:
1

**Document (63-3, 63A, 63B, or 63C)**:
63A

**Reference (Include section and paragraph number)**:
5.3.3.2

**Comment (Include rationale for comment)**:
These remote issuance requirements for IAL-3 appear to be onerous.  DoD will likely need a secure process for remotely issuing derived IAL-3 credentials to mobile devices.

**Suggested Change**:
Develop secure, but feasible, requirements for remotely issuing derived IAL-3 credentials to mobile devices.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by DoD-CIO-ID** [comment]
**Correction and Elaboration on original comment**: 
The referenced section should be 6.3 of 63A. Requirement #4 of section 6.3 apparently requires the person requesting the derived credential to submit a biometric to the CSP during the issuance process, in order to prove possession of an authenticator tied to an IAL3 identity.  We're concerned that this requirement may be too onerous for some users in a tactical environment  At the same time, we don't want to water down IAL-3 requirements for remotely-issued derived credentials.  

We were hoping NIST could address this tension by either: a) recommending ways for remote users in tactical environments to obtain and submit biometrics to the CSP, or b) allowing the remote users  to utilize a different, but equally secure, method of proving possession of the primary IAL-3 authenticator.

**Comment by paul-grassi** [comment]
OBE by change to Ch6. See #597
