### ISSUE TITLE
Requiring assertion encryption to achieve FAL2 is too restrictive

### ISSUE THREAD

**Issue by mingpeiwk** [usnistgov/800-63-3#1288]
### All Fields Are Required
**Organization Name (N/A, if individual): Symantec

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 63C 

**Reference (Include section and paragraph number)**: Section 7
 
**Comment (Include rationale for comment)**:

>> 2	Bearer assertion, signed by IdP and encrypted to RP.
>> FAL2 additionally requires that the OpenID Connect ID Token or SAML Assertion be encrypted to a public key representing the RP in question

To achieve the mostly often used LOA2 in practice, FAL2 is required by the table. To achieve FAL2, the SAML assertion must be encrypted. This isn't necessary when an assertion doesn't contain PII or additional attributes. An authentication claim and attribute claim don't need to be encrypted. Encryption creates additional performance overhead for most common authentication events.
 
**Suggested Change**:

Relax the encryption requirements from anytime to be conditional basing on whether the content itself needs to be encrypted.

For example:
 
"FAL2 additionally requires that the OpenID Connect ID Token or SAML Assertion be encrypted to a public key representing the RP in question when the assertion contains privacy data such as PII and additional attributes."

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by dig-comments** [comment]
I lean towards a decline, especially since LOA2 is going away, but we can discuss.

**Comment by jricher** [comment]
The encryption provides not only protection of the elements in the assertion but also very strict audience restriction, as only targeted RPs should be able to open this. I agree that the definition of FAL2 should not be changed.

That said, the table might have gotten out of sync from the time where we had 4 FALs, and we should make sure this is the value that we mean to have in any mapping.

**Comment by jimfenton** [comment]
The mapping to LOA2 is going away with the changes to SP 800-63-3, so this comment is no longer germane.
