### ISSUE TITLE
"Approved cryptography" is vague without some reference or definition

### ISSUE THREAD

**Issue by mingpeiwk** [usnistgov/800-63-3#1289]
### All Fields Are Required
**Organization Name (N/A, if individual): Symantec

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: General

**Reference (Include section and paragraph number)**: 63C 5.2.2, 5.2.3 etc.
 
**Comment (Include rationale for comment)**:
 
>> Approved cryptography SHALL be used

There is nowhere "approved cryptograph" is defined or given a reference. It intends to mean most probably NIST approved / FIPS compliant algorithms. The vagueness comes as whether it means algorithms that are "approved" by the RP who is going to decrypt, or IdP, or actually some standards by FIPS, or Europe standards bodies, or per country based laws etc.

**Suggested Change**:
 
Add a definition in the terminology section (e.g. Section 3 in 63C) to clarify what this means.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The definition is under "Approved" but should be under "Approved Cryptography"
