### ISSUE TITLE
Provide evidence from the scientific literature.

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1290]
### All Fields Are Required
**Organization Name (N/A, if individual):** Carnegie Mellon University/University of Maryland/University of Chicago

**Organization Type (see below for codes)**: 3
 
**Document (63-3, 63A, 63B, or 63C)**:

**Reference (Include section and paragraph number)**:
 
**Comment (Include rationale for comment)**:

This response comes from a group of faculty from Carnegie Mellon University, the University of Maryland, and the University of Chicago. With our students and colleagues, we have been conducting research since 2010 on how to help users create more secure and usable passwords. In that time, we have published over a dozen papers [1] on password security, many at the top scientific conferences on computer security or computer-human interaction; several have won awards or other recognitions. 

In general we strongly support many of the changes to NIST guidance espoused by DRAFT NIST Special Publication 800-63B [2]. In particular, we believe that it is important to relax previous guidelines that stress password complexity and password expiration [3], as evidence suggests that these are neither necessary nor sufficient conditions to create strong passwords, and may even have negative effects on both the security and usability of passwords.

We believe, however, that the guidance could still be improved in a number of ways detailed below.

Provide evidence from the scientific literature. As the ideal password policy for a particular system may be dependent on details of the system and on the context in which it is used, it is useful for policy makers to understand the tradeoffs associated with various password policy choices. Many password policies in use today have been developed without empirical evidence as to their impact on either security or usability. By adding citations to the relevant literature throughout this guidance or as part of an appendix, NIST could help promote more informed password policy development. 
 
1.
http://cups.cs.cmu.edu/passwords

2.
https://pages.nist.gov/800-63-3/sp800-63b.html

3.
William E. Burr, Donna F. Dodson, and W. Timothy Polk. 2006. NIST Special Publication 800-63-2 Electronic Authentication Guideline. http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63-2.pdf

**Suggested Change**:
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by dig-comments** [comment]
1.
http://cups.cs.cmu.edu/passwords

2.
https://pages.nist.gov/800-63-3/sp800-63b.html

3.
William E. Burr, Donna F. Dodson, and W. Timothy Polk. 2006. NIST Special Publication 800-63-2 Electronic Authentication Guideline. http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63-2.pdf

**Comment by jimfenton** [comment]
We will provide additional citations to literature, particularly in Appendix A where the detailed discussion is located.
