### ISSUE TITLE
Some complexity requirements may be appropriate.

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1291]
### All Fields Are Required
**Organization Name (N/A, if individual):** CMU / UMD / UChicago

**Organization Type (see below for codes)**: 3
 
**Document (63-3, 63A, 63B, or 63C)**:

**Reference (Include section and paragraph number)**:
 
**Comment (Include rationale for comment)**:

Some complexity requirements may be appropriate. While we agree that previous guidelines [3] placed too much evidence on password complexity, the draft guidance goes too far in recommending against the use of any password complexity requirements (Section 5.1.1.2: “Verifiers SHOULD NOT impose other composition rules (e.g., mixtures of different character types) on memorized secrets.”), relying only on length and blacklists. Appendix A concludes:

Length and complexity requirements beyond those recommended here significantly increase the difficulty of memorized secrets and increase user frustration. As a result, users often work around these restrictions in a way that is counterproductive. Furthermore, other mitigations such as blacklists, secure hashed storage, and rate throttling are more effective at preventing modern brute-force attacks. Therefore, no additional complexity requirements are imposed.

Research studies have found that password complexity requirements can indeed increase user frustration, but the impact on security varies. Some password policies with complexity requirements are particularly frustrating to users, and may not offer security benefits over simpler policies. For example, policies that require passwords that are at least 8-characters long, use all four character classes, and pass a dictionary check are by a number of metrics both less usable and less secure than policies that require passwords that are at least 16 characters long with no additional requirements [4]. However, some complex requirements that frustrate users appear to provide substantial security benefits. The requirement that non-lowercase characters be placed at the beginning or end of a password makes passwords significantly harder to guess than just requiring that multiple character classes be used anywhere in the password, but at the expense to usability [5]. 

Furthermore, requiring longer passwords can reduce guessability overall, but even users required to create 12- or 16-character passwords create some passwords that are very easy to guess. By pairing length with modest complexity requirements, we can decrease the use of weak passwords with minimal usability impact. For example, we have found that policies that require passwords to be at least 12 characters long, not be on a blacklist, and use 2 or 3 character classes strike a better balance between security and usability than policies that emphasize just length or just complexity [5].

Our research has also examined user behavior after users are told they cannot use a password because it appears on a blacklist. In a recent study we examined 2,280 passwords created by participants who were prohibited from using passwords appearing on a blacklist.  We found that participants who initially tried to use a blacklisted password ultimately created passwords with fewer characters, capital letters, digits, and symbols than those who did not attempt to create a password on our blacklist. Some participants created completely new passwords when informed that the password they had just created was on a blacklist. However, many participants simply added characters to the blacklisted password, often at the end. Those who added characters to a blacklisted password created passwords that were much easier to guess than those who created new passwords. On the other hand, users who saw a password meter that provided text feedback with suggestions for improving their password were more likely to ultimately create a strong password with a mix of character classes spread throughout the password [6]. This study suggests that blacklists alone may not eliminate weak passwords. Complexity requirements and actionable feedback [7] are both ways of reducing guessability.

3.
William E. Burr, Donna F. Dodson, and W. Timothy Polk. 2006. NIST Special Publication 800-63-2 Electronic Authentication Guideline. http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63-2.pdf

4.
Saranga Komanduri, Richard Shay, Patrick Gage Kelley, Michelle L. Mazurek, Lujo Bauer, Nicolas Christin, Lorrie Faith Cranor, and Serge Egelman. Of passwords and people: Measuring the effect of password-composition policies. In Proceedings of the ACM SIGCHI Conference on Human Factors in Computing Systems (CHI), 2011. https://www.ece.cmu.edu/~lbauer/papers/2011/chi2011-passwords.pdf 

5.
Richard Shay, Saranga Komanduri, Adam L. Durity, Phillip (Seyoung) Huh, Michelle L. Mazurek, Sean M. Segreti, Blase Ur, Lujo Bauer, Nicolas Christin, and Lorrie Faith Cranor. 2016. Designing Password Policies for Strength and Usability. ACM Trans. Inf. Syst. Secur. 18, 4, Article 13, May 2016. DOI=http://dx.doi.org/10.1145/2891411

6.
Hana Habib, Jessica Colnago, William Melicher, Blase Ur, Sean Segreti, Lujo Bauer, Nicolas Christin, and Lorrie Cranor. Password Creation in the Presence of Blacklists. In Proceedings of the Usable Security Mini Conference (USEC), 2017.  https://www.internetsociety.org/sites/default/files/usec2017_01_3_Habib_paper.pdf 

7.
Blase Ur, Felicia Alfieri, Maung Aung, Lujo Bauer, Nicolas Christin, Jessica Colnago, Lorrie Faith Cranor, Henry Dixon, Pardis Emami Naeini, Hana Habib, Noah Johnson, William Melicher. Design and Evaluation of a Data-Driven Password Meter. In Proceedings of the ACM SIGCHI Conference on Human Factors in Computing Systems (CHI), 2017.

 
**Suggested Change**:
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The position of this guideline is that for a variety of reasons single-factor authentication, and memorized secrets (passwords/PINs) in particular, should be used only for applications having modest risk. Accordingly, we have made a choice to emphasize usability rather than to take advantage of the security advantages that would result from a longer minimum password requirement, composition rules, and the like. Instead, we have emphasized verifier requirements, in particular (in the case of memorized secrets) measures to minimize the effectiveness of offline attacks.
