### ISSUE TITLE
Guidance is needed on how to choose and deploy blacklists. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1292]
### All Fields Are Required
**Organization Name (N/A, if individual):** CMU / UMD / UChicago

**Organization Type (see below for codes)**: 3
 
**Document (63-3, 63A, 63B, or 63C)**:

**Reference (Include section and paragraph number)**:
 
**Comment (Include rationale for comment)**:

Guidance is needed on how to choose and deploy blacklists. The draft guidance recommends the use of blacklists, but offers no guidance on how to choose an appropriate blacklist or how to operationalize the use of blacklists. The size of the blacklist has implications for both security and usability [8]. In addition, decisions about how to compile a blacklist, whether to apply a blacklist to the entire password or to password substrings, and whether to perform other manipulations (such as lowercasing or removing symbols) before performing a blacklist check, can also have an impact. Substring blacklists and blacklists customized for their context of use can increase security. Furthermore, as mentioned above, actionable feedback can guide users to choose stronger passwords rather than trivially modifying a blacklisted password [6]. We recommend that guidelines address blacklist selection and deployment issues. 
 
6.
Hana Habib, Jessica Colnago, William Melicher, Blase Ur, Sean Segreti, Lujo Bauer, Nicolas Christin, and Lorrie Cranor. Password Creation in the Presence of Blacklists. In Proceedings of the Usable Security Mini Conference (USEC), 2017.  https://www.internetsociety.org/sites/default/files/usec2017_01_3_Habib_paper.pdf 

8.
Patrick Gage Kelley, Saranga Komanduri, Michelle L. Mazurek, Rich Shay, Tim Vidas, Lujo Bauer, Nicolas Christin, Lorrie Faith Cranor, Julio Lopez. Guess again (and again and again): Measuring password strength by simulating password-cracking algorithms. In Proceedings of the IEEE Symposium on Security and Privacy, 2012. http://www.cylab.cmu.edu/research/techreports/2011/tr_cylab11008.html

**Suggested Change**:
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
An implementation guide is planned as a follow-on to the 800-63-3 suite, and this would be an appropriate topic for that implementation guide.
