### ISSUE TITLE
Recommend longer passwords.

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1293]
### All Fields Are Required
**Organization Name (N/A, if individual):** CMU / UMD / UChicago

**Organization Type (see below for codes)**: 3
 
**Document (63-3, 63A, 63B, or 63C)**:

**Reference (Include section and paragraph number)**:
 
**Comment (Include rationale for comment)**:

Recommend longer passwords. Sections 5.1.1.1 and A.4 of the draft guidance state that passwords may be as short as 8-characters if user selected or 6 digits if chosen randomly. With appropriate use of slow hash functions and rate-limiting login attempts, memorized secrets this short could be sufficiently resistant to adversarial guessing. However, in the general case -- which includes situations when security measures such as using slow hash functions or rate-limiting login attempts aren’t correctly implemented -- such a short, simple secret may not be sufficient to resist brute-force attacks. In particular, we believe 6 digits chosen randomly seems too short for many settings. In settings where particularly strong passwords are needed, requiring a minimum length of more than 8 chars can be an effective component of a password policy.  
 
**Suggested Change**:
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
See response to #1291.
