### ISSUE TITLE
Recommend real-time feedback on password strength.

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1295]
### All Fields Are Required
**Organization Name (N/A, if individual):** CMU / UMD / UChicago

**Organization Type (see below for codes)**: 3
 
**Document (63-3, 63A, 63B, or 63C)**:

**Reference (Include section and paragraph number)**:
 
**Comment (Include rationale for comment)**:

Although password-strength meters are commonly used [9], the draft standard never addresses employing meters or similar mechanisms to provide users feedback on the strength of their password. This omission is notable because password-strength meters can lead users to create substantially stronger passwords than they would in the absence of real-time feedback [7, 10, 11]. However, not all meters are created equal; in particular, meters that rely exclusively on basic heuristics (e.g., estimating password strength based only on the password’s length and whether digits are included) rate password strength inaccurately [9]. Meters that give detailed, personalized feedback can be particularly effective [7].

7.
Blase Ur, Felicia Alfieri, Maung Aung, Lujo Bauer, Nicolas Christin, Jessica Colnago, Lorrie Faith Cranor, Henry Dixon, Pardis Emami Naeini, Hana Habib, Noah Johnson, William Melicher. Design and Evaluation of a Data-Driven Password Meter. In Proceedings of the ACM SIGCHI Conference on Human Factors in Computing Systems (CHI), 2017.

9.
Xavier de Carné de Carnavalet and Mohammad Mannan. From Very Weak to Very Strong: Analyzing Password-Strength Meters. In Proceedings of the Network and Distributed System Security Symposium (NDSS), 2014. http://www.internetsociety.org/sites/default/files/06_3_1.pdf

10.
Serge Egelman, Andreas Sotirakopoulos, Ildar Muslukhov, Konstantin Beznosov, Cormac Herley. Does my password go up to eleven?: The impact of password meters on password selection. In Proceedings of the ACM SIGCHI Conference on Human Factors in Computing Systems (CHI), 2013. http://dl.acm.org/citation.cfm?id=2481329

11.
Blase Ur, Patrick Gage Kelley, Saranga Komanduri, Joel Lee, Michael Maass, Michelle L. Mazurek, Timothy Passaro, Richard Shay, Timothy Vidas, Lujo Bauer, Nicolas Christin, Lorrie Faith Cranor. How Does Your Password Measure Up? The Effect of Strength Meters on Password Creation. In Proceedings of the 21st USENIX Security Symposium, 2012. https://www.usenix.org/system/files/conference/usenixsecurity12/sec12-final209.pdf

 
**Suggested Change**:
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
We will suggest the application of password strength meters as an aids to users in creating better memorized secrets.
