### ISSUE TITLE
Memorized secrets should not be expired arbitrarily

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1296]
### All Fields Are Required
**Organization Name (N/A, if individual):** CMU / UMD / UChicago

**Organization Type (see below for codes)**: 3
 
**Document (63-3, 63A, 63B, or 63C)**:

**Reference (Include section and paragraph number)**:
 
**Comment (Include rationale for comment)**: Memorized secrets should not be expired arbitrarily. We agree with the requirement in Section 5.1.1.2 that “Verifiers SHOULD NOT require memorized secrets to be changed arbitrarily (e.g., periodically) and SHOULD only require a change if the subscriber requests a change or there is evidence of compromise of the authenticator.” However, this seems to contradict the guidance in Section 6.3 “CSPs MAY issue authenticators that expire.” This apparent contradiction should be resolved. Numerous experts have argued against mandatory expiration policies [12, 13], citing research that shows such policies may be counterproductive [14, 15].
 
12.
Lorrie Cranor. Time to rethink mandatory password changes. Federal Trade Commission Tech@FTC Blog. March 2016. https://www.ftc.gov/news-events/blogs/techftc/2016/03/time-rethink-mandatory-password-changes

13.
UK National Cyber Security Center. The problems with forcing regular password expiry. 2016. https://www.ncsc.gov.uk/articles/problems-forcing-regular-password-expiry

14.
Yinqian Zhang, Fabian Monrose, and Michael K Reiter. The security of modern password expiration: An algorithmic framework and empirical analysis. In Proceedings of the 17th ACM Conference on Computer and Communications Security (CCS), 2010. https://www.cs.unc.edu/~reiter/papers/2010/CCS.pdf

15.
Sonia Chiasson and P. C. Oorschot. 2015. Quantifying the security advantage of password expiration policies. Des. Codes Cryptography 77, 2-3 (December 2015), 401-408. http://people.scs.carleton.ca/~paulv/papers/expiration-authorcopy.pdf

Thank you for the opportunity to comment on this draft. We would be happy to discuss our comments with you further.

**Suggested Change**:
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The intent of the language in Section 6.3 is to allow the issuance of other authenticators (e.g., PIV cards) that have expiration dates. Similarly, certificates have expiration dates associated with them.

Of course, when we say that someone SHOULD NOT do something, that also means that they MAY do it. Hopefully the more specific context of the SHOULD NOT in 5.1.1.2 will take precedence; from comments and press we have received, it seems that it has.
