### ISSUE TITLE
Add definitions of hardware protection levels using the table formats from NIST FIPS 140-2

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1297]
### All Fields Are Required
**Organization Name (N/A, if individual):** Secure Technology Alliance

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 4 - Authentication Assurance Levels, Introduction to section 4 pg 15
 
**Comment (Include rationale for comment)**: Add definitions of hardware protection levels using the table formats from NIST FIPS 14-2  
 
Editorial, Ease of read

| FIPS 140-2 Level 1  | FIPS 140-2 Level 2  | FIPS 140-2 Level 3  | FIPS 140-2 Level 4  |
|---|---|---|---|
|   | a cryptographic module shall employ role-based authentication to control access to the module. | A cryptographic module shall employ identity-based authentication mechanisms to control access to the module | a cryptographic module shall employ identity-based authentication mechanisms to control access to the module  |
| Production-grade components | Evidence of tampering (e.g., cover, enclosure, or seal).  | Automatic zeroization when accessing the maintenance access interface. Tamper response and zeroization circuitry. Protected vents.  | EFP or EFT for temperature and voltage. |
| If applicable, production-grade enclosure or removable cover. | Opaque tamper-evident encapsulating material or enclosure with tamper-evident seals or pick-resistant locks for doors or removable covers. | Hard opaque potting material encapsulation of multiple chip circuitry embodiment or applicable Multiple-Chip Standalone Security Level 3 requirements. | Tamper detection envelope with tamper response and zeroization circuitry. |
| The cryptographic module shall consist of production-grade components that shall include standard passivation techniques (e.g., a conformal coating or a sealing coat applied over the module’s circuitry to protect against environmental or other physical damage). | The cryptographic module shall provide evidence of tampering (e.g., on the cover, enclosure, and seal) when physical access to the module is attempted. | If the cryptographic module contains any doors or removable covers or if a maintenance access interface is defined, then the module shall contain tamper response and zeroization circuitry. The tamper response and zeroization circuitry shall immediately zeroize all plaintext secret and private keys and CSPs when a door is opened, a cover is removed, or when the maintenance access interface is accessed. The tamper response and zeroization circuitry shall remain operational when plaintext secret and private cryptographic keys or CSPs are contained within the cryptographic module. | The cryptographic module components shall be covered by potting material or contained within an enclosure encapsulated by a tamper detection that shall detect tampering. |

**Suggested Change**:
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The hardware protection levels are defined in FIPS 140, and duplicating that information creates the opportunity for this document to be out of date if FIPS 140 is revised.
