### ISSUE TITLE
Secure Technology Alliance comment on 800-63-3

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1298]
### All Fields Are Required
**Organization Name (N/A, if individual):** Secure Technology Alliance

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 63-3

**Reference (Include section and paragraph number)**:
 
**Comment (Include rationale for comment)**: 

To Whom It May Concern,
 
The Secure Technology Alliance has provided various comments on SP800-63a via GitHub and has since drafted additional comments on SP800-63c and a comment that is more generally applicable across SP 800-63-3, A, B and C. Please see the attached comment spreadsheet for our comments on SP800-63c. 
 
Our comment on SP 800-63-3 is as follows:
 
The combined Identity and Access Control Councils noted four definitions that should be clarified, codified, and included within in 800-63-3 as a whole and ensure consistency within individual SP 800-63(A), (B) and (C) documents and sections as appropriate. These terms are:
•	Primary Credential or Principle Credential
•	Derived Credential
•	Primary Identity
•	Derived Identity
Currently there is a lack of clarity and consistency around the fact that in order to have a derived credential, we need to have a corresponding primary or principle credential. Definitions of both should be included (consistent with 800-157). Additionally, the relationship and binding between the primary and derived credentials and revocation should be addressed. 
 
Likewise, council discussions raised the need for clarity of a primary identity and derived identity for the purposes of uniformity and consistency with the community. 
 
 
If you have any questions, please feel free to contact me.

 
**Suggested Change**:
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We will be removing any notion of derived from this document.  Identity evidence can be physical (a driver license) or digital (proof of possession of another authenticator) to prove identity. So much like a license isn't called 'a primary credential', this update to blur physical and digital will by necessity require us to remove any notion of derived, primary, etc.
