### ISSUE TITLE
Warning causes confusion 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1299]
**Organization Name (N/A, if individual)**: Financial Services Roundtable/BITS

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.1.3.2, 2
 
**Comment (Include rationale for comment)**:  Warning causes confusion
 
Does not reference current leading practices

**Suggested Change**: Remove comment box
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We believe the vulnerabilities to SMS are sufficient enough to make reference to its potential removal from this guideline.
