### ISSUE TITLE
800-63-3 / sp800-63-3 / sec1_2_introduction.md 

### ISSUE THREAD

**Issue by rguduputi** [usnistgov/800-63-3#13]
Organization: 1

Conducting risk assessment : I think this guidance need to give more specific guidance on risk assessments methodologies.  The risk assessment method is giving to agencies  and suggesting to map the risks to specific assurance levels. If  risk assessment is not solid  as at this stage  assessors may not have good understand the limitations of technologies used during implementation. There is potentially mapping  the risk to assurance levels may not be accurate.

This does refers to NIST Special Publication (SP) 800-30 .
## 

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
Thanks for the issue.  An update to M-04-04 will cover this issue, but we will include more information, as well as keep this open for OMB to consider.
