### ISSUE TITLE
Add software authenticator credential "anti-cloning" in best practice recommendation

### ISSUE THREAD

**Issue by mingpeiwk** [usnistgov/800-63-3#1302]
### All Fields Are Required
**Organization Name (N/A, if individual): Symantec

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 5.2
 
**Comment (Include rationale for comment)**:
 
A cryptographic software OTP authenticator is more secure when the credential isn't cloned across multiple devices. This device binding property is important to give assurance of the user holding its device. As a general authenticator requirements, an authenticator should be made to mitigate cloning of its secret credential values to other devices. A verifier should detect whether a credential has been used in multiple devices (clone detection), and reduce the acceptance level.

**Suggested Change**:
 
Add in authenticator requirements that cryptographic credentials and OTP secret keys should be protected against cloning. A verifier MAY detect a credential being cloned into multiple devices, and apply policy for acceptance of such shared credential usage and mitigate stolen credential use.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
For completeness, a requirement not to clone private and symmetric keys used by software OTP and cryptographic authenticators will be added.

Detection of cloning is more problematic. The guideline does not assume the existence of any reliable means to identify a particular device other than possession and control of the authenticator secret.
