### ISSUE TITLE
63A Derived Identity - New Authenticator AAL

### ISSUE THREAD

**Issue by dkelts** [usnistgov/800-63-3#1303]
### All Fields Are Required
**Organization Name (N/A, if individual):**
MorphoTrust USA
**Organization Type (see below for codes)**:
 2
**Document (63-3, 63A, 63B, or 63C)**:
63A
**Reference (Include section and paragraph number)**:
 6.1
**Comment (Include rationale for comment)**:
 I believe the goal of the section is to issue a new "secondary" authenticator using the primary authenticator and the original record.  The last general requirement #7 is the goal, but the requirements in 6.3 somewhat contradict it.  A CSP (with the Identity Authority) should be able to meet enough requiremnts to issue a new secondary authenticator to a User whose AAL exceeds that of the primary authenticator.
**Suggested Change**:
 If the CSP/IA can authenticate the User during this Derived Identity session TO THE ORIGINAL RECORD at AAL3, they should be able to issue the new secondary authenticator to be used at that AAL3 henceforth.  This will allow the new secondary authenticator to exceed the AAL of the primary authenticator without having gathered new authentication factors (the security hole of stealing a password and issuing 2nd factor onto the credential, thus locking out the intended User).

There are ways to reword the requirements in 6.3 (and 6.2) to say that during the Derived Identity session, the process must authenticate the User to the original identity record at the intended AAL of the new secondary authenticator.  This will transfer the new AAL to the new authenticator.

I am very fond of 6.3 item 5, which is toward this particular goal.  I would expand upon that item to say that the CSP or IS should sign that biometric sample that passed comparison to the original identity record because it has future primary-biometric usage to get to higher AALs.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by dkelts** [comment]
### 2

**Comment by paul-grassi** [comment]
We agree.  Will be resolved via #628
