### ISSUE TITLE
Document states that for IAL2, each piece of evidence must be validated with a process that is able to achieve the same strength as the 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1304]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.4.1.3 Validation requirements, 
 
**Comment (Include rationale for comment)**:  Document states that for IAL2, each piece of evidence must be validated with a process that is able to achieve the same strength as the evidence presented
 
; For example, if two forms of STRONG identity evidence are presented, each evidence will be validated at a strength of STRONG. Needs additional clarification. Depending on the interpretation of this requirement, this may be result in significant impact to the Agency’s current processes.  Additional analysis is required to determine impact.
Once baselined, this guidance should be closely reviewed to ensure the third party data providers are meeting the new technical requirements.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
In absence of a specific recommended change we cannot offer a update to the document.  That said, -3 offers agencies options to vary from the stated requirements of -A, -B, and -C.  See <https://pages.nist.gov/800-63-3/sp800-63-3.html#sec5>
