### ISSUE TITLE
Please add examples of each IAL level. (An example helping to differentiate the difference between IAL2 and IAL3 would be beneficial.) 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1305]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 2.2 (Identity Assurance Levels),
IAL1 / IAL2 / IAL3

, 
 
**Comment (Include rationale for comment)**:  Please add examples of each IAL level. (An example helping to differentiate the difference between IAL2 and IAL3 would be beneficial.) 
 
Below are proposed examples: 1)      IAL1: Google 2)      IAL2: Passport 3)      IAL3: Government/corporate ID, PIV

Examples will assist the Agency in defining impact and identifying solutions capable of meeting requirements.

Examples of processes, strategies, or artifacts that currently meet a given requirement are lacking. Examples:
1)      The IAL associated with a passport is not mentioned (i.e., IAL2 or IAL3?).
2)      A PIV card is only inferred to meet IAL3 requirements. (The PIV is only discussed under Derived Identity.)

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This will be provided in a forthcoming, non-normative companion document.
