### ISSUE TITLE
Under Weak, the source is cited as authoritative. Under Fair, Strong, and Superior, the source is cited as issuing. Is an issuing source always considered 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1307]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 5.2.2.1 (Methods to Perform Identity Evidence Validation)
Table 5-2, Weak
, 
 
**Comment (Include rationale for comment)**:  Under Weak, the source is cited as authoritative. Under Fair, Strong, and Superior, the source is cited as issuing. Is an issuing source always considered an authoritative source?
 
Enhanced detail will assist the Agency in defining impact and identifying solutions capable of meeting requirements.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Related to #582

**Comment by paul-grassi** [comment]
Fixed.  Auth Source is defined now and can include an issuing source.
