### ISSUE TITLE
Can a reference be added that can point to a source for potential KBV questions? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1308]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 5.3.2 (Knowledge Based Verification Requirements),
Bullet 6,
Sub-Bullet 1
, 
 
**Comment (Include rationale for comment)**:  Can a reference be added that can point to a source for potential KBV questions? 
 
While the text gives a few such examples, a more definitive source would be a great help to a novice reader/implementation team. Enhanced detail will assist the Agency in defining impact and identifying solutions capable of meeting requirements.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We expect the private sector will innovate in this area, and agencies that have data sources that meet the necessary KBV requirements will have mission awareness of what the best questions are based on the data they have. Therefore, it is not in the governments best interest, nor is NIST in a position to know all of these datasets, for use to offer sample questions.  However, in a subsequent companion to this volume, we will consider ways to help.
