### ISSUE TITLE
Organizational policies may require enrollment code to have a length greater than six characters. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1309]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.6 (Enrollment Code),
Bullet 1
, 
 
**Comment (Include rationale for comment)**:  Organizational policies may require enrollment code to have a length greater than six characters.
 
It is highly recommended that the Enrollment code match password characteristic minimums as closely as possible (i.e., as defined by policy). Enrollment code characteristics may also be governed by NIST SP 800-53r4 control IA-5 (Authenticator Management) and IA-5(1) (Password-Based Authentication).
 1)      As applicable, enrollment code lengths need to follow the most restrictive characteristic policy applicable.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We state _minimally_ so agencies can choose to exceed the 6 character minimum.
