### ISSUE TITLE
Definition of a "Subscriber"

### ISSUE THREAD

**Issue by tarbrix** [usnistgov/800-63-3#131]
2:

Technology Provider:

63-3:

4.1, Page 40, first numbered list:
#2 says that a applicant becomes a subscriber upon successful proofing; however, 4.2 (page 42) says that the applicant becomes a subscriber once the proofing is completed AND a credential has been issued.   These need to be made consistent.

For what it's worth, within industry, we will start calling you a subscriber once you accept our privacy policy and agree to the terms and conditions of use, regardless of where you actually are in the enrollment process.

Suggested Change:
 Edit the numbered list on Page 40 as follows:
1. An individual (applicant) applies to a CSP through an enrollment process.
2. The CSP identity proofs that applicant. 
3. An authenticator and a corresponding credential are established between the CSP and the applicant.  The applicant is now referred to as a subscriber.
4. The CSP maintains the credential, its status, and the enrollment data collected for the lifetime 
   of the credential (at a minimum). The subscriber maintains his or
   her authenticator.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
I'm pretty sure we addressed this in subsequent revisions, therefore we will partially accept.  In this new model, where an individual can be proofed without receiving a credential, it is important to note that they are still a valid subscriber, regardless of whether a credential has been issued or not.
