### ISSUE TITLE
If remote proofing is allowed, will there be need for restrictions? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1310]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.4.1.5 (Presence Requirements),
Para 1

, 
 
**Comment (Include rationale for comment)**:  If remote proofing is allowed, will there be need for restrictions?
 
For example, would a recognized law enforcement agency need to take an applicant's fingerprints - or could a commercial entity provide this service (i.e., define the level of trust needed in the remote provider)?

Enhanced detail will assist the Agency in defining impact and identifying solutions capable of meeting requirements.
1)      Beneficiary-based systems are examples of systems where remote proofing could be an issue. For example, will a beneficiary have to apply via their local government facility?
2)      The restrictions may also impact who can and cannot apply for the Agency contracts.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
NIST does not expect the solutions that meet 800-63 requirements be delivered only by the federal government.  See FICAM Trust Framework Solutions for more detail on private sector offerings.
