### ISSUE TITLE
The identity proofing evidence verification that will be required to achieve IAL2 for remote registration will be more strenuous. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1311]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.4 (Identity Assurance Level 2), 
 
**Comment (Include rationale for comment)**:  The identity proofing evidence verification that will be required to achieve IAL2 for remote registration will be more strenuous. 
 
Please provide use case examples of how this will be accomplished.

Refer to Section 6.1.1. (Enrollment) of NIST SP 800-63-3B as an example.

The identity proofing evidence verification for many the Agency systems (e.g., the public under ACA, medical providers, Medicaid beneficiaries) that want to use remote registration will find the process more strenuous.
1)      At least one piece of evidence presented will need to be from an authoritative source that will need to be verified.
2)      Limitations have been placed on the number of 3rd party identifiers that may be used.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #643
