### ISSUE TITLE
Infrastructure threats are defined as outside the scope of this document. If possible, include a reference to where the infrastructure threat discussion can be found. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1313]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 7 (Threats and Security Considerations),
Para 1
, 
 
**Comment (Include rationale for comment)**:  Infrastructure threats are defined as outside the scope of this document. If possible, include a reference to where the infrastructure threat discussion can be found.
 
 For example, as appropriate, cite controls in NIST SP 800-53r4. Also cite NIST guidance on Insider Threat.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Related to #828
