### ISSUE TITLE
Does the requirement as written not increase the workload if an applicant is switching from one primary CSP to another CSP? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1314]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 6.1 (General Requirements),
Req. 2

, 
 
**Comment (Include rationale for comment)**:  Does the requirement as written not increase the workload if an applicant is switching from one primary CSP to another CSP? 
 
For example, a contractor that goes from one company to another where a PIV style corporate ID is the primary CSP.
In cases like this, would it not make sense to transfer the authenticator and not revoked the authenticator resulting in the issuance of a new authenticator?
Requirement 6 in this section appears to contradict the need to terminate, disable, revoke, or expire the authenticator(s).

1)      If a user were to leave their provider (i.e., the user’s credential service provider) for another provider, the user’s credentials could not be transferred but must be revoked. The credentials would have to be reissued.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Contractually this is possible, but this document focuses on the security and privacy, and possible options of swapping CSP's without any type of org-2-org agreement.
