### ISSUE TITLE
The requirement states that the email must be verified in records without providing guidance on what records are needed for the verification. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1315]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.4.1.6 (Address Confirmation),
Bullet 4,
Sub-Bullet 3
, 
 
**Comment (Include rationale for comment)**:  The requirement states that the email must be verified in records without providing guidance on what records are needed for the verification. 
 
Do the records need to be authoritative in nature? What type of protections are required? What happens if the record is in error? What requirements are associated with handling redress (NIST SP 800-53r4 control IP-3)?

Examples: People move. Some even live in vehicles such as RVs. What about the folks who have addresses that are General Delivery? These still exist (see http://pe.usps.gov/text/pub28/28c2_033.htm) - and provide minimal assurance the recipient of the code would always be the true applicant.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Related to #642
