### ISSUE TITLE
There are other retention schedules beyond NARA that may apply to the data. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1316]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.2 (General Requirements),
Req. 8.c

, 
 
**Comment (Include rationale for comment)**:  There are other retention schedules beyond NARA that may apply to the data. 
 
Examples include retentions periods that are specified by:
1)      Organizational policy
2)      Federal Rules of Evidence
3)      Legislation or other authoritative directive

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #1317
