### ISSUE TITLE
There are other retention schedules beyond NARA that may apply. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1317]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.1.5 (Records Retention),
Para 1
Section 4.2.5 (Records Retention),
Para 1
Section 4.3.5 (Records Retention),
Para 1
, 
 
**Comment (Include rationale for comment)**:  There are other retention schedules beyond NARA that may apply. 
 
Examples include retentions periods that are specified by:
4)      Organizational policy
5)      Federal Rules of Evidence
6)      Legislation or other authoritative directive

Discussion of retention needs to be consistent across all volumes of NIST SP 800-63-3.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Having dug around, the NARA reference is in A, while B states

> The CSP shall comply with their respective records retention policies in accordance with applicable laws and regulations.

So it is worth considering the alignment across volumes as B addresses their concern by A does not.

**Comment by jimfenton** [comment]
We should also cite NARA in B.

See also #1057

**Comment by paul-grassi** [comment]
Closed via #1057
