### ISSUE TITLE
If NIST is considering removing the public switched telephone network (PSTN) as a viable out-of-band channel for verification… 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1318]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 5.1.3.2 (Out-of-Band Verifiers), 
 
**Comment (Include rationale for comment)**:  If NIST is considering removing the public switched telephone network (PSTN) as a viable out-of-band channel for verification…
 
Please clarify and provide examples or strategies that can be used as an alternate.
The suggestion seems to be to use a “secure” application on a smart phone. Example concern: If an attacker has managed to place an IP network sniffer on a user’s smartphone, and both channels are using IP network, then they can watch and capture the user’s username and password, put them into their own separate session, then wait for the second factor in the network traffic, and use it before the user can to complete their separate session. The user will simply get an error, and just try again, not knowing that the credentials had been compromised.

If PSTN is used for current deployments and is “disallowed” in future releases of NIST SP 800-63, the Agency will be required to reengineer the PSTN-based solutions supporting an enourmous user base. Any solution proposed must be in-line with industry trends and able to scale to millions of users. It may be far more cost effective for the Agency to deploy under an alternate technology that will not be subject to future removal. However, this can only be done if the alternate technologies are specified.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is 63B

**Comment by paul-grassi** [comment]
There are many viable authenticators at IAL2, to include SMS if deployed using the risk mitigations we specified.  That said, in a forthcoming implementation guide we will offer specific strategies that would not be appropriate in this document. The goal of this document is to be stable while the implementation guide can change as technologies evolve.
