### ISSUE TITLE
Collection of personal data or making it available online is cited as requiring multi-factor authentication. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1319]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4 (Authenticator Assurance Levels),
Para Below Table 4-2

, 
 
**Comment (Include rationale for comment)**:  Collection of personal data or making it available online is cited as requiring multi-factor authentication.
 
1)      Need clarification on personal data – is it PII only?
Please include the applicable authoritative references that are driving this requirement. Clearly, the Privacy Act of 1974 would be one of the references.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is 63B

**Comment by jimfenton** [comment]
We will use _PII_ instead of _personal data_.
