### ISSUE TITLE
As stated, the requirements in this section are very difficult to verify. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1320]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 5.1.3.1 (Out-of-Band Authenticators),
Para 1
, 
 
**Comment (Include rationale for comment)**:  As stated, the requirements in this section are very difficult to verify.
 
This section should be elaborated to include one or more recommended out-of-band authenticator implementation(s).
Section should also discuss mitigating controls if the requirements could not be met and also point to the usability section (Section 10.2.3)

There is no assurance that out-of-band authenticator implementation(s) deployed by the Agency systems would meet the minimal requirements/functionality intended under NIST SP 800-63r3 when insufficient guidance is provided. Without proper guidance, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is 63B

**Comment by jimfenton** [comment]
This is an area that would be covered in a planned implementation guide following the publication of these guidelines. The current documents focus on requirements only.
