### ISSUE TITLE
Usability recommendations go against best practices for protecting authentication information and reducing the ability of an attacker to gain intelligence 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1322]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 10.1 (Usability Considerations Common to Authenticators),
Para 5,
Bullet 5,
Sub bullet 5
Section 10.2.1 (Memorized Secrets),
Para 1
Section 10.4 (Biometrics Usability Considerations), Typical Usage,
Bullet 5
, 
 
**Comment (Include rationale for comment)**:  Usability recommendations go against best practices for protecting authentication information and reducing the ability of an attacker to gain intelligence
 
Usability recommendations go against best practices for protecting authentication information and reducing the ability of an attacker to gain intelligence:
1)      Informing the user when the "throttle" (login-disabled) expires
2)      Copy and paste functionality for memorized secrets

All recommendations must be consistent with NIST guidance. Additionally, there may be agency policy that precludes displaying this type of intelligence.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by ychoong** [comment]
This bullet will not give attackers any intelligence. Having copy and paste feature is clarified in section 5.
