### ISSUE TITLE
Please include description/or reference on adaptive authentication techniques. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1323]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 5.2.2 (Rate Limiting (Throttling)),
Para 2,
Bullet 4
, 
 
**Comment (Include rationale for comment)**:  Please include description/or reference on adaptive authentication techniques.
 
There is no assurance that adaptive authentication techniques deployed by the Agency systems would meet the minimal requirements/functionality intended under NIST SP 800-63r3 when insufficient guidance is provided. Without proper guidance, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is 63B

**Comment by jimfenton** [comment]
SP 800-63B is a requirements document, and does not focus on candidate implementations. A follow-on deployment guide is planned, and this information would more appropriately be included there.
