### ISSUE TITLE
Please include use case examples in each section (e.g., manual and dynamic registration, federation authorities, proxied federations) 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1324]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.1.1 (Manual Registration)
Section 4.1.2 (Dynamic Registration)
Section 4.1.4 (Proxied Federation)
, 
 
**Comment (Include rationale for comment)**:  Please include use case examples in each section (e.g., manual and dynamic registration, federation authorities, proxied federations)
 
Please include use case examples in each section (e.g., manual and dynamic registration, federation authorities, proxied federations) providing guidance on how NIST recommends these federation model concepts can be implemented to maximize information security.

Also, ensure references are included to ensure implementations meet (or exceed) organizational policy.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is 63C

**Comment by jimfenton** [comment]
This might be suitable for a future implementation guide.
