### ISSUE TITLE
How realistic is it that a subscriber will know to ask for an additional authenticator up-grade? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1325]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 6.1.2.2 (Adding an Additional Factor to a One-factor Account),
Para 1
, 
 
**Comment (Include rationale for comment)**:  How realistic is it that a subscriber will know to ask for an additional authenticator up-grade? 
 
The subscriber will ask for access to some capability – which is driving the need for the upgrade. Adding additional authentication factors needs to be covered - in examples and/or use cases!

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is 63B

**Comment by jimfenton** [comment]
Subscribers will upgrade from single-factor to multi-factor authentication when they need to do something that requires multi-factor authentication, although it is hoped that they will be apprised of the need to do this during the identity proofing process.

Examples and use cases are more appropriately included in the implementation guide planned after these documents are published.
