### ISSUE TITLE
The requirement states the CSP SHALL honor this request (if possible). 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1326]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 7.2.1 (Reauthentication from a federation or assertion),
Para 1
, 
 
**Comment (Include rationale for comment)**:  The requirement states the CSP SHALL honor this request (if possible). 
 
However, no guidance is provided on dealing with situations where reauthentication through a federation protocol is not possible. Please include.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is 63B

**Comment by jimfenton** [comment]
Reauthentication through federation protocols is covered more completely in SP 800-63C Section 4.2.

If for some reason it is not possible to reauthenticate (through a federation protocol or otherwise), the subscriber SHALL be logged out of the application. Apparently that isn't clear enough.
