### ISSUE TITLE
Please include guidance on addressing situations where the subscriber may be transferring from one CSP (or RP) to another. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1327]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 7.1 (Session Bindings),
Para 2
, 
 
**Comment (Include rationale for comment)**:  Please include guidance on addressing situations where the subscriber may be transferring from one CSP (or RP) to another.
 
A situation where the subscriber credentials are revoked and the subscriber must reapply for new credentials may prove arduous and could result in service disruptions while the transfer is ongoing.

Failure to allow for a use case that addresses a transfer of a subscriber from one CSP to another may result in the destination CSP (the CSP to which the subscriber is transferring) repeating the identity proofing and authentication actions on the transferring subscriber. This repetition may result in increased costs to the Agency.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is 63B

**Comment by jimfenton** [comment]
The reference is to section 7.1 of -63B, but at least part of the issue has to do with transferring a proofed identity from one CSP to another, which would be covered in -63A.

**Comment by paul-grassi** [comment]
There is no allowance for transfer, just a derived credential, which would be user driven.

**Comment by jimfenton** [comment]
This is an instance of identity proofing, covered in 800-63A.
