### ISSUE TITLE
The notice should also provide guidance on redressing inaccurate information. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1328]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 8.2 (Notice and Consent),
Para 2

, 
 
**Comment (Include rationale for comment)**:  The notice should also provide guidance on redressing inaccurate information.
 
1)      Redress is only mentioned in the section on Privacy and not integrated not in the requirements associated with the capability.
2)      NIST must ensure processes associated with correcting identity-proofing information errors are protected with the same level of diligence used to protect identity proofing.
A reference to Section 8.4 would suffice. This is from IP-3 under NIST SP 800-53r4.

1)      With no guidance on addressing information redress, the Agency could implement an ineffective solution that could permit a nefarious attacker to alter identity-proofing evidence and gain unauthorized access to sensitive information.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Section 4.2 item (6) contains the redress requirement.

Further discussion account management and redress would be appropriate for the planned implementation guide.
