### ISSUE TITLE
The latest OMB Circular A-130 (July 2016) requires the privacy controls be addressed. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1329]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 9.2 (Privacy Controls),
Para 1

, 
 
**Comment (Include rationale for comment)**:  The latest OMB Circular A-130 (July 2016) requires the privacy controls be addressed.
 
 By stating Section 4.4 encourages CSP to employ appropriately tailored controls, there is an implication that the action is optional.

Since legislation, OMB Circular A-130 (July 2016), and other directives make implementation of privacy controls mandatory, the statement needs to be more forceful.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This is -63B.

The SHOULD at the beginning of -63B section 4.4 will be changed to a SHALL.
