### ISSUE TITLE
What happens if the primary CSP is using a different biometric than the secondary CSP? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1330]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 6.3 (AAL2 Requirements),
Req. 4
, 
 
**Comment (Include rationale for comment)**:  What happens if the primary CSP is using a different biometric than the secondary CSP?
 
In this case, even though the biometrics may be signed and trusted, the biometrics could be incompatible.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
To get a derived credential at the secondary CSP, the claimant needs to prove possession of the authenticator at the primary CSP.  If the secondary wants to use any type of biometric, same or different, they would enroll the new biometric after successful proof of possession. 

We will make sure the language reflects this.

**Comment by paul-grassi** [comment]
OBE by changes to Ch6.  See #597.  That said, we will include detailed language in the implementation guide.
