### ISSUE TITLE
Please give authoritative references that stipulate why the collection of PII must be minimized. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1331]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 9.3 (Use Limitations),
Para 1

, 
 
**Comment (Include rationale for comment)**:  Please give authoritative references that stipulate why the collection of PII must be minimized.
 
Examples include:
1)      OMB Directives
2)      NIST SP 800-53r4: DM-3 (Minimization of PII Used in Testing, Training, and Research)
3)      Legislation: 45 C.F.R. §164.512(i).
Please cite the appropriate controls from the UL family of controls from NIST SP 800-53r4.

There is no assurance that information collection strategies and techniques would consider legal obligations early in the development process (i.e., from the beginning) without appropriate reminders. Without proper guidance throughout development, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future to meet the privacy requirements.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
SP 800-53 is under revision, so citing it may be immediately obsolete.

This document is considered authoritative.
