### ISSUE TITLE
The requirement SHALL be verified by the RP implies a process is needed for verification. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1332]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 6.4 (Revocation and Termination),
Para 4

, 
 
**Comment (Include rationale for comment)**:  The requirement SHALL be verified by the RP implies a process is needed for verification.

 
Please include examples of or references to how this verification can be performed.

There is no assurance that verification processes, strategies, and techniques deployed by the Agency systems would meet the minimal requirements/functionality intended when NIST SP 800-63r3 provides insufficient guidance. Without proper guidance, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is 63B

**Comment by jimfenton** [comment]
Examples of how to do verification would belong in the implementation guides planned following publication of the SP 800-63-3 suite.
