### ISSUE TITLE
Where does the seven (7) day limit come from? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1333]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.4.1.6 (Address Confirmation),
Bullet 3,
Sub-Bullet 3
, 
 
**Comment (Include rationale for comment)**:  Where does the seven (7) day limit come from?
 
An authoritative reference is needed. Also, consider adding a reminder that organizational policy may define the limit to a value less than seven.

Is seven days needed if the code is an electronic code?

Enhanced detail will assist the Agency in defining impact, ensuring policies are compliant.
1)      Identification of the authoritative source will ensure compliance can be achieved.
2)      If the seven-day limit is not specifically mandated, the Agency may be able to choose a shorter duration that may better fit the Agency’s needed.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #1050
