### ISSUE TITLE
The requirement states the CSP must record the details of the primary authenticator without providing guidance on where the recording should be done. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1334]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 6.1 (General Requirements),
Req. 5
, 
 
**Comment (Include rationale for comment)**:  The requirement states the CSP must record the details of the primary authenticator without providing guidance on where the recording should be done.
 
Please address (guidance or references) where, how, minimal protections, and retention.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Some notion of where (someplace secure), why (root of trust) would be good.

**Comment by paul-grassi** [comment]
OBE by changes to Ch6.  See #597
