### ISSUE TITLE
The last paragraph should be the first. This is the “why” collection of the SSN is to be minimized. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1336]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 8.1.1 (Social Security Numbers),
Para 4 (Last)

, 
 
**Comment (Include rationale for comment)**:  The last paragraph should be the first. This is the “why” collection of the SSN is to be minimized.
 
The minimization is also related to applicable NIST SP 800-53r4 controls, such as DM-01 (Minimization of Personally Identifiable Information).

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Also need up update reference to M-07-16, which is obsolete.
