### ISSUE TITLE
The statement that session bindings SHOULD not be placed in insecure locations is based on an assumption that the reader will know what these insecure 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1337]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 6.4 (Revocation and Termination),
Para 3,
Bullet 5
, 
 
**Comment (Include rationale for comment)**:  The statement that session bindings SHOULD not be placed in insecure locations is based on an assumption that the reader will know what these insecure assumptions are.
 
Please include a reference or link to information identifying insecure location. (Examples: NIST National Vulnerability Database (NVD) or the Common Weakness Enumeration (CWE) program).

There is no assurance that session binding strategies and techniques deployed by the Agency systems would meet the minimal requirements/functionality intended when NIST SP 800-63r3 provides insufficient guidance. Without proper guidance, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is actually 63B

**Comment by jimfenton** [comment]
This is in Section 7.1.

**Comment by jimfenton** [comment]
Section 7.1 gives HTML local storage in browsers as one example (with reason). It isn't possible to enumerate all of the possibly insecure places that these bindings could be stored.
