### ISSUE TITLE
1)      Where applicable, an authoritative driver for a requirement (i.e., why is the requirement a requirement) should be added… 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1338]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: General Comment, 
 
**Comment (Include rationale for comment)**:  1)      Where applicable, an authoritative driver for a requirement (i.e., why is the requirement a requirement) should be added…
 
1)      Where applicable, an authoritative driver for a requirement (i.e., why is the requirement a requirement) should be added. This helps to ensure the reader is aware that there is only limited leeway with respect implementing the requirement.
2)      Please include Privacy Controls with the Information Security Controls wherever the controls are referenced.
3)      Include examples, descriptions and/or references for each of the requirements. Examples do not have to be specific technological solutions – they can be strategies, concepts and methodologies.

Clarification is needed:
1)      Inclusion of authoritative drivers will enable the Agency to make better prioritization decisions
2)      Impact from Privacy controls must be integrated as required under OMB Circular A-130 (2016). Privacy-related considerations for sensitive information also impact security controls.
3)      Inclusion of examples NIST recommends for meeting the requirement will better aid the Agency in determining if the approaches used by the Agency are considered secure.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
1) This is an SP - it is authoritative, not a roll-up of other documents
2) under consideration
3) examples are already provided where appropriate.

**Comment by paul-grassi** [comment]
This document is the authoritative source of requirements and does not need to be justified via a pointer to some other standard or NIST document.
