### ISSUE TITLE
1)      It is good that Privacy Considerations have been added to each volume. However… 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1339]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: General Comment, 
 
**Comment (Include rationale for comment)**:  1)      It is good that Privacy Considerations have been added to each volume. However…
 
1)      It is good that Privacy Considerations have been added to each volume. However, recommend adding authoritative references for Privacy Risk assessment etc.
2)      It is good to see that the model supports privacy enhancing approaches (e.g., pseudonymity and strong pseudonymous authentication).

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This document is considered authoritative.

Reference to the privacy risk NISTIR (8062) is being considered for inclusion in the updated 800-63-3 top-level document.
