### ISSUE TITLE
1)      The phrase real-life subject implies the applicant is a living individual. Is this the intent? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1340]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 2 (Introduction)
Section 2.1 (Expected Outcomes of Identity Proofing),
Bullet 4
Section 5.2 (Identity Evidence Validation)
Section 5.2.2 (Validating Identity Evidence)
, 
 
**Comment (Include rationale for comment)**:  1)      The phrase real-life subject implies the applicant is a living individual. Is this the intent?
 
1)      The phrase real-life subject implies the applicant is a living individual. Is this the intent?
Example: Mark Twain was a real-life subject. However, an applicant claiming to be Mark Twain today may be pseudonymous.
2)      The phrase real person implies the applicant is a living individual.

Consider adding living or other tag to ensure intent is fully described.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
yes, living if the subject is a human, but eventually these guides will be machine-to-machine as well, so we don't want to make this just about people.
