### ISSUE TITLE
Recommend adding expatiation as to what treated as self-asserted means. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1341]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 2.2 (Identity Assurance Levels),
IAL1
, 
 
**Comment (Include rationale for comment)**:  Recommend adding expatiation as to what treated as self-asserted means. 
 
Example: The user must be assumed to be anonymous and is therefore untrusted.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Appreciate the addition of context, but may not use the suggested edit as an IAL1 identity may be very trusted depending on the use case.

**Comment by paul-grassi** [comment]
Made a minor change to the document.  However, some more context.  While an RP can't trust the attributes, they do have to treat them as true/valid/correct/etc. To obtain a service that is IAL1, it may be in the users best interest to self-assert accurate information, even though the RP isn't validating it.  For example, if I want alerts of events happening in my neighborhood, I will self-assert my zip code.  I may assert my parents zip code.  Therefore, even self-asserted data needs to be protected as if it was validated and verified.
