### ISSUE TITLE
Please add that the requirement for explicit consent is driven by external privacy mandates, directives, and policy 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1342]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4 (Identity Assurance Level Requirements),
Last Para

, 
 
**Comment (Include rationale for comment)**:  Please add that the requirement for explicit consent is driven by external privacy mandates, directives, and policy
 
Please add that the requirement for explicit consent is driven by external privacy mandates, directives, and policy, such as OMB Memoranda M-17-06, M-10-22, and M-10-23, and OMB Circular A-130 (Revised 2016). (These all apply to Digital Services).

Inclusion of authoritative references provide the authoritative driver behind the stated requirements.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This is an authoritative source.
