### ISSUE TITLE
“Agencies shall consider privacy risks … and shall not select” 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1343]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.2, 
 
**Comment (Include rationale for comment)**:  “Agencies shall consider privacy risks … and shall not select”
 
This is not a testable requirement.  This requirement should be clarified with guidance on assessing privacy risks as well as guidance on determining IAL necessary for business needs

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
With the recent changes to 800-63-3, the tables in section 4.2 of -A will be removed.
