### ISSUE TITLE
Inclusion of example strategies and implementations within each identity assurance level (IAL1, IAL2, and IAL3) would be very helpful at understanding each level. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1344]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.3
Section 4.4
Section 4.5
, 
 
**Comment (Include rationale for comment)**:  Inclusion of example strategies and implementations within each identity assurance level (IAL1, IAL2, and IAL3) would be very helpful at understanding each level.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We are issuing an companion document to do just this.
