### ISSUE TITLE
Please give authoritative references that stipulate why the collection of PII must be minimized. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1345]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.4.1.1 (Resolution Requirements)
Section 4.5.1 (Resolution Requirements)
Section 8.1 (Collection and Data Minimization)

, 
 
**Comment (Include rationale for comment)**:  Please give authoritative references that stipulate why the collection of PII must be minimized. 

 
Examples include:
1)      OMB Directives
2)      NIST SP 800-53r4: DM-3 (Minimization of PII Used in Testing, Training, and Research)
3)      Legislation: 45 C.F.R. §164.512(i).

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Same as #1342
