### ISSUE TITLE
The following terms need to be described (defined) within this document (either in the current location or in Section 3): 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1346]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.4.1.2 (Evidence Requirements)
Section 4.5.2 (Evidence Requirements),
All Bullets

, 
 
**Comment (Include rationale for comment)**:  The following terms need to be described (defined) within this document (either in the current location or in Section 3):
 
1)      SUPERIOR Evidence
2)      STRONG Evidence
3)      ADEQUATE Evidence

If these terms are subjective, please included an intended description for each. The descriptive material could reference an applicable section below (e.g., Sections 5.2 and 5.3).

Examples/descriptions/references will assist the Agency in defining impact and identifying solutions capable of meeting requirements.
1)      Without a formal definition, the Agency could choose an identifier it believes to be considered as evidence at an appropriate level only to learn later the evidence does not meet the requirement.
2)      The effect of the REAL ID Act of 2005 provides possible examples where identity evidence that could be considered as one level (e.g., state issued licenses) may actually have a lower level.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
The terms are objective, based on the tables in section 5.
