### ISSUE TITLE
1)      What does valid piece of identity evidence mean? Government/federal issued? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1348]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.4.1.6 (Address Confirmation)
Section 4.4.1.6 (Address Confirmation)
Bullet 3,
Sub-Bullet 6
Section 4.5.6 (Address Confirmation)
Bullet 1
Section 5.2 (Identity Evidence Validation)
Section 5.2.1.1 (Scoring of Identity Evidence),
Table 5-1, Strong
, 
 
**Comment (Include rationale for comment)**:  1)      What does valid piece of identity evidence mean? Government/federal issued? 
 
1)      What does valid piece of identity evidence mean? Government/federal issued? Or must the level be equivalent to the definitions mandated under the REAL ID Act of 2005 (part of Public Law 109–13)?
2)      Should not the requirements defined within the REAL ID Act of 2005 be applied in as part of a strong identity evidence scoring process?
·        Not all state-issued identification cards (to include driver’s licenses) qualify under the REAL ID Act of 2005. As a result, using an identity card from a non-compliant state could be considered by the Federal Government to be non-authoritative.

Enhanced detail will assist the Agency in defining impact and identifying solutions capable of meeting requirements.
1)      The REAL ID Act of 2005 placed requirements on the manufacture of identification cards.
2)      If enforced under the Agency, identification cards used for beneficiaries in some states could become an issue. This could result in denial of service situations.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Section 4.4.1.6 (Address Confirmation)
Bullet 3,
Sub-Bullet 6
Section 4.5.6 (Address Confirmation)
Bullet 1

will be address by comment #642.

The rest of comment is not in scope of this document.  We define qualities of evidence, not what evidence qualifies.  It is up to the agency to determine the evidence it will accept and if it maps to the strong, superior...qualities.
