### ISSUE TITLE
1)      Applicability under FIPS 199 HIGH categorization is also appropriate for IAL2. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1349]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.4.1.8 (Security Controls)
Section 4.5.8 (Security Controls),
Para 1
, 
 
**Comment (Include rationale for comment)**:  1)      Applicability under FIPS 199 HIGH categorization is also appropriate for IAL2.
 
1)      Applicability under FIPS 199 HIGH categorization is also appropriate for IAL2.
2)      Can IAL3 be applied under a MODERATE system? If yes, provide guidance on tailoring the controls to address this difference.

Enhanced detail will assist the Agency in defining impact.
1)      Give the Agency the ability to choose the IAL level best suited for the Agency needs, regardless of the FIPS 199 security categorization.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Adjusting language to say FIPS mod or higher is a good thing. The last comment is not accurate.  The IAL selection has nothing to do with the security controls section.
