### ISSUE TITLE
What does compliance identity evidence mean? Please phrase the description in terms of the authoritative requirements for the evidence. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1350]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 5.2.1.1 (Scoring of Identity Evidence)
Table 5-1, Unacceptable
, 
 
**Comment (Include rationale for comment)**:  What does compliance identity evidence mean? Please phrase the description in terms of the authoritative requirements for the evidence.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Compliance is a typo.  **Compliant**
