### ISSUE TITLE
What does the term cryptographic security features mean? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1351]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 5.2.2.1 (Methods to Perform Identity Evidence Validation)
Table 5-2, Fair
Table 5-2, Strong
Table 5-2, Superior
, 
 
**Comment (Include rationale for comment)**:  What does the term cryptographic security features mean?
 
If the authoritative provider of the digital evidence is a Federal agency, the cryptographic mechanism behind the cryptographic security feature must adhere to Federal standards (FIPS 140-2).

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
No suggested change, but this will be included in the implementation guide.
