### ISSUE TITLE
An explanation of Information accessible freely or for any fee is needed. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1353]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 5.3.2 (Knowledge Based Verification Requirements),
Bullet 2
, 
 
**Comment (Include rationale for comment)**:  An explanation of Information accessible freely or for any fee is needed.
 
Many readers may not realize the depth that nefarious actors can gain information from the Internet - fee or no fee. Examples of information accessible freely or for any fee includes (criminal records, SSN, banking, etc.).

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
It's up to the implementing (or acquiring) agency to determine the data sources they will accept. We only provide characteristics for good/bad data sources.
