### ISSUE TITLE
The rationale for a resolved, validated, or verified identity to opt-out of KBV identity is missing. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1354]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 5.3.2 (Knowledge Based Verification Requirements),
Bullet 3

, 
 
**Comment (Include rationale for comment)**:  The rationale for a resolved, validated, or verified identity to opt-out of KBV identity is missing.
 
For example, KBV verification may not be required if the user has already been vetted through other means.

Enhanced detail will assist the Agency in defining impact and identifying solutions capable of meeting requirements.
1)      Information that is freely available, or by fee, from the Internet will no longer be allowed for KBV questions (criminal records, SSN, banking).
2)      A lot of information is available via the Internet that will crimp what might be allowed for KBVs.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
verified should be removed from this list.
