### ISSUE TITLE
What does multiple data sources mean? Are there any authoritative requirements on the sources? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1355]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 5.3.2 (Knowledge Based Verification Requirements),
Bullet 4
, 
 
**Comment (Include rationale for comment)**:  What does multiple data sources mean? Are there any authoritative requirements on the sources?
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Good points on just making sure we are aligned on terms.  Auth Source, Issuing Source, 3rd party, generic data source

**Comment by paul-grassi** [comment]
Resolved via fix for #770
