### ISSUE TITLE
The phrase validated identity evidence is used here. However, the phrase is not used anywhere else in the document. Please define the term. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1356]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 5.3.2 (Knowledge Based Verification Requirements),
Bullet 6,
Sub-Bullet 4
, 
 
**Comment (Include rationale for comment)**:  The phrase validated identity evidence is used here. However, the phrase is not used anywhere else in the document. Please define the term.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This requirement is redundant.  We will clean it up.
