### ISSUE TITLE
How is this requirement affected by requirement for a maximum number of failed sessions? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1358]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 5.3.2 (Knowledge Based Verification Requirements),
Bullet 6,
Sub-Bullet 10
, 
 
**Comment (Include rationale for comment)**:  How is this requirement affected by requirement for a maximum number of failed sessions? 
 
Are there any requirements associated with locking an account as required under NIST SP 800-53r4 AC-7 (Unsuccessful Logon Attempts)?

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is good.  We need details that sub-bullet 10 != a failed attempt.  In addition, guidance on what happens after max failed attempts is good.
