### ISSUE TITLE
The term ADEQUATE evidence is not defined within this document. It needs to be defined. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1359]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.6 (Summary of Requirements),
Table 4-3, Evidence
, 
 
**Comment (Include rationale for comment)**:  The term ADEQUATE evidence is not defined within this document. It needs to be defined.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Resolved by #518
