### ISSUE TITLE
Storage of ID Document Images

### ISSUE THREAD

**Issue by tarbrix** [usnistgov/800-63-3#136]
2:

Technology Provider:

63-3A:

4.2, Page 7, Item 7:

The ability to securely store images of identity documents should be permitted for forensic purposes, e.g. to aid in investigations of how/why an applicant was allowed to become a subscriber when they should not have been.  Of course, reasonable controls should be required to ensure privacy, confidentiality and integrity of the images.  Furthermore, there should be reasonable limits on how long the document images can be retained - 1 year?  3 Years? 

**Suggested Change**:

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jamiedanker-nppd** [comment]
@tarbrix See 4.2 #8 where it states the CSP SHALL record the types of identity evidence presented in the proofing process including any identification and reference number.  Is this sufficient for the forensic purposes you describe?  The rationale for the SHALL NOT record images or scans... requirement stems from data minimization and intent is to reduce collection of scanned images of identity documents by the CSP ("unless explicitly required for a specific IAL  see 4.2 #9).  As you note there would be a need for controls to ensure the privacy, confidentiality and integrity of the images and reasonable retention lengths for such images, would like to understand what the added benefit of recording an image of a scanned identity document adds versus just the document type /identification/reference number.  Can you offer any specific examples?

**Comment by tarbrix** [comment]
I understand that deleting the image immediately after use helps ensure privacy.  However, authenticating a photo ID is a critical step in an enrollment process and there are many different ways this can be accomplished.  If, at some future point, a subscriber is found to be a fraudster, having the ability to go back and review an image of the photo ID might reveal clues or processes deficiencies that could have prevented the applicant from being elevated to a subscriber.  Examples might include:  photo image didn’t really match the applicant, ID was faked and could have been detected if closer attention to some detail was paid, textual information on the ID did not match data that was independently supplied by the applicant (e.g. DOB on application didn’t match the DOB on the ID), ID identifier (license number) can’t be verified with issuer.   Depending on the specific mechanisms/processes an entity uses to authenticate an ID this type of forensic analysis could lead to better systems and reduced fraud.

**Comment by jamiedanker-nppd** [comment]
@tarbrix thanks for your feedback. We're working to consolidate and clarify requirements 7-9 in this section.  Rather than call out scans of identity images explicitly as a SHALL NOT requirement the update will direct the CSP to conduct a privacy risk assessment to determine, among other things, the PII, including any images, scans, or other copies of the identity evidence that the CSP will maintain as a record of identity proofing.

**Comment by paul-grassi** [comment]
Closed by pull #284
