### ISSUE TITLE
Please revise to indicate that the LOW, MODERATE, and HIGH baselines are both agency and implementation dependent. (This is frequently misunderstood.) 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1360]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.4.1.8 (Security Controls),
Para 1
Section 4.5.8 (Security Controls),
Para 1
, 
 
**Comment (Include rationale for comment)**:  Please revise to indicate that the LOW, MODERATE, and HIGH baselines are both agency and implementation dependent. (This is frequently misunderstood.)
 
For example, the requirements for a FedRAMP MODERATE system are different from those NIST proposes for a non-FedRAMP MODERATE system.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
I believe the term 'equivalent' satisfies this, but maybe will add 'federal' to 'industry'

**Comment by paul-grassi** [comment]
Also see NSA comment regarding the ability to select additional controls, not just the baseline.
