### ISSUE TITLE
Please provide a definition of a third-party data service. Ensure the definition includes whether or not a Contractor's identity service should be considered third party. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1361]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.5.3 (Validation Requirements),
Bullet 2
, 
 
**Comment (Include rationale for comment)**:  Please provide a definition of a third-party data service. Ensure the definition includes whether or not a Contractor's identity service should be considered third party.

 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed with issue #770
