### ISSUE TITLE
Recommend including more information on how implementing strategies will change from locally to remotely. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1362]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 7.1 (Threat Mitigation Strategies)
Table 7-2, Enrollment, Falsified identity proofing evidence

, 
 
**Comment (Include rationale for comment)**:  Recommend including more information on how implementing strategies will change from locally to remotely.
 
For example, checking physical security features implies a predominantly local implementation (i.e., touch).

If part of the strategy can address a remote implementation, please include that information as well.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
It is expected that industry will continue to innovate to provide these checks both remotely and in-person. However, we understand the question and plan on releasing an implementation guide that will include what needs to be done remote/in-person to satisfy these requirements.
