### ISSUE TITLE
Is guidance (or a reference) available that can be included for performing an assessment to define the required IAL? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1363]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.2 (General Requirements),
Para after
Table 4-1
, 
 
**Comment (Include rationale for comment)**:  Is guidance (or a reference) available that can be included for performing an assessment to define the required IAL?
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
800-63-3 contains this information.
