### ISSUE TITLE
Is should the right term to use here? The term must is recommended. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1364]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 6.3 (AAL2 Requirements),
Req. 1

, 
 
**Comment (Include rationale for comment)**:  Is should the right term to use here? The term must is recommended.
 
Restating as a mandatory requirement will assist the Agency in defining impact and identifying solutions capable of meeting requirements.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
NIST 800-157 will specify the rules required for federal derived piv.  This is the base document and it is not in our interest to mandate this requirement.
