### ISSUE TITLE
Please cite the appropriate controls from the UL family of controls from NIST SP 800-53r4. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1365]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 8.3 (Use Limitation),
Para 1
, 
 
**Comment (Include rationale for comment)**:  Please cite the appropriate controls from the UL family of controls from NIST SP 800-53r4.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
SP 800-53 is current under revision. Any specific controls reference will be out of date.
