### ISSUE TITLE
Processes associated with performing Identity Evidence Validation are not clear. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1366]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 5.2.1.1 (Scoring of Identity Evidence),
Table 5-1
, 
 
**Comment (Include rationale for comment)**:  Processes associated with performing Identity Evidence Validation are not clear.
 
1)      Use cases are needed demonstrating how identity evidence at different strengths is aggregated to provide the required identity proofing.  The use cases should provide examples for meeting IAL2 and IAL3 requirements.

1)      Use case examples will help the Agency developers build solutions that meet the NIST IAL requirements.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We understand and will be releasing a companion implementation guide to address comments like this.
