### ISSUE TITLE
The term Authenticated Protected Channel is used without having either a description in Section 3 or here. Even the term Channel is not adequately defined. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1368]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.2 (General Requirements),
Req. 10
, 
 
**Comment (Include rationale for comment)**:  The term Authenticated Protected Channel is used without having either a description in Section 3 or here. Even the term Channel is not adequately defined.

 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Resolved via #898
