### ISSUE TITLE
Can a reference be added to documentation that describes generic fraud mitigation measures (and strategies)? This would be very helpful. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1369]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.2 (General Requirements),
Req. 11
, 
 
**Comment (Include rationale for comment)**:  Can a reference be added to documentation that describes generic fraud mitigation measures (and strategies)? This would be very helpful.

 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This will be addressed in a forthcoming implementation guide that will support 800-63
