### ISSUE TITLE
The usability requirement discussed issuing a machine readable optical label. Not all applicants will be able to use such a label. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1370]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 9.3 (Enrollment and Proofing Session),
Bullet 6

, 
 
**Comment (Include rationale for comment)**:  The usability requirement discussed issuing a machine readable optical label. Not all applicants will be able to use such a label.
 
Always provide users with alternate approach directions as not all users are willing to use this level of technology. Additionally, other users may not have the technology needed for this approach to be usable.

1)      Integration of alternate approaches will ensure the Agency systems provide required access to all beneficiaries and staff.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by ychoong** [comment]
Two of the three recommended sentences were used.

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
