### ISSUE TITLE
Recommend adding Disposal and/or protection must be in accordance with PII protection requirements. to the bullet. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1371]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.2 (General Requirements),
Req. 12
, 
 
**Comment (Include rationale for comment)**:  Recommend adding Disposal and/or protection must be in accordance with PII protection requirements. to the bullet.
 
This is to ensure the CSP does not simply erase the media and reuse/dispose of the media in a manner that would not be appropriate. Related to the Media Protection (MP) family of controls in NIST SP 800-53r4.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Regardless of whether the media are identity-related, the requirements of SP 800-53 still apply and do not need to be repeated here.

We will clarify the relationship with other special publications in 800-63-3.

**Comment by paul-grassi** [comment]
Already addressed in section 2.2 of 800-63-3.
