### ISSUE TITLE
Other required privacy artifacts may be applicable to an agency offering or using a proofing service. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1372]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.2 (General Requirements),
Req. 13
, 
 
**Comment (Include rationale for comment)**:  Other required privacy artifacts may be applicable to an agency offering or using a proofing service.
 
This can include Data Use Agreements, Computer Matching Agreements, etc. Artifacts are driven by Controls AC-21 (Information Sharing), AP-1 (Authority to Collect), and UL-1 (Internal Use) in NIST SP 800-53r4.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jamiedanker-nppd** [comment]
See #1421 recommend similar approach
