### ISSUE TITLE
Each requirement would benefit from inclusion of the applicable authoritative reference. Below are four examples of enhanced detail that should be added: 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1373]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.2 (General Requirements),
Req. 1 thru 13
, 
 
**Comment (Include rationale for comment)**:  Each requirement would benefit from inclusion of the applicable authoritative reference. Below are four examples of enhanced detail that should be added:
 
1)      For Requirement 1: Some organizational implementations of NIST SP 800-53r4 control AC-17 (Remote Access) require users to be explicitly authorized for remote access. If identity proofing is responsible for determining suitability and/or entitlement, authorization is no longer appropriately controlled. Meeting control AR-8 (Accounting of Disclosures) is also made more complicated as non-repudiation may not be achievable.
2)      For Requirement 2: Many agencies have active programs addressing the reduction in reliance/use of the SSN. Mention checking policies/directives associated with SSN reduction.
3)      For Requirement 3: Add "as required by Federal Statute and Directives". Many readers may not realize that the collection of PII must be minimized – or why. The NIST SP 800-53r4 control DM-3 (Minimization of PII Used in Testing, Training, and Research) explicitly requires minimizing use of PII.
4)      For Requirement 4: Add "why" (e.g., Notice requirements 4 are driven by X, Y, Z...). For example, NIST SP 800-53r4 controls requiring notices may include AC-21 (Information Sharing), AP-1 (Authority to Collect), and AP-2 (Purpose Specification).

Section 8 provides many of these details. An alternative would be to add references to the applicable section.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This document is the authoritative reference, as an SP 800 series under FISMA and A-130.
