### ISSUE TITLE
The term secure authentication protocol should also be explained (or reference included to an appropriate section). Provide implementation examples. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1374]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 2 (Introduction), Authenticator Assurance Level 1, 
 
**Comment (Include rationale for comment)**:  The term secure authentication protocol should also be explained (or reference included to an appropriate section). Provide implementation examples.
 
There is no assurance that the secure authentication protocols deployed within the Agency systems would meet the minimal requirements/functionality intended under NIST SP 800-63r3 when insufficient guidance is provided. Without proper guidance, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Section 2 is only an informative summary of the document. Sections 4 and 5 provide detailed information on the requirements for each AAL and for each type of authenticator, respectively.
