### ISSUE TITLE
Single-factor authentication is mentioned without providing a clear indication of what the term means. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1375]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 2 (Introduction), Authenticator Assurance Level 1, 
 
**Comment (Include rationale for comment)**:  Single-factor authentication is mentioned without providing a clear indication of what the term means.
 
At a minimum, include a forward link (or reference) to the definition as well as example implementations. There is no assurance that single-factor authentication implementations deployed within the Agency systems would meet the minimal requirements/functionality intended under NIST SP 800-63r3 when insufficient guidance is provided. Without proper guidance, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
A definition for single-factor authentication will be added to the glossary.
