### ISSUE TITLE
Please include Privacy Controls with the Security Controls wherever the information security-related controls are referenced. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1376]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 3 (Definitions and Abbreviations),
Attack and Remote
Section 4.1.1 (Security Controls)
Section 4.2.4 (Security Controls)
Section 4.3.4 (Security Controls)
Section 8.2 (Threat Mitigation Strategies)
Section 10 (Usability Consideration)
, 
 
**Comment (Include rationale for comment)**:  Please include Privacy Controls with the Security Controls wherever the information security-related controls are referenced.
 
Privacy controls must now be integrated as required under OMB Circular A-130 (2016).

the Agency is required to implement both security- and privacy-related controls.
1)      Without inclusion of the privacy controls, a developer may miss vital changes in the controls associated with the inclusion of sensitive information.
This weakens the implementation and increases the risk to the Agency.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jamiedanker-nppd** [comment]
Privacy controls are integrated into 800-63B see 4.4 Privacy Requirements addresses the need to employ appropriately tailored privacy controls defined in SP 800-53 or equivalent industry standard. Note that there are no defined baselines for privacy controls in 800-53. #1377
