### ISSUE TITLE
Please include examples of each permitted authenticator type (e.g., device, mechanism, technology) listed. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1378]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 4.1.1 (Permitted Authenticator Types),
All bullets
Section 4.2.1 (Permitted Authenticator Types),
All bullets
Section 4.3.1 (Permitted Authenticator Types),
All bullets
, 
 
**Comment (Include rationale for comment)**:  Please include examples of each permitted authenticator type (e.g., device, mechanism, technology) listed.
 
For example, a Memorized Secret is the password or PIN – but does not get defined until Section 5.1.1.

Do not assume that every reader will understand the terminology. When first referenced, a description should be given. (NOTE: A reference to the definition would be acceptable - if the definition is in a glossary section.)

There is no assurance that the authenticator types implemented by the Agency systems would meet the minimal requirements/functionality intended under NIST SP 800-63r3 when insufficient guidance is provided. Without proper guidance, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Forward references to the authenticator requirements in Section 5 seem reasonable.

It is anticipated that an implementation guide will be written following the SP 800-63-3 update which will likely have more specific examples of authenticators.
