### ISSUE TITLE
Verifiers operated by government agencies at AAL1 and AAL 2shall be validated to meet FIPS 140 Level 1 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1379]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 4.1.2
Section 4.2.2
, 
 
**Comment (Include rationale for comment)**:  Verifiers operated by government agencies at AAL1 and AAL 2shall be validated to meet FIPS 140 Level 1
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Yes, that is what the guideline calls for. Not sure what the comment is.
