### ISSUE TITLE
Identity Evidence Validation Requirements

### ISSUE THREAD

**Issue by tarbrix** [usnistgov/800-63-3#138]
2:

technology Provider:

63-3A:

Section 4.5.2, Page 8, Bullet 2:

Comment:  This implies that the second form of required STRONG identity evidence must be verified with the issuing agency.  For commercial entities it may be very difficult, if not impossible, to comply with this.  Many DMVs for example, have no provisions whatsoever to verify Driver's License information to anyone other than law enforcement or other authorized government agencies.

Suggestion:
## Allow both pieces of STRONG evidence to be verified with a 3rd party.  To increase confidence in the authenticity of the document, perhaps NIST could require that various physical attributes of the document be verified.  For example:  verify presence of holograms and other  security features, verify name/address on document match the public record, very information encoded on magstripe/barcode matches printed information, etc.

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
Section 4.5.2 is all about the characteristics of evidence, not validation.

**Comment by rsfaron23** [comment]
I am not sure that this will fit the requirements of our program, where either the CSP is the employer or the CSP is our agency.  I need further clarification as to the identity proofing process for Levels 2-3.

**Comment by paul-grassi** [comment]
What specifically won't fit?  Your comment is somewhat vague so I can't respond effectively.

**Comment by rsfaron23** [comment]
The E-Verify program is dependent on credentials meeting the requirements of the I-9 list A, or B and C.  these are credentials issued by 3rd parties, but the employer just has to reasonable review and assert their legitimacy and applicability to the person in front of them.  The E-Verify process authenticates to these assertions.  We would also like to authenticate to remote assertions based on e-sign criteria. In that case we will not have the employers identity proofing capabilities, but need to rely on 3rd parties (i.e., the issuer of the documents.  Should we change our process so we are the CSP we will still ha wot rely on asserted identity claims, and will not have the ability to proof directly but only through 3rd party (commercial) or through the employer.  How can we rely on these processes when we do not interact with the document providers?

Robert Faron
202-905-7000
rsfaron@gmail.com

**Comment by rsfaron23** [comment]
Paul. I am just getting into this in depth and I will by next week get into all aspects and be more familiar and conversant. 

Bob Faron
202-905-7000
