### ISSUE TITLE
Please include use case examples in each section where each AAL (i.e., AAL1, AAL2, and AAL3) would be appropriate choices. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1380]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 4.1 (Authenticator Assurance Level 1)
Section 4.2 (Authenticator Assurance Level 2)
Section 4.3 (Authenticator Assurance Level 3)
, 
 
**Comment (Include rationale for comment)**:  Please include use case examples in each section where each AAL (i.e., AAL1, AAL2, and AAL3) would be appropriate choices.
 
Without examples and additional clarifications, the Agency will have to make interpretations that may not meet the intended guidance from NIST.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Guidance on the selection of authentication assurance levels had until very recently been in OMB M-04-04 but is now part of SP 800-63-3 (the top-level document) which was revised at the end of April. Please review this document and submit a new issue prior to May 1 if additional examples are needed there.
