### ISSUE TITLE
The phrase general purpose operating system (OS) implies the requirement may not apply to specialized environments such as control systems (e.g., SCADA) and devices (medical 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1381]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 4.1.2 (Authenticator and Verifier Requirements),
Para 1
Section 4.2.2 (Authenticator and Verifier Requirements),
Para 1
, 
 
**Comment (Include rationale for comment)**:  The phrase general purpose operating system (OS) implies the requirement may not apply to specialized environments such as control systems (e.g., SCADA) and devices (medical appliances).
 
Many specialized OS variants also attempt to detect fraudulent operation as well.

The statement should be revised as it is misleading,

Optional requirements (i.e., general purpose operating system MAY, where practical) such as this may affect appliances deployed as part of a the Agency system under AAL1 and AAL2.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The guideline is silent on what may be done by other than general purpose operating systems, but it is not precluded by the current text. Nevertheless, a more generic "where applicable" will be used.
