### ISSUE TITLE
Please revise to indicate that the LOW, MODERATE, and HIGH baselines are both agency and implementation dependent. (This is frequently misunderstood.) 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1382]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 4.1.4 (Security Controls),
Para 1
Section 4.2.4 (Security Controls),
Para 1
Section 4.3.4 (Security Controls),
Para 1
, 
 
**Comment (Include rationale for comment)**:  Please revise to indicate that the LOW, MODERATE, and HIGH baselines are both agency and implementation dependent. (This is frequently misunderstood.)
 
For example, the requirements for a FedRAMP LOW system are different from those NIST proposes for a non-FedRAMP LOW system.

While privacy controls are discussed in Section 4.4, they should be mentioned here as well. Also, reference a possible need to adjust (tailor) security controls to account for PII/PHI.

Without the proper guidance, the Agency system implementations may be misled into believing that meeting NIST SP 800-63r3 will be sufficient to achieve compliance with the Agency requirements. This would be in error and could be a substantial cost to a project. It is imperative that implementers know two basic requirements exist: meet the NIST SP 800-63r3 requirements AND meet organizational (i.e., the Agency/HHS) requirements.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Analogous to #1360
