### ISSUE TITLE
Is not reversibility dependent upon the authenticator? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1383]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 6.2 (Loss, Theft, Damage, and Unauthorized Duplication),
Para 2
, 
 
**Comment (Include rationale for comment)**:  Is not reversibility dependent upon the authenticator?
 
For example, if an RSA token is reported lost and a replacement token shipped, can (or even should) the CSP reactivate the old token if it is found? The guidance should indicate reversibility may be subject to agency policies.

There is no assurance that authenticator reversibility strategies and techniques deployed by the Agency systems would meet the minimal requirements/functionality intended when NIST SP 800-63r3 provides insufficient guidance. Without proper guidance, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Reversibility is highly implementation dependent. Since the guideline is (appropriately) silent on this topic, it is subject to agency policies.
