### ISSUE TITLE
Additional authenticator binding notification restrictions

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1385]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 6.1.2.1 (Binding of Additional Authenticator at Existing AAL),
Para 2
, 
 
**Comment (Include rationale for comment)**:  Are there restrictions on how the notification is to be sent? For example, must the notification be sent via an out-of-band channel? Must the channel be authenticated or encrypted?
 
There is no assurance that notification strategies and techniques deployed by the Agency systems would meet the minimal requirements/functionality intended when NIST SP 800-63r3 provides insufficient guidance. Without proper guidance, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The notification should be made to the subscriber independent of the transaction binding the new authenticator. Encryption and authentication is not required (a post card could be sent).
