### ISSUE TITLE
The guidance is recommending that third party subscriber-provided authenticators, perhaps Facebook or Google, be leveraged where permissible. . . 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1386]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 6.1.3 (Binding to a Subscriber-provided Authenticator),
Para 1

, 
 
**Comment (Include rationale for comment)**:  The guidance is recommending that third party subscriber-provided authenticators, perhaps Facebook or Google, be leveraged where permissible. . .
 
1)      Provide references or links to the social network providers that meet AAL2 and IAL1.
The guidance should indicate the decision to use third party subscriber-provided authenticators may be subject to agency policies or legislated proofing requirements.

There is no assurance that subscriber-provided authenticator strategies and techniques deployed by the Agency systems would meet the minimal requirements/functionality intended when NIST SP 800-63r3 provides insufficient guidance. Without proper guidance, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This would be covered in a future implementation guide supplementing the guidelines in 800-63B.
