### ISSUE TITLE
Recommend including that retaining of the identity proofing process evidence may be subject to privacy considerations. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1387]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 6.1.2.3 (Replacement of Lost Authentication Factor),
Para 1
, 
 
**Comment (Include rationale for comment)**:  Recommend including that retaining of the identity proofing process evidence may be subject to privacy considerations.
 
Any evidence that could include sensitive information, such as PII, would be subject to privacy.

There is no assurance that identity proofing strategies and techniques deployed by the Agency systems would meet the minimal requirements/functionality intended when NIST SP 800-63r3 provides insufficient guidance. Without proper guidance, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jamiedanker-nppd** [comment]
SP 800-63A, Section 4.2 identifies privacy requirements for identity proofing  including the PRA requirement for identity evidence retained- if the process must be repeated, the requirements (including privacy apply from 800-63A).   Consider adding a link to [800-63A]  to 6.1.2.3 That subscriber SHALL repeat the identity proofing process [SP 800-63A].

**Comment by jimfenton** [comment]
Add citation at beginning of 6.1.2.3 to identity proofing process in 800-63A. The privacy requirements requested are defined there.
