### ISSUE TITLE
Please clarify what "the Impact of an authentication failure" refers to in this section. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1388]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 4 (Authenticator Assurance Levels),
Para Below Table 4-1
, 
 
**Comment (Include rationale for comment)**:  Please clarify what "the Impact of an authentication failure" refers to in this section.
 
Since the individuals may or may not be familiar with the possible impacts, it is recommended examples/use cases be included that can help visualize the impact.

There is no assurance that the impact from authentication failures on deployments within the Agency systems would meet the minimal requirements/functionality intended under NIST SP 800-63r3 when insufficient guidance is provided. Without proper guidance, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
These tables and accompanying text are being removed in conjunction with the changes to SP 800-63-3 to directly specify AAL, IAL, and FAL requirements.
