### ISSUE TITLE
If a risk exists where use of UNICODE could invalidate the ability to authenticate 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1389]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 5.1.1.2 (Memorized Secret Verifiers),
Para 2

, 
 
**Comment (Include rationale for comment)**:  If a risk exists where use of UNICODE could invalidate the ability to authenticate
 
If a risk exists where use of UNICODE could invalidate the ability to authenticate, then a requirement disallowing use of UNICODE (i.e., not an optional decision made during implementation) is more appropriate.

Self-inflicted denial of service would present extreme challenges while debugging. Are there strategies that can be implemented that will help debug when this is occurring? If yes, please provide applicable discussion or reference.

There is no assurance that solutions to address UNICODE issues (i.e., reduce risk of a problem occurring) implemented by the Agency systems would meet the minimal requirements/functionality intended under NIST SP 800-63r3 when insufficient guidance is provided. Without proper guidance, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
There is not a general risk of failure inherent to accepting Unicode; there could be implementation errors but that's not a problem specific to Unicode nor a reason not to allow it.
