### ISSUE TITLE
Address Confirmation

### ISSUE THREAD

**Issue by tarbrix** [usnistgov/800-63-3#139]
2:

technology Provider:

63-3A:

4.5.5 and 4.6.5, pages 8 and 9:

Comment (Include rationale for comment):  The requirement to send a confirmation to a physical address of record will make it impossible for the applicant to complete the enrollment process in a single visit.  This provision should allow the confirmation to be sent to a verified email address or phone number.  The "verification" of the email address and/or phone number should be accomplished by 1):  verify the address/phone is associated with the applicant in the public record and 2) verify the applicant's ability to receive communications at that address.  

Leaving this requirement "as is" puts an undue hardship on applicants and may discourage many from apply for the credential.

**Suggested Change**:

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
It is not a requirement to send to physical address, it is an option among multiple addresses.

**Comment by tarbrix** [comment]
Unless I am looking at an older version, the fourth bullet in 63-3A, section 4.6.5 says “SHALL be sent to the physical mailing address verified in records”.
I see now that I was in error to include 4.5.5 in my reference.  Within 4.5.5 clearly the confirmation can be sent to a variety of addresses.

I suppose it is NIST’s intention that at IA3 the confirmation MUST be sent to the Physical Address.

Thanks
Philip

**Comment by paul-grassi** [comment]
4.6.6 says NOTIFICATION should be sent, but that is just intended to send a note to the address "Hey, you got proofed" in case the in-person action was fraudulent.  It is not meant to be for confirmation. In other words, proofing can complete within a single transaction.

**Comment by tarbrix** [comment]
I am so sorry to waste your time.  I was looking at a version dated 05/31 and see a newer version has been posted that removed the language I was complaining about.

Thanks
Philip
