### ISSUE TITLE
Disallowed methods are discussed. Please provide examples of methods that could be allowed. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1390]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 5.1.3.1 (Out-of-Band Authenticators),
Para 2
, 
 
**Comment (Include rationale for comment)**:  Disallowed methods are discussed. Please provide examples of methods that could be allowed.
 
Examples can be inferred (e.g., SMS) from the subsequent paragraphs. However, clearly defined examples would be most helpful. An assumption is implied that any implementation that is not explicitly disallowed must be allowed. However, this does not consider environments where some solutions may be more secure (e.g., robust, less vulnerable) than others. Without proper guidance, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This would be covered in a future implementation guide supplementing 800-63B. Generally speaking, smartphone applications that contain a per-user secret and communicate with the verifier over a secure independent communications channel would be an example of a suitable out-of-band authenticator.
