### ISSUE TITLE
Biometric spoofing attacks

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1391]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 5.2.3 (Use of Biometrics),
Para 1,
Bullet 1
, 
 
**Comment (Include rationale for comment)**:  1)      Please provide information on the statement that match and non-match rates do not account for spoofing attacks. Also, ensure the reader knows what a spoofing attack is.
 
Always include a reference to terminology and concepts used. Where applicable, include references for examples and/or strategies to mitigate malicious activity.

There is no assurance that anti-spoofing attack strategies and techniques deployed by the Agency systems would meet the minimal requirements/functionality intended under NIST SP 800-63r3 when insufficient guidance is provided. Without proper guidance, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by enewt** [comment]
Add a reference to ISO/IEC 30107-1 and include the URL for a free copy:
http://standards.iso.org/ittf/PubliclyAvailableStandards/c053227_ISO_IEC_30107-1_2016.zip

FYI - match rates reflect the biometric pattern's distinctiveness. Imposters in this testing are "zero-effort"  imposters (the equivalent of someone seeing if their biometric pattern happens to match a user's account). It does not account for creating a fake biometric.
