### ISSUE TITLE
If subscribers are required to surrender or prove destruction of any physical authenticators, guidance should be provided of what constitutes acceptable evidence. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1392]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 6.3 (Expiration),
Para 2
Section 6.4 (Revocation and Termination),
Para 2
, 
 
**Comment (Include rationale for comment)**:  If subscribers are required to surrender or prove destruction of any physical authenticators, guidance should be provided of what constitutes acceptable evidence.
 
There is no assurance that authenticator destruction strategies and techniques deployed by the Agency systems would meet the minimal requirements/functionality intended when NIST SP 800-63r3 provides insufficient guidance.
1)      Solutions deployed by the Agency may be more rigorous than NIST intends, costing the Agency additional resources.
Without proper guidance, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Same as #1064.
