### ISSUE TITLE
Please insert a discussion of what an approved random bit generator is in either the text (i.e., Section 5.1.1.2) or in a glossary (i.e., Section 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1393]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 5.1.1.2 (Memorized Secret Verifiers),
Para 3

, 
 
**Comment (Include rationale for comment)**:  Please insert a discussion of what an approved random bit generator is in either the text (i.e., Section 5.1.1.2) or in a glossary (i.e., Section 3).
 
Include a reference where the list of approved random bit generators can be found.

There is no assurance that approved random bit generator solutions implemented by the Agency systems would meet the minimal requirements/functionality intended under NIST SP 800-63r3 when insufficient guidance is provided. Without proper guidance, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
_Appproved_ is already defined in the glossary. A reference to SP 800-90 might be appropriate here.
