### ISSUE TITLE
Disregarding previous failed attempts from the same IP address could be a problem if the site the user comes from operates using a NAT. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1395]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 5.2.2 (Rate Limiting (Throttling)),
Para 3

, 
 
**Comment (Include rationale for comment)**:  Disregarding previous failed attempts from the same IP address could be a problem if the site the user comes from operates using a NAT.
 
The requirement should state both the user identifier and IP address need to match.

Disregarding previous failed attempts increases risk of an attack going unnoticed when the attacker “resets the clock” by simply authenticating successfully through a second account.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Rate-limiting state information is maintained by user but apparently that isn't clear enough.
