### ISSUE TITLE
Please discuss applicability of not prompting users for specific types of information. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1396]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 5.1.1.2 (Memorized Secret Verifiers),
Para 4

, 
 
**Comment (Include rationale for comment)**:  Please discuss applicability of not prompting users for specific types of information.
 
1)      Does the requirement apply to the memorized secret itself (i.e., the hint referred to), or does it also apply to secondary verification to be used if the claimant is trying to get the secret reset?
If the hint is not stored where an unauthenticated claimant cannot access the hint, provide examples of how the hint would be conveyed to a user that cannot remember the password (e.g., out-of-band channel – email, text, phone)

There is no assurance that user prompting solutions (aiding a user in recalling forgotten passwords) implemented by the Agency systems would meet the minimal requirements/functionality discussed intended under NIST SP 800-63r3 when insufficient guidance is provided. Without proper guidance, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
There is no "secondary verification": just the use of an alternate authenticator in case the primary doesn't work. The guideline is very clear on this:

**Hints SHALL NOT be used.**
**Prompts for specific information (security questions) SHALL NOT be used.**

Agencies using these techniques will indeed require re-engineering of their account recovery processes.
