### ISSUE TITLE
The terms long enough and adequate are subjective. The guidance needs to be objective: 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1397]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 10.1 (Usability Considerations Common to Authenticators),
Para 5,
Bullet 5,
Sub bullets 1 & 2
, 
 
**Comment (Include rationale for comment)**:  The terms long enough and adequate are subjective. The guidance needs to be objective:
 
1)      As appropriate, suggest the user have the ability to define the masking delay duration/text entry time in their profile or through a setting
Provide recommended masking delay duration (e.g., 5 seconds, until the next character is typed, etc.)/text entry time (e.g., one minute)

Ensure the Agency systems are providing masking delay durations/text entry times that are consistent with user needs.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by ychoong** [comment]
We used the last sentence from the suggestion.

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
