### ISSUE TITLE
When referencing availability issues, ensure the bullet clearly includes the need for alternate authentication mechanisms… 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1398]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 10.1 (Usability Considerations Common to Authenticators),
Para 5,
Bullet 3
, 
 
**Comment (Include rationale for comment)**:  When referencing availability issues, ensure the bullet clearly includes the need for alternate authentication mechanisms…
 
When referencing availability issues, ensure the bullet clearly includes the need for alternate authentication mechanisms to protect against loss, damage, or other negative impact to the original authenticator mechanism.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by ychoong** [comment]
Accepted the suggested wordings with some minor tweaking.

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
