### ISSUE TITLE
Please include a reference that defines how this value (10 entry attempts) was arrived at. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1400]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 10.1 (Usability Considerations Common to Authenticators),
Para 5,
Bullet 5,
Sub bullet 4
, 
 
**Comment (Include rationale for comment)**:  Please include a reference that defines how this value (10 entry attempts) was arrived at.

 
There may be agency policy that defines a maximum number of attempts to a value that is less than 10.

the Agency may be in a situation where implementation may have to deviate from NIST SP-800-63-3 guidance to meet the Agency security and privacy requirements. 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Usability recommendations come directly from normative requirements in chapter 4 and 5.  800-63 is the authoritative document and need not point to other standards for how we determined requirements.
