### ISSUE TITLE
Please give examples and use cases for each type of authenticator (e.g., RSA tokens, biometric devices, etc.) 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1401]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 10.2 (Usability Considerations by Authenticator Type),
All subsections
, 
 
**Comment (Include rationale for comment)**:  Please give examples and use cases for each type of authenticator (e.g., RSA tokens, biometric devices, etc.)
 
By providing examples/use cases, implementers will better understand the strategy NIST is recommending to secure both identity-proofing and authentication.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This is better handled in the implementation guide that is planned following the publication of the SP 800-63-3 document suite.
