### ISSUE TITLE
The guidance of what may be included for comparing the prospective secrets against should include: 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1402]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 5.1.1.2 (Memorized Secret Verifiers),
Para 5,
Bulleted List

, 
 
**Comment (Include rationale for comment)**:  The guidance of what may be included for comparing the prospective secrets against should include:
 
1)      common organizational terminology, acronyms, and phrases
2)      Sports and local school terminology

Dictionaries need to compare for languages common to the geographical area the service serves. For example, English and Spanish dictionaries should be routinely checked, however it may be advisable to include dictionaries of all the major world languages.  

It is not uncommon for users to choose secrets (passwords) that are associated with work (such as acronyms) or local sports. Password cracking applications are highly tunable—and can be easily tailored. When vetting a new user secret (password), the Agency systems should not limit the check to common language dictionaries. The dictionaries need to include common sports terminology (such as team names, mascots) and organizational terminology 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This is more prescriptive than appropriate for SP 800-63B, but worthy of discussion in the planned implementation guide.
