### ISSUE TITLE
In addition to the Privacy Act system of records, other privacy artifacts may be applicable to an agency offering or using a proofing service. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1403]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 9.4 (Agency-specific Privacy Compliance),
Para 1
, 
 
**Comment (Include rationale for comment)**:  In addition to the Privacy Act system of records, other privacy artifacts may be applicable to an agency offering or using a proofing service.
 
This can include Data Use Agreements, Matching Agreements, etc.

There is no assurance that ALL privacy-related artifacts (a legal obligation) will be created during the development process without appropriate reminders. Without proper guidance throughout development, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future to meet the privacy requirements.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jamiedanker-nppd** [comment]
See #1421 recommend similar approach
