### ISSUE TITLE
In many environments, a remote user is any user connecting to an organizational service via the Internet. This is derived from the definition of remote. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1404]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 6.1.1 (Enrollment),
Para 4,
Bullet “1.”
, 
 
**Comment (Include rationale for comment)**:  In many environments, a remote user is any user connecting to an organizational service via the Internet. This is derived from the definition of remote.
 
 The requirements for remote transactions are:
1.      For remote transactions
a)      The applicant SHALL identify themselves in each new transaction by presenting a temporary secret which was established during a prior transaction or encounter, or sent to the applicant’s phone number, email address, or postal address of record.
b)      Long-term authenticator secrets SHALL only be issued to the applicant within a protected session.

1)      Considering requirement “a)” for remote transactions: An organizational user will need to be issued a new access code each time the user logs into their organizational account. Is this truly the intent? Will this not make access increasingly difficult to the point users will become irritated?
2)      Considering requirement “b)” for remote transactions: What exactly do long-term and protected session mean in this context? While protected session is defined (see Section 3), long-term is not defined at all in the 800-63-3 volumes.
For both requirement “a)” and requirement “b)”, please include a use case addressing how NIST envisions the process to work.

Under requirement “a)” for remote transactions, the the Agency beneficiary (the user) will need to be issued a new access code each time the beneficiary logs into their the Agency account. Each system provides the beneficiary with an enrollment prompt, perhaps similar to the following:
How do you want the secondary access code delivered?
A.  Call phone number the Agency has on file
B.  Send text message to phone number the Agency has on file
C.  Send email to email address the Agency has on file
D.  Send letter via postal mail to address the Agency has on file
After the beneficiary has received the code and logs in to see:
Enter received secondary access code to continue:
Not only does this technique require use of a secondary channel (phone number, email address, or postal address of record) that not all beneficiaries may have, it also requires the beneficiary understand a few things about modern communication technology (e.g., where text messages can and cannot be sent.) Example use case:
Ben Eficiary sets up account choosing snail mail for code deliver (i.e., Ben Eficiary’s computer). Six months later Ben Eficiary moves into a retirement community and changes phone number(s) – forgetting to change settings in his/her the Agency account. A year after that, Ben Eficiary needs to make a change in his/her the Agency account. Ben Eficiary cannot log in since USPS does not forward postal mail indefinitely and the phone number on file is invalid. . .
The extra steps alone will not be popular.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This section does not apply to authentication transactions (each time a user logs into their Agency account), but to enrollment transactions such as the association of a new authenticator with the user's account.

**Comment by jimfenton** [comment]
_Protected session_ is a holdover from older terminology. _Authenticated protected session_ should be used instead.

A-D all appear to be acceptable means for delivering an enrollment code. Yes, and CSP and/or the subscriber will need to understand the limitations of those technologies and use an appropriate one.

**Comment by jimfenton** [comment]
It was less awkward to define _protected session_ instead.
