### ISSUE TITLE
Look-Up Secrets may represent an O&M concern. The list must be maintained – and resources will be needed to provide the O&M. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1405]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 10.2.2 (Look-up Secrets),
Para 1
, 
 
**Comment (Include rationale for comment)**:  Look-Up Secrets may represent an O&M concern. The list must be maintained – and resources will be needed to provide the O&M.
 
Look-up secrets may mean that the Agency will need to use additional resources to manage the secrets.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by ychoong** [comment]
No suggested change was given. Additionally, this is a resource management issue, not a usability issue.
