### ISSUE TITLE
PAD requirement may make it difficult to Bring Your Own Authenticator

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1406]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 5.2.3 (Use of Biometrics),
Para 6

, 
 
**Comment (Include rationale for comment)**:  1)      The requirement to implement PAD may make it difficult, if not impossible, for the user to use devices that have not been issued by the CSP (i.e., BYOD).
 
(e.g., periodically) are a contradiction to NIST SP 800-53r4 control requirements. Control IA-5 (Authenticator Management) and IA-5(1) (Password-Based Authentication) define the composition requirements for memorized secrets as well as lifetimes.

1)      The requirement to implement PAD may make it difficult, if not impossible, for the user to use devices that have not been issued by the CSP (i.e., BYOD). (Example: fingerprint readers differ from one device manufacturer to another.)
2)      The 90% value for resistance to presentation attacks may be governed by a more restrictive organizational policy. Always include a reference to check the organizational policies whenever security- or privacy-related configuration setting is listed.
Please provide a reference or link to information describing relevant attack types. This will aid an implementer in making a better choice.

If the optional requirement becomes mandatory, the Agency may have to issue tamper-resistant biometric readers to all users.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by enewt** [comment]
1. PAD is not required. There is an option to not use PAD and limit the number of unsuccessful attempts.
2. Of course an organization can implement a stronger set of security requirements. 63-b reflects a floor.
3. A new rev to 53 is coming that aligns requirements across the documents.
