### ISSUE TITLE
The requirements that verifiers SHOULD NOT impose other composition rules and SHOULD NOT require memorized secrets to be changed arbitrarily… 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1407]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 5.1.1.2 (Memorized Secret Verifiers),
Para 8

, 
 
**Comment (Include rationale for comment)**:  The requirements that verifiers SHOULD NOT impose other composition rules and SHOULD NOT require memorized secrets to be changed arbitrarily…
 
At a minimum, the guidance in NIST SP 800-63 needs to state that the composition rules and lifetime need to be compliant with organizational policy.

Solutions implemented by the Agency systems based on the minimal requirements/functionality discussed under NIST SP 800-63r3 may not meet the Agency minimal requirements. (Developers may errantly implement a strategy that would differ from the Agency policy.) Without proper guidance, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
See #1015 and #1016
