### ISSUE TITLE
What user is required to authenticate to the device means is that the access code must be sent to the out-of-band device in a manner 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1408]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 10.2.3 (Usability, Out-of-Band),
Para 2,
Bullet 1
, 
 
**Comment (Include rationale for comment)**:  What user is required to authenticate to the device means is that the access code must be sent to the out-of-band device in a manner that ensures the code…
 
What user is required to authenticate to the device means is that the access code must be sent to the out-of-band device in a manner that ensures the code is not made available UNTIL the user re-authenticates to the device. As written, this is not clear.

It is also unclear how well the requirement can be implemented: If a user is using a smart phone when the code is received, the out-of-band code would be readily available. And what happens if a user disables locking of the phone entirely?

Implementation of mechanisms associated with transmission of codes to intelligent devices, such as smart phones, may not be fully under the Agency control. How the access code will be protected on the end-point could be definable by the user (example, text message).

Compliance could require the Agency to create and maintain custom applications mimicking commonly available capabilities to meet the stated requirements.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Note that the referenced section is informative; the normative text (in Section 5.1.3.1) is:
>the device SHOULD NOT display the authentication secret on a device while it is locked by the owner

which means that devices may display out-of-band secrets they receive without being unlocked, but it is discouraged.
