### ISSUE TITLE
The statement additional trust in the sensor is required is another example where a reference to terminology and concepts used would be beneficial. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1409]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 5.2.3 (Use of Biometrics),
Para 1 Bullet 4,
Para 4

, 
 
**Comment (Include rationale for comment)**:  The statement additional trust in the sensor is required is another example where a reference to terminology and concepts used would be beneficial.
 

The discussion states that additional trust is needed without providing the guidance needed in achieving the enhanced level of trust.
1)      The requirement for an authenticated protected channel between sensor (or endpoint) and verifier suggests that the sensor must be resistant to replacement. More information on strategies to ensure replacement resistance is needed.

There is no assurance that sensors deployed by the Agency systems would meet the minimal trust requirements/functionality intended under NIST SP 800-63r3 when insufficient guidance is provided.
1)      Without proper guidance, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future.
2)      Substantial resources would be required if the Agency is required to deploy biometric sensors that provide the required level of trust.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The required trust is that the CSP/verifier must trust the sensor and any remote processing that it indeed meets the performance requirements specified, including the use of presentation attack detection if applicable.
