### ISSUE TITLE
Please provide a reference to where example strategies and implementations resistant to off-line attacks can be found. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1410]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 5.1.1.2 (Memorized Secret Verifiers),
Para 11
, 
 
**Comment (Include rationale for comment)**:  Please provide a reference to where example strategies and implementations resistant to off-line attacks can be found.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This would be a topic for the planned implementation guide.
