### ISSUE TITLE
What is meant by the term explicit whitelist in Section 4.1.1 (or blacklists and gray area as described in Section 4.1.5)? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1412]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: Section 4.1.1 (Manual Registration),
Para 1

, 
 
**Comment (Include rationale for comment)**:  What is meant by the term explicit whitelist in Section 4.1.1 (or blacklists and gray area as described in Section 4.1.5)? 
 
A better description will help the implementer understand what the list is identifying (i.e., requesting RP can access IdP's information on user w/o asking user for approval).

Clarification can be accomplished through inclusion of examples and/or use cases.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
whitelist = "known relying party domains"

**Comment by jricher** [comment]
This is of domains or other identifiers that separate them from each other. We can clarify that varying methods can be used to populate the lists.
