### ISSUE TITLE
What does appropriate runtime decisions mean? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1413]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: Section 4.1.1 (Manual Registration),
Para 1
Section 4.1.2 (Dynamic Registration),
Para 3
, 
 
**Comment (Include rationale for comment)**:  What does appropriate runtime decisions mean?
 
This is a subjective term where examples will help to ensure the implementer will be better equipped to understand the term in an objectivity manner.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by dig-comments** [comment]
This is an accept, IMO, but we should determine what is appropriate.

**Comment by jimfenton** [comment]
It's perhaps not clear that this links to 4.1.5 -- need better visibility, especially for printed documents.
Remove the word "appropriate".

Examples would go in the implementation guide.

**Comment by jricher** [comment]
Agree with removing "appropriate" and linking directly to 4.1.5.

**Comment by jricher** [comment]
Closed by 0db11eb31856689fe50805be7a526662ff87da51
