### ISSUE TITLE
Please give authoritative references that stipulate why retention, aggregation, and disclosure to third parties can be subject to special handling. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1415]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: Section 4.1.3 (Federation Authorities), Para 1

, 
 
**Comment (Include rationale for comment)**:  Please give authoritative references that stipulate why retention, aggregation, and disclosure to third parties can be subject to special handling. 
 
Examples include PII which is subject to:
4)      OMB Directives
5)      NIST SP 800-53r4: DM-3 (Minimization of PII Used in Testing, Training, and Research)
6)      Legislation: 45 C.F.R. §164.512(i).

Please cite the appropriate controls from the UL family of controls from NIST SP 800-53r4.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Same resolution as #1342.
