### ISSUE TITLE
The statement generally conducts some level of vetting implies the vetting is optional. Are there circumstances where such vetting must not be optional? Can those 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1416]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: Section 4.1.3 (Federation Authorities), Para 1

, 
 
**Comment (Include rationale for comment)**:  The statement generally conducts some level of vetting implies the vetting is optional. Are there circumstances where such vetting must not be optional? Can those be defined?
 

Examples from the discussion within this section where confusion from this statement may arise:
1)      compliance with predetermined security and integrity standards - appears to be more of a must than a should.
2)      authorities SHALL individually vet - makes the vetting mandatory.

Again, examples and use cases help ensure understanding.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by dig-comments** [comment]
the federation authority generally conducts some level of vetting on -> the federation authority conducts vetting on

**Comment by jricher** [comment]
It's up to the federated authority to determine what kind of vetting it wants to employ. Vetting could be as simple as collecting an email address for the deployer of a client, or could be as in depth as a contract being in place between all parties with full legal consequences spelled out. In cases of fully dynamic registration, the vetting is entirely optional and the federation authority (where it exists) accepts all clients or IdPs.
