### ISSUE TITLE
Example use cases will help to ensure proxies can be set up as intended to maximize the protections to IdPs and subscribers. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1420]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: Section 4.1.4 (Proxied Federation), Para 4

, 
 
**Comment (Include rationale for comment)**:  Example use cases will help to ensure proxies can be set up as intended to maximize the protections to IdPs and subscribers.

 
Providers protecting beneficiary details from other providers, releasing only the information needed.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This would be a topic for the planned implementation guide.
