### ISSUE TITLE
Please provide guidance or references on defining an appropriate amount of time. The guidance should indicate the time may be subject to agency policies. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1423]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: Section 6.1.4 (Renewal),
Para 1
, 
 
**Comment (Include rationale for comment)**:  Please provide guidance or references on defining an appropriate amount of time. The guidance should indicate the time may be subject to agency policies.
 
There is no assurance that delay times deployed by the Agency systems would meet the minimal requirements/functionality intended when NIST SP 800-63r3 provides insufficient guidance. Without proper guidance, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by dig-comments** [comment]
@jimfenton this is -B

**Comment by jimfenton** [comment]
This is agency (or CSP) determined and depends on the renewal process being used. This is just saying that the renewal process needs to be started soon enough to finish before expiration.
