### ISSUE TITLE
Inclusion of examples (or use cases) will go a long way at helping a reader understand the enrollment requirements. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1425]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 6.1.1 (Enrollment),
Para 2
, 
 
**Comment (Include rationale for comment)**:  Inclusion of examples (or use cases) will go a long way at helping a reader understand the enrollment requirements.
 
There is no assurance that enrollment strategies and techniques deployed by the Agency systems would meet the minimal requirements/functionality intended under NIST SP 800-63r3 when insufficient guidance is provided. Without proper guidance, the Agency implementations may be delayed, require revision, or even require re-engineering at some point in the future.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This is appropriate for the implementation guide.
