### ISSUE TITLE
The FMR rate of 1 in 1000 or better may be governed by a more restrictive organizational policy. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1426]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Section 5.2.3 (Use of Biometrics),
Para 5

, 
 
**Comment (Include rationale for comment)**:  The FMR rate of 1 in 1000 or better may be governed by a more restrictive organizational policy.
 
Always include a reference to check the organizational policies whenever security- or privacy-related configuration setting is listed.

Also, neither match rate concepts (False Match Rate and False Non-Match Rate) are defined/explained. It would be helpful guide a reader to the knowledge that the FMR of 1 in 1000 means the probability the biometric will erroneously declare a match (i.e., grant access to an unauthorized individual) is .1% or less.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
As with other guidelines in this document, agencies may impose more stringent requirements in order to further reduce authentication risk.

**Comment by enewt** [comment]
The ISO/IEC terminology for biometrics is freely available here:
http://standards.iso.org/ittf/PubliclyAvailableStandards/c066693_ISO_IEC_2382-37_2017.zip

**Comment by jimfenton** [comment]
We'll add that as a reference.
