### ISSUE TITLE
The text associated with session management requirements should also refer the reader 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1428]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: Section 4.3 (Reauthentication and Session Requirements in Federated Environments),
Para 3

, 
 
**Comment (Include rationale for comment)**:  The text associated with session management requirements should also refer the reader
 
The text associated with session management requirements should also refer the reader to an agencies information security and privacy polices associated with the NIST SP 800-53 security and privacy controls.

The controls can impact reauthentication as well.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by dig-comments** [comment]
I'm more inclined to point to fed profiles, but before that happens we will discuss the issue.

**Comment by jimfenton** [comment]
Same resolution as #1414.
