### ISSUE TITLE
Attribute release notice and confirmation

### ISSUE THREAD

**Issue by sarahcec** [usnistgov/800-63-3#143]
Regarding these two sentences in 63C Section 6:

"The manner of presentation may impact who is in the best position to provide notice and obtain confirmation from the subscriber. Accordingly, the CSP, RP and any broker SHALL agree in advance on who will provide notice and obtain confirmation."

Wouldn't the CSP, as the entity who is releasing the information, always be the one to obtain confirmation from the subscriber?

Additionally, requiring that the parties agree in advance who is going to provide notice and obtain confirmation breaks dynamic registration. Even in situations of manual registration, it adds an unnecessary extra step.

I propose we strike both sentences.

**Comment by jricher** [comment]
Agree with this sentiment. Only the party holding the attributes, the CSP, is in a position to gather consent for their release. It makes no sense from a privacy or technology perspective for the RP to do this. 

Should we have extra language around CSP consent gathering? What we have elsewhere is probably sufficient.

**Comment by jricher** [comment]
Language will be changed to say that the party gathering the attribute SHALL obtain consent.
