### ISSUE TITLE
Please give authoritative references that stipulate why the collection of PII-related subscriber data must be minimized. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1431]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: Section 9.1 (Minimizing Tracking and Profiling),
Para 1

, 
 
**Comment (Include rationale for comment)**:  Please give authoritative references that stipulate why the collection of PII-related subscriber data must be minimized.
 
Examples include:
1) OMB Directives
2) NIST SP 800-53r4
3) Legislation: 45 C.F.R. §164.512(i).

Please cite the appropriate controls from the UL and DM families of controls from NIST SP 800-53r4.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jamiedanker-nppd** [comment]
Explore weaving in 800-53 however given 800-53r4 control families will be changing in r5 references to specific control families may not be advisable.

**Comment by jimfenton** [comment]
Same resolution as #1342.
