### ISSUE TITLE
The current requirements for “Strong” level of evidence require that they be verified against the issuing source. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1432]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 5.2.2.1, Methods to perform Identity Evidence Validation, 
 
**Comment (Include rationale for comment)**:  The current requirements for “Strong” level of evidence require that they be verified against the issuing source. 
 
Unfortunately, the capability does not currently exist to verify documentation directly against the issuing source, such as driver’s license or passports, at anywhere close to the coverage level required to support existing use cases. The current Driver’s Privacy Protection Act (DPPA) restricts what information state DMV’s are able to share therefore limiting identity provider’s ability to verify directly. There is also not a solution available to verify passport information directly against the country that issued the passport.
It is our recommendation that NIST re-evaluate this requirement since it would apparently prevent any solution from meeting these guidelines, hence creating an undue burden by eliminating the to provide remote identity proofing services.  Most document verification solutions are able to verify the validity of the document by using templates that determine if is structurally accurate (i.e. watermarks, fonts, etc.), but current technology does not extract the PII information from the document and then verify that directly against the issuing source. Our recommendation would be to allow identity providers the ability to verify data contained on the document against an authoritative source (such as a Credit Reporting Agency) that is able to verify this information in records.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #582
