### ISSUE TITLE
Size and complexity of the memorized secret blacklist

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1433]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.1.1, 
 
**Comment (Include rationale for comment)**:  Blacklist: The size and complexity of the blacklist is not defined here. i.e. RACF blacklist is only 128 words
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The guideline was intentionally non-prescriptive on the blacklist size and composition. The implementation guide may give some examples.
