### ISSUE TITLE
“KBV SHALL NOT be used …” 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1434]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.3.2, 
 
**Comment (Include rationale for comment)**:  “KBV SHALL NOT be used …” 

 
Need to clarify the term “relationship”  - if the agency is the CSP and relies on a third party vender to perform the KBV as part of the Remote Identity Proofing, will the agency be required to maintain a relationship with all authoritative resources used by the third party?

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This is actually in -63A.

**Comment by paul-grassi** [comment]
We've defined what a good data source is, so this can be removed.
