### ISSUE TITLE
"“The CSP shall only use information that is expected to be known only to the applicant and the source…” 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1435]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.3.2, 
 
**Comment (Include rationale for comment)**:  "“The CSP shall only use information that is expected to be known only to the applicant and the source…” 
 
Need to clarify “the source” – most current information used to perform KBV can be obtained by a fee or public domain. This will essentially shut down current approach to remote identity proofing" 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This is actually in -63A.
