### ISSUE TITLE
Special Publication 800-63-3; Introduction 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1436]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: section 2, 
 
**Comment (Include rationale for comment)**:  Special Publication 800-63-3; Introduction
 
Spell out CSP as this is first use.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE with April 1 update to -3.
