### ISSUE TITLE
For example, if an assertion is presented in the back-channel federation model (described in Section 6.1), additional controls MAY be placed on the transaction 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1439]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 5.1.1, 
 
**Comment (Include rationale for comment)**:  For example, if an assertion is presented in the back-channel federation model (described in Section 6.1), additional controls MAY be placed on the transaction
 
(such as identification of the RP and assertion injection protections) that help to further protect the RP from fraudulent activity.

I am little confused on how identification of the RP can help to further protect the RP. Especially when an attacker is able to capture or manufacture a valid assertion and that attacker is able to successfully present that assertion or reference to the RP. How identification of RP helps in this scenario? May be RPs call back IdP to authenticate and pull the assertion from IdP?

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
In the back channel model, the RP calls the IdP directly to get the assertion, which means an attacker cannot present the assertion to the RP unless it can successfully impersonate the IdP to the RP. If the RP is identified in this call, the IdP won't send the assertion to an attacker.
