### ISSUE TITLE
SAFE BioPharma - Reference middleware 

### ISSUE THREAD

**Issue by paul-grassi** [usnistgov/800-63-3#145]
**Organization**:

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63C

**Reference (Include section and paragraph number)**:
Section 4

**Comment (Include rationale for comment)**:
Section 4 ought to include a reference to middleware services as a category within the generic federation model since these services also engage in data transactions with the other parties described

**Suggested Change**:

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
Middleware services are treated, for the purposes of the federation protocol, as a component of the RP or CSP itself. If a party wishes to outsource some aspect of this functionality to a middleware service, then that service is also bound by the same requirements as if it had been in-house.
