### ISSUE TITLE
SAFE BioPharma - Remove credential mgmt

### ISSUE THREAD

**Issue by paul-grassi** [usnistgov/800-63-3#146]
**Organization**:2

**Type**:

**Document (63-3, 63A, 63B, or 63C)**:63C

**Reference (Include section and paragraph number)**: Section 5

**Comment (Include rationale for comment)**:
Section 5, Assertion Strength, addresses credential management, not about federation and does not belong in 63-3C 

**Suggested Change**:

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
The assertion strength section is about how the information is carried across the network in a federated protocol, and not about how the primary credential itself is managed or verified. This belongs in `C` with other federation information.
