### ISSUE TITLE
SAFE BioPharma - Crypto Requirements

### ISSUE THREAD

**Issue by paul-grassi** [usnistgov/800-63-3#147]
**Organization**:2

**Type**:

**Document (63-3, 63A, 63B, or 63C)**:63C

**Reference (Include section and paragraph number)**: Section 5.2.2

**Comment (Include rationale for comment)**:
Section 5.2.2 needs to address requirements for the cryptographic services that MAY sign non-X.509 assertions. In general, the cryptographic key must be at the same or greater LOA than the assertion being signed

**Suggested Change**:

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
The section already requires the use of approved crypto.
