### ISSUE TITLE
SAFE BioPharma - Add encryption requirements

### ISSUE THREAD

**Issue by paul-grassi** [usnistgov/800-63-3#148]
**Organization**:2

**Type**:

**Document (63-3, 63A, 63B, or 63C)**:63C

**Reference (Include section and paragraph number)**: Section 5.3.2

**Comment (Include rationale for comment)**:
Section 5.3.2 - There needs to be a requirement for an encryption certificate including current best practice for SSL/TLS, FIPS 140-2 level HSM, CA/B Forum guidelines, etc. This is much too bare-bones

**Suggested Change**:

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
The section already requires the use of approved crypto.
