### ISSUE TITLE
SAFE BioPharma - Usability Section

### ISSUE THREAD

**Issue by paul-grassi** [usnistgov/800-63-3#149]
**Organization**:2

**Type**:

**Document (63-3, 63A, 63B, or 63C)**:63C

**Reference (Include section and paragraph number)**:Section 9

**Comment (Include rationale for comment)**:
Section 9 provides no useful information 

**Suggested Change**:

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
It's a placeholder.
