### ISSUE TITLE
The number of KBV questions needs to be increased to a minimum of 5 questions

### ISSUE THREAD

**Issue by SES-SSE** [usnistgov/800-63-3#15]
**Organization**: 1

**Reference (Include section and paragraph number)**:

5.3.2. Knowledge Based Verification Requirements

**Comment (Include rationale for comment)**:

The bullet “A CSP SHALL require a minimum of four (4) KBV questions each requiring a correct answer to successfully complete the KBV step” of four questions is too low. 
Allowing too low a number of possible questions increases the success against attacking the identity proofing capability of the system, not a given individual, when performing identity proofing. For example, the odds of guessing the correct answers to all five questions is 0.032% (0.2^5) when using 5 answers per question.  A system that has 100 million users and requires 5 questions with five answers per question to be answered correctly has the potential of 32,000 fraudulent registrations. 

A system that has 100 million users and requires 4 questions with five answers per question to be answered correctly has the potential of 160,000 fraudulent registrations. These numbers do not take into account that each account can be attacked twice or the possibility that a fraudster may already know some of the answers to questions. 

Random guessing for four questions with four answers per question could lead to 390,625 fraudulent registrations.  The odds of guessing the correct answers to all four questions correctly is 0.390625% or of (.25^4).  Fraudulent registration is based on a user base of 100 million users and only having the questions asked once—not twice.  Using the above for 100,000 user system, divide fraudulent registration numbers by 1,000.

**Suggested Change**:

Change the requirements for questions to “A CSP SHALL require a minimum of five (5) KBV questions each requiring a correct answer to successfully complete the KBV step.”

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by mleibner** [comment]
This may be a duplicate/clarification of #14

**Comment by SES-SSE** [comment]
They’re actually two different issues.

Currently, there is no requirement for a minimum number of answers per question.  A question could have two answers or more.  14 seeks to address this issue by stating 5 possible answers per question shall be provided.

With respect to 15, currently there is a minimum of 4 questions that are required.  IMO, the number of questions should be 5 questions. 

So 15 seeks to increase the number of questions from 4 to 5 and 14 seeks to specify a specific number of answers per question. Both requirements have an impact on the probability of guessing random answers.

Hope that clarifies how the requirements are distinct.

**Comment by paul-grassi** [comment]
Successfully completing KBV does not mean identity verification is complete.  The CSP must perform other verification steps in addition to KBV.  Therefore we feel a MINIMUM of 4 is sufficient with the additional steps.
