### ISSUE TITLE
"to meet the requirements for each IAL" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1512]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5, 
 
**Comment (Include rationale for comment)**:  "to meet the requirements for each IAL"
 
this statement is not upheld by this section.  Applicability to specific IALs ocurs only once - what is one to make of the other (substantial in volume) material?  Does it appky to all IALs, IAL1 included or only if referenced from §4?

**Suggested Change**: A much clearer and unambiguous statement as to how the contents of this section relates to IALs is required.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Not a duplicate, but will be addressed by #1513
