### ISSUE TITLE
"This section lists the steps a CSP SHALL follow" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1513]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5, 5.1, 
 
**Comment (Include rationale for comment)**:  "This section lists the steps a CSP SHALL follow"
 
It is difficult to see why 'SHALL' is expressed such - there is no normative requirement associated directly with it.  And, it is hardly a true statement when one considers that, e.g., §5.1, has no mandatory requirements, hence can be ignored completely (in terms of an implementation).
The particularly difficult point here is that it makes §4.5.1 very weak, despite its bold 'SHALL'.  There is effectively nothing against which to gauge a CSP's conformance.

**Suggested Change**: It ois frankly difficuklt to offer a change other than those already suggested:
Firstly, place all these requirements in a single place (there is nothing in §5.1 that could not sit within §4.4.1.1 and §4.5.1);
Secondly, make some assertive requjirements, or accept that CSPs will opt for the simplest solution.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is a good catch.  Will remove SHALL in Section 5 since 4 is the roll-up of requirements. Not going to restructure document.
