### ISSUE TITLE
The tables list: Unacceptable | Weak | Fair | Strong | Superior 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1515]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Tables 5.1, 5.2, 5.3, 
 
**Comment (Include rationale for comment)**:  The tables list: Unacceptable | Weak | Fair | Strong | Superior
 
The normative §4 refers only to Adequate | Strong | Superior. 'Fair' is not used except a single non-normative reference which could be easily re-worded.  Neither 'Unacceptable' nor 'Weak' are used in these contexts at all

**Suggested Change**: Align the table to the terms used (presumably fair = adequate?) and define only those terms used, i.e. remove  'Unacceptable' and 'Weak' .
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Error in adequate/fair resolved in #518.  We understand those strengths aren't used but do not want to delete the descriptions. They may one day be used maybe help shortcut the types of evidence that are not allowed.
