### ISSUE TITLE
"contains a photograph, image, or biometric" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1517]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Table 5.1, Fair
 
**Comment (Include rationale for comment)**:  "contains a photograph, image, or biometric"
 
How is an image not a photograph?  How are either of these not a 'biometric' (a word defined in a manner which would include either, and for which either is given as an example elsewhere in the doc).

**Suggested Change**: These terms are not sufficiently carefully and consistently used for these tables to be reliably definitive and meaningful and need careful review to enaure they are described and employed consistently and meaningfully
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will clean language, but it is just looking for one.  So a picture or perhaps a fingerprint.
