### ISSUE TITLE
Entry requires a biometric or a photograph/image 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1518]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Table 5.1, Superior'
 
**Comment (Include rationale for comment)**:  Entry requires a biometric or a photograph/image
 
Noting the comment above, this entry requires a biometric or a photograph/image.  The usage just doesn't bear up to scrutiny and does not contribute to making a 'Superior' piece of evidence any better than a 'Strong' one.

**Suggested Change**: These terms are not sufficiently carefully and consistently used for these tables to be reliably definitive and meaningful and need careful review to enaure they are described and employed consistently and meaningfully
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This are AND'd, so it's a photo, plus a biometric.  Think PIV - Face, iris, and finger.  ePassport...
