### ISSUE TITLE
"proprietary cryptographic methods, or both" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1519]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Table 5.1, Superior'
 
**Comment (Include rationale for comment)**:  "proprietary cryptographic methods, or both"
 
There must be an 'or missing after 'Proprietory'

**Suggested Change**: "proprietary or cryptographic methods, or both"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Duplicate.  Will be fixed via #640
