### ISSUE TITLE
is use of 'verified' deliberate or just a casual variance on 'genuine'? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1521]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Table 5.2, Fair
 
**Comment (Include rationale for comment)**:  is use of 'verified' deliberate or just a casual variance on 'genuine'?
 
It seems to be the only difference, apart from order of words, to the properties cited for 'strong', which means that (referring to the previous analysis of the use of these terms), by definition ADEQUATE = STRONG.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Comment reference could not be found
