### ISSUE TITLE
What is 'an identity proofing process' 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1522]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Table 5.2, Fair
 
**Comment (Include rationale for comment)**:  What is 'an identity proofing process'
 
is issuing a birth certificate (which attributes identity) such a case?  Such a certificate is not literally placed into the possession of its subject, but to its parents or guardian.  This is actually a case of one or two referees acting literally 'in loco parantis'. 

**Suggested Change**: Qualifiy to allow referees to act on behalf of the subject, in this case, but also consider the wider implicartions of the phrase in this document - does it imply a process which meets the requirements of this SP? 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
The document already allows for referees.

While we understand the point about a birth certificate, this open language allows the RP to determine what evidence they prefer by evaluating the proofing process themselves for the evidence they may collect.  So in this case, it is extremely doubtful that a high-risk service provider would allow a birth certificate from an 30 year old as anywhere near acceptable.
