### ISSUE TITLE
Tables carry many internal inconsistencies and the terms used are not sufficiently distinct to allow a real sense of separation between such labels 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1523]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Tables 5.1, 5.2, 5.3, 
 
**Comment (Include rationale for comment)**:  Tables carry many internal inconsistencies and the terms used are not sufficiently distinct to allow a real sense of separation between such labels
 
These tables carry many internal inconsistencies and the terms used are not sufficiently distinct to allow a real sense of separation between such labesl as Fair/Adequate | Strong | Superior

**Suggested Change**: There needs to be a specific review of the concepts which these tables try to convey.  They need to be rationalised and they need to be expressed as part of the id proofing process, not just as a separate narrative.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Doesn't hurt to ensure consistency, but there is certainly an improvement in strength as you move thru the levels.

**Comment by paul-grassi** [comment]
Without specific references to actual inconsistencies, we believe these tables adequately define increasing requirements for evidence types as well as validation and verification techniques.
