### ISSUE TITLE
a) Source verification for Strong evidence. The market simply does not support this today. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1524]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Table 5.2, 
 
**Comment (Include rationale for comment)**:  a) Source verification for Strong evidence. The market simply does not support this today. 
 
a) Source verification for Strong evidence. The market simply does not support this today. 

**Suggested Change**: That step should be preceded by "SHOULD" instead of SHALL.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Duplicate with #582
