### ISSUE TITLE
The document should include a concept of tenure when it comes to identity proofing. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1525]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Table 5.2, 
 
**Comment (Include rationale for comment)**:  The document should include a concept of tenure when it comes to identity proofing.
 
The document focuses on a single event to establish trust in an identity while one of the benefits of a federated approach to identity is that identity verification may be performed in incremental steps over time -- often in industries that are not the public sector -- where a validated, unique identity is verified in steps as more and more observation points, namely the tenure, volume, value, and frequency of transactions, that are collected over a period of time without any reports of fraud. 

For example, 5.2.1.1 references Customer Identification Program guidelines as an example of an institution capable of providing Strong evidence. What the section fails to capture is that a credential issued the previous day over remote channels for a new customer is far less trusted - in this case far less verified - than a credential issued to a customer who has tenure at the financial institution for, say, ten plus years with thousands of transactions and no reports of fraud. Both customers may have gone through the same identity proofing process at the bank, but it is clear that the trust in the claimed identity is far greater for the latter customer with tenure versus the former customer who is newly onboarded. 

The document should include a concept of tenure when it comes to identity proofing. There are two changes recommended:

**Suggested Change**: Two changes are recommen ded:
a) An IAL 2 credential should be able to mature into an IAL 3 credential if the credential meets some criteria for tenure and value of transactions. In fact, this is they way that the credit system works in America - if an individual is trustworthy at a less risky level, then they may be incrementally "stepped up" and the organization is comfortable issuing a higher line of credit because they have mitigated the risk.

b) If financial institution credentials are used by CSPs for identity proofing -- essentially a federation within a federated CSP -- then the notion of tenure becomes critically important as some FI credentials my be Superior, some Strong, and some Fair depending on the tenure of the customer in question. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Finalizing -3 doesn't mean we won't rev 800-63 in another 10 years.  We have an active pipeline of research, to include tenure, so we love this comment and look forward to engaging with id.me and the community writ large to determine effective proofing requirements that take tenure (among other things) into consideration.
