### ISSUE TITLE
While recognising the need for these provisions, there are no explicit, genuinelty measurable criteria 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1526]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.3.4, 
 
**Comment (Include rationale for comment)**:  While recognising the need for these provisions, there are no explicit, genuinelty measurable criteria
 
Noting that the CSP is obliged to draw up policy and procedures, there is nonetheless no requirement which is measurable unless it is strictly a defined entitlement provided-for by law.
E.g. nothing to require identity proofing of the referee to at least the same level as that required for the applicable credential sought for the applicant;  even having proofed the referee, what verification of their standing through a public register of such, having potentially the same concerns as to 'issuing authority'?  Furthermore, the phrase "or some other form of trained and approved or certified individuals" leaves things very open, even though the "approved or certified" requirement implies some kind of verification of that qualification - but from whom?  There is nonetheless the high likelihood of very different levels of rigour being applied in response to this clause, and therefore a high degree of inconsistency in assurability of credentials issued in this way - this requirement actually introduces a potentiall weakness into the CSP which very deliberately chooses to be minimally conformant.

**Suggested Change**: State measurable criteria which as a minimum require:
proofing of the referee's id to at least the same level of rigour as required for the applicable IAL of the credential being sought  
PLUS
verification of the claimed qualification from the issuing source.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Without recognizing this situation can occur, agencies would be unaware of what is allowed.  Therefore, we acknowledge this situation exists in the wild, but the agency is best equipped to draw procedures for any population they serve.
