### ISSUE TITLE
The following compound adjectives require hyphenation: appropriately tailored 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1527]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: , 
 
**Comment (Include rationale for comment)**:  The following compound adjectives require hyphenation: appropriately tailored

 

**Suggested Change**: hyphenate to improve readability
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Fixed by #1805.
