### ISSUE TITLE
The use of bullet lists does not facilitate application of this SP - indexed lists should be used instead. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1529]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: General, 
 
**Comment (Include rationale for comment)**:  The use of bullet lists does not faciliatte application of this SP  -  indexed lists should be used instead.
 
This suggestion has been made before and overlooked, yet it is difficult to see any solid argument against adopting such a change.  How can there be a downside?.

Using indexed lists would give each requirement a distinct and easily-constructed reference.  This will facilitate (at least) implementors, wishing to ensure their solution meets all requirements;  internal auditors and external auditors who have the responsibility to determine the CSP's conformance with these requirements; and anyone else (e.g. editors and reviewers) needing to easily and accurately reference specific clauses.  Identifying requirements as (e.g.) "section 4.5.6, third primary bullet, fifth secondary bullet" is just utterly clumsy and difficult to both write, record and read.  It is also far harder to locate text from such a reference than a numeric sequence.  PLEASE don't oblige us do this!  Consider this as being applicable to all of each part of 800-63-3.
Note that a numbering model based on alpha, Arabic no., Roman no., UPPER ALPHA (i.e. 'a) 1) i) A)' ) would distinguish between 1.2.3.4.5 and 1.2.3.4 5), e.g. - the proposed model would make the second instance 1.2.3.4 a).  This serves to make the distinction from the section reference more explicit and less likely to be confused. 

**Suggested Change**: Adopt a numbering sequence  'a) 1) i) A)' in place of all bulleted lists within the document.

Note that if there are two lists within a single section, they must run sequentially to avoid having two identical references.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The use of Markdown for this review process imposes some formatting limitations, and this is one of them. We will consider better numbering formats for the final publication.
