### ISSUE TITLE
Need there be a specific reference to "digital government services" (that has not been the explicit context thus far, and in a sense limits wider 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1534]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 2, 1
 
**Comment (Include rationale for comment)**:  Need there be a specific reference to "digital government services" (that has not been the explicit context thus far, and in a sense limits wider use of the SP)?
 

**Suggested Change**: Either remove 'government' or state 'government (or other)'
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This is informative introductory content; it does not need to be more specific.
