### ISSUE TITLE
The declaration that "This document provides recommendations" is again incongruous with other statements in the SP 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1536]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 2, 3
 
**Comment (Include rationale for comment)**:  The declaration that "This document provides recommendations" is again incongruous with other statements in the SP
 

**Suggested Change**: "This document provides requirements for accepotable types of authentication processes, ...
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The terminology of recommendations vs. requirements maintains consistency with earlier editions of this document and other NIST documents.
