### ISSUE TITLE
"provides some assurance" is very vague 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1537]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 2, "AAL 1"
 
**Comment (Include rationale for comment)**:  "provides some assurance" is very vague
 
The magnitude associated with 'some' is open to interpretation.  Since AAL2 and 3 are 'high' and 'very high', respectively. It would be more obvious to use 'low'.

**Suggested Change**: Replace 'some' with 'low'
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
See #1222.
