### ISSUE TITLE
"AAL3 is like AAL2" is not a very clear expression 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1538]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 2, "AAL 3"
 
**Comment (Include rationale for comment)**:  "AAL3 is like AAL2" is not a very clear expression
 
the completion of this sentence suggests that the only difference is the requirement for a "hard" authenticator, yet the wording between this and AAL 2 is not the same and could suggest other differences

**Suggested Change**: If thnis is indeed the only difference, state so more positively 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
It is not the only difference; other requirements like different reauthentication timeouts also apply.

The "is like AAL2" phrase does not add any particular value and will be removed.
