### ISSUE TITLE
Not sure this is really helpful - this kind of overview isn't really informative … 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1539]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 2, Table
 
**Comment (Include rationale for comment)**:  Not sure this is really helpful - this kind of overview isn't really informative …
 
… however, the statement preceding each section is 

**Suggested Change**: delete table 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The point of the table is to guide readers to the sections of the document that are normative. In many sections of the document, we summarize information that is found elsewhere and make that summary informative, to avoid uncertainty if there is a conflict between the summary and the detailed information.
