### ISSUE TITLE
Since some terms are replicated in the -63 family, why not collect all definitions and terms in the 'parent' doc 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1540]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 3, 
 
**Comment (Include rationale for comment)**:  Since some terms are replicated in the -63 family, why not collect all definitions and terms in the  'parent' doc
 
Unlike ISO, NIST doesn't charge, therefore encouraging use of the full 800-63 suite

**Suggested Change**: move to -63<null>
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Definitions are moving to an appendix of -63-3; see #1661
