### ISSUE TITLE
Biometrics are an Authenticaton Factor as defined earlier in the document. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1541]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 3, 
 
**Comment (Include rationale for comment)**:  Biometrics are an Authenticaton Factor as defined earlier in the document. 
 
As defined, the document suggests that the Authenticator Factor of "Something You Are" is in fact a subset of "Something You Have" which would mean that there are really only two Authenticaton Factors. While not ideal, server side biometrics may be helpful and at times the only option, for individuals to utilize MFA and/or to interact with a channel -- such as a call center with IVR -- where server side biometrics would form the most usable and secure solution. 

Limiting Biometrics as an Authentication Factor will greatly inhibit innovation in the market. If innovation is inhibited, then access rates, particularly for those Americans without smartphones, will be lower than they might be if CSPs are able to demonstrate clever, secure pathways for demographics that have limited resources or history in records for proofing and authentication. 

**Suggested Change**: Delete entire sentence under biometrics starting with "In this document"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by enewt** [comment]
The document does recognize biometrics as an authentication factor, with certain restrictions that are summarized in the definition.
