### ISSUE TITLE
Defined terms not that obvious 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1542]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 3, 
 
**Comment (Include rationale for comment)**:  Defined terms not that obvious
 

**Suggested Change**: emphasis by using bold
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Will re-examine at final publication.
