### ISSUE TITLE
Subscriber 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1543]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 3, 
 
**Comment (Include rationale for comment)**:  Subscriber
 
DIS29003 uses the term 'subject' in this context.  The EN 319 series do likewise and additionally use 'subscriber' to be a party which applies for / authorizes the IdPV process (application) for a given subject OR subjects (i.e. individual applicants, in personal IdPV).  E.g., a corporate entity (or perhqaps an agency) may act as a Subscriber for the provision of credentials to its employees (the Context, in 29003 parlance), each of whom would be a Subject.  An individual applicant would meet the definition of both Subscriber and Subject.  
It was stated by LaChelle LeVan at the EU/US meeting in DC, 2017-03-08, that (she thought that) NIST was wanting to align with international standards.  Other indicated a need to harmonise closely.  Adopting this change would be a small effort in that directikon and would have no impact on  comprehension of this SP, while providing for at least one common term.

**Suggested Change**: At least,  use  'Subject' in this document in lieu of 'Subscriber' to maintain alignment with  other global / widely-recognized stds - it makes no actual difference internally to 800-63-3, but it would ease alignment with other standards in this space (and also with such frameworks as Kantara, tScheme, ...).  If there is no reason to use 'Subscriber' in the sense in which these other stds use it, then it need not be defined, but to do so would reserve the definition.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
We will change to _subject_ to align with other standards.

@kboeckl Assigning you as well to update graphic in -3.

**Comment by jimfenton** [comment]
Reconsidering in the context of some other comments being adjudicated. We are using "subject" as the union of subscriber, applicant, and claimant, and changing _subscriber_ to _subject_ would introduce other ambiguities. We acknowledge that _subject_ is more commonly used, and will consider a terminology change in the future.
