### ISSUE TITLE
"AAL1 permits the use of any of the following authenticator types, which are defined in Section 5" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1545]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.1.1, 1
 
**Comment (Include rationale for comment)**:  "AAL1 permits the use of any of the following authenticator types, which are defined in Section 5"
 
… is not a very pointed 'normative' statement, and in fact could be better-exoressed as …

**Suggested Change**: "AAL1 authentication shall be effected by any one of the following authenticator types, which are further defined in Section 5"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
We'll go with a simpler wording that is also more clearly normative.
