### ISSUE TITLE
Approved cryptography at AAL1

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1546]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.1.2, 1
 
**Comment (Include rationale for comment)**:  Why is it that "Cryptographic authenticators used at AAL1 SHALL ue approved cryptography"
 
Given that there is only low assurance at AAL1, why enforce this upon service providers? Anything worthy of any security will require a higher AAL.

**Suggested Change**: Remove this requirement and any  related implications at AAL1.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This also conflicts with the introductory text that says, "Approved cryptographic techniques are required at AAL2 and above." There is also an indirect requirement in the use of an authenticated protected channel, which as defined also requires approved cryptography.

**Comment by jimfenton** [comment]
Use of approved cryptography (i.e., vetted algorithms, but not necessarily validation) will be required at AAL1 as well; the statement in the introduction is incorrect.
