### ISSUE TITLE
"SHOULD decline to operate" - 'decline' seems a strage usage - implies a decision 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1547]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.1.2, 1
 
**Comment (Include rationale for comment)**:  "SHOULD decline to operate" - 'decline' seems a strage usage - implies a decision
 

**Suggested Change**: re-phrase as "SHOULD not complete the operation"
(This comment applies throughout and further instances are not specifically called-out.)
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Also in section 4.2.2.
