### ISSUE TITLE
"equivalent industry standard" could be hard to define 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1549]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.1.4,
4.2.4,
4.3.4, 1
 
**Comment (Include rationale for comment)**:  "equivalent industry standard" could be hard to define
 
in terms of how equivalence was determined.  It would be helpful if such standards/controls were explicitly referenced.

**Suggested Change**: Provide reference to such standards/controls in an Annex, either as an explicit list or by reference to those identified in Annexes of SP 800-53.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
It isn't possible to cite all equivalent industry standards because many of them haven't been written yet.
