### ISSUE TITLE
This para is not expressed using concise normative terms. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1550]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.2, 1
 
**Comment (Include rationale for comment)**:  This para is not expressed using concise normative terms.
 
First sentence is a repeat of an informative description already stated in §2;
No normative terms are employed;
The last part of sent.3 "and above" is inappropriate - this clause (4.2) addresses AAL2 exclusively.

**Suggested Change**: Re-phrase as"The Subject SHALL be required to prove possession and control of two different authentication factors.  This SHALL be accomplished using a secure authentication protocol. Approved cryptographic techniques SHALL be used."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The normative authentication requirements are expressed later in the section so a somewhat less formal style was adopted for this introductory paragraph.

This applies to the introductory paragraphs of 4.1 and 4.3 as well.
