### ISSUE TITLE
This para is not expressed using concise normative terms. 'At AAL2' is redundant (§4.2 is specifically about AAL2) 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1551]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.2.1, 1
 
**Comment (Include rationale for comment)**:  This para is not expressed using concise normative terms.  'At AAL2' is redundant (§4.2 is specifically about AAL2)
 

**Suggested Change**: Rephrase as "Either a multifactor
authenticator or a combination of two single-factor
authenticators SHALL be employed."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
There is no harm in restating the context as AAL2, but this section should use normative language.

**Comment by jimfenton** [comment]
Fixed via #1545.
