### ISSUE TITLE
"used at AAL2" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1553]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.2.2, 1
 
**Comment (Include rationale for comment)**:  "used at AAL2"
 

**Suggested Change**: Redundant - this is what §4.2 is about.  This occurs frequently and all such instances can be removed.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
There is no harm in restating the context.
