### ISSUE TITLE
§4.2 and §4.2.2 both state "Approved cryptographic techniques". The latter then further states "Authenticators ... SHALL be validated to ... [FIPS 140] Level 1". 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1554]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.2.2, 1
 
**Comment (Include rationale for comment)**:  §4.2 and §4.2.2  both state "Approved cryptographic techniques".  The latter then further states "Authenticators ... SHALL be validated to ... [FIPS 140] Level 1".
 
What other 'approved techniques' are there?
If none, then why these two statements - surely one (the least specific) is redundant?
If others, why not include them?

**Suggested Change**: Simplify the text by making one definitive normative statement.
(This comment applies elsewhere and the same resolution is suggested.)
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
'Approved' is defined in Section 3.

**Comment by jimfenton** [comment]
_Approved_ refers to the choice of algorithms, etc. The FIPS 140 requirements require validation, but do not always apply to all parties equally (e.g., only agency-operated CSPs.). Both are required.
