### ISSUE TITLE
This requirement makes sense but if allowed to be not fulfilled (i.e. not mandated), it likely will not be… 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1555]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.2.2, 4
 
**Comment (Include rationale for comment)**:  This requirement makes sense but if allowed to be not fulfilled (i.e. not mandated), it likely will not be…
 
Since it offers a chance to reduce investment without compromising conformity

**Suggested Change**: Either remove or make enforceable
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by enewt** [comment]
Will change this sentence to clarify the intent of the "should":
When a biometric factor is used in authentication at AAL2, the performance requirements stated in Section 5.2.3 SHALL be met, and the verifier SHOULD make a determination that the biometric sensor and subsequent processing meets these requirements.
