### ISSUE TITLE
The use of 'CSP' is noted. Is this what is elsewhere referred-to as a 'digital service'? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1556]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.2.3, 1
 
**Comment (Include rationale for comment)**:  The use of 'CSP' is noted.  Is this what is elsewhere referred-to as a 'digital service'?
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
See #1071.
