### ISSUE TITLE
Note qualifying "Informative" status of this section … 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1558]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.5, 1
 
**Comment (Include rationale for comment)**:  Note qualifying "Informative" status of this section …
 
Contradicts the statement at the start of §4 that the (implicitly whole) section is normative.
Further, given the declared superficiality of the content of the table and its omission and lack of comprehensiveness, it could be argued that the table may mislead, despite the disclaimer.

**Suggested Change**: Remove table, or at least relegate to an informative annex.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This table is informative in order not to create a conflict if there is a difference between it and the normative content earlier in the section. The informative nature of this specific section takes precedence over the broader normative nature of Section 4.
