### ISSUE TITLE
"SHOULD … be up to 64 characters or more" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1560]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.1.2, 1
 
**Comment (Include rationale for comment)**:  "SHOULD … be up to 64 characters or more"
 
A min length has been asserted but this is not a very hard requirement, and is essentially saying either 'there is no limit' or 'set your own limit'.  It would achieve the same practical end if this was stated normatively, at least requiring CSPs to think about it psitively.

**Suggested Change**: Replace with "CSPs SHALL determine themselves the  upper limit on the length of user-chosen memorized secrets."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The suggested text does not give any hint of what a desirable maximum length is, while the current text does. CSPs are likely to choose maxima that are far too short in the absence of this information.
