### ISSUE TITLE
How can a verifier have any control over the length of memorized secrets - are these not established at the time of identity proofing? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1561]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.1.2, 1 - 6 inc., 8
 
**Comment (Include rationale for comment)**:  How can a verifier have any control over the length of memorized secrets - are these not established at the time of identity proofing?
 
All of these limitations and qualifiers should be included in 63A to govern the creation of memorized secrets at the time of enrolment.  63B is not the place to do this.
This also brings to light another point:  the scope of 800-63 is digital identities.  It does not address the whole credential management life-cycle (nor should it), but requirements on password format/strength is one necessity to provide protections against credential mis-use.  The question of pwd strength also arises when Subjects are allowed to change their passwords or have to replace second/multi-factor mechanisms.  There is therefore need of a discretely-packaged set of password requirements which can be referenced from a number of sources, perhaps not necessarily from within this SP.  These however must be addressed to the CSP in general, not the verifier specifically.

**Suggested Change**: Move to 63A, either as a separate section or separate Annex, taking into account other comments regarding this text.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Creation of memorized secrets is not part of identity proofing, but is part of the enrollment of authenticators that is covered in -63B section 6.1. Subscribers will sometimes want to change their memorized secrets, and this does not require that the identity proofing process be repeated.

Requirements for memorized secrets, the same as other authenticators, are properly in-scope for -63B.
