### ISSUE TITLE
The subscriber is not under the direct scope of these requirements … 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1563]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.2.1, 2
 
**Comment (Include rationale for comment)**:  The subscriber is not under the direct scope of these requirements …
 
… so they should not be addressing the Subject/subscriber directly.  At the most, it should be revised to reflect upon the CSP, but essentially it would be saying that the CSP MAY give this advice to the Subject … Does this even need to be said at all?  

**Suggested Change**: Delete the whole para/sentence.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The advice is useful, and rather than cluttering the text with "The CSP MAY advise the subscriber that..." it is clear from the current text what occurs.
