### ISSUE TITLE
Look-up secrets: re-enter same or next secret?

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1564]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.2.1, 3
 
**Comment (Include rationale for comment)**:  It is not clear whether the same look-up secret is to be re-entered (?hence the throttling) or whether a new/the next secret should be entered.
 

**Suggested Change**: Clarify
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
5.1.2.1 paragraph 1 says, "A given secret from an authenticator SHALL be used successfully only once", therefore the look-up secret is advanced to the next secret only on a successful authentication. Were this not the case, an attacker could very simply mount a denial-of-service attack on the subscriber by exhausting all of the look-up secrets that have been issued.
