### ISSUE TITLE
Possession of out-of-band devices

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1565]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.3, 
 
**Comment (Include rationale for comment)**:  The notion that an out of band device must be possessed by the subscriber is unncessarily limiting.
 
For example, an employer may have a trusted device that is used to assist with MFA for local access, a use case referenced earlier in this document. 

Devices controlled by subscribers, namely smartphone and tablets, are routinely shared between multiple individuals. The notion that these devices are acceptable but that devices owned by the IDP or an RP for use on behalf of a user population is not intuitive.

**Suggested Change**: If there are security or privacy criteria that are driving the limitation placed on ownership of out of band devices, then that criteria should be stated in the document. By taking an approach based on such criteria, a stakeholder may be able to demonstrate adherence to the stated criteria while taking an approach different from the prescriptive one named in the document. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The intent of the word _possession_ here is physical custody, as opposed to lawful ownership. This is clarified by the definition of _possession and control of an authenticator_ in the Definitions section.
