### ISSUE TITLE
"attempts an attacker can make" carries the presumption that a failed authentication is always the consequence of an attack … 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1566]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.3, 5
 
**Comment (Include rationale for comment)**:  "attempts an attacker can make" carries the presumption that a failed authentication is always the consequence of an attack …
 
… rather than the more probable forgetfulness or fumbling on the part of a legitimate Subject, so …

**Suggested Change**: … re-phrase as "attempts that can be made ...".
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This is a fine point, but correct. Also needs to be changed in 5.1.1.2, 5.1.2.2, 5.1.4.2, and 5.1.5.2.
