### ISSUE TITLE
adding the phrase "(112 bits as of the date of this publication)" … 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1567]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.4.1,
5.1.7.1,
5.1.8.1,
5.2.4,
5.2.7 (twice), 2
 
**Comment (Include rationale for comment)**:  adding the phrase "(112 bits as of the date of this publication)" …
 
… rather defeats the purpose of invoking the "latest revision of [SP 800131A]" …

**Suggested Change**: … so delete it.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The indicated text was intentionally included to give the reader a general idea of the requirement without sending them to another publication, but as indicated they should refer to SP 800-131A for an authoritative value.
