### ISSUE TITLE
use of a comma does not go well with the normative statements being made 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1568]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.4.1, 3, last line
 
**Comment (Include rationale for comment)**:  use of a comma does not go well with the normative statements being made
 

**Suggested Change**: use a semi-colon, at least, better make two separate sentences.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Section 5.1.4.1 paragraph 3 contains no commas.
