### ISSUE TITLE
'rate limiting vs 'throttling'

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1569]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.5.1, 3
 
**Comment (Include rationale for comment)**:  "rate limited" is used here for the first time - preceding references to this concept have used 'throttling/throttled'. 
 
There are two other instances of its use without qualification and two where it is followed by a parenthesised qualifier (i.e. "(throttling)", plus §5.2.2 is titled 'Rate Limiting (Throttling) ... so a mix of terms.

Better to stick to a single term within this document and note (in §5.2.2?) that the other term is also used in some circles.

**Suggested Change**: Use 'thottling' in all cases, and have just a note in §5.2.2 referring to the synonym. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
_Throttling_ seems to be a bit of jargon when used by itself, as compared with the more self-explanatory _rate limiting_ so the document will use the latter term more consistently.

**Comment by jimfenton** [comment]
Also being corrected in Appendix A.
