### ISSUE TITLE
"verifiers SHALL accept a given timebased OTP only once during the validity period" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1570]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.5.2, 3
 
**Comment (Include rationale for comment)**:  "verifiers SHALL accept a given timebased OTP only once during the validity period"
 
Could this not give rise to an OTP arriving from a MitM, being processed, and subsequently a second receipt, being the original.  Therefore the processing should be suspended and a second authn requested (or even not)?

**Suggested Change**: "verifiers SHALL cease processing if a given time-based OTP is received more than once during its validity period"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
It is likely that the first authentication decision will have been completed at the time the second OTP output is processed. However, there might be an opportunity to warn the second session that the OTP has already been used, and even possibly to signal the first session of possible fraud.
