### ISSUE TITLE
"overwritten in memory" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1571]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.9.1, 5
 
**Comment (Include rationale for comment)**:  "overwritten in memory"
 
Effective over-writing can require multiple writes.  Is it sufficient to apply just one? 

**Suggested Change**: State an explicit number of writes or an explicit value, to be written just once, e.g. "… overwritten in memory a single time with binary values '1' ..." 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The intent was not to require resistance to forensic attacks, other than as may be specified in FIPS 140 requirements.

**Comment by jimfenton** [comment]
See also #799
