### ISSUE TITLE
"While both types of keys SHALL …" is not very assertively stated and relies upon the preceding discursive text for context. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1572]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.9.2, 2
 
**Comment (Include rationale for comment)**:  "While both types of keys SHALL …" is not very assertively stated and relies upon the preceding discursive text for context.
 

**Suggested Change**: Make a new paragraph and re-state as:
"Symmetric and asymmetric cryptographic keys (depending on type used) SHALL ..."
and then replace the comma with a period, creating two sentences.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The requirement is clear as written.
