### ISSUE TITLE
"be strongly protected" means exactly what? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1573]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.9.2, 2
 
**Comment (Include rationale for comment)**:  "be strongly protected" means exactly what?
 
How does one know that an implementation is strong enough?  IF the SP actually required (instead of suggesting) conformity against the medium/high baseline (depending upon AAL - see comment re 4.2.4/4.3.4) then this requirement could be put in similar terms, e.g. ...

**Suggested Change**: "… be protected by controls which meet the applicable [SP800-53] baseline"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The word "strongly" will be removed.

**Comment by jimfenton** [comment]
Changed text is in 5.1.7.2 because of other edits.
