### ISSUE TITLE
"revoke or suspend the authenticator immediately upon notification from subscriber that" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1574]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.1, 2
 
**Comment (Include rationale for comment)**:  "revoke or suspend the authenticator immediately upon notification from subscriber that"
 
Might there be other sources, such as courts, which might also request or require revocation?

**Suggested Change**: Include provision for other parties with due rights to request revocatrion.  Apart from courts, this should also include the Subscriber, when that entity and the Subject are not one and the same.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The CSP is of course subject to other legal requirements, and nothing in the text precludes that.
