### ISSUE TITLE
The case made against biometrics here in order to tie biometrics to a device coud also be made against knowledge based authenticators. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1576]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.3, 1 & Bulleted list 
 
**Comment (Include rationale for comment)**:  The case made against biometrics here in order to tie biometrics to a device coud also be made against knowledge based authenticators.
 
If the fundamental question is: "how vulnerable is this authenticator type to a malicious actor?" then we would submit that all authenticator types are in fact subsets of Something You Have. Is this what NIST Is proposing? 

Each authenticator type has its own vulnerability. Memorized secrets may be stolen, devices may be lost or stolen, and biometrics may be defeated via impersonation and/or replay attacks. In this document, biometrics are unfairly singled out without comparing the relative strengths and weaknesses to the vulnerabilities of the other types of authenticators. As noted, malicious actors can download a photo of the subject, lift fingerprints, etc.; however, it is also well known that passwords are for sale on the dark web today due to breaches at Yahoo! (500M+ breached authenticators), LinkedIn (170+M authenticators) so the cost and effort to a malicious actor of defeating a memorized secret authenticator vice defeating a biometric authenticator with a liveness test may in fact be lower. 

**Suggested Change**: There should be a pathway for biometrics to be used in conjunction with something the user knows in order to esatblish MFA. A more robust examination of pros and cons of authenticator types - perhaps presented in a table - could show how MFA combinations between authenticator types mitigate the vulnerabilities of one particular authenticator type. Net-net, biometrics should not be tied to devices to serve as an authenticator. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
While all authenticators have various types of vulnerability, attackers can often gain access to a target's biometrics in ways that aren't possible with other authentication factors. While it might be possible to learn a target's memorized secret through a key logger, the target usually has choice about how and where that secret is disclosed. In contrast, biometrics are often disclosed through passive means. For this reason, additional precautions, including the requirement that a specific physical authenticator be used in the authentication, are imposed.
