### ISSUE TITLE
Note has no value 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1579]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.3, 7
 
**Comment (Include rationale for comment)**:  Note has no value
 
the standard should focus on normative requirements NOW.  This note is only of academic value

**Suggested Change**: Remove the entire note.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The note is helpful for those deploying biometric authentication to alert them to possible future requirements.
