### ISSUE TITLE
Does anyone analyze the practical implementation of these guidelines before writing them?

### ISSUE THREAD

**Issue by miketheitguy** [usnistgov/800-63-3#158]
**Organization**: 2

**Document (63-3, 63A, 63B, or 63C)**: 63-3

How does one get on the board of these documents to make these things less painful to implement in the real world? Does anyone who write this stuff even pay attention to what's going on in the industry? Or does everyone write these documents assuming RSA key fobs and/or PIV cards are the sole answer to all MFA problems across the industry?

LOA3/4 essentially almost mandates RSA key fobs or PIV cards. As nobody else in the industry provides an acceptable level of security. There are incredibly technical challenges when implementing MFA solutions, which right now no single solution provides the most comprehensive implementation of MFA to date (though phone-based OTPs and SMS-based codes tied to Federated Authentication is currently the most widely-deployed Internet-based MFA system).

Right now, within these documents, they basically say that to achieve the highest recommended security level you MUST implement hardware-based cryptographic systems. And then various agencies and IA professionals across the industry go "WELL, WE WANT TO BE AS SECURE AS POSSIBLE!" (BUT SMART CARDS ARE TOO MUCH TO IMPLEMENT!)

So how does one get on the group to write and discuss these documents? I currently work in the industry at a major organization affected by these documents and I'd like to have some input and discussion on the subject matter.

**Comment by paul-grassi** [comment]
In short, we are already allowing and supporting of what you request. Please see https://pages.nist.gov/800-63-3/ for instructions on how to participate.  In addition, you can view closed pull requests, and while minor in content updates, we are accepting pull requests from the public (an example is [here](https://github.com/usnistgov/800-63-3/pull/160), if the suggested changes align with our requirements and ultimate acceptance.

In addition, your analysis of AAL is partially correct.  However, a single-factor RSA OTP device is not allowed.  In addition, other options in the market exist that can presumably meet AAL3 requirements.  For example, a FIDO based UAF and U2F authenticator could meet AAL3 requirements depending on how it is deployed.

**Comment by miketheitguy** [comment]
I think some prudence on understanding how people read and understand these documents is incredibly important. There are a lot of IA individuals out there that simply have trouble reading and understanding the documentation, and a lot of business organizations that want to go as far as possible but don't know quite the right way to get there. The biggest example being when you describe hardware-based tokens. PIV cards are a PITA, despite HSPD-12, and a near impossible metric to meet in 100% of use cases. So the very next topic of discussion comes up is "RSA FOB". And in the interest of some level of uniformity, ease of use for the end user, companies start to say "RSA has everything we need for every application and use case because their marketing slides tell us!"--and then you get stuck with potentially implementing a highly attackable and laughable MFA security solution like "RSA on Windows Desktop".

So I think it's important to capture that somewhere in the documentation, because this is real, and this is how the industry (I work for a major federal contractor) generally takes these sorts of documents.

The initial argument that brought me here was a Slashdot article mentioning that SMS-based MFA is out, and it appears to be at all AALs, which blows my mind considering SMS-based MFA is widely deployed across the world today. And while it has severe security deficiencies, recommendations that don't include SMS-based and Software-based OTP systems (Google Authenticator) essentially means people just won't deploy MFA that end users are comfortable with.

**Comment by andrewhughes3000** [comment]
FYI - the Kantara Initiative hosts a fortnightly discussion call to help
the community work through some of the topics and help to shape up
commentary. Kantara is also preparing a set of group consensus comments on
the text which should be through the process in a few weeks.

Call details here:
https://kantarainitiative.org/confluence/display/idassurance/800-63-3+Review

Next call is August 4 , noon Pacific Daylight Time

Andrew Hughes
Chair, Kantara Initiative Leadership Council

_Andrew Hughes *CISM CISSP
Independent Consultant
*In Turn Information Management Consulting_

o  +1 650.209.7542
m +1 250.888.9474
1249 Palmer Road,
Victoria, BC V8P 2H8
AndrewHughes3000@gmail.com
ca.linkedin.com/pub/andrew-hughes/a/58/682/
*Identity Management | IT Governance | Information Security *
