### ISSUE TITLE
"can be accomplished in several different ways, any of which are acceptable" has no normative value 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1580]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.3, 9
 
**Comment (Include rationale for comment)**:  "can be accomplished in several different ways, any of which are acceptable" has no normative value
 
The language is not using normative terms, nor would it be possible to determine conformity to such a statement.  The list of (only) exempolars also gives no sound basis to assessing conformity.  In essence this clause allows complete freedom of choice, including nothing.  

**Suggested Change**: Remove from this section and consider placing in a non-normative general-discussion section (perhaps §3).
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Will restate this paragraph in normative language.
