### ISSUE TITLE
This clause, presumably related to the preceding 'MAY' choice, creates a clumsy requirement 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1582]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.3, 11
 
**Comment (Include rationale for comment)**:  This clause, presumably related to the preceding 'MAY' choice, creates a clumsy requirement
 
Stating 'SHALL' following a vague statement employing '" SHOULD … or MAY …" [para. 10] leaves scope for uncertainty and lack of rigour in how conformance is accomplished.  As already noted, this section is presumptive upon biometric matching being performed.

**Suggested Change**: Rephrase paras. 10 & 11 as:
"Biometric matching SHOULD by preference be peformed locally on the claimant’s device.  The only permissable alternative SHALL be performing biometric matching at a central verifier, in which case the following requirements SHALL be met:
a)  Use of the biometric SHALL be limited to [deleted - redundant] specific devices that are identified as using approved cryptography;
b)  Biometric revocation, referred to as biometric template protection in ISO/IEC 24745, SHALL be implemented;
c)  All transmission of biometrics SHALL be over the authenticated protected channel. "
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Also will be addressed by #682
