### ISSUE TITLE
This clause is not relevant to the scope of this standard 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1583]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.3, 13
 
**Comment (Include rationale for comment)**:  This clause is not relevant to the scope of this standard
 
Since these parts should be useable without dependance on the others, there is no reason for this non-normative paragraph.

**Suggested Change**: Remove whole para
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
As in other places, non-normative content is included to give context. This paragraph is basically a cross-reference to the use of biometrics in proofing.
