### ISSUE TITLE
It is not clear to whom this clause relates 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1584]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.4, 3
 
**Comment (Include rationale for comment)**:  It is not clear to whom this clause relates 
 
There is a possibility that this could be confused with an RP's risk-based decisions depending upon a received assertion's content.

**Suggested Change**: Modify as: "a CSP's risk-based authentication" [note addition of hyphen]
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Would probably use _verifier's_ rather than _CSP's_.
