### ISSUE TITLE
"public keys stored by the verifier SHALL use approved cryptography" is not at all clear. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1586]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.7, 3
 
**Comment (Include rationale for comment)**:  "public keys stored by the verifier SHALL use approved cryptography" is not at all clear.
 
Case 1:  Is that the keys must us approved crypto or that the storage mechanism must use approved crypto?  And why - presumably for integrity reasons (why encrypt a public key?)  In which case …

**Suggested Change**: re-phrase as:
"public keys stored by the verifier SHALL be protected against modification by use of approved cryptography"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The intent is that an approved encryption algorithm is to be used, not that the public key itself uses an approved algorithm.
