### ISSUE TITLE
"public keys stored by the verifier SHALL use approved cryptography" is not at all clear when read in conjunction with "Other verifier compromise[-]resistant secrets" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1587]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.7, 3, 4
 
**Comment (Include rationale for comment)**:  "public keys stored by the verifier SHALL use approved cryptography" is not at all clear when read in conjunction with "Other verifier compromise[-]resistant secrets"
 
Case 2:  'Other … secrets' by reference to what?  Presumably the preceding para, but that refers to (non-secret) public keys.  Should it refer to private keys? (As written, it suggests that the CSP is storing other parties' public keys.)  If so, who's?

**Suggested Change**: re-phrase as:
"private keys stored by the verifier SHALL be protected against unauthorized access by use of approved cryptography".   This clearly needs clarification of how the requirement is succinctly expressed based upon the original intention.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Basically the same as #1586
