### ISSUE TITLE
"Note that …" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1588]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.7, 4
 
**Comment (Include rationale for comment)**:  "Note that …" 
 
uses normative language and does not express a requirement that can be met - the preceding sentence does that.  Furthermore, what does 'lower complexity mean / relate to?  If SP 800-131A, that is already stated.  This note doesn't change a thing.

**Suggested Change**: Delete the whole sentence.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The words _Note that_ are probably extraneous, but it bears emphasizing that hashing of a memorized secret is not sufficient to claim verifier compromise resistance because there is no assurance that the underlying secrets have at least 112 bytes of entropy.
