### ISSUE TITLE
Use biometric input for reauth, not primary auth

### ISSUE THREAD

**Issue by oconnore** [usnistgov/800-63-3#159]
**Organization**: 2

**Type**: ?

**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 4.4 P 1, 5.2.3, 8.1 P 4, 

**Comment (Include rationale for comment)**:

The weaknesses of Biometric authentication are understated by the document. For example, biometric authenticators are subject to:
- Social engineering -- I can pressure or trick someone to put their thumb down or look into a camera. 
- Force: if I'm strong, I can grab your hand and take your fingerprint, or I can wait until you're asleep, etc.
- Testing lag: if I design a fingerprint scanner in 2016, my liveness tests (PAD) will likely fail in 2016 + years. Anecdotally: Apple's biometric liveness design once failed 48 hours after it was released. The document doesn't suggest a re-certification period. Most of the other techniques are not as technology dependent (entropy and cryptographic techniques are well studied and understood, and do not lose their security properties as quickly). 
- Circumvention: since the biometric input must default to another method after 10 failed attempts, any compliant MF device must accept a stronger third factor. 

**Suggested Change**: 

Since all biometric MF devices must accept an alternative factor of non-biometric authentication in the event that 10 attempts are failed, it would be clearer to allow biometric inputs for reauthentication, but not for initial authentication. This would clarify that the biometric input cannot be the sole input on the MF device, and would protect from some of the aforementioned attacks if they were to happen outside the re-auth window. 

Since biometric devices become easier to circumvent as technology develops, some sort of certification expiry should be recommended. Re-test once a year? 

Perhaps also: Biometric input methods "may" ("should"?) include a mechanism to allow a user to quickly require the stronger 3rd factor (cancelling the re-auth period).

**Comment by enewt** [comment]
Thanks for your comments!
I would like to focus on the suggsted changes by first asking what is meant by reauthentication?  Is this referring to when multi-factor authentication exists, the user/claimant/subscriber has to first pass the non-biometric authentication before being asked to authenticate their biometric?

The idea of expiration is great, but once a year is too short a window?

**Comment by enewt** [comment]
One last note regarding the window for expiration of certification, consider the product cycle of phones and phone upgrades.  Do you have thoughts on longer periods? Maybe 2 or 3 years?

**Comment by oconnore** [comment]
Hi @enewt , [4.4. Summary of Requirements](https://pages.nist.gov/800-63-3/sp800-63b.html#summary-of-requirements) and [7.2. Reauthentication](https://pages.nist.gov/800-63-3/sp800-63b.html#reauthentication) describe reauthentication. I think the intention is that someone who has recently authenticated with a comprehensive set of factors ought to be allowed, for convenience, to authenticate again in the near future (30 days, 30 minutes, or 15 minutes, for AAL 1-3, respectively) with a simpler, less onerous authentication procedure. Perhaps when biometric input is used to reauthenticate, the appropriate window may be longer for AAL 2-3?

> Is this referring to when multi-factor authentication exists, the user/claimant/subscriber has to first pass the non-biometric authentication before being asked to authenticate their biometric?

Yes. 

> One last note regarding the window for expiration of certification, consider the product cycle of phones and phone upgrades. Do you have thoughts on longer periods? Maybe 2 or 3 years?

I think 2-3 years would certainly be better than nothing. And to my knowledge, there is no formal certification process being established here, just a recommendation that a manufacturer periodically review whether the device "demonstrate[s] at least 90% resistance to presentation attacks for each relevant attack type" (5.2.3).

**Comment by enewt** [comment]
Hi @oconnore - thanks for the additional info and thoughts.  Another clarifying question:  in your suggeted change regarding reauthentication, is it your intention to remove the of using biometrics as a second factor (ie only use it for reauthentication purposes)?

**Comment by paul-grassi** [comment]
Without clarification we are closing this issue.
