### ISSUE TITLE
Sentences 1 & 2; whole para 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1590]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.9, 1;
2
 
**Comment (Include rationale for comment)**:  Sentences 1 & 2; whole para
 
None of the text in sentences 1 & 2 and in para. 2 is normative - it is all background or re-statement and should not be in this section (which is described as being normative).  Use of 'MAY' in para. 2 is inconsistent with the preceding normative statement that simply states that intent SHALL be determine dby (in the absence of any explict requirement) any available means.  Therefore this general discussion should be elsewhere and the 'MAY' should be replaced by 'can'.

**Suggested Change**: Place this non-normative text in a non-normative general-discussion section (perhaps §3).
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
While we have attempted to concentrate normative comment in a subset of the document, there is no harm in providing context for a requirement, rather than forcing the reader to jump around.
