### ISSUE TITLE
"Authenticators MAY be issued …" is explanatory, not normative 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1592]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 6.1, 1
 
**Comment (Include rationale for comment)**:  "Authenticators MAY be issued …" is explanatory, not normative
 
Therefore this text should be elsewhere - presumably §3

**Suggested Change**: Place this non-normative text in a non-normative general-discussion section (perhaps §3).
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The text is not strongly normative, but does establish two ways that authenticators are obtained.

**Comment by jimfenton** [comment]
See also #802.
