### ISSUE TITLE
Severe lack of distinctive requirements by AL 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1594]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 6.1.1, 2, 3
 
**Comment (Include rationale for comment)**:  Severe lack of distinctive requirements by AL
 
Earlier sections and 63A have dealt with AL by distinct level, which (even at the risk of some repetition) makes for a much clearer statement of requirements applicable to each AL.  These two paras. seem not to have evolved beyond 63 rev.2 as have other parts of this rev.3.
Furthermore, the reference to both AAL and IAL has the potential to confuse.  This clause appears to be making, whether intentionally or not, a separate function of the binding of an authenticator, cf. IdPV or actual authentication during a transaction.  As preceding comments have suggested, this was expected to be a part of 63A - its appearance here is somewhat of a surprise and has not been clearly communicated by this doc, thus far.
There is the apparent expectation that either the binding CSP is separate from the IdPV CSP, or that the IdPV CSP has to know at what level the IAL is required to be set, in order to bind.

**Suggested Change**: Sedt out separate requirements for each IAL (this above AAL, since IAL is the remit of 63B), and within those, for each discrete AAL at which the identity might have been established.  Only in this way can coherent normative requirements be stated.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The above comment and suggested change are confusing, because IAL is the remit of -63A and AAL is described in -63B. However, the two paragraphs cited could be better organized.
