### ISSUE TITLE
Text from "Enrollment and binding MAY be broken up … " until "SHALL" is not very affirmatively-expressed 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1595]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 6.1.1, 4
 
**Comment (Include rationale for comment)**:  Text from "Enrollment and binding MAY be broken up … " until "SHALL" is not very affirmatively-expressed
 
The second sentence is more like a qualifiying comment than a part of the fundamental requirement.  The remote or in-person aspects are initially overlaid, yet needn't be (separateion yields clarity).  In the proposed change they bare distinctly separate, 'electronic transaction is not 

**Suggested Change**: Re-express as:
"For remote enrollment and binding, if the process cannot be completed be completed within a single protected session, the following methods SHALL …
[then include existing indexed items a) and b), and close]"  THEN
"For in-person enrollment and binding, if the process cannot be completed be completed within a single encounter, the following methods SHALL ...
[then include existing indexed items a) - c) but list as c) - e) to ensure uniqueness[see second comment], and close]"

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Second sentence could be expressed more normatively.
