### ISSUE TITLE
The second a) is the subject of this comment [see second comment]: "as described above" is not clear 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1596]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 6.1.1, 4 a)
 
**Comment (Include rationale for comment)**:  The second a) is the subject of this comment [see second comment]:  "as described above" is not clear
 

**Suggested Change**: make a specifi reference to the intended clause/phrase (see comment above).
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The bullets are also misnumbered and poorly organized.
