### ISSUE TITLE
"each factor they" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1597]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 6.1.2.1, 1
 
**Comment (Include rationale for comment)**:  "each factor they"
 
poor grammar

**Suggested Change**: "each factor which they"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The correct change would be, "each factor that they".
