### ISSUE TITLE
Binding additional factor to a 1FA account

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1598]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 6.1.2.2, 
 
**Comment (Include rationale for comment)**:  Is it correct to infer from this section that a CSP SHALL only permit the addition of an authn factor at IAL1, and then only if the IdPV was conducted at AAL1?  
 
It doesn't explicitly say that, but to do so would make the point very clear.

**Suggested Change**: Replace all text up to but excluding "the subscriber MAY request" with:
"CSP's SHALL only allow the addition of a second [further?] authentication factor when the initial identity proofing was conducted at AAL1 and the required authentication is  at IAL1.  Under such circumstances, " [then continue from "the subscriber MAY request ..."].
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
What is an IdPV? The transition from single-factor to multi-factor is a special situation, described in this section. However, there seems to be an implication that once authenticators for multi-factor authentication have been bound to the account, that single-factor authentication isn't possible any more (i.e., even for applications at AAL1 releasing no personal information). This is incorrect and needs to be re-examined.

**Comment by jimfenton** [comment]
Also change title of 6.1.2.2 from one-factor to single-factor
