### ISSUE TITLE
Last sentence: "Reestablishment of authentication" "the biometric collected" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1599]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 6.1.2.3, 1
 
**Comment (Include rationale for comment)**:  Last sentence: "Reestablishment of authentication" "the biometric collected"
 
This is a very distinct requirement applicable only at IAL3 but is lost at the end of a paragrpah which deals with IAL2 and IAL3, which breaks basic rules.  Additionally, two further oversights 

**Suggested Change**: Make a separate paragraph and correct as follws:
"Re-establishment …"
"the biometric data collected …"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The beginning of the sentence makes it clear that the biometric reference applies only at IAL3.
