### ISSUE TITLE
Guidance for determining threshold for system users that KBV questions should be applied to for ID Proofing

### ISSUE THREAD

**Issue by SES-SSE** [usnistgov/800-63-3#16]
**Organization**: 1

**Reference (Include section and paragraph number)**:

5.3.2. Knowledge Based Verification Requirements

**Comment (Include rationale for comment)**:

The focus of identity proofing should not only be on the odds on creating a given fraudulent account for an individual, but should also include the odds of attacking the identity proofing capability of a system.  In the context of attacking the entire user base using random answers, KBV could lead to successful compromise of the identity verification steps for IAL 2 and 3.

**Suggested Change**:

Thresholds of users should be determined when the probability of compromise of KBV doesn’t support the use of KBV.  In cases where KBV must be used irrespective of user population, then compensating controls such as micro-deposits or sending a letter in the mail to the user’s official home of record shall be used.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
We prefer micro-deposit (it is  SHOULD in the KBV section) over KBV (which is a MAY).  In addition, we also require address confirmation based on records, to include notification to postal address.

**Comment by SES-SSE** [comment]
It is not clear to me how sending a letter of notification to the address of record can mitigate the threat if an enrollment code is sent by other means and can be used to get immediate access to the system, e.g. email, sms, landline. I would tend to agree if the code was sent by letter to the address of record.  

“Enrollment codes sent by means other than physical mail SHALL be valid for a maximum of 10 minutes; those sent to a postal address of record SHALL be valid for a maximum of 7 days.”

“A notification of proofing SHALL be sent to different address of record than the destination of the enrollment code. The address of record MAY include the postal address obtained from validated identity evidence. For example, if the CSP sends an enrollment code to a mobile phone of record, a notification of proofing will be sent to the postal address in records or obtained from validated evidence, like a driver’s license.”

When looking at suggested/changes requirements, you may want to also consider them in the context of the “Shall” requirements and assume that the Shall requirements will be implemented by customers.  Shoulds and Mays if not implemented may have an impact on whether to keep or reject a suggested requirement.  There are dependencies between these requirements and the Shalls are the ones that will hopefully be implemented by a given CSP.

Thank you for your consideration as I know you have a difficult job to do.
