### ISSUE TITLE
This whole section is poorly expressed and is weak in its use of mandatory terms 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1601]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 6.2, 
 
**Comment (Include rationale for comment)**:  This whole section is poorly expressed and is weak in its use of mandatory terms
 
In para. 1 the SHALL clause refers to "a similar manner", yet no 'manner' is explicitly described (the preceding sentence is simply narrative and non-specific).  The following sentence likewise is narrative.
The second para. is effectively optional and it is strange to find a SHALL dexpressed at the end of the para. - its enforcability is from from certain or concise.

**Suggested Change**: This requires a thorough overhaul to state explicitly what SHALL be met and what choices the CSP's have for optional elements (SHOULDs/MAYs).
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
_in a similar manner_  needs to be clarified. The use of normative terms, particularly in the second paragraph, seems clear enough.
