### ISSUE TITLE
"due to expiration rather than some other cause" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1602]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 6.3, 1
 
**Comment (Include rationale for comment)**:  "due to expiration rather than some other cause" 
 
It would be sufficient to state what is recommended without further qualification of what is not.

**Suggested Change**: Delete the text in bold underline
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The point is that there should be a specific indication to the subscriber when expiration is the cause.
