### ISSUE TITLE
The first sentence is not a true definition (and as such, should not be in this clause) 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1603]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 6.4, 1
 
**Comment (Include rationale for comment)**:  The first sentence is not a true definition (and as such, should not be in this clause)
 
If a definition is required, place it with other definitions.  However, is the bimding actujally removed or is the authenticator irreversibly put into a state in which it can no longer be used.  The binding needs to be maintained for potential (legal) follow-up purposes 

**Suggested Change**: Reconsider this wording
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
In some cases authenticators are used with more than one CSP account so 'killing' the authenticator is not appropriate in general. The binding is removed, but if a record of the binding having existed for forensic purposes that is permitted by the existing wording.
