### ISSUE TITLE
the stimuli for revocation overlooks any legal requirement 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1604]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 6.4, 1
 
**Comment (Include rationale for comment)**:  the stimuli for revocation overlooks any legal requirement
 
(which shouldn 't be argued to be included within the final condition, which is very tenuous - actually better to state that as policy)

**Suggested Change**: Extend with
", when required to do so in respond to applicable legal instruments [or similar] or when the CSP  determines that the
subscriber no longer meets its policy or other eligibility requirements."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
We recognize that CSPs need to conform to legal requirements as well, but that does not need to be repeated throughout the document.
