### ISSUE TITLE
Surrender or destruction proof of authenticators with certified attributes

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1605]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 6.4, 2
 
**Comment (Include rationale for comment)**:  Except in very tightly-controlled circumstances, this isn't going to happen (e.g. a c,ose relationship between employer and Subject).
 
Users can't be bothered and CSP's don't want to manage it - how many old driving licenses do we keep?  Logical revocation which renders the authenticator unusable is the most effective solution.  That said, if we are happy that the REQUIRMENT is there, fair enough - the clause does not say 'and enforce'.

**Suggested Change**: Consider the implications of this comment - is it sufficient to 'require', knowing that probably no effect will come from it?
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Authenticators such as PIV cards are required to be surrendered upon termination.
