### ISSUE TITLE
Normative status is not stated 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1607]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 7, 
 
**Comment (Include rationale for comment)**:  Normative status is not stated
 

**Suggested Change**: Insert statement to that effect
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Section is normative.
