### ISSUE TITLE
not very normatively-expressed 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1609]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 7.1, 1
 
**Comment (Include rationale for comment)**:  not very normatively-expressed
 
Sentences 1 and 3 of this para are narfrative and should be elsewhere in a non-normative section.  By mixing such pieces of text the normative focus is diminished 

**Suggested Change**: Place this non-normative text in a non-normative general-discussion section (perhaps §3).
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
While we have attempted to concentrate normative comment in a subset of the document, there is no harm in providing context for a requirement, rather than forcing the reader to jump around.
