### ISSUE TITLE
The list of SHALLs and SHOULD seems a little heavy! 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1611]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 7.1, 3
 
**Comment (Include rationale for comment)**:  The list of SHALLs and SHOULD seems a little heavy!
 
It could be better expressed as two lists:  those that "SHALL be" met (with subtle re-wording on the negative aspects) and a list of those that "SHOULD be" met

**Suggested Change**: Re-structure as suggested and use alpha-indexing (see second comment)
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This use of SHALL and SHOULD makes it clear what the conjunction (and) is between the requirements, and therefore seems clearer than the suggested change.
