### ISSUE TITLE
"verified by the RP …" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1612]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 7.1, 4
 
**Comment (Include rationale for comment)**:  "verified by the RP …"
 
Isn't it out of scope to place requirements on RPs in this doc? 

**Suggested Change**: If this is meant to enforce certain behaviours on agencies then (as recommended) create a discrete document or section directed at agencies acting as RPs.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
There are few requirements on RPs (as compared with verifiers, for example) but maintaining the integrity of the session is critical and has to be done there.
