### ISSUE TITLE
Lots of missing hyphens, required to enforce compound adjectives: 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1613]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: , 
 
**Comment (Include rationale for comment)**:  Lots of missing hyphens, required to enforce compound adjectives:
 
general purpose
replay resistant
authentication protected
context specific
rate limited (if used)
directly connected
compromise resistant
identity proofed

**Suggested Change**: hyphenate to improve readability
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The terms "authentication protected" and "context specific" are not used in the document suite.

**Comment by RGW-Zygma** [comment]
"Authn protected" - mea culpa, I misread "authenticated protected", and no hyphenation is required
"context specific" occurs in 63B, pg. 20

**Comment by jimfenton** [comment]
Thanks; missed context-specific somehow. Note that compound adjectives are only hyphenated when followed immediately by the noun they modified; hence "identity proofed" was not hyphenated.
