### ISSUE TITLE
Which is true - is the binding described in IAL or AAL, or both. If both, are these meant to be the 'same' binding? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1615]
**Organization Name (N/A, if individual)**: SecureKey

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Executive Summary and Section 5.1, 
 
**Comment (Include rationale for comment)**:  Which is true - is the binding described in IAL or AAL, or both. If both, are these meant to be the 'same' binding?
 
Doc reference statement:
 *IAL refers to* the identity proofing process and *the binding between one or more authenticators and the records pertaining to a specific subscriber*.
    AAL refers to the authentication process itself.
    FAL refers to the assertion protocol utilized in a federated environment to communicate authentication and attribute information (if applicable) to a relying party (RP).
-------------------------
SS5.1:
To determine the process and system requirements that reduce the risk of an authentication or identity proofing failure, this guideline introduces distinct categories of assurance which drive the technical solutions an agency may implement. They are:

    IAL - The robustness of the identity proofing process to confidently determine the identity of an individual.
    *AAL* - The robustness of the authentication process itself, *and the binding between an authenticator and the identifier of a specific individual.*
    FAL - The robustness of the assertion protocol utilized by the federation to communicate authentication and attribute information (if applicable) to an RP. FAL is optional as not all digital systems will leverage federated identity architectures.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Another issue similar to this.  Good catch.  Thanks!
