### ISSUE TITLE
Is it always the case that the binding would be maintained by the CSP. I would actually think the binding would be maintained by the 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1616]
**Organization Name (N/A, if individual)**: SecureKey

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Section 3, 
 
**Comment (Include rationale for comment)**:  Is it always the case that the binding would be maintained by the CSP. I would actually think the binding would be maintained by the identity record holder, or an entity on its behalf.
 
Credential

An object or data structure that authoritatively binds an identity, via an identifier or identifiers, and, optionally, additional attributes, to at least one authenticator possessed and controlled by a subscriber.

While common usage often assumes that the credential is maintained by the subscriber, this document also uses the term to refer to electronic records *maintained by the CSP* which establish a binding between the subscriber’s authenticator(s) and identity.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Binding is hard when xALs are separated and we appreciate this comment.  We remain agnostic on who performs what function, and stick to requirements that appropriately bind an authenticator to an identity.
