### ISSUE TITLE
Should table 4.7 be modified to No for IAL2 biometric collection? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1620]
**Organization Name (N/A, if individual)**: SecureKey

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 4.7, 
 
**Comment (Include rationale for comment)**:  Should table 4.7 be modified to No for IAL2 biometric collection?
 
Section 4.7 Summary of requirements states biometric collection requirement as "Yes" for IAL2, however, Section 4.4.1.7. Biometric Collection states:
The CSP *MAY* collect biometrics for the purposes of non-repudiation and re-proofing. See [Section 5.2.3 of SP 800-63B] for more detail on biometric collection.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will accept if we keep the table.
