### ISSUE TITLE
Will this restrict private sector identity validation from being able to be compliant with IAL2 and IAL3 identity proofing 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1621]
**Organization Name (N/A, if individual)**: SecureKey

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 5.2.2.1, 
 
**Comment (Include rationale for comment)**:  Will this restrict private sector identity validation from being able to be compliant with IAL2 and IAL3 identity proofing
 
Will this restrict private sector identity validation from being able to be compliant with IAL2 and IAL3 identity proofing as a result of limited access to issuing source validation mechanisms?
If yes, is it the intention to restrict private sector compliance with IAL2 and IAL3 identity prrofing (e.g., to ensure only government issued sources can be leveraged by government agencies)?

Section 5.2.2.1 outlines the following requirement in both strong and superior identity evidence validation methods:
"All personal details and evidence details have been confirmed as valid by comparison with information held or published by the issuing source."

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved under comment #582
