### ISSUE TITLE
Consider adding definitions of various binding types to glossary. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1622]
**Organization Name (N/A, if individual)**: SecureKey

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Sections 6.1 and 7.1, 
 
**Comment (Include rationale for comment)**:  Consider adding definitions of various binding types to glossary.
 
Section 6.1: Authenticator Binding
Section 7.1 Session Binding

**Suggested Change**: Note that Section 7.1.3 also includes "token binding" and Section 6.1.2 talks to post-enrolment bindings -- but assume both of these are just types of authenticator bindings
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
These are not so much different binding types, but rather binding of different things. We will add a definition of _binding_.
