### ISSUE TITLE
(editorial) The ISO definition of ‘biometrics’ places ‘biological’ before ‘behavioral’. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1627]
**Organization Name (N/A, if individual)**: DHS S&T FRG

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Clause 3, Biometrics
 
**Comment (Include rationale for comment)**:  (editorial) The ISO definition of ‘biometrics’ places ‘biological’ before ‘behavioral’.  
 
Consistency with international standard.

**Suggested Change**: Recommend to use the ISO definition verbatim. [Note:  This carries through to other parts of 800-63-3x as well.]  It may also be useful to cite:
- ISO/IEC ISO/IEC 2382-37, Information Technology – Vocabulary – Part 37: Biometrics (2nd edition, Feb 2017)
(Free at http://standards.iso.org/ittf/PubliclyAvailableStandards/index.html.)
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
@jimfenton if this issue applies to -B as well, please apply the change.  I will in -3.

**Comment by jimfenton** [comment]
Nothing to change in -63B since the definitions have been centralized.
