### ISSUE TITLE
Recommend that it be spelled out that biometrics are considered an authentication factor, but not an authenticator. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1630]
**Organization Name (N/A, if individual)**: DHS S&T FRG

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: General, General
 
**Comment (Include rationale for comment)**:  Recommend that it be spelled out that biometrics are considered an authentication factor, but not an authenticator. 
 
Clarify role of biometrics.  Although a biometric may be used as a factor in multi-factor authentication (e.g., as a second factor), only authenticators are verified at the verifier.  (This is talked around but not stated directly.)  If this is indeed the intent.

**Suggested Change**: State plainly that biometrics may be a 2nd or 3rd factor, but are not an authenticator that is verified at the verifier.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
There is an issue similar to this.  We will update.
