### ISSUE TITLE
For IAL2, the table indicates that Biometric Collection is required. However, 4.4.1.7 indicates that biometrics MAY be collected. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1632]
**Organization Name (N/A, if individual)**: DHS S&T FRG

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.7, Table 4.3, row 5
 
**Comment (Include rationale for comment)**:  For IAL2, the table indicates that Biometric Collection is required.  However, 4.4.1.7 indicates that biometrics MAY be collected.  
 
Internal consistency. Therefore, the table should more correctly indicate that at this level biometric collection is optional, rather than “Yes”.

**Suggested Change**: Change 'Yes' to 'Optional'.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
trying to determine if table should be removed.  If not, this will be fixed.
