### ISSUE TITLE
'Both' does not make sense unless ‘or’ is present, as it is on the preceding row. (Also, as it is, sounds like the cryptographic methods 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1633]
**Organization Name (N/A, if individual)**: DHS S&T FRG

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.2.1.1, Table 5-1, pg 20, 8th bullet
 
**Comment (Include rationale for comment)**:  'Both' does not make sense unless ‘or’ is present, as it is on the preceding row. (Also, as it is, sounds like the cryptographic methods are proprietary.)
 
Editorial improvement.

**Suggested Change**: Should read: “proprietary or cryptographic methods, or both …” 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We are getting rid of the term proprietary, so that will resolve the editorial comment.
