### ISSUE TITLE
Commas are misplaced. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1635]
**Organization Name (N/A, if individual)**: DHS S&T FRG

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.3.2, 1st bullet
 
**Comment (Include rationale for comment)**:  Commas are misplaced.  
 
Editorial improvement.

**Suggested Change**: Should read:  “… if the CSP is not, or does not, maintain a relationship with an authoritative source.”
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We have an accepted comment to remove this sentence, so that will resolve the editorial comment.
