### ISSUE TITLE
Requirement #4 needs further clarification 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1638]
**Organization Name (N/A, if individual)**: DHS S&T FRG

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 6.3, #4
 
**Comment (Include rationale for comment)**:  Requirement #4 needs further clarification
 
Requirement #4 implies a trust relationship between the primary CSP and the CSP issuing the derived credential since the primary CSP has an obligation to protect the biometric (PII) of the credential holder.  Further, if it is the authentication biometric (as implied by citing the AAL3 authenticator) rather than the biometric collected for identity evidence/validation/verification/non-repudiation/reproofing, biometrics stored within secure/trusted elements are usually not exportable.  Unclear logic, relationships/processes.

**Suggested Change**: This requirement should be further clarified.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This section is only for the same CSP issuing the derived credential.  However, I understand the confusion, specifically when mentioning AAL3, so this section will be revised to clarify requirements.

**Comment by paul-grassi** [comment]
OBE via update to Ch.6  See #597
