### ISSUE TITLE
The role of biometrics within ‘permitted authenticator types’ is confusing here. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1639]
**Organization Name (N/A, if individual)**: DHS S&T FRG

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.2.1, Note
 
**Comment (Include rationale for comment)**:  The role of biometrics within ‘permitted authenticator types’ is confusing here.  
 
Per 4.1.1 (and clause 5) biometrics are not considered an authenticator type and 4.2.1 states that a combination of two single-factor authenticators shall be one memorized secret + one possession-based  authenticator.  The note implies, however, that biometrics may be used as a second authenticator. Confusing.

**Suggested Change**: Please clarify.  If this applies to multi-factor authenticators only, then so state.   (If this is the case, it may be correctable by moving the note up under the multi-factor paragraph rather than under the combination paragraph.) 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Biometrics is one of the three _authentication factors_, but is not an authenticator type by itself that is recognized by -63B. Rather, it is a factor that can be used by a _multi-factor cryptographic device_, _multi-factor cryptographic software_, or a _multi-factor OTP device_.

We will add a definition for _authenticator type_ to help better explain the distinction with _authentication factor_.
