### ISSUE TITLE
Session Token: Insecure vs secure storage and "non-secret" session tokens

### ISSUE THREAD

**Issue by moderndeveloperllc** [usnistgov/800-63-3#164]
**Organization**: 3
**Type**: Pharmaceutical Software Company
**Document (63-3, 63A, 63B, or 63C)**: 63B
**Reference (Include section and paragraph number)**: 7.1
**Comment (Include rationale for comment)**:
The beginning paragraph and bullet points of Section 7.1 deal with the handling of session "secrets". It indicates that you SHOULD NOT store in Local Storage. Two points of discussion:
1. The recommendation "SHOULD not be placed in insecure locations such as HTML5 Local Storage" is vague in that there are no guidelines for what constitutes secure vs. insecure storage. Is it insecure because Local Storage can be persistent across sessions? (sessionStorage does not persist). Is it insecure because it is not stored encrypted? 
2. Does this storage recommendation apply to authenticated token schemes such as [RFC 7519](https://tools.ietf.org/html/rfc7519) ([JSON Web Tokens](https://jwt.io)) that utilize a server generated and stored secret to validate a session. The data sent in the token is encoded, but not encrypted and may not be considered "secret" in that it is designed to be read and used by the subscriber's software. It is signed with a server stored secret to prevent session tampering or hijacking.

If I'm misinterpreting the definition of "session secret" the above points may be moot, but I would appreciate further clarification. Thank you.

**Comment by jimfenton** [comment]
HTML5 local storage is manipulated exclusively through Javascript functions, and is considered by some to be less secure because of possible exposure to cross-site scripting (XSS) attacks. In contrast, a browser cookie with the HttpOnly tag set is not accessible via JavaScript, and therefore does not have that vulnerability.

JWTs are more commonly used for assertions (see SP 800-63C), but since it's a data representation, storage in that form doesn't have any bearing on these requirements.

It's clear that we need to have a bit more explanation in this section.

**Comment by moderndeveloperllc** [comment]
@jimfenton Thank you for the clarification. If I understand correctly, using JWT for session management would be the equivalent of a [front-channel presentation](https://pages.nist.gov/800-63-3/sp800-63c.html#front-channel-presentation) where the IdP and the RP are actually the same server. The three SHALLs would be fulfilled by utilizing the [signature](https://jwt.io/introduction/#signature) of the JWT (with [appropriate reserved claims](https://jwt.io/introduction/#payload)) and transmitting the information solely over APC (TLS, etc) connections:

> The RP SHALL protect itself against injection of manufactured or captured assertions by use of cross-site scripting protection or other accepted techniques.
> 
> The assertion SHALL be validated including issuer verification, signature validation, and audience restriction.
> 
> Conveyance of the assertion from the IdP to the subscriber as well as from the subscriber to the RP SHALL be made over an authenticated protected channel.

**Comment by jimfenton** [comment]
Issue was resolved by https://github.com/usnistgov/800-63-3/pull/341/commits/224e81b793d131801c7461d7ed4014ea2359e84e but feel free to add further comments if it still isn't clear.
