### ISSUE TITLE
The requirements for AAL2 authenticators include that the authenticator be validated to FIPS-140. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1640]
**Organization Name (N/A, if individual)**: DHS S&T FRG

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.2.2, 1st para (& elsewhere, e.g., Table 4-3)
 
**Comment (Include rationale for comment)**:  The requirements for AAL2 authenticators include that the authenticator be validated to FIPS-140.  
 
Since FIPS-140 certification applies only to a specific dot release of software/firmware on a specific chip(set) under a specific dot release OS, it is unclear how this applies to smart mobile devices that issue updates regularly.  If a user updates their OS, does their authenticator instantly become unapproved at AAL2?  How would a verifier know/track this?  (This is less of a problem for hardware crypto devices than for software crypto.) Continuity of operation.

**Suggested Change**: Clarify how FIPS-140 requirements are met when a mobile device OS is updated.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The FIPS 140 requirement for authenticators extends only to authenticators procured by government agencies. It was recognized that many uses of AAL2 would be by non-government subscribers, so they are exempt from the requirement.
