### ISSUE TITLE
The first bullet states: “In addition, FMR and FNMR do not account for spoofing attacks.” 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1644]
**Organization Name (N/A, if individual)**: DHS S&T FRG

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.3, 1st bullet
 
**Comment (Include rationale for comment)**:  The first bullet states: “In addition, FMR and FNMR do not account for spoofing attacks.”  
 
This is true; however, neither does password entropy account for password sharing, social engineering, or sticky notes under the keyboard.  Redundancy & leveling.

**Suggested Change**: As presentation attacks are specifically addressed in the 4th bullet, recommend this sentence be deleted from the 1st bullet as unnecessary.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The sentence describes the test conditions for the measurement of FMR/FNMR.

This will be addressed by #1391
