### ISSUE TITLE
This requires a secure channel between the biometric sensor and the verifier; however, only authenticators are verified by a verifier and biometrics are excluded as 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1645]
**Organization Name (N/A, if individual)**: DHS S&T FRG

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.3, 4th para
 
**Comment (Include rationale for comment)**:  This requires a secure channel between the biometric sensor and the verifier; however, only authenticators are verified by a verifier and biometrics are excluded as an authenticator.  
 
The purpose is therefore unclear.  Perhaps you meant between the sensor and the matcher? Logic unclear.

**Suggested Change**: Clarify, perhaps replacing 'verifier' with 'matcher' as appropriate.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
While authentication of the sensor itself is desirable, it is more likely that a (multi-factor) authenticator resistant to sensor replacement will be authenticated by the verifier. This is already reflected in the text.

We do not want to introduce additional terminology such as _matcher_.
