### ISSUE TITLE
Is it anticipated that ISO/IEC 30107 will be cited in future editions? As Part 1 is now published, it may be useful to cite that 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1646]
**Organization Name (N/A, if individual)**: DHS S&T FRG

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.3, 6th para & note box
 
**Comment (Include rationale for comment)**:  Is it anticipated that ISO/IEC 30107 will be cited in future editions?  As Part 1 is now published, it may be useful to cite that now.
 
Standards alignment.

**Suggested Change**: Cite ISO/IEC 30107-1 as appropriate.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Reference to ISO/IEC 30107-1 will be added in response to #1391.
