### ISSUE TITLE
This allows for biometric matching on a central verifier; however… 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1647]
**Organization Name (N/A, if individual)**: DHS S&T FRG

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.3, pg 27, 2nd para from bottom and next, continuing to pg 28
 
**Comment (Include rationale for comment)**:  This allows for biometric matching on a central verifier; however…
 
it is not clear how this could be achieved given the requirements that the device be identified using approved cryptography while the biometric is to be used to activate the key used to identify said device.  This appears circular.  Is the device to be identified twice?  Once with an unprotected key and then with the protected key? Unclear logic.

**Suggested Change**: If two separate keys are required, so state.  If not, clarify process/sequence.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Yes, two keys are required, and we will add that.

**Comment by jimfenton** [comment]
Apparently closed by mistake.
