### ISSUE TITLE
Authentication intent is well suited to biometrics as it requires intervention of the subject. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1648]
**Organization Name (N/A, if individual)**: DHS S&T FRG

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.9, 2nd para
 
**Comment (Include rationale for comment)**:  Authentication intent is well suited to biometrics as it requires intervention of the subject.  
 
Enhance understanding.

**Suggested Change**: Suggest adding to the 2nd sentence of the 2nd paragraph “e.g., to enter an authenticator output on their endpoint from an OTP device or to provide a biometric, establish intent by their very nature.”
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
That's true for many biometric modalities, but some behavioral biometrics (typing cadence, for example) do not establish intent. In any case, will mention that collection of a biometric often establishes intent.
