### ISSUE TITLE
Misnumbering. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1650]
**Organization Name (N/A, if individual)**: DHS S&T FRG

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 6.1.1, 2nd numbered subpara of para 4 
 
**Comment (Include rationale for comment)**:  Misnumbering.
 
Editorial improvement.

**Suggested Change**: “For physical transactions” should be numbered 2 rather than 1.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Consider removing the numbers here. They don't really add anything.
