### ISSUE TITLE
Biometric usability focuses on fingerprint, face, and iris; however, voice is also frequently used, particularly with mobile devices. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1651]
**Organization Name (N/A, if individual)**: DHS S&T FRG

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 10.4, 2nd para
 
**Comment (Include rationale for comment)**:  Biometric usability focuses on fingerprint, face, and iris; however, voice is also frequently used, particularly with mobile devices.  
 
Completeness.

**Suggested Change**: Suggest that voice be covered as well, especially since it is the only non-image based biometric and may therefore have unique considerations.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by ychoong** [comment]
The usability considerations were based on usability research and practices. Usability research on voice authentication is a relatively nascent research area.
