### ISSUE TITLE
Requirement does not match example. Pose and expression are 2 different things, though both affect facial recognition accuracy. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1652]
**Organization Name (N/A, if individual)**: DHS S&T FRG

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 10.4, pg 44, 3rd sub-bullet under Face
 
**Comment (Include rationale for comment)**:  Requirement does not match example.  Pose and expression are 2 different things, though both affect facial recognition accuracy.  
 
Pose has to do with yaw/pitch/roll angles.  Technical correctness.

**Suggested Change**: Suggest that these be separately addressed (2 bullets) or that a more suitable example be provided for pose (e.g., “looking down or away from the camera”).
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
