### ISSUE TITLE
FOIA

### ISSUE THREAD

**Issue by hferraio** [usnistgov/800-63-3#1654]
### All Fields Are Required
**Organization Name (N/A, if individual):** NIST

**Organization Type (see below for codes)**:
 
**Document (63-3, 63A, 63B, or 63C)**:63-3, 63A, 63B and 63C

**Reference (Include section and paragraph number)**: Need FOIA statement
 
**Comment (Include rationale for comment)**:
 Easy one:  Need FOIA statement
**Suggested Change**:
 Add:  All comments are subject to release under the Freedom of Information Act (FOIA).  This is usually on page ii. 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
It's included in all source documents, we just hid online until we go final.

{::comment}

**Comments on this publication may be submitted to dig-comments@nist.gov  
Public comment period: Month Day, YYYY through Month Day, YYYY**  
All comments are subject to release under the Freedom of Information Act (FOIA).

National Institute of Standards and Technology  
Attn: Computer Security Division, Information Technology Laboratory  
100 Bureau Drive (Mail Stop 8930) Gaithersburg, MD 20899-8930  
=======
Email: <dig-comments@nist.gov>

{:/comment}
