### ISSUE TITLE
xALs are introduced without context

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1657]
### All Fields Are Required
**Organization Name (N/A, if individual):** VA

**Organization Type (see below for codes)**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 63-3

**Reference (Include section and paragraph number)**: 4.1 Overview, Paragraph 4
 
**Comment (Include rationale for comment)**: The reader is introduced to the different Level of Assurance with no details provided.
 
**Suggested Change**:  Suggest adding a hyperlink to the tables in Section 5.2 Assurance Levels.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE with the April 1 update to -3.
