### ISSUE TITLE
Will the Relevant Controls in SP 800-53 revision 5 be updated to reflect this change in thinking?

### ISSUE THREAD

**Issue by OMjlowder** [usnistgov/800-63-3#1662]
### All Fields Are Required
**Organization Name (N/A, if individual):** OpenMarket

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 63-3

**Reference (Include section and paragraph number)**: All
 
**Comment (Include rationale for comment)**: If I understand the document correctly, it seems to suggest that some of the IA controls or control enhancements in SP 800-53 should be revised to reflect this change in thinking from NIST. 
 
**Suggested Change**: Please ensure that this guidance is consistent with SP 800-53 revision 5.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
They already have been.  800-53 will be out for comment in the near future.
