### ISSUE TITLE
Select Assurance Levels based upon data classification

### ISSUE THREAD

**Issue by jweden** [usnistgov/800-63-3#1669]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**: 4
 
**Document (63-3, 63A, 63B, or 63C)**: 63-3

**Reference (Include section and paragraph number)**: 6
 
**Comment (Include rationale for comment)**: Based upon my industry experience as a certified security professional in the area of IAM security control guidance.
 
**Suggested Change**:  The impact analysis mentioned in section 5 and 6 which is used to determine assurance levels is a heavyweight process.  An alternative is to base the assurance level selection on data classification only (i.e. the class of data authorized to be accessed subsequent to identity proofing/authentication) .  This also has the benefit of being much simpler and is much less likely to be subjective.  As such it is more likely to be consistently implemented while still being an arguably effective approach for the selection of assurance levels.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is language from M-04-04 that we need to retain.
