### ISSUE TITLE
Excellent policy for memorized secret complexity

### ISSUE THREAD

**Issue by JimTheFrog** [usnistgov/800-63-3#167]
**Organization**: DECE / UltraViolet

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 5.1.1 and Appendix A

**Comment (Include rationale for comment)**: 

Kudos and thank you! Thank you for an enlightened approach to memorized secret (password) complexity. Please stick to your guns on this point. The disturbing industry trend towards forcing users to create artificially complex passwords usually backfires (as you point out), always reduces system usability, and contributes to increased user blood pressure in at least my case. Ironically, misguided attempts to introduce complexity into user passwords are more likely to _reduce_ entropy. For example, an attacker attempting to guess passwords for a system with requirements such as “must contain at least one number and at least one punctuation” can simplify their algorithm to skip combinations that don’t contain a number and a punctuation character. They can further optimize their attack algorithm to put numbers and punctuation at the end of the password, as you illustrate. The best entropy comes from complete randomness, and all the clueless lemmings in IT departments across the country are driving users in the wrong direction. I look forward to being able to direct them to this sensible document.

**Suggested Change**:

Feel free to add the point above to Appendix A if you think it adds value.

---

**Comment by jricher** [comment]
Thanks and +1, but @pgrassi-nist, do we have a canonical reference for "clueless lemmings"? :)

**Comment by paul-grassi** [comment]
No comment :)
