### ISSUE TITLE
GLEIF Comments on DRAFT NIST Special Publication 800-63-3

### ISSUE THREAD

**Issue by Stphnwlf** [usnistgov/800-63-3#1670]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Global Legal Entity Identifier Foundation (GLEIF)
**Organization Type (see below for codes)**:
 5
**Document (63-3, 63A, 63B, or 63C)**:
63-3
**Reference (Include section and paragraph number)**:
 Document
**Comment (Include rationale for comment)**:
GLEIF welcomes the clarity, assurance and potential for advancing standards in digital identification provided by NIST’s draft Special Publication 800-63-3, “Digital Identity Guidelines”. Provision of technical and organizational guidance to public and private sector organizations for selecting authenticator assurance levels appropriate to the assessed risk of financial loss or liability aligns particularly strongly with the specific objectives of the Global Legal Entity Identifier System (GLEIS).
 
The GLEIS itself, as a federated system of LEI Issuers who provide registration and authentication services to legal entities wishing to receive an LEI, embodies many of the principles described by the draft guidelines, and GLEIF will support their adoption as being in line with our vision and values.
 
As a universally unique identifier for counterparties to financial transactions, the Legal Entity Identifier (LEI) itself can be considered a relevant attribute in many applications where authenticated transactions are relevant, both as a primary identifier for financial counterparties themselves, and potentially as an important attribute (e.g. contained within a digital certificate) for transactions by other types of subjects where a relationship with the entity identified by the LEI must be proven.

The LEI provides standardized reference data including but not limited to “name of the organization”, “legal form”, “authoritative validation and verification source”, “address” and especially information about the type of organization and its direct and ultimate parent organizations. Ultimately it shows any eligible entity in a network of ownership and other relationships.

Because the LEI is a quality-controlled unique identifier with no embedded intelligence, supported by a transparent infrastructure of local identity validation by trusted partners and a centralized open data challenge service, an LEI combined with other attributes might represent a pseudonymous identity for many users of digital services, such as business or non-Governmental organizations in the financial or other sectors.
 
As a “bridging identifier” between multiple databases, requiring no special access arrangements to use the LEI data, users of these Guidelines may integrate LEIs as part of their workflow and provide feedback to corroborate and improve the LEI data without the need to expose any confidential (e.g. personal or commercially sensitive) attributes.

**Suggested Change**:
GLEIF would strongly encourage users of the Digital Identity Guidelines to consider adopting the LEI as part of their risk assessment and credentialing practices, and to contribute to the development of the GLEIS as an open system.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Non-person identity is in the future roadmap.
