### ISSUE TITLE
Automated ID review for ILA3

### ISSUE THREAD

**Issue by kcourtney** [usnistgov/800-63-3#1671]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Acuant Corp
**Organization Type (see below for codes)**:
 2

**Document (63-3, 63A, 63B, or 63C)**:
63-3

**Reference (Include section and paragraph number)**:
 SP 800-63A Enrollment and Identity Proofing

**Comment (Include rationale for comment)**:
Manual document review can miss many fake IDs and is inefficient and would require training of potentially thousands of individuals. There are also hundreds of potential ID documents that change frequently that make it difficult for individuals to stay current in their identification techniques.

**Suggested Change**:
There are many vendors who provide automated ID review that is both fast and accurate.  An automated Identity document review with a manual or automated picture match to the individual offering the identity document should be the standard.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Validation and verification requirements in this document require more than just visual inspection, so we are already aligned with this comment.
