### ISSUE TITLE
Definitions 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#1673]
### All Fields Are Required
**Organization Name (N/A, if individual):** Kantara Initiative Inc. 

**Organization Type (see below for codes)**: 3
 
**Document (63-3, 63A, 63B, or 63C)**: 63-3. Revised Draft of the parent document for Special Publication 800-63-3

**Reference (Include section and paragraph number)**: Section 3 
 
**Comment (Include rationale for comment)**: There is not definition for "Token" and other terms. 
 
**Suggested Change**: Please validate that all the terms that appear in the document are defined in the Glossary.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Token is only used in change history to keep integrity of prior versions.  Authenticator definitions states - 'this was referred to as token.'.
