### ISSUE TITLE
Analysis on how the remote proofing capabilities match the proofing requirement of a RP

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#1675]
### All Fields Are Required
**Organization Name (N/A, if individual):** Kantara Initiative Inc. 

**Organization Type (see below for codes)**: 3
 
**Document (63-3, 63A, 63B, or 63C)**: 63-3. Revised Draft of the parent document for Special Publication 800-63-3.

**Reference (Include section and paragraph number)**: Section 5 
 
**Comment (Include rationale for comment)**: ) There is not an analysis on how the remote proofing capabilities that can be provided by a CSP match the proofing requirement of a RP. Therefore, it is difficult to have confidence that the requirements of a RP are being met.  As a consequence, RPs will need to resort to other mechanisms such as in person proofing.
 
**Suggested Change**: Include the required analysis so that RPs will be able to have confidence that their requirements are being met.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Agencies will determine their proofing requirements based on a risk assessment that drives the selection of IAL.  However, some additional informative language about the population(s) an agency serves compared with a CSP offering will improve this document.  It will not be an analysis, as that is up to the agency.
