### ISSUE TITLE
General Comment 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#1677]
### All Fields Are Required
**Organization Name (N/A, if individual):**  Kantara Initiative Inc. 

**Organization Type (see below for codes)**:3
 
**Document (63-3, 63A, 63B, or 63C)**: 63-3. Revised Draft of the parent document for Special Publication 800-63-3. 

**Reference (Include section and paragraph number)**:  General comment 
 
**Comment (Include rationale for comment)**: The overall publication should be restructured.
 
**Suggested Change**:  The overall publication be restructured into 5 parts as follows:
The first part being informative and descriptive and the four successive parts would be expressly normative, and would address IAL, AAL, FAL and agency considerations respectively.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We will retain the current structure.
