### ISSUE TITLE
SMS-based Two-Factor Authentication 

### ISSUE THREAD

**Issue by ghost** [usnistgov/800-63-3#168]
**Organization**:  3 = US Citizen

**Type**:  Free thinker

**Document 63B**:

**Reference (Include section and paragraph number)**:

5.1.3.2. Out of Band Verifiers

"If the out of band verification is to be made using an SMS message on a public mobile telephone network, the verifier SHALL verify that the pre-registered telephone number being used is actually associated with a mobile network and not with a VoIP (or other software-based) service. It then sends the SMS message to the pre-registered telephone number. Changing the pre-registered telephone number SHALL NOT be possible without two-factor authentication at the time of the change. OOB [Out of band verification] using SMS is deprecated, and will no longer be allowed in future releases of this guidance."

**Comment (Include rationale for comment)**:

Mobile Carriers are actually LESS secure than VOIP, since they can be pressured by the US Government to reveal personal information about us. Plus, I find most US Corporations to be sloppy with security, so it is better to do it yourself, using a collection of VOIP services.

If any citizen wants to use a VOIP number to conduct two-factor authentication, they should have the freedom to do so.  Millions of US citizens utilize VOIP instead of 'traditional' mobile phones.

**Suggested Change**:

Read this article:
http://thehackernews.com/2016/07/two-factor-authentication.html

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by GuruAllan** [comment]
I would like to point out that SMS is the ONLY technology that is marked as deprecated.  Simple passwords are NOT, so are we saying that 2FA with SMS is less secure than simple passwords?  Defining SMS as a lower level of assurance, is more appropriate.

There are many use cases where SMS adds significantly to the security of a 2FA, and although potential attack vectors should be acknowledged, deprecating it seems unduly harsh.  This also has the effect of removing the possibility of 2FA auth in many situations, where SMS is a reasonable option.  The guidelines should be encouraging 2FA,  not hindering it.

Making security decisions based on current implementations seems short sighted. "Mobile Network" is not defined in the document, and many devices may use multiple underlying transport mechanisms, making "mobile network" an undefined term.  Requiring verification against an undefined term, is unreasonable.  A simple statement saying "The security presented by the underlying transport should be considered when determining the strength of the assurance." should suffice.

It is also overly limiting to define the requirements for changing the number,  other than a statement that changing it should be done with appropriate security.  There are many possible use cases where changing the phone number might be done administratively, or as a result of an in person verification, and not based on 2FA.

**Comment by Deozaan** [comment]
Somebody needs to inform Social Security about this SMS-based 2FA deprecation. I just received this in my email today (emphasis added):

> Starting in August 2016, Social Security is adding a new step to protect your privacy as a my Social Security user.  This new requirement is the result of an executive order for federal agencies **to provide more secure authentication** for their online services. Any agency that provides online access to a customer’s personal information must use multifactor authentication.
> 
> When you sign in at ssa.gov/myaccount with your username and password, we will ask you to add your text-enabled cell phone number.  The purpose of providing your cell phone number is that, each time you log in to your account with your username and password, we will send you a one-time security code you must also enter to log in successfully to your account.
> 
> Each time you sign into your account, you will complete two steps:
> 
> Step 1:  Enter your username and password.
> Step 2:  Enter the security code we text to your cell phone (cell phone provider's text message and data rates may apply).
> 
> The process of using a one-time security code in addition to a username and password is one form of “multifactor authentication,” which means we are using more than one method to make sure you are the actual owner of your account. 
> 
> **If you do not have a text-enabled cell phone or you do not wish to provide your cell phone number, you will not be able to access your my Social Security account.** 
> 
> If you are unable or choose not to use my Social Security, there are other ways you can contact us.  To learn more, please review the Frequently Asked Questions found here.

Social Security is telling us that SMS-based 2FA will soon become mandatory, whether you have a cell phone or not. NIST is telling us that SMS-based 2FA is insecure. Therefore, NIST is telling us that Social Security's actions "to provide more secure authentication" are actually insecure.

**Comment by GuruAllan** [comment]
Social Security is telling us that SMS-based 2FA will soon become mandatory, whether you have a cell phone or not. NIST is telling us that SMS-based 2FA is insecure. <emphasis> Therefore, NIST is telling us that Social Security's actions "to provide more secure authentication" are actually insecure. </emphasis>

This is EXACTLY the wrong message we should be sending, and is why we should not be deprecating SMS.  It simply makes valid 2FA albeit less secure than a PKI,  is considerably better than simple username/password.
