### ISSUE TITLE
A more consistent approach to identifyng the parts of this suite, and in particular this part of it, would be to letter ALL parts, and 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1684]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Doc id, 
 
**Comment (Include rationale for comment)**:  A more consistent approach to identifyng the parts of this suite, and in particular this part of it, would be to letter ALL parts, and this first part would be the natural contender for being 63A, the others being sequential thereafter.  Such an approach would avoid the potential error of omission.
 
We belive there is a small risk that a reference to one of the docs in this suite might be mis-directed through the accidental omission of the differentiating letter.

**Suggested Change**: Re-identify as SP 800-63A and then the others in sequence (see also specific comment re §5).
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We intend to continue with the current naming conventions. Similar to #1677
