### ISSUE TITLE
Sent "As such ..." does not hold up in practice. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1685]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Exec Sumry, 7
 
**Comment (Include rationale for comment)**:  Sent "As such ..." does not hold up in practice.
 
This part of the suite directly addresses agencies in terms (primarily) of how to determine their required ALs, and therefore it ties closely to similar requirements focusing on agencies in the other parts of this suite.  For this reason, we believe there is merit in combining all requirements which are aimed at agencies into a separate document.  

**Suggested Change**: Place all requirements addreessing agencies into 
SP 800-63E (assuming the adoption of the preceding comment)
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
As the entities delivering identity services are ultimately accountable to the agency, all requirements are applicable for an agency. In some cases when the requirement can't be delegated to a provider, we specify agency rather than the generic CSP, RP, etc.
