### ISSUE TITLE
Description of SP 800-63-3 Digital Identity Guidelines - appears to conflict with claim in para 7 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1687]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Exec Sumry, 10
 
**Comment (Include rationale for comment)**:  Description of SP 800-63-3 Digital Identity Guidelines - appears to conflict with claim in para 7
 
Having normative content in here (inherently applicable to all services) and normative content in the 'xAL'-specific context is inconvenient from a conformance and assessment standpoint.  

**Suggested Change**: Could the normative content not be re-expressed in the other three parts, in their specific contexts, and this part be established as the informative but descriptive overview?
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
A statement about -3 being mandatory while the others stand alone would be beneficial
