### ISSUE TITLE
the statement refers to registration, but is equally true of authentication processes 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1688]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 2.3, last sent
 
**Comment (Include rationale for comment)**:  the statement  refers to registration, but is equally true of authentication processes
 

**Suggested Change**: replace the last word ("process") with"
"process and in subsequent authentication events"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE by another edit that deleted this paragraph altogether
