### ISSUE TITLE
"Each document stands alone" is a false statement 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1689]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 2.4, 
 
**Comment (Include rationale for comment)**:  "Each document stands alone" is a false statement
 
This statement seems to conflict with the fact that their are normative requirements in this doc which relate to those in the other parts.  See previous comments.

**Suggested Change**: Remove this statement
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
#1687
