### ISSUE TITLE
Confusion around federated assurance level and methods of assertion presentation

### ISSUE THREAD

**Issue by nckroy** [usnistgov/800-63-3#169]
**Organization**: 2

**Type**: Higher Education

**Document (63-3, 63A, 63B, or 63C)**: 63C

**Reference (Include section and paragraph number)**: Section 7 Par. 3, Section 8.1.1.2

**Comment (Include rationale for comment)**: First, Section 7 says that only indirect (back-channel) assertion delivery is acceptable above FAL 1.  This is unreasonable given that front-channel assertions which are signed and encrypted at the message level provide arguably a stronger level of assurance than assertions that are only protected at the transport level using, say, browser-trusted PKIX.

Second, Section 8.1.1.2 directly contradicts section 7, then saying that assertions signed by a CSP and encrypted for a specific RP are equivalent to a mutually-authenticated protected session.

If that's true (and it is), why is direct presentation of signed, encrypted assertions not acceptable above FAL 1?

**Suggested Change**: Allow bearer assertions using direct presentation which are signed and encrypted through FAL 3.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by sarahcec** [comment]
Hi Nick,

Thanks for your feedback. This is a good point. We're discussing options to allow for your use case, and we'll get back to you.

Sarah
