### ISSUE TITLE
Reference to IS29003 is not reliable - There will be no such standard in the immediate or near-term future. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1691]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Table, Wed Feb 01 00:00:00 EST 2017
 
**Comment (Include rationale for comment)**:  Reference to IS29003 is not reliable - There will be no such standard in the immediate or near-term future.
 
As of 2017-04-19, DIS29003 was NOT voted to progression as a Final Draft IS (SC 27 meeting, Hamilton NZ).  The voting was by a notable number of votes, not marginal.
The document will be published as a Tech Spec, but will not have the standing of an IS.  Furthermore, US experts within (e.g. Elaine Newton) and outside of NIST have argued against 29003, not least because it conflicts with this publication and we therefore would not want to adopt it as a US standard if ISO were to publish it as an IS.  It is therefore probably preferable to remove it from this table. 

**Suggested Change**: Remove the column headed [ISO 29003]
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Resolved via #1109
