### ISSUE TITLE
The statement is both wrong and overly-stated 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1692]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, para. 1
sent 2
 
**Comment (Include rationale for comment)**:  The statement is both wrong and overly-stated
 
How is this true, when pseudonymous ids are permitted at IAL1?  This statement carriues the presumption that the IdPV process is processing a non-pseudonymous applicant?  Furthermore for 'true' identities, such is only true to a certain degree, not absolutely.

**Suggested Change**: Replace with:
"Except when pseudonymous identities are permitted, identity proofing establishes, to a degree of certitude determined by the requirements of the level of assurance to which the proofing is being conducted, that a subject is who they claim to be"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
May not take edit as is, but qualifying is a good thing.

**Comment by paul-grassi** [comment]
OBE with past edits.
