### ISSUE TITLE
"If approved" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1694]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, para. 3
sent 4
 
**Comment (Include rationale for comment)**:  "If approved"
 
Is this the right phraseology? - it is unclear as to whom or what is the subject of this 'approval' (not a term generally used in this context).  

**Suggested Change**: It would be better to state: "If the applicant is successfully proofed by the CSP ..."  [see item (2) below, from which this language is stolen ... 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
May be better to just remove this paragraph per issue #1692
