### ISSUE TITLE
"privacy enhancing" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1695]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, para. 4
 
**Comment (Include rationale for comment)**:  "privacy enhancing"
 

**Suggested Change**: "privacy-enhancing"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
@dannago we are trying to catch all of these before you, but just in case...you're it.
