### ISSUE TITLE
"the claimant is a valid subscriber" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1696]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, para. 5
 
**Comment (Include rationale for comment)**:  "the claimant is a valid subscriber"
 
introducing 'subscriber' seems an unnecessary additional label

**Suggested Change**: Replace with:
"claimant is the legitimate party to whom the authenticators are bound"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
subscriber will remain in this suite.
