### ISSUE TITLE
"In a federated identity architecture" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1699]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, para. 11, item 3.
 
**Comment (Include rationale for comment)**:  "In a federated identity architecture"
 
Performance of an authentication is not limited to federations:  if it is, then all proofing/ authentication would be performed in a federated context

**Suggested Change**: ""
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Fair point.  Will update and include a second sentence on federation and assertions.
