### ISSUE TITLE
Authorization delegation and Reauthentication at AAL 2

### ISSUE THREAD

**Issue by nckroy** [usnistgov/800-63-3#170]
**Organization**: 2

**Type**: Education

**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 4.2.4

**Comment (Include rationale for comment)**: Reauthentication is required after 12 hours regardless of activity level, after 30 minutes of inactivity.  How does this work for delegated authentication, where, say, an HPC job is running on behalf of a user, with the user's access to, say, genomic data.  Does the user have to sit at the console the entire time the job is running and reauthenticate every 30 minutes?  Does this requirement mean a CSP can't assert AAL 2 if its users' credentials may be used on RPs for this type of job?  Does this make CSPs responsible for the actions of RPs that may, for example, generate high assurance grid credentials and run jobs on behalf of the CSP's users, based on the high assurance identity asserted by the CSP?

**Suggested Change**: Consider situations where high assurance credentials are needed for delegated use cases.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
Delegation of authorization isn't the same as authentication, the latter of which is the topic of this document and not the former. We've tried to be clear in a few places (like the mention of OAuth tokens in -B), but if this can be made more explicit in the text we're welcome to suggestions of how to communicate that.

**Comment by jimfenton** [comment]
Machine-to-machine authentication (as in the example where the HPC job needs access to the genomic data) is outside the scope of the SP 800-63 document set.

In this example, subscriber authentication would be required to submit the job, and particularly to access the results once the job has been completed. Access to results might involve a single  reauthentication if the submitting session still exists, or might involve a new authentication if not. But repeated reauthentication to allow the job to proceed is not required,
