### ISSUE TITLE
Not the best place for this text 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1700]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5, 
 
**Comment (Include rationale for comment)**:  Not the best place for this text
 
All of this clause appears to relate to agencies' use of digital ids, not to the risks which a provider of such services ought to take into consideration.  There is a good case for keeping THIS publication as an entirely non-normative discussion, overview, explanations, etc.

**Suggested Change**: Introduce a fifth part to the suite to address ALL matters directed at agencies (i.e. extracting agency-directed content from the present parts A, B, C, re-labelling all as A - E)
Remove this text to a Part E - prefix the title with "Agencies' "
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is due to the migration of M-04-04, which is about risk determination for relying parties.
