### ISSUE TITLE
"Low—at worst, limited" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1707]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.3.2, para. 2
 
**Comment (Include rationale for comment)**:  "Low—at worst, limited"
 
Though the difficulty of quantifying such adjectival 'values' is acknowledged, without any attempt to do so, these definitions are extremely vague, open to interpretation, and therefore inconsistent outcomes, where similar impacts are taken into consideration.  At the least, some guidance in each case as to what might constitute 'short-term' vs 'medium-term', 'serious' versus 'severe', etc., in the context of Fed agencies should be provided.

**Suggested Change**: Can some more tangible sense of scale be provided?  
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is M-04-04 language that will be retained.
