### ISSUE TITLE
"Agencies SHOULD ..." 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1708]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.4, para. 1
 
**Comment (Include rationale for comment)**:  "Agencies SHOULD ..."
 
there seems little point in making this statement about requirements if they are not to be enforced

**Suggested Change**: Replace 'SHOULD' with 'SHALL'
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is carry over language from M-04-04 and will remain.
