### ISSUE TITLE
"Agencies MAY determine ..." 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1710]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.4, para. 2
 
**Comment (Include rationale for comment)**:  "Agencies MAY determine ..."
 
is this sufficiently strong, or does it leave open an exit door?

**Suggested Change**: Rephrase as:
"Agencies SHOULD determine ..."  
and then at the end of this sentence 
"agency, they SHALL document their reasons for not implementing those parts of these requirements which they determine to exclude."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
It's a MAY to give agencies options if they determine, based on risk, that can implement less than required.  A SHOULD would indicate that we encourage this, which we don't.
