### ISSUE TITLE
"This section is normative" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1712]
**Organization Name (N/A, if individual)**: ID.me Inc.

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 6, 
 
**Comment (Include rationale for comment)**:  "This section is normative"
 
No doubt an oversight, but this clause is clearly normative in nature.

**Suggested Change**: "This section is normative"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
#1676
