### ISSUE TITLE
"vulnerabilities of impersonation" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1715]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Executive Summary, 
 
**Comment (Include rationale for comment)**:  "vulnerabilities of impersonation"
 

**Suggested Change**: Which are ?
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
There is a Threat/Mitigation chapter in -A, -B, and -C.
