### ISSUE TITLE
"proving yourself, repeatedly proving it is you logging in is just as complicated and vulnerable as the original claim and proof of identity" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1716]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Executive Summary, 
 
**Comment (Include rationale for comment)**:  "proving yourself, repeatedly proving it is you logging in is just as complicated and vulnerable as the original claim and proof of identity"
 

**Suggested Change**: not sure getting the purpose of the stmt ;
pls, consider re-stating, using FPL guidelines.
From what is understood so far: there is no intent to prove it is myself ; on the contrary, the intent is to prove that I'm who I want you to think I'm.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will rewrite for clarity.
