### ISSUE TITLE
"assurances that subject that is accessing service today is same as that which accessed service yesterday" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1717]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Executive Summary, 
 
**Comment (Include rationale for comment)**:  "assurances that subject that is accessing service today is same as that which accessed service yesterday"
 

**Suggested Change**: Do you, as a provider, really care if this is me or my wife consuming your service (as a returning customer) ? As long as you properly reimbursed, naturally, you shouldn't be.
Pls, consider re-phrasing.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Yes we do care from an authentication perspective. We are not advocating for shared accounts, quite the contrary.
