### ISSUE TITLE
"access digital government services" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1718]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Executive Summary, 
 
**Comment (Include rationale for comment)**:  "access digital government services"
 

**Suggested Change**: Is this additional constraint intentional ?
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Unclear what constraint is being referenced.
