### ISSUE TITLE
"offer multiple opportunities for impersonation" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1719]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Executive Summary, 
 
**Comment (Include rationale for comment)**:  "offer multiple
opportunities for impersonation"
 

**Suggested Change**: Yes, this is the intent: to present service provider with persona. 
(Should be contrasted with identity theft.)
Or the stmt has a different purpose ? In which case, consider re-stating.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Suggested change not provided.
