### ISSUE TITLE
"subject that is accessing the service today is the same as that which accessed the service yesterday" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1720]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Introduction, 
 
**Comment (Include rationale for comment)**:  "subject that is accessing the service today is the same as that which accessed the service yesterday"
 

**Suggested Change**: see line #7
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
#1717
