### ISSUE TITLE
"enrollment proceeds as follows" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1723]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 
 
**Comment (Include rationale for comment)**:  "enrollment proceeds as follows"
 

**Suggested Change**: pls, consider well indented, tabular formatting
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
-A has a much more detailed, step-wise description of enrollment.
