### ISSUE TITLE
"authenticators may be … provided by a third party" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1724]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 
 
**Comment (Include rationale for comment)**:  "authenticators may be … provided by a third party"
 

**Suggested Change**: which 3rd party this stmt refers to ? is there a responsibility matrix assisting in determining who does what ?
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
any 3rd party that the RP trusts and the CSP can validate.
