### ISSUE TITLE
"verified attribute values, verified attribute claims" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1726]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 
 
**Comment (Include rationale for comment)**:  "verified attribute values, verified attribute claims"
 

**Suggested Change**: semantical difference, unless the stmt implies smth else ;
pls. clarify
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
granted, this list represents attributes, but we want to be clear.  See definitions for difference between value and claims.
