### ISSUE TITLE
"make access control or authorization decisions" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1728]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 
 
**Comment (Include rationale for comment)**:  "make access control or authorization
decisions"
 

**Suggested Change**: (here and elsewhere) how AC decision differs from authz decision ?
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Good point. This is old language, which I think was trying to accomplish a subtle differentiation. Access control (subset of authZ) to gain access to a function.  AuthZ decision to determine if someone is eligible for a benefit, for example.  But authZ is the right term to save the reader from having to make up a distinction.
