### ISSUE TITLE
"in some cases in attributes about the subscriber" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1729]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 
 
**Comment (Include rationale for comment)**:  "in some cases in attributes about the subscriber"
 

**Suggested Change**: rather, in attribute's value ;
attributes are part of the identity, making confidence in attributes implicit.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
While we chose not to make the attribute value changes in other issues, this is a good place to make the distinction obvious.  Thank you.
