### ISSUE TITLE
"optionally obtain claimant attributes" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1732]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 
 
**Comment (Include rationale for comment)**:  "optionally obtain claimant attributes"
 

**Suggested Change**: (here and elsewhere) 
rather, attribute's values  
or value assertions (born after certain date, T/F ?)
attrib is key/value pair ;
you do not obtain / question key, but its value.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
#1749
