### ISSUE TITLE
"prior to authentication of claimant" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1733]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 
 
**Comment (Include rationale for comment)**:  "prior to authentication of claimant"
 

**Suggested Change**: rather, prior to reaching authn decision
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Suggested change is not accurate.  Unauthenticated user accesses RP.  RP asks CSP `please authenticate this user and provide me attributes a, b, and c`.
