### ISSUE TITLE
"requested to consent to release of those attributes" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1734]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 
 
**Comment (Include rationale for comment)**:  "requested to consent to release of those attributes"
 

**Suggested Change**: might cause a confusion: provided identity is a collection of attributes, subject might be unaware of the correlation (~s)
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Correlation is not the subject of this sentence.  As stated throughout the suite, any user attribute that is under management in the 'system' can only be released when the user consents.
