### ISSUE TITLE
"local messages between applications running on the same system rather than protocols over shared, untrusted networks" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1735]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 
 
**Comment (Include rationale for comment)**:  "local messages between applications running on the same system rather than
protocols over shared, untrusted networks"
 

**Suggested Change**: implying it won't work using remote messaging or over trusted n/w ?
pls, consider re-stating
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
No. All components in a single system == local messages. RATHER THAN, all components separated, possibly running on verifier.com, csp.gov,.
