### ISSUE TITLE
"repeat the enrollment process to obtain a new authenticator and credential" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1736]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 
 
**Comment (Include rationale for comment)**:  "repeat the enrollment process to obtain a new authenticator and credential" 
 

**Suggested Change**: possibly even new identity, as in case with USAJOBS : once you fail to authn (due to various reasons),
it locks your accnt, forcing to run registration process anew resulting in a new identity. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Correct, that is exactly what we are stating.  USAJobs is a simple creation of a new account.  At higher IALs, it would be the same identity.
