### ISSUE TITLE
"If the applicant is successfully proofed and a credential is created by a CSP and authenticator(s) are bound to it" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1737]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.2, 
 
**Comment (Include rationale for comment)**:  "If the applicant is successfully proofed and a credential is created by a CSP and authenticator(s) are bound to it"
 

**Suggested Change**: is there a UC of unsuccessful credential creation / unbound authenticator, besides malfunction ?
If not, consider re-stating, as this doc should not address exceptions.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is a good catch of old language, prior to breaking apart LOA, that should be resolved.
