### ISSUE TITLE
"As such, whereas cryptographic keys ... user-chosen passwords may be vulnerable" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1738]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.3, 
 
**Comment (Include rationale for comment)**:  "As such, whereas cryptographic keys ... user-chosen passwords may be vulnerable"
 

**Suggested Change**: symmetric (aka session) keys vs pwd: the main difference is TTL and 
fatigue (vs length, as I can request a phrase); 
pls. consider re-stating.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
no recommended change
