### ISSUE TITLE
Reauthentication, Authentication and Proof of Presence

### ISSUE THREAD

**Issue by ergood** [usnistgov/800-63-3#174]
**Organization**: 2

**Type**: Education

**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: Definitions; 7 Session Management

**Comment (Include rationale for comment)**:
This comment initiated from reading through and considering reauthentication use cases. The documents do an impressive job of addressing -- directly and indirectly -- many of the complex edge use cases around "reauthentication". However, I had some concern around the description of "Session Management".

Section 7 states: "_The session MAY be continued through a reauthentication event (described in section 7.2), wherein the user repeats some or all of the initial authentication event, **thereby asserting their presence again**_." [emphasis added] This statement implies that authentication is also the act of asserting presence. 

However, authentication is defined as "_The process of establishing confidence in the identity of users or information systems._" It is not defined as being required to establish presence. (Other than the section 7, the only other use of the term "presence" related to authentication is in the definition of "Authentication Time" in assertions (800-63c section 5).) 

I think the totality of the text and the individual constraints on single factor methods makes it reasonably clear that proof of presence is part of the expectation of authentication, but to some extent you have to "want" to know this to do the necessary cross-referencing to substantiate the requirement. 

If the intent of "authentication" is that it should explicitly establish confidence in the identity _and presence_ of a user, I think it would be useful to clarify this to help guide implementors. 

Similarly, if "reauthentication" is considered a distinct type of event from authentication, I think it would be useful guidance to more prominently clarify that it is focused on verifying user presence rather than identity (or perhaps it is weakly verifying identity). 

**Suggested Change**:
1) Define reauthentication in the definitions and terms section, and clarify the distinction between reauthentication and authentication.  

2) Include "proof of presence" in the definition of Authentication (and possibly in the definition of Reauthentication). 

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
We like the idea of consistency and the explicit statement regarding presence, so we are accepting both.  Thanks for this.

**Comment by ergood** [comment]
I also just noticed that the language in 4.1.4 ("Reauthentication" for AAL1) and 4.3.4 should be reviewed for consistency after any changes to definitions. Because of the requirements, the descriptions are less ambiguous in those sections, but redefining the terms could still impact them both.

**Comment by jimfenton** [comment]
User authentication (as distinct from machine-to-machine authentication) does require presence; that is implied by the requirement to enter a memorized secret, control a physical authenticator, or present a biometric. The section on reauthentication emphasizes presence because it is the continued presence of the authenticated user that is the primary goal: leaving one's physical authenticator connected to the endpoint is not sufficient. User activity can be a proxy for continued presence, up to a point, which is why reauthentication is required more often in the absence of activity.
