### ISSUE TITLE
"prevent a subscriber who is registered from repudiating the enrollment" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1740]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.3, 
 
**Comment (Include rationale for comment)**:  "prevent a subscriber who is registered from repudiating the enrollment"
 

**Suggested Change**: IMO, this is a very ternary objective due to its reactive nature
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
no recommended change.
