### ISSUE TITLE
"usually by interacting with the CSP" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1741]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.3.3, 
 
**Comment (Include rationale for comment)**:  "usually by interacting with the CSP" 
 

**Suggested Change**: which might be asynch: in distributed environments affiliated CSP might issue a revocation list (similar to CRL) of "expired" accounts in advance 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Sure, but we say usually and don't specify that the interaction is real-time, offline, asysch, synch, so I think we are ok here.
