### ISSUE TITLE
"masquerading as a legitimate verifier" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1742]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.3.3, 
 
**Comment (Include rationale for comment)**:  "masquerading as a legitimate verifier"
 

**Suggested Change**: this alone won't help the impostor, as it has to issue authz ; so it has to be MiM
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
undetermined what the specific recommended change would be.
