### ISSUE TITLE
"have many significant benefits" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1743]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.4, 
 
**Comment (Include rationale for comment)**:  "have many significant benefits"
 

**Suggested Change**: there must be a reason, why NOT (otherwise we won’t be discussing it here). 
So what is its deficiency ?
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
It remains an agency decision to federate or not.  We would state that an agency should always federate, even if they manage some portion of the users themselves.
