### ISSUE TITLE
"verifier is responsible for ensuring that information contained in assertion can only be extracted by RP" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1747]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.4.1, 
 
**Comment (Include rationale for comment)**:  "verifier is responsible for ensuring that information contained in assertion can only be extracted by RP"
 

**Suggested Change**: passing such info (ex.: OpenID Connect JSON), implies RP has to support either 
- encryption 
or 
- tunneling ;
if sec comm cannot be established,
does it mean verifier's responsibility is NOT to send ?
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
In federations, as discussed in -C, metadata is exchanged to make sure verifiers can encrypt to a specific RP. This section is informative and doesn't provide error handling requirements.
