### ISSUE TITLE
"attributes, if any, are self-asserted" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1749]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.2, 
 
**Comment (Include rationale for comment)**:  "attributes, if any, are self-asserted"
 

**Suggested Change**: rather, their values (see #19)
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is technically correct, but the document uses the term attributes throughout. Unless there is significant pushback, this shorthand seems appropriate, especially with the inclusion of definitions for attribute.
