### ISSUE TITLE
Proof of Presence and Single Factor Cryptographic Devices

### ISSUE THREAD

**Issue by ergood** [usnistgov/800-63-3#175]
**Organization**: 2

**Type**: Education

**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 5.1.6. Single Factor Cryptographic Devices

**Comment (Include rationale for comment)**:
This comment is closely related to my previous comment (#174) about Proof of Presence; enough that perhaps it should be captured in the same issue. However, I can imagine one being declined and the other being accepted, so I have entered them separately.

Section 5.1.4, _Single Factor OTP Devices_, explicitly states that the category "_...includes software-based OTP generators installed on devices such as mobile phones._" 

Section 5.1.6, _Single Factor Cryptographic Devices_ is silent on software implementations. A reader might reasonably infer that software installed on a networked device would meet the requirement of section 5.1.6. However, it's not clear that this is intended. 

Given that 5.1.6.1 goes on to say that Single Factor Cryptographic Devices SHOULD require manual activation (rather than MUST), software installed on a network-connected device could be used in a way that does not provide the kind of authentication proofs intended.

**Suggested Change**:
[One or the other, not both. I'd recommend the second approach 2] 
1) Clarify that software running on a networked device does not meet the requirements of Single Factor Cryptographic Devices in 63b 5.1.6. 

2) Require that when implemented as software running on a networked device, manual activation MUST be required for the software to be considered a Single Factor Cryptographic Device (rather than SHOULD, as is currently specified.)

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
Resolved by usnistgov/800-63-3#302

**Comment by jimfenton** [comment]
The resolution is (1). Software cryptographic authenticators require the protection of the secret key through a memorized secret. The use of a memorized secret to unlock a secret key makes it multi-factor, as described in section 5.1.7. It is considered too risky to accept authentication using an unprotected secret key.

The wording is being changed to emphasize that a single-factor cryptographic  authenticator is a physical device, and the wording for OTP authenticators is being changed to more consistently state that OTP generators may be software-based.

**Comment by sshorter** [comment]
For consistency with prior 800-63 revisions, this resolution should also support the use of a biometric to unlock the token.

**Comment by jimfenton** [comment]
Interesting point. Any such use of a biometric to unlock the secret key would need to be protected against endpoint compromise: the activation key couldn't be just stored on the endpoint where it would be as vulnerable as the secret key it's protecting. Perhaps in a secure enclave of some sort. Remote verification of the biometric wouldn't be possible because of the requirement in 5.2.3 to identify the device with approved cryptography, which effectively makes the software cryptographic authenticator moot.

There does seem to be a situation where a locally-verified biometric could be used to release an activation key for a software-based cryptographic authenticator's private key. We will try to cover that case.

**Comment by jimfenton** [comment]
I just reviewed the language under 5.1.7.1. Multi-Factor Cryptographic Software Authenticators. It does explicitly support the use of a biometric to unlock the secret key. So I mis-stated things above where I said it had to be a memorized secret.
