### ISSUE TITLE
"resume information is available in later sessions ... agency must select an AAL that requires MFA" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1750]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.3, 
 
**Comment (Include rationale for comment)**:  "resume information is available in later sessions ... agency must select an AAL that requires MFA"
 

**Suggested Change**: USAJOBS does not and asking for MFA is impractical ;
remains unclear what UC this stmt addresses, provided online submission is discussed later.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is a hypothetical example of a solution that provides personal information, in the form of a resume, back to the submitter in future sessions.  Therefore, MFA is required but proofing may not be.
