### ISSUE TITLE
"mission capability degradation to the extent and duration that the organization is able to perform its primary functions with noticeably reduced effectiveness" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1751]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.3.2, 
 
**Comment (Include rationale for comment)**:  "mission capability degradation to the extent and duration that the organization is able to perform its primary functions with noticeably reduced effectiveness"
 

**Suggested Change**: what is it, but a hiccup, which any agency is experiencing every so often ;
if true, such impact evaluates to none
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is language from M-04-04 that will be retained.
