### ISSUE TITLE
"resolve to a unique identity" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1754]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 6.1, 
 
**Comment (Include rationale for comment)**:  "resolve to a unique identity"
 

**Suggested Change**: aren't identities unique by definition, as dup keys are disallowed ?
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Resolution in the context of identifying the real human subject as part of the proofing process.  Yes, technically duplicates are not allowed, but this is about ensuring that attributes collected will resolve uniquely.  You can't just collect first/last as John Smith will never uniquely resolve.
