### ISSUE TITLE
Following formal disposition, another round of proof-reading might be waranted. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1757]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: All, 
 
**Comment (Include rationale for comment)**:  Following formal disposition, another round of proof-reading might be waranted.
 

**Suggested Change**: Following formal disposition, another round of proof-reading might be waranted.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We have minimum 2 white glove reviews by independent teams, so we agree! :)
