### ISSUE TITLE
7th bullet - Clarification on the use of independent channels and devices as "something you have".  Since 63B added language explicitly disallowing email as an acceptable authenticator, add language in the Change History that it is no longer allowed

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1759]
**Organization Name (N/A, if individual)**: Social Security Administration (SSA)

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 2.6.3
 
**Comment (Include rationale for comment)**:  7th bullet - Clarification on the use of independent channels and devices as "something you have".  Since 63B added language explicitly disallowing email as an acceptable authenticator, add language in the Change History that it is no longer allowed

Many valid arguments have been made for and against the use of email address as a 2nd factor under 800-63-2, since the guidance on the out of band requirements were subject to interpretation.  

**Suggested Change**: Please add something like, "email has been removed as an acceptable second factor" to this bullet in the Change History Section. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is a good edit since this is an actually removed requirement.
