### ISSUE TITLE
Figure 4-1 terminology

### ISSUE THREAD

**Issue by ctilton2** [usnistgov/800-63-3#1777]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**:
 
**Document (63-3, 63A, 63B, or 63C)**:

**Reference (Include section and paragraph number)**:
 
**Comment (Include rationale for comment)**:
 
**Suggested Change**:
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by ctilton2** [comment]
Figure 4-1 shows an IDP; however, the preceding text describes the process in terms of a CSP.  I think these should match.

**Comment by paul-grassi** [comment]
Will be resolved via #1193.
