### ISSUE TITLE
Verifiers SHALL NOT send the password back to the user by email.

### ISSUE THREAD

**Issue by rechlin** [usnistgov/800-63-3#1782]
### All Fields Are Required
**Organization Name (N/A, if individual):**
N/A
**Organization Type (see below for codes)**:
 Self
**Document (63-3, 63A, 63B, or 63C)**:
63B
**Reference (Include section and paragraph number)**:
5.1.1.2 Memorized Secret Verifiers
- This information could be accompanied by its own explanation, if needed, and put in a separate section.
**Comment (Include rationale for comment)**:
 Most companies send an email to you when you have registered a username, which might be an email address, and password.
A very few include the password in the email message.
It is also possible that some government departments do this.
Without a rule in document 63B that they shall not do this, they may continue to do it.

**Suggested Change**:
 Add a requirement similar to the following:
- Verifiers SHALL NOT send the password back to the user by plain text email.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
If they're following the storage requirements (see paragraph that begins "Verifiers SHALL store memorized secrets...") they won't be able to do that anyway.
