### ISSUE TITLE
Second Address of Record?

### ISSUE THREAD

**Issue by jaspenc** [usnistgov/800-63-3#18]
**Organization**: 2

**Type**: Procedural

**Reference (Include section and paragraph number)**: SP 800-63A  Section 4.5.5

**Comment (Include rationale for comment)**:  In the last bullet of this section it states: "A notification of proofing SHALL be sent via a different address of record than the destination of the enrollment code."
I'm not sure I understand this.  Can you give an example of a different address of record?  Also, proofing is not defined in the glossary, I'm not sure what is being delivered here.  My concern is that not every individual will have a 'second address of record'.

**Suggested Change**:

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
We will clarify this requirement and provide considerations when a second address of record is not available.
