### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by gggustafson** [usnistgov/800-63-3#1806]
### All Fields Are Required
**Organization Name (N/A, if individual):NA**

**Organization Type (see below for codes)NA**:
 
**Document (63-3, 63A, 63B, or 63C)**:

**Reference (Include section and paragraph number)**:
 
**Comment (Include rationale for comment)**:
 
**Suggested Change**:
 
---Review links and repair in References
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Same as #699
