### ISSUE TITLE
MFA concept, revisited

### ISSUE THREAD

**Issue by LionDude** [usnistgov/800-63-3#181]
**Organization**: Industry (Financial)

**Type**: MFA Concept, a different perspective

**Document (63-3, 63A, 63B, or 63C)**:  63B

**Reference (Include section and paragraph number)**: 4.2.1

**Comment (Include rationale for comment)**:  in combining two SF authenticators, it's not necessary all the time or absolutely that both authenticators are ALWAYS invoked to be completed in  the same authentication process flow. There may be some authentication requirements where the second SF authenticator  can be conditionally invoked, depending on overall security requirements of the application. The essential point is that both SF authenticator mechanisms are available for the application to use within a single authentication workflow. Ultimately, it all depends on the overall security/risk requirements of the application.  

**Suggested Change**: Following should be included in the section narrative:  In combining  two SF (one is Memorized Secret Authenticator and other is possession-based authenticator), it's possible to CONDITIONALLY invoke the second factor within the same authentication process, IF AND ONLY IF, the application detects "device identity change, geo-location change, etc."  And this type of authentication process should still be considered an MFA implementation flavor. IOW, the second SF is built into the application but the application has to make the decision as to when to invoke the second SF.
Obviously, CONDITIONAL invocation of the second SF authenticator is less secure than when requiring both two SF authenticators ALWAYS in the same authentication process flow. But then again, from a risk perspective, CONDITIONAL invocation of the second SF, may be appropriate for some types of applications, depending on risk criticality. In fact, not all MFA authenticators (where out-of-band is used as 2 SF) provide the same amount of security but they are MFA implementations just the same. Conceptually, whether the 2nd SF authenticator is invoked Conditinally, or Always, this authentication flow is (and should) still considered MFA. 
Just to clarify further, a colleague postulated the following: Generally, in a common remote login situation, a Login/Password ("what you know") is required together with token-code on a RSA Physical Secure-ID ("what you have") to complete the authentication flow. But, from a risk requirements standpoint, some application may only require the RSA Token to be invoked under certain conditions,  if the application detects a change in "geo-location or device". Is the above situation, where there's  conditional invocation of the "what you have" authenticator, still MFA implementation? 

---t

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
**Device identity change**: If the device identity can be _securely_ established and has been securely associated with the subscriber's account, it can already be used as a "something you have" authentication factor. This can be done if the device contains a multi-factor software cryptographic authenticator as described in section 5.1.7 or has a single- or multi-factor cryptographic device embedded in it as described in sections 5.1.6 or 5.1.8. Use of facilities like browser cookies or local storage for this purpose is not sufficiently secure to establish device identity.

**Geolocation change**: There is no sufficiently secure means for obtaining the geolocation of the user to allow the absence of a change to bypass second-factor authentication. Geolocation may be used to increase confidence within a given AAL, however.

**Comment by LionDude** [comment]
Thank you, Jim.

If I may, ...

from a conceptual standpoint, in an idealized authentication situation where the invocation of the "something you have" is conditional (as addition to the "what you know" factor), will this implementation architecture still be considered multifactor authentication (assuming all other factors are equal)?

Please advise.

Thanks.

LionDude
