### ISSUE TITLE
Authentication dead-lock

### ISSUE THREAD

**Issue by lineumann** [usnistgov/800-63-3#183]
**Organization**: 2

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63C

**Reference (Include section and paragraph number)**:

**Comment (Include rationale for comment)**:
The document deals with the issue of transferring assertions from CSP to RP to enable authentication of the subscriber by CSP (instead of direct authentication by RP). 
Different presentation types (direct/indirect) requires use of several “authenticated protected channels” (two or four). 
Definition of an authenticated protected channel requires authentication. This means that transferring results of authentication requires use of another authentication.
The definition of Authenticated Protected Channel requires extremely high security of the channel “Authenticated protected channels provide confidentiality and man-in-the-middle protection” but the reality is different. Authentication is based on authentication of “the recipient (server)” by “the initiator of the connection (client)”. The client can be an attacker. 
Many attacks of TLS based communication are known including phishing. 
The risk evaluation and classification of Federation Assurance Level is based on a prerequisite of very high security of Authenticated Protected Channel. But the reality is different.
The risk evaluation should include limited security of the communication of RP and CSP thought client browser. 
Significantly different FAL and their relation to IAL and AAL should be the result.

The most important parts of the document is enclosed.

DRAFT NIST Special Publication 800-63C
Digital Authentication Guideline
Federation and Assertions
1. Introduction
   Assertions are presented over a network through the use of an identity federation protocol. In a federation protocol, the subscriber does not authenticate directly to the RP using credentials as described in this document suite. Instead, the federation protocol defines a mechanism for an RP to request that a CSP generate an assertion for the currently-present subscriber, by way of having the subscriber authenticate to the CSP.
2. Definitions and Abbreviations

Authenticated Protected Channel
A communication channel that uses approved encryption where the initiator of the connection (client) has authenticated the recipient (server). Authenticated protected channels provide confidentiality and man-in-the-middle protection and are frequently used in the user authentication process. TLS [BCP 195] is an example of an authenticated protected channel when the certificate presented by the recipient is verified by the initiator.

6.1. Indirect presentation
Conveyance of the assertion reference from the CSP to the subscriber as well as from the subscriber to the RP SHALL be made over an authenticated protected channel. Conveyance of the assertion reference from the RP to the CSP as well as the assertion from the CSP to the RP SHALL be made over an authenticated protected channel.

6.2. Direct Presentation
Conveyance of the assertion from the CSP to the subscriber as well as from the subscriber to the RP SHALL be made over an authenticated protected channel.

**Suggested Change**:
 The risk evaluation should include limited security of the communication of RP and CSP thought client browser. 

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
The "authentication" in the "authenticated protected channel" definition is, as stated, the verification of the TLS certificate of the server. Yes, an attacker can validate this certificate just as well as a legitimate user, but that doesn't have any bearing on the security of the assertion. 

We do account for the risk of communication through the browser by separating the considerations of front channel (through browser) vs. back channel (non-browser) communications in direct and indirect assertion presentation mechanisms. This is precisely why we consider a direct presentation mechanism (through the browser) to be less secure, all else being equal.

**Comment by lineumann** [comment]
The "only" issue is that the attacker can use victim's assertion or assertion reference. It is not important if the attacker uses assertion itself or assertion reference. In both cases it is accepted by RP instead of victim.  
The indirect assertion presentation mechanisms only adds additional threads, additional opportunity to attacker compared to direct assertion presentation mechanisms if the possibility to steal the assertion is taken into account. 
The communication between RP and CSP goes through the browser in all cases.
