### ISSUE TITLE
Holder-of-key assertion security

### ISSUE THREAD

**Issue by lineumann** [usnistgov/800-63-3#184]
**Organization**:2

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63C

**Reference (Include section and paragraph number)**:
5.1.1. Holder-of-Key Assertions

**Comment (Include rationale for comment)**:
 The definition of a holder-of-key assertion is not consistent with the security evaluation. 
The definition do not include any relation of the key with authentication made by CSP. The attacker can use its own key and misuse the assertion e.g. if attacker is MITM on the channel between victim’s browser and CSP.

**Suggested Change**:
Change definition or security evaluation. 

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
The key must be referenced by the assertion itself, and the assertion needs to be validated and verified by the RP as having come from the CSP. Therefore it's the CSP's responsibility to bind the key used in HoK to the assertion. The attacker cannot use their own key.

**Comment by lineumann** [comment]
It is difference between binding the key and prove possession of the key by CSP.  The prove possession is not requested.  CSP can be forced by attacker to bind attacker's key instead of authenticated victim's key to assertion in the case e.g. if the attacker is on the end of TLS channel used by CSP and TLS key is used. I.e. if the attacker is between the authenticated victim and CSP.
