### ISSUE TITLE
FIPS References

### ISSUE THREAD

**Issue by jricher** [usnistgov/800-63-3#1852]
From @RGalluzzo: 

May get lost because it is in a "outdated" item, but Jim Foti changed all of the FIPS 140 references to "January 11, 1994" in the red-lined word document we were provided. Given he made the same edit in multiple volumes, I would imagine he had a reason.

**Comment by paul-grassi** [comment]
@RGalluzzo @jricher he sent me another note with an updated date.  We are good.

**Comment by paul-grassi** [comment]
@RGalluzzo @jricher check that, looks like Ryan reverted.  I'll fix as I want to add Danna to acknowledgements anyway.
