### ISSUE TITLE
Authenticator user feedback

### ISSUE THREAD

**Issue by FIDOAlliance** [usnistgov/800-63-3#186]
FIDO Alliance

800-63-3B section 5.1.7.1

We are concerned that this requirement (i.e. not allowing the authenticator to give feedback to the user but requiring the RP doing that) may lead to bad user experience especially when using biometric modalities.  It is important for the user to get spontaneous feedback, e.g. when swiping a wet finger or the wrong finger.  

We understand its goal for protecting against brute force/presentation attacks, but we believe countermeasures against such attacks should be implemented inside the authenticator (still giving user feedback).
## Note: At this time, FIDO and most smartphones give the user a clear and direct feedback on matching issues/errors.

Organization 2 = Industry

**Comment by paul-grassi** [comment]
Fixed by pull #104
