### ISSUE TITLE
Expiration of authenticators

### ISSUE THREAD

**Issue by FIDOAlliance** [usnistgov/800-63-3#187]
FIDO Alliance

800-63-3B section 6.3

“CSP’s SHOULD issue authenticators that expire”. 

It would be helpful to give some indications for why expiration of authenticators is required as people want guidance on practical timeframes.
1. Instead of requiring authenticators to expire, the Authenticator BINDING could expire as well.  This should be clarified.
2. In section 6.1. It is stated that CSPs provide authenticators followed by an explanation what the difference to issuance of authenticators is.  The sentence above should use the term “provide” instead of “issue”.

Organization:  2 = Industry

**Comment by jimfenton** [comment]
1. There is not a strong motivation to make a general recommendation for authenticator expiration, especially in view of the recommendation against expiration of memorized secrets. This has been changed to a MAY.
2. The wording was inconsistent between provide and issue, but issue seemed more natural in this context. Made wording clearer that the two words are equivalent in this context.

**Comment by jimfenton** [comment]
Resolved by https://github.com/jimfenton/800-63-3/commit/407c41362fc4e1543c81f9e66643da7c27b8aa28 in #320
