### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by FIDOAlliance** [usnistgov/800-63-3#188]
FIDO Alliance

800-63-3B 
section 8.2, Table 5, Entry Eavesdropping

The sentence “Use authenticators that generate authenticators based on an authenticator input value or challenge” is difficult to understand.

The term Authenticator was defined as “Something that the claimant possesses and controls (typically a cryptographic module or password) that is used to authenticate the claimant’s identity. In previous versions of this guideline, this was referred to as a token.”.

It might be better to define separate terms for the first use of the term Authenticator (see above, e.g. FIDO Authenticator) and the second use (e.g. signed challenge, bearer-token etc.) of it. 

---

Organization:  2 = Industry

**Comment by jimfenton** [comment]
Thanks; this stems from the old use of _authenticator_ as the output from a token. The new term for this is _authenticator output_. So the new text reads, "Use authenticators whose output is based on an input value or challenge."
