### ISSUE TITLE
Claimant verifying OOB authenticators?

### ISSUE THREAD

**Issue by sshorter** [usnistgov/800-63-3#1883]
The final bullet under Section 5.1.3.1 of 63B indicates a scenario in which the claimant responds with a yes/no as to the consistency of secrets sent over two channels.  

It's not clear exactly how the validation of the claimant response is expected to be processed, there seem to be two alternatives.

1. If the secrets are always consistent, then  a "yes" answer would then result in successful authentication.  So an adversary can answering "yes" to pass authentication.

2. If on the other hand it's a stochastic "claimant has to guess correctly whether or not the second channel secret was consistent", then the adversary still has a 50/50 chance of passing authentication.

Strongly recommend removing this option from the section.

**Comment by jimfenton** [comment]
In that bullet, the confirmation of the secrets match is prompted by the authenticator (probably a smartphone app or something similar), not the primary channel. So if the rightful subscriber is in control of the authenticator, the adversary would not be able to answer "yes". Perhaps the text could be clearer about this.
