### ISSUE TITLE
SP-800-63-3B AAL3 inconsistency

### ISSUE THREAD

**Issue by identitymonk** [usnistgov/800-63-3#1895]
_Section 4.3 Authenticator Assurance Level 3_ intro states that:

> AAL3 authentication SHALL use a hardware-based authenticator and an authenticator that provides verifier impersonation resistance — the same device MAY fulfill both these requirements

This means that the combination "ONE hardware-based authenticator that DOES NOT offer verifier impersonation resistance AND ONE software-based authenticator that DOES offer verifier impersonation resistance" is a valid AAL3 solution. But the section _4.3.2 Authenticator and Verifier Requirements_ states that:

>  **All** cryptographic device authenticators used at AAL3 **SHALL be** verifier impersonation resistant 

Which is inconsistent

**Comment by jimfenton** [comment]
Should probably be "At least one authenticator used at AAL3 SHALL be verifier impersonation resistant."
