### ISSUE TITLE
Poor rendering on mobile devices

### ISSUE THREAD

**Issue by jimfenton** [usnistgov/800-63-3#1899]
When viewed at https://pages.nist.gov/800-63-3, the documents render very poorly on mobile devices such as iPhones: text is microscopic, and only a small portion of the width of the screen is used. Reported by Ian Glazer.

![image](https://user-images.githubusercontent.com/1020212/29041891-85256590-7b69-11e7-803f-b6bf90ea4c10.png)

**Comment by jricher** [comment]
Can confirm on android as well, likely missing viewport width directives.

**Comment by jricher** [comment]
Directive in question: `<meta name="viewport" content="width=device-width, initial-scale=1.0">`
