### ISSUE TITLE
SMS Deprecation 

### ISSUE THREAD

**Issue by FIDOAlliance** [usnistgov/800-63-3#190]
FIDO Alliance

800-63-3B section 5.1.3.2 

The FIDO Alliance strongly supports the decision to deprecate use of OOB AuthN using SMS.  The security weaknesses of SMS-based authentication have been well-documented over the last two years by industry, academic and government experts.  Industry is responding with next-generation authentication approaches that are much stronger and easier to use, and that do not have the vulnerabilities associated with SMS.  

---

Organization: 2 = Industry

**Comment by paul-grassi** [comment]
@FIDOAlliance thanks!
