### ISSUE TITLE
authorization credential

### ISSUE THREAD

**Issue by paul-grassi** [usnistgov/800-63-3#1904]
Used in -C I believe in the context of something like 'auth token'. Need to define to keep the old-schoolers from freaking out (in fact they are, that is how I was made aware of this term.

**Comment by jricher** [comment]
This is really an OAuth token in the OIDC world. Was trying to avoid use of "token" here as that will *also* freak out the old-schoolers.

**Comment by jricher** [comment]
Duplicate of #1922
