### ISSUE TITLE
MF OTP device - May vs Must

### ISSUE THREAD

**Issue by FIDOAlliance** [usnistgov/800-63-3#191]
FIDO Alliance

800-63-3B section 5.1.5+5.1.7+5.1.8

Current language: The MF OTP device is something you have, and it MAY be activated by either something you know or something you are.
## We suggest that in order to make it a multifactor OTP token, it MUST (cannot be optional) be activated with either something you know or something you are.

Organization: , 2 = Industry,

**Comment by jricher** [comment]
I think the intent of the language was that it needs to be one of the two but it doesn't have to be both, so I think we can clarify that normative requirement better.

**Comment by LionDude** [comment]
Agree, MFA is essentially about "Something you know", "Something you have", and "Something you are". At least, two must be " activated or used" in the authentication workflow. This activation may be relative and needs to be clarified.  In the following two scenarios, are they both considered MFA implementations? I think it is, though offering different amount of security assurance:  First scenario:  (1) Login/Password ("something you know") is always required together (at the same time) with second SF authenticator ("something you have", OTP, etc.). The second scenario is (1) Login/Password is required BUT the application will (conditionally) only invoke the 2nd SF authenticator ("something you have") only if the application detects, for instance, "change in device, change in geo-location, etc.  
Obviously, not all MFA implementations offer the same "amount of security", but certainly some applications may be "appropriate" for any of those flavor of MFA implementations, depending on the risk-criticality of the application.

**Comment by jimfenton** [comment]
@LionDude See response to #181 with respect to scenario 2.
