### ISSUE TITLE
"authentication assertions" vs. "authentication"

### ISSUE THREAD

**Issue by jimfenton** [usnistgov/800-63-3#1917]
(submitted by MITRE)

In 800-63C,   Section 1, Purpose, second paragraph, second sentence:

Believe "Federation allows a given IdP to provide authentication and (optionally) subscriber attributes to a number of separately-administered RPs through the use of assertions." is missing a word. While an IdP can authenticate, that's not what federation allows.

Suggestion: Add "assertions" after "authentication"

**Comment by jricher** [comment]
This is an incorrect reading, it is in fact "authentication attributes and subscriber attributes", as per #1921 's question. We will consider rewording the sentence but not as requested.
