### ISSUE TITLE
Use of additional authenticators

### ISSUE THREAD

**Issue by FIDOAlliance** [usnistgov/800-63-3#192]
FIDO Alliance

800-63-3B section 6.1.2

Following enrollment, binding an additional authenticator to an account requires the use of an existing authenticator of the same type (or types). 

In reality authenticators of a different type could be used as well as long as their AAL is sufficient for the targeted level of strength.

---

Organization: 2 = Industry,

**Comment by paul-grassi** [comment]
That is what we intended, but the message got garbled in how we wrote it.  We will fix.

**Comment by jimfenton** [comment]
Can you clarify what you mean by "type"? Do you mean _something you know_ vs. _something you are_ as types or _single-factor cryptographic device_ vs. _single-factor OTP device_ as types?
