### ISSUE TITLE
Move attribute references sentence

### ISSUE THREAD

**Issue by jimfenton** [usnistgov/800-63-3#1924]
(submitted by MITRE)

In 800-63C,  Section 7.3 , final paragraph:

"The RP SHALL, where feasible, request attribute references rather than full attribute values as described in Section 9.3." This can only apply to the back channel, it would seem, since the entity does not know a priori what the RP is looking for.

Recommend moving this to Section 7.1 Backchannel Presentation.

--

**Comment by jricher** [comment]
This is not true -- front-channel protocols can allow the RP to request specific attributes and references just as well as back-channel protocols. The difference is that the request goes in through the browser as well as the response.
