### ISSUE TITLE
Deprecating SMS is a bad idea

### ISSUE THREAD

**Issue by akemshall** [usnistgov/800-63-3#194]
**Organization**: 2

Document 63B

Reference 5.1.3.2

If we look at this from a risk perspective, then clearly memorized secrets should be deprecated first as they have a far higher risk associated with them. 

SMS offers a one-time passcode (OTP) which is considerably stronger than any static reusable secret.  

SMS risks within the GSM network
• The 2G standard was shown to be weak and later patched, key lengths for 3G and 4G have  increased and are exponentially harder to guess.
• SMS signals use the same control channel as the phone which if compromised will lead to phone cloning and billing issues which is not seen in the real world. 
• Apps need acceptance from the user to access SMS (or other external resources) so users can decide which apps they trust, if any, to access their SMS message store.

Memorized secrets can be compromised in the following ways: - 
• If used on an unencrypted or weak encrypted network will lead to it being copied
• Shoulder surfing from nearby people or cameras
• Stored copies of passwords on backend authenticating server regularly become compromised in the press
• users typically write them down as they cannot remember them especially if infrequently used!
• Browsers store passwords to give users an easier single sign on experience

SMS offers the only zero-foot print OTP solution as it doesn’t need any software on the chosen phone. There are many situations in use today were this is required such as employees with personal phones that are not supported by their company or users that do not want to be forced to install third party software on their phone.  

Advising 1000’s of existing SMS based applications to deprecate and effectively move to a smart phone app can only lead to potentially 100’s of different authentication apps on a single user’s phone, which doesn’t scale.

Andy Kemshall, (over 20 years’ experience in multi factor authentication, Co-Founder of SecurEnvoy and previously number 5 employee of RSA Europe)

Note the SecurEnvoy offer a number of multifactor solutions including push based phone apps and OTP apps so do not have any bios towards SMS

**Suggested Change**: Do Not Deprecate SMS

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by gdbelvin** [comment]
SMS carries the following additional risks:
- [SS7 Vulnerabilities](https://www.ptsecurity.com/upload/ptcom/PT-SS7-AD-Data-Sheet-eng.pdf).
- Exposure of authentication codes to network operators. 

Additional methods of 2FA attacks seen in the wild:
https://citizenlab.org/2015/08/iran_two_factor_phishing/

**Comment by kunala** [comment]
@gdbelvin I believe @akemshall points here aren't being completely addressed. SMS as an out-of-band two-factor method has been unfairly **deprecated** compared to other more insecure methods.

Any method of authentication carries risk -- e.g. Many software based apps do not guarantee duplication resistance, such as TOTP QR code based authenticators. These can easily be duplicated across multiple devices.

**Comment by jimfenton** [comment]
The SMS deprecation issue is addressed in #19.
