### ISSUE TITLE
Grammatical error in NIST SP 800-63B section 5.2.3

### ISSUE THREAD

**Issue by ksr42** [usnistgov/800-63-3#1953]
An authenticated protected channel between sensor (or an endpoint containing a sensor that
resists sensor replacement) and verifier SHALL be established and **the sensor or endpoint
SHALL be established** and the sensor or endpoint SHALL be authenticated prior to capturing the
biometric sample from the claimant.

**Comment by jimfenton** [comment]
This was addressed in #1915. Errata correcting this grammatical error are currently in the approval process.
