### ISSUE TITLE
AAL Levels for Federal Agencies

### ISSUE THREAD

**Issue by BBC1** [usnistgov/800-63-3#196]
**Document (63-3, 63B)**:

**63-3 Executive Summary, 63B section 4.3.5**:

**The Executive Summary in 800-63 says that all federal agencies must comply with the LOA level 4 requirements.  In order to be LOA level 4 -compliant, an agency must be compliant with the requirements of AAL level 3.  AAL level 3 requires that agencies choose the security controls from the high baseline.

Many federal systems are FIPS-199 medium rated.  These new requirements are burdensome, at best, and most moderate or low FIPS-199 systems will struggle to meet the new requirements**:

**Revise the document to be more in line with FIPS-199 which is a mandatory requirement**:

---

Organization: 3 = Other

**Comment by paul-grassi** [comment]
The document does not state that LOA4 is a requirement for federal agencies.  It allows for options based on risk, the process of which is documented in [M-04-04](https://www.whitehouse.gov/sites/default/files/omb/memoranda/fy04/m04-04.pdf).  M-04-04 is founded on FIPS199.
