### ISSUE TITLE
SP800-63a 4.4.1.6 e sequence repeated

### ISSUE THREAD

**Issue by birdybro** [usnistgov/800-63-3#1965]
https://pages.nist.gov/800-63-3/sp800-63a.html

in 4.4.1.6 the numbering has a small typo, the sequence continues with "e" a second time instead of with "f" as it should be.

https://i.imgur.com/luFVFlR.png

**Comment by jimfenton** [comment]
Good catch. Also, the item numbered 4 that it is under should also be numbered 5 (the 4 was also repeated).
