### ISSUE TITLE
Two-Factor device unlock clarification

### ISSUE THREAD

**Issue by DamianM1** [usnistgov/800-63-3#1987]
Seeking clarification, particularly on 800-630B 5.1.9. I appears this question has been asked in different scenarios but the answers are unclear. Does Multi-Factor Cryptographic Device Authenticators constitute MFA for access to the device itself?

Example: If I have a hardware TPM on a device that is activated through a PIN, is this considered MFA when logging into/unlocking that same device? It appears that this scenario isn't addressed or clear for device login/unlock. If it is, please let me know as this question seems common among industry that has requirements to use MFA for local access to devices, and the NIST guidance appears to allow it or doesn't address it.

**Comment by jimfenton** [comment]
SP 800-63B addresses the authentication of individuals over an open network; it does not address issues relating to local authentication to a device (which is what device unlocking is). Therefore, the question of two-factor authentication is not in scope. For remote authentication using such a device, it would be considered two factor with one factor being the possession and control of the device itself (or specifically the private key it holds), and the other factor being the PIN.

**Comment by DamianM1** [comment]
Thank you for this clarification! This answers my question and I am sure other's will appreciate this too.
