### ISSUE TITLE
Proofing and Identification Document Freshness

### ISSUE THREAD

**Issue by williambrantmyzenkey** [usnistgov/800-63-3#1991]
Clarification on  Proofing document expiration.  It is pretty clear form the current NIST documents that identity documents need to be un-expired.  However, it is silent on what happens when an already proofed identity has the document expires.

Also are there any guidelines on how many expired pieces of identity documentation are allowed to be kept

## SP 800-63-3 Has Been Published

The SP 800-63-3 document suite has been finalized and published. It is publicly available at https://pages.nist.gov/800-63-3/

As the document has been finalized in its current revision, requests for normative changes will be held for adjudication for possible inclusion in a future revision of the SP 800-63 document suite. Editorial changes and internal clarifications may be incorporated in an errata set for this revision. Additional context and discussion may be addressed by the FAQ (https://pages.nist.gov/800-63-FAQ/) or other publications and resources.

**Comment by jimfenton** [comment]
Please direct comments and questions about SP 800-63 via email to dig-comments@nist.gov to make sure it gets to all the right people.
