### ISSUE TITLE
How to include assurance levels into X.509 S/MIME certificates?

### ISSUE THREAD

**Issue by RufusJWB** [usnistgov/800-63-3#1992]
Dear NIST team!

Do you have recommendations how to include the identity and authenticator assurance level into an S/MIME x.509 certificate? Thinking about adding them as OIDs into the Certificate Policy field, but I couldn't find OIDs for the various levels. Do you have a recommendation?

If this is the wrong forum for asking this question, please excuse me for asking here and kindly close this issue.

/Rufus

**Comment by jimfenton** [comment]
Rufus, please direct questions via email to dig-comments@nist.gov. Thanks!
