### ISSUE TITLE
SMS OOB Deprecation

### ISSUE THREAD

**Issue by kunala** [usnistgov/800-63-3#200]
**Organization**: 2

**Type**: Information Security

**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 5.1.3

**Comment (Include rationale for comment)**: 

We review a large amount of two-factor deployments both in enterprise, and even more in consumer. One of the best 'guards' to enrolling in a more secure form of two-factor authentication, such as an OTP generator or Push Notification, is SMS. 

It is convenient, and simple, yet provides a service a heightened level of security than out-of-wallet questions & an email verification to login. We find this to be a great method to validate a registered identity with 2FA, and then promote to a more secure option. 

We also see an issue with deprecating SMS OOB entirely as this is a firm method that leads to more 2FA adoption for consumer sites.

**Suggested Change**:

Current

> OOB using SMS is deprecated, and may no longer be allowed in future releases of this guidance.

OOB using SMS on a per authentication should be discouraged, but not deprecated. Instead, after establishing an identity, it should encouraged to 'upgrade' to a more secure authenticator.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
Deprecation of OOB SMS (saying that it may not be allowed in future releases of this guidance) is in effect discouraging its use.

There may be other reasons for using OOB SMS: to verify a text messaging number to be used for notifications, for example. These will continue to be allowed; what may not be used in future releases is the ability to use OOB SMS as an authenticator.

See also issue #19.
