### ISSUE TITLE
Whitelist and blacklist should be updated to allow list and deny list.

### ISSUE THREAD

**Issue by mozts2005** [usnistgov/800-63-3#2006]
The terms allow list and deny list are more expressive to the intent of the list. Also removes the racial connotations. for more details please see https://www.ncsc.gov.uk/blog-post/terminology-its-not-black-and-white

**Comment by jimfenton** [comment]
This change has already been made in the draft of the next revision, SP 800-63-4, except that 'blocklist' was used rather than 'deny list'. See https://www.nist.gov/identity-access-management/nist-special-publication-800-63-digital-identity-guidelines for more information on the revision.
