### ISSUE TITLE
Remote authentication guidance

### ISSUE THREAD

**Issue by dmbanks61** [usnistgov/800-63-3#202]
**SAIC**:

**Contractor**:

**Document 63-A**:

**Reference 4.5.7**:

**Comment**: IAL-2 precludes collection of biometrics for either STRONG or ADEQUATE evidence. Extending to accept biometric evidence for IAL-2 as an option will further reduce potential false authentications. Remote enrollment and authentication are the "future" of identity-proofing. This is a much more cost-effective way to proceed.**:

**Suggested Change**: Use the biometrics language from IAL-3 as an OPTION for - at least - "adequate" evidence for IAL-2.

Organization: 2

**Comment by mathiasrw** [comment]
If you come with a concrete suggestions to how the text could be I can make a pull request for the changes.

**Comment by paul-grassi** [comment]
Closed via #402
