### ISSUE TITLE
Testing environment should be clearly defined.

### ISSUE THREAD

**Issue by MassimoTornatore** [usnistgov/800-63-3#203]
**Organization**:3

**Type**:

**Document (63-3, 63A, 63B, or 63C)**:63B

**Reference (Include section and paragraph number)**:5.2.3

**Comment (Include rationale for comment)**: The draft reads "Testing of the biometric system to be deployed SHALL demonstrate an equal error rate of 1 in 1000 or better with respect to matching performance. The biometric system SHALL operate with a false match rate of 1 in 1000 or better."
Testing can be done theoretically on paper, similated on computer or demonstrated in labooratory, in indoor environment and in outdoor environment.  It should be made clear that theoretical testing on paper and simulation testing on computer shall not be allowed.  It should be carried out in the real use environment.

**Suggested Change**: The guideline should include such statements as "Testing of biometric system for office/home use shall be demonstrated in the real office/home enviroment.  Testing of the products for mobile use should be demonstrated in the real outdoor environment."

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by mathiasrw** [comment]
If you come with a concrete suggestions to how the text could be I can make a pull request for the changes.

**Comment by enewt** [comment]
Offline testing is also valuable and cost effective.  I would prefer a simpler change to make your clarifying point to simply add the word "Empirical" in front of "[t]esting of the biometric system to be deployed..." to avoid being overly prescriptive.

**Comment by MassimoTornatore** [comment]
I agree that it should not be overly prescriptive.  But do you think it is sufficient to prevent the inhouse data from being misused as the outdoor data?
