### ISSUE TITLE
Incomplete definition of 'federation'

### ISSUE THREAD

**Issue by andrewhughes3000** [usnistgov/800-63-3#205]
**Organization**: In Turn Information Management Consulting Corp. (ITIM Consulting)

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**: 63C

**Reference (Include section and paragraph number)**: Section 3, Para 3-4

**Comment (Include rationale for comment)**:
The existing definition of "Federation" is: "A process that allows for the conveyance of identity and authentication information across a set of networked systems."

This appears to miss an important aspect of Federation: that the networked systems belong to distinct 'security domains'. In other words, the networked systems are administratively controlled by different governance entities. 

The significance of this distinction is that if the networked systems are controlled by the same governance entity, they are probably required to follow the same rules and specifications and compliance regimes. Therefore, the administrative controllers of each system have confidence that they each are 'trustworthy' in performing their activities to the degree required.

The same is not true in a federation scenario where the administrative controllers are likely to be following different rules, specifications and compliance regimes. Thus the need to define Federation Assurance Levels.

If this observation about the definition of Federation is correct, then there will be many locations throughout 63C that will require adjustment in order to distinguish between simple networked authentication and federated authentication.

**Suggested Change**:
 Modify the definition of Federation to include the concept of distinct security domains (or similar term).
Modify the text of 63C as appropriate to indicate that a security domain boundary (or governance boundary) is crossed in order for 'federation' to occur. 
## (I am willing to attempt some modification through a pull request, but will need some time to construct it sufficiently)

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
We'll add a note in the definition that the networked systems are often (but not always) separated from each other.
