### ISSUE TITLE
Definition of 'assertion' might be inaccurate

### ISSUE THREAD

**Issue by andrewhughes3000** [usnistgov/800-63-3#206]
**Organization**: In Turn Information Management Consulting (ITIM Consulting)

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**: 63C

**Reference (Include section and paragraph number)**: Section 3, "Assertion" term

**Comment (Include rationale for comment)**:
The existing definition of 'Assertion' is: A statement from a verifier to a Relying Party (RP) that contains identity information about a subscriber. Assertions may also contain verified attributes. 

Is it strictly true that assertions come from verifiers?

Assertions about verification activities such as authentication and identity function activities probably do come from the verifier. Is this strictly true for verified attributes? 

A possible illustrative case (I do not know if this case exists in real implementations): A verifier performs an authenticator verification; the verifier triggers an attribute assertion service to assert verified attributes to the RP. 

**Suggested Change**:
Possible solution, change the text to read:
## A statement from a verifier to a Relying Party (RP) that contains identity information about a subscriber. The **statement** may also contain verified attributes. 

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
The current definition doesn't rule out attribute providers.
