### ISSUE TITLE
Zero-effort & Out-of-band Autonomous Authentication Factors

### ISSUE THREAD

**Issue by CloudwearAutonomous2FA** [usnistgov/800-63-3#207]
**Organization**: 2

**Suggested Change**: NIST's recommendations should recommend "zero user effort" and "out-of-band" second/multiple factors, such as those presented by Cloudwear, as reduced user effort results in higher adoption, and therefore higher levels of realized security. 

---

**Further explanation:**

Autonomous Two-Factor Authentication by Cloudwear, Inc.

Cloudwear provides a frictionless (zero user action) ultra-secure 2FA solution that authenticates mobile logins without the need for SMS messaging.

Two-thirds of cybersecurity breaches are password related, says Verizon’s 2016 “Data Breach Investigations Report,” and less than 10% of Google users enable 2FA. Security is useless if people don’t use it.

Cloudwear solves this problem with Autonomous 2FA, authenticating every login by instantly verifying that the user's mobile device is related to the account being accessed. For attempted logins or changes on a device that isn’t related to the user’s account, Cloudwear instantly raises an alert and requires further authentication.

Our Autonomous 2FA solution is transparent, always on, always working, with zero action required by the user.  The details of how we accomplish this are described in our deck (available by request) in greater detail.

Cloudwear secures online shopping transactions, maintaining historical records to detect and trace fraud attempts.   Cloudwear also disarms credential phishing and data breaches. Recent reports detailed a hacker posting online more than 80,000 stolen IDs, passwords and IP addresses from an e-commerce giant. If that company were using Cloudwear, this posted information could do no damage, because Cloudwear renders stolen credentials unusable.

Autonomous 2FA is a powerful authentication technology that helps protect companies and their users, for a safer, smoother, more secure online experience.

Cloudwear, Inc.
Four Embarcadero Center, Suite 3460
San Francisco, CA 94111
Contact us at nist2fa@cloudwear.com

**Comment by mathiasrw** [comment]
If you come with a concrete suggestions to how the text could be I can make a pull request for the changes.

**Comment by jricher** [comment]
Continuous and heuristic authentication systems such as this one (and those used by the likes of Google and offered by a number of other companies) should already be covered by the current text. If not, please suggest text that would improve that.

**Comment by rsfaron23** [comment]
Cloudwear: How does the user enroll his device with the account being used and subsequently being authenticated.  Does the Cloudwear service also validate and verify the user is related to the mobile phone? does the Cloudwear service authenticate the mobile account?
or does the user have to have a prior connection to the account being used?
