### ISSUE TITLE
MF Cryptographic devices - the case of smartphones

### ISSUE THREAD

**Issue by kriffy** [usnistgov/800-63-3#208]
**Organization**: 2

**Type**: MF Cryptographic devices

**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 5.1.8 and 5.2.3 §7

**Comment (Include rationale for comment)**: In the case of Smartphones the user device and the authentication cryptographic device merge.  You do not get acccess through a separate device like for a PC for instance.  Henceforth we have two single-factor authentication (fingerprint/PIN code after 10 trials and the application PIN code) which is not matching the AAL3 (e.g.. for accessing remotely sensitive data).  In the case of e-banking applications some institutions only require a fingerprint.  It means that single-factor authentication is sufficient when it is something you are.
## **Suggested Change**: I suggest that the labelling 'multi-factor cryptographic devices' for Smartphone be restricted to activation through something you are since do not own something different from the smartphone device itself and usages of memorized secrets.

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by mathiasrw** [comment]
If you can come with a concrete suggestions to how the text could be I can make a pull request to get the change implemented.

**Comment by jimfenton** [comment]
I don't fully understand the comment, but it sounds like the suggestion is that a biometric alone be considered sufficient for AAL 3 on smartphones. Even though banks may think otherwise, this guideline does not consider biometrics to be sufficient to authenticate the user standing on their own.

**Comment by kriffy** [comment]
Thanks for your response.  I appologize for my English, I'm not a native speaker...  I just wanted to get a clarification.

The question is : "having the multi-factor cryptographic protection in the same device than the device to be protected (e.g. a smartphone) can it be considered as AAL3" ?

Having a separate single factor cryptographic device (AAL2 ) separate form the smarphone should be considered more secure than a touchID.

Based on the document and the picture of an iPhone showed in 5.1.8, it seems that my reasoning is wrong

Thanks

Date: Wed, 31 Aug 2016 21:35:18 -0700
