### ISSUE TITLE
4.5 Assurance Levels: Reach Level 3 with IAL=2, AAL=2, FAL=2 ?!

### ISSUE THREAD

**Issue by TerryMcBride** [usnistgov/800-63-3#21]
**Organization**: 1

**Type**:

**Reference (Include section and paragraph number)**: 800-63 Section 4.5 Assurance Levels

**Comment (Include rationale for comment)**:
For instance, to achieve an overall assurance level of **3**:
•The enrollment and identity proofing process shall, at a minimum, use IAL **2** processes or higher.
•The authenticator (or combination of authenticators) used shall have an AAL of **2** or higher.
•Authentication assertions (if used) shall have an FAL of **2** or higher.

**Suggested Change**:
##  Change 3 to 2

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by TerryMcBride** [comment]
I should include the comment.  I believe there is a typo. The bullets point to an overall level of 2, but the lead in sentence says 3.

**Comment by paul-grassi** [comment]
The tables in the executive summary of -3 show the complete mapping of M-04-04 to the new components of assurance: IAL, AAL, FAL.  We only have 3 IAL and AALs, therefore IAL and AAL of 2 is equivalent to the old requirements necessary to hit M-04-04 LOA3.  FAL's have additional options, but 2 or higher, based on the new definitions, is sufficient to hit LOA3 as well.
