### ISSUE TITLE
OOB using SMS is not OOB

### ISSUE THREAD

**Issue by wangxjnj** [usnistgov/800-63-3#215]
**Organization**: 2

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 5.1.3. Out of Band

**Comment (Include rationale for comment)**: OOB means that there are two channels: primary and secondary. Both of them are used for the authentication. The Primary channel is used to verify the first factor, and the Secondary is used to verify the secondary factor.  SMS is used to deliver the OTP, and is part of the authentication flow. But not used to verify the OTP. The OTP is verified through the Primary channel. 

"The device is possessed and controlled by the claimant and supports private communication over a secondary channel that is separate from the primary channel for e-authentication. "   SMS also does not meet the above PRIVATE requirement for the secondary channel. 

**Suggested Change**:
1. create a new section: 5.1.x SMS-based OTP.  
2. replace OOB using SMS with SMS-based OTP, and move SMS related info to the new section
3.  change "OOB using SMS is deprecated" to "using SMS-based OTP as the sole authentication factor, secondary factor, step-up authenticator, or the second step of the two-step authentication is deprecated". 
4. combine the 5.1.3.1 and 5.1.3.2 into a single section. OOB authenticators and 
## "out of band verification is to be made using a secure application" are referirng to the same thing: mobile app. 

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
The out-of-band channel is used to establish control of a physical authenticator.  The verifier can use either channel to verify the OOB OTP.  In the case of SMS, the primary channel is used to verify.  In the case of new authenticators like Google Prompt, the secondary channel is used.  Both ways demonstrate control of the physical authenticator.

**Comment by wangxjnj** [comment]
why OOB? To make the authentication secure, and an attacker cannot take over a user's account unless he/she is able to compromise both of the Primary and Secondary channels. The OOB mitigates the Primary channel's MITM/MITB, OTP guessing .. risks.  Are the risks also mitigated by  OOB OTP? Is OOB without any OOB related Security benifits OOB? I would vote for not. 

OOB SMS OTP is exactly the same as the physical OTP device. The only difference is that the OTP code is delivered Vs calculated based on pre-shared secret. If successfully authenticated the verifier knows that the OTP device or phone is in the user's control. So the OTP from the physical device can also be called OOB Local OTP? 

Please also add the OOBA  into the Definitions and Abbreviations.
