### ISSUE TITLE
Verifier should not be required to authenticate itself to the claimant.

### ISSUE THREAD

**Issue by wangxjnj** [usnistgov/800-63-3#216]
**Organization**:2

**Type**:

**Document (63-3, 63A, 63B, or 63C)**:63B

**Reference (Include section and paragraph number)**: 5.1.1.2, 5.1.2.2, 5.1.3.2, 5.1.4.2 and 5.1.5.2

**Comment (Include rationale for comment)**: 
"Verifiers SHALL use approved encryption and SHALL authenticate themselves to the claimant (e.g., through the use of a X.509 certificate using approved encryption that is acceptable to the claimant) when requesting look-up secrets in order to provide resistance to eavesdropping and phishing attacks.

"In collecting the OTP from the claimant, the verifier SHALL use approved encryption and SHALL authenticate itself to the claimant."

The verifier usually sits behind layered protection, The authentication flow may pass multiple hops (eg web --> radius-proxy --> Radius --> verifier ), and cross multiple zone (DMZs and Corp networks). It is almost impossible for the verifier  to authenticate itself to the claimant(user). Even if it is possible what credential should the verifier use to authenticate itself to the user?  

For web based application technical claimants may be able to verify whether they are talking to the right web site by looking at the cert. But they are not going to know whether the Web App is asking the correct Verifier for verification. They just got a good/bad auth result back. It is the Web app's responsibility to make sure it is reaching out to the right verifier.

**Suggested Change**:
## after collecting the authentication secret from the claimant the secret SHALL be submitted to the verifier for verification through an Authenticated Protected Channel to provide resistance to eavesdropping.

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
The language being suggested effectively says the same thing as the current text. The use of an _authenticated_ protected channel (emphasis added) also requires that the verifier authenticate itself to the claimant. Even if the verifier operates behind several hops, the host that the user establishes with needs to be within the trust sphere of the verifier, and needs to be able to authenticate itself to the user as the verifier.

However, the text you cite predates the introduction of the term authenticated protected channel, and might be clearer if that term is used as you suggest.

**Comment by wangxjnj** [comment]
Based on the definition "Claimant: A party whose identity is to be verified using an authentication protocol." It is referring to human user(my understanding).  A verifer cannot authenticate itself to a human.  For https (authenticated protected channel) the web server authenticates itself to the web browser, not the user.  The user only knows whether he/she is accessing the correct web application URL.

**Comment by wangxjnj** [comment]
UDP based authentication protocols, such as RADIUS, KERBEROS, SecurID, and many others, do not meet the "authenticated protected channel" requirement. I would suggest taking the "the verifier SHALL use approved encryption and SHALL authenticate itself to the claimant." out.
