### ISSUE TITLE
OTP: numeric or alphanumeric?

### ISSUE THREAD

**Issue by wangxjnj** [usnistgov/800-63-3#218]
**Organization**:

**Type**:2

**Document (63-3, 63A, 63B, or 63C)**:63B

**Reference (Include section and paragraph number)**: 5.1.4, 5.1.5

**Comment (Include rationale for comment)**:
 single factor OTP device image shows numeric OTP, and multi-factor one alphanumeric "123ABC". 
**Suggested Change**:
##  change the image to show numeric only

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
These are illustrative and informative.  No requirements are to be derived from these images.

**Comment by wangxjnj** [comment]
Good to know
