### ISSUE TITLE
Multi-factor OTP device: activation

### ISSUE THREAD

**Issue by wangxjnj** [usnistgov/800-63-3#219]
**Organization**:

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 5.1.5

**Reference (Include section and paragraph number)**: 5.5.5

**Comment (Include rationale for comment)**:
" The MF OTP device is something you have, and it may be activated by either something you know or something you are."

That requires the device to support locally both user/passwd or user/biometric provisioning and verification.  Any vendor products are able to do that? RSA SecurID is 2FA but PIN is verified by SecurID server, not locally by the device.

**Suggested Change**:

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by enewt** [comment]
The text uses the verb "may" and the word "either" to indicate that an MF device does not need to be able to authenticate with all factors. We are not commenting on products available.

**Comment by wangxjnj** [comment]
Then the MF OTP device is not MF if not activated by what you know or what you are.

**Comment by paul-grassi** [comment]
You are misunderstanding.  We require MF OTP to be activated by one of the other factors.  What we don't require is that vendors support BOTH factors in their solutions.  They can if they want, but we just require one or the other to activate.
