### ISSUE TITLE
General Requirement #13 - Entire Identity Proofing Session over Mutually Authenticated Session

### ISSUE THREAD

**Issue by TerryMcBride** [usnistgov/800-63-3#22]
**Organization**: 1

**Type**:

**Reference (Include section and paragraph number)**: 800-63-A, Section 4.2, bullet 13

**Comment (Include rationale for comment)**:
Regarding:  13.The entire proofing transaction, including transactions that involve a third party, SHALL occur over mutually authenticated protected sessions.

Can you clarify?  I assume that you don't mean that the user has to have a mutually authenticated TLS session with the CSP, since they don't have an authenticator yet.  That would be good for use with third party services (e.g., credit bureau), but the user is a major part of the id proofing transaction.

**Suggested Change**:
 Clarify

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
I agree with this comment -- "mutually authenticated" points to a particular technological solution, whereas I think the intent is that it's an integrity-protected and non-spoofable connection, yes? We can probably be a lot more clear on this.
