### ISSUE TITLE
Suggestion for AAL 2 

### ISSUE THREAD

**Issue by hitoshikokumai** [usnistgov/800-63-3#221]
**Organization**: 3

**Type**:  Security design

**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**:   Executive Summary AAL 2, Introduction AAL 2 and 4.2. Authenticator Assurance Level 2

**Comment (Include rationale for comment)**:  Two different factors can be operated in two ways - (1) by AND/Conjunction (we need to go through both of the two) or (2) by OR/Disjunction (we need only to go through either of the two).  

If two different factors are used by OR/Disjunction, we will only obtain the level of security lower than AAL 1.  AAL 2 can be achieved only by (1) AND/Conjunction.  

For further details of the rationale, you could refer to my earlier comment #193.

**Suggested Change**:  Such a sentence as " The two different factors shall be used by AND/Conjunction (we need to go through both of the two), not by (2) by OR/Disjunction (we need only to go through either of the two.)" should be explicitly included in all the relevant sections.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by hitoshikokumai** [comment]
Whether explicitly called as the fallback means or not, a fallback means for rescue of the claimant who gets rejected by the first factor is nothing but a second factor operated by OR/Disjunction.

I hope you are with me.

**Comment by jimfenton** [comment]
From a purely theoretical standpoint, you are correct that being able to use either of two authenticators is less secure than only having one because of the larger attack surface. But at present, account recovery (forgotten password, lost physical authenticator, etc.) is typically handled much less securely than standard authentication, email password resets being a prime example. And it isn't necessary for the attacker to actually lose an authenticator; all they need to do is assert that they did.

The issuance of multiple authenticators is expected to make account recovery much less commonplace, so that the recovery process can be made more secure (even though that may make it more expensive and time consuming).

The AND/Conjunction and OR/Disjunction terminology you are suggesting is not commonly used and is likely to cause more confusion than clarity if included in the guideline.

**Comment by hitoshikokumai** [comment]
Before getting locked out I would add as follows:

If your reasoning were valid, you should allow people to allege that using a hard-to-forget (=easy-to-break) password will help reduce the chances of account recovery, thus helping to maintain security.  So do the re-use of a password across many accounts and carrying around a memo with passwords on it.

NIST should be in the best position to make a clear definition and educate the public that there are two ways of operating two factors - AND/Conjunction = we need to go through both of the two and OR/Disjunction = we need only to go through either of the two, each having its own merits and demerits.

**Comment by hitoshikokumai** [comment]
I also wonder if you could let me know your observation about which of (1) biometrics with a fallback password and (2) a password-only authentication contributes more to fewer cases of account recovery?

**Comment by hitoshikokumai** [comment]
As indicated in the foregoing, I reckon that your story of account recovery is not just invalid but detrimental.

Invalid because you would otherwise have to demonstrate that "biometrics with a fallback password" contributes notably more to fewer cases of account recovery than "password-only authentication" does.

Detrimental because it would be tantamount to encouraging people to use harder-to-forget = easier-to-break passwords, re-use a password across many accounts and carry around a memo with passwords on it, so that account recovery would be made much less commonplace.

**Comment by hitoshikokumai** [comment]
As stated in the latest suggestion #334, the story of account recover is valid for the cases of biometrics and passwords used by AND/Conjunction.  It is wrong, however, to try to apply it to "biometrics with a fallback password operated by OR/Disjunction".

**Comment by hitoshikokumai** [comment]
As stated in the latest suggestion #334, the story of account recovery is valid for the cases of biometrics and passwords used by AND/Conjunction. It is wrong, however, to try to apply it to the cases of  "biometrics with a fallback password operated by OR/Disjunction".
