### ISSUE TITLE
Entropy of Micro Transactions

### ISSUE THREAD

**Issue by TerryMcBride** [usnistgov/800-63-3#226]
**Organization**: 1

**Type**: 

**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: 
5.3.2. Knowledge Based Verification Requirements 

Also see: https://github.com/usnistgov/800-63-3/issues/44#issuecomment-231419641 

**Comment (Include rationale for comment)**:
The entropy of micro transactions plays a role in the security of the scheme.   If a dollar or less, then at least 1/100 probability of guessing correctly (probably better assuming they aren't using FIPS random number generators).

**Suggested Change**:
 Suggest added requirements and/or guidance to help ensure that implementations take the entropy of the micro transactions into account. 

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
Will shift the 'for example' to a minimum requirement.
