### ISSUE TITLE
Identity Verification - Add interaction over postal mail to Strong

### ISSUE THREAD

**Issue by TerryMcBride** [usnistgov/800-63-3#227]
**Organization**: 1

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**:  5.4.1. Identity Verification Methods

**Comment (Include rationale for comment)**:
The requirements for Superior include biometric comparison and interaction via postal address of record. Meanwhile, the requirements for Strong list either photo/biometric comparison or trusted referee confirmation. Since, both address degrees of biometric comparison, the implication is that postal address confirmation is comparable if not stronger than trusted referee confirmation.  

**Suggested Change**:
##  Add "OR - The applicant’s ownership of the claimed identity has been confirmed by an interaction with the applicant via the postal address of record." to the list of acceptable methods for Strong.

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
Address verification is not the equivalent of a physical comparison of applicant to evidence.  It is an extra step at higher IAL's to obtain additional confidence you are dealing with the right claimed individual.  We already have address verification (not just postal) at IAL 2, and want physical compare with picture to occur.

**Comment by TerryMcBride** [comment]
In the Resolution, Validation, Verification framework, address confirmation is a form verification, not an extra step outside of it, as your entry in Superior implies and as evidenced by address confirmation’s role as the primary verification method in 800-63-2.  It demonstrates the individual’s control over an address known to be linked to the individual. Why treat it separately? And, why treat is separately for Superior (including it there) than for Strong (not including it there)?

I thought the intention was for IAL2 (which requires Strong) to for registration to be able to be remote and automated, is that right?  If so, then it’s not a physical comparison of an applicant to evidence that you’re doing. It’s a digital comparison of two pictures.  The lack of references to specifications and thresholds for determining the digital match (like we have for fingerprint matching) is pretty obviously missing from the document. Add to that that we’re not talking about trusted computing devices that are taking these pictures; so attacks like replacing drivers to feed photos (obtained from social media) as if they come from the camera would likely be coming quickly.

What evidence can you share that leads NIST say that a code mailed to a _physical_ address of record is not as strong as the _digital_ comparison of two pictures sent by the claimant?

**Comment by paul-grassi** [comment]
OK, I see the issue here.  I will reopen and update.  Thanks.
