### ISSUE TITLE
Requiring KBV for Adequate Evidence

### ISSUE THREAD

**Issue by TerryMcBride** [usnistgov/800-63-3#230]
**Organization**: 1

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: 5.3.1.1, Scoring of Identity Evidence

**Comment (Include rationale for comment)**: 
The requirements for Adequate Identity Evidence includes this line as a hard requirement (not part of a set of choices)...
     "- Ownership of the evidence can be confirmed through KBV"
KBV can be a useful option in validating the identity, but requiring KBV as something that must be available for Adequate Evidence IMHO is too prescriptive.

**Suggested Change**: 
Remove the requirement 
(and more generally, don't REQUIRE KBV for anything [make it an option]).

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by kcrowl11** [comment]
I guess my interpretation was different. When I read that statement I took it to mean the KBV can be used to confirm but not that it must be used. Clarification as to intent of this requirement would be appreciated.

**Comment by paul-grassi** [comment]
This is an unfortunate error when moving some of these requirements from strong to adequate.  Will update.  Thanks @TerryMcBride
