### ISSUE TITLE
Encrypted front-channel assertions via SAML Web Browser SSO profile should be acceptable

### ISSUE THREAD

**Issue by nckroy** [usnistgov/800-63-3#238]
**Organization**: 1

**Type**: Education and Research

**Document (63-3, 63A, 63B, or 63C)**: 63-3

**Reference (Include section and paragraph number)**: Section 7

**Comment (Include rationale for comment)**: Need to update language around SAML profiles supported at FAL 2

**Suggested Change**: With the change Justin just made to allow encrypted front-channel assertions per my comment / issue #169, it is now possible to use the SAML Web Browser SSO profile, not just artifact resolution.  Artifact is a generally difficult to deploy and so not widely deployed profile in the education and research space.  Please consider adding use of encrypted assertions via the SAML Web Browser SSO profile to this section.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
It already is acceptable. The paragraph below the table is a non normative example.
