### ISSUE TITLE
Are FAL and AAL comparable?

### ISSUE THREAD

**Issue by nov** [usnistgov/800-63-3#239]
**Organization**: 2

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63-3

**Reference (Include section and paragraph number)**: Section 4.5

**Comment (Include rationale for comment)**:

This section compares AAL2 and FAL3 and concludes FAL3 is stronger than AAL2, AAL and FAL are defined orthogonal each other though.
Are they comparable? and even so, AAL2 is stronger than FAL3?

**Suggested Change**:

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
This section isn't directly comparing AAL2 and FAL3, it's saying that if they are used together (orthogonally), then an attacker is likely to go for the easier target, whichever that is. I can see how that would look like a direct comparison is being made, so we'll look at the wording of this example section.

**Comment by paul-grassi** [comment]
I can add some language to tweak this.

**Comment by nov** [comment]
cool 👍
