### ISSUE TITLE
IAL2 requires Trained Personnel and cannot be automated

### ISSUE THREAD

**Issue by TerryMcBride** [usnistgov/800-63-3#24]
**Organization**: 1

**Type**:

**Reference (Include section and paragraph number)**: 800-63A, Section 5.2.2.1. Methods to Perform Identity Evidence Validation
"Strong" row in the table

**Comment (Include rationale for comment)**:
IAL 2 requires at least on piece of Strong evidence.  The requirements for validating Strong evidence state:
- The evidence has been confirmed as genuine by **trained personnel** and appropriate equipment, confirming the integrity of the physical security features OR The evidence has been confirmed as genuine by confirmation of the integrity of cryptographic security features.
  AND
  - All personal details and evidence details have been confirmed as valid by comparison with information held/published by the issuing source OR evidence details have been confirmed as valid by comparison with information held/published by the issuing source.

Assuming the transaction is remote and the evidence doesn't include cryptographic security feature (which I think is safe to assume is the vast majority of cases), you are requiring a "person" to look at an image/video (video is a series of images).  

**Suggested Change**:  Allow IAL 2 to be automated (no trained personnel required to look at each piece of Strong evidence).  
Also, I suggest that requiring agencies to receive and analyze images of identity documents is relatively prescriptive. It makes me wonder what evidence NIST has to drive all agencies to these technologies. 

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by TerryMcBride** [comment]
Related in 5.3.1 Strong row of table. 
"- The applicant’s ownership of the claimed identity has been confirmed by **physical comparison** using a photograph/image OR Biometric comparison of the Applicant to the strongest piece of evidence provided to support the claimed identity."

Physical comparison implies that you have the identification evidence physically in front of you.  I can only assume you mean to also allow a digital comparison unless you are requiring IAL 2 to be in person.

**Comment by paul-grassi** [comment]
Thanks @TerryMcBride.  Our intention at IAL2 is that this can happen remotely, so we will look into this and update accordingly.  We didn't intend physical to be in-person so we will clarify.  What we meant is that remote capabilities may be able to compare, but that we don't consider that biometric if they don't have an enrolled template to match against.  Thanks again.

**Comment by paul-grassi** [comment]
For remote proofing when a human is not in the loop, we expect that the CSP will do a records check, which is allowable (as an OR) for the higher validation requirements.  However, we will also update the language to ensure that implementors understand when remote validation is required and what we expect when validation is performed remotely.

**Comment by TerryMcBride** [comment]
So, are you changing the AND at the end of the first bullet to an OR?

**Comment by paul-grassi** [comment]
It will be some sort of update that allows video/photo AND records check OR trained personnel.  We'll get the language right.  When we issue the pull request this issue will close so you can see what we did.
