### ISSUE TITLE
FAL 4 additional key example

### ISSUE THREAD

**Issue by ve7jtb** [usnistgov/800-63-3#242]
**Organization**: 2

**Type**:  Software Vendor

**Document (63-3, 63A, 63B, or 63C)**: 63C

**Reference (Include section and paragraph number)**: 7 Para 3

**Comment (Include rationale for comment)**:

Fido is used as an example of an additional bound key for the assertion. 
Fido keys are pairwise so not really suited to be used as a proof key for assertions as both the IdP and SP cannot verify the same key is held by the user agent presenting the assertion or artifact.

I think calling out Fido for this might be a misdirection. I know some people are talking about modifying Fido but that is speculative at this point.

I appreciate that it is non normative, but it should be accurate. 

**Suggested Change**:  

A current example would be a mutual TLS certificate,  in future it might be token binding.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
Good point, we probably shouldn't name FIDO here, but rather reference a theoretical hardware authenticator that would have this capability.

**Comment by ve7jtb** [comment]
One of the existing problems in my opinion is that the old SP800-63 requires they proof key to be the same as the one used for authentication, or at-least that is how it has commonly been interpreted.   That removes the utility of doing pairwise identifiers because the key is correlateable.    I prefer to leave open the possibility of chaining.

The user authenticates using Fido to the IdP (Or PIV) by proving a key over the channel.  In the fido case the ekm is used as a challenge and that is signed and sent to the IDP.  In the PIV case the key is used to do mutual TLS.  We could argue the finer points, but say they are equivalent from a security perspective.

Fido + Token binding asserts the devices keys for the IdP and RP by also signing the EKM and providing that as a assertion in a header of the Authentication request.   If all three are over the same EKM we have a proof that all three are coming from the same user agent.

Tying the assertion to the token binding key the user agent allows for a equivalent man in the middle protection.    Now There are some diffrences regarding how the private keys are stored, but that is probably not relevant to the man in the middle attack we are trying to mitigate. 

Given that this tye of attack is becoming more popular in the wild, mitigating it at all FAL is probably a good idea.  To do that and preserve pseudonomy  at the lower LoA we need to break the tight binding between the authentication key and the proof key.

So we could say that the proof key is provided by hw backed storage on the device.  I would prefer not to call the proof key an authenticator (it is for the user agent)  as the assumption that it is the user authenticator will be jumped to.   I am fine if you want to call it a HW device or user agent authenticator.

John B.

**Comment by jricher** [comment]
The key is no longer required to be the same one used in the primary authentication, and in many cases it probably shouldn't be. We don't specify that one way or the other.

**Comment by ve7jtb** [comment]
Right,  so when you say theoretical hardware authenticator, avoid the implication that it is the user authenticator.   We know this but people will tend to read it thinking of the old version where it is the user authenticator..
