### ISSUE TITLE
Use of "physical comparison" is unclear

### ISSUE THREAD

**Issue by TerryMcBride** [usnistgov/800-63-3#243]
**Organization**: 1

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: 5.4.1 Strong

**Comment (Include rationale for comment)**: 
This sentence could use more explanation to avoid misinterpretation: "- The applicant’s ownership of the claimed identity has been confirmed by physical comparison using a photograph/image"... 

**Suggested Change**:

"- The applicant's ownership of the claimed identity has been confirmed by comparison of the photograph/image on the evidence with a photograph/image of the applicant captured during the identity proofing session using appropriate equipment or trained personnel."

Bonus points for defining appropriate equipment and comparison algorithms. Additional bonus points for adding requirements that help ensure that the photograph is captured during the identity proofing session.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by TerryMcBride** [comment]
Probably more clear that using equipment/personnel refers to the comparison rather than the photo capture if rearranged like this: 
"- The applicant's ownership of the claimed identity has been confirmed by comparison using appropriate equipment or trained personnel of the photograph/image on the evidence with a photograph/image of the applicant captured during the identity proofing session."

**Comment by paul-grassi** [comment]
We will be developing an implementation guide to go along with 800-63-3.  Requirements such as this will be supplemented with recommended implementations.

**Comment by dollarmoney** [comment]
That is interesting... do you have an estimate on when a draft of the implementation guide will be available?
