### ISSUE TITLE
LoAs

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#245]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63-3 

**Reference (Include section and paragraph number)**: 
Section  - LoAs

(KI Ref: KI/ADG#01)

**Comment (Include rationale for comment)**: 
LoAs are defined in terms of confidence levels, confidence by whom, in what, how much?  "Assurance Level" should be replaced with more useful metrics - see IETF VOT and the discussions at the NIST workshop for examples.

**Suggested Change**: 
Something like "Assurance Levels are sets of requirements and security controls developed to achieve increasing levels of threat mitigation for authentication."

Perhaps rewrite in terms of what the DAG is trying to achieve with Assurance Levels -

**Comment by paul-grassi** [comment]
Thank you for this.  800-63-3 is still bound by M-04-04, where LOA's are defined and locked in.  We will add language for XALs, since those are new to the LOA mix.
