### ISSUE TITLE
Definitions - Authoritative Source 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#249]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63A

**Reference (Include section and paragraph number)**: 
Section 3 - Definitions and abbreviations

(KI Ref: KI/ADG#06)

**Comment (Include rationale for comment)**: 
The definition of authoritative source makes it appear that to be more objective than it really is.  Determining what the characteristics of what makes an authoritative source for verifying identity evidence is a crucial policy determination that will fundamentally affect the security characteristics of the registration and issuance process. The definition indicates that a source becomes authoritative when it has access to sufficient information from an issuing source to validate the evidence, but how does one determine what is "sufficient"?  What level of accuracy makes a validation good enough for the source to be considered "sufficient"?  This is an area where statistical methods could be useful to define and measure the accuracy of information provided by an "authoritative" source.

Note the definitions of “authoritative source” and “corroborative source” in ISO/IEC 29003. That document defines authoritative source as one "deemed to be true" - this definition is also lacking since it fails to indicate who does the deeming in that case, but we propose that this important decision should be made by policy administrators of trust framework providers rather than defined in the digital authentication guidance.

Consider the example of DNS - ICANN is the authoritative source by definition. Do we want to weaken this sense of the word?

**Suggested Change**: 
Update definition of authoritative source to either include clearer metrics for what "sufficient" confirmation is (such as defining the required accuracy of the confirmation) , or make it clear who decides whether a source if authoritative or not.

**Comment by paul-grassi** [comment]
We will add language as proposed, but will keep the current definition as in tact as possible as it aligns with GPG45.
