### ISSUE TITLE
Definitions - Pseudonym 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#250]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63A

**Reference (Include section and paragraph number)**: 
Section 3 - Definitions and abbreviations

(KI Ref: KI/ADG#07)

**Comment (Include rationale for comment)**: 
Pseudonym is still defined as "a false name" and prohibited at higher assurance levels. There should be a way to associate pseudonyms with validated identities for higher trust higher privacy environments, and that is commensurate with the use of the term in healthcare for de-identification techniques.

**Suggested Change**: 
Define pseudonym as an alternative identifier either selected by the subscriber as an alias, or provided by a de-identification service.

**Comment by jricher** [comment]
Would it be possible to resubmit all of these @KantaraInitiative-IAWG issues as actual text instead of pictures of text?

**Comment by KantaraInitiative-IAWG** [comment]
Dear Justin

They were re-submitted in text now.

Sorry for the inconveniences.

Best
Ruth

**Comment by jricher** [comment]
Great, thanks!

**Comment by paul-grassi** [comment]
@KantaraInitiative-IAWG if you could provide a pointer to where 'false name' is included and where we state it is not allowed at higher LOA's, we would appreciate it.  Throughout the suite of documents, we purposely encourage pseudonyms at higher LOAs.  In fact, in -3, A,B, C we make it a SHALL statement that pseudonyms are used where possible.  Only in -3 where we have a table for 'strict adherence to M-04-04' is the old model retained.  Some pointers to where we are inconsistent and recommended language would be great.
