### ISSUE TITLE
General requirements 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#251]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63A

**Reference (Include section and paragraph number)**: 
Section 4.2. - General requirements

(KI Ref: KI/ADG#08)

**Comment (Include rationale for comment)**: 
Requirement 2.  SSN is prohibited "unless necessary" - that's a weak requirement. Who says what's necessary, how do they determine that?

**Suggested Change**: 
Discuss specific alternative identifiers and their pros and cons.

**Comment by MartinFSmith** [comment]
May be worth noting, with respect to SSAN (or any claimant attribute) that the use of any data for an unintended or unanticipated purpose increases the risk to the information system that maintains the (attribute) data.  The value of a driver's license is far greater than it would be if it were only useful as proof of permission to drive. Therefore the incentive to compromise the DL system (via hack or counterfeit or even robbery) is greater than the DL system was engineered to withstand (though the added risk is well-recognized now and various mitigations have been developed.) 

The point is that any use of data in identity systems (for identity proofing or for authorization) imposes a risk on the system that is the source of that data, and that added risk is a "negative externality" imposed by the identity system on that other data system.  This should be taken account of in the risk management of that system and some method may have to be devised for the beneficiaries of the identity system (CSPs, RPs and users) to compensate the providers of authoritative attribute data. (This is of course outside the scope of 800-63-3.)
