### ISSUE TITLE
KBV

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#252]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63A

**Reference (Include section and paragraph number)**: 
Section 5.2.2.  - KBV

(KI Ref: KI/ADG#09)

**Comment (Include rationale for comment)**: 
Parsing out the requirements for KBV, it appears difficult or impossible to achieve.  How can a third party ever actually verify information that "only the subscriber" should know?

**Suggested Change**: 
Either ban KBV explicitly or allow the RP to make the decision whether to use them by providing sufficient information to know whether credentials were issued based on KBV.

**Comment by paul-grassi** [comment]
Agencies are always allowed to make risk based decisions and apply compensating controls.  And we want to allow for use cases where an entity can meet these requirements (rather than explicitly disallow) while discouraging low entropy, high risk KBV.

**Comment by rsfaron23** [comment]
Agree: sometimes the agency (RP) use case does not have enough at risk to justify any added verification processes. and sometimes the RP is the verifying agent based on transactional attribute values that the subscriber alone could know or a trusted agent might know. In those cases other security features besides strong identity may be just enough to lower the risk to tolerable levels.
