### ISSUE TITLE
Scoring identity evidence 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#253]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63A

**Reference (Include section and paragraph number)**: 
Section 5.3.1.1  - Discussing scoring identity evidence

(KI Ref: KI/ADG#10)

**Comment (Include rationale for comment)**: 
It would be great if specific real world examples could be identified and scored. 

**Suggested Change**: 
Include concrete examples of identity evidence and how they score.

**Comment by paul-grassi** [comment]
We expect 'operational/implementer guides' to follow this effort.  This would also be what a trust framework could profile (for example, TF X accepts the following STRONG documents) and is also a great thing for TF providers like @KantaraInitiative-IAWG to do.
