### ISSUE TITLE
Identity Evidence Validation 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#254]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63A

**Reference (Include section and paragraph number)**: 
Section 5.3.2.1 - Methods to Perform Identity Evidence Validation

(KI Ref: KI/ADG#11)

**Comment (Include rationale for comment)**: 
The section lists “validation of evidence failed” as an unacceptable strength of validation, but that is a possible outcome of verification at any strength.  Unacceptable strength of validation would be skipping validation or doing it wrong.

**Suggested Change**: 
Remove "validation of evidence failed" from the list of validation strengths. Replace with "no validation performed".

**Comment by paul-grassi** [comment]
If an attempt at any strength failed, you would immediately drop into 'unacceptable' and not pass this phase of proofing.  However, 'no validation or validation failed' is appropriate.  Good comment!
