### ISSUE TITLE
Threats and requirements 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#255]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63A

**Reference (Include section and paragraph number)**: 
Section 7.1 - Threat Mitigation Strategies

(KI Ref: KI/ADG#13)

**Comment (Include rationale for comment)**: 
Threats and security considerations do not seem to end up mapped to requirements - for example two person control is a recommended mitigation for unauthorized issuance, where does that show up as a requirement?

**Suggested Change**: 
Map threats to requirements to confirm coverage.

**Comment by paul-grassi** [comment]
All of the Threats and Security Considerations chapters are non-normative.
