### ISSUE TITLE
Machine-to-machine authentication 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#256]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63B

**Reference (Include section and paragraph number)**: 
Section 2 - Introduction 

(KI Ref: KI/ADG#14)

**Comment (Include rationale for comment)**: 
The document says that machine-to-machine authentication is out of scope, that is a very unfortunate choice. Endpoint security is critical to achieving high trust in user authentication, and endpoint security requires machine-to-machine authentication.  

**Suggested Change**: 
Include discussion of machine-to-machine authentication in the scope of the DAG.

**Comment by jricher** [comment]
Within this document, we define an "authenticated trusted channel", which is essentially TLS with server certificate authentication, and this is essential for user authentication to happen. This requirement is a far cry from full "machine to machine" authentication where the client is authenticated as well, such as with mutual TLS. 

This type of authentication is really better suited to a document focusing on APIs and other machine-facing services, which NIST may publish in the future.
