### ISSUE TITLE
Strongly bound credentials

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#257]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63B

**Reference (Include section and paragraph number)**: 
Section 3 - Definitions and abbreviations

(KI Ref: KI/ADG#15)

**Comment (Include rationale for comment)**: 
Strongly bound credentials: Recommend that the definition include the idea that strongly bound credentials also authenticate the issuer of the credential. 

**Suggested Change**: 
New definition: "Credentials that are bound to a subscriber in a tamper-evident fashion, that enable the relying party to authenticate the issuer of the credential."

**Comment by paul-grassi** [comment]
We will remove the definition since it isn't used within the document.
