### ISSUE TITLE
Social Engineering 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#258]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63B

**Reference (Include section and paragraph number)**: 
Section 3 - Definitions and abbreviations

(KI Ref: KI/ADG#16)

**Comment (Include rationale for comment)**: 
Social Engineering definition needs to be expanded to include deceiving an organization into issuing credentials or otherwise modifying credential lifecycles.

**Suggested Change**: 
Append to the definition "or deceiving an organization into issuing credentials or otherwise modifying credential lifecycles."

**Comment by jimfenton** [comment]
This aspect of social engineering has more to do with the issuance process than authentication itself, so treating it as a 63A issue.

**Comment by paul-grassi** [comment]
Will include this in Ch 7.
