### ISSUE TITLE
Remote definition 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#259]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63B

**Reference (Include section and paragraph number)**: 
Section 3 - Definitions and abbreviations

(KI Ref: KI/ADG#17)

**Comment (Include rationale for comment)**: 
The definition of remote should be made as tight as possible, it currently leaves a lot of room for misinterpretation by those that are not familiar with security controls. Without knowing what security controls an organization uses to protect their networks, one should be very hesitant to say two endpoints are not remote.

**Suggested Change**: 
Clarify the definition to explain when  and how security controls can ameliorate remoteness.

**Comment by paul-grassi** [comment]
We believe the definition is broad enough.
