### ISSUE TITLE
Conflict(?) between Gen Req 4.2.7 and and IAL3 Req 4.6.6

### ISSUE THREAD

**Issue by hongmoyang** [usnistgov/800-63-3#26]
**Organization**:  2

**Type**:  

**Reference (Include section and paragraph number)**: General Req 4.2.7 states:  The CSP SHALL record the types of identity evidence presented in the proofing process, including any identification and reference number. The CSP SHALL NOT record an image, scan, or other copy of the evidence.

IAL3 Req. 4.6.6 states:  The CSP SHALL collect and record a current biometric (e.g., photograph or fingerprints) to ensure that the applicant cannot repudiate application.

**Comment (Include rationale for comment)**:  There seems to be an apparent conflict - under what circumstance/context should CSP capture or record an image, scan, or other copy of the evidence?  

**Suggested Change**:  Perhaps a rephrasing of the General Requirement 4.2.7 to allow for capturing or recording for satisfying specific IAL level requirements?

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
For privacy reasons and to limit the amount of unnecessary data a CSP has, we do not want a copy of any identity evidence to be retained by the CSP.  At IAL3, we want a biometric captured for non-repudiation reasons.
