### ISSUE TITLE
Entropy

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#260]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63B

**Reference (Include section and paragraph number)**: 
Section 3 - Definitions and abbreviations

(KI Ref: KI/ADG#18)

**Comment (Include rationale for comment)**: 
Recommend adding a definition of entropy, since the term is used in various places in the document.  Appendix A says that the term won't be used, but Appendix A is non-normative.

**Suggested Change**: 
Either define entropy or don’t use the term.

**Comment by jimfenton** [comment]
Section 3 does define entropy, but the definition is fairly terse. We will expand on it.
