### ISSUE TITLE
Strength  of authentication

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#261]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63B

**Reference (Include section and paragraph number)**: 
Section  - 

(KI Ref: KI/ADG#19)

**Comment (Include rationale for comment)**: 
There are frequent references to “strength” of authentication, ultimately the concept is not defined except to say that the AAL represents strength, higher AAL is stronger, lower AAL is weaker.  Ultimately this reduces the utility of the AAL

**Suggested Change**: 
Provide some narrative about what is meant by the strength of authentication.  One possibility is that "stronger" means that more resources are required to subvert the processes.

**Comment by jimfenton** [comment]
I was surprised that the term _strength_ didn't appear more.

Adding text in the introduction to further clarify what is meant by strength.
