### ISSUE TITLE
Authenticator and Verifier Requirements

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#262]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63B

**Reference (Include section and paragraph number)**: 
Section 4.2.2 - Authenticator and Verifier Requirements

(KI Ref: KI/ADG#20)

**Comment (Include rationale for comment)**: 
Section 4.2.2 says that "Cryptographic authenticators used at AAL 2 SHALL use approved cryptography. Authenticators developed by government agencies SHALL be validated to meet the requirements of [FIPS 140] Level 1".  Apparently the reason is to support BYOD approaches, so the user doesn't have to maintain a FIPS 140-2 validated platform.  Could the requirements at least please state that FIPS 140 requirements are a target, regardless of whether certification is required. There should be a preference for using certified modules, but a risk determination could approve operating in non-approved configurations.

**Suggested Change**: 
Recommend that all authenticators SHOULD be validated.

**Comment by vanderaj** [comment]
We have a lot of these sorts of requirements in the Application Security Verification Standard, and we've had experience in what's possible. FIPS 140-2 is a difficult target for an average developer to reach or maintain, and often ends up going with a particular commercial crypto library, instead of using what they know on their preferred platform, which may be good enough. 

Happy to help draft some text here if you need assistance.

**Comment by jimfenton** [comment]
The key phrase here is _developed by government agencies_. My impression is that government agencies don't generally _develop_ authenticators; they purchase commercial products or contract for their development so it's not entirely when this phrase applies.

The intent here is to allow commercial off-the-shelf products to be used in most cases at AAL 2, especially when the authenticators are multi-use platforms like mobile phones. It's a non-starter (and probably counter-productive for security) to tell subscribers not to update the software on their devices until it has been FIPS 140-2 verified.

At one point we had discussed requiring design to meet FIPS requirements and no verification at AAL 2, but that was dropped in favor of this wording. We need to discuss this further.

In the meantime @vanderaj if you have some text to offer, we'd be happy to consider it.
