### ISSUE TITLE
Shoulder surfing 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#263]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63B

**Reference (Include section and paragraph number)**: 
Section Appendix A Item A.1 - Strength of Memorized Secrets

(KI Ref: KI/ADG#21)

**Comment (Include rationale for comment)**: 
There's an observation that "shoulder surfing" attacks are only slightly more difficult for complex passwords, is there a citation for this claim? It would seem would think that requiring mixed case passwords means that the attacker must observe multiple fingers on the keyboard at once, for example.  

**Suggested Change**: 
Remove the shoulder surfing explanation or provide citation for the information.

**Comment by jimfenton** [comment]
Removing it because it isn't an essential point to make and may not be 100% accurate as you point out.
