### ISSUE TITLE
Keystroke logging

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#264]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63B

**Reference (Include section and paragraph number)**: 
Section Appendix A Item A.1 - Strength of Memorized Secrets

(KI Ref: KI/ADG#22)

**Comment (Include rationale for comment)**: 
The argument about keystroke logging doesn't really make sense as an argument about password complexity - keystroke logging is equally effective against all lengths of password just like all complexities of passwords, so that does not really argue for leaving complexity out of the equation but not length - it argues for addressing endpoint security. 

**Suggested Change**: 
Remove the discussion of keystroke logging from this section, put it in the endpoint security section.

**Comment by jimfenton** [comment]
Section A.1 introduces Section A.2, Length, and Section A.3, Complexity but the introductory text only mentioned complexity. Adding mention of length as well.
