### ISSUE TITLE
Requirements for RPs to report bad behavior of subscribers

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#265]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63B

**Reference (Include section and paragraph number)**: 
Section  6.2 - Loss, Theft, and Unauthorized Duplication

(KI Ref: KI/ADG#23)

**Comment (Include rationale for comment)**: 
Recommend Section 6.2 consider including requirements for RP's to report bad behavior by subscribers - see NISTIR 7817 for discussion of credential reliability.

**Suggested Change**: 
Add requirements at higher assurance levels for RPs to report bad behavior that could be indicators of compromise.

**Comment by paul-grassi** [comment]
This is a good requirement for federated environments, which is the domain of the -C document.  -C already contains text in [Section 4](https://pages.nist.gov/800-63-3/sp800-63c.html#sec4).  The text is: A IdP MAY disclose information on subscriber activities to other RPs within the federation for security purposes such as communication of compromised subscriber accounts.
