### ISSUE TITLE
Mitigating Authenticator Threats

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#266]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63B

**Reference (Include section and paragraph number)**: 
Section 8.2 - Threat Mitigation Strategies

(KI Ref: KI/ADG#24)

**Comment (Include rationale for comment)**: 
Table 5 Mitigating Authenticator Threats the mitigation strategy should always be a complete sentence that identifies the subject for every verb.  Some actions are taken by identity system developers, some by issuers, some by subscribers.

**Suggested Change**: 
Rewrite to make clear which entity does what in order to mitigate the threat. Also make sure the table unambiguously maps mitigations to threats.

**Comment by jimfenton** [comment]
The strategies are complete sentences, just imperative statements.

Since Section 8 is non-normative, we want to avoid language that implies otherwise, like "The claimant shall do so-and-so". One way to avoid this might be wording like, "Claimant: Do so-and-so."
