### ISSUE TITLE
Threats -  Mitigations strategies

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#267]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63B

**Reference (Include section and paragraph number)**: 
Section 8.2 - Threat Mitigation Strategies

(KI Ref: KI/ADG#25)

**Comment (Include rationale for comment)**: 
Phishing/pharming and social engineering both have the same mitigation strategy as for "eavesdropping". Is that intended?

**Suggested Change**: 
Add the correct mitigation strategies for the threats.

**Comment by jimfenton** [comment]
We will update the mitigation mechanisms.
