### ISSUE TITLE
When multiple valid authenticators are not available

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#268]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63B

**Reference (Include section and paragraph number)**: 
Section 8.3 - Authenticator Recovery

(KI Ref: KI/ADG#26)

**Comment (Include rationale for comment)**: 
Section 8.3 should explain what to do when subscriber fails to maintain two valid authenticators at all time.  Repeat identity proofing, or follow an approach such as the FIPS 201 / PIV chain of trust. 

**Suggested Change**: 
Include a discussion of what to do multiple valid authenticators are not available.

**Comment by jimfenton** [comment]
Please see new section 6.1.2.3 that was added recently by #329 and let us know if that addresses this comment sufficiently.
