### ISSUE TITLE
Authenticator Recovery - Distinction 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#269]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63B

**Reference (Include section and paragraph number)**: 
Section 8.3 - Authenticator Recovery

(KI Ref: KI/ADG#27)

**Comment (Include rationale for comment)**: 
There's a distinction between using multiple authenticators and using authenticators that embody multiple authentication factors.

**Suggested Change**: 
Authenticator recovery is for recovering authenticators, not authentication factors.

**Comment by jimfenton** [comment]
Sections 6.1.2.2 and 6.1.2.3 (added by #329) should address the dictinction between multiple authenticators and recovery. The text in section 8.3, which is not normative, is just trying to describe the issues with adding authenticators of a different factor following the loss of an authenticator if the CSP does not take appropriate precautions.

Please let us know if the new text sufficiently addresses the issue.
