### ISSUE TITLE
FIPS Level clarification for AAL 2 authenticators

### ISSUE THREAD

**Issue by TerryMcBride** [usnistgov/800-63-3#27]
**Organization**: 1

**Type**:

**Reference (Include section and paragraph number)**: 800-63-B, Section 4.4 Summary of Requirements, FIPS 140 Verification Row, AAL 2 Column

**Comment (Include rationale for comment)**:
The cell says: 
Level 1 (single factor),
Level 2 (multi factor

However Multi-Factor Software Cryptographic Authenticator should be FIPS 140 Level 1 pretty much be definition (Software) - even though it is "multi-factor"

**Suggested Change**:

Change to:
Level 1 (Software)
Level 2 (Hardware)

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
The FIPS 140 requirements in the section 4.4 requirements summary were out of sync with the normative requirements in sections 4.1.2, 4.2.2, and 4.3.2. We'll be changing them to be consistent with those sections, and a bit different from the text you suggested. Thanks for pointing out the inconsistency.
