### ISSUE TITLE
Endpoint security requirements

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#270]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  General

**Reference (Include section and paragraph number)**: 
Section  - Endpoint security requirements

(KI Ref: KI/ADG#28)

**Comment (Include rationale for comment)**: 
Endpoint security requirements should be discussed in the document. Prior drafts discussed endpoint security in terms of Common Criteria, but all references to that standard appear to have been removed from the document, without a clear replacement.

**Suggested Change**: 
Include discussion of endpoint security in all of the threat analyses.

**Comment by paul-grassi** [comment]
Agency endpoint requirements are well documented in 800-63 and its pointers to 800-53.  It's out of scope for this document to specify endpoint requirements for consumer computing, nor is it enforceable. Agencies will determine special requirements, if any, based on risk, mission, and use case.
