### ISSUE TITLE
IETF VOT standard

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#272]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  General 

**Reference (Include section and paragraph number)**: 
Section  - IETF VOT standard 

(KI Ref: KI/ADG#30)

**Comment (Include rationale for comment)**: 
We note that there are multiple instances in the updated guidance in which technologies and techniques with limited security properties are being deprecated (e.g. SSN and KBV).  We support the DAG's is effort to break up the monolithic assurance levels into functional topic areas, and suggest that the IETF VOT standard be extended and refined to support expression of the techniques underlying credential issuance and other relevant details, so that RPs can make appropriately fine-grained risk based decisions, whether at "trust time" or at "authentication time".

**Suggested Change**: 
Develop a roadmap towards utilizing IETF VOT to express details about authentication risk mitigations, and support the development of VOT to support the metrics of interest.

**Comment by jimfenton** [comment]
IETF VOT is an [internet draft](https://datatracker.ietf.org/doc/draft-richer-vectors-of-trust/) at this point; it is a work in progress and there is no standard to utilize yet.
