### ISSUE TITLE
Infrastructure services - federations and assertion schemes 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#273]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63C

**Reference (Include section and paragraph number)**: 
Section 4 and 5 - Federation and Assertions 

(KI Ref: KI/ADG#31)

**Comment (Include rationale for comment)**: 
Architectural model does not address infrastructure services.

**Suggested Change**: 
Include discussion of the infrastructure services that underlies federations and assertion schemes.

**Comment by jricher** [comment]
Infrastructure services are entirely dependent upon the underlying protocols and therefore not appropriate to be addressed in this document.
