### ISSUE TITLE
Federations - Policy frameworks 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#274]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63C

**Reference (Include section and paragraph number)**: 
Section 4 - Federation

(KI Ref: KI/ADG#32)

**Comment (Include rationale for comment)**: 
Federation means interoperation between network systems controlled by different governing bodies, following different rules. The federation is an agreement between governing bodies about how to consider each others rules within their own scheme.  Assertions and federation are around technical requirements for setting up authoritative services and connecting metadata - in actual implementations there's technology and policy considerations.

**Suggested Change**: 
Include discussion of the policy frameworks that underlies federations.

**Comment by jricher** [comment]
Federation may also take place between parties controlled by the same governing organization, or it may occur with no overarching governance (such as an OIDC connection using dynamic registration and discovery). This document is focused on the technology and not the policy and governance between parties in a federation agreement.
