### ISSUE TITLE
Document content and name - 63C

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#275]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63C

**Reference (Include section and paragraph number)**: 
Section  - Document content and name

(KI Ref: KI/ADG#33)

**Comment (Include rationale for comment)**: 
It seems that the overall document should be described as a collection of assertion assurance levels rather than federation assurance levels.

**Suggested Change**: 
Develop more material about federation requirements or refer to the document as assertion assurance levels.

**Comment by jricher** [comment]
Assertions are the mechanism by which federations communicate identity information, so the content and title are accurate.
