### ISSUE TITLE
Federations models - Central Authority 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#277]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63C

**Reference (Include section and paragraph number)**: 
Section 4.1.1 - Federation models - Central Authority 

(KI Ref: KI/ADG#35)

**Comment (Include rationale for comment)**: 
Use of the word "trust" in the first sentence of 4.1.1 is redundant - the parties are more likely to establish contracts (SLA/MOU) with a central authority to make trust decisions on their behalf.

**Suggested Change**: 
Change trust to "contract".

**Comment by jricher** [comment]
This document does not mandate business contracts or other legal mechanisms for trust establishment, only requiring that such mechanisms be in place.
