### ISSUE TITLE
Federation requirements

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#278]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63C

**Reference (Include section and paragraph number)**: 
Section 4 - Federation - requirements 

(KI Ref: KI/ADG#36)

**Comment (Include rationale for comment)**: 
There are no assurance requirements and very few "SHALL" statements in the federation section. Adding those could be a way to implement the federation assurance level (FAL) that the document talks about.

**Suggested Change**: 
Consider what requirements might be applicable in the federation section.

**Comment by jricher** [comment]
The requirements are found throughout the document, and largely dependent upon which FAL is desired to be reached.
