### ISSUE TITLE
Threat Mitigation Strategies

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#281]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63A

**Reference (Include section and paragraph number)**: 
Section 7.1 - Threat Mitigation Strategies

(KI Ref: KI/ADG#12)

**Comment (Include rationale for comment)**: 
e.g. Table 2 Enrollment and Issuance Threat Mitigation Strategies, the mitigation strategy should always be a complete sentence that identifies the subject for every verb.

**Suggested Change**: 
Rewrite to make clear which entity does what in order to mitigate the threat.

**Comment by paul-grassi** [comment]
The strategies are complete sentences, just imperative statements.

Since Section 7 is non-normative, we want to avoid language that implies otherwise, like "The applicant shall do so-and-so".
