### ISSUE TITLE
Clarification of how a second factor shall be operated with the first factor

### ISSUE THREAD

**Issue by hitoshikokumai** [usnistgov/800-63-3#282]
**Organization**: 3

**Type**: Security design

**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**:  5.2.3

**Comment (Include rationale for comment)**:   It reads “Biometrics SHALL be used with another authentication factor (something you know or something you have)” at one place and “The biometric system SHALL allow no more than 10 consecutive failed authentication attempts. Once that limit has been reached, the claimant SHALL be required to use a different authenticator or to activate their authenticator with a different factor such as a memorized secret” at another place.

The former leads us to assume that the biometrics and another factor should be operated by AND/Conjunction (we need to go through both of the two) but the latter leads us to assume that the operation of the biometrics and another factor by OR/Disjunction (we need only to go through either of the two) is allowed.  

Operation by AND/Conjunction and that by OR/Disjunction is mutually exclusive.  Logic does not allow such a third way as both of AND/Conjunction and OR/Disjunction are allowed at the same time.  NIST is expected to make clear which is required.

Incidentally, the means of account recovery should not be brought into this discussion.  It would make the discussion opaque.  The means of account recovery should be considered separately in a different context.

**Suggested Change**:   If NIST's intention is to allow only AND/Conjunction (we need to go through both of the two), I would suggest that the latter sentence should be changed to ““The biometric system SHALL allow no more than 10 consecutive failed authentication attempts. Once that limit has been reached, the claimant SHALL get no access”.

If NIST's intention is to allow OR/Disjunction (we need only to go through either of the two), I would suggest that the former sentence should be removed for clarity’s sake.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
There is no logical problem here. The use of multiple authenticators is permitted, and even encouraged to avoid the problems associated with account recovery. Biometrics, which have a hard limit of 10 consecutive failed authentication attempts, particularly need to be backed up by another authenticator because of the likelihood that they will encounter that limit.
