### ISSUE TITLE
definition: Claimant - one or more auth protocol?

### ISSUE THREAD

**Issue by wangxjnj** [usnistgov/800-63-3#285]
**Organization**:

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 3

**Comment (Include rationale for comment)**:
 "Claimant: A party whose identity is to be verified using an authentication protocol."

what is "authentication protocol"? It is not defined in the doc. What are the differences among the: protocol, factor and authenticator? Some of claimants may require to be verified by multiple factors. 
**Suggested Change**:
 "Claimant: A party whose identity is to be verified using **one or more** authentication factors."

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
Authentication Protocol is defined in SP 800-63B section 3, definitions:

> A defined sequence of messages between a claimant and a verifier that demonstrates that the claimant has possession and control of a valid authenticator to establish his/her identity. Secure authentication protocols also demonstrate to the claimant that he or she is communicating with the intended verifier.

However, _valid authenticator_ should perhaps read _one or more valid authenticators_, so this will be corrected.

**Comment by wangxjnj** [comment]
about the "Secure authentication protocols also demonstrate to the claimant that he or she is communicating with the intended verifier.": 
1. protocols --> protocol ( consistent with the definition)
2. secure vs non-secure auth protocol? definitions(what makes  an auth protocol secure or not secure)
3. intended verifier --> intended verifier**(s)** for multiple authenticator verifications
4. what the auth flow should look like based on the requirement? Use case: a bank web app requires Kerberos Auth.   Suppose that I am a customer of the bankA. I go to their web site, and present my loginID and Kerberos passwd. Once authenticated by their AD infra I will  be presented with the bellow info:
1.  a statement like " TRUST ME. I am the one verified your passwd."
2.  here is my certificate, and signed by CA XXX
3. here is the the clear text "YYYYYYYY"
4. here is the ciphertext "GGJIYRTKKKKKl...." encrypted using my private key
5. please go somewhere/use some tool to decrypt the ciphertext using my public key from my cert, and verify  that the clear texts match 

"
