### ISSUE TITLE
Change from e-authentication to d-authentication

### ISSUE THREAD

**Issue by DavidStaggs** [usnistgov/800-63-3#29]
Digital authentication is the process of establishing confidence in user identities digitally presented to an information system. Digital authentication presents a technical challenge when this process involves the authentication of individual people over an open network for the purpose of digital government and commerce.

Respectfully recommend using electronic authentication (e-authentication) instead of the term digital authentication (presumably  d-authentication) for historical continuity.  Creation of a new term will cause confusion in those relying on the NIST standards (unless there is a good reason to distinguish the terms).

**Comment by paul-grassi** [comment]
We will update any references to make sure consistency is retained.
