### ISSUE TITLE
Definitions for Direct and Indirect

### ISSUE THREAD

**Issue by jim-thomson** [usnistgov/800-63-3#293]
**Organization**: 3

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63C

**Reference (Include section and paragraph number)**: Section 3 and Section 6

**Comment (Include rationale for comment)**: The terms "direct" and "indirect" are used in several ways, and often it is not clear which meaning is intended. 

"Indirect" and "direct" refer to what were consistently known as the Indirect and Direct Assertion models in 800-63-2. Now they are known as either the "indirect federation model" (Section 5.1.2), or the Direct and indirect Presentation models (Section 6).

**Suggested Change**: Since the key distinction, as shown in the words, are assertions versus assertion references, recommend using those terms rather than direct and indirect. This  reduces confusion in the broader space between direct authentication and indirect authentication; the latter being what's described in this document because of the use of a verifier and assertion.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
Good point, though even with an assertion reference you still need to fetch the assertion from the IdP.

**Comment by jim-thomson** [comment]
My comment wasn’t about the steps involved, it was about changing the terminology. I would like to avoid overloading any word, in this case, direct (and indirect). I’ve seen material utilizing 800-63-2 (DoD JIE IdAM Portfolio, I believe) that confused indirect authentication with retrieving the assertion indirectly.

Also, I believe token was deprecated precisely because it too is an overloaded term.

Jim Thomson
MITRE

**Comment by jricher** [comment]
Defining and using good terms for a comprehensive technical document like this is difficult, as any word chosen is going to be automatically overloaded in other circumstances (just look at the use of "token" in 800-63-2, which we've corrected here). We're open to better terms here, but don't think that referring to the assertion directly in this way is the right choice.
