### ISSUE TITLE
Holder of Key Question

### ISSUE THREAD

**Issue by jim-thomson** [usnistgov/800-63-3#294]
**Organization**: 3

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63C

**Reference (Include section and paragraph number)**: Section 5.1.1

**Comment (Include rationale for comment)**: "The RP may [emphasis added] require the subscriber to prove possession of the key …" seems contradicted by 6.1's "The assertion is still considered a bearer assertion if the artifact required to fetch the Assertion does not require presentation of additional proof of key possession after the assertion has been fetched." 

Doesn't Holder of Key, the subject of this section mandate the subscriber provide proof of possession, by definition?

**Suggested Change**: Change "may" to "shall" or "must".

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
This can be clarified. Technically, the RP can decide when it wants to prompt the user to prove the HoK status, but the normative requirement is to prove it. We'll import some of the language from 6 into 5 to make this more clear.
