### ISSUE TITLE
Digital Signing Question of "May"

### ISSUE THREAD

**Issue by jim-thomson** [usnistgov/800-63-3#295]
**Organization**: 3

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63C

**Reference (Include section and paragraph number)**: Section 5.2.2

**Comment (Include rationale for comment)**: "Assertions MAY be cryptographically signed by the CSP …" seems too permissive. It seems that unsigned assertions are pointless, from a security perspective.

**Suggested Change**: Change "may" to "shall" or "must".

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
You'll note that within the FAL definitions, signatures are required at all levels in practice.

**Comment by jim-thomson** [comment]
I see it was closed before I could respond…… Nevertheless, if not signed, does it make it FAL Level 0? Why make it optional in the text?

Jim Thomson
MITRE

**Comment by jricher** [comment]
You can still respond to closed issues (as you just did), and we can always reopen them if there's need.

There is no FAL level 0. An assertion without a signature has no defined FAL, but we acknowledge that it exists. If delivered directly over a highly trusted channel, the signature on the assertion itself adds security but isn't strictly necessary for secure operation. 

But that said, the baseline recommendation for federal systems is a signed assertion, thus FAL1 starts there. Other frameworks can define their own levels which may include signature-less assertions at some level of their choosing.
