### ISSUE TITLE
Positive Confirmation Too Restrictive

### ISSUE THREAD

**Issue by jim-thomson** [usnistgov/800-63-3#296]
**Organization**: 3

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63C

**Reference (Include section and paragraph number)**: Section 6

**Comment (Include rationale for comment)**: "The RP MAY [emphasis added] require the subscriber to prove possession of the key …" seems contradicted by 6.1's "The assertion is still considered a bearer assertion if the artifact required to fetch the Assertion does not require presentation of additional proof of key possession after the assertion has been fetched." 

Doesn't Holder of Key, the subject of this section mandate the subscriber provide proof of possession, by definition?

**Suggested Change**: Change "SHALL" to "SHOULD".

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jim-thomson** [comment]
Comment should have said:
"Positive confirmation SHALL be obtained from the subscriber before any attributes about the subscriber are transmitted to any RP. If the protocol in use allows for optional attributes, the subscriber SHALL be given the option to decide whether transmit those attributes to the RP. " is too restrictive and too cumbersome. 

Even allowing for the possibility that this statement allows an implementation where employees sign statements acknowledging that their attributes will be shared for access, this statement is too restrictive. In my mind, it elevates privacy concerns above the need to manage access. Furthermore, the second statement forces querying the subscriber about optional attributes for each and every RP. It presumes that the user can understand what each RP is and imagine how the RP may misuse those optional attributes. Since optional attributes are nod defined, it's not clear whether these are meant to be any attributes (since including attributes are not required by the spec) or they are attributes that the RP is [somehow] known to not require for authorization.

I apologize for the error.

**Comment by jricher** [comment]
The positive confirmation can happen at any time, not just at runtime. In most OIDC runtime transactions, there's an interstitial approval screen for graylisted parties. For whitelisted parties, there's going to be a policy acknowledged by the subscriber for use of their attributes at the IdP. The current language is not intended to be onerous or create undue burden on the IdP. "Optional" attributes is dependent on the underlying technology, as OIDC does not define a mechanism for them but other protocols do.
