### ISSUE TITLE
Any Party Requirement is Too Restrictive

### ISSUE THREAD

**Issue by jim-thomson** [usnistgov/800-63-3#297]
**Organization**: 3

**Type**: 

**Document (63-3, 63A, 63B, or 63C)**: 63C

**Reference (Include section and paragraph number)**: Section 6

**Comment (Include rationale for comment)**: "Any party in the transaction who collects attribute information SHALL provide notice and obtain confirmation from the subscriber." is too restrictive. 

In service chaining scenarios, a service down the chain may not have connectivity to the user to obtain confirmation. For example, a user is interested in tornado warnings. Services in a chain finally get to a service that estimates the time until tornados may strike the user's location, so the service queries the CSP for that data item. However, no connection can be made to the user for confirmation allowing the user's location to be used.

**Suggested Change**: Change "SHALL" to "SHOULD".

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
In the example given, I would have expected the user to give informed consent at the time they signed up to receive tornado warnings. Or more likely that they would have signed up to receive tornado warnings for a specific area where they live. I don't see anything saying that the consent can't be persistent.

**Comment by jim-thomson** [comment]
But my point is that the service requesting location doesn’t know the user gave permission. It only knows that it needs location. The “shall” requirement levies a consent infrastructure onto chained services that may be cumbersome to initiate. The fundamental problem is that services at the head of the chain don’t necessarily know what attributes might be needed downstream, and thus can’t get confirmation. Furthermore, conveying confirmation in attribute assertions is a lot of work. NISTIR 8112 provides a way to convey this information and a cleaner way to deal with this is to say that the RP SHOULD adhere to any AVM PII restrictions associated with any attributes it uses.

Jim Thomson
MITRE

**Comment by andrewhughes3000** [comment]
If the attributes in question consist of PII then notice to the subject of
the intended use is best practice (and, in fact required in most
jurisdictions).

The 'tornado warning' scenario is perhaps not ideal to illustrate this
point since it is reasonably easy to envision what a notice/consent would
look like as Jim F noted.

_Andrew Hughes *CISM CISSP
Independent Consultant
*In Turn Information Management Consulting_

o  +1 650.209.7542
m +1 250.888.9474
1249 Palmer Road,
Victoria, BC V8P 2H8
AndrewHughes3000@gmail.com
ca.linkedin.com/pub/andrew-hughes/a/58/682/
*Identity Management | IT Governance | Information Security *

**Comment by paul-grassi** [comment]
And when the user signed up for tornado notifications, the consented that the information may be queried when they aren't present.  This is what Oauth provides for as well.  I delegate authorization to my information, even when I am not present, and I explicitly opt-in for sharing of said information.  The requirement isn't meant for run-time confirmation any time the data is used, just when it is collected (provided use is in-line with what they said they would do with the information.

**Comment by jricher** [comment]
Note that it's the party _collecting_ attribute information that is required to gather consent. This generally means the IdP, not the RP in most federation transactions. In the chaining scenario you mention, the downstream participants are not collecting attributes from the user, they're receiving them as part of the federation transaction.

**Comment by jim-thomson** [comment]
OK, but that’s not how I read it. If I misinterpreted it, perhaps others will. Please consider whether a wording tweak can reduce misinterpretation. But no suggestions come to mind, so maybe that’s the best it can be.
