### ISSUE TITLE
Direct vs. Indirect Replay

### ISSUE THREAD

**Issue by jim-thomson** [usnistgov/800-63-3#298]
**Organization**: 3

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63C

**Reference (Include section and paragraph number)**: Section 6.2

**Comment (Include rationale for comment)**: "… the direct method also allows the assertion to be replayed to other RPs by the subscriber." implies that indirect presentation can't be replayed. In the indirect presentation model, an assertion reference is used. It's not intuitively obvious why this can't be replayed.

**Suggested Change**: Add a statement for informative reasons why assertion references are resistant to replay that direct presentations are not.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
This can be made more clear. In general, assertion references are one time use (we might even want to make this a normative SHOULD) whereas an assertion is usually good within a larger lifetime and is designed to be self-contained. In practice this means that assertions in the wild are often generated to target multiple RPs at once, or don't have audience restriction in them. This wider playback space offers more attack surface and greater chance of the presenter handing the assertion to an unintended party. In the direct method, the assertion is fetched from the IdP itself.

**Comment by jim-thomson** [comment]
The last comment ends with "In the direct method, the assertion is fetched from the IdP itself." but I infer from this a backchannel call from the RP to the IdP. But I was contrasting the first sentence of 6.2: "In the direct model, the CSP creates an assertion and sends it directly to the subscriber" with creating an assertion REFERENCE (not shouting, just italicizing) that is sent directly to the subscriber, ala SAML WebSSO Artifact bindings. But perhaps I'm reading too much into "fetched" and it doesn't mean RP-initiated to the IdP but simply part of the subscriber<=> IdP protocol.

**Comment by jricher** [comment]
Sorry, that should say "indirect". So I agree, the terms can be confusing. 

Perhaps we can use "front channel delivery" and "back channel delivery" instead? With the latter requiring a reference.
