### ISSUE TITLE
Attribute Claims Definition

### ISSUE THREAD

**Issue by jim-thomson** [usnistgov/800-63-3#299]
**Organization**: 3

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63C

**Reference (Include section and paragraph number)**: Section 6.4

**Comment (Include rationale for comment)**: "The RP SHALL, where feasible, request attribute claims rather than full attribute values. The CSP SHALL support attribute claims." Attribute claims are undefined. Please define attribute claims in the glossary.

**Suggested Change**:

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
Thanks!  I'll double check.  I think we defined in -A and didn't carry forward to -C.

**Comment by jim-thomson** [comment]
I messed up and pasted in the wrong Comment to one of my issues. Feel free to just correct it at the original item and delete my correction. It will be cleaner all the way around. Sorry about making that mistake.

I had a personal  deadline to submit comments prior to your presentation.

**Comment by paul-grassi** [comment]
We will also change the definition of attribute to 'A quality or characteristic ascribed to someone or something.'

**Comment by jricher** [comment]
Another name for "attribute claims" in the general world is "zero knowledge proof".
