### ISSUE TITLE
Unicode passwords & normalization issues

### ISSUE THREAD

**Issue by nickmalcolm** [usnistgov/800-63-3#301]
**Organization**: [ThisData](https://thisdata.com)
**Type**: 2
**Document (63-3, 63A, 63B, or 63C)**: 63B
**Reference (Include section and paragraph number)**: 5.1.1.2. Memorized Secret Verifiers
**Comment (Include rationale for comment)**:

5.1.1.2 contains the following statement: 

> Unicode [ISO/ISC 10646:2014] characters SHOULD be accepted as well

I agree with the principle that any character should be permissible in a Memorized Secret. However there are issues, particularly in web based applications, with accepting unicode characters. As an example:

> _if someone sets their password to "mañana" (ma\u00F1ana) on one computer and tries to log in with "mañana" (ma\u006E\u0303ana) on another computer, the hashes will be different and the login will fail_
> Source: https://stackoverflow.com/questions/16173328/what-unicode-normalization-and-other-processing-is-appropriate-for-passwords-w

Is it within the scope of this document / project to discuss this issue? Perhaps it's a matter for browser vendors / OS creators?

When the Verifier controls the input of the password (e.g. a mobile app, or a systems administrator) they can probably mitigate this issue.
For web applications accessible on arbitrary browser on arbitrary operating systems, this is (as I understand it) out of their control.

I thought I'd raise the issue here for discussion - apologies if it's inappropriate!

**Suggested Change**:

No suggested change.

**Comment by jimfenton** [comment]
Thanks for pointing out the sublety here -- there is a lot more to this than I had expected.

The original thought was to not do any normalization other than to accommodate differences in representation (between UTF-8 and UTF-16, for example).

But the point of this is to make it easier for people whose primary language isn't English to create memorable secrets (not just cute emoji passwords!). But if different endpoints are likely to create different representations of the same character, it actually makes it less usable. Do you have an idea if that is the case, or is the same user likely to compose the same character the same on different endpoint types?

**Comment by GaryGapinski** [comment]
http://unicode.org/faq/normalization.html may be of interest.

**Comment by zerkms** [comment]
> The original thought was to not do any normalization

And that's the problem: it is browsers that may change the input _before_ the request is sent.

> Do you have an idea if that is the case, or is the same user likely to compose the same character the same on different endpoint types?

It is not the problem. The problem is on different browsers/potentially on the same browsers but different versions/may be between OS updates the normalisation might be applied differently for the very same input.

**Comment by nickmalcolm** [comment]
> is the same user likely to compose the same character the same on different endpoint types

I don't have any data on that unfortunately, however as @zerkms said the issue is that even _if_ the user types it the same (which they likely will), it's the browsers or operating systems which decide how to normalize that character when it hits the input field.

It _sounds like_ Webkit-based browsers normalize form data to NFC, whereas IE, Firefox, and Opera do not: http://stackoverflow.com/a/11190012

But yeah, nothing more than anecdotes on how likely this is to be a real problem.

**Comment by nickmalcolm** [comment]
Nice one @jricher!

**Comment by tbroyer** [comment]
I'm coming late but shouldn't this have used [RFC 8265](https://datatracker.ietf.org/doc/html/rfc8265)? ([RFC 7613](https://datatracker.ietf.org/doc/html/rfc7613) at the time, now superseded)

(using NSSP with NFKC or NFKD is much easier than using PRECIS, but PRECIS also deals with usernames)

Are there any arguments against using PRECIS in an application?

(currently researching how to properly normalize inputs in an application, and torn between NIST's UAX 15 recommendation and PRECIS)
