### ISSUE TITLE
Address Confirmation

### ISSUE THREAD

**Issue by Slevy-TransUnion** [usnistgov/800-63-3#305]
**Organization**: TransUnion

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: 4.5.6; bullet 7

**Comment (Include rationale for comment)**:
Current guidance "A notification of proofing SHALL be sent to **different** address of record than the destination of the enrollment code. The address of record MAY include the postal address obtained from validated identity evidence. For example, if the CSP sends an enrollment code to a mobile phone of record, a notification of proofing will be sent to the postal address in records or obtained from validated evidence, like a drivers license."

If a notification is required, and it is to go to an address that is different than previously used for an enrollment code, it would seem that sometimes this rule can not be followed. For example, if an enrollment code is forwarded to a consumer's home address to complete the proofing process, and they do not have a different address to then send a notification of proofing, then the guidance would appear to be impossible to follow.  Perhaps I am missing something.

**Suggested Change**:
Remove the SHALL requirement for notification. This is an expense and industry can deliver assurance levels high enough that it adds nothing to security. If it must stay, then modify guidance to allow for eventualities that include the real possibility that a consumer may not have a cell phone or may not choose to allow an enrollment code to be transmitted via SMS.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
If enrollment code is sent to postal address, we will not require notification to a second address.  If not, we feel the notification is an important feature.  @Slevy-TransUnion what are the metrics in your dataset of individuals that have a phone of record but not a postal of record?

In addition, we allow the address displayed on validated and verified evidence to be used for this notification, which mitigates the lack of availability in records.
