### ISSUE TITLE
High level context for Assurance Level tables

### ISSUE THREAD

**Issue by sshorter** [usnistgov/800-63-3#307]
**Organization**:  Scott Shorter

**Type**: Individual

**Document (63-3, 63A, 63B, or 63C)**: 63-3

**Reference (Include section and paragraph number)**: Section 2

**Comment (Include rationale for comment)**:  The documents would benefit from a high level overview of the assurance level tables.  63A, 63B and 63C each has pairs of tables that show first the mapping of "strict adherence to OMB M-04-04" and then another table that shows an "expanded set of levels that are allowed".  Discussion with Justin about issue 279 revealed that the secondary table is intended to reflect "what NIST believes the appropriate future guidance should be, regardless of the content of MB04-04."

**Suggested Change**:  Provide some context about the relationships between this document and M-04-04, and how the assurance level tables are to be used.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
This document remains pinned to M-04-04.  However, with the addition of [EO 13681](https://www.whitehouse.gov/the-press-office/2014/10/17/executive-order-improving-security-consumer-financial-transactions), personal data, even self-asserted, made available online requires MFA.  Therefore, it is critical that MFA be applied where appropriate, and that the required proofing is commensurate with the service being delivered. In some cases this will be robust proofing (IAL2 or 3) and in others, none (IAL 1). 

More language, including a process by which agencies can identify the most appropriate IAL, AAL, and FAL will be provided NLT the [Public Draft](https://github.com/usnistgov/800-63-3/milestone/5).
