### ISSUE TITLE
Definition of 'real identity'

### ISSUE THREAD

**Issue by lorenz-mueller** [usnistgov/800-63-3#321]
**Organization**:

**Type**:

**Document (63-3, 63A, 63B, or 63C)**:

**Reference (Include section and paragraph number)**:

**Comment (Include rationale for comment)**:

In the definitions I miss a definition of the term 'real identity' which is the basis of of IAL; it may sound trivial but it is not as the only context that my be the basis of a real identity is state established identity at the time of birth. Is it this identity which is meant by real identity?

**Suggested Change**:

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
This issue is referring to the definition of Identity Assurance Level in 63-3 and 63B. The term "real identity" is not used elsewhere.

**Comment by lorenz-mueller** [comment]
Dear Jim

I agree that the term is only ussed once, but the issue concerns the whole IAL assurance level. 

I work for the Swiss government (fedpol) to establish an eID in Switzerland and we face the problem that for non native persons very often it is not clear what their real name, birthday and even origin is. We are obliged to define a process or a restriction about the determination of what the real identity is. For the moment we say that the real identity of a person is by definition the identity defined by the attributes registered  by the Swiss government. This is certainly a perfect definition for all native citizens, but it could lead to a situation where one person has different real identities in different states. We would be interested to know what kind of solution to this problem is proposed by the NIST.

Thanks for your comment.

Best regards

Lorenz Müller

PS: For direct contact reply to  mailto:lorenz.mueller@fedpol.admin.ch lorenz.mueller@fedpol.admin.ch

(We can not use github directly)

---

Dr. Lorenz Müller

Swiss Federal Police - fedpol

Fachbereich Weiterentwicklung Ausweise

Nussbaumstrasser 21

3000 Bern

M: +41 79 341 0326

E: lorenz.mueller@fedpol.admin.ch mailto:lorenz.mueller@fedpol.admin.ch 

---

Von: Jim Fenton [mailto:notifications@github.com] 
Gesendet: Donnerstag, 1. September 2016 01:05
An: usnistgov/800-63-3 800-63-3@noreply.github.com
Cc: lorenz-mueller lorenz.mueller@bluewin.ch; Author author@noreply.github.com
Betreff: Re: [usnistgov/800-63-3] In the definitions I miss a definition of the term 'real identity' which is the basis of of IAL; it may sound trivial but it is not as the only context that my be the basis of a real identity is state established identity at the t

This issue is referring to the definition of Identity Assurance Level in 63-3 and 63B. The term "real identity" is not used elsewhere.

**Comment by JimClendonDIANZ** [comment]
In New Zealand we use the term 'AnchorName' which is the name assigned at birth associated with the births register for those born in NZ.  For those not born in New Zealand the 'AnchorName' is the name declared / used when they passed through immigration into the country.

**Comment by MartinFSmith** [comment]
Jim -- Please have a look at the suggested definition for IAL near the bottom of this Issue: Reconsider definition and use of the term "Claimed Identity" #385

I, too was uncomfortable with the use of "real identity" and tried to avoid that ambiguous concept by focusing on the accuracy of whatever personal attributes the CSP's registration policy uses.

**Comment by paul-grassi** [comment]
Use definition for ES in -A.

**Comment by jricher** [comment]
From summary:

> Identity Assurance Level (IAL) refers to the robustness of the identity proofing process and the binding between an authenticator and a specific individual.
