### ISSUE TITLE
Verifiers should not remove all space characters prior to verification

### ISSUE THREAD

**Issue by agreinhold** [usnistgov/800-63-3#322]
**Organization**:2

**Type**:Researcher

**Document (63-3, 63A, 63B, or 63C)**:63B

**Reference (Include section and paragraph number)**:5.1.1.1

**Comment (Include rationale for comment)**:
Draft NIST 800-63B Section 5.1.1.1 currently provides “Verifiers MAY remove space characters prior to verification.” I strongly disagree with this recommendation. I am the developer of Diceware™, (http://diceware.com) a method for generating random pass phrases that are strong, yet relatively easy to remember. Diceware has been available for 20 years and has been translated into 17 languages. I have had many interactions with Diceware users and my comments are based in part on that experience. 

Removing spaces before hashing can materially weaken reasonable pass phrases chosen by users. The extent of weakening depends on the search mode chosen by an attacker. Say a user has a three word passphrase, a reasonable choice for a login password of moderate strength, e.g. “man bravo pit”. If that passphrase appears in a dictionary of previous passwords (unlikely), then sophisticated attack software might try it with and without spaces, so removing spaces would only reduce attack complexity by a factor of 2, i.e. one bit of entropy. However if the attacker employs a search over all character strings, removing spaces would reduce the length of this password from 13 characters to 11 characters. Assuming this attacker is searching only Latin alphabet characters, eliminating spaces would reduce the entropy by 9.5 bits or a work factor of 729. If a larger alphabet is being searched, the work factor reduction in favor of the attacker will be greater.

Another potential problem with space elimination would be someone randomly selecting a passphrase from a word list such as Diceware. An attacker knowing this might attempt to try all combinations of words from the list up to a certain word count. It can happen that two consecutive words will form a third word in the word list, for example “to” and “day” form “today”. If spaces are removed, a four word random passphrase could be effectively turned into a three word passphrase, which would succumb to attack far sooner that a typical four word passphrase. If the Diceware word list were employed, that would be a reduction of 12.9 bits of entropy or a factor of 7,776. Retaining spaces between words (assuming the users included them) eliminates the risk of a generating a weak random passphrase in such cases.

I do not think there is a human factors problem in leaving spaces in. It is natural for users to type spaces between words in a passphrase. And if the user exercises the suggested option to fully display, spaces, or their lack, will be readily apparent to the user. There may be a case for converting two or more space characters to a single space character, but even these situations can be dealt with the display option, perhaps by using a monospace font or employing special glyphs to represent spaces. 

I did not find any mention of eliminating non-printing characters or converting white-space characters, such as tab, to single spaces. I think that practice should at least be permitted, if not mandated.   

**Suggested Change**:
Verifiers SHALL NOT remove all space characters prior to verification.
Verifiers MAY replace multiple, consecutive space characters and white space characters with a single space character prior to verification.
Verifiers MAY remove non-printing characters (except for the space character) prior to verification.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
The draft currently says that the verifier MAY remove spaces. To the extent that spaces are used in longer memorized secrets (more than 8 characters not including the spaces), the secrets will have sufficient complexity to meet the requirements of this guideline with the guideline.

However, we will also offer the alternative of only removing multiple consecutive spaces, and also make it clear that the length minimums apply after any such spaces have been removed.

We are unaware of any user experience benefit from accommodating non-printing characters other than space. The definition of non-printing may even be ambiguous when considering Unicode characters. Accordingly, no special treatment will be accorded to characters other than space.
