### ISSUE TITLE
Allow passwords to be at least 64 characters in length, but note this is for authentication

### ISSUE THREAD

**Issue by agreinhold** [usnistgov/800-63-3#323]
**Organization**:2

**Type**:Researcher

**Document (63-3, 63A, 63B, or 63C)**:63B

**Reference (Include section and paragraph number)**:5.1.1.1

**Comment (Include rationale for comment)**:
Draft Section 5.1.1.1 currently provides “Verifiers SHALL permit user-chosen memorized secrets to be at least 64 characters in length.” I strongly agree. 

The average length of a word in the English Diceware word list is 4.3 characters, with a maximum of 6 characters.(http://diceware.com) and the Diceware page encourages users to type a space between words in their passphrase, which most would do anyway. A full 80-bit strength, as recommended by NIST, requires 7 words randomly chosen from a Diceware-style list, So an 80-bit English Diceware passphrase could be 49 characters long. Words in Diceware word lists in other languages are sometimes longer, and the Electronic Frontier Foundation (EFF) recently released its own word list with an average word length of 7 characters and a maximum of 9.(https://www.eff.org/deeplinks/2016/07/new-wordlists-random-passphrases).  An 80-bit strength passphrase taken from the EFF list could contain up to up to 69 characters if spaces between words are included, though the average EFF 7-word passphrases is 56 characters and vast majority would fit in 64 characters.  

I understand that there has been some criticism of the 64 character limit as conflicting with the recommendation “the verifier SHOULD offer an option to display the secret (rather than a series of dots or asterisks, typically) as it is typed” (which I also support). I believe both requirement can co-exist, even on mobile devices. For example, a text box with two 32-character lines could be used, if necessary, when a password longer that 32 characters is entered. Also, it was mentioned in the presentation at the recent Passwords 16 conference in Las Vegas that were was concern that allowing very long passwords could allow a denial of service attack. I would point out  excess characters beyond a certain length can be hashed and the hash string appended to the early characters without significant loss of security or performance.

While SP 800-63B only deals with passwords for authentication, developers might adopt its guidance for allowable length for password entry in applications where passwords are used to generate cryptographic keys, such as for disk encryption or password managers. In those applications 64 characters would not be sufficient. For example with some word lists a 10 word Diceware passphrase, needed to achieve 128-bit security, could exceed 63 characters. A ten-word, 128-bit passphrase from the EFF word list would most likely exceed the 64 character limit. If 256-bit strength encryption is needed, say for quantum hardness, passphrase of 20 words are needed. Some caution that other uses besides simple authentication may require permitting a longer password should be included in the standard. 

**Suggested Change**:
Retain existing “Verifiers SHALL permit user-chosen memorized secrets to be at least 64 characters in length.

Add: “Note: This recommendation applies to authentication systems. Other applications, such as disk encryption, where the password is used to form a cryptographic key may need to allow longer passwords that match the entropy requirements of the cryptographic methods used.” 

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
The text has changed to change the requirement from a SHALL to a SHOULD. This was done to accommodate the many legacy authentication systems used by the Federal government that would otherwise become non-compliant, while strongly encouraging new deployments to accommodate 64 characters or more.

The requirements for memorized secrets are in no way sufficient to support the derivation of keys of any particular key length; we have backed off from attempts at estimating entropy for any user-generated secret in part to emphasize this. The title of the document, _Digital Authentication Guideline_, should be sufficient to make this point without further caveats.
