### ISSUE TITLE
Divergence with PCI DSS

### ISSUE THREAD

**Issue by milopalmer** [usnistgov/800-63-3#325]
**Organization: 2**

**Type: Enterprise Risk Manager**

**Document: 63B**

**Reference: 5.1.2 Memorized Secret Verifiers**

> Verifiers SHOULD NOT impose other composition rules (mixtures of different character types, for example) on memorized secrets. Verifiers SHOULD NOT require memorized secrets to be changed arbitrarily (e.g., periodically) unless there is evidence of compromise of the authenticator or a subscriber requests a change.

**PCI DSS v3.2 8.2**

> 3) Passwords/passphrases must meet the following:
> . Require a minimum length of at least seven characters.
> . Contain both numeric and alphabetic characters.
> Alternatively, the passwords/ passphrases must have complexity and strength at least equivalent to the parameters specified above.
> 
> 4) Change user passwords/passphrases at least once every 90 days.

On composition rules, I suppose it's defensible to argue that longer strings are as or more secure than faux-complicated short strings, but the reset guidance diverge between standards.

**Suggested Change**:

Lobby the PCI SSC to update the DSS controls to allow for broader risk based decisioning in the protection of payment infrastructure. Consider progressive requirements based on the systems use profile.

---

**Comment by jimfenton** [comment]
SP 800-63-3 is written for use by Federal government agencies, although other organizations adopt all or part of the guidelines. It is not within the scope of this effort to attempt to lobby other organizations who may be engaging in these uses.
