### ISSUE TITLE
definition: Authentication Protocol or Authentication Flow? 

### ISSUE THREAD

**Issue by wangxjnj** [usnistgov/800-63-3#326]
**Organization**:

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 3. Definitions and Abbreviations

**Comment (Include rationale for comment)**:
 the authentication protocol definition is quite different from the wiki site one: https://en.wikipedia.org/wiki/Authentication_protocol

Human(claimant) should be part of the protocol or not?

**Suggested Change**:
##  Claimant should not be part of the protocol. The protocol should define just how a factor been verified once submitted by a claimant. I would suggest changing the "Authentication Protocol" to "Authentication Flow".  

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
Wikipedia is not considered to be an authoritative source.

This definition is largely unchanged from SP 800-63-2, and we see no compelling reason to create confusion by changing this term.
