### ISSUE TITLE
 Two different authentication factors

### ISSUE THREAD

**Issue by MassimoTornatore** [usnistgov/800-63-3#332]
**Organization**:3

**Type**:

**Document (63-3, 63A, 63B, or 63C)**:63B

**Reference (Include section and paragraph number)**:4.2. Authenticator Assurance Level 2

**Comment (Include rationale for comment)**:We can combine two factors in two ways - One is that both have to be passed and the other is that it suffices if one of the two is passed. It seems that many people are unconscious of these two different methods. It should be expressly mentioned that both methods should be accepted.
## **Suggested Change**:At least two different authentication factors are required.  There are two methods of requiring multiple factors.  One is that all have to be passed and the other is that it suffices if one of them is passed.  Both methods shall be accepted.

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by tarbrix** [comment]
If I understand you correctly, I do not support this suggestion.  Passing one of two checks  does not give the same level of confidence as passing two-of-two checks (true multi-factor).

**Comment by MassimoTornatore** [comment]
I agree.  Then NIST could add a footnote that the two methods have their own merits and demerits - better safety with lower convenience vs better convenience with lower security.

**Comment by paul-grassi** [comment]
At AAL2 and above, we require 2 factors and that both SHALL pass.

**Comment by MassimoTornatore** [comment]
Then it could be explicitly mentioned in 4.2 for the sake of clarity.
