### ISSUE TITLE
Favoring not storing the user's password

### ISSUE THREAD

**Issue by maherbo** [usnistgov/800-63-3#333]
**Organization**:  Individual

**Type**: 3

**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: Appendix A: Strength of Memorized Secrets

**Comment (Include rationale for comment)**:

You should favor NOT saving the actual user's password.  [This repository](url https://github.com/maherbo/easy-random-password-login) shows a method on how to do it. 

This would deter any offline cracking attack.  It would also counter many attacks of the following type: online guessing, phishing, social engineering, eavesdropping and duplication.

**Suggested Change**:

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
Appdenix A is non-normative. The normative requirement is found in the last paragraph of Section 5.1.1.2:

> Verifiers SHALL store memorized secrets in a form that is resistant to offline attacks. Secrets SHALL be hashed with a salt value using an approved hash function such as PBKDF2 as described in [SP800-132]. The salt value SHALL be a 32 bit (or longer) random value generated by an approved random number generator and is stored along with the hash result. At least 10,000 iterations of the hash function SHOULD be performed. A keyed hash function (e.g., HMAC), with the key stored separately from the hashed authenticators (e.g., in a hardware security module) SHOULD be used to further resist dictionary attacks against the stored hashed authenticators.

As you can see, the document already requires that actual user memorized secrets (passwords) SHALL NOT be saved.

**Comment by maherbo** [comment]
Sorry, that is not what I meant.

This requirement DOES save the actual user's password, only it is in a hashed form.  Hackers are now using patterns to GUESS passwords, a thing that every human create to remember passwords (sometimes unconsciously).  Human-generated passwords will never create enough randomness to withstand dictionary attacks.  So only a pure random, high entropy, password should be given to the user, stored on his machine, encrypted with HIS human-generated password (HGP), easy to remember.  This has the advantage, that his HGP is not stored in the database (hashed or otherwise), only the random and complex one given to him, such that no hacker would be interested in it even if they could find it.  The random password is unique to the user AND the database.  Check this repository out to better understand what I mean: https://github.com/maherbo/easy-random-password-login

**Comment by jimfenton** [comment]
What you are describing is a multi-factor software cryptographic authenticator, described in section 5.1.7. The terminology we are using for something that is random and high entropy and not expected to be memorized by the user is that it is a _key_ rather than a password.

**Comment by maherbo** [comment]
Thank you.  Very helpful.  First time I've seen this method described and recommended by someone. (Though, «_multi-factor software cryptographic authenticator_» are not words I was thinking about when searching on the subject!)
