### ISSUE TITLE
Future-proofing key strength requirements

### ISSUE THREAD

**Issue by pjez** [usnistgov/800-63-3#34]
**Organization**: 3

**Type**:

**Reference (Include section and paragraph number)**:  
-C, 5.2.2 Shared Secret ("A 128-bit random symmetric key or equivalent strength asymmetric key ...")
-B, 5.1.4.1. Single Factor OTP Authenticators ("The secret key SHALL be a 128-bit or longer AES...")
-B, 5.1.6.1 Single Factor Cryptographic Device Authenticators ("The secret key SHALL be a 128-bit or longer...")
Others...

**Comment (Include rationale for comment)**:  Consider qualifying all such statements of key strength with a date after which the strength must be increased.  NIST is better positioned than most agencies that will use this document to predict when a particular strength key is likely to no longer be strong enough due to advances in technology.  The ability of NIST to update this document at a particular time in the future will only be partially within NISTs control -- subject to budget cuts, politics, new national priorities assigned to NIST, etc.  Writing in an automatic increase may help protect against use of keys that have become weak.  The timeline will also give agencies using the guidance helpful information for deciding whether to deploy new systems with stronger keys from the beginning if they expect the system life to extend beyond the date advised by NIST.  Even if the strength increase date is 60 years out, such information is still helpful to readers as it will help them avoid investing effort to figure that out for themselves.

**Suggested Change**:  Consider qualifying all such statements of key strength with a date after which the strength must be increased.  

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
The specification is already too specific with respect to key lengths. Rather than specifying 128-bit AES, for example, it needs instead to refer to Special Publication 800-131A (currently at revision 1) and SP 800-57 for allowable algorithms and key lengths. Rather than try to predict and separately manage key sizes for authentication, referencing approved cryptography will cause these requirements to be revised when this guidance changes overall.

**Comment by jimfenton** [comment]
Fixed by #62
