### ISSUE TITLE
Human cognitive short-comings can be side-stepped

### ISSUE THREAD

**Issue by p13man** [usnistgov/800-63-3#342]
**Organization**: 3

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Appendix A.4 etc

**Comment (Include rationale for comment)**:

"Therefore, no additional complexity requirements are imposed"

The point that we humans are not wired up to remember lots of strong passwords is well made. But it misses the point that passwords don't need to be committed to memory (or recorded) in order to be used. We have, for a great while, been using patterns as the basis of our passwords. 1q2w3e4r is an example of such a password, which is generated by a simple keyboard pattern. This password is in the Top 50 most used passwords for most (hacked) websites i.e. popular! We, as people, are much more comfortable remembering patterns than remembering strong passwords. We can utilize this cognitive trait to help folk generate strong passwords that they don't need to remember. Taking this approach, complexity requirements become moot. By basing passwords on a memorable pattern, anyone can generate and retrieve an unlimited number of strong passwords without relying on memory. We just need to remove the current dependence on the keyboard as the basis for the translation from pattern -> password. See references below.

Refs: 
[the use of patterns in password composition](https://public.tableau.com/profile/simon.gibbard#!/vizhome/Ananalysisoftheextenttowhichweusepatternstogeneratememorablepasswords/Welovepatternswhenitcomestocreatingpasswords)

[the use of patterns to generate strong, unique passwords](https://www.youtube.com/watch?v=Ic-3d_B32sI)

**Suggested Change**:
Adjust the assumption that passwords must be committed to memory in order that they can be used. Quite a lot flows from this assumption.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by burr44** [comment]
There are many tricks that can help people to remember and use more and longer and better passwords, and I expect that everybody who does business  extensively online and is security conscious has some set that he uses.  Still, the password manager I use has 206 separate entries.  Maybe half I will never use again (not always easy , however, to predict what might come back to life), and of the others maybe half aren't anything very important.  Still, my insurance company wants me to have a password, a PIN and a phone password.  I have accounts with 3 banks, plus several other credit card accounts.  I have 2 login passwords for the 3 computers I use routinely and one for my cellphone.  I have about 4 e-mails I us routinely,  each with a password and some old accounts I check occasionally.  I'm getting some medical treatments at a hospital, that wants me to have 2 different accounts, each with passwords, one for billing and one for medical records.  I have accounts with a couple of medical labs, to get test results & schedule appointments.  Frankly, I'm not going to trust my identity and history of where I go to Facebook or Google, I don't trust them and they don't need to know what I'm doing, so federation won't do squat for me.  I have accounts with three different transit authorities and several airlines.   I use tricks for a few important passwords I use routinely, but there's no way I can keep 200 odd passwords straight without writing them down, with my password organizer.  

Based on my own experience, I don't think we can do much useful in 800-63 with tricks for memorizing better passwords.

**Comment by jimfenton** [comment]
The term _memorized secret_ does not require that all such secrets be memorized, but rather that it be a secret that a user is capable of memorizing. We are very well aware of the use of password management products, and neither attempt to prohibit them (which would probably be unsuccessful anyway) nor do we endorse their use. We are also personally aware of the near-impossibility of committing large numbers of secure memorized secrets to memory.

The product you refer to is a password manager, in the sense that it has a master secret (represented by a pattern in this particular case) and generates a number of individual secrets from that master. We have no comment on its security but it would similarly be neither prohibited nor endorsed.
