### ISSUE TITLE
SP 800 63A Comments and some suggested changes

### ISSUE THREAD

**Issue by trbouma** [usnistgov/800-63-3#343]
Treasury Board Secretariat

Government of Canada

Organization: 1 = Federal, 

SP 800 63A Digital Authentication Guideline Comments based on differences between Canadian and US approach. 

Some high level comments. I believe they are due to some differences in how we have developed our models. It may be worth a follow-up call to discuss in detail.

Section: Executive Summary 

Identity assurance level definitions (IAL1-IAL3)

The IAL  definitions are defined by the methods by which they are achieved – not how they can be relied on. While the definitions might be straightforward to a technical practitioner, there is not a reference on how this definition is meaningful in relation mapping back to a business requirement.

The IAL definition combines two related but very distinct processes: 
1) proving who you are and, and 2) the binding process.  

In the GC, we are breaking these processes into two separate definitions:

1) IAL is proving who you are , and,
2) Identity Enrolment (the binding process) is binding this proven identity to a credential (or authenticator)

The rationale for this is that identity proofing and enrolment should be regarded as separate functions that can be carried out be completely different organizations.  There seems to be an implicit assumption that these functions are combined within a larger process carried out by the same organization. This may not be the case.

**Suggested Change for IAL definitions**:
Consideration should be given to scoping back the definition of IAL to Identity Proofing Only.

Section 4.7  Enrollment Section
The discussion can be broadened beyond the enrolment code/address of record use case. There are use cases where the address may not be required or desired.

Section 4.1 Process Flow 
Figure 4-1 The Identity Proofing Process
Not sure if I agree with the organization of this process flow. I think the pieces are there, but need to be re-arranged.

Instead, It may be something like this:
1.  Identity Proofing Establishing an Identity Assurance Level
   a) Collect Identity Information
   b ) Resolution
   c) Validation
   d) Verification, or 
   Leverage Antecedent Proofing Events
2. Enrolment (or Binding as we call it)
   a) Create Credential for Client (or acquire existing one, if client already has one)
   b) Collect and validate additional information as required (e.g. address, email, etc.)
   c) Binding Identity/Personal Information to existing(or new) credential
   Issue Enrolment Code
   Validate Enrolment Code
   Bind identity (and other information) to credential.

**Comment by wardmundy** [comment]
If you only have one mobile phone and you always have it with you, Google Authenticator or something like it works great. Otherwise, it's worthless. SMS messages are much easier to deal with and one would hope you could educate users not to respond to anonymous text messages seeking ANYTHING! Other than that, SMS use for two-factor authentication is easy and works great.

**Comment by trbouma** [comment]
In our guidance, we call these 'linkage methods' - the idea is the same as 'binding' which is part of an enrolment process.

So, 'linkage methods' might include: mobile phone with Google Authenticator, SMS. There are also some more traditional linkage methods, such as sending lettermail with an access code to an address on record. Our tax agency still use this method.

For consideration, I've cut-and-pasted some text from Section 3.6.2 Table from our [guideline ](http://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=30678) that might be useful as more generalized guidance

_The efficacy of linkage methods is dependent on factors such as the service delivery context, the threat environment, and the evidence that the individual is willing or capable of providing. 

Care should be taken to select and develop linkage methods that do not place undue burden on the individual or that can introduce unintentional vulnerabilities or risk (e.g., using sensitive personal information that may have an adverse effect if compromised). 

Linkage methods may be enhanced by implementing a combination of techniques described in [Table 6](http://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=30678) (instead of only one technique per method). For example, a knowledge-based confirmation method may combine static and dynamic knowledge-based confirmation methods.

Similarly, for biological or behavioural characteristic confirmation, the method may include a combination of techniques. For example, biological or behavioural characteristic confirmation may include a combination of facial comparison and fingerprint comparison._

**Comment by paul-grassi** [comment]
Closing since we talked offline with our good friends from Canada.  Thanks @trbouma!
