### ISSUE TITLE
6 random digits too weak

### ISSUE THREAD

**Issue by jeffshannon** [usnistgov/800-63-3#345]
**Organization**: 2

**Type**: comment on 6 random digits proposed requirement

**Document (63-3, 63A, 63B, or 63C)**: Powerpoint deck "Toward Better Password
Requirements"

**Reference (Include section and paragraph number)**:
Page 10

**Comment (Include rationale for comment)**:
This line in the powerpoint deck represents a weakness.
"NEW: SHALL be at least 8 characters or 6 random digits"

6 random digits represents a password which is trivial to crack mathematically. We should not encourage the use of 6 character passwords in any form.

**Suggested Change**:

In the specification, it should just be "SHALL be at least 8 characters"

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by burr44** [comment]
I can only find 1 occurrence of  "6 random digits" in 63A section 4.8.  This is for an enrollment code used to confirm an address.  Six random digits in the 10 minutes allowed for confirmation of electronic delivery to the address being confirmed, seems strong enough.  This isn't a password valid for months or years.  I have no idea what "crack mathematically" means here, but an in-band guessing attack against a 6 random digit enrollment code in a ten minute time frame isn't too troubling.  Perhaps a stronger code might be used for postal delivery with 7 or 21-day limits.  

If I have an objection to the text: "An enrollment code consisting of at least 6 random digits SHALL be included in address confirmation." it is that a strictly constructed English reading of the sentence would forbid an enrollment code containing letters and symbols as well as numbers, which would do at least as well.  Perhaps it might be better to say something like "an enrollment code randomly selected from a set of at least one million different codes."

**Comment by jimfenton** [comment]
The reference here is to -63B section 5.1.1.1:

> Memorized secrets SHALL be at least 8 characters in length if chosen by the subscriber; memorized secrets chosen randomly by the CSP or verifier SHALL be at least 6 characters in length and MAY be entirely numeric.

This is the same as required in 800-63-2 at LoA 2 (see Table 6, p. 51). The rationale here is that throttling (section 5.2.2) makes this sufficient to protect against online attacks. This is definitely not sufficient to mitigate an offline guessing attack, but neither is 8 digits or 8 characters. To be fully safe against offline attacks, we're now talking about a key: 112 bits or about 34 decimal digits.

As in other places in this document, the goal is to set modest expectations for the security of memorized secrets alone and move to 2-factor authentication for any applications with any sensitivity, as required by [Executive Order 13681](https://www.whitehouse.gov/the-press-office/2014/10/17/executive-order-improving-security-consumer-financial-transactions), and to strengthen the infrastructure against offline attacks with keyed hashes and multiple rounds of hashing.

@burr44: Good point on the construction of enrollment codes. Can you create an issue for that one so it doesn't get lost?

**Comment by jeffshannon** [comment]
I see now and appreciate the clarification. In the powerpoint slide I am referencing it lacks the detail necessary to come to the conclusion I did and with your help I now understand. I have dug more into the documents thanks to your referencing section 5.1.1.1.

I won't be able to keep up with your familiarity of the document or processes you are creating but I'll do my best to pickup the lingo and appreciate the opportunity to participate. I read 5.1.1.1 and still have some worry about propogating 6 digit long term passphrases as acceptable into industry when they are likely not the best idea. Best idea, to me, would be to simply require 8 as a minimum, that way we have consistent minimum. Also, VERIFIERS could distribute in 2 groups of 4 which should maintain memorizable nature.

What I worry about with less than 8 character password devices is offline database attacks. Obviously, a VERIFIER set password of 8 characters has a lot of things going for it, namely that it is far more random than anything a user could set and also would be singular in nature. Therefore, even if an auth database were compromised and a 6 digit password were discovered, the scope of attack should be minimal.

I read Appendix A and think it could be expanded on to clarify why 6 digit VERIFIER set pins are ok.

Either that, or just increase it to 8 character VERIFIER set pins, to match the user standard, and dictate 2 groups of 4 or whatever as a way to present them as memorizable?

thanks for the opportunity. I am participating out of my league but it's fun!

**Comment by jimfenton** [comment]
SP 800-63-2 permitted the use of _randomly generated_ 6 digit PINs. Since this is to defend against online guessing attacks and not offline attacks, and the same throttling applies, there isn't a particular reason to increase the requirement, possibly rendering some SP 800-63-2 compliant systems non-compliant.

However, I have added a short section to Appendix A describing the rationale for shorter requirements when the secrets are randomly chosen and uniformly distributed. Thanks for the suggestion.
