### ISSUE TITLE
utilize an authenticated protected channel when collecting the OTP - second thought

### ISSUE THREAD

**Issue by wangxjnj** [usnistgov/800-63-3#350]
**Organization**:

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 5.1.4 and 5.1.5 

**Comment (Include rationale for comment)**:
 on #216 I suggested changing to " authenticated protected channel". On second thought it is not adding much values. OTP by definition once used no longer valid any more, and replay attack will not work. If the attacker is able to capture it and also use it ahead of the real request  possible in theory but in reality  almost impossible. 
**Suggested Change**:
##  change from SHALL to SHOULD. 

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
The authenticated protected channel is required in order to make sure there is not a man-in-the-middle attack between the claimant and verifier. Otherwise an attacker might have the opportunity to intercept the OTP and use it for a different authentication transaction. This is different from the replay attack you describe.

**Comment by wangxjnj** [comment]
Authenticated protected channel is not going to prevent MitM attack since the attacker is in the middle and impersonating as the verifier to the claimant, and as the claimant to the verified.  If a channel is required the attacker will bring a channel up. Both claimant and verifier believe they are directly communicating with each other.

**Comment by jimfenton** [comment]
That's exactly the point of having an _authenticated_ protected channel. If there is a MitM, the TLS connection made by the claimant will not present a valid certificate from the verifier. Unless, of course, the attacker has the ability to create a certificate signed by a certificate authority trusted by the claimant.
