### ISSUE TITLE
Remote identity proofing should incorporate strong fraud mitigation measures

### ISSUE THREAD

**Issue by cmccolgan** [usnistgov/800-63-3#352]
**Organization**: TeleSign Corporation

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: 4.2 p11

**Comment (Include rationale for comment)**:
In 800-63a standards around remote identity assurance are discussed. Given the threats that are considered in 63b and decisions made based on those threats it is surprising that the following statement is made in 4.2 point 11:

> _The CSP MAY obtain additional confidence in remote identity proofing using fraud mitigation measures, for example inspecting geolocation,_

Given the levels of threats around identity proofing, and for that matter authentication, this should be a “SHALL” and not a “MAY”. All major consumer providers today use fraud mitigation measures in both identity proofing and authentication and NIST 800-63 should also set that as a standard.

**Suggested Change**:In 4.2 point 11 change MAY to SHALL

**Comment by paul-grassi** [comment]
We shall make this a SHOULD
