### ISSUE TITLE
The online password guessing threat is largely underestimated in 63B

### ISSUE THREAD

**Issue by nkyle01** [usnistgov/800-63-3#354]
**Organization**: 2

**Type**:  

**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**:  
5.2.2. Rate Limiting (Throttling)
A.2 Length

**Comment (Include rationale for comment)**:

Currently, the major threat for passwords are not offline guessing, but online guessing. Previously, sites tend to place the responsibility of protecting web accounts on users, and let users choose complex and long passwords. Actually, sites shall be responsible for protecting user account by using slow, iterated hash like PBKDF2 and do not leak users’ password file. This is why I think the majority of the NIST 800-63-3 advices are wise. Users only need to select passwords that can withstand online guessing. 

Unfortunately, according to an ACM CCS’16 research (http://bit.ly/2ck516a), normal users’ passwords are far from secure against targeted online guessing attacks (e.g.,  100 guesses as allowed by 63B).  More specifically, according to the last paragraph of Section 5.2 in this ACM CCS'16 paper: when sister passwords are available, an online attacker can reach a success rate of 77% against normal users with 100 guesses; Even when sister passwords are unavailable, an online attacker can still achieve about 20% success rates against normal users with just 100 guesses, 25% with 1000 guesses, and 50% with 1000,000 guesses.

In Section 5.2.2 of 63B, it reads that "Unless otherwise specified in the description of a given authenticator, the verifier SHALL effectively limit online attackers to 100 consecutive failed attempts on a single account in any 30 day period."

In Appendix A.2 of 63B, it reads that “Online attacks where the attacker attempts to log in by guessing the password can be **readily** addressed by throttling the rate of login attempts permitted.” 

**Suggested Change**:

I think it would be better to place more emphasis (and propose more countermeasures) on resisting online guessing attacks, and necessary to remove the word "readily" from Appendix A.2 of 63B. 

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
The wording in the appendix is being changed as you suggested. Please also consider the recommendations in SP 800-63B section 5.2.2. While these are primarily focused on preventing subscribers from being inadvertently locked out from their accounts, they also provide some further protection against sibling passwords from other accounts.

If you have further suggestions on avoiding these attacks that you think should be included, please suggest them.

Thank you for the link to your forthcoming paper. Please note that the wording it cites at the end of section 5.2 will not be in the document once the change is merged.
