### ISSUE TITLE
Section 4.1 Title Should Change to Federation Trust Models

### ISSUE THREAD

**Issue by jim-thomson** [usnistgov/800-63-3#355]
**Organization**: 3

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63C

**Reference (Include section and paragraph number)**: Section 4.1 Title

**Comment (Include rationale for comment)**: Section 4.1 deals with the trust relationships between identity federation and doesn't cover implementation models (i.e. patterns), for example. Section 6 also shows "federation models", calling them presentation models.

**Suggested Change**: Because Section 4.1 is the first discussion of several ways to look at federated authentication, recommend that "Trust" be added to its title to better convey its scope.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
The problem here is that "trust" is a very loaded term and tends to have contextual meanings beyond the system relationships that we're describing here. Perhaps there's a better but less loaded term.

**Comment by andrewhughes3000** [comment]
The body of Section 4.1 describe a few **Federation On-boarding Strategies** or **Federation On-Boarding Approaches**
They are not about Trust, nor are they Models. They are about the gatekeeper that authorizes additional federation member entities.

**Comment by jim-thomson** [comment]
The title is “Federation Models”, so should not “Models” be removed from the title?

**Comment by jim-thomson** [comment]
The text states, in its entirety:

“This section provides an overview of a few common models of identity federation currently in use. In these models, trust is established between members of the federation in several different ways. Some models mandate that federated parties have a high level of trust. Other models allow for parties with a diversity of trust relationships.”

Adding “trust” to the title summarizes what the text claims is in the section. It doesn’t add any more uncertainty than is in the introductory sentences. Perhaps something like “Trust Between Federation Parties” is clearer, although somewhat clumsier.

Anyway, the reason this struck me in the first place is that I was performing a “Monday-morning” read of the document and the contents of 4.1 were not what I expected from the title. I expected runtime models either describing identity federation vs. attribute federation vs. authorization decision federation (yes, out of scope somewhat), or a more narrow comparison of federation of how an ecosystem of IdPs / Verifiers connect to and trust each other, and how RPs tie in. Instead it was about instantiation.

**Comment by jricher** [comment]
We're going to re-word the section to remove references to "trust" where possible, and keep the current title as we feel that these are models of federation relationships.
