### ISSUE TITLE
Proofing confidence

### ISSUE THREAD

**Issue by dberini** [usnistgov/800-63-3#357]
**Organization**: NextgenID

**Type**: 2 
Industry

**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: 
Section 4.2 General Requirements
Subsection 11, First sentence

**Comment (Include rationale for comment)**:
The as written Subsection 11 limits additional confidence to remote identity proofing only and should be expanded to all identity proofing so that proofing may achieve higher confidence regardless of the type of identity proofing being performed. Even though this subsection is a "MAY" requirement, it is viewed that broadening this strengthens identity proofing and therefore should be considered a benefit to the process regardless of the IAL level being sought. The "May" level of requirement allows this to be impllemetend as an option by a CSP, if so desired.   

**Suggested Change**:
##  11.    The CSP MAY obtain additional confidence in identity proofing using fraud mitigation measures, for example inspecting geolocation, examining the device characteristics of the applicant, evaluating behavioral characteristics, or checking vital statistic repositories such as the Death Master File, so long as any additional mitigations do not substitute for the mandatory requirements contained herein and the CSP SHALL conduct a privacy risk assessment of these mitigation measures.

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
Accepted and duplicate to #352
