### ISSUE TITLE
Virtual in-person proofing - local operator

### ISSUE THREAD

**Issue by dberini** [usnistgov/800-63-3#362]
**Organization**: NextgenID

**Type**: 2 
Industry

Document (63-3, 63A, 63B, or 63C): 63A

Reference (Include section and paragraph number):
Section 5.4.3, Virtual In-Person Proofing Requirements
Sub Number 6

Comment (Include rationale for comment):
This "SHOULD" requirement is in conflict with the definition, value and desired process of Virtual In-Person Proofing. The In-Person Operator requirements are however appropriately provided in the other sections of this document. The In-Person Operator participates over a remote session to this section 5.4.3 requirements.  

**Suggested Change**:
##  Delete sub-number 6 in its entirety.

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
We like the belt and suspenders approach of a CSP potentially selecting to have an attendant onsite.  It's not required.

**Comment by dberini** [comment]
Hi Paul,

I hear what you’re saying on this, especially that it is not required but I believe the same is implied from requirements within the other sections of the publication. I do believe that adding this SHOULD requirement lowers the perceived strength of Virtual in-Person Proofing where no in-person operator is utilized and can confuse CSP’s and auditors as the deployed system will and could be then clouded with lap-overs and exceptions.

As for example, a CSP claims that their system’s proofing is being implemented and performed as Virtual In-Person (VIP) proofing BUT also includes an in-person operator (the SHOULD requirement). Further, the CSP does not meet all of the Virtual In-person proofing requirements. As such, what is the CSP and what is the system? Compliant as virtual in-person proofing? Compliant as partially virtual in-person proofing and In-Person? Compliant as In-Person? To me it adds potential confusion in the overlap as a… hybrid?

So to the above… I believe that with the requirements within the virtual in-person proofing section they should be specific to virtual in-person proofing (read without the SHOULD requirement). You are either performing an “in-Person” proofing or a “Virtual In-Person” Proofing and no in-betweens. You either meet all the requirements specific to the virtual in-person proofing section of the publication or not. In my humble opinion, the SHOULD requirement hurts more than helps.

Hope this is making sense.

**Comment by paul-grassi** [comment]
Fair enough.  SHOULD indicates a preference to do it.  What if we made it a MAY?
