### ISSUE TITLE
Virtual In-Person Proofing - remote visibility

### ISSUE THREAD

**Issue by dberini** [usnistgov/800-63-3#363]
**Organization**: NextgenID

**Type**: 2 
Industry

Document (63-3, 63A, 63B, or 63C): 63A

Reference (Include section and paragraph number):
Section 5.4.3, Virtual In-Person Proofing Requirements
Sub Number 7

**Comment (Include rationale for comment)**:
 Within a Virtual In-Person Proofing, the CSP's remotre operator must be capable of performing this requirement through the use of appropriate hardware components, technical implementation and procedures. As such, all requirements within this document specific to the requirement are applicable regardless of being performed In-Person or Virtual In-Person Proofing.  

**Suggested Change**:
7.  The CSP SHALL have the operator view the biometric source (e.g., fingers or face) for presence of non-natural materials and perform such inspections as part of the proofing process. 

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
Thanks.  These do need to be made parallel.
