### ISSUE TITLE
Virtual In-Person Proofing - operator training

### ISSUE THREAD

**Issue by dberini** [usnistgov/800-63-3#364]
**Organization**: NextgenID

**Type**: 2 
Industry

Document (63-3, 63A, 63B, or 63C): 63A

Reference (Include section and paragraph number):
Section 5.4.3, Virtual In-Person Proofing Requirements
Sub Number 8

**Comment (Include rationale for comment)**:
It is recommended that this requirement be expanded to include the addition of training specific to the performance of a Virtual In-Person Proofing session. This will ensure that the operator has the skills to detect potential fraud AND be adept of all the features provided the operator through the Virtual In-Person Proofing session.  

**Suggested Change**:
8.  The CSP SHALL require operators to have undergone a training program to detect potential fraud and to properly perform a virtual in-process proofing session.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
If you have any more issues to submit, could you make the titles more descriptive? It's going to be hard to keep all of these straight otherwise.
