### ISSUE TITLE
Section 9.1.2 Enrollment and Proofing Session 9th major bullet

### ISSUE THREAD

**Issue by dberini** [usnistgov/800-63-3#367]
**Organization**: NextgenID

**Type**: 2 
Industry

**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**:
Section 9.1.2 Enrollment and Proofing Session
9th major bullet

**Comment (Include rationale for comment)**:
It is recommended that their not be a distinction between In-Person and Virtual In-Person Proofing in this section.  The usability requirements apply equally regardless of the proofing type (In-Person or Virtual In-Person).

Sub-bullet 2 Virtual in person bullet title should be removed.

Sub-bullets 1 and 2 under Virtual in person should remain as written and apply to both In-Person and Virtual in-Person proofing.

Sub-bullets 3 through 6 under Virtual in person should be deleted as they are a word for word replications of In-Person that is stated above this section.

**Suggested Change**:
• Depending on enrollment session type (in-person, virtual in-person, or remote), additional usability considerations apply.
o   In-person and Virtual In-Person

Sub-bullet 2 Virtual in person title - Delete bullet title and

o   Virtual in-person

Remains the same:
 If enrollment sessions are conducted in publicly observable spaces (e.g., a kiosk in a bank or supermarket), users may be concerned that others can view their activity and identity evidence. Care should be taken in the design and placement of the enrollment station to minimize user concern of being observed by others. Users may be reluctant to bring identity evidence to certain public places (bank versus supermarket), as it increases exposure to loss or theft.

 At the start of the enrollment session, users need to be informed that they must not depart during the session, and that all their actions must be visible throughout the session.

Delete the following:
 At the start of the enrollment session, operators should explain their role to users. For example, will operators walk users through the enrollment session step by step, or will they observe silently and only interact with users as needed?

 If users choose to complete a partial enrollment session (due to not having the requisite set of identity evidence), provisions must be made to schedule a follow-up session to complete the enrollment process. The previously identified usability considerations for appointments still apply.

 If biometrics are being collected during the enrollment session, provide users clear instructions on how to complete the collection process. Instructions should be provided just prior to the collection process. Verbal instructions with corrective feedback from a live operator are the most effective. For example, instruct users where the biometric sensor is, when to start, how to interact with the sensor, and when the biometric collection is completed.

 If users receive the authenticator during the enrollment session, operators should demonstrate use of the authenticator. Operators should help users test the authenticator during enrollment sessions to ensure the authenticator works correctly and users understand its operation.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
We were aware of the duplication, yet for now it is done purposefully. We decided to go with this approach since we thought that readers (especially implementers) may be interested in certain implementation (e.g., in-person in this case, or Multi-factor OTP in 63B) and go directly to the relevant bullet point for information. Thus, though it seems to be duplicate, it is important to give readers complete information for the topic they are interested in.
