### ISSUE TITLE
definition: Man-in-the-Middle Attack (MitM) -- inconsistent 

### ISSUE THREAD

**Issue by wangxjnj** [usnistgov/800-63-3#368]
**Organization**:

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**:3. Definitions and Abbreviations

**Comment (Include rationale for comment)**: **Man**-in-the-Middle Attack (MitM)
 "An attack on the authentication protocol run in which the attacker positions **himself or herself** in between the claimant and verifier so that **he** can intercept and alter data traveling between them."

**Suggested Change**:
##  take "**or herself**" out or replace **he** with "**he or she**". 

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
I would suggest we use the singular "they" for non-specific gender pronouns throughout.

**Comment by jimfenton** [comment]
@jricher Normally I would use the singular "they" as you suggest, but in this sentence "them" refers also to the claimant and verifier (not the attacker) and it looks like it would be confusing.

**Comment by jricher** [comment]
If the antecedents are unclear, then it may be a good idea to eschew pronouns.
