### ISSUE TITLE
definition: Authenticator, Possession and control of an authenticator -- Possession required?

### ISSUE THREAD

**Issue by wangxjnj** [usnistgov/800-63-3#369]
**Organization**:

**Type**:

**Document (63-3, 63A, 63B, or 63C)**:63B 

**Reference (Include section and paragraph number)**:3. Definitions and Abbreviations

**Comment (Include rationale for comment)**:
**Possession and control of an authenticator**: The ability to activate and use the authenticator in an authentication protocol.

The above **Possession and control of an authenticator** definition does not say anything about possession. 

 **Authenticator**: Something that the claimant **possesses and controls** (typically a cryptographic module or password) that is used to authenticate the claimant’s identity

Is authentication actually verifying possession by the claimant? If that is the case then we never need to worry about online guessing, replay and MitM attacks. For me authentication is the process that  a verifier makes sure the presented authenticator with an user account matching its expectation (exact  match or good enough match(bio)). Possession is not verified at least not directly. 

possession but not in control:  useless ( such as cannot unlocking an authenticator)
in control but not in possession: could not find a good example.  for me in control implies in possession directly or indirectly. e.g.  I am forced to  unlock my MF OTP using my fingerprint. Now the OTP authenticator is under who's control and possession? I may still hold the device physically but it is no longer under my control.  Possession is not important. Control is!  

**Suggested Change**:
 I would suggest taking the possession requirement out from the "Authenticator" definition, and at the same time take the "Possession and" out from the **Possession and control of an authenticator** but no definition changes:

**Authenticator**: Something that the claimant **controls** (typically a cryptographic module or password) that is used to authenticate the claimant’s identity.

**Control of an authenticator**: The ability to activate and use the authenticator in an authentication protocol.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
We believe that possession and control is a necessary and sufficient definition of the requirement.
