### ISSUE TITLE
Removal of Email and SMS cuts off broader security measures for "Individuals"

### ISSUE THREAD

**Issue by kcsapersona** [usnistgov/800-63-3#370]
**Organization**: 2

**Type**: Comment on AAL-1 and AAL-2 along with removal and depreciation of Email and SMS

**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**:  ABSTRACT, Authenticator Assurance Level 2 – AAL 2

**Comment (Include rationale for comment)**:
In the Abstract, the document states that the document includes recommendations for remote authentication of private individuals  interacting with government IT systems over open networks.

My comment and question revolves around the definition of "Private Individuals". Does this definition include for example, healthcare.gov or any other consumer facing service?

If so, then here is my comment:

By depreciating SMS and eliminating Email, you take away the only two ubiquitous methods of reaching out to a private individual. In so doing, Federal Services must require (For AAL2) these users to install  some additional authentication program or use some other factor method to authenticate. In principle, this is actually fine, but I use this to demonstrate that there is an enormous gap between AAL1 and AAL2 that should be filled.

Here is the primary principle: In customer facing services, if the end user (private individual in this case) is required to install anything outside of any existing behavior, then the service owner is faced with only two options: 1) Force the user to comply, or do not allow access. or 2) Enable some level of advanced protection and make it an Opt-In option for the user.

Let's take GitHub as an example. In your directions to setup git hub accounts, you guys strongly recommended that we turn on 2-factor authentication. And this is clearly important, but it was up to me as a user to opt-in. The point is, that git-hub can only offer an opt-in because the method for adding additional security is a pain and they simply can't require it because too many people would simply go somewhere else if they did. 

The Federal government is essentially in the same boat. If the Federal Government wants to have public services available, you can't make it too difficult for users to access the services.

So now let's talk about services like healthcare.gov or any other service that holds PII and/or Health related information. With the current AAL1 and AAL2 definitions, will the Federal Government really push all these public facing services to AAL2 and require 2-Factor for all access? I doubt it. If you do, your adoption rates to use the services will plummet. People won't access them because they have to do extra stuff (download and app, or install something) and enter additional factors every time they access the service.

But in reality, all these Gov't services should be at AAL2 correct??  There is no security professional that would agree that AAL1 (ID and Password alone) is enough security to protect public/private individual information that contains PII and/or Health related information.

Here is the gap. The document should include some level of recommendation that increases assurance for these types of services because AAL1 is not strong enough and AAL2 is not workable in these cases.

With AAL1, the "Data Breach Free For All" is on the table. Meaning, that if an unauthorized user has the credentials, they can access the service. This is no longer acceptable security for any service that holds PII and/or Health information. If you disagree, I welcome your reasoning. It is vital that Federal Services containing any PII and/or Health related information, that the "Data Breach Free For All" is taken off the table.

If NIST does not provide another Level (let's call it AAL1-R for Risk-Based or AAL1-A for Adaptive-Based) to address this gap, then what is NIST's recommendation for services like Healthcare.gov. Are you going to recommend AAL1 or AAL2? AAL1 is not enough security and if you push Healthcare.gov to AAL2, people will hate it, they won't be able to login, user acceptance will be terrible, it won't work.

**Suggested Change**:

Provide an AAL1-A or AAL-R or (you pic the label) that provides the following recommendation. 

Authenticator Assurance Level 1-A - AAL 1-A provides single factor digital authentication along with a Risk-Based Adaptive Multi-Factor Evaluation (of previously known factors within a given time-frame), providing additional assurance that the same claimant who participated in previous transactions is accessing the protected transaction or data. AAL 1-A allows a wide range of available authentication technologies to be employed and requires both a single authentication factor AND an Adaptive Risk-Based Evaluation to be used. It also permits the use of any of the authentication methods of higher authenticator assurance levels. Successful authentication requires that the claimant prove through a secure authentication protocol that he or she possesses and controls the authenticator and passes the Adaptive Risk-Based Evaluation. Failure to pass the Risk-Based Adaptive Multi-Factor Evaluation, results in a Step-Up challenge that requires the user to further validate their Identity via an additional factor that can be a one-time passcode sent to the user via SMS or Email, or Voice or KBV, or various types of authenticators, including multi-factor Software Cryptographic Authenticators, may be used as described in SP 800-63B.  Factors that may be used for Risk-Based Adaptive Multi-Factor Evaluation include but are not limited to: One-Time Transaction Keys, IP Address, Device ID, Geo-Location, Paired Hardware Token ID's, Application Threashold values, Time, etc. The risk of the transaction being accessed should determine the number of additional factors that should be evaluated for access.

I provide the above as an example text and not as any definitive answer, but the point is clear. The above level takes takes the "Data Breach Free For All" off the table. Unauthorized users can't simple access an account with known credentials. They must take a step back and individually target specific users one at a time. In addition, the addition of a Risk-Based Adaptive Multi-Factor Evaluation, means that for the most part, the Private Individual/Public User will almost never see any change in access behavior. The inclusion of SMS, Email and Voice as a method to reach out to the user, is provided because they are essentially ubiquitous and these methods allow for the Level to be deployed across an entire user population at various risk levels. Without these methods, the Private Individual would be required to download or install something or change their behavior which would guarantee that the additional security could only be deployed on an opt-in basis.

In summary, NIST 800-63-3 should provide recommendations for Private Individual access to Federal Services that hold PII and/or Health Care information. In my opinion, AAL-1 and AAL-2 are not sufficient for this use case. 

If NIST is not going to address recommendations for Risk-Based Adaptive Multi-Factor Evaluation and where they fit, then the document should specifically point out that the use case outlined above is not addressed by the document. 

I would note that Risk-Based Adaptive Multi-Factor Evaluations can be deployed not just for the login/authentication transaction, but any time during a session for any reason. 
## Both FFIEC guidelines and CJIS have provided guidance where RISK-Based authentication may be appropriate. I think NIST should as well.  

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
[Executive Order 13681](https://www.whitehouse.gov/the-press-office/2014/10/17/executive-order-improving-security-consumer-financial-transactions), _Improving the Security of Consumer Financial Transactions_, mandates the use of multiple factors of authentication by all agencies making personal data accessible to citizens through digital applications. Therefore, services like healthcare.gov will need to operate at AAL 2; supplementing AAL 1 with risk-based authentication is not an option.

As noted in SP 800-63-3 section 2, agencies may supplement requirements at a given AAL with additional risk mitigation measures.

**Comment by kcsapersona** [comment]
Thanks for the quick follow-up. So to be clear the reference you provided "_all agencies making personal data accessible to citizens through digital applications require the use of multiple factors of authentication and an effective identity proofing process, as appropriate._" applies to the Agency Employees AND the consumer, or does this ONLY apply to the Agency Employees?

**Comment by jimfenton** [comment]
The use of "citizens" here applies to consumers as well. Otherwise, they would have used "agency employees" or a similar term.

**Comment by rsfaron23** [comment]
this will become problematic for a number of consumer to USG cases over the internet, employment Verification, SSN review and SSN Lock, and even employer verification of hires.  The conjunction of risk-based evaluation of personal attributes, and identity resolution, coupled with identity validation via some method, possibly dynamic KBA, plus 2 factor authentication, would provide citizen and non-citizen customers a way to verify PII and other USG holding.  It makes it much harder to use digital processes, and means in-person verification, validation and authentication will be needed, placing a huge burden on USG programs (including refusal to participate) and a burden on budgets. Up front risk evaluation of persons seeking to build accounts can provide the foundation for risk evaluated programatic access to some government data and programs, as the risk is programmatically evaluated.  At higher risks, then added authentication processes may be warranted.

**Comment by kcsapersona** [comment]
Well it will certainly be interesting when ISG requires AAL-2 for citizens. In effect, if citizens do not access with a 2nd factor token of some kind, they will not be permitted to access services. Jim is making is clear that this is the stated direction. In practice, this level of security is difficult for users and would most likely light up the help desk with millions of calls. Risk evaluations provide a calculated buffer (based on many factors and time) and push for 2-Factor when needed. Jim's point is clear however, that services like healthcare.gov will "Require" AAL-2 for all parties. Trying to figure out how to make it useable will be a task for the application service owners, I guess.

**Comment by paul-grassi** [comment]
Just to be clear on a few things:
- Jim isn't saying this, the Administration is. 
- NIST is setting technical requirements, not determining which agencies or apps apply to this EO.  
- employees and contractors are covered by HSPD-12, not the EO.

**Comment by rsfaron23** [comment]
good luck in in-person identity proofing all USC's and e-gov users.  I am not disagreeing, just saying...

**Comment by kcsapersona** [comment]
Oh.. good point.. I did not want to imply Jim is creating policy. Sorry about that Jim!
The comment "services like healthcare.gov will need to operate at AAL 2" seemed to indicate a mandate rather than agencies will determine if their service applies to the technical requirements or not. 
Thanks for your comments and allowing this forum for discussion.

**Comment by paul-grassi** [comment]
The EO says nothing about in person proofing. It says effective proofing where appropriate. This may be, based on risk and use case, NO proofing. AAL2 != IAL2.
