### ISSUE TITLE
Problems with health tracker example 

### ISSUE THREAD

**Issue by DavidStaggs** [usnistgov/800-63-3#375]
**Organization**:
 Staggs PLLC

**Type**:
 Comment on HIPAA compliance.

**Document (63-3, 63A, 63B, or 63C)**:
SP 800 63-3

**Reference (Include section and paragraph number)**:
Executive summary:

**Comment (Include rationale for comment)**:
Suggest reviewing "health tracker" example for compliance with HIPAA.  Release of sensitive information from a covered entity to an application requires knowledge of the identity of the user.  Compare SP 800-63-3 text: "However, in this example, there may be no need for the agency system to know the true identity of the user."  Consider the API Task Force recommendations Topic 8 "Identity Proofing, User Authentication and App Authentication" (https://www.healthit.gov/facas/sites/faca/files/HITJC_APITF_Recommendations.pdf).  Also note, 800-63-3 relied on a reference to Executive Order 13681 ("Improving the Security of Consumer Financial Transactions") which does not include a "health tracker" example.

**Suggested Change**:
Covered entities may be required to perform identity proofing under HIPAA. The choice of IAL and AAL for access through an Application Programming Interface (API) should be the same level as the sign-up and login process that is used for patient portal access.  However,  API providers must not impose patient identify-proofing or authentication barriers for API access.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other 
1 for Federal health care providers, 2 for non-Federal health care providers

**Comment by paul-grassi** [comment]
A health tracker application as an example is not meant to be a HIPAA covered entity.  In addition, 800-63-3 states that it is not the only set of guidelines an organization may need to follow.  See 2nd paragraph under "Authority" in all docs.

**Comment by DavidStaggs** [comment]
Hi Paul

For what it is worth, it's not the health tracker that I was referring to.  It's the implication that the data custodian (when a CE) is releasing the information without the identity of the requester that I thought might cause confusion.

Thanks,

David

David Staggs, JD, CISSP

Security and Privacy Consultant

Security Risk Solutions, Inc.

698 Fishermans Bnd., Mt. Pleasant, SC 29464

Tel: (858) 433-1473

drs@securityrs.commailto:drs@securityrs.com

www.securityrisksolutions.comhttp://www.securityrisksolutions.com
