### ISSUE TITLE
Authentication Level Signaling

### ISSUE THREAD

**Issue by nklingenstein** [usnistgov/800-63-3#378]
**Organization**: 3

**Type**: Higher Education

**Document (63-3, 63A, 63B, or 63C)**: 63C

**Reference (Include section and paragraph number)**: Authentication Level Signaling

**Comment (Include rationale for comment)**: I need to signal the levels of assurance associated with user authentication from an identity provider to a service.  I can't find any defined way to do this.

**Suggested Change**: I'd like at least 4 URL's hosted by NIST that represent authentication levels with pointers from 800-63C.  I would prefer 4 static strings, but versioning and FAL levels might need to be considered.

**Comment by jricher** [comment]
A transferrence protocol like Vectors of Trust is a better way to define this kind of material reference.

**Comment by paul-grassi** [comment]
FICAM is the closes place this is defined in USG - https://gsageo.force.com/IDM/servlet/fileField?entityId=ka0t0000000TNKHAA4&field=File__Body__s

iGov is working on this too, and is eager to adopt VOT.  http://openid.net/wg/igov/

**Comment by nklingenstein** [comment]
Philosophical question, then.

What's the motivation for pulling this apart into finer and finer granularity?  I've seen other organizations defining assurance levels taking the opposite tact, pushing things back into as few as two categories.

I'm not sure what the schools here would prefer.

Thanks for the references to other USG work.  I'll chew through it.
