### ISSUE TITLE
5.2 add a general section on attestation

### ISSUE THREAD

**Issue by skswave** [usnistgov/800-63-3#38]
**Organization**:

**Type**:

**Reference (Include section and paragraph number)**:
5.2

**Comment (Include rationale for comment)**:
While government always like talk about the Public Private partnership the lack of attention in 800-63 for trusted computing is truly amazing. 

The problem is that the only assurance model for hardware is Fips 140-2   and it's failure to adapt to the new framework of TPM and TEE embedded hardware has resulted in little use of these really valuable authentication technologies. There is not one example of TPM throughout all of this document but there is a bunch on PIV, Biometrics and OTP Just one example in the doc of TPM would probably be a good idea.  

**Suggested Change**:
 Add a section on attestation to the health and integrity of the hardware device and it's capabilities. The verifier should be able to verify that the authentication but also play a role in the Cyber security controls. In the modern model of cloud computing with remote users it is not clear that the network will be able to provide these cyber security measures.  For a distributed user base verification of the attestation of the hardware as a self test performed by the hardware would lay the foundation to integrate cybersecurity controls on distributed authentication events.  The concept that there should be velocity controls is very cool but their also should be Cyber security controls. Known authentications coming from Known devices in a Known condition. It is simple to integrate into a Multifactor authentication and would add tremendous value for the systems that can support it. 

In general hardware protection of keys should be used if available regardless of FIPS 140- 2 certification level it will enhance an AAL1 if used.  

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
SP 800-63B does refer to the use of TPM and TEE in 5.1.3.1 in the context of protecting an embedded secret in an out-of-band authenticator. There are undoubtedly other contexts where that guidance should also apply; we will call out similar guidance in other places where a secret is embedded in an endpoint device.

**Comment by skswave** [comment]
There are 2 points in this comment. the first is just generic that an out of band authenticator is not an industry term for the TPM and TEE. So far with billions of TPMs deployed it continues to be shocking how little they are used. This document is a perfect place to put a higher level of focus on the embedded hardware.  There must be some reasonable way to say it is strongly suggested to use hardware to protect keys if available vs software solutions.  it is the opposite of suggesting that perhaps SMS is not the best model to use. 

the second point is that there should be some thought to how Attestation data for the authenticating platform can be carried with the identity transaction. This would allow a peer to  peer identity verification with cyber security controls. The relying device could verify that the sending device has attestation data that meets reference values Similar to the model for trusted network connect in NIST 800-155.  This assurance that the sending platform is in a known good condition could then easily become part of the identity risk score.  It would also allow the relying party to continuously verify that the identity asserted by a higher level of trust. As the trust systems shift from static smartcards to dynamic TEE o TPM environments there will be a need to assert that the platform has not been updated from a known reference. What might have been a level 4 credential may not still be one.  The complexity of certification is going to become really really hard on these dynamic platforms and it will be through platform identity and attestation that it will be possible to keep up. With 500 million smart devices already deployed and many more to come it is important that there is some initial thought  as to how this is considered or treated.
