### ISSUE TITLE
"Account linking" should be discussed as a distinct function in the Digital Authentication Model

### ISSUE THREAD

**Issue by MartinFSmith** [usnistgov/800-63-3#380]
**Organization**: BFC Consulting

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**: 63-3

**Reference (Include section and paragraph number)**:
63-3 Sec. 4.1 & 4.4 

**Comment (Include rationale for comment)**:

By "account linking" I mean the process of establishing a durable binding between a subscriber identifier in one domain and a subscriber or account identifier in another domain.  The principal use-case is linking a subscriber identifier issued by an "external" CSP to a pre-existing account on a information system of a government agency or business enterprise. 

This is what most governmental citizen-access initiatives (e.g., the late Connect.gov) aim to accomplish, by providing or certifying sources for subscriber identifiers (e.g., Connect.gov "login partners") that can be used to access multiple governmental accounts -- tax, social security, health care, etc. The challenge is to assure that the claimant holder of the externally provided identifier is the same person for whom the various governmental accounts were established. The usual approach is to find a set of personal attributes, each of which is "known" (to whatever level of assurance is provided by the proofing used) by both the external CSP and the relying-party governmental system, and which taken together provide an acceptable (to the RP) assurance of a correct match. Once a correct match has been determined, a durable binding is established between the external identifier and the internal account identifier. 

This durable binding means that the matching process does not have to be performed each time the subscriber wants to access the RP resource, which means that the personal attributes do not have to be exposed by the external CSP after the initial match is made. 

The account-linking function is important to call out because it is the only function supporting a major use-case for which there is a well-defined requirement for a CSP to make a limited, one-time release personal attributes to support federated authentication. Calling out this function and describing its typical use-case would help clarify and justify the recommendation that personal attributes should not otherwise be exposed.   

("Personal attributes" are those, like name, address, DOB etc. that are commonly used to uniquely identify a human, but which typically are not authorization related, i.e., are not required by a valid access-control policy based on law, regulation or mission/business policy. There are exceptions: DOB, for example, is PII, but DOB --or a derived claim like "over 21 yo" -- may also be needed to authorize purchase of alcohol in many jurisdictions.) 

Note that the attribute matching technique is not necessarily the only technique for accomplishing account linking, but it is well-established and is supported by commercial products going back to the "meta-directory" and "virtual directory" products of the 1980s. Note also that these techniques were also used to assemble "privilege" or "role" attributes assigned to a subscriber (to support authorization decisions) from multiple databases and directories within an enterprise. Although linking of multiple remote authoritative attribute sources for transaction-time assembly of authorization assertions has not been implemented, the same account-linking techniques would likely be used for this capability.

**Suggested Change**:
##  Draw on material above to define "account linking" and to recommend that exposure of PII by a CSP is discouraged outside this use-case.

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
This is a good topic, as we have seen many account linking approaches, some better than others, this is a candidate for a supplemental operations-type document.  Not the SP.
