### ISSUE TITLE
inconsistent among Asymmetric Keys, Digital Signature, Private Key and Public Key

### ISSUE THREAD

**Issue by wangxjnj** [usnistgov/800-63-3#381]
**Organization**:

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**:3. Definitions and Abbreviations

**Comment (Include rationale for comment)**:
 **Asymmetric Keys** (signature should be referring to Digital Signature. It does not clearly state that both of the keys can be used to do the encryption and decryption.)

**Digital Signature** ( make it clear that it does not provide confidentiality protection)

**Private Key** (digital signing is just a special  private key encryption use case)

**Public Key**(digital signature verification is just a special  public key decryption use case)

**Suggested Change**:
  **Asymmetric Keys** from 
"Two related keys, a public key and a private key that are used to perform complementary operations, such as encryption and decryption or signature generation and signature verification."
to

"A key pair, a public key and a private key that are used to perform complementary encryption and decryption operations, such as digital signature signing and signature verification(private key is used to do encryption and public key is used to do decryption) or Authenticated Protected Channel(TLS) establishment(public key is used to do encryption and private is used to do decryption)."

**Digital Signature**  from
"An asymmetric key operation where the private key is used to digitally sign data and the public key is used to verify the signature. Digital signatures provide authenticity protection, integrity protection, and non-repudiation."
to

"An asymmetric key operation where the private key is used to digitally sign data and the public key is used to verify the signature. Digital signatures provide authenticity protection, integrity protection,  non-repudiation, but no confidentiality protection."

**Private Key**  from
"The secret part of an asymmetric key pair that is used to digitally sign or decrypt data."
 to

"The secret part of an asymmetric key pair that is used to encrypt or decrypt data.  Private key encryption provides authenticity protection. Private key decryption ensures confidentiality."

**Public Key** from
"The public part of an asymmetric key pair that is used to verify signatures or encrypt data."
to
## "The public part of an asymmetric key pair that is  used to encrypt or decrypt data. Public key encryption provides confidentiality protection. Public key decryption ensures authenticity and non-repudiation."

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
See also #246
