### ISSUE TITLE
Suggestino to provide levels of assurance that do not require FIPS certification

### ISSUE THREAD

**Issue by igaines** [usnistgov/800-63-3#382]
**Organization**:
DOE MFA Program and Policy Working Group

**Type**:

**Document (63-3, 63A, 63B, or 63C)**:
63B

**Reference (Include section and paragraph number)**:
overall document 

**Comment (Include rationale for comment)**:

If the goal of AAL is to improve the authentication and life cycle management practices of Federal Agencies/Relying Parties, the current draft of 800-63 r3 undercuts that goal.  In this case the perfect is the enemy of the good – or more precisely certification is the enemy of improvement.
Given that:
 Achieving full certification for AAL 3 can be a costly and time consuming process (up to 2 years; I don’t have any figures on the financial burden but for a small company the inability to sell for 2 years can cost the entire company)
 Implementation of technology and practices that conform to the AAL 3 requirements, but have not yet been certified as compliant would improve authentication and reduce the risk of failed or subverted authentication.
 While certification is a valuable element of AAL3, the cost of certification is not proportionate to the value (and if past history is any indicator, this disparity will increase over time).
This has the effect that:
 Relying parties/Federal Agencies will find it difficult to implement cutting edge authentication technologies
 Small innovative firms will be excluded from the market
 Innovation in authentication technology will be suppressed.

**Suggested Change**:

We recommend that SP 800-63r3 be extended in a manner similar to SP 800-53a.  It should be possible for a vendor to offer an AAL3 technology at varying levels of rigor.  For example:
1.  Low Rigor – the vendor asserts that the technology/implementation conforms to the requirements
2.  Moderate Rigor – The vendor asserts and provides substantial evidence of conformance. Evidence should be transparent, and open to peer or popular review. 
3.  High Rigor – the technology is certified as conformant. 

---

Organization: 1 = Federal, 2 = Industry, 3 = Other 
1

**Comment by paul-grassi** [comment]
AAL3 is supposed to be hard, due to the nature of the assets that need protecting and the impact of an authentication failure.  In addition, any scheme at AAL3 that allows a progressive path to certification means that the only gate that will ever be reached is low rigor.  Once it's in, it's in and the motivation to reach certification is lost.  

To that end, we have introduced a new authenticator at AAL3, SF HW Crypto Device + Memorize secret that requires FIPS 1, Physical 3.
