### ISSUE TITLE
Eliminate definitions for "Unverified Name" and "Verified Name" or change "Name" to "Attribute"

### ISSUE THREAD

**Issue by MartinFSmith** [usnistgov/800-63-3#383]
**Organization**: BFC Consulting

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**: 63-3 and 63-3a

**Reference (Include section and paragraph number)**:
 63-3 Sec 3 . and 63-3A Sec 3
**Comment (Include rationale for comment)**:
Including "Unverified Name" and "Verified Name" in the Definitions suggests that "name" has special status as a personal identity attribute, and may imply that it is appropriate to use name as a subscriber identifier, which in general it is not.  

Furthermore, the terms don't appear to be used elsewhere in the 800-63-3 draft documents.  

**Suggested Change**:

Eliminate "Unverified Name" and "Verified Name" from the Definitions sections in 63-3 and 63-3A.

Alternatively, replace these terms with "Unverified Personal Attribute" and "Verified Personal Attribute" 

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
Still needs to be fixed in 800-63-3.
