### ISSUE TITLE
Reconsider definition and use of  the term "Claimed Identity"

### ISSUE THREAD

**Issue by MartinFSmith** [usnistgov/800-63-3#385]
**Organization**: BFC Consulting

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**: 63-3

**Reference (Include section and paragraph number)**:
 63-3 Sec 3.; 63-3 Sec 4.3.1.

**Comment (Include rationale for comment)**:

Sec 3--
1. The definition of "Claimed Identity" seems to assert that there is a set of three personal attributes (personal name, DOB, and address) that is universally or at least widely accepted by CSPs as necessary and sufficient to establish accountability of a subscriber for their digital activities. First, I am not aware this particular set of attributes is generally accepted. Second, two of the three attributes are problematic. The conventions of constructing personal names vary widely between cultures (last name first, or vice versa; use of matronymics; even character sets used.) Address is not an enduring personal attribute, and furthermore release of this information by a CSP as part of any authentication process opens up a vector for physical attack on a subscriber.
1. The usage of "Claimed Identity" in the definition of "Pseudonymous Identifier" [mis-spelled as "Identifer" by the way] seems contradictory. On the one hand it says the identifier "does not allow the RP to infer the subscriber" while on the other hand it "does permit the RP to associate multiple interactions with the subscriber’s **claimed identity.**" [Emphasis added] 
2. The definition of "Identity Assurance Level (IAL)" should be changed, which would eliminate the use of the term "Claimed Identity." 

Sec 4.3.1.
Reference: " . . . other types of information, such as location data or device identity, may be used by an RP or verifier to evaluate the risk in a claimed identity, but they are not considered authentication factors. "  This clearly implies that an RP will have access to the personal attributes included in the definition of "Claimed Identity." Such exposure of DOB and address, in particular, should be discouraged except (possibly) as a one-time release in an account-linking scenario. 

**Suggested Change**:
1. Since the only usages of the term "Claimed Identity" (in 63-3) should be eliminated, perhaps the definition should also be eliminated. Alternatively, it might be redefined in a more general way, depending on the reason for including it in the Special Pub. Is the intent to promote use of a standard set of personal attributes?  If so, is the focus on account linking, where attributes are considered likely to be available to both federated CSPs and one or more RPs? Or on establishing reliable accountability of the subscriber for his/her digital actions (i.e., so the subscriber can be located by law-enforcement if necessary)? (Presumably the focus is not on generating a unique digital identifier since that can be done without PII.)  
1. Identity Assurance Level (IAL)
   A metric describing degree of confidence that the personal attribute data on the basis of which the CSP grants an identifier are accurate.  
2. Pseudonymous Identifer
   A meaningless, but unique number that does not allow the RP to infer the subscriber but which does permit the RP to associate multiple interactions with the claimant's presented identifier..

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
-3 definition will  be fixed.
