### ISSUE TITLE
Distinguish and provide guidance for two different types of user (subscriber) attributes

### ISSUE THREAD

**Issue by MartinFSmith** [usnistgov/800-63-3#387]
**Organization**: BFC Consulting

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  63-3

**Reference (Include section and paragraph number)**:

Sec 4.1 or 4.4 or 4.4.1

**Comment (Include rationale for comment)**:
It is useful to distinguish between two types of user attributes, based on their use in identity and access management systems. 

The first type, let's call them "personal attributes", are properties of the human user verified by a CSP at registration and used as the basis for a decision to accept an applicant as a subscriber. Personal attributes should not generally be exposed by the CSP: they are not required to authenticate a claimant; they are not generally appropriate for use in authorization decisions, and they are clearly PII. An exception is that personal attributes may be needed on a one-time basis for account linking. [See separate comment on account linking.]  Examples of personal attributes are name, DOB, and biometrics generally. 

The second type of user attributes, non-personal attributes, are used for authorization decisions. These attributes are particularly important for access to information by authorized users acting as agents of a governmental or private organization subject to information-access-related law, regulation, policy or contract obligations. Examples of non-personal user attributes are security clearance, citizenship, employee/contractor status (with a specific organization), physician, law-enforcement officer, and duty station.  

The benefit of distinguishing between these two types of user attributes is to provide a basis for guidance that they should be treated differently, particularly in federated scenarios, by CSPs and other participants in identity systems. 
Personal attributes should not generally be exposed by the CSP: they are not required to authenticate a claimant; they are not generally appropriate for use in authorization decisions, and they are clearly PII. An exception is that personal attributes may be needed on a one-time basis for account linking. [See separate comment on account linking.]  Non-personal attributes are also generally (but not always) less sensitive from a privacy point of view as they are typically granted (provisioned) to the user by their employer or other legally authoritative source. Non-personal attributes are obtained (by CSPs or RPs) specifically because they are needed to meet information access requirements defined by law, regulation, etc. Thus they are required to be made available for access-control (authorization) decisions.

There are some cases where a personal attribute (e.g. DOB) may be relevant to an authorization decision (e.g., ability to buy alcoholic beverages.) However in many of these cases, the minimum requirement for the authorization decision is not a specific DOB, but only for the derived attribute that the DOB is 21 years earlier than the current date. Guidance should recommend that in such cases the authorizer (typically the RP) should request and the CSP should provide only the derived attribute necessary to satisfy the specific access policy requirement. 

**Suggested Change**:
##  Draw on comment above to add guidance on "personal attributes" vs. "non-personal" attributes. Alternatively, the distinction could be drawn between (user) attributes used for registration but not exposed except when required for account-linking; vs user attributes provided to RPs for authorization purposes. 

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
It's not up to this guidance to define which attributes are used for authorization and which are not.
