### ISSUE TITLE
IAL and AAL Summary

### ISSUE THREAD

**Issue by nadalin** [usnistgov/800-63-3#39]
**Organization**:
 2
**Type**:
 Nomative
**Reference (Include section and paragraph number)**:
 IAL and AAL Summary
**Comment (Include rationale for comment)**:
 Level 1 may not contain any attributes 
**Suggested Change**:
##  At this level, attribute may be provided in conjunction

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
Fix applied.
