### ISSUE TITLE
Apparent conflict for In-Person Proofing requirement for IAL3

### ISSUE THREAD

**Issue by soreilly01** [usnistgov/800-63-3#4]
Department of Justice
 
Requirement Conflict
 
800-63-3A, Sections 4.3 and 4.6
Section 4.3 - "At IAL 3, identity proofing SHOULD be performed in person. 'Virtual in-person' identity proofing MAY be employed by a CSP as an equivalent process to in-person identity proofing."
Section 4.6 - "In addition, identity proofing at IAL 3 SHALL be performed in-person."
Section 4.6.1 "The CSP SHALL perform identity proofing in-person."

There is a clear conflict between SHALL (must be done) and SHOULD (course of action is preferred but not necessarily required) in these sections.  I think I understand where section 4.3 is going (promoting a virtual in-person option with specific requirements), but this type of conflict between requirement and recommendation in different sections will cause issues.

Additionally, the title of section 4.3 is In-person Proofing Requirements, but it is clearly focused on introducing the virtual in-person option.
 
Recommendation 
The requirement language should be aligned between sections.  If this virtual in-person is a true option for IAL3, it should be reflected in 4.6.  Also recommend section 4.3 remove IAL3 requirement language and just be a definition of the in-person AND virtual in-person proofing requirements (potentially in separate subsections), and the section header adjusted to reflect it's content.

---
 
Organization: 1 - Federal

**Comment by pgrassi-nist** [comment]
This is good feedback.  The use of SHOULD and MAY was to indicate we prefer real in-person, but are ok with virtual in-person.  But I understand that we are calling them the same in the In person Section.  We will clarify.
