### ISSUE TITLE
Virtual In-Person .v. Remote

### ISSUE THREAD

**Issue by mabbiss** [usnistgov/800-63-3#434]
I am confused by the references to "**Virtual In-Person**" and "**Remote**" identity proofing. 

The terms seem to be used interchangeably within the document and ultimately refer to the same thing, or am I missing a subtle difference?

**Comment by mabbiss** [comment]
May I ask why this question was removed?

**Comment by paul-grassi** [comment]
Comment period is closed until we release the next draft. https://pages.nist.gov/800-63-3/

**Comment by mabbiss** [comment]
Ok. Thanks for the quick reply. When will the next draft be released?

**Comment by paul-grassi** [comment]
Hopefully right at the new year, if not earlier.
