### ISSUE TITLE
The veracity of a micro-deposit is only as good as the strength of a financial institution’s identity proofing system.

### ISSUE THREAD

**Issue by SES-SSE** [usnistgov/800-63-3#44]
**Organization**: 1

**Reference (Include section and paragraph number)**:
5.3.2. Knowledge Based Verification Requirements 

**Comment (Include rationale for comment)**:
A fraudster opened up several checking accounts with “overdraft protection” through a financial institution online in my wife’s name. The fraudster made a mistake in opening some of the accounts that made us aware of the fraud, but the financial institution was totally unaware of any fraud until she notified them. Needless to say, the accounts were opened for several days—possibly enough time to commit fraud against a system using micro-deposits.  She talked to the security group of the financial institution and they informed her that the fraudster knew her basic information, e.g. name, DOB, SSN etc., but according to the security team, no KBV type questions were asked.  Because of this, she now has her credit locked.

Therefore, any government system that will place a reliance on micro-deposits must be aware of the above risk. The veracity of a micro-deposit is only as good as the strength of a financial institution’s identity proofing system. That being said, it is next to impossible for any government system owner to determine whether a micro-deposit is trustworthy or not without having a proper understanding of the identity proofing system of the financial institution.  Moreover, we naturally focus on U.S. systems, but what happens in the case where a foreign bank is used? 

It would seem to me that NIST 800-53 Rev 4 Security Control AC-20 Use of External Information Systems, “b” is applicable to micro-deposits.  AC-20 “b” states “Process, store, or transmit organization-controlled information using external information systems.”  In this case the organization-controlled information is the micro-deposit, but the reliance of the proofing mechanism isn’t the micro-deposit, but the reliance on the financial institutions identity proofing system that makes the financial account valid.

So in summary, the larger issue is, when a government system relies on a none-government system or any other government system for that matter for evidence of any kind for identity proofing individuals, the evidence produced by the system is only as strong as the identity proofing of that external system.

**Suggested Change**:
CSP MAY need to determine the IAL of a financial institution’s identity proofing system and the security controls of the proofing system that are implemented before allowing micro-deposits to be made to the financial institution that is to be used as a security control by the CSP for its identity proofing.

Note: I struggled with using MAY and SHOULD instead of SHALL because it is probably beyond the resources of any one agency to vet all financial institutions' methods of identity proofing that an agency may wish to use micro-deposits with in order to support the agency’s identity proofing of individuals.  IMO, AC-20 is applicable but in reality it probably isn’t feasible to apply across every financial institution. Guidance on foreign banks should also be provided.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by TerryMcBride** [comment]
It's also only as good as the entropy of the deposit amount.  If a dollar or less, then at least 1/100 probability of  guessing correctly (probably better assuming they aren't using FIPS random number generators).

**Comment by paul-grassi** [comment]
We appreciate the concern and hate to hear stories like this.  The guidance we are offering hopefully can prevent this, but it's never a perfect system, and least we can do is prevent scalable attacks.  Per the suggested change, this requirement already exists for evidence in [Section 5.3](https://pages.nist.gov/800-63-3/sp800-63a.html#validate).  I also expect that trust frameworks will arise that will predetermine the institutions that qualify for this type of validation, to include any foreign institutions that could be allowed.  But trust framework definitions, rules, tools, is out of scope for 800-63.  

@TerryMcBride you make a good point and would recommend you create a new issue for that.  Our approach is likely to be verification of the amount and the transaction id, which would achieve the entropy we need.  If transaction id is not available, perhaps a timestamp.  To allow for flexibility, probably best to say amount + something else.  Anyway, a new issue would be great for tracking and transparency purposes.
