### ISSUE TITLE
Random memorized secret by default

### ISSUE THREAD

**Issue by fulldecent** [usnistgov/800-63-3#449]
SP 800-63B correctly identifies the main problem with passwords:

 > Users struggle to remember passwords, to carry multiple authentication devices, and to remember which authenticator goes with which RP. It is critical to evaluate the usability of authentication, since poor usability often results in user coping mechanisms and unintended user work-arounds, which can ultimately degrade the intended security controls.

For the Authenticator Assurance Level 1, a password ("memorized secret") is a permitted authenticator. This is /by far/ the most common authentication method in use in online systems today.

Unfortunately password reuse is not mentioned in this document. This is a major problem, and the document only addresses this issue by recommending a blacklist against passwords from previous breach corpuses.

A MUCH better alternative is to take the notice from A.5 as a prescription:

 > Secrets that are randomly chosen (in most cases by the verifier or CSP) and are uniformly distributed will be more difficult to guess or brute-force attack than user-chosen secrets meeting the same length and complexity requirements.

----

# Recommendation

Update **10.1.2. Memorized Secret / Typical Usage**. Append a bullet point to **Usability considerations for typical usage include:** as follows:

 * User experience during creation of memorized secrets.

    * Follow all recommendations for "User experience during entry of memorized secrets" above, ignoring those relating to allowed attempts.

    * Users SHOULD have the option to generate a random memorized secret. The entry screen may randomly generate a version 4 UUID (defined in RFC 4122) as the recommended memorized secret.

    * Users SHOULD be able to generate a random memorized secret with minimal interaction (one click or less).

    * The entry screen MAY generate a random memorized secret by default and require the user to make additional effort (click a button) to enter their own customized memorized secret.

**Comment by fulldecent** [comment]
Additional discussion at https://www.reddit.com/r/netsec/comments/5extcf/nist_recommendation_use_random_generated_passwords/

**Comment by IncludeSec** [comment]
So NIST is referencing reddit for standards discussions now....

![When NIST is referencing reddit for standards discussions](https://media.giphy.com/media/l0K4nCoSjvMx0agYE/giphy.gif "When NIST is referencing reddit for standards discussions")

**Comment by jricher** [comment]
No, a discussion is happening on a popular discussion website about something that NIST is doing, and one of the people involved with said discussion (not a NIST person) posted the reference here.

**Comment by jimfenton** [comment]
Issue closed because we are not currently in a comment period.

**Comment by fulldecent** [comment]
@jimfenton Thanks for categorizing the issue. I will wait for the next comment period to discuss further.
