### ISSUE TITLE
Accessibility out of scope ?  That's not just unwise, it's illegal!

### ISSUE THREAD

**Issue by readnotify** [usnistgov/800-63-3#481]
I notice this today:

-Accessibility is out of scope for this section, and can be addressed in an organization’s implementation plans.

This is a major vulnerability: if you do not address solutions for the disabled, then hackers are going to be able to use the adhoc implementations that result to bypass the entire authentication mechanism.

And that's not starting on the "scope" sentence: no, it was never out of scope - nor was it legal to try and put it there.  Unless you want this entire standard banned by law, catering for everyone properly needs inclusion.

**Comment by jimfenton** [comment]
We are not currently accepting comments on GitHub. If you wish, please make this comment in the public comment period that will be opening up soon.

**Comment by readnotify** [comment]
Ironic how standards end up getting trusted, yet during their creation, everyone puts on blinkers and utterly ignores - no - actively rejects - looking at the faults...
