### ISSUE TITLE
Blog link is dead

### ISSUE THREAD

**Issue by frozencemetery** [usnistgov/800-63-3#489]
README.md links to http://nstic.blogs.govdelivery.com/ which seems to serve a redirect to http://trustedidentities.blogs.govdelivery.com/ which cannot be resolved.

**Comment by paul-grassi** [comment]
We are not taking issues, but this was so darn easy and an oversight on our end after changing domains that I made the change.  Thanks for the catch. Please note, we are auto-closing issues at this point.  Please hold issues for formal public comment period, which will be opening very soon.  Thanks for your feedback and attention to this document.
