### ISSUE TITLE
Suggestion: Move all definitions to separate document

### ISSUE THREAD

**Issue by iglazer** [usnistgov/800-63-3#49]
**Organization**: 2 

**Type**:

**Reference (Include section and paragraph number)**: 

**Comment (Include rationale for comment)**: The definition sections appears in each document as Section 3 and reflects a great deal of overlap. Why not simply create 800-63-D for a consolidated definitions document?

**Suggested Change**:

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
@iglazer double checking with NIST pub folks on how to accomplish this good comment.  Accepting for now, pushing to future iteration.

**Comment by paul-grassi** [comment]
NIST pub prefers the approach currently being taken. We will make sure only terms relevant to each doc turn up in its respective glossary.
