### ISSUE TITLE
typo: Authenticator Assurance Level 1

### ISSUE THREAD

**Issue by wangxjnj** [usnistgov/800-63-3#506]
### All Fields Are Required
**Organization Name (N/A, if individual):** N/A

**Organization Type (see below for codes)**:4
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**:2. Introduction
 Authenticator Assurance Level 1
**Comment (Include rationale for comment)**:
 "Successful authentication requires that the claimant prove possession and control of the authenticator through a secure authentication protocol."
**Suggested Change**:
 prove --> proves
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
In this context, "requires" is a propositional verb, which causes the verb in the following clause (prove) to be in the base (infinitive) form. The sentence is correct as written.

See item 7 in http://www.eslcafe.com/grammar/verb_forms_and_tenses02.html
