### ISSUE TITLE
RE: Digital Signature definition

### ISSUE THREAD

**Issue by wangxjnj** [usnistgov/800-63-3#508]
### All Fields Are Required
**Organization Name (N/A, if individual):**N/A

**Organization Type (see below for codes)**:4
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**:3. Definitions and Abbreviations
 Digital Signature
**Comment (Include rationale for comment)**:
 Digital Signature is PKI based. 
**Suggested Change**: 
 A PKI based asymmetric key operation where the private key is used to digitally sign data and the public key is used to verify the signature. Digital signatures provide authenticity protection, integrity protection, and non-repudiation but not confidentiality protection.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Digital signatures may be used with pre placed keys or other asymmetric key management schemes apart from PKI. The definition is accurate as it is written.

**Comment by wangxjnj** [comment]
The authenticity protection and non-repudiation  without a Cert?
