### ISSUE TITLE
RE: PKI definition

### ISSUE THREAD

**Issue by wangxjnj** [usnistgov/800-63-3#509]
### All Fields Are Required
**Organization Name (N/A, if individual):** N/A

**Organization Type (see below for codes)**: 4
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 2 definition
Public Key Infrastructure (PKI)
**Comment (Include rationale for comment)**:
 PKI does not manage private key.
**Suggested Change**:
 take the "and public-private key pairs" out
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
PKI manages the association between keys in a keys key pair and often manages generation of both public and private keys, so I believe the current text is accurate.

**Comment by wangxjnj** [comment]
PKI only manages the public keys. The private keys are  NEVER exposed to PKI. PKI cannot force private key change. It does not even know whether the private key still exists or valid ( corrupted or accidentally removed)  while signing the public key.

**Comment by wangxjnj** [comment]
PKI is an arrangement that binds public keys with respective identities of entities (like persons and organizations). The binding is established through a process of registration and issuance of certificates at and by a certificate authority (CA)
