### ISSUE TITLE
Not all out-of-band authenticators require presentation of secret back to primary channel

### ISSUE THREAD

**Issue by iglazer** [usnistgov/800-63-3#51]
**Organization**: 2

**Type**:

**Reference (Include section and paragraph number)**: 800-63-B Section 5.1.3

**Comment (Include rationale for comment)**: The 1st paragraph of 5.1.3 describes a way that an out-of-band authenticator can work - in which a secret is sent via one channel and that secret is presented back to the primary channel. But that is only one way an out-of-band authenticator can work. OOB authenticators can also work by never asking the user to present anything directly back to the primary channel but instead use the secondary channel to communicate solely.

**Suggested Change**: Section 5.1.3 should be made more specific to say that if the OOB Authenticator requires the presentation of the delivered secret back to the primary channel then the existing text holds. However, if the OOB Authenticator communicates solely along the secondary channel then the system must be designed to ensure that the delivery as well as a proof-of-possession action is done so securely.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
OOB authenticators can of course work in the manner that you describe, but in that case it's important that there be a means of securely associating the primary and secondary channels so that an attacker could not trick the holder of the OOB authenticator into approving an authentication for the attacker. There needs to be some identifier, such as a transaction ID or description included there as well.

**Comment by iglazer** [comment]
Agreed but I don't think this document ought to be prescriptive as to how that is accomplished.

**Comment by paul-grassi** [comment]
I think the suggested text, reworded if we need to, allows for describing security characteristics we desire in pure 2nd channel OOB.  The market can drive innovation and security and RP's can do the risk assessment that their implementation holds up, or that they even want to take this route for an authenticator.

**Comment by paul-grassi** [comment]
>  Note, suggested text provided by @iglazer in the initial comment.

**Comment by jimfenton** [comment]
I want to be as general as possible, and saw Ian's text, but "done so securely" isn't quite sufficient. When the secret is communicated back over the primary channel, that establishes a binding to the authentication that doesn't exist when the communication is back over the secondary channel. We need to make sure that binding happens some other way lest the user approve the wrong authentication.

I'll have a pull request ready soon and let me know if I'm being too prescriptive.

**Comment by paul-grassi** [comment]
Great!  Tag ian in the pull request so he can take a look before merging.

**Comment by paul-grassi** [comment]
Closed  by pull request #86
