### ISSUE TITLE
RE: "authentication error"

### ISSUE THREAD

**Issue by wangxjnj** [usnistgov/800-63-3#511]
### All Fields Are Required
**Organization Name (N/A, if individual):** N/A

**Organization Type (see below for codes)**:4
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 2. Introduction
 The strength of an authentication transaction is characterized by an ordinal measurement known as the AAL. Stronger authentication (a higher AAL) requires a higher level of capabilities or resources on the part of an attacker in order to successfully authenticate, effectively reducing the risk of an authentication error.
**Comment (Include rationale for comment)**:
 MFA auth means more  "authentication error" .  Should be changed to "account takeover"?
**Suggested Change**:
 change "authentication error" to "account takeover". 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Not all authentication errors are due to account takeovers. We will maintain the current wording.
