### ISSUE TITLE
RE: move OOB SMS to SMS OTP

### ISSUE THREAD

**Issue by wangxjnj** [usnistgov/800-63-3#512]
### All Fields Are Required
**Organization Name (N/A, if individual):** N/A

**Organization Type (see below for codes)**:4
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 5.1.3. Out-of-Band Devices

**Comment (Include rationale for comment)**:
 OOB SMS is not  "uniquely addressable", and can not " communicate securely with the verifier over a distinct communications channel". 
**Suggested Change**:
  OOB SMS does not meet the  "uniquely addressable" and " communicate securely " requirements. Should move it out from OOB, and put it into OTP section.  Rename OOB SMS to SMS OTP. It is the weakest OTP authenticator. 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
OOB SMS involves the transmission of an authentication secret from the verifier to the subscriber. This is fundamentally different from an OTP authenticator that locally produces the same authentication secret as the verifier, so to move SMS to OTP would be a mischaracterization.
