### ISSUE TITLE
Virtual In-Person" .v. "Remote" identity proofing

### ISSUE THREAD

**Issue by mabbiss** [usnistgov/800-63-3#514]
### All Fields Are Required
**Organization Name (N/A, if individual):**
N/A
**Organization Type (see below for codes)**:
 4
**Document (63-3, 63A, 63B, or 63C)**:
63A
**Reference (Include section and paragraph number)**:
 Multiple
**Comment (Include rationale for comment)**:
 I am confused by the references to "Virtual In-Person" and "Remote" identity proofing. The term Virtual In-Person is actually defined in section 3 (Definitions and Abbreviations) but the remainder of the document focuses on "Remote". The terms appear to be used interchangeably but is there in fact a fundamental difference between these two alternatives?

**Suggested Change**:
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Any transaction that meets the requirements stated in Section 5.3.3.2 counts as in-person.  Any other remote in person transaction needs to meet the requirements for IAL2 to be acceptable.
