### ISSUE TITLE
typo: Memorized Secrets

### ISSUE THREAD

**Issue by wangxjnj** [usnistgov/800-63-3#515]
### All Fields Are Required
**Organization Name (N/A, if individual):** N/A

**Organization Type (see below for codes)**: 4
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**:5.1.1. Memorized Secrets
 A Memorized Secret authenticator (commonly referred to as a password or, if numeric, a PIN) is a secret value that is intended to be chosen and memorable by the user. Memorized secrets need to be of sufficient complexity and secrecy that it would be impractical for an attacker to guess or otherwise discover the correct secret value
**Comment (Include rationale for comment)**:
"to be chosen and memorable " should be "to be chosen and memorized"?

"sufficient complexity and secrecy that" --> "sufficient complexity and secrecy so that" (missing so)
**Suggested Change**:
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
"Memorable" means that is is able to be memorized; this is the intended meaning.

"So" is not necessary in this context.
