### ISSUE TITLE
RE: authenticated protected channel

### ISSUE THREAD

**Issue by wangxjnj** [usnistgov/800-63-3#516]
### All Fields Are Required
**Organization Name (N/A, if individual):** N/A

**Organization Type (see below for codes)**: 4
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**:4.1.2, 4.2.2, 4.3.2
 Communication between the claimant and verifier (the primary channel in the case of an Out of Band authenticator) SHALL be via an authenticated protected channel to provide confidentiality of the authenticator output and resistance to MitM attacks.
**Comment (Include rationale for comment)**:
 single Vs multiple channels? 

For web based auth the auth flow may look like below;
claimant --> Browser -->RP -->Verifier.  Two channels should be established: 1. Browser to RP(https),  2.  RP to Verifier (https, SSL, or something else) are required
**Suggested Change**:
 change "SHALL be via an authenticated protected channel" to "SHALL be via  authenticated protected channels"
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Changed from accepted to declined; we had misread the issue.

-63B addresses the situation where the RP and verifier are the same entity, or effectively so. When the RP and verifier are separate, an assertion is sent from the verifier to the RP as described in -63C, and the requirement for an authenticated protected channel is described there (see sections 6.1 and 6.2 of -63C).
