### ISSUE TITLE
Consistent use of "Adequeate" or "Fair"

### ISSUE THREAD

**Issue by kcrowl11** [usnistgov/800-63-3#518]
### All Fields Are Required
N/A

2
 
63A

4.4 and 5.2
 
Section 4.4 refers to "Adequate" levels of Evidence, but then section 5.2 refers to them as "Fair"
 
In my opinion, either term is fine, just need to be consistent.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Good catch.  Will fix.

**Comment by paul-grassi** [comment]
Fixed via PR https://github.com/usnistgov/800-63-3/pull/520
