### ISSUE TITLE
RP shouldn't rely on 'expiration' to be accurate

### ISSUE THREAD

**Issue by iglazer** [usnistgov/800-63-3#52]
**Organization**: 2

**Type**:

**Reference (Include section and paragraph number)**: 800-63-C Section 5

**Comment (Include rationale for comment)**: We should be teaching RPs to play stronger defense when it comes to claims, especially around expiration. Just because a claim includes an expiration doesn't guarantee that something hasn't happened in the intervening time to cause the CSP to expire the claim prematurely. RPs should be of the habit to check the validity of the claim and not rely upon expiration as the sole expression of validity.

**Suggested Change**: A small section on claim validity checking, potentially in Section 7

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
The "expiration" here is for the assertion itself, not necessarily for the attributes of the user. We can be more clear on what those pieces apply to and why the values are recommended.

As for claim validity checking, this is ultimately a problem of cache consistence. The RP should be willing and able to take in information from the IdP, even though things could change in the mean time. What advice would you give an RP to handle this?

**Comment by iglazer** [comment]
To the RPs I would say that the expiration of the assertion is an expression of the longest the assertion might live but that a) many things can happen in between that would revoke the assertion and b) not to assume the assertion is still valid based on date < expiration.

**Comment by jricher** [comment]
But the RPs should really only ever be using an assertion as a login event. After that, it folds over to session management (in -B). Using an assertion for a long period of time is problematic for all the reasons you mention, and we shouldn't encourage that behavior.

**Comment by iglazer** [comment]
I agree in principle but think about how people use access tokens today. I see way too many people issuing long lived tokens and assuming they are still valid up to the expiration date.

**Comment by jricher** [comment]
I would agree if we were talking about access tokens, but we're not -- these are more along the lines of ID tokens (and SAML assertions and Kerberos tickets). Access tokens should _never_ be taken as proof of a user's presence.

**Comment by iglazer** [comment]
Fair enough
