### ISSUE TITLE
RE: Protected Session definition -- inconsistent

### ISSUE THREAD

**Issue by wangxjnj** [usnistgov/800-63-3#522]
### All Fields Are Required
**Organization Name (N/A, if individual):** N/A

**Organization Type (see below for codes)**: 4
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 3 definition

A participant is said to be authenticated if, during the session, he, she or it proves possession of an authenticator in addition to the session keys, and if the other party can verify the identity associated with that authenticator. If both participants are authenticated, the protected session is said to be mutually authenticated.
**Comment (Include rationale for comment)**:
1.   Session keys are generated after authentication.  so the "in addition to" should be changed to" or" ?

**Suggested Change**:
1. change "A session wherein messages between two participants are encrypted and integrity is protected using a set of shared secrets called session keys."
to
"A session wherein both confidentiality and integrity of messages between two participants are protected using a set of shared encryption and MAC secrets called session keys. "

2. "in addition to" should be changed to" or"
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
A session typically exists in an unauthenticated state prior to authentication, so the proof of possession of authenticator(s) is indeed in addition to the session keys.
