### ISSUE TITLE
RE: surrender or prove destruction of any physical authenticator 

### ISSUE THREAD

**Issue by wangxjnj** [usnistgov/800-63-3#523]
### All Fields Are Required
**Organization Name (N/A, if individual):** N/A

**Organization Type (see below for codes)**: 4
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 6.3, 6.4
 The CSP SHALL require subscribers to surrender or prove destruction of any physical authenticator containing certified attributes signed by the CSP as soon as practical 
**Comment (Include rationale for comment)**:
 Not sure what the " certified attributes signed by the CSP" referring to. 

physical authenticator usually holds cryptic keys:
1. OTP hardware authenticator -- useless once expired, or unassigned/deleted at the CSP side(seed no longer valid)
2. crypt hardware device -- the key is also useless once the binding broken at the CSP side.
3. crypt device may hold multiple keys with multiple CSPs.  And the device may be an BYOD. 
**Suggested Change**:
 should not require subscribers to surrender or prove destruction of any physical authenticator. 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
An example of a physical authenticator with certified attributes signed by the CSP is the US Government PIV (personal identity verification) card. Since a PIV card carries attributes whose revocation may not be checked consistently, it is best to require surrender or destruction.
