### ISSUE TITLE
Appendix A.2 Length of Memorized Secrets

### ISSUE THREAD

**Issue by mliben** [usnistgov/800-63-3#526]
### All Fields Are Required
**Organization Name (N/A, if individual):**
N/A
**Organization Type (see below for codes)**:
 4
**Document (63-3, 63A, 63B, or 63C)**:
63B
**Reference (Include section and paragraph number)**:
 Appendix A.2
**Comment (Include rationale for comment)**:
 Add term "Passphrase" as It encourages longer Memorized Secrets
**Suggested Change**:
 All instances of "passwords" to "passwords and passphrases"

--
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Since "passwords" appears frequently in the section, we are instead adding a short paragraph at the beginning saying that it includes passphrases and PINs. This avoids the awkwardness that might result of all instances were changed as suggested.

**Comment by jimfenton** [comment]
Fixed by #529.
