### ISSUE TITLE
Appendix A Memorized Secrets

### ISSUE THREAD

**Issue by mliben** [usnistgov/800-63-3#527]
### All Fields Are Required
**Organization Name (N/A, if individual):**
N/A
**Organization Type (see below for codes)**:
 4
**Document (63-3, 63A, 63B, or 63C)**:
63B
**Reference (Include section and paragraph number)**:
 Section 3. Definitions and Abbreviations
**Comment (Include rationale for comment)**:
 The term "Passphrase" suggests the use of longer Memorized Secrets
**Suggested Change**:
 Add definition (from Wikipedia:)
"A passphrase is a sequence of words or other text used to control access to a computer system, program or data. A passphrase is similar to a password in usage, but is generally longer for added security."
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
With the added use of passphrase, definition has been adapted to the style used in the document and added to the definitions.
