### ISSUE TITLE
RE: Memorized Secrets: Password Vs PIN

### ISSUE THREAD

**Issue by wangxjnj** [usnistgov/800-63-3#528]
### All Fields Are Required
**Organization Name (N/A, if individual):** N/A

**Organization Type (see below for codes)**: 4
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 5.1.1. Memorized Secrets
 
**Comment (Include rationale for comment)**:
 5.1.1 is focused on the password.  It does  not say much about how the PIN should be used. PIN should not be used as an authenticator by itself.  Should only be used as the other factor in MFA: 1. unlock MF authenticator; 2.  with "what you have" just like the bio.
**Suggested Change**:
 1.  split 5.1.1 Memorized Secrets to "Memorized Secrets: Password", and "Memorized Secrets: PIN". Or
2.  create a new section in 5.2 General Authenticator Requirements: 5.2.x Use of PIN
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We treat PINS as an instance of a password, with special rules if the PIN is verifier generated.  Weak PINS (like 123456) would be caught by the dictionary requirements.
