### ISSUE TITLE
Public Draft (PDF) missing section in sp800-63b-draft.pdf 

### ISSUE THREAD

**Issue by Collaborator42** [usnistgov/800-63-3#539]
### All Fields Are Required
**Organization Name (N/A, if individual):IRS

**Organization Type (see below for codes)**:1
 
**Document (63-3, 63A, 63B, or 63C)**:63B

**Reference (Include section and paragraph number)**:Appendix A: Strength of Memorized Secrets, A.3. Complexity, A.4. Randomly-chosen Secrets,A.5. Summary
 
**Comment (Include rationale for comment)**: Appendix A: Strength of Memorized Secrets, A.3. Complexity, A.4. Randomly-chosen Secrets,A.5. Summary sections are missing from the public PDF on http://csrc.nist.gov/publications/drafts/800-63-3/sp800-63b-draft.pdf 
 
**Suggested Change**: Include the full documents (PDFs) for review on the NIST site (http://csrc.nist.gov/publications/PubsDrafts.html#SP-800-63-3). 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be reposted on csrc shortly.  Thanks for identifying this.
