### ISSUE TITLE
Clarification of combineable authentication factors 

### ISSUE THREAD

**Issue by hitoshikokumai** [usnistgov/800-63-3#546]
### All Fields Are Required
**Organization Name (N/A, if individual):** individual

**Organization Type (see below for codes)**:
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 5.2.3
 
**Comment (Include rationale for comment)**:  The guideline could provide the list of combinations of authentication factors that are allowed and not allowed so that there would be no room for misinterpretation.
 
**Suggested Change**:  For clarity's sake, the following list could be included at the end of 5.2.3.

Specifically, the following combinations are allowed.
1. Something possessed AND biometrics, with sensible retrials permitted for biometrics 
2.  [Something possessed AND biometrics] OR [Something possessed AND another biometrics] 
3.  [Something possessed AND biometrics]  OR  [Something possessed AND memorized secrets] 

The following combinations are not allowed. 
4.  [Something possessed AND biometrics] OR [another biometrics] 
5.  [Something possessed AND biometrics] OR [memorized secrets] 
6.  [Something possessed] OR [biometrics] 
7.  [Something possessed] OR [memorized secrets] 

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The allowable authenticator combinations are shown in section 4.2.1 (AAL2) and 4.3.1 (AAL3). 5.2.1 contains supplementary guidelines on biometrics; the allowable combinations are a more general concern and are therefore in the earlier section.

**Comment by hitoshikokumai** [comment]
You wrote "5.2.1 contains supplementary guidelines on biometrics;"  You meant "5.2.3", didn't you?

Anyway, I appreciate your confirmation that the earlier section override the later section.  Thanks.

**Comment by hitoshikokumai** [comment]
For record's sake, I could have added 8. [biometrics] or [memorized secrets] in my now-declined suggestion.

I did not mean that something was missing in your guideline but I just wished to help make the guideline as easy as possible to grasp with the least chance of misinterpretation.
