### ISSUE TITLE
Previously used memorized secrets

### ISSUE THREAD

**Issue by mbrancato** [usnistgov/800-63-3#547]
### All Fields Are Required
**Organization Name (N/A, if individual):**
N/A
**Organization Type (see below for codes)**:
 4
**Document (63-3, 63A, 63B, or 63C)**:
63B
**Reference (Include section and paragraph number)**:
10.2.1
**Comment (Include rationale for comment)**:
 The mention of previously used memorized secrets is only done in passing in 10.2.1.

> * Provide clear, meaningful and actionable feedback when chosen passwords are rejected (e.g., when it appears on a "black list" of unacceptable passwords or has been used previously). Advise users that they need to select a different secret because their previous choice was commonly used.

No guidance seems to be provided on required history to be stored. No requirement to store previously used secrets seems to be defined for any assurance level. No requirement to reject based on history seems to be defined for any assurance level.

5.1.1.2 leaves room for previously used secrets, but does not explicitly mention.

I'm not certain the current language prevents on a required change of a memorized secret, setting the secret to the same value. Effectively, not changing the secret.

**Suggested Change**:
Provide clear guidance or remove the example in 10.2.1.

Apply history requirements to subscriber-chosen secrets only.

Defined or suggest history requirements for each assurance level or for all memorized secrets in general.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Password history is used primarily to enforce the effectiveness of password change policies; without it, subscribers might alternate between two passwords whenever asked to change their password. But as it says in Section 5.1.1.2, "Verifiers SHOULD NOT require memorized secrets to be changed arbitrarily (e.g., periodically)..."  Accordingly, there is no requirement to store password history. There is also the concern that compromise of a stored password history might introduce additional vulnerabilities by revealing more of the subscriber's password choices.

The text in section 10.2.1 doesn't relate to password history, but to the list of commonly-used, expected, or compromised passwords described in paragraph of 5.1.1.2.

**Comment by mbrancato** [comment]
I don't disagree with most of your comment. However, I do think saying "might introduce additional vulnerabilities" is speculative on a user store compromise. I'd argue the whole thing is compromised at that point.

The meat of my comment was...

**I'm not certain the current language prevents on a _required_ change of a memorized secret, setting the secret to the same value. Effectively, not changing the secret.**

i.e. not periodic.

I ask that you address deliberate subverting of **required** password changes (evidence-based, not periodic) in this method through controls within the memorized secret change process.

Additionally, 10.2.1 explicitly refers to passwords "used previously" so the document still implies this without clear guidance through this example.
>Provide clear, meaningful and actionable feedback when chosen passwords are rejected (e.g., when it appears on a "black list" of unacceptable passwords or **has been used previously**)
