### ISSUE TITLE
To make sure that 2-factor authentications require both two to  pass

### ISSUE THREAD

**Issue by MassimoTornatore** [usnistgov/800-63-3#555]
### All Fields Are Required
**Organization Name (N/A, if individual):**individual

**Organization Type (see below for codes)**:
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 4.2 or 5.2.3
 
**Comment (Include rationale for comment)**: I know of many people who are misled to wrongly believe that biometrics operated with additionally-used passwords (fallback passwords) are providing the level of security higher than that of the password-only authentication although the opposite is the case.

An example is the fingerprint scanners operated on smartphones together with fallback pincodes.  The fact is that a smartphone with only a pincode login is more secure due to smaller "attack surface".

I also know of some people who, whether wittingly or not, call "biometrics operated with a fallback password" as a two-factor authentication. 

Consumers should be protected from such misinformation. (A recovery mechanism could be allowed where practicality matters.  But where the recovery mechanism is allowed, users should be expressly advised of its consequences.)

On the other hand, NIST expressly declared "At AAL2 and above, we require 2 factors and that both SHALL pass" in reply to my earlier suggestion #332. Clear enough.
 
**Suggested Change**: In view of the reality that many people are not free from a wrong interpretation of 2-factor authentication, 4.2 or 5.2.3 could explicity read "When referring to two-factor authentication, we require that both of two factors SHALL pass.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
4.2 is the better place for this because the need for both authentication factors is not specific to biometrics, and 5.2.3 deals with biometrics. Also adding to 4.3 for completeness (it's true at AAL3 as well).
