### ISSUE TITLE
Clarification for Identity Evidence 

### ISSUE THREAD

**Issue by jandrewh** [usnistgov/800-63-3#556]
### All Fields Are Required
**Organization Name (N/A, if individual):** AYIN International, Inc.

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: 800-63.3a "Definitions and Abbreviations" 
 
**Comment (Include rationale for comment)**: Though section 5.2 discusses comprehensively Identity Evidence initially we were challenged to find this content primarily due to industry taxonomy in the identity proofing genre designating "identification documents" as (e.g. drivers license, passport, permanent resident card etc...)   vs. the 63A new taxonomy as "identity evidence". 

The current definitions related to identity are:

Identity
A set of attributes that uniquely describe a person within a given context.

Identity Assurance Level (IAL)
A category that conveys the degree of confidence that the applicant’s claimed identity is their real identity.

Identity Proofing
The process by which a CSP collects and verifies information about a person for the purpose of issuing credentials to that person.

**Suggested Change**: Recommend adding a definition for "Identity Evidence" related to identification documents distinctive from PII.

"Ex. Identity Evidence 
     One or more Government issued or Official identification documents owned by the holder to support identity. (e.g. drivers license, passport, permanent resident card, birth certificate)"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other 2

**Comment by jweden** [comment]
I like this idea too and I (lightly) touched on why this is needed in #544.

**Comment by paul-grassi** [comment]
Will add a definition.  Please note, evidence can also be a digital credential (think derived credentials).  In addition, we will be coming out with an implementation guide that will actually list evidence that maps to each score to assist RPs and CSPs.  But even with that, a definition is a good thing.  Thanks!

**Comment by jandrewh** [comment]
Jason, I appreciate your comment and after reading #544 it makes perfect sense that account recovery should not diminish assurance. I also agree with your alignment with the Real I.D. Law and would include that as part of our contribution regarding "Identity Evidence". 

Paul as always I appreciate your support, work, and quick responses. Your comment about a digital credential or derived credential is interesting, in that, theoretically, the identity proofing would've been performed to acquire a digital or derived credential. Correct?

It seems you are suggesting that an already identity proofed digital or derived credential may be subsequently used as "identity evidence" for a subsequent identity proofing event. Or are you referring to an authentication event? 

Interesting supposition for digital or derived credentials being leveraged in identity proofing. Perhaps an attribute from a digital or derived credential for IAL or AAL elevation as necessary may be the necessity for a digital or derived credential in an identity proofing event. Either way very interesting CSP challenge. 

Gentlemen thanks again!
