### ISSUE TITLE
Define "bearer assertion"

### ISSUE THREAD

**Issue by sashorter** [usnistgov/800-63-3#558]
### All Fields Are Required
**Organization Name (N/A, if individual):** N/A

**Organization Type (see below for codes)**: 5
 
**Document (63-3, 63A, 63B, or 63C)**: 63C

**Reference (Include section and paragraph number)**: 5.1.1 and everywhere
 
**Comment (Include rationale for comment)**: The term "bearer assertion" is used frequently without being defined within the documents.  Various protocols (SAML Web Profile, OAuth, OpenID Connect) have "bearer" types, but can you provide a definition in case someone uses a protocol that didn't provide such convenient names?
 
**Suggested Change**:  Include protocol neutral definitions for "bearer assertion" and "holder of key assertion" in 63C.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
As you note, this is defined in detail in §5.1.1 but I don't see a problem with adding succinct definitions for this and Holder of Key assertions in the definitions section of -C.
