### ISSUE TITLE
Clarification on whether a table or a grid card look-up secret authenticator’s cell shall only be used successfully once with respect to lookup

### ISSUE THREAD

**Issue by SES-SSE** [usnistgov/800-63-3#56]
**Organization**: 1

**Reference (Include section and paragraph number)**:
5.1.2.2. Look-up Secret Verifiers

**Comment (Include rationale for comment)**:
5.1.2.2 states: A given secret from an authenticator SHALL only be used successfully only once; therefore, a given authenticator can only be used for a finite number of successful authentications.

It is not clear how this requirement would apply to a look-up table/grid card. If a cell is used just once, than only the remaining set of unused cells can be used for authentication.  If the requirement is referring to a specific grouping of cells that are used for authentication that can only be used once, then that could be difficult to track.  For example, if one has a 50 cell look-up table and is required to enter values from 3 cells, then the look-up table can only be used 16 times.  If cells are allowed to be used more than once, then a finite number wouldn’t be practical to track based on groupings.  Limits on the number of times the table/card is used would possibly be more advisable.

If the intent is that a cell only be used once, then please provide clarity.  If the intent is that a cell maybe used more than once, please state and provide guidance on lifetime of use.

**Suggested Change**:
## Clarify whether the requirement above applies to look-up tables/grid cards. If the requirement does apply to look-up tables/grid cards, clarify if a given cell can only be used one time or multiple times and how often the look-up table/grid card should be changed.

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
The intent is that grid card cells SHALL be used only once as well. In any case few, if any, US government agencies use grid cards, and this is the target audience for this document.
