### ISSUE TITLE
Update KBV definition

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#560]
### All Fields Are Required
**Organization Name (N/A, if individual):** Symbiotic Consulting Services Limited

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: 3. Definitions and Abbreviations
 
**Comment (Include rationale for comment)**: You have defined “Knowledge Based Verification”; however, I think this verification type needs to be differentiated to “Pattern Based verification” used for biometric authentication.
 
Knowledge based verification often involves the comparison of two discrete values (e.g. a salted password hashed multiple times).
 
Pattern based verification uses a combination of sensed stream of signals, e.g. iris scan, of the claimant to then undertake a “closeness” match of multiple features of a specific biometric modality.
 
**Suggested Change**: I think this verification type needs to be differentiated to “Pattern Based verification” used for biometric authentication.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
KBV is defined properly as a method to verify an identity using questions that supposedly only they would know.  It is not a biometric in the context of identity proofing and is not a valid authenticator as documented in 800-63B.
