### ISSUE TITLE
Blacklisting memorized secrets: optional or mandatory?

### ISSUE THREAD

**Issue by BrJu** [usnistgov/800-63-3#561]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Safran Identity & Security
**Organization Type (see below for codes)**:
 2
**Document (63-3, 63A, 63B, or 63C)**:
63B
**Reference (Include section and paragraph number)**:
 5.1.1.1. ; and 5.1.1.2. 5th paragraph
**Comment (Include rationale for comment)**:
 5.1.1.1 says that some memorized secrets choices may be disallowed, while 5.1.1.2 says "verifiers SHALL compare the prospective secrets against a list..."

Consequently, it is unclear whether comparison against a blacklist is mandatory or optional.  I assume this is optional as the list could be close to being empty (it seems difficult to define a concrete requirement on the quality of its content) and the verifier might not be able to check the value of the secret (e.g. if hashed on subscriber side).

**Suggested Change**: 
Change SHALL into SHOULD in the sentence "verifiers SHALL compare the prospective secrets against a list..."

Additionally, it should be clarified in the text what applies to chosen secrets and what applies to both chosen or randomly generated secrets.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Comparison against a blacklist is mandatory. We are changing the wording of 5.1.1.1. to make it clearer that it does not relax that requirement.

**Comment by BrJu** [comment]
If mandatory, then one should define some basic controls on the blacklist. Is there a requirement on its minimum content?

**Comment by jimfenton** [comment]
Section 5.1.1.2 says that the list "contains values known to be commonly-used, expected, or compromised," and we give some examples of that. We do not give a minimum size for the list, so that minimum does not become the requirement.

A quick analysis I (personally, not NIST) did suggested that ~100,000 entries is a ballpark estimate for a good blacklist size. https://www.slideshare.net/mobile/jim_fenton/toward-better-password-requirements

**Comment by paul-grassi** [comment]
As noted by @jimfenton we believe the guidance is sufficient.  We are balancing outcomes with prescription, and this is one where agencies are best to make their own risk-based determination.  In addition, this allows industry to innovate and offer the best solutions possible.
