### ISSUE TITLE
Biometric EER requirement

### ISSUE THREAD

**Issue by kwilson997** [usnistgov/800-63-3#567]
### All Fields Are Required
**Organization Name (N/A, if individual):** iBeta Quality Assurance

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 5.2.3
 
**Comment (Include rationale for comment)**: The statement: **Empirical testing of the biometric system to be deployed SHALL demonstrate an EER of 1 in 1000 or better with respect to matching performance**. 
Does any biometric system demonstrate an EER of 1 in 1000?
This document is a security document and should not concern itself with usability issues. The EER, where FNMR = FMR relates to the FNMR, which is a usability issue. The security operating point is the FMR, the requirement for which is supplied in the next sentence: **The biometric system SHALL operate with an FMR of 1 in 1000 or better**

 
**Suggested Change**: 
change EER to FMR or FAR. Since the following sentence references FMR, FMR is recommended.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by BrJu** [comment]
I agree with this comment. EER requirement is too strong as it is in the draft. And, although usability is important, setting a maximum EER does not really make sense with respect to security objectives.

**Comment by jimfenton** [comment]
The critical criterion is, of course, the FMR from a security standpoint, so the text will be reworded to emphasize that. However, it will also point out that the FNMR can't be _too_ bad; otherwise, the limit on failed tries will kick in and make the biometric ususable.
