### ISSUE TITLE
Confirming use of "allowed" + general comment

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#569]
### All Fields Are Required
**Organization Name (N/A, if individual):** State Department

**Organization Type (see below for codes)**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 63-3

**Reference (Include section and paragraph number)**: Table 5-2 Cell for intersection of Row IAL3 and Column AAL2
 
**Comment (Include rationale for comment)**: Value of “allowed” is a significant change from previous versions.  Would like to validate this is correct.

General Comment:  Bravo on a really substantive updated draft of this entire suite of documents.  Addition of the flowcharts for determining IAL and AAL is very helpful.  Focus on privacy and EO 13681, with the consequent ability to now “mix and match” IAL and AAL to meet business needs really potentially makes life easier and cheaper for the G2B and G2C sectors.  Great steps on driving down IAL and minimizing collection of PII and/or using assertion claims rather than data items.  Consideration of transient collection of PII, pseudonymity, and overall evaluation of the backend process is great.  Addition of usability section is also welcomed, however generic it may be so far.
 
**Suggested Change**: N/A
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This new model of combining distinct xAL's is use cases specific.  If the use case is getting a PIV card, then IAL1/AAL3 would not be appropriate - so the RP would pick IAL3/AAL, which is allowed per this document.

If the use case is pseudonymous but strong auth required (perhaps self-asserted data is still high risk, like PHR) then then RP should pick IAL1 and AAL2 or 3, now also allowed in this document.
