### ISSUE TITLE
biometric device is ambiguous

### ISSUE THREAD

**Issue by kwilson997** [usnistgov/800-63-3#570]
### All Fields Are Required
**Organization Name (N/A, if individual):** iBeta Quality Assurance

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 4.2.1 para 4 Note:
 
**Comment (Include rationale for comment)**: Although the intent is probably clear from the context of the statement, the statement assumes that the biometric reading device is in possession of the claimant. That may not be true, as the biometric reader may be associated with the station such as at a port of entry.
 
**Suggested Change**:
 change "Therefore, it is unnecessary..." to "Therefore, it may be unnecessary..." 
**OR**
otherwise clarify the previous sentence to include "by using the claimant's device"
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
A biometric reader at a station such as a point of entry is outside the scope of this specification; this application is not considered remote authentication (see SP 800-63-3 Section 2 paragraph 2).
