### ISSUE TITLE
63B wording suggestions/corrections, elaboration needed on CSPs validating the existing assurance level of a subscriber-provided authenticator, and biometrics under Duplication threats

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#572]
### All Fields Are Required
**Organization Name (N/A, if individual):** State Department

**Organization Type (see below for codes)**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: Listed below with corresponding comments.
 
**Comment (Include rationale for comment)**:
Section 2, Paragraph 1, last sentence: Sentence fragment starting with “of which.”  Disconnected antecedent, combine.

Section 4.1.2, Paragraph 1: Help to clarify “the platform in which they are running” as the claimant/subscriber system, i.e. user system hygiene (or other remote end).

Section 4.1.5: Recommend adding “and inform subscriber” (with consent?)

Section 5.1.1.2, Paragraph 4: “Memorized secret verifiers” I get it, but it would be clearer to say “verifiers of memorized secrets”.

Section 5.1.4.2, Paragraph 2: Unclear why this reference to multi-factor OTP appears in the section on single factor OTPs.

Section 5.1.5.1, Paragraph 2: “The authenticator output SHALL have at least 6 decimal digits of entry.”  Mixing requirements here, for PIN, yes 6 decimal digits, otherwise state entropy requirements in bits.

Section 6.1.3: Documents don’t say much about how a CSP validates the existing assurance level of a subscriber provided authenticator.  Yes, it’s generically covered in document proofing standards in 63A, but it’s still vague.  Could use some elaboration somewhere.

Table 8-1, cell at intersection of row “duplication” and column “examples”: Granted, a biometric cannot be a primary authenticator, but insofar as it may be a co-factor in two-factor authentication (i.e., smartcard unlock), there’s a threat here too.  Or is the absence of reference a concession that there is no mitigation available (except perhaps tests for “liveness.”)

Section 8.2, sentence immediately following Table 8-2: Reference to table 5 is incorrect.  Update it.
 
**Suggested Change**: N/A
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Thanks for your comments. Responses to a couple of them:

5.1.1.2: We are opting for consistency with other authenticators with the wording of this section heading. Your suggested wording is a bit smoother, but the existing wording is accurate.

5.1.4.2: Already fixed by #510.

5.1.5.1: This points out a larger issue of consistency with 5.1.4.1. The two sections should be consistent except that 5.1.5.1 also discusses the ways in which a multifactor OTP device are activated.
