### ISSUE TITLE
Add to section 5.2 guidance on secure PIn and secure display

### ISSUE THREAD

**Issue by skswave** [usnistgov/800-63-3#581]
### All Fields Are Required
**Organization Name (N/A, if individual):** Rivetz Corp.

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 63b

**Reference (Include section and paragraph number)**: Section 5.2 general guidance
 
**Comment (Include rationale for comment)**:

One of the most powerful technologies that has been available on hardware over the last 7-8 years has been secure display and secure input. Technology by Intel that is part of over 900 millin PCs and technology from ARM and Global platform Trusted User Interface 1.0 TUI that is part of a billion platforms and fully enabled on 70 -80 million current devices.  

Section 5.2 provides guidance on biometrics as a user to device binding it would seem that a nod to Trusted PIN entry would also be good. The goal is to help device manufacturers understand the benefits and to identify that TUI is probably as useful or more useful for real security than Biometrics and in most cases the technologies paly incredibly well together. Areas that could be touched on.

Secure Display can be used to create secure PIN entry by randomizing the position of the inputs to reduce the risk of capturing a PIN though mouse clicks or touch screen data capture

TUI should be used if available to provide the is a user present functionality required for higher assurance access to the keys similar to the button push model on a USB token

If trusted display should be used if available to assure an authentication request is from the relying party and any details of a transaction could be confirmed.

Trusted Input should be used if available for the initial binding of the device to the service provider to assure the integrity of One time Use registration keys.

Trusted Input should be used if available to secure the trusted Input of recovery data to reduce risk of data stolen in the process. 

TUI could be used to secure the review and or entry of PII data as part of the enrollment process. this would prevent most device malware theft of PII data. 

TUI could be used to Display the 6 digit codes with significantly reduced risk of theft. 

Thank you for your consideration of this area

Steven Sprague
 
**Suggested Change**:
 I have tried to summarize a few of the concepts above and i think the NIST team is in a stronger position to define language that would incorporate TUI and secure display as important in the user to device binding to collect the intent that a user permissions the use of Keys for authentication. 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Trusted input and secure display are good mitigations for eavesdropping threats. Accordingly, it's appropriate to include them as threat mitigations in Table 8-2.
