### ISSUE TITLE
Issuing Source for verification

### ISSUE THREAD

**Issue by kcrowl11** [usnistgov/800-63-3#582]
### All Fields Are Required
Experian

2
 
63A

5.2.2.1
 
According to the requirement for "Strong", "All personal details and evidence details have been confirmed as valid by comparison with information held or published by the issuing source". The capability does not currently exist to the Industry today to take information from a document such as a Driver's License or Passport and verify that data directly against the issuing source. Most document verification technologies available today are able to validate that the technical components of the document (i.e watermarks, holograms, fonts, location of text, etc.) are consistent with the proper structure by using templates provided from the various states or state agencies but do not provide the ability to verify the PII data contained on the document directly against the issuing source. We are aware of an organization that is attempting to create such a repository for state driver's license data, but this is currently incomplete (less that 20% currently participate) and with the Driver's Privacy Protection Act (DPPA) would seem to restrict the state's willingness to participate in sharing this information.
 
Can NIST either provide further clarification on this requirement or allow industry to use an authoritative source for verification of PII information contained in the document? Using an authoritative source allows verification of the PII using validated and verified data to confirm that the PII information is accurate wile still allowing the document verification technology to verify the validity of the document.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We will work on an outcome/characteristic based definition that expands beyond issuing source.
