### ISSUE TITLE
Consequenses of Adding Recovery Mechanism on Security as against on Practicability

### ISSUE THREAD

**Issue by hitoshikokumai** [usnistgov/800-63-3#583]
### All Fields Are Required
**Organization Name (N/A, if individual):** Individual

**Organization Type (see below for codes)**:
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 5.2.3
 
**Comment (Include rationale for comment)**: In #559 suggestion, the contributor wrote "Remark: This suggestion has nothing to do with the fact that a smartphone equipped with biometrics authentication and a fallback password authentication as a recovery mechanism is obviously less secure than a smartphone with only a pincode authentication due to the larger attack surface."

NIST could expressly add this kind of observation to 5.2.3 so that the consequences of adding a recovery mechanism on the security as against on the practicability will be made clear enough, leaving no room for a  possible misinterpretation that the fallback password works as the third security factor for enhancing security.
 
**Suggested Change**:  5.2.3 could include a footnote to the effect that a smart device equipped with biometric authentication and a fallback password authentication as a recovery mechanism provided in case of false rejection by the biometrics is less secure than a smart device with only a password authentication due to the larger attack surface generated by the addition of the recovery mechanism. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Quoting comment originally made in #559:

Your logic would be valid if the threats against biometrics and against passwords or PIN codes are the same, but they aren't. For example, when I'm in a public place, the option to do biometric authentication denies a potential attacker the ability to learn my PIN through "shoulder surfing", after which they could snatch my phone. In this way, security is enhanced.

It's therefore not clear that the footnote you suggest is entirely accurate, and it's also not clear what it is recommending other than possibly to discourage the use of biometrics. There are also a number of places where the document suggests the registration of multiple authenticators, which might also be considered to weaken authentication since any of them could be used. But their availability avoids the need for simple "account recovery" methods that are often the weak spot in authentication. Their availability can therefore enhance overall security.

**Comment by hitoshikokumai** [comment]
It appears that you closed this thread by misunderstanding.  

There are three areas where I would appreciate your good thoughts; (1) Inherent characteristics of a two-door house as against a one-door house, (2) Nonexistent effects on account recovery and (3) Meaningless comparison between passwords and biometrics.

(1) Here is a 30second video.　 https://youtu.be/7UAgtPtmUbk

Please assume that the first door, which is common to both houses, is the password and the second door, which is unique to the two-door house, is the biometrics.  The second door could be far stronger or far weaker than the first one.  Whichever the case, a two-door house is always less secure than a one-door house because of the always larger attack surface.
 
I am of the view that there is no way of finding a case that a one-door house is less secure than a two-door house against burglars, and the same applies to the one-door smartphone as against the two-door 
smartphones.

(2) The difference between Model A smartphone (authenticated by pincode) and Model B smartphone (authenticated by biometrics with a fallback piincode) does not have any positive or negative effect on the reliability of account recovery.  Pincode authentication is common to both models.

I reckon that it is not appropriate to raise the issue of the account recovery with respect to the evaluation of Model A as against Model B.

(3) There is no way of judging which of the shoulder-surfing of the user’s password input and the collection of the user’s fingerprints from the users' devices or photos is safer or less safe than the other.  

It should also be noted that we can manage a relatively stronger password when we recall it frequently, whereas the password that we recall occasionally only when falsely rejected by biometrics tends to be 
very weak.  In other words, biometrics could well drive users to register the easiest-to-recall easiest-to-break passwords. 

Generally speaking, it is not possible to compare the strength of biometrics operated on its own with that of a password operated on its own.  There are (or could be) no objective data about the overall 
vulnerability of biometric solutions (not just false acceptance rate when false rejection is near-zero but also the risk of forgery of body features, the risk of use when the user is unconscious and leakage) and 
that of the passwords (not only that it may be as low as 10 bits or as high as 100 bits but also that it can be shoulder-surfed, otherwise stolen and leakage.)

I believe that we should build our discussions without involving such futile comparisons.

As such I would appreciate if you could give a further consideration on the above discussions.  I hope you will opt to reopen this thread for continued discussions.

**Comment by hitoshikokumai** [comment]
I am of the view that we can confidently state that Model A is securer than Model B.  Should you not be so confident, however, you would agree that it could be safely stated that it is not correct to claim, whether 
explicitly or implicitly, that Model B is securer than Model A.  

This kind of footnote is indispensable in the guidelines in view of the observation that so many people including a number of media wrongly believe that Model B is securer than Model A.
