### ISSUE TITLE
ADEQUATE Evidence Requirements

### ISSUE THREAD

**Issue by drfitzpatrick** [usnistgov/800-63-3#584]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Partners HealthCare
**Organization Type (see below for codes)**:
 5
**Document (63-3, 63A, 63B, or 63C)**:
63A
**Reference (Include section and paragraph number)**:
 4.7 Table 4.3
**Comment (Include rationale for comment)**:
A strength of 'ADEQUATE' is used when describing the Evidence Requirements however the strengths listed in Tables 5.1, 5.2, and 5.3 are categorized as 'Unacceptable, Weak, Fair, Strong, and Superior'
**Suggested Change**:
 Either clarify the definition of an 'ADEQUATE' strength requirement or replace 'ADEQUATE' with a term listed in Table 5.1, 5.2, and 5.3.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Resolved by #518
