### ISSUE TITLE
Missing Definitions

### ISSUE THREAD

**Issue by adamshane** [usnistgov/800-63-3#588]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**: 4
 
**Document (63-3, 63A, 63B, or 63C)**: 63-3

**Reference (Include section and paragraph number)**: 3
 
**Comment (Include rationale for comment)**: There are several terms and abbreviations used in the document that are not defined.
 
**Suggested Change**: Add the following terms and abbreviations into section 3.
- Authoritative Source
- Claimed address
- Derived Credential
- Enrollment
- Issuing Source
- Knowledge Based Verification (KBV)
- Practice Statement
- Protected Session
- Pseudonym
- RA
- Social Engineering
- Token
- Trust Anchor
- Virtual In-Person Proofing
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We will likely collapse definitions from all 4 into 1.  This will get resolved then.

**Comment by paul-grassi** [comment]
Resolved via merge of definitions into single doc.
