### ISSUE TITLE
Definition of MFA

### ISSUE THREAD

**Issue by adamshane** [usnistgov/800-63-3#589]
### All Fields Are Required
**Organization Name (N/A, if individual):** 

**Organization Type (see below for codes)**: 4
 
**Document (63-3, 63A, 63B, or 63C)**: 63-3

**Reference (Include section and paragraph number)**: 3
 
**Comment (Include rationale for comment)**: Definition of Multi-Factor Authentication (MFA) does not clearly indicate if this is multiple orthogonal factors or multiple factors of the same type is also acceptable.
 
**Suggested Change**: Clearly indicate how MFA is intended to be used.  There are applications of both multiple factors of same type and multiple orthogonal factors.  In other documents where normative sections use the term MFA this distinction becomes critical.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by twbaldridge** [comment]
I second this suggested change, it must be clear that the MFA is an extension of two-factor, where the term MFA (Multi-Factor Authentication) specifically indicates two or more orthogonal authentication factors. While multiple occurrences of the same type factor in a particular authentication does increase entropy, it does not increase the number of factors.

**Comment by lachellel** [comment]
I **third** this suggest change.  Saves us from submitting it separately (was on our suggestion list for feedback!). 

Example:  

- Multi-factor authentication by general industry definition and in other documents could be UN/PWD + UN/PWD (two sets of passwords / "what you know" strung together)
- Two-factor authentication is two or more factors

**Comment by jimfenton** [comment]
-63B Section 4.2 says, "Proof of possession and control of two different authentication factors is required..." Note that it doesn't say "two different authenticators" but "two different authentication factors". But perhaps we need to be clearer about that.

In any case, if you go through the different authenticator types in 4.2.1 and 4.3.1, it should be clear that you always need an authenticator that is _something you have_.

I have never heard multi-factor being described differently from two-factor before (except that multi-factor might, I suppose, include use of three factors). This "general industry definition" that multi-factor allows multiple instances of the same factor is, in my personal opinion, harmful.
