### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by adamshane** [usnistgov/800-63-3#590]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**: 4
 
**Document (63-3, 63A, 63B, or 63C)**: 63-3

**Reference (Include section and paragraph number)**: section 2, first paragraph, last sentence.
 
**Comment (Include rationale for comment)**: "Of which exists..." is not a complete sentence.
 
**Suggested Change**: Change sentence to "The use of an open network presents multiple opportunities for impersonation and other attacks to fraudulently claim another subject's digital identity."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Same correction as needed from #572 / #579, except needed in -63-3 as well.

**Comment by paul-grassi** [comment]
@jimfenton I'll take -3 if you want to apply to the other docs.

**Comment by jimfenton** [comment]
I thought the other docs were already addressed by #579

**Comment by paul-grassi** [comment]
Resolved via April 1 update to -3.
