### ISSUE TITLE
Personal Identity Verification

### ISSUE THREAD

**Issue by adamshane** [usnistgov/800-63-3#591]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**: 4
 
**Document (63-3, 63A, 63B, or 63C)**: 63-3

**Reference (Include section and paragraph number)**: General
 
**Comment (Include rationale for comment)**: There are several references to Federal Government and Agencies, yet no mention of the the PIV program, FIPS 201 or SP800-73.  The PIV program is tied to the use of Identity Proofing and digital identity and it seems odd not to mention it.
 
**Suggested Change**: Address PIV where appropriate.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
PIV is mentioned in -63-3 section 5.3, -63A section 6, and -63B section 6.4 (including reference to FIPS 201).
