### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by adamshane** [usnistgov/800-63-3#593]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**: 4
 
**Document (63-3, 63A, 63B, or 63C)**: 63-3

**Reference (Include section and paragraph number)**: Section 4.1, second paragraph, fourth sentence.
 
**Comment (Include rationale for comment)**: missing word
 
**Suggested Change**: Change phrase, "... an entity known as the RA or identity manager (IM)." to "... an entity known as **either** the RA or **the** identity manager (IM)."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
I would also spell out registration authority (RA).

**Comment by paul-grassi** [comment]
@jimfenton I'll take this given the other changes I am making to -3.
