### ISSUE TITLE
800-63C Editorial Comment - Section Title

### ISSUE THREAD

**Issue by jim-thomson** [usnistgov/800-63-3#602]
### All Fields Are Required
**Organization Name (N/A, if individual):**MITRE

**Organization Type (see below for codes)**:5
 
**Document (63-3, 63A, 63B, or 63C)**:63C

**Reference (Include section and paragraph number)**:5
 
**Comment (Include rationale for comment)**:Section 5 is titled "Assertions" and begins with "An assertion …" Section doesn't stand alone as well as it might.

 
**Suggested Change**:Change title to "Authentication Assertions". Consider changing at least the first line to "An authentication assertion" with the understanding that further references assume the longer name.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
We explicitly define assertion within the scope of this document as:

> 
> Assertion
> 
> A statement from a verifier to an RP that contains identity information about a subscriber. Assertions may also contain verified attributes.

Thus they are already bound to the authentication transaction. That said, I wouldn't be against tweaking the first line to read "An assertion used for authentication", but not change other instances.
