### ISSUE TITLE
Pairwise Identifier Subsection

### ISSUE THREAD

**Issue by jim-thomson** [usnistgov/800-63-3#604]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**:4
 
**Document (63-3, 63A, 63B, or 63C)**:63C

**Reference (Include section and paragraph number)**: 5.2.6
 
**Comment (Include rationale for comment)**: Section 5.2.6 would seem to be subservient to Section 5.2.5. 5.2.6 discusses a process that pertains only to the subject of Section 5.2.5.
 
**Suggested Change**: Change to 5.2.5.1
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
I'm against singular subsections.  It's like having one-bullet.  But I am open to this being subsumed. @jricher ?

**Comment by jricher** [comment]
I'm not a fan of singular subsections either. We pulled this content into a separate section so that it would be referenceable apart from its parent component. I see no harm in having it be a same-level section as 5.2.6, but would be fine with it being demoted to 5.2.5.1.
