### ISSUE TITLE
63C Section 7 Wording

### ISSUE THREAD

**Issue by jim-thomson** [usnistgov/800-63-3#606]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**:4
 
**Document (63-3, 63A, 63B, or 63C)**:63C

**Reference (Include section and paragraph number)**: Section 7, Paragraph 3
 
**Comment (Include rationale for comment)**: The third paragraph begins with "This table presents different requirements …". These would seem to be solutions or implementations.
 
**Suggested Change**: Consider changing word in the paragraph and Table 7-1 column heading to "Implementation"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
These are requirements for the implementations to adhere to. Whatever the chosen implementation, it must have, eg, at least a bearer token and RP-target encryption at level 2.

**Comment by paul-grassi** [comment]
What @jricher said.
