### ISSUE TITLE
63C Awkward Sentence

### ISSUE THREAD

**Issue by jim-thomson** [usnistgov/800-63-3#608]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**:4
 
**Document (63-3, 63A, 63B, or 63C)**: 63C

**Reference (Include section and paragraph number)**: 9.2, paragraph 1
 
**Comment (Include rationale for comment)**: The first paragraph ends with "However, an effective notice is never only a link that leads to a complex, legalistic privacy policy or general terms and conditions that a substantial number of subscribers do not read or understand." Sentence is awkward.
 
**Suggested Change**: Change to "However,  a link to a complex, legalistic privacy policy or general terms and conditions that a substantial number of subscribers do not read or understand is never an effective notice.".
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by nbl-nist** [comment]
I accept this change.

-------- Original Message --------

**Comment by paul-grassi** [comment]
@nbl-nist @jamiedanker-nppd I'll make the change since I am grabbing up the editorial changes for -C.
