### ISSUE TITLE
Singular They

### ISSUE THREAD

**Issue by jim-thomson** [usnistgov/800-63-3#609]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**:4
 
**Document (63-3, 63A, 63B, or 63C)**: 63C

**Reference (Include section and paragraph number)**: Throughout
 
**Comment (Include rationale for comment)**: Extensive use of the singular they construct, as in "the user identified themselves using their authenticator." This singular / plural mismatch is common is speech, but less common in formal writing. I could not find a NIST style guide, so I cannot tell whether singular they is now acceptable.
 
**Suggested Change**: Whether NIST style guide allows singular they or not, revisit all sentences using "they", "their", "themselves" etc. to consider rewiring to avoid both singular they and the also awkward "s/he", "he or she" and alternating use of "he" and "she. 

If accepted, apply this throughout the 800-63 suite.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
We are going with the singular "they" but as you point out haven't caught that everywhere.
