### ISSUE TITLE
Federation levels do not represent the strength of the IdP assertion protection

### ISSUE THREAD

**Issue by LarryFrank** [usnistgov/800-63-3#610]
### All Fields Are Required
**Organization Name (N/A, if individual):**
N/A
**Organization Type (see below for codes)**:
 Self
**Document (63-3, 63A, 63B, or 63C)**:
63C
**Reference (Include section and paragraph number)**:
 7.1
**Comment (Include rationale for comment)**:
 The discussion seems to assume that all assertions are at common strength "approved cryptography" but nowhere does it discuss the protection of the cryptographic keys of the IdP.  Is it OK to accept an LOA 4 assertion that is signed with what is essentially an "AAL 2" mechanism.
**Suggested Change**:
To meet LOA4, the security of the IdP key used to sign the assertions must meet the same AAL3 level of security as authenticator it sends.   
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
These are two very different uses for keys. Keys used to prove presence of a user need to be unlocked interactively by the user at higher levels. However, what does that mean for the keys used for an IdP? Does there need to be an administrator sitting at the IdP's console to manually unlock its keystore every time a user (who isn't the administrator) needs to log in? 

The IdP's keys obviously do need to be stored and protected appropriately, but how exactly that happens is dependent on the implementation and deployment of the IdP software. We do already implicitly require this in §7.1:

> At any FAL, the IdP SHALL ensure that an RP is unable to impersonate the IdP at another RP by protecting the assertion with a signature and key using approved cryptography.

**Comment by LarryFrank** [comment]
> These are two very different uses for keys.

Agree - the security of the IdP's keys is actually of greater concern than a single user's key.  I read the statement in 7.1 as providing some protection against replay - but not specifying any requirement related to the protection of the IdP's keys.  "Appropriately" is a very ambiguous term when it comes to security of keys.  Appropriate in whose opinion - since it is unlikely the RP actually gets to review the practices of the IdP.

I am not suggesting manual unlocking of the IdP key - but, like a CA, the IdP can have specific security requirements related to the security of the keys (e.g., FIPS 140-2 level 2 hardware).

**Comment by jimfenton** [comment]
Given that we impose FIPS 140 requirements on verifiers (in -63B), it makes sense to have comparable requirements on the protection of private keys by the IdP here.
