### ISSUE TITLE
Use of the word "yesterday" may be limiting.

### ISSUE THREAD

**Issue by kcsapersona** [usnistgov/800-63-3#612]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**: 4
 
**Document (63-3, 63A, 63B, or 63C)**: 63-3

**Reference (Include section and paragraph number)**: The sentence in review here is located in three placed and is identical in all three places.
Executive Summary, Paragraph 2
For services in which return visits are applicable, successfully authenticating provides reasonable risk-based assurances that the subject that is accessing the service today is the same as that which accessed the service yesterday.

SP 800-63B Authentication and Lifecycle Management, Paragraph 1
For services in which return visits are applicable, a successful authentication provides reasonable risk-based assurances that the subscriber that is accessing the service today is the same as that which accessed the service yesterday.

2. Introduction, Paragraph 1
"For services in which return visits are applicable, successfully authenticating provides reasonable risk-based assurances that the subject that is accessing the service today is the same as that which accessed the service yesterday."
 
**Comment (Include rationale for comment)**:
Generally the concept of "time" is extreemly important to security. In the reference document sentence under this review, the use of the word "yesterday" implies time, but is rather specific and implies only a single day of time, when in reality a security policy may be looking back in time more than one day or even less than a day. 
 
**Suggested Change**: I would suggest to reword the sentence to something along these lines: "For services in which return visits are applicable, successfully authenticating provides reasonable risk-based assurances that the subject that is accessing the service today is the same as that which accessed the service within an acceptible time-frame ranging from a few minutes to many days as determined by the risks associated with the transaction being executed."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Good catch, that phrasing could be interpreted as too specific. I believe that "yesterday" could be changed to "previously" and capture the intent of the original text in all of these cases. I don't think any additional explanation or time bounds are warranted.

**Comment by kcsapersona** [comment]
Justin:
“previously” works and is a much simpler edit.
Agreed.

Kelly Sparks  -  CEO  |   aPersona  |  ksparks@apersona.com<mailto:ksparks@apersona.com>  |  www.apersona.com<http://www.apersona.com/>

**Comment by paul-grassi** [comment]
Accepted per the agreed upon 'previously'.
