### ISSUE TITLE
Broading the "mechanisms" examples for the sake of better guidance.

### ISSUE THREAD

**Issue by kcsapersona** [usnistgov/800-63-3#613]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**: 4
 
**Document (63-3, 63A, 63B, or 63C)**: 63-3

**Reference (Include section and paragraph number)**: 4. Digital Identity Model/4.1. Overview - Paragraph 8

As part of authentication, mechanisms such as device identity or geo-location may be used to identify or prevent possible authentication false positives.
 
**Comment (Include rationale for comment)**:
The wording "such as device identity or geo-location" are good examples, but for the sake of guidance, more examples would be helpful I believe to the readers. 
 
**Suggested Change**: I would suggest to reword the sentence to something along these lines: "As part of authentication, mechanisms such as device identity, geo-location, specific IP's, application level behavior, or combinations of one or more of these mechanisms previously used within a given time period may be used to identify or prevent possible authentication false positives."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
It's not possible to give an exhaustive list here, and the context is that these mechanisms don't directly increase the AAL, so I'm not sure there's much benefit from a more comprehensive list.

**Comment by kcsapersona** [comment]
Jim:
I certainly understand. In general, the use of additional mechanisms increases assurances to some degree, and the more you have over a shorter time period the better the assurance.
For example, even if a Level2 ID & Password is used for authentication, if the same device “and” IP address are present, there is a bit more assurance than if IP alone was present.
In addition, if the time period of the mechanism is shorter, than that also improves assurances. E.g. we have seen this ID, PWD, Device and IP used previously in the last 24 hrs.

The two concepts were what I was striving for: A) the more you have the better &  B) The shorter the time-frame the better.
Considering the fact that with Level2 (ID and Pwd alone) includes the entire globe of all 6B devices and every IP in the world, I’d say that a limit to a single device and a single IP validated in the past few days is a bit better.

In fact, given the massive data-breaches and credential reuse, we  generally conclude that Level 1 and Level 2 are essentially worthless without additional factors/mechanisms to narrow the threat landscape. I believe this is what you are communicating by including the additional mechanisms in the first place otherwise there would be no need to mention them at all.

I sincerely appreciate the work you guys are doing. Just adding in my 2 cents! ☺
Very Best,
Kelly

Kelly Sparks  -  CEO  |   aPersona  |  ksparks@apersona.com<mailto:ksparks@apersona.com>  |  www.apersona.com<http://www.apersona.com/>
