### ISSUE TITLE
Clarify mapping in the table

### ISSUE THREAD

**Issue by mstrock** [usnistgov/800-63-3#614]
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 63-3

**Reference (Include section and paragraph number)**: Section 2.4, table 2-1 
 
**Comment (Include rationale for comment)**: The table shows two different mappings for AAL/IAL1 to other standards and guidelines.
 
**Suggested Change**: Either delete the incorrect table entry OR add a footnote explaining why there are two different mappings possible.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
2 entries are correct, but the mapping is wrong.  It should be that AAL/IAL2 maps to the other Level 2 entries, not AAL/IAL1.  Good catch.
