### ISSUE TITLE
Position of the first green "GO" symbol is incorrect

### ISSUE THREAD

**Issue by mstrock** [usnistgov/800-63-3#615]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: Section 4.1, figure 4-1
 
**Comment (Include rationale for comment)**: The position of the first green 'GO' symbol is incorrect assuming the figure represents the three IAL levels. IAL 1, as defined in paragraph 4.1, does not require resolution. 
 
**Suggested Change**: Move the symbol so it appears on the vertical line between enrollment and resolution AND denote the three symbols represent the three IAL levels for clarity.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
@mstrock thanks for all the great comments.  I think we will make a different change, but a change nonetheless to make this clearer.  Watch for a PR to see if the graphic update suits you.
