### ISSUE TITLE
"Shall" and "as applicable" are contradictory (section 4.2, item 13.b)

### ISSUE THREAD

**Issue by mstrock** [usnistgov/800-63-3#617]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: Section 4.2, item 13.b
 
**Comment (Include rationale for comment)**: “SHALL” indicates this requirement is to be followed strictly in order to conform to the publication and from which no deviation is permitted. "As applicable" leads a reader to believe there are situations where this is not required.
 
**Suggested Change**: Change "SHALL" to "MAY" and describe the conditions where this would not be required OR delete "as applicable".
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
If accepted, we should also fix rendering issues.

**Comment by paul-grassi** [comment]
@mstrock we understand your point, but it is important to us to reaffirm these statements, even if they may not be triggered by every system being built.
