### ISSUE TITLE
Unclear requirement (4.4.1.6)

### ISSUE THREAD

**Issue by mstrock** [usnistgov/800-63-3#621]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: Section 4.4.1.6, last bullet
 
**Comment (Include rationale for comment)**: This requirement is unclear: "address of record that is not physical mail" is confusing.
 
**Suggested Change**: Change this bullet to read "The CSP SHALL ensure the enrollment code and notification of proofing are sent by the different means. For example, if the CSP sends an enrollment code to a mobile phone of record, a notification of proofing will be sent to the physical address in records or obtained from validated and verified evidence, such as a driver’s license."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Also resolve #624 with this one.
