### ISSUE TITLE
Clarify the distinction between evidence quality and the strength of validation methods (4.5.3)

### ISSUE THREAD

**Issue by mstrock** [usnistgov/800-63-3#623]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: Section 4.5.3, general
 
**Comment (Include rationale for comment)**: Clarify the distinction between evidence quality and the strength of validation methods. Language is inconsistent within this section and in section 5.2 which this section references.
 
**Suggested Change**: Change the title of this section to read "Evidence Quality Requirements" AND change the line below the title to read "See Section 5.2.2, Identity Evidence Quality Requirements, for more information."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Consistent with #626 and #627

**Comment by paul-grassi** [comment]
Closed via: https://github.com/usnistgov/800-63-3/pull/1663
