### ISSUE TITLE
Clarify the distinction between identitification evidence quality and evidence validation strength (5.2.2)

### ISSUE THREAD

**Issue by mstrock** [usnistgov/800-63-3#626]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: Section 5.2.2, general
 
**Comment (Include rationale for comment)**: Clarify the distinction between identitification evidence quality and evidence validation strength. Clarifying this heading will help to distinguish between the two.
 
**Suggested Change**: Change the title to read "Validating Identity Evidence Strength".
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via: https://github.com/usnistgov/800-63-3/pull/1663
