### ISSUE TITLE
Clarity to strength of identity evidence validation (5.2.2.1)

### ISSUE THREAD

**Issue by mstrock** [usnistgov/800-63-3#627]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: Section 5.2.2.1, general
 
**Comment (Include rationale for comment)**: This sentence can be confused with identification evidence quality. This sentence needs to clearly address the strength of identity evidence validation.
 
**Suggested Change**: Change the sentence to read "Table 5-2 lists strengths, ranging from unacceptable to superior, of identity validation methods that are performed by the CSP to validate the evidence presented for the current proofing session and the information contained therein."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via: https://github.com/usnistgov/800-63-3/pull/1663
