### ISSUE TITLE
Contradictory phrasing in sections 6 - 6.3

### ISSUE THREAD

**Issue by mstrock** [usnistgov/800-63-3#628]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: Sections 6 (4th para.), 6.1 (item 4), 6.1 (item 6), 6.2, and 6.3
 
**Comment (Include rationale for comment)**: These sections are contradictory. It also does not acknowkedge the requirements for binding primary and derived PIV authenticators are different than for other primary and derived authenticators. This sentence says "it is possible that all authenticators bound to the identity will also be revoked." Item 4 states "The new authenticator SHALL be valid only as long as the subscriber is authorized to hold the primary authenticator." And item 6 states "There are instances where the new authenticator need not be directly tied to the expiration of the primary authenticator." 6.2 and 6.3 require the status of the primary authenticator to be checked weekly and daily, respectively.
 
**Suggested Change**: Change "SHALL" in item 4 to "MAY" AND add a note that reads "The requirements for binding PIV primary and derived authenticators is more restrictive than the general requirements presented here. Please see NIST Special Publication 800-157 for additional information."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We believe we have this right, but we will re-review and add explanatory text to support why these scenarios can all exist.

**Comment by jimfenton** [comment]
PIV is a profile of -63, with additional requirements, so MAY is reasonable in the more general case. This text is moving to -63B since this is an authenticator requirement (see #597)

**Comment by paul-grassi** [comment]
Addressed via #597
