### ISSUE TITLE
Typographic error (section 6)

### ISSUE THREAD

**Issue by mstrock** [usnistgov/800-63-3#629]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: Section 6, text box
 
**Comment (Include rationale for comment)**: Typographic error in the last line.
 
**Suggested Change**: Delete the word "will".
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Duplicate of #571; fixed by #577.
