### ISSUE TITLE
varying definitions of attack

### ISSUE THREAD

**Issue by vashekmatyas** [usnistgov/800-63-3#632]
### All Fields Are Required
**Organization Name (N/A, if individual):** Red Hat & Masaryk U.

**Organization Type (see below for codes)**: 2, 3
 
**Document (63-3, 63A, 63B, or 63C)**: 3, A, B

**Reference (Include section and paragraph number)**: section 3 in all these 3 documents
 
**Comment (Include rationale for comment)**: Attack - definitions in all parts (in C none) different! On top of this, all versions stay shy of dealing properly with insider attacks.
 
**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Even when we combine definitions into one document we should investigate this comment.

**Comment by jimfenton** [comment]
Definitions have been consolidated into Appendix A of -3. Insiders are being included in the definition of "attacker".
