### ISSUE TITLE
ADEQUATE evidence

### ISSUE THREAD

**Issue by vashekmatyas** [usnistgov/800-63-3#633]
### All Fields Are Required
**Organization Name (N/A, if individual):** Red Hat & Masaryk U.

**Organization Type (see below for codes)**: 2, 3
 
**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: 4.4.1.2., 4.5.2., and also summarizing Table 4-3.
 
**Comment (Include rationale for comment)**: "ADEQUATE" not defined!!!  (probably meant "FAIR"?)
 
**Suggested Change**: change to FAIR
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Fixed by #571
