### ISSUE TITLE
reauthentication - 1 vs. more sessions

### ISSUE THREAD

**Issue by vashekmatyas** [usnistgov/800-63-3#634]
### All Fields Are Required
**Organization Name (N/A, if individual):** Red Hat & Masaryk U.

**Organization Type (see below for codes)**: 2, 3
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: Sections 4.x.3 (3 times)
 
**Comment (Include rationale for comment)**: (At AALx, reauthentication of the subscriber SHOULD/SHALL be repeated at least once per XXX, regardless of user activity.)
Reason: req's are incomplete, dependent on the definition of reauthentication as such. The problem is that such stated requirements do not specify that they concern only the extended subscriber session (lasting more than XXX), allowing for an obscure interpretation of such requirement of additional authentication request even when a subscriber logged off the session and does not need service/identity for a while.
 
**Suggested Change**: adding ", during one extended usage session." explicitly to the end of the first sentence of the requirements
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by lachellel** [comment]
### All Fields Are Required
**Organization Name (N/A, if individual):**  GSA

**Organization Type (see below for codes)**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Comment (Include rationale for comment)**:  

**Second** this issue and suggested changes.  

The definition of Re-authentication in the glossary contains the "during one extended usage session"; however, the normative sections (4.x) and requirements do allow for obscure interpretation.  

To support the original Issue submission: another use case is to consider information security requirements that require a session be **terminated** after XX period of inactivity.  A system terminated session is implemented (technically) the same as a user terminated session such as a direct "logout".   A reauthentication using one factor would not be prudent nor in the best interest of the user or system. 

Recommend Table 4-3 (informative) is also updated.  The 4.x.3 requirements and Table 4.3 are not aligned.  For example, the "Authentication SHALL ...every 12 hours" as specified in 4.x.3 is not a _Reauthentication_, and the Table 4-3 information allows for misinterpretation.   Readers tend to use / re-use the Tables in lieu of the text; therefore reducing confusion in the Tables benefits a wider reading audience.

**Comment by jimfenton** [comment]
Made clarification that session activity (and not just user activity) is required to satisfy inactivity timeouts. Also added a sentence to make it clear that session termination occurs when timely reauthentication doesn't happen.

Some further thought may be needed to clarify the meaning of a "session" in the context of mobile applications as compared with web browser-based sessions.
