### ISSUE TITLE
testing of biometrics - zero-effort (impostor) or non-zero effort (spoof) attack(s)

### ISSUE THREAD

**Issue by vashekmatyas** [usnistgov/800-63-3#635]
### All Fields Are Required
**Organization Name (N/A, if individual):** Red Hat & Masaryk U.

**Organization Type (see below for codes)**: 2, 3
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 5.2.3
 
**Comment (Include rationale for comment)**: Statement "Empirical testing of the biometric system to be deployed SHALL demonstrate an EER of 1 in 1000 or better with respect to matching performance." should be clarified whether this is with zero-effort (impostor) or non-zero effort (spoof) attack(s). I expect the former, but it is not clear. Overall, this requirement as (under)specified is rather doubtful, due to ambiguity.
 
**Suggested Change**:
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by enewt** [comment]
Matching rate testing is performed with a set of genuines and imposters, the latter representing zero-effort. This statistic represents something different than analyzing zero-information v targeted attacks. Will clarify text using ISO/IEC definitions.

**Comment by jimfenton** [comment]
Test conditions were added by the fix for #1391, although the EER language has been removed.
