### ISSUE TITLE
testing of biometrics - zero-effort (impostor) or non-zero effort (spoof) attack(s) II

### ISSUE THREAD

**Issue by vashekmatyas** [usnistgov/800-63-3#636]
### All Fields Are Required
**Organization Name (N/A, if individual):** Red Hat & Masaryk U.

**Organization Type (see below for codes)**: 2, 3
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 5.2.3
 
**Comment (Include rationale for comment)**: Statement "Testing of the biometric system to be deployed SHOULD demonstrate at least 90% resistance to presentation attacks for each relevant attack type (aka species), where resistance is defined as the number of thwarted presentation attacks divided by the number of trial presentation attacks."
Here it should be clarified whether this is with zero-effort (impostor) or non-zero effort (spoof) 
attack(s). I expect the former, but it is not clear. Overall, this requirement as (under)specified is rather doubtful, due to ambiguity.
 
**Suggested Change**:
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by enewt** [comment]
A zero-effort attack is one type of attack. The requirement here is for any attack type that is under consideration. Each attack type should demonstrate 90% resistance. A reference to error rates discussed in ISO/IEC 30107-3 Clause 12 will be added.
