### ISSUE TITLE
terminology - unclear meaning of "authenticated protected channel"

### ISSUE THREAD

**Issue by vashekmatyas** [usnistgov/800-63-3#637]
### All Fields Are Required
**Organization Name (N/A, if individual):** Red Hat & Masaryk U.

**Organization Type (see below for codes)**: 2, 3
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 
 
**Comment (Include rationale for comment)**: Many sections - search for phrase "authenticated protected channel"
The phrase "authenticated protected channel" should be changed to "authenticated and confidential channel" or "authenticated encrypted channel". The reason is that the phrase "authenticated protected channel" is ambiguous - basic meaning is channel protected to provide authentication, implicit extended meaning is channel that is authenticated and also providing other "protective" functionality, e.g., confidentiality. Then also statements like "authenticated protected channel to provide confidentiality of the authenticator output and resistance to MitM attacks." can be misinterpreted.

**Suggested Change**:  phrase "authenticated protected channel" should be changed to "authenticated
and confidential channel" or "authenticated encrypted channel"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
"authenticated protected channel" is a term with a specific definition within these documents:

> **Authenticated Protected Channel**
> A communication channel that uses approved encryption where the initiator of the connection (client) has authenticated the recipient (server). Authenticated protected channels provide confidentiality and man-in-the-middle protection and are frequently used in the user authentication process. TLS [BCP 195] is an example of an authenticated protected channel when the certificate presented by the recipient is verified by the initiator.

See the definitions section of each component.
