### ISSUE TITLE
simple typo - singular/plural - exist/s

### ISSUE THREAD

**Issue by vashekmatyas** [usnistgov/800-63-3#638]
### All Fields Are Required
**Organization Name (N/A, if individual):** Red Hat & Masaryk U.

**Organization Type (see below for codes)**: 2, 3
 
**Document (63-3, 63A, 63B, or 63C)**: 63-3

**Reference (Include section and paragraph number)**: section 2, par. 1
 
**Comment (Include rationale for comment)**: Typo: "Of which exists multiple opportunities for..."
 
**Suggested Change**: "Of which exist multiple opportunities for..."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will fix via issue #590
