### ISSUE TITLE
Section 5.2.2.1 intro sentence

### ISSUE THREAD

**Issue by lachellel** [usnistgov/800-63-3#641]
### All Fields Are Required
**Organization Name (N/A, if individual):**  GSA

**Organization Type (see below for codes)**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**:
Section 5.2.2.1
 
**Comment (Include rationale for comment)**:
General edit for clarity

Current: 

> Table 5-2 lists qualities, ranging from unacceptable to superior, of identity validation that is performed by the CSP to validate the evidence presented for the current proofing session and the information contained therein.

 Section 5.2.2.1 is "Identity Evidence Validation".  Section 5.3 is "Identity Verification".  For clarity, the term "identity validation" should be updated.   

**Suggested Change**:

> Table 5-2 lists qualities, ranging from unacceptable to superior, of validation that is performed by the CSP to perform identity evidence validation presented for the current proofing session.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by lachellel** [comment]
Similar / same as #627

**Comment by paul-grassi** [comment]
Will resolve with #627
