### ISSUE TITLE
IAL2 too restrictive

### ISSUE THREAD

**Issue by kcrowl11** [usnistgov/800-63-3#643]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Experian
**Organization Type (see below for codes)**:
 2
**Document (63-3, 63A, 63B, or 63C)**:
63A
**Reference (Include section and paragraph number)**:
 
**Comment (Include rationale for comment)**:
 Many organizations require high-volume levels of remote identity proofing and to require the need for Strong level of authentication which would involve using document verification or in-person identity proofing for all IAL2 level of Identity proofing will create a large bottleneck, while shrinking the population of eligible applicants that do not possess the capability or are unwilling to transmit this sensitive type of data. We have spoken to many Federal agencies and industry partners who feel this will have an adverse effect to the desired result of increased success of identity proofing while reducing customer friction. Not to mention an increased cost to perform document verification which will either have to be absorbed by the agency or passed on to the consumer, which neither is desired.

**Suggested Change**:
 We strongly recommend considering re-implementation of 4 IAL levels as opposed to the 3 levels currently defined in 800-63-3. There seems to be too much of a “gap” between IAL level 1 (no proofing/self-asserted) to IAL 2 (requiring document verification) to IAL 3 (in person). We suggest defining 4 levels as follows:
•	IAL 1 – No ID proofing required (self-attested only)
•	IAL 2 (Fair Level(s) of Evidence) – Online identity validation of PII (name, address, DOB, SSN) and 1 or 2 financial accounts (similar to LOA3 under current SP 800-63-2) Knowledge Based Authentication, or KBA, could also be utilized at this level as another method to validate identity information.  Although NIST has indicated a deprecation of using One-Time Passcode (OTP) over SMS as part of the Authentication process, we believe using OTP as part of the identity proofing process could be an acceptable part of the process. 
•	IAL 3 (Strong Level(s) of Evidence) – IAL 2 with the addition of document verification with optional facial recognition 
•	IAL 4 – in person ID proofing required (Superior level of evidence required)
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by mingpeiwk** [comment]
Support this view.

It is also in Symantec's view that we prefer to keep the previous 4 IAL levels instead of the newly proposed 3 levels. The document verification for IAL2 makes it hard to achieve L2 for the variety of document types and mandatory ones that may meet broad verification need. 

From our customer interaction experience as a Kantara certified LOA3 provider, we observed that many customers prefer LOA2 because it doesn’t include address check that may take significant amounts of time.

**Comment by paul-grassi** [comment]
We are changing the requirements for document verification all the way to issuing source.  In addition, the April 1 update to 800-63-3 gives agencies some flexibility.
