### ISSUE TITLE
General comment: Continuous authentication not mentioned/covered at all. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#645]
**Organization Name (N/A, if individual)**: BioCatch

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: , 
 
**Comment (Include rationale for comment)**:  General comment: Continuous authentication not mentioned/covered at all.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Continuous authentication (which apparently refers to the use of behavioral biometrics during a session) is one of many types of additional risk mitigation measures that may be used as described in SP 800-63-3 Section 2.2. It is not practical to name all of them, nor appropriate to name specific ones.
