### ISSUE TITLE
Behavioral biometrics differ from physical biometrics as there is nothing to "steal", hence they do constitute secrets without storing PII. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#649]
**Organization Name (N/A, if individual)**: BioCatch

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.3, 
 
**Comment (Include rationale for comment)**:  Behavioral biometrics differ from physical biometrics as there is nothing to "steal", hence they do constitute secrets without storing PII. 
 
There are also no sensors to authenticate. Furthermore, techniques like Invisible Challenges™ provide significant assurance against presentation and replay attacks. 

**Suggested Change**: Add: In the case of behavioral biometrics, validate the device.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by enewt** [comment]
We agree with the proposed change but disagree with the assertions in the comment regarding behavioral biometrics. They are like other biometric modalities: they use a sensor (in some cases it's the mobile phone, in others it may be a keyboard) and a reference template to compare a claimant's behavior/identity.
