### ISSUE TITLE
Behavioral biometrics do not require an active enrollment. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#650]
**Organization Name (N/A, if individual)**: BioCatch

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 6.1.1, 
 
**Comment (Include rationale for comment)**:  Behavioral biometrics do not require an active enrollment.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by enewt** [comment]
It is unclear how this comment relates to the proposed requirements in 63-B
