### ISSUE TITLE
One of the most promising use cases for behavior biometrics is password resets since the recovery is done by comparing passive means. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#654]
**Organization Name (N/A, if individual)**: BioCatch

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 8.3, 
 
**Comment (Include rationale for comment)**:  One of the most promising use cases for behavior biometrics is password resets since the recovery is done by comparing passive means.
 

**Suggested Change**: Add use of behavioral biometrics to aid in the authenticator recovery process and minimize call center costs.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by enewt** [comment]
Will consider citing biometrics (generally) in password recovery.

**Comment by jimfenton** [comment]
Fixed by f688e2ba7161f8451b9c4adf7ebe1f5b011de28f (as part of resolution of #1065).
