### ISSUE TITLE
800-63-A Table 4-3 incomplete

### ISSUE THREAD

**Issue by iglazer** [usnistgov/800-63-3#658]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Salesforce

**Organization Type (see below for codes)**:
2 
**Document (63-3, 63A, 63B, or 63C)**:
63A
**Reference (Include section and paragraph number)**:
 4.7 - Table 4-3
**Comment (Include rationale for comment)**:
 Table 4-3 doesn’t have an entry for Resolution at IAL3. Should it be assumed that IAL3 is the same as IAL2 here?
**Suggested Change**:
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Markdown table error.  Will fix.
