### ISSUE TITLE
800-63-A ADEQUATE/FAIR mismatch in 5.2.2.1

### ISSUE THREAD

**Issue by iglazer** [usnistgov/800-63-3#660]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Salesforce 

**Organization Type (see below for codes)**:
2
 
**Document (63-3, 63A, 63B, or 63C)**:
63A

**Reference (Include section and paragraph number)**:
5.2.2.1
 
**Comment (Include rationale for comment)**:
The table (5-2) talks of Weak, Fair, Strong, and Superior grade evidence but section 4.4.1.2 references Adequate evidence.
 
**Suggested Change**:
Update 4.4.1.2 to change reference of Adequate to Fair 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Fixed by #571
