### ISSUE TITLE
Proofing terms: use of remote, physically present, virtual and in-person

### ISSUE THREAD

**Issue by BrJu** [usnistgov/800-63-3#665]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Safran Identity & Security
**Organization Type (see below for codes)**:
2 
**Document (63-3, 63A, 63B, or 63C)**:
63-3 and 63A
**Reference (Include section and paragraph number)**:
 General
**Comment (Include rationale for comment)**:
 IAL2 allows both remote and in-person, IAL3 allows in-person and remotely equivalent. However, depending on the wording used in the different part of the text, it could become very confusing.
**Suggested Change**:
1/ stick to the same wording all along the 2 documents

2/ Clarify the wording to avoid misleading understanding of in-person and physically present as necessarily physical face-to-face.
Suggestion (but one might find better ones...): 
- replace "remote" (for identity proofing) by "unsupervised remote"
- replace "physically-present" and "in-person" by "supervised" 
- replace "virtual in-person" and "remote in-person" by "supervised remote" 

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Best suggestion on these differences thus far.  Will plan on using these terms unless we discover something else.
