### ISSUE TITLE
IAL2 presence req.

### ISSUE THREAD

**Issue by BrJu** [usnistgov/800-63-3#667]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Safran Identity & Security
**Organization Type (see below for codes)**:
 2
**Document (63-3, 63A, 63B, or 63C)**:
63-A
**Reference (Include section and paragraph number)**:
 4.4.1.5
"The CSP SHOULD perform identity proofing in-person. The CSP MAY perform remote identity proofing. The CSP SHOULD offer both in-person and remote proofing."
**Comment (Include rationale for comment)**:
The 2nd SHOULD looks strange after the MAY for remote proofing. 
**Suggested Change**:
 Replace the 2nd SHOULD by MAY. 

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The point is that in-person identity proofing is acceptable at AAL2, and that in-person is generally stronger. In-person is also an alternative when remote doesn't work. But agreed that the section is worded in a possibly confusing way.
