### ISSUE TITLE
Clarify that in-person proofing can be remote

### ISSUE THREAD

**Issue by BrJu** [usnistgov/800-63-3#668]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Safran Identity & Security
**Organization Type (see below for codes)**:
 2
**Document (63-3, 63A, 63B, or 63C)**:
63A
**Reference (Include section and paragraph number)**:
4.5 - 1st paragraph  “In addition, identity proofing at IAL3 is performed in-person.” 
4.5.5 "All identity proofing steps SHALL be performed in person"
Table 4-3. Presence/IAL3 cell
**Comment (Include rationale for comment)**:
 In-person can be understood as physically present.
**Suggested Change**:
 Replace "in-person" with "in-person (or remotely equivalent)" 
Or follow suggestion in https://github.com/usnistgov/800-63-3/issues/665  (replace "in-person" by "supervised")

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Fixing via #665
