### ISSUE TITLE
IAL2/IAL3 evidence req.

### ISSUE THREAD

**Issue by BrJu** [usnistgov/800-63-3#669]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Safran Identity & Security
**Organization Type (see below for codes)**:
 2
**Document (63-3, 63A, 63B, or 63C)**:
63A
**Reference (Include section and paragraph number)**:
 4.4.1.2 and 4.5.2 and table 4-3

**Comment (Include rationale for comment)**:
 These two sections are not fully consistent. In particular when comparing A/"One (1) piece of STRONG evidence plus two (2) pieces of ADEQUATE evidence." with B/"Two (2) pieces of STRONG evidence plus one (1) piece of ADEQUATE evidence.". 
The corresponding requirement for IAL3 to A/ seems to be "One (1) piece of SUPERIOR evidence plus two (2) pieces of STRONG evidence."
The corresponding requirement for IAL2 to B/ seems to be  "Two (2) pieces of ADEQUATE evidence plus one (1) piece of FAIR evidence.". 

Moreover, the text in Table 4-3 (row "evidence") is not consistent with the text of those two sections.

**Suggested Change**:
Check and correct requirements in 4.4.1.2 and 4.5.2.
Correct content of Table 4-3 

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Will either make the table consistent with the text or delete it.
