### ISSUE TITLE
63A - Table 4-3 edits

### ISSUE THREAD

**Issue by BrJu** [usnistgov/800-63-3#670]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Safran Identity & Security
**Organization Type (see below for codes)**:
 2
**Document (63-3, 63A, 63B, or 63C)**:
63A
**Reference (Include section and paragraph number)**:
 Table 4-3 "biometric" row
**Comment (Include rationale for comment)**:
The entry "Yes" for IAL2 is not consistent with 4.4.1.7.
For IAL3, it would be clearer to use "SHALL"
**Suggested Change**:
Replace Yes by MAY for IAL2 
Replace Yes by SHALL for IAL3

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We have an issue under consideration that proposes to delete this table.  If we do not, this change will be applied.
