### ISSUE TITLE
Salt value storage for memorized secrets

### ISSUE THREAD

**Issue by BrJu** [usnistgov/800-63-3#672]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Safran IS
**Organization Type (see below for codes)**:
 2
**Document (63-3, 63A, 63B, or 63C)**:
63B
**Reference (Include section and paragraph number)**:
 5.1.1.2 « The salt value SHALL be a 32-bit or longer random value generated by an approved random bit generator and stored along with the hash result.”
**Comment (Include rationale for comment)**:
 It shall not be mandatory to store the salt value with the hash result. The only important requirement is to store it somewhere for later use.
**Suggested Change**:
 Replace "stored along with the hash result" with "SHALL be stored"

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Since the salt value is per-user, the value needs to be stored for each user. The intent was not to require that they be stored contiguously, although they very frequently are. Will make a slight wording change to address that mis-impression.

**Comment by jimfenton** [comment]
The wording had been changed in this section that removed the cited text, but adding a statement about storage of the salt and hash result in any case.
