### ISSUE TITLE
On private channel for out-of-band authenticators

### ISSUE THREAD

**Issue by BrJu** [usnistgov/800-63-3#673]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Safran IS
**Organization Type (see below for codes)**:
 2
**Document (63-3, 63A, 63B, or 63C)**:
63B
**Reference (Include section and paragraph number)**:
5.1.3.1 2nd paragraph "The out-of-band device SHOULD be uniquely addressable and communication over the secondary channel SHALL be private. Methods that do not prove possession of a specific device, such as voice-over-IP (VOIP) or email, SHALL NOT be used for out-of-band authentication"
**Comment (Include rationale for comment)**:
Precise definition of "private" for a channel is missing.
VOIP and email could be private when used with encryption.
**Suggested Change**:
 Introduce the term private.
Append "such as voice-over-IP (VOIP) or email" with "when used without any confidentiality measure" 

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
"Private" here means that out-of-band secret is delivered over a channel that is encrypted. It is recognized that it may not always be possible to establish an authenticated protected channel with a device under the control of the claimant.  We will clarify this wording.

Note that VOIP and email do not prove possession of a specific device, even when encrypted, so they are not acceptable delivery methods for out-of-band secrets and the suggested wording change is moot.
