### ISSUE TITLE
Applicant vs. Claimant

### ISSUE THREAD

**Issue by mrwiggins1** [usnistgov/800-63-3#676]
### All Fields Are Required
**Organization Name (N/A, if individual)**: US Citizenship and Immigration Services

**Organization Type (see below for codes)**: 1
 
**Document (63-3, 63A, 63B, or 63C)**:  63A

**Reference (Include section and paragraph number)**:  3. Definitions and Abbreviations 
 
**Comment (Include rationale for comment)**: I don't understand the need for both an "applicant" and "claimant". The two are nearly identical.  It sounds like a "claimant" becomes an "applicant" once they start the process but I'm not sure I understand why we need to make that distinction.
 
**Suggested Change**: I suggest that we choose one and make the definitions more comprehensive.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We will be collapsing definitions into a single document.  Applicant is someone starting the proofing process, unknown to CSP.  Claimant is someone with an authenticator that has not yet successfully authenticated.  Once authenticated, they are no longer a claimant.  See [Digital Identity Model](https://pages.nist.gov/800-63-3/sp800-63-3.html#63Sec4-Figure1).
