### ISSUE TITLE
General Requirements: Redress

### ISSUE THREAD

**Issue by mrwiggins1** [usnistgov/800-63-3#678]
### All Fields Are Required
**Organization Name (N/A, if individual)**: US Citizenship and Immigration Services

**Organization Type (see below for codes)**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: 4.2 General Requirements
 
**Comment (Include rationale for comment)**: "The CSP SHALL provide effective mechanisms for redress of applicant complaints or problems arising from the identity proofing. These mechanisms SHALL be easy for applicants to find and access." While I completely agree with this requirement, I'm unsure how it would be enforced as it is completely subjective.
 
**Suggested Change**: I don't feel strongly about this.  Not sure how we can say "SHALL" if there is no way to measure or enforce subjectivity.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by lachellel** [comment]
We 2nd this comment.

**Comment by paul-grassi** [comment]
We will drop the term 'effective' and include the outcome of 'resolved'.  This would also flow down to 8.4.
