### ISSUE TITLE
confidence provided by FMR and FNMR for biometric authentication

### ISSUE THREAD

**Issue by BrJu** [usnistgov/800-63-3#680]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Safran Identity & Security
**Organization Type (see below for codes)**:
 2
**Document (63-3, 63A, 63B, or 63C)**:
63B
**Reference (Include section and paragraph number)**:
 5.2.3 "Biometric False Match Rates (FMR) and False Non-Match Rates (FNMR) do not provide confidence in the authentication of the subscriber by themselves"
**Comment (Include rationale for comment)**:
 This statement is incorrect, as FMR and FNMR doe provide some confidence but with some statistical bias. 
**Suggested Change**:
 Change "confidence" into "full confidence"

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by enewt** [comment]
"by themselves" has the same intent.
