### ISSUE TITLE
Trust on sensor for PAD

### ISSUE THREAD

**Issue by BrJu** [usnistgov/800-63-3#681]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Safran IS
**Organization Type (see below for codes)**:
 2
**Document (63-3, 63A, 63B, or 63C)**:
63B
**Reference (Include section and paragraph number)**:
 5.2.3 "While presentation attack detection (PAD) technologies such as liveness detection can mitigate the risk of these types of attacks, additional trust in the sensor is required to ensure that PAD is operating properly in accordance with the needs of the CSP and the subscriber."
**Comment (Include rationale for comment)**:
 The PAD mechanism could be embedded on the sensor or in software, thus trust may also concern processing. Additionally  all processing is not necessarily local for PAD; when made on server side, CSP can control the process.
**Suggested Change**:
Change "additional trust in the sensor is required" into "additional trust in the sensor or biometric processing may be required"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Perhaps "additional trust in the sensor and biometric processing" because even if PAD is centrally processed, trust in the sensor is always required.

**Comment by BrJu** [comment]
Well, it depends. PAD can be very different from one system to another. For instance one may have some PAD techniques based on challenge-response for which the sensor does not really matter.
