### ISSUE TITLE
Biometric comparison: local vs central

### ISSUE THREAD

**Issue by BrJu** [usnistgov/800-63-3#682]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Safran IS
**Organization Type (see below for codes)**:
 2
**Document (63-3, 63A, 63B, or 63C)**:
63B
**Reference (Include section and paragraph number)**:
 5.2.3 "Biometric matching SHOULD be performed locally on claimant’s device or MAY be performed at a central verifier."
**Comment (Include rationale for comment)**:
 The main reason for differentiating the level of recommendation here seems to be that central verification leads to more privacy constraints. However, it also offers a higher control on the quality of the matching being processed.  
**Suggested Change**:
The suggestion is to suppress this distinction. 

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
We will look at the wording; we do want to express a preference for local matching of biometrics because of the potential scalability of central verifier attacks. This is also reflected in the additional requirements for central matching.
