### ISSUE TITLE
Central biometric comparison

### ISSUE THREAD

**Issue by BrJu** [usnistgov/800-63-3#684]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Safran IS
**Organization Type (see below for codes)**:
 2
**Document (63-3, 63A, 63B, or 63C)**:
63B
**Reference (Include section and paragraph number)**:
 5.2.3
"If matching is performed centrally:
•Use of the biometric SHALL be limited to one or more specific devices that are identified using approved cryptography.
•Biometric revocation, referred to as biometric template protection in ISO/IEC 24745, SHALL be implemented.
•All transmission of biometrics shall be over the authenticated protected channel."
**Comment (Include rationale for comment)**:
-1st item is unclear: what is "the biometric"? is it the reference biometric data?

-2nd item: As mentioned earlier in 5.2.3, availability of solutions for biometric revocation is limited. Should not be a mandatory requirement as of today. Additionally prefer the use of the standardized term “Biometric information protection”.

**Suggested Change**:
-Clarify wording of 1st item

-Replace 2nd item with "Biometric information protection techniques, following ISO/IEC 24745 definition, SHOULD be implemented"

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by enewt** [comment]
1. Will replace the first part of the first bullet with something similar to "Use of the biometric as an authentication factor..."

2. Decline the 2nd.

**Comment by BrJu** [comment]
Thanks for the feedback. On 2., additionally, the sentence needs to be clear on whether only ISO/IEC 24745 compliant schemes are allowed (not sure when reading again the wording if this was the intention?); and if so, standard terminology shall be used.
