### ISSUE TITLE
Memorized secrets and anti-replay

### ISSUE THREAD

**Issue by BrJu** [usnistgov/800-63-3#685]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Safran IS
**Organization Type (see below for codes)**:
 2
**Document (63-3, 63A, 63B, or 63C)**:
63B
**Reference (Include section and paragraph number)**:
 5.2.8 "In contrast, memorized secrets are not considered replay resistant because the authenticator output (the secret itself) is provided for each authentication."
**Comment (Include rationale for comment)**:
 This statement is not universally true. Although being the case for classical hash based password authentication, there are many other authentication mechanisms that are resistant to replay, like for instance when relying on challenge/response protocol or when using password-based authenticated key exchange (PAKE) schemes.
**Suggested Change**:
Be more specific in this example of authentication that can be replayed, by for instance referring to memorized secret that is manually  provided.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This is referring to memorized secret authenticators as defined in section 5.1.1 and its subsections. Apparently that isn't clear.

**Comment by jimfenton** [comment]
Memorized secrets are expected to be transmitted using a protocol such as TLS that is replay resistant. However, replay of the communications channel is not the only threat. The memorized secret is provided to the endpoint, which if not secure presents the opportunity (e.g. through a key logger) for an attacker to capture and replay the memorized secret. These threats are still present when using PAKE schemes.
