### ISSUE TITLE
Frequency of password change

### ISSUE THREAD

**Issue by EbHelicon** [usnistgov/800-63-3#686]
### All Fields Are Required
**Organization Name (N/A, if individual):** N/A

**Organization Type (see below for codes)**: 4
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: Section 5.1.1.2. Memorized Secret Verifiers, paragraph 12 - "Verifiers SHOULD NOT require memorized secrets to be changed arbitrarily (e.g., periodically) and SHOULD only require a change if the subscriber requests a change or there is evidence of compromise of the authenticator."
 
**Comment (Include rationale for comment)**: I quote from Department of Defense Password Management Guideline (CSC-STD-002-85): 
“…passwords should be changed on a periodic basis to counter the possibility of undetected password compromise. They should be changed often enough so that there is an acceptably low probability of compromise during a password’s lifetime.” 
That was good advice in April, 1985, when the document was released, and it’s still good advice today. We should not assume that the end user will be able to determine that his password has been compromised before the attacker uses it. 
 
**Suggested Change**: Eliminate the quoted sentence.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by HoLyVieR** [comment]
From my understanding, the reason this mandatory change was removed was that it created a more important problem than what it tried to fix. When mandatory password change is required, people get more and more lazy with their password choice and start picking really awful password like January2017, MyCompany2017, Fall2017. They also tend to use very noticeable patterns between password update that makes the password update completely useless. They start with SuperStrongPassword1 then go with SuperStrongPassword2 and so on. So with knowledge of the previous password you can very often make a very accurate guess of the new password. So the effectiveness of this mandatory change is in practice limited and it also makes some user pick less desirable password which is a big downside.

**Comment by jimfenton** [comment]
There is a growing body of evidence that routine password expiration is of little benefit, and may actually be harmful to security. For example, the National Cyber Security Centre in the UK has published "[The problems with forcing regular password expiry](https://www.ncsc.gov.uk/articles/problems-forcing-regular-password-expiry)" and the former Chief Technologist of the FTC published a comprehensive blog post, "[Time to rethink mandatory password changes](https://www.ftc.gov/news-events/blogs/techftc/2016/03/time-rethink-mandatory-password-changes)" citing considerable research supporting removal of mandatory periodic password changes.
