### ISSUE TITLE
Replacement of auth factors in-person

### ISSUE THREAD

**Issue by BrJu** [usnistgov/800-63-3#687]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Safran IS
**Organization Type (see below for codes)**:
 2
**Document (63-3, 63A, 63B, or 63C)**:
63B
**Reference (Include section and paragraph number)**:
 6.1.2.3 " Reestablishment of authentication factors at IAL3 SHALL be done in person and SHALL verify the biometric collected during the proofing process."
**Comment (Include rationale for comment)**:
 "in person" can be interpreted as physically in-person
**Suggested Change**:
 append "in person" with "(or equivalent)"

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Effectively the last part of the identity proofing process (verification) needs to be completed, and the requirements for this should be consistent with the requirements in SP 800-63A. Rather than establish new requirements here, the text should refer to the -63A procedures.
