### ISSUE TITLE
4.2.4 Reauthentication

### ISSUE THREAD

**Issue by mschleiff** [usnistgov/800-63-3#69]
**Organization**: 2

**Reference (Include section and paragraph number)**: 4.2.4 - paragraph 1

**Comment (Include rationale for comment)**: The text says, "Reauthentication MAY use one of two authentication factors if the AAL 2 requirements of Section 5.2.4 are met." There is no section 5.2.4.

**Suggested Change**: Update the reference, or include a section 5.2.4.

**Comment by jimfenton** [comment]
Thank you for the comment; what had been in section 5.2.4 at one point is now in section 7. Since the reauthentication requirements in section 7.2 reiterate the requirements already stated, the reference is no longer needed.
