### ISSUE TITLE
Is Identity proofing now optional for Registration/Enrollment?

### ISSUE THREAD

**Issue by Jigneshvadhel** [usnistgov/800-63-3#690]
### All Fields Are Required
**Organization Name (N/A, if individual):**
N/A
**Organization Type (see below for codes)**:
 Insurance 
**Document (63-3, 63A, 63B, or 63C)**:
 63A
**Reference (Include section and paragraph number)**:
 Table 4-2. Recommended M-04-04 IAL Requirements
**Comment (Include rationale for comment)**:
 According to Table 4-2 in 63A, what I am getting is IAL 1 is optional for all LoA. But Its not clear to me  if Identity proofing can be optional for registration/enrollment.
**Suggested Change**:
 Please clarify if Identity Proofing is up to organizations to decide for Registration/Enrollment process, and is not mandatory. 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
New language in 800-63-3 makes this obe.  The tables will be deleted once we close the extended comment period.

**Comment by Jigneshvadhel** [comment]
Could you please explain what did you mean by obe ?

**Comment by paul-grassi** [comment]
Overcome By Events.

**Comment by Jigneshvadhel** [comment]
Thanks for the full form. But if the tables will be deleted, identity proofing requirement for enrollment again becomes unclear. It will be the same as previous NIST. So if possible, could you please simply clarify whether Identity proofing is mandatory for insurance or bank registration?

**Comment by paul-grassi** [comment]
-3 will provide a companion to the NIST RMF for organizations to determine their assurance level.  It is not up to this suite of guidelines to dictate what is required for specific use cases.  Risk determination will do that.

**Comment by Jigneshvadhel** [comment]
Thank you so much,
