### ISSUE TITLE
Explicit "Device Identity" definition required in 63-3

### ISSUE THREAD

**Issue by aidan-herbert** [usnistgov/800-63-3#691]
### All Fields Are Required
**Organization Name (N/A, if individual):**
ThreatMetrix
**Organization Type (see below for codes)**:
 2
**Document (63-3, 63A, 63B, or 63C)**:
63-3 
**Reference (Include section and paragraph number)**:
 Section 4.1 Paragraph 8
**Comment (Include rationale for comment)**:
This paragraph in 63-3 refers to "Device identity" and states that Device Identity does not increase AAL.  Elsewhere in 63B  cryptographic software authenticators and cryptographic hardware authenticators are defined as "something you have"  factors of authentication.  When these cryptographic authenticators are embedded in the users device, they represent device identity.  
The meaning of "device identity" in 63-3 is confusing when compared with authenticators which can be embedded in devices for the purposes of providing device identity
**Suggested Change**:
Add an explicit definition of "device identity" as intended by it use in 63-3 section 4.1 paragraph 8
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by TomCJones** [comment]
It is not true that "When these cryptographic authenticators are embedded in the users device, they represent device identity". Given the structure of (for example) the ARM trust zone it is possible to embed user identities in the device that requires to presence of the user to activate. This is the virtual smart card concept now available in Windows 10.

**Comment by aidan-herbert** [comment]
Documents 63-3 & 63B establish clear distinctions between credential, authenticator and identity.Within the 800-63 guideline it is not possible to embed an identity into a device.  Under 63-3 credentials are provisioned to authenticators by the CSP.  In 63B a credential is defined as an object or data structure that binds an identity to an authenticator.  In the IOT / M2M space (outside the scope of 800-63) the CSP binds an embedded cryptographic authenticator to the "device identity".    My suggestion is that NIST explicitly define the intended meaning of "device identity" as used in 63-3, so as to avoid confusion with "device identity" as used in the IOT/M2M space.

**Comment by TomCJones** [comment]
simply not true that user identities are not embedded in devices. The smart card has an identity embedded in it. The VSC in Windows 10 can have any identity in it. Your restriction does not match the reality of devices today.

**Comment by aidan-herbert** [comment]
800-63 defines identity as “A set of attributes that uniquely describe a person within a given context”. Programming “A set of attributes that uniquely describe” you into an authenticator will not provide sufficient entropy for AAL2 or AAL3.   In addition, personal attributes (i.e. name, address, age, SSN, phone number, bio-metrics, etc.) are private vs. secret, consequently they are discoverable by an adversary.

In the scope of 800-63, Smart-cards and Virtual smart-cards are cryptographic authenticators, containing and embedded cryptographic secret that meets the 112 bits security requirement.  The credentials in the smartcard represent the digital identity of the persona that the smart-card was provisioned to.

**Comment by paul-grassi** [comment]
We will make it clearer in -3 what we mean, but we don't agree that a certificate or private key representing a user stored in secure storage == device identity.  That statement is meant to convey that we aren't doing machine identity yet.
