### ISSUE TITLE
Device Authentication

### ISSUE THREAD

**Issue by DoD-CIO-ID** [usnistgov/800-63-3#692]
**Organization Name (N/A, if individual):**
DoD-CIO-ID

**Organization Type (see below for codes):**
1
 
**Document (63-3, 63A, 63B, or 63C):**
63-3

**Reference (Include section and paragraph number):**
2.2
 
**Comment (Include rationale for comment):** 
It is stated that these guidelines "…do not yet address machine-to-machine authentication…" Will a future Annex be added that addresses Device Identity and Authentication?  Is there a timeline available for machine-to-machine authentication changes?  

**Suggested Change:**
Show a placeholder for future section on Device Identity / Authentication and add a timeline for machine-to-machine policy development.  DoD-CIO-ID is willing to partner with NIST on developing this.  

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Yes, no timeline set but it is of utmost importance to us, especially given the IoT space.
