### ISSUE TITLE
Enrollment Grace Period

### ISSUE THREAD

**Issue by DoD-CIO-ID** [usnistgov/800-63-3#693]
**Organization Name (N/A, if individual):**
DoD-CIO-ID

**Organization Type (see below for codes)**:
1
 
**Document (63-3, 63A, 63B, or 63C)**:
63-3

**Reference (Include section and paragraph number)**:
4
 
**Comment (Include rationale for comment)**:
The document states that: "Alternatively, the CSP may choose to accept a request during a grace period after expiration." 

**Suggested Change**:
CSPs should be required to clearly set out a maximum amount of time allowed for the grace period.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Requirements are in -A and -B.  This is just narrative.
