### ISSUE TITLE
Document Naming

### ISSUE THREAD

**Issue by jaspenc** [usnistgov/800-63-3#7]
**Organization**:2

**Type**: Editorial

**Reference (Include section and paragraph number)**: Title 

**Comment (Include rationale for comment)**:  I recognize that you have asked us to hold back on the editorial comments, but I believe this is fundamental to tracking these documents over time.  As currently named (SP 800-63-3, SP 800-63A, SP 800-63B and SP 800-63C), there is no linkage between the A,B,C documents and the base document.  This will become an issue if there are future updates to the document suite.  It needs to be kept clear that this 'A' goes with this 'B' goes with this '-3'  

**Suggested Change**:  Rename SP 800-63A/B/C to SP 800-63-3A/B/C 

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
It was somewhat intentional to not tie the document revision numbers too tightly together. One of the goals is to allow the documents to be revised independently: for example, for the enrollment and identity proofing requirements to change independent of the authenticator requirements. The intent is that the latest current revision be used for each. Is there some way we can make this goal clearer?

**Comment by jaspenc** [comment]
I am not sure it will work in practice as well as it sounds in theory.  For example, recently, the FIPS 201 team decided to align the version numbers of the related Special publications (-73, -76, -78, etc) even though these are generally independent of each other.  Also, how do you intend to handle future version numbering? SP 800-63A-1?  So, there could be a SP 800-63-3 that aligns with SP 800-63A-1 that aligns with SP 800-63B-4?  
I would suggest keeping the versions in step, even when there are substantive changes to only one.  They do cross reference each other, so substantive changes to one could affect the others in some way (I would suggest updating references at least).  By keeping the versions aligned it will (hopefully) prevent unintended divergence and reduce the confusion factor.

**Comment by jimfenton** [comment]
I was looking at SP 800-53 and SP 800-53A as a model: they're both at revision 4 currently, but they haven't always been in version number sync.

**Comment by paul-grassi** [comment]
NIST library has approved this scheme.  The documents are meant to stand alone given the separation of IAL, AAL, and FAL and are expected to be out of sync at some point.  They will remain rooted in -3 (or future revision).
