### ISSUE TITLE
4.2.4. Reauthentication in federation scenarios

### ISSUE THREAD

**Issue by mschleiff** [usnistgov/800-63-3#70]
**Organization**: 2

**Reference (Include section and paragraph number)**: 4.2.4 - paragraph 1

**Comment (Include rationale for comment)**: I was hoping that either 800-63B or 800-63C might provide some additional guidance about reauthentication requirements in federation scenarios, but I couldn’t find any. For example: if after 30 minutes of inactivity (or after 12 hours since the RPs session was created) the RP sends the user to the CSP with a request for assertion, and the user still has a valid session at the CSP, it’s common practice for the CSP to generate a new assertion for the subscriber without reauthenticating the subscriber. Would that assertion meet the RP’s reauthentication requirement? Would the CSP be required to have the same 30 minute inactivity and 12 hour limits? What about in brokered/proxied federation scenarios - if both the CSP (where the user conducts the primary authentication) and the broker have 12 hour session maximums, then the RP could receive a fresh assertion based on the user's primary authentication that occurred up to 24 hours ago.

**Suggested Change**: In either 800-63B or 800-63C provide some guidance around reauthentication in federation scenarios. I think a Reauthentication section in 800-63C might be best.

**Comment by paul-grassi** [comment]
We will look into this issue, and are considering additional requirements for the CSP in this federated scenario.
