### ISSUE TITLE
"Hard" Crypto-Authenticator

### ISSUE THREAD

**Issue by DoD-CIO-ID** [usnistgov/800-63-3#703]
### All Fields Are Required
**Organization Name (N/A, if individual):**
DoD-CIO-ID

**Organization Type (see below for codes)**:
1 

**Document (63-3, 63A, 63B, or 63C)**:
63-3, 63B

**Reference (Include section and paragraph number)**:
- 63-3, Section 5.1, AAL Table, AAL-3
- 63B, Section 2

**Comment (Include rationale for comment)**:
The policy states that AAL-3 requires a "hard" cryptographic authenticator.  This term should be better defined or explained.

**Suggested Change**:
- 63-3: Change "hard" to hardware for the sake of consistency with the rest of the 800-63-3 documents.  Provide a description of a "hardware" cryptographic authenticator" and describe it's operation.
- 63B: Change "hard" to hardware for the sake of consistency with the rest of the 800-63-3 documents.  
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The term we want to use is probably _hardware-based_ in order to make sure we accommodate authenticators that are embedded in programmable devices.
