### ISSUE TITLE
FIDO

### ISSUE THREAD

**Issue by DoD-CIO-ID** [usnistgov/800-63-3#705]
### All Fields Are Required
**Organization Name (N/A, if individual):**
DoD-CIO-ID

**Organization Type (see below for codes)**:
 1

**Document (63-3, 63A, 63B, or 63C)**:
63-3, 63A, 63B

**Reference (Include section and paragraph number)**:
- 63-3: Section 4.1
- 63A
- 63B    

**Comment (Include rationale for comment)**:
The second paragraph in 63-3, section 4.1 describes the guidelines as reflecting current technologies and architectures available in the market.  However, this section does not have anything on device centric authentication models being introduced in industry, such as the Fast Identity Online (FIDO) Alliance's Universal Authentication Framework (UAF) and Universal 2nd Factor (U2F) Protocol.  FIDO should also be touched on in 63A and 63B.

**Suggested Change**:
Introduce Device Centric Authentication and the advantages that it brings in terms of security.  
- In 63-3: 4.1, add a line stating "In addition, there are device-centric forms of authentication where the device itself is the credential, such as the Fast Identity Online (FIDO) Alliance's Universal Authentication Framework (UAF) and Universal 2nd Factor (U2F) Protocol."
 - In 63A, add some verbiage acknowledging that an Applicant may already have HW authenticator [on their device] that can be registered when obtaining credentials. 
- In 63B, add some verbiage acknowledging that some FIDO authenticators may qualify as AAL-3 hardware-based mechanisms.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We can not reference technologies but we appreciate the point related to clarity and will consider enhancements along the lines of those proposed.

**Comment by jimfenton** [comment]
FIDO is an example of a hardware-based cryptographic authenticator as described in -63B. Ability for subscribers to supply their own authenticators for binding to their identity has already been addressed.
