### ISSUE TITLE
Cloud Computing

### ISSUE THREAD

**Issue by DoD-CIO-ID** [usnistgov/800-63-3#706]
### All Fields Are Required
DoD-CIO-ID

**Organization Type (see below for codes)**:
 1

**Document (63-3, 63A, 63B, or 63C)**:
63C

**Reference (Include section and paragraph number)**:
 All

**Comment (Include rationale for comment)**:
These guidelines do not address cloud with respect to possible considerations for authenticating to cloud services from outside or from within cloud boundaries.  Such guidance is needed as assets increasingly are moving to cloud hosted environments. Current cloud security guidance is notably missing when it comes to authentication to numerous cloud services where multiple identities are involved.
 
**Suggested Change**:
Clarify how the generic federation models advanced in 800-63C would work with cloud-based resources.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
The current description of federation models already describes several different types of connections, including fully dynamic systems. Federations are designed explicitly to cross network and authority boundaries, and therefore the current model already describes and includes cloud computing -- both for the IdP and the RP. In fact, federation is vastly preferable in cloud environments as it allows a technological abstraction layer between primary credentialing systems and the downstream applications which the user logs in to.

**Comment by paul-grassi** [comment]
what @jricher said. All of -C assumes disparate, networked services.  On prem, cloud, internal to a domain, whatever the use case may be to assert identity. Traditional federation was built for cross domain (x.com to y.gov not Secret to TS), so a cloud SaaS provider can consume a DoD assertion per -C.  Vice versa - if the cloud provider is an IDP, DoD can be an RP can accept their assertion.
