### ISSUE TITLE
Identity proofing SHALL NOT be performed to determine suitability/entitlement to gain access to services or benefits.

### ISSUE THREAD

**Issue by TomCJones** [usnistgov/800-63-3#707]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**:4
 
**Document (63-3, 63A, 63B, or 63C)**:63A

**Reference (Include section and paragraph number)**:4.2
 
**Comment (Include rationale for comment)**: The requirement that identity proof SHALL NOT be performed to determine suitability to gain access seems to be in contradiction to Identity certs like drivers' licenses and PIV cards
 
**Suggested Change**:
 Drop this item
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
See #677
