### ISSUE TITLE
Relying Party Attribute Requirements Documentation

### ISSUE THREAD

**Issue by kjklingenstein** [usnistgov/800-63-3#708]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Internet2/InCommon Federation Community

**Organization Type (see below for codes)**:
3
 
**Document (63-3, 63A, 63B, or 63C)**:
63-C

**Reference (Include section and paragraph number)**:
 9.3
**Comment (Include rationale for comment)**:
 Providing insufficient attributes may impact the functionality of the application. If the RP can identify which attributes are needed for which functions, it will help a user determine what to release.

**Suggested Change**:

 Guidance on how to do this would be helpful.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
From an IDP to RP perspective, the document is very clear in regards to the RP being in control of requesting the attributes from the IDP, with user consent.  In addition, Section 9.2 states that the user should be aware of which functions may be impacted by not consenting to release of attributes, allowing the user to make a more informed decision about attribute release.
