### ISSUE TITLE
Flowcharts

### ISSUE THREAD

**Issue by DoD-CIO-ID** [usnistgov/800-63-3#709]
### All Fields Are Required
**Organization Name (N/A, if individual):**
DoD-CIO-ID

**Organization Type (see below for codes)**:
1

**Document (63-3, 63A, 63B, or 63C)**:
All (63-3, 63A, 63B, or 63C)

**Reference (Include section and paragraph number)**:
- 63-3: 5.3.2, 5.3.3, 5.3.4

**Comment (Include rationale for comment)**:
- Sections 5.3.2 and 5.3.3 in 63-3 provide guidance and flowcharts for how government agencies should evaluate their systems and decide on the IAL and AAL levels to require from subscriber credentials.  Section 5.3.4 has no corresponding flowchart providing guidance on selecting an FAL.  The convention should remain the same across discussions of all three types of xAL.
- The other annexes (63A, 63B, 63C) would also benefit from these flowcharts, especially if readers go directly to them and skip over 63-3.

**Suggested Change**:
- For consistency and completeness, add a flowchart to 63-3, section 5.3.4, that describes Selecting FAL.
- Duplicate the flowchart in 63-3, section 5.3.2, in 63B.  
- Duplicate the flowchart in 63-3, section 5.3.3, in 63A.
- Duplicate the flowchart that will be developed in 63-3, section 5.3.4, in 63C.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
@DoD-CIO-ID -3 becomes normative with the migrating of M-04-04 language.  Would you still recommend putting the flow charts in both places?  We don't want to arbitrarily lengthen these documents.  Understand point of FAL, just not sure it has the same complexity to warrant a flowchart.  Will consider.

**Comment by jimfenton** [comment]
We will look at creating a flowchart for FAL, although it may be a fairly simple flowchart. With the newly normative nature of 63-3, it is less necessary to duplicate the flowcharts (which would potentially create an opportunity for the flowcharts to be inconsistent).

**Comment by paul-grassi** [comment]
@kboeckl let's discuss this and see if we can't figure out a simple flow chart for FAL
