### ISSUE TITLE
Data Minimization and Portals

### ISSUE THREAD

**Issue by kjklingenstein** [usnistgov/800-63-3#710]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Internet2/InCommon Federation Community

**Organization Type (see below for codes)**:
 3

**Document (63-3, 63A, 63B, or 63C)**:
63C

**Reference (Include section and paragraph number)**:
 9.3

**Comment (Include rationale for comment)**:
 Data minimization for portals is particularly vexing. 

**Suggested Change**:
 
Guidance on how to manage this use case would be helpful.
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We understand that there are many use cases that could have complex requirements that make minimization a complex topic.  We will be putting out implementation guides that can discuss portals and other use cases and strategies to minimize data while making sure RP's under the control of a portal can get the data they need.
