### ISSUE TITLE
Collection of PII SHALL be limited to the minimum necessary 

### ISSUE THREAD

**Issue by TomCJones** [usnistgov/800-63-3#712]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**:4
 
**Document (63-3, 63A, 63B, or 63C)**:63A

**Reference (Include section and paragraph number)**:section 4.2 requirement 3
 
**Comment (Include rationale for comment)**:All IdP's that exist today collect information beyond that necessary to the id process. Drivers' licenses want to know if you need glasses, Social sites like Google and FaceBook want to know about friends and family.
 
**Suggested Change**:
 It seems that this limits IAL 2 and 3 in ways that will prevent any existing, or commercially viable IdP from use on the Federal networks. Or that it limits Federal sites to IAL 1 if they want to allow social networks. Since Google in particular is upgrading their IdP in ways that would support IAL 2, I recommend that this restriction be removed. Even if it allied to IAL3 only, it seems to prevent use of drivers' licenses or passports from use at these levels.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by TomCJones** [comment]
this applies as well to 4.4.1.1. Resolution Requirements

**Comment by paul-grassi** [comment]
We will add information in the 'Model' section of -3 that acknowledges that a CSP can have more roles, but that these requirements only apply to its role as a CSP.  For example, the DMV as a CSP can only collect certain information, but its role as a DMV it can collect 'eye glasses required'.  This attribute would then not be allowed to be sent to any RP, as it is unrelated to identity proofing and the CSP role.
