### ISSUE TITLE
Attribute Name Mapping

### ISSUE THREAD

**Issue by kjklingenstein** [usnistgov/800-63-3#713]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Internet2/InCommon Federation Community

**Organization Type (see below for codes)**:
 3

**Document (63-3, 63A, 63B, or 63C)**:
63C

**Reference (Include section and paragraph number)**:
 10.2.1

**Comment (Include rationale for comment)**:
Section does not offer guidance on the translation of technical attribute names and values into user-friendly language.

 
**Suggested Change**:
Guidance on how to do this would be helpful.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by ychoong** [comment]
We added a sentence to explained why such guidance is not currently available.
