### ISSUE TITLE
Attribute Name Mapping

### ISSUE THREAD

**Issue by kjklingenstein** [usnistgov/800-63-3#714]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Internet2/InCommon Federation Community

**Organization Type (see below for codes)**:
3
 
**Document (63-3, 63A, 63B, or 63C)**:
63C

**Reference (Include section and paragraph number)**:
 9

**Comment (Include rationale for comment)**:
 Section does not offer guidance on the translation of technical attribute names and values into user-friendly language.

**Suggested Change**:
 Guidance on how to do this would be helpful.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is not only an informative section, but the whole of 800-63 will not provide community, app, domain, etc related guidance on attributes semantics and naming.  That would be the responsibility of individual profiles and federations (trust frameworks).  In addition GSA manages an attribute registry that does this.
