### ISSUE TITLE
User Attribute Value Update

### ISSUE THREAD

**Issue by kjklingenstein** [usnistgov/800-63-3#715]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Internet2/InCommon Federation Community

**Organization Type (see below for codes)**:
 3

**Document (63-3, 63A, 63B, or 63C)**:
63C

**Reference (Include section and paragraph number)**:
10.1.1
 
**Comment (Include rationale for comment)**:
 The suggestion to "provide users with the ability to easily verify, view and update attributes" is (perhaps deliberately) ambiguous about whether this function needs to be part of the context in which the attributes are being shown and/or released.  

**Suggested Change**:
Clarify the language to state that attribute update should not be offered at the time attribute release decisions are made as its too confusing.  The process for how users can change attribute values should be well known, documented, and easy to do.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by ychoong** [comment]
We added a sentence to explained why such guidance is not currently available.

**Comment by paul-grassi** [comment]
https://github.com/usnistgov/800-63-3/pull/1682
