### ISSUE TITLE
Collection of PII SHALL be limited to the minimum necessary 

### ISSUE THREAD

**Issue by TomCJones** [usnistgov/800-63-3#716]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**:4
 
**Document (63-3, 63A, 63B, or 63C)**:63A

**Reference (Include section and paragraph number)**:4.3.Collection of PII SHALL be limited to the minimum necessary 
 
**Comment (Include rationale for comment)**:
 This seems to imply that an IdP could not support more than one level.
**Suggested Change**:

Make it clear that a Level 3 IdP could still provide Level 1 support to an RP that asked for it.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by TomCJones** [comment]
this applies to section 4.4.1.1. Resolution Requirements as well

**Comment by TomCJones** [comment]
this applies to section 8.1 as well

**Comment by paul-grassi** [comment]
We will make it clear that a CSP that does proof can still make assertions at IAL1. But if the CSP is truly IAL, then they shouldn't proof at all.
