### ISSUE TITLE
Minimize Needed User Actions

### ISSUE THREAD

**Issue by kjklingenstein** [usnistgov/800-63-3#717]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Internet2/InCommon Federation Community

**Organization Type (see below for codes)**:
3
 
**Document (63-3, 63A, 63B, or 63C)**:
63C

**Reference (Include section and paragraph number)**:
10.1
 
**Comment (Include rationale for comment)**:
It might help to qualify what is meant by minimizing user actions.  While we think this is a worthy goal overall, we have struggled with a temptation to minimize user actions in ways that allow important concepts and information to be glossed over.   We are happy to show examples where we chose not to minimize user actions if it would help foster a discussion.

The link to Account Chooser isn't formatted so as to be clickable.  We did navigate to http://openid.net/wg/ac/  and noted a typo. The title of the page (and working group name) uses the word "login" instead of “log in” – use "you only log in once", not "you only login once".

 
**Suggested Change**:
 (a) add language to encourage developers to not lose important concepts in their work to simplify the user experience; (b) consider typo feedback for openid.net.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by ychoong** [comment]
We fixed suggestion (a). But, we have no control over Open ID (e.g. typos).

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
