### ISSUE TITLE
All identity proofing steps SHALL be performed in person

### ISSUE THREAD

**Issue by TomCJones** [usnistgov/800-63-3#718]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**:4
 
**Document (63-3, 63A, 63B, or 63C)**:63A

**Reference (Include section and paragraph number)**:4.5.5
 
**Comment (Include rationale for comment)**:
 This seems to prevent the creation of derived credentials at level 3.

**Suggested Change**:
 Include language like,
All identity proofing steps SHALL be performed in person or based on credentials that meet this criteria.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Derived credentials are already based on a prior proofing experience.  The primary credential is based on in person IAL. Any derived is not based on more proofing, but on proving possession of the primary authenticator.  See section 6 and NIST 800-157 for more details
