### ISSUE TITLE
Transaction History Retention

### ISSUE THREAD

**Issue by kjklingenstein** [usnistgov/800-63-3#719]
### All Fields Are Required
**Organization Name (N/A, if individual):** 
Internet2/InCommon Federation Community

**Organization Type (see below for codes)**:
3
 
**Document (63-3, 63A, 63B, or 63C)**:
63C

**Reference (Include section and paragraph number)**:
10.1.1
 
**Comment (Include rationale for comment)**:
Users typically have little knowledge of data/log retention times and thus can face difficulty making consent decisions.
 
**Suggested Change**:
Recommend the publication of clear, easy to find, site/application data retention policy information.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
