### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by kjklingenstein** [usnistgov/800-63-3#720]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Internet2/InCommon Federation Community

**Organization Type (see below for codes)**:
3
 
**Document (63-3, 63A, 63B, or 63C)**:
63C

**Reference (Include section and paragraph number)**:
10.1.3; last bullet
 
**Comment (Include rationale for comment)**:
Typo: use of “logout” instead of “log out”.
 
**Suggested Change**:
 Consider change
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by ychoong** [comment]
For consistency, we use "logout" for nouns, and "log out" for verbs.

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
