### ISSUE TITLE
using information not supplied by the applicant

### ISSUE THREAD

**Issue by TomCJones** [usnistgov/800-63-3#721]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**: 4
 
**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: 5.3.2 bullet 6.9
 
**Comment (Include rationale for comment)**:
The requirement "◦The CSP SHALL ensure that any KBV approach does not reveal PII that the applicant has not already provided, nor personal information that, when combined with other information in a KBV session, could result in unique identification." Prevents verification by asking if the user last lived at some other address in the past that was not supplied by the applicant. This is a common method used today and should not be eliminated.
 
**Suggested Change**:
 
Drop this requirement
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by TomCJones** [comment]
doc 63A, individual.

**Comment by paul-grassi** [comment]
'approach' will be changed to 'questions'.
