### ISSUE TITLE
IAL-2 Evidence Requirements

### ISSUE THREAD

**Issue by DoD-CIO-ID** [usnistgov/800-63-3#723]
### All Fields Are Required
**Organization Name (N/A, if individual):**
DoD-CIO-ID

**Organization Type (see below for codes)**:
 1

**Document (63-3, 63A, 63B, or 63C)**:
63A

**Reference (Include section and paragraph number)**:
 4.4. Identity Assurance Level 2

**Comment (Include rationale for comment)**:
The subsections are  unclear as written. There appears to be a lack of strict requirements, particularly with regards to Evidence Requirements.   It is assumed that most of the section is guidance (SHOULD), rather than strict requirements, since there is no 'SHALL'.

**Suggested Change**:
Clarify whether the contents of the subsections are strict requirements, and clarify the nature of these requirements.  What are the identity evidence requirements for IAL-2?  4.4.1, 4.4.2, or both?

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #1462
