### ISSUE TITLE
usage of the term Authentictor

### ISSUE THREAD

**Issue by TomCJones** [usnistgov/800-63-3#724]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**:
 
**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: section 6, throughout
 
**Comment (Include rationale for comment)**:
the definition of authenticator is ok, but its use in section 6 is badly muddled. The problem comes from the variety of authenticator designs already available, as well as new designs not yet imaged. Specifically one authenticator may have more that one private key, indeed even more than one physically distinction section with more than one private key. Also each private key will assuredly have more than one certificate as new ones are issued before old ones expire, but could also result from the user applying for certificates from multiple CSPs.
 
**Suggested Change**:
 rewrite this whole section to be technology neutral.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will make an edit to ensure technology agnostic and supportive of multiple authenticators per device (or at least not limited to just one per).

**Comment by paul-grassi** [comment]
OBE by new edits to Section 6.
