### ISSUE TITLE
IAL-2 Evidence Requirements 2

### ISSUE THREAD

**Issue by DoD-CIO-ID** [usnistgov/800-63-3#726]
### All Fields Are Required
**Organization Name (N/A, if individual):**
DoD-CIO-ID

**Organization Type (see below for codes)**:
 1

**Document (63-3, 63A, 63B, or 63C)**:
63A

**Reference (Include section and paragraph number)**:
4.4.1.2. Evidence Requirements and  5.2.1.1. Scoring of Identity Evidence

**Comment (Include rationale for comment)**:
IAL 2 Evidence Requirements and Scoring Strong Evidence are too strict/restrictive. This is challenging to implement and users will not be receptive to these requirements as it greatly increases the complexity with performing remote proofing. There will be an increase in costs to make these changes and operate going forward.  From a technical standpoint, the challenge will be in confirming "the  authenticity of the claimed issuing source". Mechanisms are not fully in place on the CSP/IdP side to do this and issuing sources will become overburdened with servicing all providers.  Additional costs are also anticipated with increased call volume to call centers addressing user issues, questions, or concerns. So from the end-user perspective, adoption and success-rate may be low. This is likely with the less tech-savvy user population that will struggle or lack the means to submit evidence for validation, also with the security-sensitive users hesitent with transmitting identity information/ images.

**Suggested Change**:
Given the different types of users of federal systems and the way technology works today, the federal user population would be better served by an additional IAL.  Think DS-Logon users.  A possible option will be to have another IAL level between 1 - 2 that will be less restrictive.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved by the adjudication of #643
