### ISSUE TITLE
Mobile Devices

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#727]
### All Fields Are Required

**Organization Name (N/A, if individual):**
DoD-CIO-ID2

**Organization Type (see below for codes)**:
1

**Document (63-3, 63A, 63B, or 63C)**:
63-3B

**Reference (Include section and paragraph number)**:
 5.1.9.1

**Comment (Include rationale for comment)**:
 Mobile devices.  SW or HW.  FIPS or NIAP?

**Suggested Change**.
 Mobile device + NIAP PP can equal 5.1.9.1 - for sufficient binding Multifactor Cryptographic Device Authenticators
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Agencies are free to make risk-based decisions to use comparable standards such as NIAP to certify mobile devices for use as cryptographic devices (i.e., at AAL3).

We will add language to 800-63-3 to make this clear, especially in the case of NIAP.
