### ISSUE TITLE
Adequate Evidence

### ISSUE THREAD

**Issue by DoD-CIO-ID** [usnistgov/800-63-3#728]
### All Fields Are Required
**Organization Name (N/A, if individual):**
DoD-CIO-ID

**Organization Type (see below for codes)**:
1

**Document (63-3, 63A, 63B, or 63C)**:
63A

**Reference (Include section and paragraph number)**:
4.4.1.2

**Comment (Include rationale for comment)**:
Section specifies the use of ADEQUATE evidence.  However, the tables in section 5.2 do not include Adequate strength as a category.

**Suggested Change**:
ADEQUATE evidence is not defined and used inconsistently.  Correct mapping to reflect intent.  If Adequate and Fair evidence are the same, choose one term and use it throughout.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Resolved by #518
