### ISSUE TITLE
AAL2 Verifier

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#729]
### All Fields Are Required

**Organization Name (N/A, if individual):**
DoD-CIO-ID2

**Organization Type (see below for codes)**:
1

**Document (63-3, 63A, 63B, or 63C)**:
63-3B

**Reference (Include section and paragraph number)**:
Section 4.5;  Table 4-3

**Comment (Include rationale for comment)**:
AAL 2 communications also occur with RP and CSP. Why is verifier singled out here?

**Suggested Change**:
Inconsistent use of terms.  Verifier used as generic here, whereas elsewhere refers to a particular position**.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
As was done in previous editions of SP 800-63, the term _verifier_ denotes the role of checking the authentication of the claimant. This can be done in different places depending on the structure of the system: sometimes by the CSP directly, or in other circumstances by the RP with the cooperation of the CSP, and sometimes elsewhere in federated identity systems. _Verifier_ denotes the place where that is done, wherever it is. See the definition in Section 3 (which will be moving to 800-63-3 at some point).
