### ISSUE TITLE
Enrollment Codes

### ISSUE THREAD

**Issue by DoD-CIO-ID** [usnistgov/800-63-3#730]
### All Fields Are Required
**Organization Name (N/A, if individual):**
DoD-CIO-ID

**Organization Type (see below for codes)**:
1

**Document (63-3, 63A, 63B, or 63C)**:
63A

**Reference (Include section and paragraph number)**:
4.4.1.6

**Comment (Include rationale for comment)**:
Having an enrollment code valid for only 10 minutes may be too short  of a timeperiod for a majority of our users. "If the CSP performed remote proofing: Enrollment codes sent by means other than physical mail SHALL be valid for a maximum of 10 minutes; those sent to a postal address of record SHALL be valid for a maximum of 7 days but MAY be made valid up to 21 days via an exception process to accommodate addresses outside the direct reach of the U.S. Postal Service."  The primary concern is in regards to codes sent via E-mail. A large user population of the DS Logon Identity Management Service are not tech-savvy, or require extra time. For example, aging veterans may need more time to access their E-mail during enrollment. In addition, some users are geographically dispersed and it may take some time for E-mails to traverse network domains, especiallyin the large user population utilizing older Government-issued/ personal systems that can be considered antiquated and therefore perform much slower.

**Suggested Change**:
Codes sent via E-mail SHALL be valid for a maximum of 24 hours and a minumum of 3 hours.  Codes sent via mobile telephone (SMS or voice) SHALL be valid for 10 minutes.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
We mostly want to make sure that the CSP enforces an expiration, so a more liberal upper limit is acceptable if the CSP is allowed to profile that down if appropriate. So something like, "Codes sent via E-mail SHALL be valid for no more than 24 hours and codes sent via telephone (SMS or voice) SHALL be valid for no more than 10 minutes."
