### ISSUE TITLE
usability should go clear back to design of the system

### ISSUE THREAD

**Issue by TomCJones** [usnistgov/800-63-3#731]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**:4
 
**Document (63-3, 63A, 63B, or 63C)**:63A, etc.

**Reference (Include section and paragraph number)**:9 Usability & 4.6 Enrollment code 
**Comment (Include rationale for comment)**:
In many cases bad design can result in bad usability. One example is the statement in section 9.1 on "enrollment codes". Using fonts to distinguish between the number "0" and letter "O" in an enrollment code is a bad user experience no matter what font is used. The section on enrollment codes should make clear that usability should be considered. The Airlines have already solved this with their confirmation codes which avoid o and I, among other pairs to prevent the problem in the first place. The input code should equate O and 0 so the user does not need to.
 
**Suggested Change**:
 At least fix the section 4.6 on enrollment codes to make usability a design issue.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by ychoong** [comment]
The usability section is informative, not normative.

**Comment by TomCJones** [comment]
The problem is the design of the confirmation code - THAT MUST BE FIXED TO BE USABLE
