### ISSUE TITLE
Missing Definitions

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#732]
### All Fields Are Required

**Organization Name (N/A, if individual):**
DoD-CIO-ID2
**Organization Type (see below for codes)**:
1
**Document (63-3, 63A, 63B, or 63C)**:
63-3B
**Reference (Include section and paragraph number)**:
 Table 4-3
**Comment (Include rationale for comment)**:
 Definitions missing for these terms in Table 4-3:
Authentication Intent
Authenticator Types 
Look-up Secret  
Look-up Secret Authenticator 
Man in the Middle (MitM) Resistance 
Memorized Secret Verifier 
Memorized Secret   
Multifactor One-Time Password (OTP) Devices 
Multifactor One-Time Password (OTP) Authenticator 
Multifactor One-Time Password (OTP) Verifier 
Multifactor Cryptographic Software (Device) 
Multifactor Cryptographic Software Authenticator 
Multifactor Cryptographic Software Verifier 
Out-of-Band Devices 
Out-of-Band Authenticators 
Out-of-Band Verifiers
Replay resistance 
Single Factor OTP Device 
Single Factor OTP Authenticator 
Single Factor OTP Verifier
Single Factor Cryptographic Software Device 
Single Factor Cryptographic Software Authenticator
Single Factor Cryptographic Software Verifier

**Suggested Change**:
 Include missing definitions
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Several of the names on the list are names of authenticator types, which are already more completely defined in Section 5. Other terms, particularly characteristics like _replay resistance_ and _authentication intent_ will be added.
