### ISSUE TITLE
authenticated channels

### ISSUE THREAD

**Issue by TomCJones** [usnistgov/800-63-3#733]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**:4
 
**Document (63-3, 63A, 63B, or 63C)**:63B, etc.

**Reference (Include section and paragraph number)**:4.1.2
 
**Comment (Include rationale for comment)**:
 the assertion "Communication between the claimant and channel (the primary channel in the case of an Out of Band authenticator) SHALL be via an authenticated protected channel..." does not make clear if the channel requires mutual authentication (ie at both ends). If mutual auth is required, most existing implementations will fail.

**Suggested Change**:
 Make clear that authentication at only one end is required to meet the needs of this spec.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The definition of _authenticated protected channel_ (Section 3; moving to 800-63-3 at some point) makes it clear that the client authenticates the server. Mutual authentication is not required unless explicitly specified (as in 5.2.6 between a verifier and separate CSP).

Will try to work something into the definition making it yet clearer that the default is only authentication of the server.
