### ISSUE TITLE
Control of an Authenticator

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#734]
### All Fields Are Required

**Organization Name (N/A, if individual):**
DoD-CIO-ID2

**Organization Type (see below for codes)**:
1

**Document (63-3, 63A, 63B, or 63C)**:
63-3B

**Reference (Include section and paragraph number)**:
 Table 4-3

**Comment (Include rationale for comment)**:
Possession and Control of an Authenticator as defined doesn't speak to control.

**Suggested Change**:

 Add further clarification as to how control of an authenticator is demonstrated or achieved.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
_possession and control of an authenticator_ is defined in Section 3. Control is the ability to activate and use the authenticator.
