### ISSUE TITLE
IAL Requirements Summary

### ISSUE THREAD

**Issue by DoD-CIO-ID** [usnistgov/800-63-3#735]
### All Fields Are Required
**Organization Name (N/A, if individual):**
DoD-CIO-ID

**Organization Type (see below for codes)**:
1

**Document (63-3, 63A, 63B, or 63C)**:
63A

**Reference (Include section and paragraph number)**:
4.7, Table 4-3

**Comment (Include rationale for comment)**:
- IAL-2 Address Confirmation: The "In-person" section in 4.4.1.6 (IAL-2) has different requirements than the "remote" section.  The address confirmation box for IAL -2 in the table under section 4.7 just seems to address the remote requirements, which are mostly SHALL, and doesn't mention the different "in-person" requirements, which are more of a mixture of MAY, SHOULD, and SHALL.
- IAL-3 Address Confirmation: What do physical address confirmation requirements do or add for IAL-3, which already requires in-person identity-proofing?
- IAL-2 Biometric Collection: Biometric Collection in IAL2 is listed as Yes in 4.7.  In 4.4.1.7 this requirement is listed as ‘MAY.’
 
**Suggested Change**:
- IAL-2 Address Confirmation: Update 4.4.1.6 or the table so they match.  
- IAL-3 Address Confirmation: Delete address confirmation requirements from IAL-3, or explain what security benefits are added to IAL-3 by address confirmation.
- IAL-2 Biometric Collection: Clarify that biometrics are optional for IAL-2.  Update table to reflect the optional inclusion of biometric in the table as well.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
we have a recommendation to delete this table.  If we do, this comment is OBE.  If not, we will fix.

**Comment by jimfenton** [comment]
See issue #669
