### ISSUE TITLE
limitation on email for authentication

### ISSUE THREAD

**Issue by TomCJones** [usnistgov/800-63-3#736]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**:4
 
**Document (63-3, 63A, 63B, or 63C)**:63B

**Reference (Include section and paragraph number)**:5.1.3.1
 
**Comment (Include rationale for comment)**:
 The assertion "Methods that do not prove possession of a specific device, such as voice-over-IP (VOIP) or email, SHALL NOT be used for out-of-band authentication" may be applied to authenticators, but not to authentication in general. It may be argued that context makes this clear, but I would prefer if the text were clear on its own. 

**Suggested Change**:
change to.
Methods USED WITH AUTHENTICATORS that do not prove possession of a specific device, such as voice-over-IP (VOIP) or email, SHALL NOT be used for out-of-band authentication
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
It does not apply to authentication in general, it applies to out-of-band authentication as indicated both by the context and the compound adjective before _authentication_.

**Comment by TomCJones** [comment]
I do not believe that you addressed the question. I believe that any authentication which used a separate communications channel for one factor, versus that used for another factor, can be used for authentication. Your response seems to deny that. So in my view your response is incorrect.
