### ISSUE TITLE
CSP provides assertion

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#737]
### All Fields Are Required

**Organization Name (N/A, if individual):**
DoD-CIO-ID2

**Organization Type (see below for codes)**:
1

**Document (63-3, 63A, 63B, or 63C)**:
63-3C

**Reference (Include section and paragraph number)**:
1

**Comment (Include rationale for comment)**:
Second paragraph includes "… allows a given CSP to provide authentication and (optionally) subscriber attributes …". It would seem that the CSP provides authentication assertions.  The CSP does authenticate, but it's the assertion it provides.

**Suggested Change**:
 Add "assertions after "authentication".
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
@DoD-CIO-ID2 as-is, this is a decline, because authentication attributes are part of the assertion (what AAL was used, what mechanism was used, etc.). But we could add the term assertion someplace in this section if it helps mission and what agencies need to apply these requirements.
