### ISSUE TITLE
limitations on technology

### ISSUE THREAD

**Issue by TomCJones** [usnistgov/800-63-3#739]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**:4
 
**Document (63-3, 63A, 63B, or 63C)**: 6sB

**Reference (Include section and paragraph number)**: 4.2
 
**Comment (Include rationale for comment)**:
 This section seems to limit authentication to techniques known at time of publication.

**Suggested Change**:
 Please add a comment like: "New authentication technologies that are the equal to these are encouraged."
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
One of the main reasons for the rather abstract description of authentication without reference to specific technologies is to permit the use of innovative new technologies. The existing categories accommodate the vast majority of new authentication techniques that have been proposed. If some new authentication methodology is proposed that clearly does not fit into any of these categories, agencies could still deploy it subject to a security risk assessment as described in the recent update to SP 800-63-3. It is expected that considerable diligence would be required to ensure that there are not unseen risks in a new technology, however.
