### ISSUE TITLE
Attribute Bundle

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#740]
### All Fields Are Required

**Organization Name (N/A, if individual):**
DoD-CIO-ID2

**Organization Type (see below for codes)**:
1

**Document (63-3, 63A, 63B, or 63C)**:
63-3B

**Reference (Include section and paragraph number)**:
 4.1.5

**Comment (Include rationale for comment)**:
 "Attribute bundle" is not defined.

**Suggested Change**:
 Add attribute bundle to glossary or define it better in the text.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The referenced term is in -63C.
