### ISSUE TITLE
retired identifiers

### ISSUE THREAD

**Issue by TomCJones** [usnistgov/800-63-3#741]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**:4
 
**Document (63-3, 63A, 63B, or 63C)**: missing requirement

**Reference (Include section and paragraph number)**: not present
 
**Comment (Include rationale for comment)**:
 Perhaps I missed it, but I could not find anywhere a limitation on what happens to an identifier that is retired.

**Suggested Change**:
 Add a requirement to either 63A or 63B that when an identifier is retired and no longer applies to a user that identifier will not be reused for another individual for a period of 2 years.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
800-53 controls allow organizations to determine how to handle identifier reuse, so this is out of scope for this document.  However, it is a worthy item to discuss in the implementation guide that will be released after this document goes final.

**Comment by jimfenton** [comment]
On additional discussion, we will say that identifiers SHOULD NOT be reused for a different subject (can't be stronger statement because of -53) but that they SHOULD be used if the same subject is re-enrolled by the CSP (to account for possible account lapses as well as re-employment, etc.)

**Comment by TomCJones** [comment]
agree


________________________________
