### ISSUE TITLE
IdP SHALL require authentication 

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#742]
### All Fields Are Required

**Organization Name (N/A, if individual):**
DoD-CIO-ID2

**Organization Type (see below for codes)**:
 1

**Document (63-3, 63A, 63B, or 63C)**:
63-3C

**Reference (Include section and paragraph number)**:
 6.1

**Comment (Include rationale for comment)**: Last sentence in section begins with: "Presentation of the assertion reference at the IdP SHOULD require authentication …" Suggest changing "SHOULD" to SHALL"

**Suggested Change**:
 Either change it to SHALL or provide an example of the exception use-case had in mind.  Not consistent with end of previous paragraph which implies SHALL.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
@jricher thoughts?

**Comment by jricher** [comment]
I think we'd need to be careful about making this a SHALL unless we want to prescribe what exactly is acceptable for RP authentication at this stage. Would a public client with PKCE count there, for example? The client's not really authenticating itself, really, but it's still providing a mechanism to tie the request to a previous one.

**Comment by jricher** [comment]
Going to make this SHALL require protection of the assertion reference and give RP authentication as an option.
