### ISSUE TITLE
Front channel assertion 

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#744]
### All Fields Are Required
**Organization Name (N/A, if individual):**
DoD-CIO-ID2

Organization Type (see below for codes):
 1

Document (63-3, 63A, 63B, or 63C):
 63-3C

**Reference (Include section and paragraph number)**:
 6.2

**Comment (Include rationale for comment)**:
 Should this section also say something to the effect of "The front channel assertion also may provide one or more assertion references that the RP could use to fetch additional attributes that may be necessary?"

**Suggested Change**:

An all front channel approach requires that ALL entity attributes that might ever be needed for authorization are known ahead of time, and provided to the RP. The suggested statement is consistent with the data minimization concept in Section 9.3.  This section should also say something to the effect of "The front channel assertion also may provide one or more assertion references that the RP could use to fetch additional attributes that may be necessary."
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
We already allow assertions -- whether front channel or back -- to be associated with authorization credentials that can fetch additional attributes.

> The RP MAY fetch additional identity attributes from the IdP in one or more separate transactions using an authorization credential issued alongside the original assertion.
