### ISSUE TITLE
federation protocols

### ISSUE THREAD

**Issue by TomCJones** [usnistgov/800-63-3#745]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**:4
 
**Document (63-3, 63A, 63B, or 63C)**:63B

**Reference (Include section and paragraph number)**: 7.2.1. Reauthentication from a federation or assertion
 
**Comment (Include rationale for comment)**:
Statements like "When using a federation protocol to connect the CSP and RP" have no meaning. Is this a discussion of session creation? The context of the entire section is unclear.

**Suggested Change**:
 Rewrite the entire section making clear where this applies and to what.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Federation protocols are covered in depth in volume C.

**Comment by TomCJones** [comment]
No protocol between the CSP and RP is defined in 63C.  I think the problem is in the descriptions used in this section.  For example the phrase "session expires at an RP " should be rewritten to say "session between the subscriber and the RP expires".  When I first read this phrase I assumed this phrase referred back to the phrase at the beginning.  "When using a federation protocol to connect the CSP and RP". Since there is no session defined between the CSP and RP the rest of the section was misinterpreted by me, and probably others.

**Comment by jricher** [comment]
Federation _is_ the protocol between the CSP (IdP) and the RP covered and defined in 63C. You are correct that there is no session between the IdP and RP, only the authentication transaction event which is carried by the federation protocol ties these two together. It doesn't really make sense for there to be a session between two machines (the CSP and RP). Therefore, the session referred to here is about the _subscriber_, a person, and the system. The text about session expiry here does refer to the subscriber's session at the RP, which is of course separate from the subscriber's session at the IdP in a federation scenario.

**Comment by TomCJones** [comment]
that would be fine if only the text were a little clearer as I suggested above.

**Comment by jricher** [comment]
As this is the intent of the text, we will review to see if that meaning can be made clearer.

**Comment by TomCJones** [comment]
thx

thx ..tom
