### ISSUE TITLE
FAL - AAL correspondence

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#747]
### All Fields Are Required
**Organization Name (N/A, if individual):**
DoD-CIO-ID2

Organization Type (see below for codes):
1

Document (63-3, 63A, 63B, or 63C):
63-3C

**Reference (Include section and paragraph number)**:
7

**Comment (Include rationale for comment)**:
 This section describes the FAL levels, but how are the FAL level designation information carried over an Assertion?  Should the assertion have the FAL level embedded as an attribute?  

**Suggested Change**:
 FAL levels should be included in assertion.  Proxy assertion should contain info on the IAL, AAL, and FAL.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
@jricher i don't think we want FALin assertion because its inferred what level you are by actually sending the assertion.  However, I can see a point in talking about exposing the FAL for discovery purposes...

**Comment by jimfenton** [comment]
FAL can be inferred from the manner in which the assertion is sent. There is nothing wrong with including the FAL in the assertion (although if it's inconsistent with how the assertion was sent, one would need to figure out how to deal with that). But we will not mandate that it be there.
