### ISSUE TITLE
CSP in a Federation

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#748]
### All Fields Are Required

**Organization Name (N/A, if individual):**
DoD-CIO-ID2

Organization Type (see below for codes):
1

Document (63-3, 63A, 63B, or 63C):
63-3C**

Reference (Include section and paragraph number)**:
 9.4

**Comment (Include rationale for comment)**:
First paragraph includes: "For example, if the Agency is serving as a CSP in a federation, ... since credentials would be maintained on behalf of the agency RP." Sentence doesn't make sense.

**Suggested Change**:

  Clarify intent of paragraph in line with comment and rationale.  Credentials are not maintained for RPs. Credentials are maintained on behalf of agencies, users, or perhaps other agencies. But RPs don't have (or shouldn't have) their own credentials. However, if this is a throwback or a sop to stovepipe systems that maintain their own credentials, it's not clear why it's  in a section on federation.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
It is not intending to say that RPs manage credentials -- quite the opposite, in fact. The intent of the sentence is that the CSP manages credentials so that the RP does not -- using federation as the mechanism to convey authentication transactions between parties.

**Comment by paul-grassi** [comment]
Part of the confusion is that it says "credentials would be maintained on behalf of the agency RP." While this acknowledges the agency's CSP role and responsibilities as being distinct from its other roles, in fact the agency CSP maintains credentials for any RP it federates with. So we should clarify to indicate the broader use of the credentials by dropping the last part of the sentence.
