### ISSUE TITLE
Identity Evidence Validation

### ISSUE THREAD

**Issue by DoD-CIO-ID** [usnistgov/800-63-3#750]
### All Fields Are Required
**Organization Name (N/A, if individual):**
DoD-CIO-ID

**Organization Type (see below for codes)**:
 1

**Document (63-3, 63A, 63B, or 63C)**:
63A

**Reference (Include section and paragraph number)**:
4.4.1.2., 4.5.2, 4.7, 5.2. 

**Comment (Include rationale for comment)**:
- The evidence requirements laid out in sections 4.4.1.2., 4.5.2, and 4.7 discuss a type of evidence termed ADEQUATE, but don't mention anything about FAIR evidence.  Section 5.2.1.1 discuss FAIR evidence, but mention nothing about ADEQUATE evidence.  

**Suggested Change**:
- Resolve inconsistencies between FAIR and ADEQUATE.

**Comment (Include rationale for comment)**:
- Section 4.4.1.2 lists a number of options for Evidence Requirements for IAL-2.  The IAL Requirements Summary (Table 4-3) in section 4.7 omits the first option for IAL-2.    

**Suggested Change**:
- Ensure consistent options for IAL-2 Evidence Requirements throughout 63A.

**Comment (Include rationale for comment)**:
- In section 5.2.1.1, 63A states "Unless otherwise noted, to achieve a given strength the evidence SHALL, at a minimum, meet all the properties listed."  It may be useful to integrate the "SHALL"s into the table itself, as some readers may miss this sentence.

**Suggested Change**:
- Integrate details on which "properties of identity evidence" are optional or required into the table itself.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
#518 address the adequate/fair issue.  Will adjust the remaining.
