### ISSUE TITLE
Evidence Confirmation

### ISSUE THREAD

**Issue by DoD-CIO-ID** [usnistgov/800-63-3#751]
### All Fields Are Required
**Organization Name (N/A, if individual):**
DoD-CIO-ID

**Organization Type (see below for codes)**:
 1

**Document (63-3, 63A, 63B, or 63C)**:
63A

**Reference (Include section and paragraph number)**:
Section 5.2.2.1, Table 5-2

**Comment (Include rationale for comment)**:
A number of categories in the table discuss evidence having "been confirmed as valid by comparison with information held or published by an authoritative source."  It would be helpful to have some clarity and examples on what qualifies as "information held or published by an authoritative source."  

**Suggested Change**:
Clarify and provide examples of what qualifies as "information held or published by an authoritative source."  

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
See issue #582
