### ISSUE TITLE
Fraud prevention services / transaction risk scoring SHOULD be used for remote identity proofing

### ISSUE THREAD

**Issue by aidan-herbert** [usnistgov/800-63-3#752]
### All Fields Are Required
**Organization Name (N/A, if individual):**
ThreatMetrix
**Organization Type (see below for codes)**:
 2
**Document (63-3, 63A, 63B, or 63C)**:
63A
**Reference (Include section and paragraph number)**:
 Section 4.2  Bullet item 11
**Comment (Include rationale for comment)**:
 Bullet item 11 states "The CSP SHOULD obtain additional confidence in remote identity proofing using fraud mitigation measures, for example inspecting geolocation, examining the device characteristics of the applicant, evaluating behavioral characteristics"  this an indirect way of stating that fraud prevention services improve IAL.
**Suggested Change**:
 Explicitly state "A fraud prevention service SHOULD be used for remote identity proofing to achieve higher IAL.  Device identity, device reputation, contextual analysis, link analysis and transaction risk scoring services produce a higher IAL (identity assurance level) by mitigating remote identity spoofing and remote impersonation attacks"
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Item 11 describes measures that are good practices, but do not produce a higher IAL.

**Comment by aidan-herbert** [comment]
This is contradictory - Good practices are only good if they support the desired outcome - for identity proofing the desired outcome is highest possible identity assurance for a given scenario  -   Contextual analysis, link analysis and lookup of 3rd party reference data validate and strengthen the identity bind - i.e. increase identity confidence / IAL.   Inclusion of contextual analysis in subsequent authentication steps validates IAl continuously across the identity life cycle.
