### ISSUE TITLE
Risk-based mechanisms increase effective AAL

### ISSUE THREAD

**Issue by aidan-herbert** [usnistgov/800-63-3#753]
### All Fields Are Required
**Organization Name (N/A, if individual):**
ThreatMetrix
**Organization Type (see below for codes)**:
 2
**Document (63-3, 63A, 63B, or 63C)**:
63-3
**Reference (Include section and paragraph number)**:
 Section 4.1 paragraph 8 
**Comment (Include rationale for comment)**:
 Paragraph 8 states " mechanisms such as device identity or geo-location may be used to identify or prevent possible authentication false positives. While these mechanisms do not directly increase the AAL" , this only part of the truth.  Authenticators can be lost, stolen, cloned, duplicated or emulated and used illegitimately for impersonation and identity spoofing.  Risk-based mechanisms can identify and mitigate illegitimate use of authenticators / credentials thereby preventing false negatives.
**Suggested Change**:
 "As part of authentication, risk-based mechanisms SHOULD be used identify and mitigate false negative ( such as cloning / spoofing) and increase the effective AAL"
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by mingpeiwk** [comment]
Further on this from Symantec's view:

Suggest to clarify whether risk-based authentication can be used to meet AAL2 in place of an authenticator. Good risk-based authentication by location, velocity of user move, and continuous presence can serve better than using an authenticator.

**Comment by paul-grassi** [comment]
This section is informative narrative.  Requirements and recommendations for authenticators are in -B.
