### ISSUE TITLE
scope of IdP

### ISSUE THREAD

**Issue by TomCJones** [usnistgov/800-63-3#754]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**:4
 
**Document (63-3, 63A, 63B, or 63C)**:63C

**Reference (Include section and paragraph number)**: 4.2 Privacy Requirements
 
**Comment (Include rationale for comment)**:
 The assertion "The IdP SHALL NOT ... use the information for any purpose other than federated authentication" leads to some odd results that may prevent IdPs from participating in gov't activities and may prevent commercial standards from referencing this document. Specifically if Google is search to find a merchant and DoNotTrack is not asserted, then Google is free to display ads that depend on this referral. If the merchant then uses google for authentication this statement could be read to retroactively prohibit Google from displaying ads to that user based on the referral.

**Suggested Change**:
 
Perhaps a good solution is to allow on-line entities to create a "fenced=in" IdPs that meet this requirement only insofar as the federation is involved. That would mean something like this:

The IdP may not release or otherwise use any information that was developed during the authentication event. Specifically the IdP may not pass on information about the attributes requested by an RP during such an event.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This gets resolved via the change proposed in #712.  We will not add anything else into -C.
