### ISSUE TITLE
Which guidance? "The guidance defines the required LOA in terms of the potential consequences of an authentication error." 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#755]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 2, 3
 
**Comment (Include rationale for comment)**:  Which guidance? "The guidance defines the required LOA in terms of the potential consequences of an authentication error."
 
Clarity

**Suggested Change**: Need to clarify which guidance defines the LOA in term… Believe the guidance here could be OMB memo or the NIST SPs being reviewed or both. I would clarify which is being talked about here which I believe was intended to be the OMB memo. Such as, This OMB guidance...
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
It's in the Abstract too.  Fix everywhere.
