### ISSUE TITLE
Re: FL2 - It's not clear how encryption increases the level of assurance in the assertion. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#757]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.1, 4
 
**Comment (Include rationale for comment)**:  Re: FL2 - It's not clear how encryption increases the level of assurance in the assertion.
 
Perhaps the binding of the assertion to the claimant would be a better discriminator than encryption.

**Suggested Change**: Encryption should be selected depending on the privacy concerns associated with the particular assertion, independently of the robustness of the assertions. Encryption does not automatically make the confidence in the assertions more robust. Please consider adding to disucssion
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
-C explains the details as to why this increases the level for federation.
