### ISSUE TITLE
RE: FL2 -Timeliness of the assertions provided by the IdP could be used to increase security. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#758]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.1, 4
 
**Comment (Include rationale for comment)**:  RE: FL2 -Timeliness of the assertions provided by the IdP could be used to increase security.
 
Currently this seems to be missing from the discussion.

**Suggested Change**: Please consider adding to disucssion
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We will add informative language about the importance of assertion lifetimes but we will not create a normative requirement.
