### ISSUE TITLE
In the example given in this text, from the point of view of privacy, I would think that an agency would want to know whom 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#759]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.3, 1
 
**Comment (Include rationale for comment)**:  In the example given in this text, from the point of view of privacy, I would think that an agency would want to know whom they were releasing personal data to. 
 
Misleading example

**Suggested Change**: How could they justify not knowing who they are releasing the data to? I believe I would find a different example to use.

"Agency mission and risk tolerance will drive the most advantageous selection of xALs to minimize risk. This could include the selection of an IAL that is lower than the selected AAL. For example, suppose an agency establishes a “health tracker” application. In line with the terms of EO 13681 requiring “…that all agencies making personal data accessible to citizens through digital applications require the use of multiple factors of authentication…”, the agency is required to implement MFA at AAL2 or AAL3.
The EO also requires agencies employ “…an effective identity proofing process, as appropriate” when personal information is released. This does not mean that proofing at IAL2 or IAL3 (to match the required AAL) is necessary. In the above example, there may be no need for the agency system to know who the user actually is. Therefore, an ‘effective proofing process’ would be to not proof at all. In the past, an LOA3 assessment would equate to identity proofing the user at IAL2. This is no longer necessary and the agency is discouraged from performing any identity proofing, allowing the user of the health tracker system to be pseudonymous."

Suggest using a different example than a health tracker application. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Because of the authentication requirements, they know they are making it available to the same user that provided it, but they don't need to know the identity of the user.
