### ISSUE TITLE
The first paragraph’s example of different IAL and AAL requirements does not mention IAL. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#760]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.3, 1
 
**Comment (Include rationale for comment)**:  The first paragraph’s example of different IAL and AAL requirements does not mention IAL. 
 
Consider EO 13681

**Suggested Change**: EO 13681 requires MFA and an effective identity vetting process. It does not map ‘effective’ to any IAL levels, but IAL 1 (no vetting) is not such a process. So, MFA at AAL 2 and ‘an IAL that is lower…’ is not allowed. Please revise as necessary
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This paragraph:  EO 13681 also requires agencies employ “…an effective identity proofing process, as appropriate” when personal information is released. This does not mean that proofing at IAL2 or IAL3 (to match the required AAL) is necessary. In the above example, there may be no need for the agency system to know the actual identify of the user. In this case, an ‘effective proofing process’ would be to not proof at all. This allows the user of the health tracker system to be pseudonymous.

will be changed to:

EO 13681 also requires agencies employ “…an effective identity proofing process, as appropriate” when personal information is released. This does not mean that proofing at IAL2 or IAL3 (to match the required AAL) is necessary. In the above example, there may be no need for the agency system to know the actual identify of the user. In this case, an ‘effective proofing process’ would be **IAL1**. This allows the user of the health tracker system to be pseudonymous.
