### ISSUE TITLE
The last paragraph of Section 5.3.1 should emphasize that IAL 1 is appropriate so long as a user can access only the resume they submit, 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#761]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.3.1, 3
 
**Comment (Include rationale for comment)**:  The last paragraph of Section 5.3.1 should emphasize that IAL 1 is appropriate so long as a user can access only the resume they submit, but even then, other parts of the series claim this is not allowed.
 
Please consider apparent inconsistency

**Suggested Change**:  Also, the example discusses submitting resumes on behalf of another person, but IAL 1 would preclude the subject of that resume from being able to access it. Revise as necessary
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
As described, all proofing happens on the backend when the agency reviews the resume, not when it is submitted.  Therefore, IAL1 is appropriate for submitting my own or someone elses.  They don't care who submits online, hence the IAL1 selection.  All the business process of proofing is part of the hiring process, not the online service.
