### ISSUE TITLE
Suggest that the this should be rewritten using the term Pseudonymous Identifier defined in this document 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#762]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.4, 3
 
**Comment (Include rationale for comment)**:  Suggest that the this should be rewritten using the term Pseudonymous Identifier defined in this document  
 
Clarity

**Suggested Change**: or adding the defintion of Pseudonymity: "the use of a pseudonym; also :  the fact or state of being signed with a pseudonym" - Merriam-webster.com; or "Pseudonymity, a word derived from pseudonym, meaning 'false name', is a state of disguised identity. The pseudonym identifies a holder, that is, one or more human beings who possess but do not disclose their true names (that is, legal identities)." - Wikipedia.
"Pseudonymity is required, necessary, feasible, or important to stakeholders accessing the service." Suggest using an existing definiton in the document or adding one for Pseudonymity.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We will add the definition.
