### ISSUE TITLE
Certain obscure identity evidence might qualify as strong or superior according to a strict interpretation of the definition, while customary identity evidence might be weak. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#763]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: GENERAL, 
 
**Comment (Include rationale for comment)**:  Certain obscure identity evidence might qualify as strong or superior according to a strict interpretation of the definition, while customary identity evidence might be weak.  

 

**Suggested Change**: [See tbl 5.1] Strong evidence could be a baptismal certificate containing a picture of the subject as an infant and an identification number. Since baptismal records never expire the picture would be acceptable according to the definition. The church’s records might be under review by IRS to detect fraudulent charitable contribution claims. [See tbl 5.1] Superior evidence could be a smart card obtained by a foreign national from a foreign intelligence service. Memberships in the foreign intelligence service might be under review by the CIA.  Superior evidence could be a smart card issued to members of an obscure cult for entry into their gated compound. Memberships in the cult might be under review by the FBI.  A Maryland driver’s license issued to an undocumented immigrant who assumed an alias upon entry to the U.S. would be weak because no identity proofing was done to detect the alias.  A renewed Maryland driver’s license or a U.S. passport might be delivered by mail and received by the subject’s roommate or family member. Since the issuing process for the evidence did nothing to ensure against this occurrence, the evidence by definition fails to be strong. 

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is the rub with proofing, it's largely based on another proofing process, enter infinite loop where of course fraud lurks, hence much more to the proofing process than just accepting the id.  In addition, at least at the onset, agencies/CSP will pre-determine what evidence they will accept.  Because of the example here, baptismal records are likely not going to be acceptable evidence.
