### ISSUE TITLE
Para 2: The ‘example of minimally necessary’ or ‘core’ attributes doesn’t provide the context to indicate when the listed attributes might or might not be 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#765]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4, 2
 
**Comment (Include rationale for comment)**:  Para 2: The ‘example of minimally necessary’ or ‘core’ attributes doesn’t provide the context to indicate when the listed attributes might or might not be necessary or sufficient.
 
Clarity

**Suggested Change**:  Either clarify or remove.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is just an example and the section (to include resolution section) states it is up to the CSP/agency to determine the resolution attributes, not this document.
