### ISSUE TITLE
Figure 4-1: The diagram is confusing. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#766]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4, 1
 
**Comment (Include rationale for comment)**:  Figure 4-1: The diagram is confusing. 
 
Clarity

**Suggested Change**: What do the open circles represent, is there an implied vertical axis, what does the dotted path connecting the circles represent, and what represents the ‘corresponding sections’. Please  Either clarify or remove.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is a typical graphical representation of a 'user journey'; however, we notice that the figure name doesn't not specify it is a 'journey', we will update.

**Comment by paul-grassi** [comment]
Also related to #615
