### ISSUE TITLE
The ‘SHALL NOT statements related to identity proofing contradict the SP 800-63-3 note in section 5.3 that an agency can accept higher IAL than the 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#767]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.2, 3
 
**Comment (Include rationale for comment)**:  The ‘SHALL NOT statements related to identity proofing contradict the SP 800-63-3 note in section 5.3 that an agency can accept higher IAL than the application is assessed as requiring. 
 
Consistency

**Suggested Change**: They also contradict specific requirements for federal employees.
Specifically:
3 – SHALL and vague phrases like ‘minimum necessary’ and ‘based on best available practices’ typically do not go together. Rather, ‘SHALL justify the need for …’ seems more appropriate/achievable.  
5 – Contradicts 1 in that a CSP does not determine authorization (‘authorization assertions’). CSP only provide attribute assertions based on identity vetting (aka, identity attributes). Other (organizational affiliation, role, or assigned attributes) not based on identity vetting would not be managed by a CSP. 
7 - Practice statements should always be required, policies governing classes of credentialing services are optional.  Posting of the policy/practice statements should also be required to ensure that all applicants and relying parties can review the appropriateness of the procedures. Third party audit of a CSP against the practice statement should also be required. 
8 –It is not clear whether the ‘record’ is about the process of collecting information, or the logging of information collected. These should be separated and the language clear (use plural “identities of applicants” for processes; singular “any identity information” for logging requirements). If this is documenting processes, tie it to the practice statement requirement in (7)
11 – Do such measures also need to be documented in the policy/practice statements or in a privacy statement provided to the applicant?  

Please consider point made in revision.
Clarify ‘the service’ (establishing credentials, or the service for which credentials are being requested).
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Note that the ability to accept a higher IAL does not correlate with the identity proofing process used by the CSP.

**Comment by paul-grassi** [comment]
Regarding the comment: we will address the ability for RP's to federate with any CSP at or above the xAL they need, provided attribute sharing is in line with the desired xAL, not the proofed one.

Regarding the suggested changed:
3 - We can provide more information.  The goal is to ensure that CSP's just don't default to what is easy (i.e - collecting everything)
5 - Not our intention, so we will revise.  We want the CSP to only send attributes that are used for these purposes.
7 - noted, the requirement states this
8 - record includes logging, so we will be clearer
11 - yes, we will be clearer
