### ISSUE TITLE
Difficult to understand without first reading section 5. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#768]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.4, 1
 
**Comment (Include rationale for comment)**:  Difficult to understand without first reading section 5. 

 
This comment also applies to 800-63-B. Better order of presentation.

**Suggested Change**: Suggest including a summary to make this clearer. Emphasize in the summary that ADEQUATE, STRONG, and SUPERIOR are defined in 5.3 (but ADEQUATE needs to be defined), based on evidence provided, the ability to validate that evidence as authentic, and verifying that the applicant is the entity described by the evidence. Please consider in revisions
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Forward references were included in -63A, which at least tell the reader that additional information is to come. Similar references will be added in -63B to each of the authenticator types.
