### ISSUE TITLE
Section 4.4.1 includes SHALL statements, but IAL 2 providers are not required to meet the requirements (‘SHOULD meet … 4.4.1’). 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#769]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.4.1, 1
 
**Comment (Include rationale for comment)**:  Section 4.4.1 includes SHALL statements, but IAL 2 providers are not required to meet the requirements (‘SHOULD meet … 4.4.1’). 
 
Clarity

**Suggested Change**: This is confusing. Is it intended to say one of Section 4.4.1 or 4.4.2 is required, but 4.4.1 is preferred, or that that none are required, but if a claim for “Conventional Proofing” is made (IAL 2+?) the requirements of 4.4.1 must be met?  Suggest: A CSP SHALL implement identity…with Section 4.4.1’ as the recommended fix for this.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Need to adjust the normative language to convey that either 4.4.1 or 4.4.2 is required, and that 4.4.1 should be used unless circumstances dictate otherwise.
