### ISSUE TITLE
(Also see 4.4.1.5, pg 15 and 4.5.3, pg 15) Define third party data service, or at least explain the difference between this and a trusted 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#770]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.4.1.3, 1
 
**Comment (Include rationale for comment)**:  (Also see 4.4.1.5, pg 15 and 4.5.3, pg 15)  Define third party data service, or at least explain the difference between this and a trusted referee.
 
Clarity

**Suggested Change**: Consider suggested changes
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Related to #582

**Comment by paul-grassi** [comment]
Resolved via #666.
