### ISSUE TITLE
Is the use of enrollment codes required (i.e. for in-person proofing, must the enrollment code provided to the person directly if not sent to the 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#771]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.4.1.6, 1
 
**Comment (Include rationale for comment)**:  Is the use of enrollment codes required (i.e. for in-person proofing, must the enrollment code provided to the person directly if not sent to the address or record)? 
 
Clarity

**Suggested Change**: Is in-person vetting required if there is no address of record (e.g. for transient/homeless citizens), or is Section 4.4.2 a SHALL, or may it be impossible to achieve IAL 2 or above in this case? Why expand on this validation of address of record evidence and not others (name, DOB). Consider suggested changes
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #642
