### ISSUE TITLE
Multiple selections may need to be made within SP 800-53 to fully define necessary security controls. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#773]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.4.1.8, 1
 
**Comment (Include rationale for comment)**:  Multiple selections may need to be made within SP 800-53 to fully define necessary security controls.            
 
For example, personnel security controls are one way to mitigate against a rogue individual at a CSP.  Another example would be System and Communications Protection with a specified strength of the encrypted session. (Also see sectin 4.5.8, pg 16) Mitigation against disclosure threat/attach may require multiple security control, which should be referenced in SP 800-63A

**Suggested Change**: Provide a fuller accounting of all security control families requiring CSP consideration.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
I don't think in this draft we want to specify controls, but a statement about adding additional would be good.  In addition, it may be worth considering a -Alpha volume that does just this in the future.
