### ISSUE TITLE
What was the rationale for 6 character minimum? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#774]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.6, 1
 
**Comment (Include rationale for comment)**:  What was the rationale for 6 character minimum? 
 
Clarity

**Suggested Change**: The code is provided to the user, likely in a scannable format, so user’s ability to remember the code is irrelevant… (at least reference usability criteria if that’s the answer). Consider suggested changes
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The six-character option was provided for other sorts of enrollment for which a scanner might not be available or used. Since it's a one-time event and there is a timeout associated with it, this is sufficiently complex to resist impersonation threats.
