### ISSUE TITLE
Recommend IALs using aggregate evidence be defined in terms of table 5-3, and that table 5-3 be revised as recommended below. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#775]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Table 5-1, 5-2, and 5-3, 1
 
**Comment (Include rationale for comment)**:  Recommend IALs using aggregate evidence be defined in terms of table 5-3, and that table 5-3 be revised as recommended below.

 
Clarity

**Suggested Change**: Alternatively
- ADEQUATE strength identity evidence is not defined (WEAK and FAIR are defined, but neither, even by combining multiple pieces, can be considered equivalent to STRONG).
- Require two independent STRONG identity evidence 
- For IAL 3, require one SUPERIOR strength identity evidence and another, independent STRONG or SUPERIOR strength identity evidence. Also note that independent means physical security with anti-tamper and anti-forgery mechanisms that use independent mechanisms (SUPERIOR) or are provided by different issuers (for STRONG without physical security mechanisms) or authoritative sources using different sources.
 Consider suggested changes
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Wording of ADEQUATE vs. WEAK and FAIR were addressed in #518.

Suggest follow-up discussion to understand this issue better.
