### ISSUE TITLE
MAY appears too week (see #6) 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#778]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.3.3.2, 2
 
**Comment (Include rationale for comment)**:  MAY appears too week (see #6)
 
A trusted referee requires stronger requirements

**Suggested Change**: Change MAY to SHOULD or even SHALL
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
The MAY statement is redundant to requirements in section 4.  Will remove.
