### ISSUE TITLE
The strength of the mutually authenticated encryptioned session should be specified (see #8) 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#779]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.3.3.2, 2
 
**Comment (Include rationale for comment)**:  The strength of the mutually authenticated encryptioned session should be specified (see #8)
 
Completeness of requirement

**Suggested Change**: Specifity beyone 40 bit security is encouraged
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Should either specify authenticated protected channel (which requires approved crypto) or explicitly approved crypto (which establishes strength requirements)
