### ISSUE TITLE
In addition to confirming the binding of the referee to the applicant (which would associate the claimed identities), there should be an identity verification of 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#780]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.3.4, 3
 
**Comment (Include rationale for comment)**:  In addition to confirming the binding of the referee to the applicant (which would associate the claimed identities), there should be an identity verification of the referee to ensure they are the person claimed in the binding evidence. 
 
Completeness

**Suggested Change**: Consider suggested changes
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will add more detail to the statement: "The CSP SHALL determine the minimum evidence required to bind the relationship between the trusted referee and the applicant."

Need evidence to proof the referee and to bind relationship.
