### ISSUE TITLE
status needs to be qualified - primary authenticator status? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#781]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 6.1, 2
 
**Comment (Include rationale for comment)**:  status needs to be qualified - primary authenticator status?

 
Clarity

**Suggested Change**: Before issuance, the CSP SHALL verify the primary authenticator status. The CSP SHALL NOT issue an additional authenticator if status indicates any type of termination, disablement, revocation, or expiration. suggest adding 'of the primary authenticator' after 'status'
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE with new updates to Ch 6. See #597
