### ISSUE TITLE
This contradicts number 2. How do you know that an expired primary authenticator is being replaced? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#782]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 6.1, 6
 
**Comment (Include rationale for comment)**:  This contradicts number 2. How do you know that an expired primary authenticator is being replaced? 
 
Clarity

**Suggested Change**: 6. The CSP SHOULD set the expiration of the new authenticator to the expiration, if any, of the primary authenticator. There are instances where the new authenticator need not be directly tied to the expiration of the primary authenticator as the new authenticator can provide authentication services in its place, for example, while the expiring primary credential is being replaced.

Suggest either deleting the highlighed text or make it clearer what the author is trying to say.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE with new updates to Ch 6. See #597
