### ISSUE TITLE
Not talking about virtual in-person here correct? Do any of the AAL Levels apply to virtual in person? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#783]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 6.3, 2
 
**Comment (Include rationale for comment)**:  Not talking about virtual in-person here correct? Do any of the AAL Levels apply to virtual in person?

 
Clarity

**Suggested Change**: 2. The CSP SHOULD perform inperson issuance. This is important if the CSP needs to explicitly provision the authenticator to a trusted device and inperson is the only mechanism to ensure delivery and assurance.

Suggest indicating how a virtual in-person person gets their authenticator here.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
There is some clarifying language that can be added to account for virtual in-person.

**Comment by paul-grassi** [comment]
OBE with new updates to Ch 6. See #597
