### ISSUE TITLE
Re: Both examples for Social Engineering 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#784]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Table 7-1, 1
 
**Comment (Include rationale for comment)**:  Re: Both examples for Social Engineering
 
Examples suggest either a CSP has been infiltrated, or an individual has been turned.  I wouldn't consider CSP subversion to be Social Engineering.  A more appropriate examle is a rogue CPS masquerading to an applicant/subscriber.  The result of this attack is the exposure of PII to an authorized CSP.

**Suggested Change**: 1. For both Activity: Enrollment and Activity:Issuance replace both Social Engineering Examples with "A rogue CSP masquerading to an applicant/subscriber."
2. For both Activity: Enrollment and Activity:Issuance add a threat, "CSP Subversion" and use the examples currently listed for Social Engineering.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Will be adding a threat category for insider threats.

**Comment by paul-grassi** [comment]
@jimfenton is this insider threat AND phishing?
