### ISSUE TITLE
There are no definitions of the threats; only examples. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#785]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Table 7-1, 1
 
**Comment (Include rationale for comment)**:  There are no definitions of the threats; only examples.
 
Completeness

**Suggested Change**: Consider suggested changes
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This is an informative section, and the examples given provide an understanding of the threats involved. We would be receptive to more formal definitions if you have some to provide.
