### ISSUE TITLE
Re: Activity: Issuance; Threat: Disclosure: a sealed envelop is not truly secure 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#786]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Table 7-2, 1
 
**Comment (Include rationale for comment)**:  Re: Activity: Issuance; Threat: Disclosure: a sealed envelop is not truly secure
 
Tamper resistance is required.

**Suggested Change**: Change "physically mail in a sealed envelope" to "physically mail in a tamper resistant sealed envelope"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
@jimfenton maybe this should be a SHALL in both -A and -B?
