### ISSUE TITLE
Regarding social engineering (CSP Subversion per previous comment), one mitigation for both Enrollment and Issuance is dual-control. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#787]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Table 7-2, 1
 
**Comment (Include rationale for comment)**:  Regarding social engineering (CSP Subversion per previous comment), one mitigation for both Enrollment and Issuance is dual-control. 
 
1. If suggested Table 7-1 changes are made, Table 7.2 will need to be changed to maintain consistency
2. Dual Control should be included as a valid mitigation of CSP Subversion

**Suggested Change**: For both Activity: Enrollment and Activity:Issuance add a threat, "CSP Subversion" with mitigation "Dual Control"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Will be addressed with #784
