### ISSUE TITLE
Suggest adding why the data is being collected to this sentence. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#788]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 9.1, 2
 
**Comment (Include rationale for comment)**:  Suggest adding why the data is being collected to this sentence. 
 
Completeness. 

Something like: "Clearly explain to users who is collecting, retaining and why the information is being collected, as well as  providing an indication of where the data is being stored."

Also not sure why they would need to know the path the data will take except maybe where the data would be stored (entity.com site vs. entity.gov)

**Suggested Change**: make suggested changes.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
