### ISSUE TITLE
Suggest adding information on any security requirements for protecting the authenticator as well. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#789]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 9.3, 8
 
**Comment (Include rationale for comment)**:  Suggest adding information on any security requirements for protecting the authenticator as well.

 
Completeness

**Suggested Change**: "If users receive the authenticator during the enrollment session, provide users information on the use and maintenance of the authenticator. For example, instructions for use (especially if there are different requirements for first-time use or initialization), information on authenticator expiration, and what to do if the authenticator is lost or stolen." make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
