### ISSUE TITLE
(Also see section 4.2.3 and 4.3.3) Explain what re-authentication is and why it is required (see section 7.2). 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#791]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.1.3, 1
 
**Comment (Include rationale for comment)**:  (Also see section 4.2.3 and 4.3.3) Explain what re-authentication is and why it is required (see section 7.2).
 
Completeness

**Suggested Change**: Consider suggested changes
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Will add forward references to 7.2 and give more context there about why reauthentication is needed.
