### ISSUE TITLE
AAL 2 communications also occur with RP and CSP. Why is verifier singled out here? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#793]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.2.2, 1
 
**Comment (Include rationale for comment)**:  AAL 2 communications also occur with RP and CSP. Why is verifier singled out here? 

 
Completeness

**Suggested Change**: Consider suggested changes
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Verifier is a role; see #729.

The use of authenticated protected channels is desirable for other communications, e.g., between subscriber and RP, but that is outside the scope of authentication and this document.
