### ISSUE TITLE
Channel is not typically a participant in communication, but is what protects the communications. Explain “between the claimant and channel” 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#795]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.3.2, 1
 
**Comment (Include rationale for comment)**:  Channel is not typically a participant in communication, but is what protects the communications. Explain “between the claimant and channel” 
 
Completeness

**Suggested Change**: Consider suggested changes
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Analogous issue to #790. Looks like this is correct for section 4.2.2, though.
