### ISSUE TITLE
This section does not address privacy protections resulting from authentication, such as what might result from use of the credentials, or implementing access controls based 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#796]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.4, 1
 
**Comment (Include rationale for comment)**:  This section does not address privacy protections resulting from authentication, such as what might result from use of the credentials, or implementing access controls based on identity attributes received from the CSP.   
 
Completeness

**Suggested Change**: Consider suggested changes
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
General privacy aspects of authentication probably belongs better in the top-level document, -63-3. We will add a short privacy introduction there.
