### ISSUE TITLE
Contains rows that are not addressed in section 4. At least introduce the concepts before summarizing the requirements. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#797]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Table 4.3, 1
 
**Comment (Include rationale for comment)**:  Contains rows that are not addressed in section 4. At least introduce the concepts before summarizing the requirements. 
 
Consistency

**Suggested Change**: Consider suggested changes
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Verifier compromise resistance seems not to have been mentioned earlier in Section 4, and should be.
