### ISSUE TITLE
We agree with the requirements in this section, with one reservation -- CSP chosen 6 digit PINs (Also see seciton A.4, gp 46) 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#798]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.1.1, 1
 
**Comment (Include rationale for comment)**:  We agree with the requirements in this section, with one reservation -- CSP chosen 6 digit PINs (Also see seciton A.4, gp 46)
 
CSP chosen or not, this is still pretty short, very guessable in our opinion ***

**Suggested Change**: Please consider longer passwords without restriction, excpet for blacklisting common passwords
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The 6-digit CSP-chosen PIN requirement was driven by two things:
- Use of 6-digit PINs by PIV
- Desire not to set different requirements for memorized secrets used as second factors vs. those used as single-factor memorized secrets at AAL1

A 6-digit randomly-generated PIN has about 20 bits of entropy. While we are avoiding making an estimate of the entropy of 8-character user-generated memorized secrets (depends on the blacklist, for example), they are probably comparable. Accordingly, we have established rate-limiting requirements to address online attacks, and salting and hashing requirements to at least partially mitigate offline attacks.

We recognize and continue to emphasize that memorized secrets as a single factor has limited security, and that two-factor authentication should be used whenever there is any sensitivity to the application.

Thank you for your supportive comment on other aspects of memorized secrets.
