### ISSUE TITLE
usnistgov/800-63-3

### ISSUE THREAD

**Issue by rguduputi** [usnistgov/800-63-3#8]
Organization:1

5.3.2. Knowledge Based Verification Requirements

800-63-3 / sp800-63a / sec5_proofing.md 

I am surprised to see Knowledge Based Verification Requirements in the this draft. KBV/KBA refers to asking "secret” questions that only applicant can supposedly answer to prove their identity for remote identity proofing/authentication. 
 In my opinion KBV/KBA is less effective as a verification of identity especially with growing 
 number of data breaches. It is no longer an effective method. It is not good idea to use KBV/KBA for IAL 2/IAL3. it is possibly can be used for IAL 1.

I like to see some alternatives to Knowledge Based Authentication/Verification in this draft.

**Comment by paul-grassi** [comment]
There are many alternatives to KBV in this document, to include micro-payment verification.  We also tightly scoped the acceptable data sources that KBV can be used for, as well as the scenarios where it would be partially acceptable.  It is not the only, or preferred, approach in -A. @rguduputi any additional alternatives you would recommend is greatly appreciated.
