### ISSUE TITLE
Sections 5.1.7.2 and 5.1.9.2 appear nearly identical. Recommend combining sections highlighting additional detail for Multi-Factor Device Verifiers. (Also see section 5.1.9.2 pg 26) 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#800]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.7.2, 1
 
**Comment (Include rationale for comment)**:  Sections 5.1.7.2 and 5.1.9.2 appear nearly identical.  Recommend combining sections highlighting additional detail for Multi-Factor Device Verifiers. (Also see section 5.1.9.2 pg 26)
 
Key is the question as to whether the verifier in each of the four cases (SF Software, SF hardware, MF software, and MF hardware) could be the same.  

**Suggested Change**: Please clarify addition requirements in the Multi-Factor verifer case
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
There seem to be differences in wording between 5.1.7.2 and 5.1.9.2 that are not significant from a requirements standpoint. The wording will at least be unified.
