### ISSUE TITLE
(also see section 5.1.8) In order to understand software defined keys as ‘something you have’, there has to be some binding (as in out-of-band mechanisms) 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#801]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.6, 1
 
**Comment (Include rationale for comment)**:  (also see section 5.1.8)  In order to understand software defined keys as ‘something you have’, there has to be some binding (as in out-of-band mechanisms) to the device.
 
 From a verifier’s perspective, there is no way to determine whether the device is actually associated to the user to verify that the authenticator is controlled by the subscriber. What requirements on the CSP and subscriber are imposed to provide any confidence that the subscriber controls the device and that the device retains control of the key? At a minimum, FIPS 140-2 level 2 validated software container should be required, or generation and storage of the key in accordance with NIAP MDF protection profile using a hardware defined root encryption key (or equivalent).

**Suggested Change**: Consider suggested changes
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Storage requirements for keys depend on the authentication assurance level, and are specified in Sections 4.2.2 and 4.3.2.

Will re-examine whether the current requirements are sufficient.

**Comment by jimfenton** [comment]
Upgrading to FIPS 140 Level 2, which requires that the user authenticate to gain access to the authentication secret, would by its nature make the authenticator multi-factor (something you know + something you have, the private key). Therefore requiring FIPS 140 Level 2 for this authenticator would be contradictory. Agencies are free to disallow use of authenticators that do not meet their requirements.
