### ISSUE TITLE
AL - Reversing suspension should require more than successful authentication (at least if the subscriber uses the suspended authenticator, not to mention that compromise of 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#805]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 6.2, 2
 
**Comment (Include rationale for comment)**:  AL - Reversing suspension should require more than successful authentication (at least if the subscriber uses the suspended authenticator, not to mention that compromise of one might be correlated with compromise of others).
 
 Either specify that the authentication is with a valid (not suspended) authenticator, or explain what is required to confirm that the actual subscriber is in control of the authenticator.  If it is indeed reversible, then simple authentication with the credential may not be enough, especially in the case of AAL2 or AAL3. 

**Suggested Change**: Please consider the  option is to set a time period for the suspension, and after that time has passed, the suspension is no longer reversible.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
"successfully authenticates" assumed that the suspended authenticator wouldn't be successful, but that could be made clearer.

We will not specify a time period for the suspension, but will allow the CSP to set one if they wish to do so.
