### ISSUE TITLE
Explain why destruction after expiration/termination is required. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#806]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 6.4, 2
 
**Comment (Include rationale for comment)**:  Explain why destruction after expiration/termination is required. 
 
Completeness

**Suggested Change**: Consider suggested changes
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
It is because the certification attributes on the authenticator will probably not have expired when revocation or termination takes place. This will be made clearer.
