### ISSUE TITLE
How is a session secret stored in software considered ‘what you have’, when a verifier has no way to know that the session secret is 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#807]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 7.2, 2
 
**Comment (Include rationale for comment)**:  How is a session secret stored in software considered ‘what you have’, when a verifier has no way to know that the session secret is bound to a device and the device is in the control of the subscriber? 
 
Completeness

**Suggested Change**: Consider suggested changes
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The session (typically a TLS session) is established by the creation of an authenticated protected channel through which the user authenticates. The session secret is bound to the subscriber through that process, but at AAL2 and above we need a second factor. The statement here is explaining that something other than 'what you have' is needed to do two-factor reauthentication, such as the reentry of a memorized secret.
