### ISSUE TITLE
Offline attacks: We are happy to see the requirement in Section 5.1.1, which states that passwords must be salted. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#809]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: A.2, 3
 
**Comment (Include rationale for comment)**:  Offline attacks:  We are happy to see the requirement in Section 5.1.1, which states that passwords must be salted.  
 
While we agree that it is common knowledge and good practice to salt passwords, we have seen a disturbing number of systems that don’t.  Is there a mechanism to check a claim? Our observations suggest password salting requirements cannot be overemphasized.

**Suggested Change**: Suggest emphasis of password salting requirement
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Thank you for the comment. We are not aware of general techniques to verify that password salting/hashing has been done, although occasionally one can infer that if, for example, a verifier sends the subscriber their password in response to a password reset request. Fortunately these instances are rare. Often the use of poor memorized secret storage is first visible when the site has been breached.

We are not sure how to further emphasize this, but are open to more specific suggestions.
