### ISSUE TITLE
IdP is the generic label; a CSP can be an example of an IdP indicated by parenthesis. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#810]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: Figure 4-1, 1
 
**Comment (Include rationale for comment)**:  IdP is the generic label; a CSP can be an example of an IdP indicated by parenthesis. 
 
In many  use cases, the CSP as defined in this series will not be the IdP providing assertions to RPs (e.g., the CSP and authoritative source for attributes within DoD are separate, and each of three tiers of the DODIN architecture will be providing additional attributes for RPs).

**Suggested Change**: Reverse CSP and IdP in the upper right block. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
A new version of the diagram has been created that just shows IdP. The fact that the IdP often corresponds to the CSP is explained at the beginning of Section 2.

Fixed by #578.
