### ISSUE TITLE
Suggest define/represent federation members used in the various models and provide separate diagrams for each model identifying all members. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#811]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: Figure 4-1, 1
 
**Comment (Include rationale for comment)**:  Suggest define/represent federation members used in the various models and provide separate diagrams for each model identifying all members.

 
Clarity

**Suggested Change**: - Use at least two IdPs and RPs in each diagram to clarify that federations may involve multiple IdPs.
- Also address when federation uses a single IdP for multiple RPs (e.g., in Kerberos, Privileged Access Management, or single-sign-on mechanisms). 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
I'm not fond of making the presentation models noisy, but an overall diagram may help. @kboeckl let's discuss in case we have to make a new diagram.

**Comment by jricher** [comment]
I would not change the diagrams. The essential relationship remains pairwise, but multiple pairings may exist in parallel.
