### ISSUE TITLE
The directionality of blacklists seem to be backwards. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#814]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 4.1.5, 1
 
**Comment (Include rationale for comment)**:  The directionality of blacklists seem to be backwards. 
 
The IdPs in a federation control the identity information and may or may not pass that information to RPs. Blacklists would indicate which RPs are precluded from receiving information, not indicating which IdPs are restricted from sending information. The generic use of ‘parties’ is confusing. 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Agree, this section is really about CSPs sending information to RPs and under what circumstances they may do so. Also consider renaming the section.

**Comment by jricher** [comment]
Blacklists are not unique to IdPs: RPs can also blacklist which IdPs they are not willing to accept identity data from.

**Comment by paul-grassi** [comment]
Let's keep this as accepted as, at a minimum, we can make the exact point @jricher makes to avoid confusion.  We also plan on fixing parties or making it clear in the document what we mean so we can avoid always writing IDP, RP, Proxy, etc.
