### ISSUE TITLE
Key binding: asserting the public key or key identifier which a subscriber used to authenticate to the IdP does not ‘demonstrate’ the binding. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#815]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 5, 4
 
**Comment (Include rationale for comment)**:  Key binding: asserting the public key or key identifier which a subscriber used to authenticate to the IdP does not ‘demonstrate’ the binding. 
 
A binding is only demonstrated through the use of a digital signature. A subscriber’s digital signature is not required/suggested to be part of the assertion or metadata.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
I can see where this terminology may be confusing -- this is the public key or key identifier that was used in creating the signature, and not the demonstration of the binding itself. That comes from the signature that is one of the required metadata.

Will reword to make clearer.

**Comment by jricher** [comment]
The subscriber's signature is not carried in the assertion itself, it is demonstrated separately at the RP.
