### ISSUE TITLE
Explain how using the IdP to verify claimant’s response to a challenge is different from a bearer’s assertion: is the challenge generated by the RP, 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#816]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 5.1.2, 2
 
**Comment (Include rationale for comment)**:  Explain how using the IdP to verify claimant’s response to a challenge is different from a bearer’s assertion: is the challenge generated by the RP, is it performed in a separate (back channel) transaction between the IdP and RP? 
 
As specified, it could be computed during the initial exchange between the IdP and subscriber and included in the original assertion – this is no better than a bearer assertion since the RP has no proof that the actual subscriber was involved.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
This is an incorrect reading of the requirement: the *RP* verifies the response, **not** the *IdP*. This can be made more explicit:

> A holder-of-key assertion contains a reference to a key possessed by and representing the subscriber.The subscriber SHALL prove possession of that key to the RP in addition to presentation of the assertion itself.
