### ISSUE TITLE
Symmetric keys shared between the RP and IdP should be updated periodically (using a secure process, or performing a partial re-registration) 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#817]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 5.2.2, 1
 
**Comment (Include rationale for comment)**:  Symmetric keys shared between the RP and IdP should be updated periodically (using a secure process, or performing a partial re-registration)
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Does this only apply to symmetric keys or should it also apply to asymmetric?
