### ISSUE TITLE
Clarify when encryption SHALL be used (not only are there conflicting SHALL and MAY, discussion in other parts of the series include requirements to encrypt 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#818]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 5.2.3, 1
 
**Comment (Include rationale for comment)**:  Clarify when encryption SHALL be used (not only are there conflicting SHALL and MAY, discussion in other parts of the series include requirements to encrypt PII when contained in assertions.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
I understand what we are doing in the doc, but this is a good point for clarity purposes.

**Comment by jricher** [comment]
Encryption is used at higher FALs, and it's especially important when the assertion is passed through third parties (like the browser) as in older federation technologies like SAML, but with OIDC and using the back channel, you have only two parties seeing the information over a direct connection protected by TLS.
