### ISSUE TITLE
The clause ‘if provided’ in reference to the audience of an assertion contradicts the metadata requirements provided in section 5. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#819]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 5.2.4, 1
 
**Comment (Include rationale for comment)**:  The clause ‘if provided’ in reference to the audience of an assertion contradicts the metadata requirements provided in section 5. 
 
A general statement that RP SHALL reject an assertion missing any of the required metadata should be made.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
There is another similar comment from NSA

**Comment by jricher** [comment]
Holdover from when explicit audience targeting was dependent on FAL instead of required across all FALs.
