### ISSUE TITLE
Sentence is important but is lost after table. The CSP MAY use KBV to verify the identity of an applicant provided the requirements in Section 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#821]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.3.1, 2
 
**Comment (Include rationale for comment)**:  Sentence is important but is lost after table. The CSP MAY use KBV to verify the identity of an applicant provided the requirements in Section 5.3.2 are met.
 
Clarity

**Suggested Change**: Suggest moving it above the table.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
May be redundant as well so consider deleting.
