### ISSUE TITLE
The individual may provide their own authenticator(s), so the CSP will revoke the credential the authenticator is bound to, such that authentication is no longer 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#824]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 6, 5
 
**Comment (Include rationale for comment)**:  The individual may provide their own authenticator(s), so the CSP will revoke the credential the authenticator is bound to, such that authentication is no longer possible with that CSP; authenticator will can be used by the individual at other CSPs.
 
Grammar

**Suggested Change**: make suggested change
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE via the changes to Ch 6.  See #597
