### ISSUE TITLE
Not sure what is meant by the second sentance here. 'to be at the same level, in order to...?' 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#825]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 6.1, 1
 
**Comment (Include rationale for comment)**:  Not sure what is meant by the second sentance here. 'to be at the same level, in order to...?'
 
The IAL of the credential bound to the new authenticator SHALL be at or below the primary IAL. In most cases the IALs are expected to be at the same level, in order to benefit from the reuse of the original identity proofing event(s).'

**Suggested Change**: make suggested change
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Good catch.  The IAL should remain the same.

**Comment by paul-grassi** [comment]
OBE with new Chapter 6. See #597
