### ISSUE TITLE
The items numbers 4 and 6 appear inconsistent 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#827]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 6.1, 4
 
**Comment (Include rationale for comment)**:  The items numbers 4 and 6 appear inconsistent
 

**Suggested Change**: please clarify
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE with Ch 6 changes. See #597
