### ISSUE TITLE
This should probably be a note in a box like many of the other notes. The 'though', which makes the sentence harder to read, could 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#830]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 8.1.1, 1
 
**Comment (Include rationale for comment)**:  This should probably be a note in a box like many of the other notes. The 'though', which makes the sentence harder to read, could be removed in that case.
 
Higlighting key point. "Note though that evidence requirements at the higher IALs preclude the usage of the SSN or the Social Security Card as acceptable identity evidence."

**Suggested Change**: make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jamiedanker-nppd** [comment]
Delete though and use suggested format like notes on redress etc.
