### ISSUE TITLE
Redundant to text in previous paragraph and the next paragraph. Suggest combining these three paragraphs into one paragraph. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#832]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 8.3, 2
 
**Comment (Include rationale for comment)**:  Redundant to text in previous paragraph and the next paragraph. Suggest combining these three paragraphs into one paragraph.
 
Care should be taken to ensure that use of attributes collected and maintained in the identity proofing process are limited to its original purpose for collection. If use of such information does not fall within uses related to identity proofing, authentication, authorization or attribute assertions, or to comply with law or legal process, the CSP must provide notice and obtain consent from the subscriber."

**Suggested Change**: Change as suggested.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Will delete the first two sentences in 8.3 paragraph 2.
