### ISSUE TITLE
Already spelled out in section 4 [4.2.13.a] no need to do it again here. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#833]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 8.3, 2
 
**Comment (Include rationale for comment)**:  Already spelled out in section 4 [4.2.13.a] no need to do it again here.
 
format: "Agencies should consult their Senior Agency Official for Privacy (SAOP) if there are questions about whether proposed agency uses fall within the scope of these uses."

**Suggested Change**: take out expansion of acronym.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jamiedanker-nppd** [comment]
Change to SAOP acronym
