### ISSUE TITLE
Redundant text in previous two paragraphs. Suggest combining these three paragraphs into one paragraph. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#834]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 8.3, 2
 
**Comment (Include rationale for comment)**:  Redundant text in previous two paragraphs. Suggest combining these three paragraphs into one paragraph.
 
"Rather if there are uses outside the bounds of these explicit purposes, the subscriber should be provided with a meaningful way to understand the purpose for additional uses, and the opportunity to accept or decline."

**Suggested Change**: Suggest combining these three paragraphs into one paragraph.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
See #832
