### ISSUE TITLE
Break into two sentences for ease of understanding and reading. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#836]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 9, 4
 
**Comment (Include rationale for comment)**:  Break into two sentences for ease of understanding and reading. 
 
"Performing a usability evaluation on the enrollment and identity proofing process is critical. It should be conducted with representative users, realistic goals and tasks, and appropriate contexts of use."

Original text: "Performing a usability evaluation on the enrollment and identity proofing process is critical, conducting it with representative users, realistic goals and tasks, and appropriate contexts of use."

**Suggested Change**: Suggest breaking into two sentences for ease of understanding and reading. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
