### ISSUE TITLE
Concerning the sentence: "The goal of this section is to raise implementers’ awareness of usability considerations associated with enrollment and identity proofing (for usability considerations 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#837]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 9, 5
 
**Comment (Include rationale for comment)**:  Concerning the sentence: "The goal of this section is to raise implementers’ awareness of usability considerations associated with enrollment and identity proofing (for usability considerations for typical authenticator usage and intermittent events, see 800-63-3B)."
 
I would move this to the first sentence in the section. I would also move the statement: "In this section, the term “users” means “applicants” or “subscribers.” to the first paragraph as well as this describes why all of a sudden applicants became users.

**Suggested Change**: Make suggested changes.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by ychoong** [comment]
The paragraph was moved to the beginning of the intro. The assumption was remained in the original place for consistency across 800-63A, B, and C.

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
