### ISSUE TITLE
Suggest changing 'is' to 'should be' in this sentence: "Ideally, sufficient information is provided to enable users to answer their own enrollment preparation questions without 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#839]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 9.1, 2
 
**Comment (Include rationale for comment)**:  Suggest changing 'is' to 'should be' in this sentence: "Ideally, sufficient information is provided to enable users to answer their own enrollment preparation questions without outside intervention."
 
fit in better with what the paragraph is conveying.

**Suggested Change**: make suggested changes.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
