### ISSUE TITLE
Suggest moving this up to after the first sentence in this section. "Usability considerations specifically for each step are detailed below." 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#840]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 9.1, 7
 
**Comment (Include rationale for comment)**:  Suggest moving this up to after the first sentence in this section. "Usability considerations specifically for each step are detailed below." 
 
The sentence gets lost here. Also may want to change "...are detailed below." to "... are detailed in sections 9.2-9.4."

**Suggested Change**: make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
