### ISSUE TITLE
Suggest deleting 'the' before 'users'' and making 'perspectives' plural unless it is the intention that the 'user' is singular. If this is the case then 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#841]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 9.2, 2
 
**Comment (Include rationale for comment)**:  Suggest deleting 'the' before 'users'' and making 'perspectives' plural unless it is the intention that the 'user' is singular. If this is the case then 'user' should be singular "user's"
 
"This includes making users aware of exactly what identity evidence will be required, conveyed from the users’ perspective, not the implementers’ perspectives."

**Suggested Change**: make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
