### ISSUE TITLE
Suggest adding the sentence: "If KBV is used, the following consideration should be addressed:" after the original text. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#842]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 9.3, 3
 
**Comment (Include rationale for comment)**:  Suggest adding the sentence: "If KBV is used, the following consideration should be addressed:" after the original text.
 
Original text - "Avoid using KBV since it is extremely problematic from a usability perspective. KBV tends to be error prone and frustrating for users given the limitations of human memory."

**Suggested Change**: make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
