### ISSUE TITLE
Need to put the bullets in a list in this paragraph. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#843]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 9.4, 2
 
**Comment (Include rationale for comment)**:  Need to put the bullets in a list in this paragraph. 
 
"Usability considerations for post-enrollment include: * Minimize the amount of time that users wait for their authenticator to arrive. Shorter wait times will allow users to access information systems and services more quickly. * Inform users whether they need to go to a physical location to pick up their authenticators. The previously identified usability considerations for appointments and reminders still apply. * Along with the authenticator, give users information relevant to the use and maintenance of the authenticator; this may include instructions for use, especially if there are different requirements for first-time use or initialization, information on authenticator expiration, and what to do if the authenticator is lost or stolen."

**Suggested Change**: make suggested changes.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
