### ISSUE TITLE
What process is authentication central to? Is it central to digital identity or to digital authentication? Suggest qualifying which process is meant. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#845]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 2, 2
 
**Comment (Include rationale for comment)**:  What process is authentication central to? Is it central to digital identity or to digital authentication? Suggest qualifying which process is meant.
 
The ongoing authentication of subscribers is central to this process.

**Suggested Change**: Make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Something like, "central to the process of associating a subscriber with their online activity."
