### ISSUE TITLE
Suggest making these references to FIPS 140 without the brackets. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#847]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.1.2, 2
 
**Comment (Include rationale for comment)**:  Suggest making these references to FIPS 140 without the brackets.
 
They distract the reader. Also earlier and later in the document you use this with out the brackets. there are several more instances where the brackets are used when referring to levels. Probably do not need the hyperlinks to documents outside of any of the documents in this review and do not need hyperlinks to the references either.

"Verifiers operated by government agencies at AAL1 SHALL be validated to meet the requirements of [FIPS 140] Level 1."

**Suggested Change**: Make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The introductory statement at the beginning of Section 4 about FIPS 140 should be sufficient.
