### ISSUE TITLE
Re: Reauthentication - Need to make key words like SHALL, MUST, etc. all caps in Table 4-3. AAL Summary of Requirements 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#849]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: Table 4-3, 1
 
**Comment (Include rationale for comment)**:  Re: Reauthentication - Need to make key words like SHALL, MUST, etc. all caps in Table 4-3. AAL Summary of Requirements
 
Format - 
Conforms with format of the same basic table in SP 800-63A.

**Suggested Change**: Make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Table 4-3 is non-normative, but updating the capitalization for consistency.
