### ISSUE TITLE
Use of term 'authentication' in OOB context

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#851]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.3.2, 2
 
**Comment (Include rationale for comment)**:  Suggest that this note is associated with section 5.1.3.1 and should be moved up unless the term 'authentication' is incorrect and this should read: Note: Out-of-band 'verification' using PSTN…
 
Highlighting key point/Correction of text. 
Original text: 
"Note: Out-of-band authentication using the PSTN (SMS or voice) is discouraged and is being considered for removal in future editions of this guideline."

**Suggested Change**: Make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This note is in 5.1.3.2 because the acceptable types of OOB authentication constitute a verifier requirement.

The wording is slightly off, though. Perhaps "Authentication using the PSTN (SMS or voice) as an out-of-band channel is discouraged..."
