### ISSUE TITLE
Emphasize limited use of biometrics

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#856]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.3, 2
 
**Comment (Include rationale for comment)**:  Suggest adding 'limited' to this sentence: "Therefore, the 'limited' use of biometrics for authentication is supported with the following requirements and guidelines:"
 
Clarity

**Suggested Change**: Make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Not adding the quotes, though.
