### ISSUE TITLE
Section title: 'Verifier Impersonation Resistant Protocols' vs. 'Verifier Impersonation Resistance'

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#857]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.5, 1
 
**Comment (Include rationale for comment)**:  Suggest changing this section title to '5.2.5. Verifier Impersonation Resistant Protocols" which better matches the discussion in the section.
 
Correctness

**Suggested Change**: Make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Verifier impersonation resistance is a characteristic of more than just the protocol, but the choice of authenticator type as well. Will re-examine and see if the discussion puts too much emphasis on protocols.

**Comment by jimfenton** [comment]
Prefer to leave the current section name because the section also deals with other aspects of verifier impersonation resistance, such as the choice of authenticator type.
