### ISSUE TITLE
Section title: "Verifier Compromise Resistance" vs 'Verifier Compromise Resistant Protocols and Techniques'

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#858]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.2.7, 1
 
**Comment (Include rationale for comment)**:  Suggest changing this section "5.2.7. Verifier Compromise Resistance" to '5.2.7. Verifier Compromise Resistant Protocols and Techniques'. This better reflects the text and reinforces the use of the word resistant.
 
Format/Clarity

**Suggested Change**: Make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Above commit cited the wrong issue number and has been corrected.

**Comment by jimfenton** [comment]
The current section name has the right connotation and is shorter and therefore preferred.
