### ISSUE TITLE
Update reference to ‘table 5’ to ‘Table 8-1’ 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#867]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 8.2, 2
 
**Comment (Include rationale for comment)**:  Update reference to ‘table 5’ to ‘Table 8-1’
 
valid reference

**Suggested Change**: Consider suggested changes
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Already fixed by #579.
