### ISSUE TITLE
Suggest adding 'the' before 'number' in this sentence: 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#868]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 10.1, 4
 
**Comment (Include rationale for comment)**:  Suggest adding 'the' before 'number' in this sentence:
 
Provide clear, meaningful feedback on number of remaining allowed attempts. Readability

**Suggested Change**: Make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
