### ISSUE TITLE
Suggest this text should be a bulletized list as shown or something like it. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#869]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 10.2.1, 3
 
**Comment (Include rationale for comment)**:  Suggest this text should be a bulletized list as shown or something like it.
 
Usability considerations for intermittent events include: 
* When users create and change memorized secrets: 
* Clearly communicate information on
how to create and change memorized secrets. 
* Clearly communicate memorized secret requirements, as specified in Section 5.1.1. 
* Allow at least 64 characters in length to support the use of passphrases. Encourage users to make memorized secrets as lengthy as they want, using any characters they like (including spaces), thus aiding memorization. 
* Do not impose other composition rules (e.g. mixtures of different character types) on
memorized secrets. 
* Do not require that memorized secrets be changed arbitrarily (e.g., periodically) unless there is a user request or evidence of authenticator compromise. (See Section 5.1.1 for additional information) 
* Provide clear, meaningful and actionable feedback when chosen passwords are rejected (e.g., when it appears on a “black list” of unacceptable passwords or has been used previously). Advise users that they need to select a different secret because their previous choice was commonly used.

**Suggested Change**: Make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by ychoong** [comment]
It is already a bulleted list.
