### ISSUE TITLE
Add 'the' before 'number'. Readability. This should be stated for every authenticator that provides more than one attempt at authenticating. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#870]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 10.4, 5
 
**Comment (Include rationale for comment)**:  Add 'the' before 'number'. Readability. This should be stated for every authenticator that provides more than one attempt at authenticating.
 
Clarity - Provide clear, meaningful feedback on number of remaining allowed attempts.

**Suggested Change**: Make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
