### ISSUE TITLE
Introduce and Use consistent language to refer to the ‘members of federation’ used in the various models. Avoid generic language such as ‘parties’, ‘external parties’, 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#873]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 4.1, 1
 
**Comment (Include rationale for comment)**:  Introduce and Use consistent language to refer to the ‘members of federation’ used in the various models. Avoid generic language such as ‘parties’, ‘external parties’, which can be confusing.
 
Clarity

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via PR #1790
