### ISSUE TITLE
Suggest adding 'levels' after 'IAL and AAL' in this sentence. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#876]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 4.1.3, 2
 
**Comment (Include rationale for comment)**:  Suggest adding 'levels' after 'IAL and AAL' in this sentence.
 
"Federation authorities SHALL establish parameters regarding expected and acceptable IAL and AAL in connection with the federated relationships they
enable."

**Suggested Change**: Make suggested changes.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
The "L" stands for "Level" in both "IAL" and "AAL", so adding it would be redundant.

**Comment by paul-grassi** [comment]
We can pluralize the acronyms. IALs, AALs.  We've done that elsewhere.
