### ISSUE TITLE
Suggest further explaination of federation members (IdP/CSP used by an RP, specific to the subscriber, or RPs serviced by an IdP?) 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#877]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 4.1.2, 1
 
**Comment (Include rationale for comment)**:  Suggest further explaination of federation members (IdP/CSP used by an RP, specific to the subscriber, or RPs serviced by an IdP?)
 
Clarity

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
There is a similar comment to be clear about what 'members' means.

**Comment by jricher** [comment]
"Federation membership" applies to the set of IdPs and RPs that can talk to each other per rules of the federation. By extension, the users at the IdPs and the services at the RPs are included in the federation as well, but really it's the list of IdPs and RPs that we're concerned with.
