### ISSUE TITLE
Suggest the section introduction should be moved up to section 4. It helps explain the concept of federation and applies to all models. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#878]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 4.1.5, 1
 
**Comment (Include rationale for comment)**:  Suggest the section introduction should be moved up to section 4. It helps explain the concept of federation and applies to all models.
 
Better order of presentation

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Section 4.1.5 doesn't really relate to specific federation models, so probably doesn't belong in Section 4.1. We will move it, probably in connection with a move of Section 7 to Section 4 (see #746) to a place more suited for general requirements.
