### ISSUE TITLE
‘Namespace control’ is not defined in any of the documents within the series, but is being used (as a recommended or typical situation) within a 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#879]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 5, 3
 
**Comment (Include rationale for comment)**:  ‘Namespace control’ is not defined in any of the documents within the series, but is being used (as a recommended or typical situation) within a requirement for federated IdPs.
 
This is an important concept for federation that should be defined and made a formal recommendation (‘SHOULD…’, rather than ‘usually…’.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
The intent here is that the subject is determined by the issuer and is taken in context with the issuer, not assumed to be a universally unique name for the subscriber.
