### ISSUE TITLE
4.3.1 Difference between "key" and "password", Inaccuracy in password spaces

### ISSUE THREAD

**Issue by UppaJung** [usnistgov/800-63-3#88]
**Organization**: Microsoft

**Type**: 2

**Reference (Include section and paragraph number)**:
 4.3.1

**Comment (Include rationale for comment)**:
 “As such, keys are something the subscriber has, while passwords are something he or she knows”

This is not clear.  What does it mean to have something?  You have a password in your memory.  The difference between a password and a key in this context is that a key is stored for you, whereas a password is stored in memory.

Further down further in that paragraph
“Since passwords are committed to memory, they usually do not have as many possible values as cryptographic keys, and, in many protocols, are severely vulnerable to network attacks that are more restricted for keys.”

Passwords usually have just as many possible values—if not more so since cryptographic keys have a fixed number of bits but good password protocols do not restrict the length of passwords.  Rather, the great majority of users choose from a very small subset of the space of possible values.

**Suggested Change**:

A more accurate replacement for the section containing the above statements: “
“Shared secrets stored on authenticators may be either symmetric keys or passwords (as opposed to the asymmetric secrets described above, which subscribers need not share with the authenticator.)  While both keys and passwords can be used in similar protocols, one important difference between the two is how they relate to the subscriber. While symmetric keys are generally stored in hardware or software that the subscriber controls, passwords are intended to be memorized by the subscriber.   As such, a key is a secret stored on behalf of the subscriber, whereas subscribers are expected to store passwords within their mind.  Since most users choose short passwords to facilitate memorization and ease of entry, passwords typically have fewer characters than cryptographic keys.  Further, whereas systems choose keys at random, users attempting to choose memorable passwords will often select from a very small subset of the possible passwords of a given length, and many will choose very similar values.  As such, whereas cryptographic keys are typically long enough to make network-based guessing attacks untenable, user-chosen passwords may be vulnerable—especially if no defenses are in place.”

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by TerryMcBride** [comment]
Should we group shared secrets as a single authenticator type, then?  Maybe we should treat them like this doc treats "Identity Evidence":
- Shared Secrets:
  - Weak: human brain
  - Adequate: any device w/o user activation
  - Strong: FIPS 140 Level 1 w/ user activation
  - Superior: FIPS 140 Level 2 w/ user activation

**Comment by UppaJung** [comment]
Hi Terry,

   Not all human-memorized secrets are weak.  For example, we've shown that the great majority (~99%) of people can store crypto-strength keys in memory.  http://research.microsoft.com/pubs/220380/SecretsInHumanMemory_Extended.pdf

   One challenge with the current classification is that device-managed/stored symmetric keys are treated more similarly to human-managed/stored passwords than device-managed/stored asymmetric keys.  When you are entrusting a device to manage and store a secret, you are likely also to trust it not to share that secret with someone impersonating/spoofing the party you want to authenticate to.  For example, you trust your password manager only to fill in the password on the correct website and you trust your browser to only send cookies to the domain authorized to see those cookies.  As such, the difference between asymmetric keys (which almost always use authentication protocols that do not leak keys) and symmetric keys (which can be used in protocols that do not leak secrets, but are sometimes sent in plaintext) is small. 

Device stored/managed
- Type of key
  - Asymmetric
  - Symmetric
- Under what conditions does the device use the secret
  - Device authentication of user (e.g., via shared secrets or biometrics)
  - User authorization of use (e.g., OK to sign into this website or to authorize this transaction)

Human stored/managed
- How is secret chosen?
  - By user
    - Under what policy
  - By system at random and assigned to user
    - Key space (in bits)
  - Encoding (e.g., as words, digits, lowercase characters, etc.)
    - How does user know its safe/appropriate to provide the key?
      - How does the user know who they're releasing the key to?
      - How does the user know what they are implicitly authorizing by authenticating?

**Comment by TerryMcBride** [comment]
Thanks for the interesting article. The article seems to acknowledge that users might not be able/willing to memorize a lot of strong passwords or ones they don't use often: "While our study is preliminary in nature, we believe it debunks the myth that users are inherently incapable of remembering
cryptographically-strong secrets for a select few
high-stakes scenarios, such as a password for enterprise
login or as a master key to protect other credentials (e.g.,
in a password manager)."  

Also, the rate of decay in the ability to remember the passwords seems significant when compared to how often the public interacts with the government. If the dream of federation comes true, this would be very useful.

Completely agree about the need to trust the computer. That's the linchpin for security in general.

I would like to see a scenario where a cryptographic shared secret would be acceptable at some level when not stored in a non FIPS 140 validated module when compensating controls are in place (for example, when both halves of a symmetric key are secret and only the server can verify that the challenges was encrypted by the client). So, I very much appreciate the topic.

**Comment by jimfenton** [comment]
The distinction between a key and a password derives from SP 800-63-2, section 4.3, paragraph 6, which reads:

> Shared secrets stored on tokens may be either symmetric keys or passwords. While they can be used in similar protocols, one important difference between the two is how they relate to the subscriber. While symmetric keys are generally stored in hardware or software that the Subscriber controls, passwords tend to be memorized by the Subscriber. As such, keys are something the Subscriber has, while passwords are something he or she knows. Since passwords are committed to memory, they usually do not have as many possible values as cryptographic keys, and, in many protocols, are vulnerable to network attacks that are impractical for keys.  Moreover the entry of passwords into systems (usually through a keyboard) presents the opportunity for very simple keyboard logging attacks, and it may also allow those nearby to learn the password by watching it being entered. Therefore, keys and passwords demonstrate somewhat separate authentication properties (something you have rather than something you know).  However, when using either public key pairs or shared secrets, the Subscriber has a duty to maintain exclusive control of his or her token, since possession and control of the token is used to authenticate the Claimant’s identity. Token threats are discussed more in Section 6.2. 

The keys we're talking about here are those associated with approved cryptographic algorithms - 112 bits or greater presently. The question here is not whether it's possible to train a user to memorize a 112 bit number (it definitely is, ask the geeky kids on Pi Day) but that a value that is intended to be memorized and typed has a different nature than a key.

That said, I like the Suggested Change you have provided.
