### ISSUE TITLE
Clarify here that assertion references presented by the claimant are not assertions, but allow the RP to retrieve the assertion via back channels. Otherwise, the 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#881]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 5.1.1, 1
 
**Comment (Include rationale for comment)**:  Clarify here that assertion references presented by the claimant are not assertions, but allow the RP to retrieve the assertion via back channels. Otherwise, the discussions/claims of forgery protection are confusing/questionable.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The section is consistent in use of "assertion or assertion reference" which shouldn't give the impression that references are assertions.
