### ISSUE TITLE
suggest adding 'assertion' after holder-of-key. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#882]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 5.1.2, 2
 
**Comment (Include rationale for comment)**:  suggest adding 'assertion' after holder-of-key.
 
"The key referenced in a holder-of-key represents the subscriber, not any other party in the system including the browser, IdP, or RP. This key MAY be distinct from any key used by the subscriber to authenticate to the IdP."

**Suggested Change**: Need to qualify what holder of key is talking about.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Resolved via PR https://github.com/usnistgov/800-63-3/pull/657
