### ISSUE TITLE
‘Vital’ fields are not defined; explain that any field or component of an assertion that may be used by the RP to determine access, obtain 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#883]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 5.2.2, 1
 
**Comment (Include rationale for comment)**:  ‘Vital’ fields are not defined; explain that any field or component of an assertion that may be used by the RP to determine access, obtain proof of possession of holder’s key, or to hold the subscriber accountable for their access/activities associated to their access, SHALL be signed by the IdP.
 
Clarity

**Suggested Change**: Define 'vital field'
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Valid comment regarding vital, but would like to discuss what should replace it before we fully-accept this comment.

**Comment by jimfenton** [comment]
"the signature should cover the entire assertion" instead of "vital fields"
