### ISSUE TITLE
The range of IALs is too narrow

### ISSUE THREAD

**Issue by TomCJones** [usnistgov/800-63-3#884]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**: 4
 
**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: missing level (or maybe IAL 3 is wrong)
 
**Comment (Include rationale for comment)**:  
We still need to have a level of authentication that is absolutely, positively guaranteed to not be pseudonymous, for example from Doctors subscribing to medicines to corp executives signing Dodd-Frank statements. IAL 3 still permits pseudonymous, which is probably appropriate for someone accessing medical records where the lab is not aware of the name attached to the AIDS test, but that patient really doesn't want anyone else to have access. Anyway - at some point IAL3 (or 4 if it comes to that) should not be allowed without a pseudonym at the core of the authn process.
 
**Suggested Change**:
 
It would be sufficient if the IdP assertion were not pseudonymous, but the federated ID was anonymized, perhaps a new IFL? That is actually possible, but not guaranteed with OpenID Connect today. If that were ok, just eliminate the pseudonymous option on IAL3.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
The allowance for pseudonymity is the choice of an RP based on privacy risk assessment, among other things.  Pseudo at IAL3 only means that the CSP proofed at that level - meaning, they know they person at level of confidence == IAL3.  But in an assertion they need not reveal the identity, but the RP can be confident that an attributes asserted by the CSP were proofed at IAL3.

**Comment by TomCJones** [comment]
Could out please make that clear in the document. I could not determine that was the case.
