### ISSUE TITLE
Explain that sending assurances to a Federation proxy is the same as treating the receiving proxy as an RP. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#887]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 6, 1
 
**Comment (Include rationale for comment)**:  Explain that sending assurances to a Federation proxy is the same as treating the receiving proxy as an RP. 
 
Indicating that there is another model is confusing. Section 4.1.4 does not answer questions about federation proxy relevant to this section.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
unclear where this comment is targeted.
