### ISSUE TITLE
The section appears not to be complete, and not especially well tied to the discussion in the rest of this document. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#888]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 7, 1
 
**Comment (Include rationale for comment)**:  The section appears not to be complete, and not especially well tied to the discussion in the rest of this document. 

 
The text indicates that descriptions will be provided, and that the presentation model will be taken into account. Table 7-1 does neither. It would also be expected that specific federation protocols would be defined/referenced here, but only examples are provided. It would be expected that for front-channel presentations, attribute references would be mentioned/included in different FALs. At least reference section 11 (still only examples).

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Good catch.  Hangover from when we had a different FAL per presentation type.
