### ISSUE TITLE
4.3.3 Defenses against online guessing

### ISSUE THREAD

**Issue by UppaJung** [usnistgov/800-63-3#89]
**Organization**: Microsoft

**Type**: 2

**Reference (Include section and paragraph number)**: 4.3.3.

**Comment (Include rationale for comment)**:

 “Additionally, mechanisms located at the verifier can mitigate online guessing attacks against lower entropy secrets like passwords and PINs by limiting the rate at which an attacker can make authentication attempts or otherwise delaying incorrect attempts. Generally, this is done by keeping track of and limiting the number of unsuccessful attempts, since the premise of an online guessing attack is that most attempts will fail.”

Rate limiting implies some number of attempts are still allowed.  Rate limiting is really just a subset of a larger defense, which is blocking attempts from clients (e.g., IP addresses) that appear to be engaged in guessing attacks.  Rate limiting blocks attempts that exceed a given rate, but it would be just as valid to block all attempts after a threshold has been exceeded.  Delaying incorrect attempts doesn’t do much unless the attacker has a poorly-written client.  If the attacker knows that incorrect attempts are delayed, the attacker can just terminate the connection if not achieving success in the expected time frame.

“Additionally, mechanisms located at the verifier can mitigate online guessing attacks against lower entropy secrets like passwords and PINs by blocking authentication attempts from clients that appear to be guessing or otherwise delaying attempts. Generally, this is done by keeping track of and limiting the number of unsuccessful attempts, since the premise of an online guessing attack is that most attempts will fail.”

Additional defenses include blocking clients more quickly if they are issuing frequently-guessed passwords and giving extra protection (or locking accounts) of users whose passwords are among those being frequently guessed by attackers.

**Suggested Change**:

“Additionally, mechanisms located at the verifier can mitigate online guessing attacks against more easily guessable secrets, like passwords and PINs, by blocking attempts from clients that appear to be engaged in guessing attacks.  One approach to identifying clients engaged in guessing attacks is to track the number of unsuccessful attempts, since most guesses will be wrong.  Additional defenses include blocking clients more quickly if they are issuing frequently-guessed passwords and giving extra protection (or locking accounts) of users whose passwords are among those being frequently guessed by attackers.”

**Comment by jimfenton** [comment]
Section 5.1.1.2 already recommends the use of a dictionary to disallow the use of frequently-guessed memorized secrets (passwords). Attackers would then be less likely to guess those passwords and users wouldn't be able to use them in the first place.

Identifying clients engaged in guessing attacks is difficult -- many attackers have wide resources, such as botnets, under their control making it difficult to correlate their activities in order to block them. It is important that throttling mechanisms be chosen that do not give attackers such means of evasion.
