### ISSUE TITLE
Not sure what may be dictated in this sentence. Are the proxies dictated by policy or are the blinding techniques dictated by policy? Suggest adding 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#891]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 9.5, 1
 
**Comment (Include rationale for comment)**:  Not sure what may be dictated in this sentence. Are the proxies dictated by policy or are the blinding techniques dictated by policy? Suggest adding what is being dictated to the sentence after "appropriate use 'of xxx' by the "

 
Original text:
"Privacy policies may dictate appropriate use by the IdP, RP, and the federation proxy, but technical means such as blinding can increase effectiveness of these policies by making the data more difficult to obtain."

**Suggested Change**: Make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
'appropriate use' here refers to both the subscriber attributes and the assertion metadata (who the RP and IdP are, for example). Will clarify this in the text.
