### ISSUE TITLE
Suggest that the technical and operational implementation complexity may 'increase' as well. Suggest qualifying what increases as shown above. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#892]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 9.5, 1
 
**Comment (Include rationale for comment)**:  Suggest that the technical and operational implementation complexity may 'increase' as well. Suggest qualifying what increases as shown above.
 
Original text: "As the level of blinding increases, the technical and operational implementation complexity may as well.

**Suggested Change**: Make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The need for proxies to implement the blinding process accounts for the additional complexity, but we can say that.

**Comment by jricher** [comment]
Also the key management between parties gets more complex with blinding systems.
