### ISSUE TITLE
Please define what 'entities' represents here. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#893]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 10.1.1, 2
 
**Comment (Include rationale for comment)**:  Please define what 'entities' represents here. 
 
Need to try to explain what is meant by entities here and in "Provide users unique, meaningful, and descriptive identifiers to distinguish among 'entities'." and in " Provide users means for updating data even if the associated 'entity' no longer exists."

**Suggested Change**: Make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by ychoong** [comment]
Added text to clarify.

**Comment by paul-grassi** [comment]
Closed via PR #1790
