### ISSUE TITLE
May need to add text to qualify this statement with respect to authentication and knowing who is on our systems. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#894]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 10.1.1, 2
 
**Comment (Include rationale for comment)**:  May need to add text to qualify this statement with respect to authentication and knowing who is on our systems.
 
 Policy may dictate that a user's access to data be accounted for so that we know specifically who accessed the data or system.

"Provide users appropriate anonymity and pseudonymity options and the ability to switch among such identity options as desired."

**Suggested Change**: Make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
