### ISSUE TITLE
GENERAL EDITORIAL: Overall across the document suite consistent cross-referencing is lacking. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#895]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 

**Reference (Include section and paragraph number)**: , 
 
**Comment (Include rationale for comment)**:  GENERAL EDITORIAL: Overall across the document suite consistent cross-referencing is lacking. 
 
Consistent Formatting. Sometimes [ ] brackets are used othertimes just ( ) parenthesis--sometime with SP, sometimes not. Examples: 800-63B (Sect 5.1.7.1, pg 33; Sect 7.2.1, pg 33; 800-63C (Sect. 4.3, pg 13; Sect 10.1, pg 26)

**Suggested Change**: Please review this formatting and make it consistent across all of the documents. Also some of these are links which cannot be accessed by some folks.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Related to #699
