### ISSUE TITLE
GENERAL EDITORIAL: Overall across the document suite internal cross-referencing is inconsistent. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#896]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 

**Reference (Include section and paragraph number)**: , 
 
**Comment (Include rationale for comment)**:  GENERAL EDITORIAL: Overall across the document suite internal cross-referencing is inconsistent. 
 
Sometimes, above/below; sometimes, sub-section.  Examples: 800-63A (Sect 9, pg 30; Sect 9.1, pg 30; Sect 9.3 pg 32); 800-63B (Sect 2, pg 6; 800-63C (Sect 10.1.2, pg 27).

**Suggested Change**: Recommend cross referencing sections only by paragraph number throughout the suite of documents
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Related to #895
