### ISSUE TITLE
More GENERAL EDITORIAL: 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#898]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 

**Reference (Include section and paragraph number)**: , 
 
**Comment (Include rationale for comment)**:  More GENERAL EDITORIAL: 
 
1. Across the document suite some inconsistencies in glossary definitions are noted.  These are provided in a companion Excel Spreadsheet.  We advocate a single stand-alone Information Assurance Glossary rather than document-specific glossaries to avoid these  inconsistencies.  For example "Authenticated Protected Channel" is referenced in 800-63A Section 4.2, pg 13, and 800-63B Sect 5.1.2.2,  pg 21 but not found in a glossary until 800-63C.  
2. In some cases terms/acronyms are called out but missing from any glossary.  For Example 800-63-B, Sect 5.2.3, pg 27 (presentation attack detection (PAD)).  In other cases, missing from some glossaries, For example "verifier" in 800-63A and 800-63C.
3. We would encourage capitalization of key term, such as those found in glossaries, where appropriate.  (For Example 800-63B, Sect 2, pg 6 - "Relying Party"; 800-63A Section 4.2, pg 13, and 800-63B Sect 5.1.2.2 "Authenticated Protected Channel"; 800-63C Sect 2, pg 7; "Credential Service Providers";  and 800-63C, Sect 5, pg 14 "Message Authentication Code (MAC)".
4. We encourage acronyms be spelled out on first use, For example 800-63-C sect. 2, pg 7.

**Suggested Change**: Suggestions to further improve a strong and well written document suite
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Accepting all comments except (3) due to style issues at the home office.
