### ISSUE TITLE
CSP Risk Mitigation Measures

### ISSUE THREAD

**Issue by mschleiff** [usnistgov/800-63-3#9]
**Organization**: 2 Industry

**Reference (Include section and paragraph number)**: 800-63A Section 4.2, second enumerated list:
1.If the CSP employs risk mitigation measures, the agency SHALL conduct a privacy risk assessment of these mitigation measures. Such assessments should include any privacy risk mitigations (e.g., limited retention, strict use limitations, notice, etc.) or other technological mitigations (e.g.,cryptography).The CSP SHALL NOT apply additional risk-based approaches without providing explicit notice of such approaches.

**Comment (Include rationale for comment)**:
 If the CSP employs risk mitigation measures (a good thing), then that imposes additional responsibilities on the agency or other relying party (a bad thing). This might encourage agencies/RPs to favor CSPs that do not employ risk mitigation measures.
What are “risk-based approaches”? Do you mean the same thing as the earlier use of “risk mitigations”? Or something else? Could you provide an example?

**Comment by paul-grassi** [comment]
we purposefully intend to be non-prescriptive here, and allow CSPs to employ mitigations they deem appropriate.  The required proofing processes establish a minimum set of requirements for the IAL they are built for. CSPs can go beyond, but can't substitute these requirements.  We will fix the text to be clear which requirement this privacy requirement is meant for.
