### ISSUE TITLE
Use semantic/descriptive anchors for cross links

### ISSUE THREAD

**Issue by jricher** [usnistgov/800-63-3#90]
At the moment, all anchors in the document are based on document and section numbers, which is fragile if the document structure changes. We should instead use semantic tags instead, describing the content in the link anchor, such as #inpersonproofing and #sessionmanagement, instead of #sec1 and #sec7.

**Comment by paul-grassi** [comment]
Agreed. I have been using a mix but prefer Justin's recommendation.

**Comment by jimfenton** [comment]
Suggest we use semantic anchors going forward, and change to them whenever something breaks. I'm not sure it's worth updating a lot of existing anchors.

**Comment by jricher** [comment]
That's a reasonable approach.
