### ISSUE TITLE
What presents multiple opportunities? Of which exists multiple opportunities for impersonation and other attacks to fraudulently claim another subject’s digital identity. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#901]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 2, 1
 
**Comment (Include rationale for comment)**:  What presents multiple opportunities? Of which exists multiple opportunities for impersonation and other attacks to fraudulently claim another subject’s digital identity.
 
Clarity

**Suggested Change**: Of which what? The process of authenticating, of Identity proofing or… Cannot suggest a rewrite at this time. It just seems very awkward the way it is written.
Suggestion: Which increases potential for impersonation and other attacks involving fraudulent claims of the identify.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This paragraph is about the whole of digital identity, but a clarifying update will be made.

**Comment by paul-grassi** [comment]
Resolved via April 1 update of -3.
