### ISSUE TITLE
Extra word in sentance: "This document suite describes identity assurance, authenticator assurance, and federation assurance and as separate ordinal measurements" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#902]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 2, 2
 
**Comment (Include rationale for comment)**:  Extra word in sentance: "This document suite describes identity assurance, authenticator assurance, and federation assurance and as separate ordinal measurements"
 
Grammar

**Suggested Change**: believe there is an extra and: This document suite describes identity assurance, authenticator assurance, and federation assurance and as separate ordinal measurements
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE with April 1 update to -3.
