### ISSUE TITLE
The mixing of statements of exclusion (machine-to-machine) with statements of inclusion (biometrics, allbeit with caveats) makes for a jumbled presentation of the limitations. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#904]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 2.2, 1
 
**Comment (Include rationale for comment)**:  The mixing of statements of exclusion (machine-to-machine) with statements of inclusion (biometrics, allbeit with caveats) makes for a jumbled presentation of the limitations.
 
Improve readability and clarity through parallel construction of limitations, prerhaps building on the Abstract on pg 3 (see suggested change)

**Suggested Change**: These guidelines adress remote authentication of users (employees, contractors, or private individuals) interacting with government IT systems over open networks.  As such, machine-to-machine (such as router-to-router) authentication is outside the scope of this suite of documents as are  requirements for issuing authenticators to machines and servers when they are used in authentication protocols.

Users' human characteristics, or biometrics, employed as a means of remote authentication are included in these guidelines, but also with limitations.  The need for these limitations is derived from cases where attackers may have access to these biometrics.  Thus, the use of biometrics for authenticaiton is limited to activation of a specific physical authenticator to which it is strongly bound and where the number of consecutive activation failures is limited, afterwhich another activation factor or authenticator is required.  This document suite also supports the use of biometircs, with the same limitations, to prevent repudiation of registration, and to verify that the same individual participates in all phases of the registration process.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will clean up paragraph but may not take entire suggested change.
