### ISSUE TITLE
Do the changes and assumptions listed after this text also apply to the new SP 800-63-3 document? It is not clear from the text. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#906]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 2.5.1, 2
 
**Comment (Include rationale for comment)**:  Do the changes and assumptions listed after this text also apply to the new SP 800-63-3 document? It is not clear from the text. 
 
If they do not apply then why list them here? 
"NIST SP 800-63-1 updated NIST SP 800-63 to reflect current authenticator (then referred to as token) technologies and restructured to provide a better understanding of the digital authentication architectural model used here. Additional (minimum) technical requirements were specified for the CSP, protocols utilized to transport authentication information, and assertions if implemented within the digital authentication model. Other changes to NIST SP 800-63 included:"
and 
"The subsequent sections of NIST SP 800-63-1 presented a series of recommendations for the secure implementation of RAs, CSPs, Verifiers, and RPs. It should be noted that secure implementation of any one of these can only provide the desired LOA if the others are also implemented securely. Therefore, the following assumptions were made in NIST SP 800-63-1:"

**Suggested Change**: Suggest changing wording of last sentence in paragraph to  SP 800 - 63-3 -  "Other changes to NIST SP 800-63-3 included:" If this applies to 800-63-3.

The same goes for this paragraph: if the recommendations apply to 800-63-3 then state that - "Therefore, the following recommendations were made in for NIST SP 800-63-13:
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Languge is in the 800-63-1 heading.  In addition, the list is preceded by `Therefore, the following assumptions were made in NIST SP 800-63-1`. It seems clear which document is being referred.
