### ISSUE TITLE
Does this statement apply to 800-63-3? Same problem as with section 2.5.1 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#907]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 2.5.2, 1
 
**Comment (Include rationale for comment)**:  Does this statement apply to 800-63-3? Same problem as with section 2.5.1
 
Assuming the Section 5 in the last sentence of this paragraph is referring to the document in review, 800-63-3. the section 5 in the first sentence appears to be in 800-63-2.

**Suggested Change**: suggest qualifying which text in the section is in which document. For example: 

The substantive changes in the revised draft Section 5 of SP 800-63-3 were intended to facilitate the use of professional credentials in
the identity proofing process, and to reduce the need to use postal mail to an address of record to issue credentials for level 3 remote registration. Other changes to Section 5 of SP 800-63-3 were minor explanations and clarifications.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Heading is 800-63-2, so it is clear to us which document the change applied to.
