### ISSUE TITLE
Believe this should be SP 800-63-3! "Other areas of update to SP 800-63-2 include:" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#908]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 2.5.3, 2
 
**Comment (Include rationale for comment)**:  Believe this should be SP 800-63-3! "Other areas of update to SP 800-63-2 include:"
 
Clarity

**Suggested Change**: Make suggested change from SP 800-63-2 to 800-63-3.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is a confusing statement.  An update will be made.
