### ISSUE TITLE
The use of specification here is confusing. The paragraph starts with For example. Suggest that the first 'specification' might be better as this example. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#910]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.3.1, 8
 
**Comment (Include rationale for comment)**:  The use of specification here is confusing. The paragraph starts with For example. Suggest that the first 'specification' might be better as this example. 

 
The second 'specification' in the next paragraph should probably be this guidance.
"This specification considers such a device to effectively provide two factor authentication, although the actual authentication protocol between the verifier and the claimant simply proves possession of the key.
As noted above, biometrics, when employed as a single factor of authentication, do not constitute acceptable secrets for digital authentication, but they do have their place in this specification."

**Suggested Change**: Suggest reworking the paragraphs as suggested.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
the term `specification` should be replaced by a more appropriate term, like `guideline`.
