### ISSUE TITLE
Suggest changing word 'going to'go.' 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#911]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.1, 3
 
**Comment (Include rationale for comment)**:  Suggest changing word 'going to'go.'
 
A risk assessment to determine each xAL is recommended. Section 5.3 provides details on how agencies may going about making xAL selections.

**Suggested Change**: Suggest changing wording as shown.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE with April 1 update of -3.
