### ISSUE TITLE
In figure 5.1 what do the different columns represent? Suggest adding column headings. Is there a document that explains how to do an M-04-04 risk 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#915]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Figure 5.1, 1
 
**Comment (Include rationale for comment)**:  In figure 5.1 what do the different columns represent? Suggest adding column headings. Is there a document that explains how to do an M-04-04 risk assesment. 
 
Completeness/Clarity

**Suggested Change**: Suggest adding column headings. Suggest adding a reference. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE with April 1 update to -3.
