### ISSUE TITLE
Suggest that in this sentence agency should be agencies. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#916]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.3.3, 1
 
**Comment (Include rationale for comment)**:  Suggest that in this sentence agency should be agencies. 
 
Grammar: Suggest that in this sentence agency should be agencies. 
"This analysis is not intended to be a substitute for M-04-04 risk assessments or any other risk management process in use by the agency."

**Suggested Change**: Suggest reworking the sentence as follows: "This analysis is not intended to be a substitute for M-04-04 risk assessments or any other risk management process used by agencies."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE with April 1 update of -3.
