### ISSUE TITLE
Correlating subscribers by related RPs

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#922]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 5.2.6, 1
 
**Comment (Include rationale for comment)**:  5.2.6 corrections
 
the concern is not about associating RPs (second bullet), but associating the subscribers activity among those RPs. This should be included in privacy notices to the subscriber.

‘a correlation’ is not a group. Use ‘set of correlated RPs’ for clarity.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Agreed; need to determine if notice to subscribers is sufficient or whether subscriber consent is also required.

@nbl-nist what do you think?
