### ISSUE TITLE
Suggest using IdP and CSP 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#924]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: Fig 6-1, 1
 
**Comment (Include rationale for comment)**:  Suggest using IdP and CSP
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Already fixed by #578.
