### ISSUE TITLE
Explain whether requiring assertion references to be restricted to “single RP” precludes use of attribute assertions with federation proxies. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#925]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 6, 1
 
**Comment (Include rationale for comment)**:  Explain whether requiring assertion references to be restricted to “single RP” precludes use of attribute assertions with federation proxies.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
In a proxied federation, the IdP would audience restrict to the proxy, and the proxy would re-restrict to the RP. We will make this clearer.

**Comment by jricher** [comment]
Closed by 82e8fcfb24d71f9d405afc8c7c0c71637fc86ddd
