### ISSUE TITLE
6.1 changes 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#926]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 6.1, 1
 
**Comment (Include rationale for comment)**:  6.1 changes
 
An RP obtaining additional attributes in a federation may require interaction with other IdPs. Explain how this can occur in the back-channel presentation if the IdP required for the attribute does not have the original assertion (or specify that it can’t).
Explain (or reference) ‘issuer verification’, as opposed to just verifying the signature on the assertion (listed separately). What about the other required/optional metadata.
Explain the concerns with bearer assertions used within the back-end presentation model (preventing replay and forgery) and spell out the additional controls to further protect the RP from fraudulent activity (as indicated/referenced from section 5.1.1). 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This could be a good place to introduce 'oauth' concepts where the user can delegate authorization to data outside the scope of the IDP.

**Comment by jricher** [comment]
The assertion is not used by the RP to get additional attributes, but additional authorization credentials (such as OAuth access tokens) can be issued alongside the assertion. From section 5:

> The RP MAY fetch additional identity attributes from the IdP in one or more separate transactions using an authorization credential issued alongside the original assertion.

This mechanism can be repeated and referenced in section 6.1 to prevent people from misreading it as above.

**Comment by jricher** [comment]
lssuer verification amounts to checking if the issuer is one that the RP accepts assertions from for this transaction. This is separate from validating the signature as an RP could get a valid and properly signed assertion from an IdP they don't accept. We can't assume that all keys are pre-placed as is required in older federation protocols, which seems to be implied by the comment here.
