### ISSUE TITLE
Characterize the examples to provide definitions of (one or more) federation protocol, as used throughout the document – there is no definition. Then provide the 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#929]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 7, 4
 
**Comment (Include rationale for comment)**:  Characterize the examples to provide definitions of (one or more) federation protocol, as used throughout the document – there is no definition. Then provide the examples to illustrate the definitions. 
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Don't understand what definition(s) are lacking.
