### ISSUE TITLE
Remove 's' at the end of assertions. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#930]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 8, 1
 
**Comment (Include rationale for comment)**:  Remove 's' at the end of assertions.
 
grammar - IdPs, RPs, subscribers, and parties outside of a typical assertions transaction may be malicious or become compromised.

**Suggested Change**: Make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
already fixed
