### ISSUE TITLE
Claims that these mitigations are ‘included’ should provide references to the particular sections, having one or more SHALL statements; where the referenced section includes optional 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#932]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 8.1, 1
 
**Comment (Include rationale for comment)**:  Claims that these mitigations are ‘included’ should provide references to the particular sections, having one or more SHALL statements; where the referenced section includes optional controls (SHOULD or MAY), or otherwise not indicated as mandatory, additional discussion is required. 
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Good comment, probably applies to -63A and -63B as well.
