### ISSUE TITLE
Clearly distinguish the discussion based on employees, privileged users, and citizens. For employees and privileged user accesses, insider threat programs and network defense activities may 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#933]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 9.1, 1
 
**Comment (Include rationale for comment)**:  Clearly distinguish the discussion based on employees, privileged users, and citizens. For employees and privileged user accesses, insider threat programs and network defense activities may require such tracking.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Need for additional tracking and profiling for employees and privileged users would be covered by consultation with the SAOP.

We will consider additional language in -3 covering the applicability in these use cases.

**Comment by paul-grassi** [comment]
Resolved via April 1 update to -3, specifically section 2.1
