### ISSUE TITLE
The second paragraph regarding which party/parties in a federation are required to obtain consent should be included in the discussion on various models (a third 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#934]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 9.2, 2
 
**Comment (Include rationale for comment)**:  The second paragraph regarding which party/parties in a federation are required to obtain consent should be included in the discussion on various models (a third consideration: assertion presentation, assertion protection, and interactions with the subscriber).
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
We will be reorganizing to create a general requirements section that will include the privacy requirements, notice and consent requirements, etc. so it will be clearer that the requirements apply to all federation models.
