### ISSUE TITLE
There is wording missing to make a complete thought in this sentence. Suggest adding 'this can be accomplished' before 'by following...' in the sentence. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#935]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 10, 5
 
**Comment (Include rationale for comment)**:  There is wording missing to make a complete thought in this sentence. Suggest adding 'this can be accomplished' before 'by following...' in the sentence.
 
"The overall user experience with federated identity systems should be as smooth and easy as possible, by following usability standards (such as the ISO 25060 series of standards) and established best practices for user interaction design."

**Suggested Change**: Make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
