### ISSUE TITLE
Suggest adding 'specific' before 'usability'. This sets this section apart from the previous section which were more general usability considerations. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#936]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 10.2, 1
 
**Comment (Include rationale for comment)**:  Suggest adding 'specific' before 'usability'. This sets this section apart from the previous section which were more general usability considerations.
 
clarity. "This section addresses the usability considerations that have been identified with federated identity systems."

**Suggested Change**: Make suggested changes.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
