### ISSUE TITLE
Missing word 'by' and 'data' in this sentence. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#937]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 10.1.1, 2
 
**Comment (Include rationale for comment)**:  Missing word 'by' and 'data' in this sentence. 
 
Clarity/ readability. "For example, some healthcare data is updated and owned 'by' the patient, while some 'data' is only updated by a hospital or doctor’s practice."

**Suggested Change**: Make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
