### ISSUE TITLE
Missing word 'they' and '()'. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#938]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 10.1.1, 2
 
**Comment (Include rationale for comment)**:  Missing word 'they' and '()'.
 
Clarity/ readability. "Provide users with the ability to easily verify, view and update attributes. Identities and user roles are dynamic and not static, thus 'they' change over time, '(e.g., age, health, and financial data.)'"

**Suggested Change**: Make suggested change.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Closed via PR https://github.com/usnistgov/800-63-3/pull/1682
