### ISSUE TITLE
Delete "will" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#939]
**Organization Name (N/A, if individual)**: DCMA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 6, Note
 
**Comment (Include rationale for comment)**:  Delete "will"
 

**Suggested Change**: To read, "the authenticator can"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
or 'will be revoked at the same time'.

**Comment by paul-grassi** [comment]
OBE with changes to Ch. 6.  See #597
