### ISSUE TITLE
Avoiding confusion for CSP acronym 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#949]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: General, 
 
**Comment (Include rationale for comment)**:  Avoiding confusion for CSP acronym
 
With the advent of FedRAMP and acronym of CSP already widely used for "Cloud Service Provider," perhaps an different acronym or label could be used instead of Credential Service Providers (CSP). In some cases, these may be the same entity, but in others not, thus the possibility for confusion.

**Suggested Change**: Choose a different acronym to avoid confusion.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by lachellel** [comment]
2nd this comment.

**Comment by paul-grassi** [comment]
This is unlikely to change. The term has been around forever in identity, and we made sure to align to FICAM TFS rather than the old "PKI centric" terms in the old version.  Everything is contextual.  When you talk identity, CSP is credential, when cloud, it's cloud.

**Comment by lachellel** [comment]
I'm not suggesting to change the term directly (as this issue / suggestion states).  You are correct that it's widely used.  

Clarity is preferred.  Often Standards will be taken apart piece by piece and used in procurements, architecture, websites, etc.   Reducing the use of **acronyms** in each requirement is an option.

**Comment by paul-grassi** [comment]
Following proper document style guides we will keep the acronym list as-is. Incorrect or unintended copy/paste errors are out of our control.
