### ISSUE TITLE
Table 2-1. Earlier in the document, there's mention that there are four LOAs, but LOA 4 doesn't seem to be included here (or elsewhere)? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#950]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: Table 2-1, 
 
**Comment (Include rationale for comment)**:  Table 2-1. Earlier in the document, there's mention that there are four LOAs, but LOA 4 doesn't seem to be included here (or elsewhere)?
 
 Why not match the LOA to the source OMB document?

**Suggested Change**: Add the missing LOA.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE with April 1 update to -3.
