### ISSUE TITLE
Trusted processes 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#951]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 2.5.1, 
 
**Comment (Include rationale for comment)**:  Trusted processes
 
Trusted processes: Document notes that "It is assumed that there exists a process of certification through which agencies can obtain the above assurance for trusted entities which they do not implement themselves." This is a major assumption, because without this root trust, the system cannot function. More guidance around this (a la FedRAMP) would be helpful to ensure that the chain of trust is established and maintained throughout the system.

**Suggested Change**: Offer suggestions or additional guidance for establishing or maintaining this chain of trust.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is a change log entry for the -1 updates and does not apply to this update.
