### ISSUE TITLE
IAL0 as an option 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#952]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 
 
**Comment (Include rationale for comment)**:  IAL0 as an option
 
4.1 "At IAL1, identity proofing is not required, therefore any attribute information provided by the subscriber is self-asserted or should be treated as self-asserted and not verified." If IAL1 does not require any identity proofing, wouldn't it be better referred to as IAL0? I can appreciate the need for pseudonymous access, as well as the self-assertion from an operational perspective, but Level 1 implies there was some Identity Assurance (where there is actually none - 0).

**Suggested Change**: Include IAL0 as the option for self-asserted attributes to give an intuitive sense that there is "zero" assurance at this level.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Fair point, and merits could be made on both sides.  At this point, IAL1 will remain.
