### ISSUE TITLE
Reduce information returned to prevent risk of information leakage. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#953]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 
 
**Comment (Include rationale for comment)**:  Reduce information returned to prevent risk of information leakage.
 
4.1 "In all cases, the RP should request the attributes it requires from a CSP prior to authentication of the claimant. In addition, the claimant should be requested to consent to the release of those attributes prior to generation and release of an assertion." If the claimant is requested to consent to release of attributes, this could result in information leakage (i.e. a potential claimant could see the attributes prior to release and understand what's needed for this transaction, then abort the transaction prior to assertion minimizing audit trail but accessing required attributes). I'm not sure what value consenting to release of attributes offers, particularly since the claimant likely can't negotiate which attributes are released, nor is there an alternative if they want the assertion to complete the transaction. Consider removing this requirement.

**Suggested Change**: Reduce information returned to prevent risk of information leakage.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
User consent is a privacy requirement that will remain. Yes, perhaps there is a small vector of information gathering, but a potential attacker should be able to glean this information regardless of the authentication process.
