### ISSUE TITLE
Revise to reflect the reality that many users employ pass phrases, or use password managers that enable longer, more secure passwords. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#954]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.1, 
 
**Comment (Include rationale for comment)**:  Revise to reflect the reality that many users employ pass phrases, or use password managers that enable longer, more secure passwords.
 
4.1 "Furthermore, whereas systems choose keys at random, users attempting to choose memorable passwords will often select from a very small subset of the possible passwords of a given length, and many will choose very similar values. As such, whereas cryptographic keys are typically long enough to make network-based guessing attacks untenable, user-chosen passwords may be vulnerable, especially if no defenses are in place." With the rise and advent of password managers that utilize MFA (particularly hardware authenticators), much longer and more complex passwords are possible. Dismissing all users as choosing short memorable passwords in 2017 seems shortsighted and slightly out of step with the choices available to users today and going forward.

**Suggested Change**: Revise to reflect the reality that many users employ pass phrases, or use password managers that enable longer, more secure passwords.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This section is just narrative.  -B contains requirements that are in line with the suggested change.
