### ISSUE TITLE
Move towards an as-needed collection model. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#955]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4, 
 
**Comment (Include rationale for comment)**:  Move towards an as-needed collection model.
 
4. Information Minimization. There seems to be some philosophical conflict presented here. On the one hand, the CSP is encouraged to collect attributes that are "the minimum necessary." Yet, on the other hand, they are permitted to collect additional information provided the "applicant explicitly consents to the CSP collecting and storing the attributes." Shouldn't the information be collected as needed (i.e. when the applicant needs a higher IAL, they can then add more information to the CSP's repository). In fact, in reference to Table 4-2, the document requires that agencies "SHALL NOT select an IAL that is higher than necessary for the business purpose of the digital service." Why would CSPs be allowed to collect information in a similar way? Otherwise, the CSP may be storing more information than necessary on many users, increasing the impact of a breach or potentially allowing a compromised applicant to apply for a higher IAL with pre-supplied information. See 8.1 for more risks.

**Suggested Change**: Move towards an as-needed collection model.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
We will clarify that additional information may be collected by the CSP with the informed consent of the subscriber, such as additional attributes that may be used by RPs making authorization decisions.

- Add informed consent exception in 4.2 item 3
- Check privacy considerations for consistency
