### ISSUE TITLE
Update to reconcile ADEQUATE vs. FAIR inconsistency. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#956]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.2.1.1, 
 
**Comment (Include rationale for comment)**:  Update to reconcile ADEQUATE vs. FAIR inconsistency.
 
5.2.1.1 - All previous sections refer to the strength of the evidence in the following nomenclature: SUPERIOR, STRONG, ADEQUATE, but the table includes Unacceptable, Weak, Fair, Strong, and Superior. Is ADEQUATE equivalent and interchangeable to FAIR? If so, suggest changing table to include ADEQUATE, or change rest of document to mention FAIR

**Suggested Change**: Update to reconcile ADEQUATE vs. FAIR inconsistency.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Updated via #518
