### ISSUE TITLE
FIPS approved algorithm should be called out as opposed to secure . 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#958]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4, 4.6
 
**Comment (Include rationale for comment)**:  FIPS approved algorithm should be called out as opposed to secure .
 
FIPS needs to be stated.

**Suggested Change**: a code generated by a random number generator that uses an approved algorithm from NIST's DRBG Validation List.  The DRBG Validation List can be found at http://csrc.nist.gov/groups/STM/cavp/documents/drbg/drbgnewval.html.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Approved random number generator will be used.
