### ISSUE TITLE
Scientifically-unsupported statement: "“Password length has been found to be the primary factor in characterizing password strength.”

### ISSUE THREAD

**Issue by UppaJung** [usnistgov/800-63-3#96]
**Organization**: Microsoft

**Type**: 2

**Reference (Include section and paragraph number)**:
 800-63-3 / sp800-63b / appA_memorized.md  
Appendix A
A.2

**Comment (Include rationale for comment)**:
If length "has been found" to be the primary factor in characterizing password strength, then cite scientific evidence.  I've seen no such evidence.  Some studies out of CMU found that 16-character passwords did well relative to 8-character passwords, but the attack model was trained on 8-character passwords.

Further inspection has revealed that the set of passwords participants use in such studies include such items as "fourfourfourfour" and "passwordpassword".  In other words, increasing the length requirement can cause users to choose weaker passwords because:
   (1) They need to remember something longer.
   (2) There are fewer strategies that work for long passwords so repetitions and other tricks may become more common than they would be for shorter passwords.
   (3) Users feel less obligated to choose something hard to guess because the length requirement seems so arduous that they get a false sense of security.

**Suggested Change**:
The document should be rewritten without the scientifically-unsubstantiated claims that length increasing minimum-length requirements makes user-chosen secrets harder to guess.

Rather, it is better to used data-based approaches, such as block lists of forbidden passwords or of strings that contribute little to making a password less guessable.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
You are reading too much into this sentence: "Password length has been found to be the primary factor in characterizing password strength."  It simply says that, by in large, the strength of longer passwords is different from the strength of shorter passwords. It does not discuss minimum password length requirements.

We have adopted the approach suggested in Florencio, Herley, and van Oorschot, "An Administrator's Guide to Internet Password Policies" by setting the minimum password length at a value considered suitable for online attacks, but not taking the usability/memorability hit of trying to address offline attacks with password length. As you have noted in #98, we are already using block lists of forbidden passwords.

**Comment by demarinaGit** [comment]
I do think this sentence could be worded better. As it is, it could easily taken as license to say length 9 is better than 8, 10 is better than 9, etc. I'll see if I can come up with a candidiate alternative wording.

Jim, we didn't specify length as the way of achieving online-resistance in Administrators Guide, but the number of guesses a password could withstand.

**Comment by paul-grassi** [comment]
Thanks @demarinaGit.  If you want to send me the language I can add it.  Or feel free to submit a pull request for me to accept directly into the text.  Note that "nist-pages" is the master branch in this repo.
