### ISSUE TITLE
Referencing guidance on session management should be provided. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#960]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 7, 7
 
**Comment (Include rationale for comment)**:  Referencing guidance on session management should be provided. 
 
Since in many instances, public facing systems will web appliations, references for addressing session management in this use case should be provided, NIST and/or otherwise.

OWASP number 2 vulnerability on OWASP Top 10 Vulnerabilities for 2010 and 2013.

**Suggested Change**: Reference OWASP Session Management Cheat Sheet at https://www.owasp.org/index.php/Session_Management_Cheat_Sheet in Section 7.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Another option might be to reference RFC 6265, which is an IETF Proposed Standard.
