### ISSUE TITLE
OMB Memorandom M-10-22 Guidance for Online Use of Web Measurement and Customization Technologies covers cookie management extensively. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#961]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 7, 7.1.1
 
**Comment (Include rationale for comment)**:  OMB Memorandom M-10-22 Guidance for Online Use of Web Measurement and Customization Technologies covers cookie management extensively.
 
Guidance on cookies is provided by OMB that is not accounted for in this section.

**Suggested Change**: Provide M-10-22 as a reference.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The suggestion in #960 provides more concrete requirements for session management identifiers. M-10-22 is largely focused on analytics and customization, with little of the security emphasis needed here.
