### ISSUE TITLE
Threats of mobile phone users that are subscribers to foreign wireless networks should be addressed. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#962]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 8, Table 8.1
 
**Comment (Include rationale for comment)**:  Threats of mobile phone users that are subscribers to foreign wireless networks should be addressed. 
 
CSP subscribers of foreign networks and the threat of subscribers' reliance on those networks isn't addressed.

Threats of endpoint security with respect to endpoints such as smartphones that are distributed by foreign telecom providers should be addressed as many U.S. citizens live abroad but will access Federal systems and applications.  

In many cases, telecom providers provide their own customized versions of the OS, e.g. Android, as well as apps and can make their subscribers susceptible to attacks by the telecom provider.  Additionally, these same telecoms have great control as well as visibility into a user’s traffic. Agencies should be advised that they may want to consider access to their systems from foreign networks and/or devices when allowing access to a CSP.  The same could be said with respect to foreign internet service providers used by U.S citizens. Draft NISTIR 8144, Assessing Threats to Mobile Devices & Infrastructure, provides some insight.

**Suggested Change**: In Table 8-1, identify use of foreign wireless providers and internet service providers as potential threats.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Foreign telecom providers are but one source of an endpoint compromise as described in Table 8-1. In the absence of an endpoint compromise, the requirements for use of authenticated protected channels for authentication mitigate the threat of visibility into a user's traffic.

**Comment by jimfenton** [comment]
Will look at adding mitigation in table 8-2, further recommending that PSTN not be used for OOB on foreign wireless networks.
