### ISSUE TITLE
Does the entire proofing transaction include the "enrollment"? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#963]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.2. General Requirements, 10
 
**Comment (Include rationale for comment)**:  Does the entire proofing transaction include the "enrollment"? 
 
if yes, there will not be an authenticated channel as authentication cannot happen before
id proofing.  If not, there is missing requirement for enrollment transaction.

"The entire proofing transaction, including transactions that involve a third party, SHALL occur over an Authenticated Protected Channel."

**Suggested Change**: Add the requirement of protected channel for enrollment transaction.  After enrollment, the proofing transaction shall occue over an authenticated protected channel.  
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Authenticate channel definition will be updated.  This does not mean the user needs an authenticator for the channel to be authenticated.  Think TLS.
