### ISSUE TITLE
There is a discrency between 4.6 and 4.7. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#964]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.7, 
 
**Comment (Include rationale for comment)**:  There is a discrency between 4.6 and 4.7.
 

In 4.6 "An enrollment code SHALL be comprised of one of the following:
Minimally, a random six character alphanumeric. "
however, in 4.7 Table 43.
"IAL Requirements Summary, for IAL2 Address Confirmation: An enrollment code consisting of at least 6 random digits SHALL be included in address confirmation."

**Suggested Change**: Update 4.7 to make sure the enrollment code requirements are consistent with 4.6.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will update, though there is a chance this table may be deleted.

**Comment by paul-grassi** [comment]
Will be resolved via #669
