### ISSUE TITLE
Clarification needed for reauthentication at least once per 12 hours 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#965]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.2.3, 
 
**Comment (Include rationale for comment)**:  Clarification needed for reauthentication at least once per 12 hours
 
"At AAL2, authentication of the subscriber SHALL be repeated at least once per 12 hours, regardless of user activity. Reauthentication of the subscriber SHALL be repeated following no more than 30 minutes of user inactivity. "

Needs some clarification here.  So if the
user has been activie for over 12 hours, does s/he need an authentication or re-authentication? Also, how can the situation of first scenario (reauthentication at least once per 12 hrs regardless of user activity ) will happen if the second scenario ( reauthentication afte 30 min inactivity) is required?

**Suggested Change**: Clarify
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The "first scenario" occurs when the session has been active more or less continuously for 12 hours. At that point, reauthentication is required (only one factor is required at AAL2, unlike a new authentication that requires 2 factors). 

Some clarification to this session is being introduced in response to #634; if this is still unclear, please suggest better language.
