### ISSUE TITLE
Exception to statement in 4.3.1 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#967]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 4.3.1, 6
 
**Comment (Include rationale for comment)**:  Exception to statement in 4.3.1
 
Clarity in security capabilities.

Reads: "In this document, authenticators always contain a secret. Some of the classic authentication factors do not apply directly to digital authentication. For example, an ID badge is something you have, and may be useful when authenticating to a human (e.g., a security guard), but is not in itself an authenticator for digital authentication."

**Suggested Change**: PIV cards with chips are an exception to this statement and are commonly used in the government.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We'll come up with something better.
