### ISSUE TITLE
Start a new line entry for each item

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#969]
### All Fields Are Required
**Organization Name (N/A, if individual):** DCMA

**Organization Type (see below for codes)**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: 4.2., 13.c and d
 
**Comment (Include rationale for comment)**: Start a new line entry for each item

Formatting
 
**Suggested Change**:
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Fixed via #617
