### ISSUE TITLE
Storing Hints

### ISSUE THREAD

**Issue by UppaJung** [usnistgov/800-63-3#97]
**Organization**: Microsoft Research

**Type**: 2

**Reference (Include section and paragraph number)**:
 5.1.1.2 paragraph 3.
   Memorized secret verifiers SHALL NOT permit the subscriber to store a "hint" that is accessible to an unauthenticated claimant. Verifiers also SHALL NOT prompt subscribers to use specific types of information (e.g., "What was the name of your first pet?") when choosing memorized secrets.

**Comment (Include rationale for comment)**:
   Some mechanisms for storing memorized system-generated secrets allow storing of hints that can be safely shared with unauthenticated claimants.  In these schemes, the system generates a set of cue words (hints) and a random secret that is _independent of_ the secret.  Since they are independent, there is no risk that the hint could in any way compromise the secret.  The user uses the hints as pegs to try to remember parts of the secret.  For example, finding a way to associate a hint word with a word of the secret by generating some mental association.  See 

   https://www.internetsociety.org/sites/default/files/blogs-media/testing-computer-aided-mnemonics-feedback-for-fast-memorization-of-high-value-secrets.pdf

  Since there is no risk to using hints that were not influenced by the subscriber's secret, and did not influenced the choice of the subscriber's secret, this class of hints should not be forbidden.

**Suggested Change**:
   Memorized secret verifiers SHALL NOT store and make available to an unauthorized claimant any "hints" or other information to help the subscriber remember the secret, unless this hint was generated by the system at random and independently of the generation of the secret.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by mridentity** [comment]
Hints are being gradually recognized as anti-patterns among security experts. It's another casually introduced approach to address the catastrophic shortcomings of the first casually introduced approach - the password. Fundamentally, "hints" is a concept demands more than just a binary process yet today's systems do not have good enough AI to handle them properly, less securely. For some reasons, those account secret questions always remind me auto-flush sensors mounted on the public toilets, they rarely function as designed but surely make their users nervous.

**Comment by jimfenton** [comment]
The solution being proposed is not a subscriber-stored hint but a set of system-generated hints, and therefore doesn't apply to the text being commented upon.

The proposed solution is interesting, but I am unaware of substantial operational experience with this and therefore it seems premature to include it in this guideline.
