### ISSUE TITLE
Please clarify if the IAL-AAL-FAL assessment processes are in addition to or in place of M-04-04 risk determination guidance. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#971]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5, 3
 
**Comment (Include rationale for comment)**:  Please clarify if the IAL-AAL-FAL assessment processes are in addition to or in place of M-04-04 risk determination guidance. 
 
OMB M-04-04 says that NIST has authority for "developing complementary e-authentication technical guidance that agencies will use to identify appropriate technologies, based on the analysis process described here." NIST is at risk of overstepping this authority by changing the analysis process itself. Specifically, NIST says "This guideline recommends that agencies meet M-04-04 requirements by separately evaluating the impact that could result from (1) a true authentication error (a false claimant using a credential that is not rightfully theirs) and (2) an identity proofing error." One could argue that NIST is stepping into a gray area where it appears to be superseding OMB.

**Suggested Change**: Please clarify if the IAL-AAL-FAL assessment processes are in addition to or in place of M-04-04 risk determination guidance. 

This questions appears to be answered in Section 5.3, but please review the entire document to ensure consistency.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE with April 1 update to -3.
