### ISSUE TITLE
Referring to M-04-04 LOA as "Legacy" contributes to confusion over whether NIST is implementing or superseding OMB. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#972]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.3, Table 5-1
 
**Comment (Include rationale for comment)**:  Referring to M-04-04 LOA as "Legacy" contributes to confusion over whether  NIST is implementing or superseding OMB.
 

**Suggested Change**: Remove the word "Legacy" from the title or replace it with another word such as "Baseline" to correctly depict that M-04-04 is still valid and in effect.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE with April 1 update to -3.
