### ISSUE TITLE
Is it necessary to eliminate LOA2 altogether? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#973]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.3, Tables 5-1 and 5-2
 
**Comment (Include rationale for comment)**:  Is it necessary to eliminate LOA2 altogether? 
 
OMB thought 4 levels were appropriate, but now there are only 3 effectively.

**Suggested Change**: Instead of making LOA2 and LOA3 the same, could LOA2 be redefined as "IAL1 with Personal Data" and AAL2 and FAL2?
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE with April 1 update to -3.
