### ISSUE TITLE
Are agencies required to define a process to determine IAL-AAL-FAL or can they stick to M-04-04 LOAs alone if they choose to? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#974]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.3.2, 1
 
**Comment (Include rationale for comment)**:  Are agencies required to define a process to determine IAL-AAL-FAL or can they stick to M-04-04 LOAs alone if they choose to? 

 
The AAL decision tree in Figure 5-1 is described as a "possible path", suggesting the specific method is notional. But are agencies required to either implement this process or develop their own? Same question applies for IAL.

**Suggested Change**: Please clarify if a new requirement is being levied on agencies.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE with April 1 update to -3.
