### ISSUE TITLE
Additional guidance on how to examine privacy risks when determining the IAL level is needed. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#975]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.2, Table 4-2 and the para before it
 
**Comment (Include rationale for comment)**:  Additional guidance on how to examine privacy risks when determining the IAL level is needed. 
 
"Agencies SHALL consider the privacy risks of stronger identity proofing and SHALL NOT select an IAL that is higher
than necessary for the business purpose of the digital service."

This statement is very important in that it allows a considerable amount of flexibility that was absent from previous versions of SP 800-63. For example, you can have a LOA4 system with IAL1, self-asserted identity! This is a significant departure from baseline LOA4 requirements and as such requires a stronger explanation.

**Suggested Change**: Additional guidance on how to examine privacy risks when determining the IAL level is needed. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This is a candidate topic for the implementation guide that is planned following the publication of the 800-63-3 suite of documents.
