### ISSUE TITLE
Evaluate if IAL deviation from LOA requirements should be limited to one level. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#976]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.2, Table 4-2
 
**Comment (Include rationale for comment)**:  Evaluate if IAL deviation from LOA requirements should be limited to one level.
 
While accepting that there are privacy concerns, should limits be placed on how far IAL can deviate from its LOA requirement? If you limited the deviation to one level, that would be more consistent with the AAL standard. For example, an LOA4 system would start with an IAL3 requirement. IAL3 could be reduced to IAL2 (one level below) based on assessment of privacy risk, but not IAL1.

**Suggested Change**: Evaluate if IAL deviation from LOA requirements should be limited to one level.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is OBE via the risk assessment language added to -3
