### ISSUE TITLE
Please address the issue of agencies issuing credentials to foreign nationals residing in foreign countries. Or else state explicitly that agencies are free to pursue 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#977]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: , 
 
**Comment (Include rationale for comment)**:  Please address the issue of agencies issuing credentials to foreign nationals residing in foreign countries. Or else state explicitly that agencies are free to pursue their own solution.
 
SP 800-63-2 contains the following note (#14) in the Identity Assurance section: "Agencies issuing credentials to foreign nationals residing in foreign countries determine what constitutes a valid Government issued ID as required." There is no statement that corresponds to this in draft Rev 3. 

**Suggested Change**: Please address the issue of agencies issuing credentials to foreign nationals residing in foreign countries. Or else state explicitly that agencies are free to pursue their own solution.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
We were purposefully agnostic to the type of evidence (government id, financial account) and outcome driven (characteristics of evidence).  Now, agencies can evaluate identity evidence, such as a form of id issued by a foreign entity, and determine if it meets the criteria (weak, strong, superior, etc.)  Therefore, there is no need for NIST to include the old footnote as the guidance already support agencies finding their own solution, should the evidence they select meet the requirements.

That said, implementation guidance that will be released at a later date will talk about evidence that meets the requirements in the table.  It would be inclusive of every piece of evidence in the world, but it will give ideas.
