### ISSUE TITLE
"Legacy" M-04-04 IAL requirements - unless OMB is issuing a revision, M-04-04 is still in effect. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#978]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.2, Table 4-1
 
**Comment (Include rationale for comment)**:  "Legacy" M-04-04 IAL requirements - unless OMB is issuing a revision, M-04-04 is still in effect.
 

**Suggested Change**: Suggest substituting the word "Baseline" for "Legacy" to avoid any suggestion that M-04-04 is being superseded.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
OBE by update to -3
