### ISSUE TITLE
"Legacy" M-04-04 AAL requirements - unless OMB is issuing a revision, M-04-04 is still in effect. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#979]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4, Table 4-1
 
**Comment (Include rationale for comment)**:  "Legacy" M-04-04 AAL requirements - unless OMB is issuing a revision, M-04-04 is still in effect.
 

**Suggested Change**: Suggest substituting the word "Baseline" for "Legacy" to avoid any suggestion that M-04-04 is being superseded.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The relationship between SP 800-63-3 and OMB M-04-04 is changing significantly. See the [TIG blog](http://trustedidentities.blogs.govdelivery.com/2017/03/31/a-minor-plot-twist-comment-period-extended-for-part-of-sp-800-63-3/) for more details.

SP 800-63B hasn't yet caught up with all these changes, so leaving this issue open for now.

**Comment by jimfenton** [comment]
M-04-04 based requirements were removed by f6bc8cb840feeea99401ea9d5e82cd0d430052b7
