### ISSUE TITLE
Replacing PSTN (SMS or voice) OOB will be difficult

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#980]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.3.2, 2
 
**Comment (Include rationale for comment)**:  "Out-of-band authentication using the PSTN (SMS or voice) is discouraged and is being considered for removal in future editions of this guideline." 
 
Without this option, implementing AAL2 for citizen services will be very difficult. 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
We note that deployment of alternative forms of 2-factor authentication will take time, which is why the note was included but PSTN is still acceptable for out-of-band authentication in this revision.
