### ISSUE TITLE
"Authenticated Protected Channel" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#981]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 3, 
 
**Comment (Include rationale for comment)**:  "Authenticated Protected Channel"
 
"Authenticated Protected Channel" - Note that TLS supports mutual authentication, where both ends of the connection authenticate to each other. This is useful for app-to-app, server-to-server communications.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Noted, although authenticated protected channels are used (especially in 800-63B) in many places where mutual authentication is impractical, but authentication of the server is needed.
