### ISSUE TITLE
While it is understood that this section doesn't attempt to provide a complete survey of assertion technologies, the fact that WS-Federation isn't included seems like 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#982]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 11, 
 
**Comment (Include rationale for comment)**:  While it is understood that this section doesn't attempt to provide a complete survey of assertion technologies, the fact that WS-Federation isn't included seems like an omission.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
As you note, this section doesn't attempt to provide a complete survey of assertion technologies.
