### ISSUE TITLE
Strike requirement regarding third party data service for only one piece of evidence 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#983]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.7, Table 4-3. IAL Requirements Summary
 
**Comment (Include rationale for comment)**:  Strike requirement regarding third party data service for only one piece of evidence
 
Validation for IAL 2 stipulates that "Validation against a third party data service SHALL only be used for one piece of presented identity evidence." Only one aggregation service can be used to verify the identity documents, yet multiple identity documents are required. The other(s) must be verified directly with the source, which will require agencies to have agreements and connections with many identity document issuers and is impractical.

For the use of two Strong pieces of evidence to be practical, agencies must be able to use aggregation services to validate the data with the issuing sources (a requirement of Strong per Table 5-2). Otherwise, agencies will be in a position of having to connect directly to, and manage going forward, each data source. For example, all 50 states DMVs, 6500+ birth certificate issuers, hundreds of banks, etc.

**Suggested Change**: Strike the requirement
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Issuing source will be redefined to alleviate the challenge of getting to the actual source.  That said, this requirement is about KBV, and we will not change the requirement that KBV can only be used to verify 1 piece of evidence.

Follow #582 to see how we resolve the issuing source definition.
