### ISSUE TITLE
Strike the requirement from Table 4.3 or allow for confirmation of details from only one source 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#984]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.2.2.1, Table 5-2. Verifying Identity Evidence
 
**Comment (Include rationale for comment)**:  Strike the requirement from Table 4.3 or allow for confirmation of details from only one source
 
Related to STRONG strength row; "All personal details and evidence details have been confirmed as valid by comparison with information held or published by the issuing source."
Since an aggregator can be used for one ID (see Table 4.3), agencies must connect directly to each issuing source for the other piece of Strong evidence. This requirement will require agencies to have agreements and connections with many identity document issuers, which is impractical.

For the use of two Strong pieces of evidence to be practical, agencies must be able to use aggregation services to validate the data with the issuing sources. Otherwise, agencies will be in a position of having to connect directly to, and manage going forward, each data source. For example, all 50 states DMVs, 6500+ birth certificate issuers, hundreds of banks, etc.

This exchange of identity data by an issuing source proliferates the sharing of identity data, erodes the privacy of our citizens, and places a burden on such regulated organizations to serve as identity verifiers.
• Citizens will be effectively divulging to the Federal agency that they transact with the issuing organization; Likewise, the organization will know that the individual is transacting with the Federal Government
• Relying on issuing source to provide this information / validation exposes the sources to increased attack by fraudsters
• If the information is actual “published” by the issuing source (as a result of this publication), then they would be making personally identifiable information (PII) widely available

**Suggested Change**: Strike the requirement from Table 4.3 or allow for confirmation of details from only one source
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Fix to #582 will resolve this.
