### ISSUE TITLE
Rework for options similar to LOA3 in SP 800-63-2 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#985]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.3.1, Table 5-3. Verifying Identity Evidence
 
**Comment (Include rationale for comment)**:  Rework for options similar to LOA3 in SP 800-63-2
 
STRONG Identity Verification requires either a physical comparison or cryptographical bound biometric component. This requires a user to be in possession of or have access to video (or more complex methods) for physical comparison or a trusted biometric capture device (per 63B, 5.2.3). The IRS is concerned that these requirements could have a significant impact to coverage as many users will not have access to such capabilities.

There are many ways to ensure “that the presented identity information is valid” that should be acknowledged and considered acceptable per SP 800-63. For example, agencies such as the IRS often amass confirmed data about the individuals they are proofing through years of interacting with them, their employers, and other agencies (e.g., SSA). This data, which includes personal biographical (e.g., name, DoB, current address, etc.) and transactional data, can be used to validate the identity in the context of the actual agency with whom the user is transacting in lieu of photo identification.

**Suggested Change**: Rework for options similar to LOA3 in SP 800-63-2
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Will be resolved via #643
