### ISSUE TITLE
Provide supporting research regarding VOIP that includes cost of technology / services that exclude VOIP. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#987]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.3.1, Second paragraph
 
**Comment (Include rationale for comment)**:  Provide supporting research regarding VOIP that includes cost of technology / services that exclude VOIP.
 
The IRS is concerned that the requirement excluding VOIP from out-of-band authentication ("Methods that do not prove possession of a specific device, such as voice-over-IP (VOIP) [...], SHALL NOT be used for out-of-band authentication") is impractical. The cost of technology and/or services that exclude VOIP may far outway the risk (in terms of likelihood and scale) of a successful attack.  The implication that VOIP is inherently insecure is not necessarily accurate. In addition, this requirement may be impractical to control given that the public, industries, and Federal agencies are adopting VOIP. 

SMS text or traditional voice do not prove possesion of a specific device either. The authenticator is not a device, the authenticator is an out-of-band communication, which is dificult to attack at scale. 

**Suggested Change**: Provide supporting research regarding VOIP that includes cost of technology / services that exclude VOIP.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The implication is not that VoIP is inherently insecure, it is that VoIP does not establish the possession of a particular physical device. If a subscriber can access a VoIP service using just a password, then two-factor authentication could consist of a memorized secret + the VoIP service password. Two-factor authentication requires two _different_ authentication factors.

As noted, SMS and traditional voice do not strongly prove possession of a specific device, but they do so more strongly than VoIP (or email). Accordingly, they are permitted but discouraged in -63B.

Alternative communication services that are appropriate for out-of-band authentication are an appropriate topic for the implementation guide that is planned after the release of the 800-63-3 suite.
