### ISSUE TITLE
Rework for baseline requirement/credentials options similar to LOA3 in SP 800-63-2 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#988]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: General Comment, General Comment
 
**Comment (Include rationale for comment)**:  Rework for baseline requirement/credentials options similar to LOA3 in SP 800-63-2
 
Whether  Risk Assessments result in level 2 or 3, the baseline requirements are now the same (e.g., multiple identity sources, multi-factor authentication), significantly increasing the level of effort to bring low risk applications (LOA 2) online as well as the volume of high-assurance credentials that must be issued. At the same time, requirements to employ sophisticated technology or trained personnel to inspect security features of identification documents / cards, combined with deprecation of Out of Band SMS and voice, will make the cost of credentials even more expensive. 

It took nearly a decade from the release of SP 800-63-1 until agencies started implementing LOA3. Because SP 800-63-3 does not allow any of the identity proofing methods from past versions, much of the progress that has been made will be ignored and reversed.

**Suggested Change**: Rework for options similar to LOA3 in SP 800-63-2
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Somewhat OBE with April 1 update to -3. In addition, this revision reflects state of the market to include the mitigations required to prevent attacks at scale. In this revision, NIST will not decrease requirements for any assurance level.
