### ISSUE TITLE
Risk of reducing access for disadvantaged populations 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#989]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: General Comment, General Comment
 
**Comment (Include rationale for comment)**:  Risk of reducing access for disadvantaged populations
 
Regardless of whether proofing is performed in person or remote, the standard is likely to reduce access for disadvantaged populations. To receive a level 2 credential the applicant must have at least one photo ID from a regulated organization that also provides identity validation information in order to transact with the federal government at IAL 2. This approach further disenfranchises already disadvantaged populations and will have the affect of driving such people to other channels (e.g., mail, over the counter).  Further, a significant number of taxpayers do not have a photo ID and will not even be able to identity proof in-person, effectively shutting them out of services via the online channel.
Not all regulated document issuers permit their documents to be used for this purpose either. This version of the document will also make it harder to identity proof foreign individuals as the ability to validate ID security features and identity data with the foreign issuing sources will not exist initially.

In the current version of SP 800-63-3, NIST has taken the high-level concepts for remote identity proofing – resolution, validation, and verification – and applied them, not to identities, but to specific identity “evidence” in the form of physical identification documents created by organizations such as licensing agencies and regulated industries. Such an approach greatly limits agency options for conducting identity proofing, expands the sharing of identity data by organizations for whom identity proofing is a side mission, and reduces coverage for the poor and disenfranchised who must obtain photo identification cards to transact with the Government online.

There are many ways to ensure “that the presented identity information is valid” that should be acknowledged and considered acceptable per SP 800-63. For example, agencies such as the IRS often amass confirmed data about the individuals they are proofing through years of interacting with them, their employers, and other agencies (e.g., SSA). This data, which includes transactional data and personal biographical data (e.g., name, DoB, current address, etc.) can be used to validate the identity in the context of the actual agency with whom the user is transacting in lieu of photo identification.

**Suggested Change**: Rework for options similar to LOA3 in SP 800-63-2
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
-A evidence can be virtual and physical, and not all require photos, etc. so be acceptable at IAL2.  In addition, we added a trusted referee process that gives agencies a lot of latitude to serve their populations.  Finally, the rework of -3 gives agencies risk-based exceptions to the NIST requirements.
