### ISSUE TITLE
Account-based lock-outs are known to fail against many guessing attacks

### ISSUE THREAD

**Issue by UppaJung** [usnistgov/800-63-3#99]
**Organization**: Microsoft Research

**Type**: 2

**Reference (Include section and paragraph number)**:
5.2.2

"It MAY be necessary to implement controls at the verifier to protect against online guessing attacks. An example requirement for such authenticators is given in the authenticator requirements above: the verifier shall effectively limit online attackers to 100 _consecurive_**[SIC]** failed attempts on a single account in any 30 day period." 

**Comment (Include rationale for comment)**:

This defense only works against attacks that target a single user.  It is disastrous against attacks that try the 100+ most common passwords against all accounts--which is a common attack against Internet-connected services.  If an attacker tries more than the 100 most-common passwords against all accounts, all accounts will be locked out.  Users will be inconvenienced.  The administrator will have no choice but to unlock allow accounts and reset the failure counts to 0.  The attacker will then try passwords 101-200 and everyone will be locked out again.  This process repeats until the administrator simply turns off the defense.  This is why most large-scale services don't use account-based lock-out.   

**Suggested Change**:

Modern services use IP-based lockouts.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
The spelling error was corrected by #64.

We acknowledge the potential for denial-of-service attacks using account-based throttling. The language in 5.2.2 does allow the use of IP address as well as account when counting failed authentication attempts. However, the use of IP address alone allows attackers with access to many IP addresses (such as those controlling botnets) to make an unacceptable number of authentication attempts in a short period of time. This is also a concern for services accessible via IPv6, where enormous numbers of IP addresses are available, even to those without a botnet at their disposal.

**Comment by mridentity** [comment]
The fundamental solutions to the issue will need to do one of two things:
a) Incur meaningful cost to the attackers (the blockchain technologies could have an interesting play here).
b) Diminish the hope of brute-force type of attacks, such as by switching to PKI based authentication from the password.
Meanwhile escalating delays introduced after each failed login attempt continues to be the most viable solution before either of the above becomes prevalent. IP based throttling could also have negative collateral effect on users shared the same outbound IP with the attacker, in addition to the issues pointed out by Jim.
