### ISSUE TITLE
Why was LOA divided into IAL, AAL, and FAL? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#990]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: , 
 
**Comment (Include rationale for comment)**:  Why was LOA divided into IAL, AAL, and FAL?
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
-3 describes the rationale.  Also OBE by April 1 update to -3.
