### ISSUE TITLE
Why can we only validate proofing data against a single data agregator? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#992]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: , 
 
**Comment (Include rationale for comment)**:  Why can we only validate proofing data against a single data agregator?
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
No recommended edit.
