### ISSUE TITLE
Does FAL mean SAML? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#994]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: , 
 
**Comment (Include rationale for comment)**:  Does FAL mean SAML? 
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
FAL is the Federation Assurance Level, and it's a set of requirements not tied to a specific technology.

**Comment by paul-grassi** [comment]
See above.
