### ISSUE TITLE
To do remote fingerprinting the IRS will need downloadable software to register biometric devices with a CSP 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#995]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: , 
 
**Comment (Include rationale for comment)**:  To do remote fingerprinting the IRS will need downloadable software to register biometric devices with a CSP
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
No suggested change.
