### ISSUE TITLE
", and the number of consecutive activation failures is limited" There should be a higher level authentication piece that allows for reset after too many 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#996]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 2.2, 2
 
**Comment (Include rationale for comment)**:  ", and the number of consecutive activation failures is limited" There should be a higher level authentication piece that allows for reset after too many failures.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
No suggested change.  However, 800-53 also applies which discusses lockout.
