### ISSUE TITLE
"All PII collected as part of the enrollment process SHALL be protected to ensure confidentiality, integrity, and attribution of the information source." Including encryption and 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#997]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.2, 2
 
**Comment (Include rationale for comment)**:  "All PII collected as part of the enrollment process SHALL be protected to ensure confidentiality, integrity, and attribution of the information source." Including encryption and backup of data stores that are vulnerable to ransomware.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
No recommendation provided
