### ISSUE TITLE
The CSP MAY collect biometrics for the purposes of non-repudiation and re-proofing.They MAY utilize the SSDMF and/or the National Birth Certificate Database. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#998]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 4.4.1.7, 1
 
**Comment (Include rationale for comment)**:  The CSP MAY collect biometrics for the purposes of non-repudiation and re-proofing.They MAY utilize the SSDMF and/or the National Birth Certificate Database.
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
No suggested edit provided.
