### ISSUE TITLE
"The CSP SHALL NOT use KBV questions for which the answers do not change regularly over a period of time (e.g., What was your first 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#999]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.3.2, 2
 
**Comment (Include rationale for comment)**:  "The CSP SHALL NOT use KBV questions for which the answers do not change regularly over a period of time (e.g., What was your first car?)."
 
How will these be verified? Will the KBV ask new questions after each sign in?

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
No recommended edit provided.
